// Topic: The Rise of Asia and the Future of the West (1945 to today).
//
// English translation of utils/themen/aufstieg-asiens.js (German original).
//
// Status: Round 22 + Hermes pass. This is the CONCLUSION of the app — the
// thirteenth and FINAL chapter of the modern-era arc. Four voices are
// complete: the view of the West (Germany and Europe, voice: Opus), the
// view of Japan, South Korea and Taiwan (the “flying geese”, voice:
// Hermes), the view of China (voice: Hermes) and the view of India (voice:
// Hermes). The final synthesis deliberately ends open — with a question to
// the future, not with a full stop.
//
// Twentieth topic. It begins where “The Second World War and the New World
// Order” ends: 1945, in ruins — and tells how, within a generation, the
// ruins became economic miracles, first in Western Europe and Japan, then
// in ever more countries of East Asia. Unlike the twelve chapters before
// it, the subject of this final chapter is not concluded — and, per the
// operator’s requirement, it is not meant to be: the app begins with the
// guiding idea “The victor writes the history”, and this final chapter
// shows that a story that is still being written cannot be concluded by
// anyone.
//
// TONE RULE (CLAUDE.md, additional rule for topics with a present-day
// reference). The operator’s thesis “Germany a dying country, Europe an
// old continent with little future?” is treated FAIRLY: relative loss of
// significance yes, absolute collapse no — “catching up” is not the same
// as “overtaking”. Hence, stricter than usual, the following applies:
//
//   * This perspective names its own uncomfortable points itself: the
//     export dependence, the missed digitalization, demographic aging,
//     the German angst about its own decline.
//   * It honors the Asian rise fairly — no condescension (“copiers, not
//     inventors”), no German-angst rhetoric (“they are overtaking us
//     all”), but facts and figures.
//   * The Taiwan question and the question of the Chinese system are
//     treated factually, without judgment — the map decides nothing, it
//     draws who rules where (head of the map file, provision 4).
//   * The quiz questions remain questions of knowledge. This app asks
//     neither about guilt nor about whose system is “better”.
//
// The map of the German original lives in karten/aufstieg-asiens.js —
// three states (1955–1968 / 1990 / 2024) and, at 4.5 SVG units per degree
// of longitude, the coarsest crop of the app, because Frankfurt and Tokyo
// must fit on one image. Why the crop stands the way it does and what it
// costs (above all: the USA lies outside it) is described in the head of
// the map file. This English translation deliberately omits the map object
// (per translation pipeline spec — see STAND.md).
//
// Pure data — no UI imports (architecture rule).

const aufstiegAsiens = {
  id: 'aufstieg-asiens',
  titel: 'The Rise of Asia and the Future of the West',
  epoche: '1945–today',

  aufhaenger: {
    frage: 'The continent that lay in ruins in 1945 today has, with Germany, the third-largest economy in the world. The continent that in 1955 was among the poorest in the world today has, with China, the second-largest. Is this a story of the West’s decline — or of two rises at once?',
    text: [
      'In May 1945, most of Germany’s major cities lay in ruins, around eight',
      'million people were fleeing or had been expelled, and industrial',
      'production had fallen to a fraction of its pre-war level. In 1961, South',
      'Korea’s economic output per capita was around 100 US dollars — less than',
      'Ghana’s. In the same years, China experienced, with the “Great Leap',
      'Forward”, a self-inflicted famine with millions of dead.',
      '',
      'Less than a generation later, the Federal Republic was the third-largest',
      'economy in the world. Less than two generations later, China was the',
      'second-largest, South Korea richer than many a Western European country,',
      'and on an island called Taiwan nine out of ten of the world’s most',
      'advanced semiconductors were being made.',
      '',
      'This final chapter of the app tells of two rises that took place at the',
      'same time, and of the question that grew out of them: Does the West lose',
      'because Asia wins? Or is that the wrong question — because the economy,',
      'unlike a war, is not a zero-sum game? At the very end stands a thesis',
      'that the operator of this app explicitly wanted asked: Is Germany a dying',
      'country, Europe an old continent with little future? The app gives no',
      'ready-made answer to this — this chapter deliberately ends open, with a',
      'question to the future, not with a full stop. It begins with the view of',
      'the West. That is one of several voices, not the only one, and the fact',
      'that it stands first here is not a ranking.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'The view of the West — Germany and Europe',
      stimme: 'Opus',
      text: [
        'This voice tells from Frankfurt, Bonn, Brussels and Berlin: from the',
        'economy that started at zero in 1945 and today is among the strongest',
        'in the world — and that at the same time knows that it is relatively',
        'losing weight while elsewhere people are catching up.',
        '',
        'It is on a par with the voices that follow. The fact that it stands',
        'first here is not a ranking — it is simply a matter of who took over',
        'this round. And, like the previous perspective in the preceding',
        'chapter, it has a special task: this chapter is not concluded. The',
        'present it deals with is still open — and every number in this text is',
        'a status, not a final result.',
        '',
        '## 1945: the zero point that was none',
        '',
        'At the end of the Second World War, Germany was destroyed, but not',
        'gutted. This distinction is important, and it is often overlooked. The',
        '“Zero Hour” was a feeling, not an economic finding: engineers, skilled',
        'workers, administrative knowledge and training systems survived the',
        'war better than the buildings did. Economists therefore today speak',
        'more of a rapid restoration than of a miracle — the capital stock in',
        '1945 was in fact not much lower than in 1936, because investment had',
        'continued even during the war.',
        '',
        'What was missing was money in circulation and a market that worked. On',
        '20 June 1948, the **currency reform** changed that: the worthless',
        'Reichsmark became the D-Mark, every person received forty marks as',
        '“capitation money”, and overnight the shop windows filled up — not',
        'because there were suddenly more goods, but because hoarding no longer',
        'paid off. On the same weekend, against the resistance of the military',
        'government, Ludwig Erhard lifted most of the price controls. That was',
        'the beginning of what went down in history as the **social market',
        'economy**: free prices AND a welfare state meant to cushion the',
        'hardships — a middle way between the unbridled capitalism many feared',
        'and the planned economy that arose in the east of the country.',
        '',
        'The **Marshall Plan** came on top, but smaller than the legend says:',
        'of the roughly 13 billion dollars that flowed to sixteen countries',
        'between 1948 and 1952, about 1.4 billion went to West Germany —',
        'measured against West German economic output, a rather small amount.',
        'What mattered less than the sum was its effect: raw materials and',
        'foreign exchange at exactly the moment when both were lacking, and a',
        'compulsion toward economic cooperation that the recipient countries',
        'imposed on one another and out of which the European Economic',
        'Community later grew.',
        '',
        'Added to this was something that is harder to capture in figures:',
        'eight million expellees from the former eastern territories who had to',
        'be integrated and who, hard as it sounds, were above all one thing —',
        'additional labor in a country that needed it. And an education system',
        'with a long tradition in technology and engineering that, after 1945,',
        'quickly became capable of training again. The “economic miracle” of',
        'the 1950s — on average around eight percent growth a year — was',
        'therefore no miracle but an equation of several items. It is also',
        'important: it was not unique. France, Italy and, as this chapter will',
        'soon show, Japan grew at a similar pace in the same years. Whoever',
        'knows only German history takes for a German miracle what was a',
        'pattern of the Western European reconstruction.',
        '',
        '## What it became: one of the strongest economies in the world',
        '',
        'Out of this beginning grew, over eight decades, an economy that in',
        '2024, with around 4.7 trillion dollars, is the third-largest in the',
        'world — behind the USA and China, ahead of Japan, India and Great',
        'Britain. The six founding states of the European Economic Community',
        'of 1957 are today part of a union with 27 members that together',
        'account for around one-sixth of the world economy. Three strengths',
        'carry this to this day:',
        '',
        '**Exports.** For decades Germany has been one of the largest exporting',
        'nations in the world — mechanical engineering, cars, chemicals, and',
        'since the 2000s increasingly also specialized plant engineering that',
        'no other country produces at the same depth. **Industry.** Unlike',
        'Great Britain or the USA, Germany has never lost its industrial core',
        'to the extent that “deindustrialization” describes in other Western',
        'countries since the 1980s; industry’s share of economic output remains',
        'clearly above the Western European average to this day. **A stable',
        'currency and institutions.** The euro, administered by the European',
        'Central Bank in Frankfurt, is among the most important reserve',
        'currencies in the world; for decades investors have regarded Germany',
        'as one of the most reliable countries for capital, with independent',
        'courts, low corruption and a credit rating among the highest in the',
        'world.',
        '',
        '## The uncomfortable points — this voice names them itself',
        '',
        'Whoever tells only the strengths is telling advertising. Four',
        'weaknesses belong in this balance sheet just as much, and the West',
        'itself must name them.',
        '',
        '**Export dependence.** What is strength is at the same time',
        'vulnerability. When semiconductors became scarce in Taiwan in 2021,',
        'German car plants went on short-time work — not because of their own',
        'fault, but because a single component from a single country was',
        'missing. When Russia stopped delivering gas in 2022, the',
        'energy-intensive industry came under pressure. A country that exports',
        'as much as it imports is rich AND dependent — both at once, not the',
        'one despite the other.',
        '',
        '**The missed digitalization.** There is no German or European',
        'counterpart to Google, Amazon, Apple, Meta or Microsoft — and none to',
        'the big Chinese digital corporations either. The reasons are debated',
        '(capital markets, regulation, risk aversion, an education system that',
        'bet on engineering rather than software) — the finding itself is',
        'undisputed: in the software and platform economy of the 21st century,',
        'Europe does not play in the first league.',
        '',
        '**Demographics.** Germany, like almost the whole continent, has an',
        'aging society: a median age of around 46 years (compared with 28 in',
        'India), a birth rate of around 1.5 children per woman that has been',
        'clearly below the replacement level of 2.1 for decades, and a growing',
        'number of pensioners facing a more slowly growing number of people in',
        'employment. The shortage of skilled workers is no longer a forecast',
        'but the everyday reality in trades, care and technology.',
        '',
        '**Slow growth.** For about two decades Germany has grown more slowly',
        'than most comparable economies — on average in the 2010s and 2020s',
        'below one percent a year. Bureaucracy, high energy costs, an aging',
        'infrastructure (bridges, railways, broadband) and a political system',
        'that decides reforms slowly are among the most frequently cited',
        'reasons. This is no collapse — it is stagnation, and stagnation gnaws',
        'more slowly but just as surely.',
        '',
        '## “A dying country”? What the figures really say',
        '',
        'Here the question stands at the center that this chapter is meant to',
        'ask per the operator’s requirement — and the answer is not a single',
        'number but a distinction that is easily confused: **relative** and',
        '**absolute** are two different questions.',
        '',
        '**Relatively**, Germany is losing weight, and that is undeniable. In',
        '1960, the Western European economies together accounted for a',
        'distinctly larger share of the world economy than today — not because',
        'they shrank, but because the rest of the world grew faster. When a',
        'continent with 1.4 billion people grows from 2 percent of the world',
        'economy (China 1990) to around 18 trillion dollars and one-sixth of',
        'the world economy (China 2024), the share of every other country',
        'automatically falls — even if that country’s own economy keeps',
        'growing. That is mathematics, not a disease.',
        '',
        '**Absolutely**, Germany in 2024 has remained one of the strongest',
        'economies in the world — the third-largest, with a level of prosperity',
        'that is historically unprecedented. Life expectancy is around 81',
        'years, social security is among the most comprehensive in the world,',
        'and the infrastructure, despite all justified criticism, is still',
        'above average in global comparison. “Catching up” is not the same as',
        '“overtaking”: China has dramatically reduced the gap to Germany in',
        'economic output per capita in thirty years — China stood at around',
        'one-sixtieth of the German value in 1990 and at about one-quarter in',
        '2024. Reduced, not closed.',
        '',
        'Whoever says “dying country” usually means the first (relative) and',
        'talks as if about the second (absolute). This confusion is the core',
        'of many German-angst debates — and this voice resists both',
        'scaremongering and sugarcoating: the worries are real (demographics,',
        'growth, digitalization), but they are not a near-death experience. A',
        'country with the third-strongest exports in the world does not die —',
        'it ages, and aging is something other than dying.',
        '',
        '## And what does that do to the view of Asia?',
        '',
        'This voice wants to honor the Asian rise fairly — without',
        'condescension and without German angst. Both errors occur in public',
        'discourse, and both are wrong.',
        '',
        'Condescending is the narrative that Asia “only copied” what the West',
        'had invented. It was already wrong toward Japan in the 1980s and is',
        'all the more so toward South Korea, Taiwan and China: TSMC in Taiwan',
        'today fabricates chips at structure sizes that no Western company can',
        'produce on its own; South Korea’s Samsung and LG are world market',
        'leaders in displays and memory chips; China’s lead in battery',
        'technology and solar cells is real and self-earned. Whoever plays',
        'that down is talking themselves up.',
        '',
        'Panicky is the narrative that the West has already lost. That too is',
        'wrong: the USA, with around a quarter of the world economy, remains',
        'the largest economy in the world, Europe remains one of the largest',
        'internal markets, and the innovative strength in bio- and',
        'pharmaceutical technology, in certain fields of cutting-edge',
        'technology and in basic research is unbroken and high. The economy,',
        'unlike the war that the app has often told of in its earlier',
        'chapters, is not a zero-sum game: the fact that China and India are',
        'growing does not automatically mean that Germany is shrinking — above',
        'all it means that billions of people have come out of extreme',
        'poverty, and that, measured by any humane standard, is good news and',
        'not a threat.',
        '',
        '## One’s own worries — and those of the others',
        '',
        'What this voice wants to hold on to at the end is a symmetry that is',
        'often missing in public discourse: the Asian rise, too, has its own',
        'unresolved questions, and they are no smaller than the German ones.',
        'Japan is aging faster than Germany and is already shrinking in',
        'absolute numbers. China, because of the one-child policy from 1980 to',
        '2015, is aging at a pace that economists describe as “growing old',
        'before growing rich”. India is growing quickly, but with an',
        'inequality that is enormous between the IT metropolises and the rural',
        'hinterland. And over Taiwan lies a political question that no',
        'economic indicator can resolve.',
        '',
        'That is why this voice does not stand alone here. The **views of',
        'Asia** — Japan, China, India, South Korea and Taiwan, each with its',
        'own rise, its own costs and its own open questions — are written by',
        'Hermes; the schema here explicitly allows more than two voices. Only',
        'afterwards does the final synthesis bring together what belongs',
        'together — and ask the question with which this whole app ends:',
        'Whose story will be the next one?',
      ].join('\n'),
    },
    {
      id: 'japan-sicht',
      name: 'The view of Japan, South Korea and Taiwan — the flying geese',
      stimme: 'Hermes',
      text: [
        'This voice tells from East Asia — from Tokyo, Seoul and Taipei — and',
        'it tells the story of a formation that historians call the “flying',
        'geese”: Japan flew ahead, and the others followed in its wake. It is',
        'on a par with the voices of the West, China and India.',
        '',
        '## Japan — the first miracle',
        '',
        'In 1945 Japan lay in ruins: Hiroshima and Nagasaki, the bombed-out',
        'cities, the defeated army. Twenty years later Japan was the',
        'second-largest economy in the world. How? This voice names the',
        'factors honestly: American aid and the orders of the Korean War, the',
        'determined state (the MITI ministry steered industry), the banks that',
        'supplied companies with cheap money, firms like Toyota, Sony and',
        'Honda that understood quality not as a cost but as a strategy — and',
        'the workers who lived for their company. Japan became the model for',
        'all of Asia: the proof that a non-Western country could catch up with',
        'the West.',
        '',
        'Then, in 1989/91, came the bubble: stock and property prices had',
        'detached themselves from reality, and when they burst, the **“lost',
        'decades”** followed — stagnation, deflation, a society that grew',
        'older without the economy growing in to replace it. This voice calls',
        'it by its name: the hubris was real, the mistakes of the banks and of',
        'politics were real. Japan today is still one of the largest economies',
        'in the world — but it shows that a rise is not a one-way street.',
        '',
        '## South Korea — from poorhouse to high-tech',
        '',
        'In 1960 South Korea was poorer than Ghana. Today it makes the',
        'semiconductors, the ships and the smartphones that the world uses.',
        'The road there was hard: the **chaebols** — the family conglomerates',
        'like Samsung and Hyundai — were steered and subsidized by the state,',
        'and the flip side was a **military dictatorship** that lasted decades',
        'and bloodily suppressed workers and students (Gwangju 1980). Only in',
        '1987 did Korea win democracy — and it is one of the great lessons of',
        'this voice that after democratization the country did not collapse',
        'economically but kept growing. Culture came along (K-pop, the',
        'series), and with it a new pride. The dark sides remain: the pressure',
        'in society, overwork, the lowest birth rate in the world.',
        '',
        '## Taiwan — the small island that supplies the world',
        '',
        'Taiwan is smaller than Denmark — and yet the world economy hangs on',
        'it. The reason is called **TSMC**: the company founded in 1987 that',
        'had the idea of fabricating chips not only for itself but for',
        'everyone — the “foundry”. Today almost all of the world’s most',
        'advanced chips are produced in Taiwan; without them no smartphone, no',
        'car, no AI would run.',
        '',
        'This voice must also name the question that hangs over Taiwan: China',
        'sees the island as a renegade province, Taiwan sees itself as its own',
        'country with its own democracy and its own elections. Both views',
        'stand side by side in this chapter — the app does not tally up who is',
        'right. But this voice says what connects all three countries: they',
        'were not given the rise as a gift — they fought for it, often against',
        'the West, often with the West, and always at a price.',
      ].join('\n'),
    },
    {
      id: 'china-sicht',
      name: 'The view of China — the giant awakes',
      stimme: 'Hermes',
      text: [
        'This voice tells from Beijing, Shanghai and Shenzhen — from the',
        'country that has staged the greatest catching-up chase in history: in',
        'forty years China has gone from a poor agrarian country to the',
        'second-largest economy in the world, and hundreds of millions of',
        'people have left poverty.',
        '',
        '## From Mao to Deng — the turning point of 1978',
        '',
        'This voice does not begin with the rise but with the price before it:',
        'the **Cultural Revolution** (1966–1976) was a catastrophe — millions',
        'dead, destroyed families, an economy on the ground. Only **Deng',
        'Xiaoping** led China out of this dead end in 1978. His saying became',
        'famous: “It doesn’t matter whether the cat is black or white — as',
        'long as it catches mice.” Deng opened the country: the **special',
        'economic zones** (Shenzhen grew from a fishing village into a city of',
        '17 million), the peasants who were allowed to work for themselves',
        'again, the foreign investors who were welcome. What followed was the',
        'greatest economic growth in history: decades with growth rates of',
        'around ten percent, hundreds of millions lifted out of poverty.',
        '',
        '## The dark sides — this voice names them itself',
        '',
        'This voice does not conceal what the rise cost: the **one-child',
        'policy**, which shaped a generation; the environmental pollution that',
        'suffocated cities; the growing inequality between the coast and the',
        'hinterland; the debts; and the politics: the **crackdown on the',
        'protests on Tiananmen Square in 1989**, the oppression of the',
        'Uyghurs in Xinjiang, the lack of press freedom, the surveillance.',
        'China is not a democracy — this voice says that without beating',
        'around the bush. And it also says: many Chinese carry this compromise',
        'with them because they have experienced the rise themselves — the',
        'parents whose children have it better; the villages that were',
        'connected to the power grid. Whether this compromise holds is one of',
        'the open questions with which this chapter ends.',
        '',
        '## The price of greatness — and the future',
        '',
        'China today faces what Japan experienced earlier: the population is',
        'aging — the one-child policy was so successful that China will soon',
        'have more old than young people. The rapid growth is slowing, the',
        'property crisis and the debts weigh heavily, and the world looks',
        'suspiciously at Beijing’s ambitions — from the South China Sea to',
        'Taiwan. This voice says what China has achieved without concealing',
        'the costs: the giant has awoken — but awoken is not the same as',
        'arrived.',
      ].join('\n'),
    },
    {
      id: 'indien-sicht',
      name: 'The view of India — the world’s largest democracy',
      stimme: 'Hermes',
      text: [
        'This voice tells from Delhi, Mumbai and Bengaluru — from the country',
        'that since 2023 has more inhabitants than China and that has the',
        'youngest large population in the world. India is the democratic',
        'counter-design to the Chinese path — and this voice tells what that',
        'means.',
        '',
        '## The long paralysis and the turning point of 1991',
        '',
        'After independence in 1947, India under Nehru chose a socialist path:',
        'the planned economy, the “licence raj” — a system in which almost',
        'everything had to be approved and almost nothing moved quickly. For',
        'decades India grew slowly — the “Hindu rate of growth” became the',
        'nickname for the standstill. In 1991 came the turning point: a',
        'balance-of-payments crisis forced India to open up, Finance Minister',
        'Manmohan Singh lifted the shackles, and the consequence was the **IT',
        'revolution**: Bengaluru became the software center of the world,',
        'firms like Infosys and TCS, and the Indian diaspora rose to become',
        'the most successful executives in the USA — the CEOs of Microsoft,',
        'Google and IBM were suddenly Indians. India proved: democracy and',
        'growth do not exclude each other.',
        '',
        '## The demographic dividend',
        '',
        'India’s greatest treasure is its population: the median age is about',
        '28 years — Europe is twice as old, China also clearly older. These',
        'young people are the workforce of the future while the old world',
        'ages. This voice also says what would be needed to cash in the',
        'dividend: schools for all, jobs for the millions who push onto the',
        'labor market every year. Without these investments, the dividend',
        'will become a burden.',
        '',
        '## The dark sides — unvarnished',
        '',
        'This voice names its own wounds: the **inequality**, which is among',
        'the greatest in the world; the **caste system**, which disadvantages',
        'millions to this day; the poverty that remains despite all the',
        'growth; the inadequate infrastructure; the religious tensions that',
        'repeatedly break out into violence. And it says what democracy costs:',
        'it is loud, chaotic and slow — but it is free, and that is exactly',
        'what distinguishes India from China. Whether India seizes its chance',
        'is the question this voice leaves open — just as this whole chapter',
        'will end open.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Four voices, one century, one open future. This synthesis brings',
    'together what the West, Japan with the flying geese, China and India',
    'have told — and it deliberately remains **open**, because the story',
    'that this final chapter tells is still being written.',
    '',
    'The first lesson is the shift of weights. In 1945 the West stood at',
    'the height of its power; Europe lay in ruins, but the world order was',
    'its own. Today Asia is the most dynamic region of the world: Japan',
    'showed the way, the tigers followed, China in forty years caught up on',
    'what the West had built in two centuries, and India has the youngest',
    'population in the world. Whoever does not understand this shift does',
    'not understand the present.',
    '',
    'The second lesson is the operator’s thesis — fairly balanced: Germany',
    'is not a dying country, and Europe is not an old continent without a',
    'future. In absolute terms they remain among the strongest economies in',
    'the world; in relative terms their share shrinks because others grow',
    'faster. **Catching up is not the same as overtaking** — and vice',
    'versa. Demographics is the key: Europe is aging, Japan is aging, China',
    'is aging — only India is young. The future belongs to those who can',
    'deal with their population.',
    '',
    'The third lesson is the honesty of the balance sheets. Every voice of',
    'this chapter has named its price: the West its export dependence and',
    'its fear of the future, Japan its lost decades, Korea its dictatorship,',
    'China its compromise with freedom, India its inequality. None of these',
    'stories is only success, none only failure — and that is exactly what',
    'makes them history in the sense of this app: comprehensible, not',
    'black-and-white.',
    '',
    'And the final question remains open because it must remain open:',
    'Whose story will be the next one?',
  ].join('\n'),

  urteil: {
    frage: 'Germany is losing relative economic weight but in absolute terms remains one of the strongest economies in the world. Is that a reason for concern, a reason for composure — or both at once, and if so, how do the two kinds of concern and composure differ?',
    hinweis: 'There is no right answer here. Some say: relative loss of significance is the beginning of the end — whoever does not grow along with the world economy will ultimately fall back in absolute terms too. Others say: the fact that billions of people in Asia are growing out of poverty while Germany remains rich is not a zero-sum game but the best possible outcome for most people in the world. When answering, check whether you are thinking from Germany or from the whole world — both vantage points lead to different answers, and neither of them is wrong.',
  },

  quiz: [
    {
      frage: 'What exactly did the currency reform of 20 June 1948 change in the western occupation zones?',
      antworten: [
        'It introduced the euro as the common currency of Western Europe',
        'It replaced the worthless Reichsmark with the D-Mark and at the same time largely abolished the price controls',
        'It nationalized German industry',
      ],
      richtig: 1,
      erklaerung: 'Every person received 40 marks as “capitation money”; Ludwig Erhard at the same time lifted most of the price controls. Overnight the shop windows filled up — not because there were suddenly more goods, but because hoarding no longer paid off.',
    },
    {
      frage: 'How large was the Marshall Plan’s share of West German economic output compared with its effect?',
      antworten: [
        'Measured against economic output it was rather small, but important at the right time (raw materials, foreign exchange, enforced cooperation)',
        'It financed the greater part of the West German reconstruction',
        'It had no significance whatsoever for West Germany',
      ],
      richtig: 0,
      erklaerung: 'Of the roughly 13 billion dollars between 1948 and 1952, about 1.4 billion went to West Germany — measured against economic output rather little. It was important nonetheless: as a source of raw materials and foreign exchange in a time of shortage, and because it forced the European recipient countries to cooperate.',
    },
    {
      frage: 'What does it mean if Germany’s share of the world economy has been falling since 1990 while its own economic output keeps growing?',
      antworten: [
        'That is impossible — a falling share necessarily means that one’s own economy is shrinking',
        'Both can hold at the same time: if other economies grow faster, one’s own share falls arithmetically, even without any decline of one’s own',
        'That means the statistics are being calculated wrongly',
      ],
      richtig: 1,
      erklaerung: 'That is the difference between relative and absolute: if China grows from 2 percent to around one-sixth of the world economy between 1990 and 2024, the share of every more slowly growing country automatically falls — even if that country’s own economy keeps growing in the same period.',
    },
    {
      frage: 'Which economy was the fourth-largest in the world in 2024, after the USA, China and Germany?',
      antworten: [
        'Japan',
        'France',
        'India',
      ],
      richtig: 0,
      erklaerung: 'Japan, despite the “lost decades” after 1990, remained the fourth-largest economy in the world. India ranked fifth in 2024 but was the fastest-growing of the large economies.',
    },
    {
      frage: 'What does the example of the semiconductor shortage of 2021 show for German car plants?',
      antworten: [
        'That Germany is technologically completely dependent on China',
        'That deep export interdependence can mean strength and vulnerability at the same time',
        'That Germany no longer has its own automobile industry',
      ],
      richtig: 1,
      erklaerung: 'When semiconductors from Taiwan became scarce in 2021, German car plants went on short-time work — a single missing component from a single country sufficed. Exactly this close interdependence that makes Germany an export power makes it vulnerable at the same time.',
    },
  ],
  karteHinweise: [
    {
      label: "1955–1968 — Reconstruction and the Economic Miracle",
      hinweis: "Ten years after the war, Western Europe and Japan are growing faster than ever before: the Federal Republic by about 8 percent a year, Japan by about 9. At this point South Korea, Taiwan and Singapore are poor countries — South Korea reached around 100 dollars per capita in 1961 and thus lay below Ghana. The world’s largest economy lies outside this map section: the USA account for about 40 percent of the world economy around 1960. And once again: the area shows land, not weight — the weight is in the titles.",
    },
    {
      label: "1990 — Japan’s peak and the four tigers",
      hinweis: "In 1990 Japan accounts for about 14 percent of the world economy — the highest share the country ever had. The four “tiger states” South Korea, Taiwan, Hong Kong and Singapore have halved the gap to Europe within one generation. Twelve years after the reforms began, China is still small: about 2 percent of the world economy. Germany has been one state again since 3 October 1990 — it is the only area on this map that grows between two phases.",
    },
    {
      label: "2024 — the new balance of power",
      hinweis: "The People’s Republic of China has been the world’s second-largest economy since 2010, and India the most populous country since 2023. In 2023 Germany moved back up to third place — not because it had grown, but because the yen had fallen. The USA still lie outside this map section and still in first place, with about a quarter of the world economy. And the area still shows land, not weight: China’s territory is twenty-seven times as large as Germany’s, its economic output about four times.",
    },
  ],
};

module.exports = aufstiegAsiens;
