// Topic: China — from the First Emperor to the great dynasties.
//
// English translation of utils/themen/china.js (German original).
// Both voices are complete: the European perspective (Voice: Opus)
// and the Chinese perspective (Voice: Hermes); the synthesis below
// brings them together (see CLAUDE.md, perspective workflow).
//
// No map in this module: the German original ships its map separately
// in karten/china.js (geometry instead of narrative), and this English
// version deliberately omits it.
//
// Pure data — no UI imports (architecture rule).

const china = {
  id: 'china',
  titel: 'China: From the First Emperor to the Great Dynasties',
  epoche: 'The imperial era — from the unification of the empire in 221 BC to the end of the Tang dynasty in 907 AD',

  aufhaenger: {
    frage: 'An empire as vast as Rome — and Europe did not even properly know it existed for centuries. How do you write a country together when everyone writes differently?',
    text: [
      'Imagine you are told to turn seven countries into one. They have been',
      'at war with one another for two hundred and fifty years. They use',
      'different coins, different weights, different laws — and they write',
      'the same word with different characters. An order from your capital',
      'is not just slow at the far end of the realm: it is unreadable.',
      '',
      'In 221 BC, exactly this problem stood before a man who called himself',
      'Qin Shi Huangdi: the First August Emperor of Qin. His solution was as',
      'simple as it was brutal — he made everything the same. One script. One',
      'measure. One weight. Even a single standard axle width for carts, so',
      'they would all fit into the same wheel ruts.',
      '',
      'And while Rome was rising in Europe, a second empire was growing at the',
      'other end of the world, roughly the same size and with roughly the same',
      'number of people. The two knew almost nothing about each other. A',
      'single thread connected them: silk.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'European Perspective',
      stimme: 'Opus',
      text: [
        'This is how China’s history is told in Europe — or rather, not told,',
        'because for a long time Europe knew astonishingly little about it.',
        'That is itself part of the story: this perspective does not begin',
        'with China but with a gap. Keep that in the back of your mind as you',
        'read.',
        '',
        '## Serica — the land the fabric came from',
        '',
        'The Romans did not know China. They knew a product.',
        '',
        'In Rome, silk was the most expensive fabric in the world: light as',
        'nothing, lustrous, cool against the skin. Some weighed it out against',
        'gold. The scholar Pliny grumbled that the empire was pouring fortunes',
        'into the stuff, and the Senate seriously debated whether men should be',
        'allowed to wear silk at all — it was considered far too soft.',
        '',
        'Nobody knew exactly where the fabric came from. The Romans called the',
        'people at the other end of the world “Seres” and the land “Serica” —',
        'from the word for silk. Pliny reported in all seriousness that the',
        'Seres combed the silk off leaves. He had never heard of silkworms.',
        'The Chinese guarded that secret for over a thousand years; exporting',
        'silkworms or their eggs was punishable by death.',
        '',
        'That, for a long time, was Europe’s picture of China: a commodity',
        'without a country, a rumor at the end of a very long road. Now turn',
        'the picture around. For where the road began there was no rumor, but',
        'an empire with officials, canals, censuses, and libraries.',
        '',
        '## 221 BC: One man makes everything the same',
        '',
        'Before 221 BC, China was not a country but a battlefield. Seven great',
        'states fought for supremacy — to this day the period is called the era',
        'of the Warring States. In the end Qin prevailed, a tough, well-',
        'organized realm in the west, and its king made himself into something',
        'that had never existed before: an emperor.',
        '',
        'What happened next was quick, and it went deep:',
        '',
        '- **One script for everyone.** The characters were standardized. That',
        '  was the cleverest move of the whole story, and it still works',
        '  today: people in China speak very different languages, but they',
        '  write the same characters. A merchant from Canton and an official',
        '  from Peking can barely understand each other when they talk — on',
        '  paper they understand each other instantly.',
        '- **One measure, one weight, one coin.** Trade and taxes became',
        '  calculable for the first time.',
        '- **A bureaucracy instead of the nobility.** The empire was divided',
        '  into districts run by transferable officials rather than',
        '  hereditary princes. Whoever has nothing to pass on builds no power',
        '  base of his own.',
        '- **A wall in the north.** Older ramparts were joined into a single',
        '  line — against the horse peoples of the steppe.',
        '',
        'The price was high. Hundreds of thousands of forced laborers died on',
        'the wall, the roads, and the canals. Critical books were burned,',
        'inconvenient scholars eliminated. And the emperor, who feared death,',
        'had a burial complex built the likes of which the world had never',
        'seen: an army of some 8,000 life-size terracotta soldiers, each with',
        'its own face, standing in rank and file underground. It was only',
        'found in 1974, by peasants who had wanted to dig a well.',
        '',
        'His dynasty lasted less than fifteen years. His empire lasted two',
        'thousand. His name stuck around, too: “Qin” is probably buried in our',
        'word China.',
        '',
        '## The Han: when two world empires existed at the same time',
        '',
        'After Qin came the Han dynasty — and with it the time when the',
        'history of China and the history of Rome almost touch. Around 100 AD',
        'there were two empires on Earth of roughly equal size and roughly',
        'equal population: one around the Mediterranean, one on the Yellow',
        'River. Together they probably ruled over half of all the people in',
        'the world. They did not know each other.',
        '',
        'The Han held their empire together with different tools than Rome.',
        'Rome relied on legions, roads, and citizenship. The Han relied on a',
        'civil service — one you could pass an examination to enter. Whoever',
        'mastered the classical texts could become an official, even from',
        'humble beginnings. It was not fully established until centuries',
        'later, but the idea was there long before Europe arrived at it:',
        'office by examination instead of by birth.',
        '',
        'And then there is the man to whom the Silk Road owes its existence,',
        'without him ever wanting it. In 138 BC Emperor Wu sent an envoy named',
        '**Zhang Qian** to the west. The mission: find allies against the',
        'Xiongnu, the horse peoples of the north. Zhang Qian was captured',
        'immediately, lived among the Xiongnu for ten years, married there,',
        'fled further west, saw lands nobody in China had known about — and',
        'returned after thirteen years without an alliance.',
        '',
        'But with reports. Of cities beyond the desert. Of people who drank',
        'wine. Of the “heavenly horses” of Fergana, which were bigger than any',
        'Chinese horse. Out of that failed mission grew the trade route we',
        'call the Silk Road today — a name, by the way, that only a German',
        'geographer invented in the 19th century.',
        '',
        'Westward along this route went silk, lacquer, cinnamon, peaches — and',
        'eventually paper, perhaps the most consequential Chinese invention of',
        'all. Eastward came glass, gold, wool, grapes, and horses. And with',
        'the goods traveled ideas: Buddhism came from India to China along',
        'these roads. Diseases traveled too; in the 2nd century a great',
        'epidemic struck both ends of the route without anyone suspecting',
        'why.',
        '',
        'No single person ever walked the whole way. The silk passed from hand',
        'to hand, through dozens of middlemen, taking a year or longer. Rome',
        'and China sent each other embassies that either never arrived or',
        'never returned. The two greatest empires on Earth remained a rumor to',
        'each other.',
        '',
        '## The Tang: the greatest city in the world',
        '',
        'After the end of the Han, China fell apart into separate realms — and',
        'came together again. Under the Tang dynasty (618–907) the country',
        'reached a flowering that is hard to imagine.',
        '',
        'Around 750 AD the capital Chang’an, with about one million',
        'inhabitants, was the greatest city in the world, bigger than anything',
        'Europe had at the time — Rome had long since shrunk to a small town.',
        'Chang’an was strictly planned: a rectangle divided into 108 walled',
        'quarters, with a 150-meter-wide grand avenue down the middle. In the',
        'evening drums closed the gates; in the morning they opened again.',
        '',
        'The most astonishing thing is how open this city was. On the West',
        'Market, Sogdians, Persians, Indians, Arabs, and Turks traded. There',
        'were Buddhist monasteries, Zoroastrian fire temples, Manichaean and',
        'Christian congregations. Persian music was in fashion, polo was the',
        'sport of the upper class, and for a while noblewomen wore riding',
        'dress in the steppe style. One empress, Wu Zetian, ruled in her own',
        'name — the only woman in Chinese history to do so.',
        '',
        'Above all, it was an age of poetry. Li Bai and Du Fu, China’s two',
        'most famous poets, lived in this century. Chinese children still',
        'memorize their poems today — just as German children learn Goethe.',
        '',
        'Then, in 755 AD, came the rebellion of the general An Lushan, and the',
        'flowering turned into catastrophe: the capital fell, millions of',
        'people died or lost their homes. The Tang ruled for another century',
        'and a half, but the great openness was over. In 907 the dynasty',
        'ended.',
        '',
        '## Why Europe barely tells this story',
        '',
        'If all of that is true — why does it appear so rarely in European',
        'schoolbooks?',
        '',
        'Part of the answer is simply distance. Between Rome and Chang’an lay',
        '8,000 kilometers, deserts, high mountains, and a dozen foreign',
        'realms. People knew little because there was little they could know.',
        '',
        'The other part is more uncomfortable. Europe likes to tell world',
        'history as a single line that runs from Greece through Rome to',
        'Europe and culminates there. In that line, China is not a chapter',
        'but at best a footnote — interesting, exotic, but off to the side.',
        'When European travelers did reach China in the 13th century and',
        'reported what they saw — cities of millions, paper money, coal',
        'heating — nobody back home believed them. Marco Polo was mocked by',
        'his contemporaries as “Il Milione”, the braggart.',
        '',
        'And in the 19th century something else was added: Europe had become',
        'militarily superior to China and accordingly told the story as if',
        'China had always been backward. That paper, printing, the compass,',
        'and gunpowder all came from China and traveled west along the Silk',
        'Road did not fit well into that narrative.',
        '',
        'That is why this chapter is doubly interesting. It does not merely',
        'tell a story; it also shows how a story comes into being: through',
        'selection. Whoever tells the story decides what appears in it.',
        '',
        'And this is exactly where this perspective reaches its limit.',
        'Everything you have just read is the view from outside — the view of',
        'those who sat at the other end of the road and bought the fabric',
        'without knowing the country. What this history means from the',
        'perspective of those who lived it from the inside, a second voice',
        'will tell.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Chinese Perspective',
      stimme: 'Hermes',
      text: [
        'This perspective tells the story from the inside — the way China’s',
        'history is told in China itself: by people whose ancestors lived in',
        'Chang’an, who learned the poems of Li Bai in school, and for whom',
        'China was never the faraway land at the end of a road, but the',
        'center. This, too, is a narrative — with its own terms, its own',
        'questions, and its own sense of self.',
        '',
        '## The Middle Kingdom',
        '',
        '“Zhongguo” — the Middle Kingdom. That is what China calls itself, and',
        'the name is a program: the world arranges itself around China. Not',
        'because China claims to know everything, but because its own history',
        'was already told in full hundreds of years before the first contact',
        'with Europe. A civilization that has its own calendar, its own',
        'script, and its own dynasties does not need Europe as a yardstick.',
        'The Chinese narrative does not begin with a gap but with its own',
        'center.',
        '',
        'Seen from here, the European view of China looks like a mirror held',
        'at a great distance: it shows an image — but a small, blurry one,',
        'and it says more about the person looking into it than about what is',
        'being looked at.',
        '',
        '## The Son of Heaven and the Mandate',
        '',
        'In the Chinese narrative, the emperor stands above everything — the',
        'Son of Heaven. He does not rule by his own right, but because Heaven',
        'has lent him the Mandate: as long as he governs well, as long as the',
        'fields are tended, the officials honest, and the borders calm, rule',
        'stays with his dynasty. If he governs badly, Heaven withdraws the',
        'Mandate — often through uprisings that later historiography reads as',
        'a sign that the time had come.',
        '',
        'This way of thinking makes the Chinese narrative different from the',
        'European one. Europe asks: “What did Rome leave behind?” China asks:',
        '“Did the dynasty fulfill its Mandate?” And because the Mandate',
        'wanders, the change of dynasties is not the collapse of the world',
        'but the order of the world — the cycle in which the empire keeps',
        'gathering itself anew.',
        '',
        '## 221 BC: The end of chaos',
        '',
        'For the Chinese narrative, Qin Shi Huangdi is neither a riddle nor a',
        'contradiction, but the answer to an open wound: 250 years of',
        'Warring States, in which the states tore each other apart. That an',
        'emperor put an end to that — with one script, one measure, one',
        'bureaucracy — was, from this point of view, the restoration of the',
        'order that Heaven wanted.',
        '',
        'Chinese historiography is not blind to the price, either. The',
        'burning of the books and the forced labor on the wall are named to',
        'this day — the scholars of the following Han dynasty portrayed Qin',
        'as ruthless, and that verdict still echoes. But they also record the',
        'unification: that a country which had fallen into seven quarreling',
        'parts became one again — that, from a Chinese point of view, was not',
        'tyranny but fulfillment. And the unity holds to this day, two',
        'thousand years later. That is the Chinese narrative’s answer to all',
        'who see only the price: Look at what it has become.',
        '',
        '## The Han: scholars instead of generals',
        '',
        'The Han dynasty gave the empire the government it was to keep into',
        'the last imperial era: the scholar state. Whoever wanted to become',
        'an official had to master the classical texts — and could learn',
        'them, regardless of origin. Examination instead of birth. The Middle',
        'Kingdom was held together not primarily by soldiers, but by an',
        'administration that legitimized itself through education.',
        '',
        'For the Chinese narrative, that is a point of pride older than any',
        'European example: a state that trains its leadership instead of',
        'inheriting it. That Rome bound its citizens through rights is, from',
        'this point of view, a different answer — not the only one — to the',
        'same question: How do you hold a giant empire together?',
        '',
        '## The Silk Road: when the world came to Chang’an',
        '',
        'In the Chinese narrative, the Silk Road is not a trade route along',
        'which goods flowed west — it is the gate through which the world',
        'came to China. Envoys and merchants from countries nobody in China',
        'had heard of stepped before the emperor and brought gifts. From a',
        'Chinese point of view, that was not trade among equals, but the',
        'tribute of the world to the center — the order as it should be.',
        'That the caravans traveled thousands of kilometers through deserts',
        'for it only confirmed how coveted what China had to give was.',
        '',
        'Zhang Qian, the envoy who went west and returned after thirteen',
        'years, is told about in China, too — as the one who opened the',
        'empire’s eyes to the world. But the emphasis lies differently: not',
        '“we discovered the West”, but “we got to know the world that wanted',
        'to come to us”. The grapes, the horses, the music — all of that came',
        'in, and China remained what it was: the center.',
        '',
        '## The Tang: the greatest city in the world — from the inside',
        '',
        'Chang’an under the Tang is, in the Chinese narrative, the proof that',
        'openness is strength. In the 108 quarters of the city lived Sogdians',
        'and Persians, Indians and Arabs; on the West Market you could hear a',
        'dozen languages. From a Chinese point of view, that was no exception',
        'but the natural order of an empire sure of its center: whoever is',
        'strong can afford to be open.',
        '',
        'And then there is the poetry. Li Bai and Du Fu — Chinese children',
        'still memorize their poems today, just as German children learn',
        'Goethe. That a century a thousand years ago produced the greatest',
        'poetry the Chinese language knows is, for the Chinese narrative,',
        'more important than any battle. You do not recognize a civilization',
        'by its borders, but by what it leaves behind — and China has the',
        'poems of Li Bai, Confucianism, paper, and the script.',
        '',
        'When the general An Lushan rose up in 755 and Chang’an fell, that',
        'was a catastrophe in the Chinese narrative, too — but a familiar',
        'one: the Mandate of the Tang was drawing to its end. Not the empire',
        'ended, only a dynasty. The cycle went on.',
        '',
        '## Why this story sounds different',
        '',
        'Two things make the difference from the European perspective.',
        '',
        'First: the Chinese narrative does not ask why Europe knew so little',
        'about China. It never needed that question. For the center of the',
        'world, the question “Why does the periphery not know us?” was',
        'meaningless — history went on in Chang’an whether Rome knew it or',
        'not. That Europe long took China for a rumor says, from a Chinese',
        'point of view, something about the distance — and about the',
        'perspective of those who looked at the center from the periphery.',
        '',
        'Second: Chinese historiography, too, is written by the victors.',
        'Every new dynasty had the history of the fallen one written — and',
        'had an interest in making that dynasty’s loss of the Mandate clear.',
        'So in China, too, it holds: whoever tells the story selects. But the',
        'selection turns out differently than in Europe, because the',
        'narrative thinks in cycles instead of in a line. Europe tells: Rome',
        'fell, and something came to an end. China tells: a dynasty ended,',
        'and the empire gathered itself anew.',
        '',
        'This is not a correction of the European view. It is the other half',
        'of the same story — told from the center instead of from the',
        'periphery, from the inside instead of from the outside. Only when',
        'both halves lie before you can you see how much of what we call',
        '“history” depends on where you stand.',
      ].join('\n'),
    },
  ],

  // Synthesis (revised jointly after the Chinese perspective was added).
  synthese: [
    'Now two narratives about the same two thousand years lie side by side —',
    'and they sound like two different stories. That is the point.',
    '',
    '**Where they meet:** Both perspectives see the Qin unification as the',
    'decisive moment — one script, one measure, one bureaucracy. Both tell',
    'the Silk Road as the great connection through which goods, ideas, and',
    'Buddhism traveled. And both call the Tang era a flowering in which',
    'Chang’an was the greatest city in the world. When it comes to the what,',
    'the narratives are closer than you would expect.',
    '',
    '**Where they diverge:** The European view begins with a gap — “we knew',
    'nothing about China for a long time” — and asks why that was and why',
    'Europe barely tells this story. The Chinese view begins with its own',
    'center: China never needed the gaze from outside; history went on in',
    'Chang’an whether Rome knew it or not. The same Silk Road is, for one',
    'narrative, a trade route along which silk flowed west; for the other,',
    'the gate through which the world came to the center. And the same',
    'changes of dynasty are, for one, a sign of decay; for the other, the',
    'order of the Mandate — the cycle in which the empire keeps gathering',
    'itself anew.',
    '',
    '**What follows from it:** Both narratives are written by people who',
    'take their own view for the natural one — Europe sees China as a',
    'footnote at the edge of its world line; China sees itself as the',
    'center around which everything arranges itself. The choice of words',
    'gives it away: “distant rumor” and “Middle Kingdom” describe the same',
    'distance — only from different ends of the road.',
    '',
    '**Your judgment begins here:** Whose narrative helps you more to',
    'understand what happened in those two thousand years — the one from',
    'outside or the one from inside? And what would change in your picture',
    'of China if you had heard only one of them?',
  ].join('\n'),

  urteil: {
    frage: 'The First Emperor united a country that had been at war for 250 years — with one script, one measure, one bureaucracy. Hundreds of thousands of forced laborers, burned books, and killed scholars paid for it. In your opinion, was this unification worth the price? And who is allowed to decide something like that at all?',
    hinweis: 'There is no right or wrong here. Name two or three reasons for your view — and consider whether a peasant at the wall, an official in the capital, and a person 2,000 years later would give the same answer.',
  },

  quiz: [
    {
      frage: 'Is it true that all people in China speak the same language?',
      antworten: [
        'Yes — since the First Emperor there has been only one language.',
        'No — very different languages are spoken, but since the First Emperor they have been written with the same characters.',
        'No — there are also different scripts for every region.',
      ],
      richtig: 1,
      erklaerung: 'That is the real trick of the unification: what was unified was the script, not the speech. People who can barely understand each other orally understand each other instantly on paper — which is why this unity holds to this day.',
    },
    {
      frage: 'Did the Roman Empire know that China existed?',
      antworten: [
        'Yes — there was regular exchange of ambassadors between Rome and Chang’an.',
        'No — nobody in Rome had ever heard of silk.',
        'Only roughly — they knew the silk and called the faraway land “Serica”, but knew almost nothing about it.',
      ],
      richtig: 2,
      erklaerung: 'Rome knew the product, not the country. The scholar Pliny even wrote that silk was combed off leaves — he had never heard of silkworms. Conversely, China called Rome “Da Qin” and knew just as little.',
    },
    {
      frage: 'How did the Silk Road come about?',
      antworten: [
        'An envoy was supposed to find allies against the Xiongnu — that failed, but he brought back the first reports about the West.',
        'A Chinese emperor had it deliberately built as a trade road.',
        'Roman merchants explored the route from the West.',
      ],
      richtig: 0,
      erklaerung: 'In 138 BC Zhang Qian set out with a military mission, was taken captive, and only returned after thirteen years — without an alliance, but with knowledge. Out of that failed mission grew the most important trade route of antiquity.',
    },
    {
      frage: 'Which city was the greatest in the world around 750 AD?',
      antworten: [
        'Rome',
        'Chang’an, the capital of the Tang dynasty, with about one million people.',
        'Constantinople',
      ],
      richtig: 1,
      erklaerung: 'Chang’an — today’s Xi’an — was a planned city of 108 walled quarters in which Sogdians, Persians, Indians, and Arabs traded. Rome, by that time, had long since shrunk to a small town.',
    },
    {
      frage: 'Is it true that paper is a Chinese invention?',
      antworten: [
        'No — paper came from Egypt.',
        'Yes — and it traveled west along the Silk Road, together with the compass, printing, and gunpowder.',
        'Yes — but it stayed limited to China until modern times.',
      ],
      richtig: 1,
      erklaerung: 'Papyrus from Egypt is something different from paper. Real paper comes from China and took about a thousand years to reach Europe. Without that long road there would be no European printing — and without it, hardly the modern age as we know it.',
    },
  ],
};

module.exports = china;
