// Topic: The Thirty Years' War (1618–1648).
//
// English translation of utils/themen/dreissigjaehriger-krieg.js. Field names
// follow the German schema (aufhaenger, perspektiven, synthese, urteil, quiz) —
// only the texts are translated. The map is omitted in this English module
// (see karten/dreissigjaehriger-krieg.js), as are the karteHinweise.
//
// Status: Round 12. Contains for now ONLY the view of the emperor, the
// princes and the generals (Voice: Opus) — the view of those who decided. The
// view of those affected (towns and villages: mercenaries, hunger, plague,
// flight, survival) is added by Hermes; the synthesis below is explicitly
// preliminary and will be revised together afterwards (see CLAUDE.md,
// perspectives workflow).
//
// Third chapter of the early-modern arc (notizen/kapitel-planung.md). It
// begins exactly where "From the Middle Ages to the Early Modern Era" ends:
// 1618 in Prague, with the defenestration that chapter has as its last
// sentence.
//
// The axis is again a social one — top and bottom in the same country, as
// with the early kingdoms and the Middle Ages. This voice belongs to those
// who decided: the emperor, the electors, the kings of Denmark, Sweden and
// France, the generals. It may explain its calculations without glossing
// over them.
//
// TONE RULE (CLAUDE.md, additional rule for sensitive topics, applied in
// spirit to the question of confession): The warring parties were
// political-religious powers, not caricatures. No side is demonised, none
// is played down. The narrative itself names its uncomfortable spots —
// above all the mercenary and contribution system that financed the war at
// the expense of the population — and the motives of the other side are
// presented fairly, even within this perspective. The quiz questions remain
// questions of knowledge: this app does not ask about guilt.
//
// The map lives in karten/dreissigjaehriger-krieg.js — three states (1618,
// 1631/32, 1648) and an imperial border that lies over the terrain as a
// line rather than an area.
//
// Pure data — no UI imports (architecture rule).

const dreissigjaehrigerKrieg = {
  id: 'dreissigjaehriger-krieg',
  titel: "The Thirty Years' War",
  epoche: '1618–1648',

  aufhaenger: {
    frage: 'Three men fly out of a window in Prague and survive — thirty years later the centre of Europe lies devastated and a peace has been concluded that still shapes the map to this day. How does a dispute over churches become a war in which half of Europe is eventually involved?',
    text: [
      "On 23 May 1618 Bohemian nobles threw two imperial governors and",
      "their secretary out of a window of Prague Castle. Seventeen metres",
      "down. All three got up again and ran away.",
      '',
      "That sounds almost like an anecdote — and it is the beginning of",
      "thirty years of war. Not because a defenestration would be so",
      "powerful, but because everything that had been piling up for decades",
      "was in that throw: the question of who in the Empire decides over",
      "faith. The question of how much power an emperor has over princes",
      "who elected him themselves. And the question of who sets the tone in",
      "Europe.",
      '',
      'What it became, those involved themselves did not know as "the',
      "Thirty Years' War\" — the name came later. They experienced several",
      "wars one after another: first the Bohemian, then the Danish, then",
      "the Swedish, and finally the Franco-Swedish. Each one began because",
      "someone calculated that getting involved would pay off. And each one",
      "ended without anything having been decided.",
      '',
      "This chapter first tells from above: of those who decided — emperor,",
      "electors, kings, generals. They wrote down their reasons, in",
      "letters, treaties and instructions; one can watch them calculate.",
      "What their decisions did down below is told by the second voice.",
    ].join('\n'),
  },

  // "History in motion" — the map comes after the hook and before the
  // perspectives (utils/lernformat.js). Omitted in this English module
  // (see karten/dreissigjaehriger-krieg.js).

  perspektiven: [
    {
      id: 'herrscher-sicht',
      name: 'The view of the emperor, the princes and the generals',
      stimme: 'Opus',
      text: [
        "This is the view of those who decided: of the emperor in Vienna,",
        "the seven electors, the kings of Denmark, Sweden, France and",
        "Spain, the generals who raised and sold armies. It is the story",
        "from the cabinets and field camps — where war was waged as an",
        "account.",
        '',
        "This voice has one advantage and one blind spot. The advantage: it",
        "can explain why every single step looked reasonable from the point",
        "of view of the man who took it — and that is what is actually",
        "frightening about this war. The blind spot: in this account, the",
        'people who paid the price appear as line items. As "contribution",',
        'as "quartering", as "recruitment". Not as people.',
        '',
        "Both voices of this chapter are of equal worth. That this one",
        "stands first is not a ranking but merely the order in which it was",
        "written.",
        '',
        '## 1618: A window in Prague',
        '',
        "Bohemia was an elective kingdom, and its estates were",
        "predominantly Protestant. In 1609 Emperor Rudolf II had granted",
        "them freedom of faith in the **Letter of Majesty** — not out of",
        "conviction, but because he needed their support. When churches",
        "were later closed and demolished in two Protestant towns, the",
        "estates saw the right as broken.",
        '',
        "On 23 May 1618 they came to the castle and threw the two governors",
        "out of the window. That was no outburst of rage but a formal act",
        "with a precedent: in Bohemia this had already been done in 1419.",
        "Its message was: we renounce our obedience to the king.",
        '',
        "From the point of view of the estates it was self-defence. From",
        "the point of view of Vienna it was rebellion — and Archduke",
        "**Ferdinand**, who was soon to become emperor, was not a man for",
        "compromises: deeply religious, educated by Jesuits, convinced that",
        "a ruler answers before God for the faith of his subjects. He had",
        "already pushed back Protestantism in his own lands. The Bohemians",
        "knew that. Precisely for that reason they acted.",
        '',
        "They deposed Ferdinand and elected a new king: **Frederick V of",
        "the Palatinate**, a Calvinist elector and son-in-law of the",
        "English king. He accepted — against the advice of almost everyone",
        "who could calculate. On 8 November 1620 his army lost at the",
        "**White Mountain** before Prague in a little over two hours. He",
        'fled and went down in history as the "Winter King".',
        '',
        "What followed shows how victors thought in those days: in 1621,",
        "twenty-seven leaders were executed on the Old Town Square, the",
        "Protestant nobility was dispossessed, the country made Catholic.",
        "Part of the confiscated property made a previously middling",
        "Bohemian nobleman very rich — his name was Albrecht von",
        "Wallenstein.",
        '',
        '## Why a defenestration could trigger a war',
        '',
        "To understand why this was not over after two years, one must",
        "know how the Empire was built.",
        '',
        "The Holy Roman Empire was not a state. It was a federation of more",
        "than three hundred lordships: electorates, principalities,",
        "bishoprics, free imperial cities, imperial knights — each with its",
        "own law, its own coin, its own troops. At the top stood an emperor",
        "who was elected and who got neither money nor an army without the",
        "consent of the imperial estates.",
        '',
        "And over all of this lay the **Peace of Augsburg** of 1555 with",
        "its famous formula: **cuius regio, eius religio** — whose the",
        "land, his the religion. One usually reads it as a rule of faith.",
        "It was above all a rule of power: it made every territorial lord",
        "the master of the church of his land, together with its property.",
        "Whoever changes confession, changes income as well.",
        '',
        "The peace had three design flaws, and all three exploded from",
        "1618 onwards:",
        '',
        "- The **Calvinists** did not occur in it — in 1555 they barely",
        "  existed in the Empire. Sixty years later the Palatinate,",
        "  Hesse-Kassel and Brandenburg were Reformed, and the peace did",
        "  not protect them.",
        "- The **Ecclesiastical Reservation** stipulated that a bishop who",
        "  becomes Protestant must give up his bishopric. The north did",
        "  not hold to that: Halberstadt, Magdeburg, Bremen and many other",
        "  bishoprics had long been in Protestant hands.",
        "- And the imperial courts, which were supposed to settle such",
        "  disputes, were themselves blocked by confession.",
        '',
        "Whoever asks today whether this was a war of religion or a war of",
        "power asks a question the contemporaries would not have",
        "understood. For them the two were the same: church property was",
        "power, freedom of faith was a right of the estates against the",
        "prince, and one allied oneself with whoever used the same",
        "catechism — until it no longer paid off.",
        '',
        '## 1629: The Edict of Restitution — the victory that went too far',
        '',
        "The first half of the war was won by the emperor. Bohemia had been",
        "crushed, the Palatinate conquered and its electoral dignity",
        "transferred to Bavaria in 1623 — an enormous act, for with it the",
        "emperor unilaterally changed who would elect him in future. In",
        "1625 the Danish king **Christian IV** intervened, at once as a",
        "Protestant prince and as Duke of Holstein and Sweden's rival for",
        "the Baltic; in 1629 he had to give up in the Peace of Lübeck.",
        '',
        "At the height of his power Ferdinand II issued the **Edict of",
        "Restitution** in March 1629: all church property that had become",
        "Protestant since 1552 was to be returned. Two archbishoprics, a",
        "dozen bishoprics, hundreds of monasteries.",
        '',
        "Legally it could be justified — that is what stood in the peace",
        "of 1555. Politically it was the greatest mistake of the war. For",
        "first, it took away the basis of the Protestant princes'",
        "possessions. And second, even the Catholic side was alarmed: an",
        "emperor who could reach that far was dangerous for every prince.",
        "In the summer of 1630 the electors — the Catholic ones in the",
        "lead — forced the emperor in Regensburg to dismiss his own",
        "commander. They feared him more than the enemy.",
        '',
        '## Wallenstein: the entrepreneur of the war',
        '',
        "**Albrecht von Wallenstein** is the figure on whom one best",
        "understands the logic of the decision-makers — and its limit.",
        '',
        "He was a Bohemian nobleman, baptised Protestant, converted to",
        "Catholicism, made rich through marriage and through the sales of",
        "estates after 1620. In 1625 he offered the emperor something no",
        "one else could offer: an entire army, raised on his own account.",
        "The emperor had no money; Wallenstein had credit. He became Duke",
        "of Friedland, later also of Mecklenburg, and led armies that at",
        "times numbered over a hundred thousand men.",
        '',
        "They were paid according to a principle that became the key",
        "sentence of this war: **The war feeds the war.** The army took",
        "from the land what the war chest did not provide. Towns and",
        "regions had to pay **contributions** — regular, formally",
        "calculated sums, in return for the assurance of not being",
        "plundered. Whoever did not pay had the soldiers in the house.",
        '',
        "One must see what was new in this and what was old. Old was that",
        "armies provisioned themselves from the land; everyone did that.",
        "New was the scale and the cold-bloodedness of the calculation:",
        "Wallenstein made a system out of the makeshift and a",
        "self-sustaining business out of the war — and precisely for that",
        "reason it no longer stopped. An army that feeds itself from the",
        "land must move on as soon as the land is empty.",
        '',
        "That is no defamation from outside. It was intent, it stood in",
        "the contracts, and it applied to all sides — imperial, League,",
        "Swedish, French. Only at one point did Wallenstein visibly fail:",
        "in 1628 he besieged **Stralsund** and did not get the city,",
        "because it was supplied by sea. Whoever does not hold the Baltic",
        "does not win in the north. Another man drew that lesson two years",
        "later.",
        '',
        "Dismissed in 1630, called back in 1632, Wallenstein was beaten to",
        "death on 25 February 1634 in **Eger** by his own officers. The",
        "emperor had declared him deposed and ordered his capture, dead or",
        "alive; Wallenstein had negotiated with the enemy on his own",
        "authority. Whether that was treason or the attempt to end the war",
        "is still disputed by scholars today. What is certain: the man who",
        "had made the war affordable was finished off by the system he had",
        "built.",
        '',
        '## Magdeburg 1631 — what this system cost',
        '',
        "On 20 May 1631 **Magdeburg** fell, besieged since November by",
        "Pappenheim, since April by Tilly. During the assault fire broke",
        "out; of roughly 25,000 to 30,000 people, about 20,000 died. It",
        "was the single greatest catastrophe of the war, and from the name",
        'of the city a word was born: "to magdeburgize".',
        '',
        "Who set the fire is disputed to this day. Tilly accused the",
        "defenders, the Protestant pamphlets the imperial troops;",
        "scholarship holds both possible and neither proven. What is not",
        "disputed belongs in this narrative, because it lays open the",
        "account of the decision-makers: Tilly's army had stood before the",
        "city for months, had not been paid and had consumed the",
        "surroundings. The plundering of a conquered city was the promised",
        "wage. That was no lapse of individual monsters — it was the",
        "consequence of a decision about how war is paid for.",
        '',
        "That does not make it better. It only makes it explicable. And",
        "whoever can explain also sees who was responsible: not the",
        "mercenary who climbed into the breach, but those who sent him",
        "there without pay.",
        '',
        "Magdeburg also became Europe's first great media war. Hundreds of",
        "pamphlets and pictures went through the whole continent — and",
        "because printing had become cheap by then, each side could spread",
        "its version. Whoever keeps the guiding idea of this app in mind",
        "finds an early example here: the same night, two narratives, both",
        "printed, both interested.",
        '',
        '## Gustavus Adolphus 1630–1632',
        '',
        "On 6 July 1630 **Gustavus Adolphus**, King of Sweden, landed on",
        "Usedom with about 13,000 men. That was only made possible by the",
        "Truce of Altmark of 1629, which had ended his war against Poland.",
        '',
        "He came as the saviour of the Protestants — and he meant it",
        "seriously. He was a devout Lutheran who prayed with his troops",
        'every day, and in the Empire many saw in him the "Lion of the',
        'North" who would liberate his fellow believers.',
        '',
        "At the same time he came as a power politician, and that too is",
        "openly documented. Sweden wanted to dominate the Baltic — no",
        "enemy on its southern shores, no imperial fleet threatening tolls",
        "and trade. And he came with foreign money: in the Treaty of",
        "Bärwalde of 1631 Catholic France promised him annual subsidies.",
        '',
        "Militarily he was the most modern commander of his time: smaller,",
        "mobile units, volley fire instead of deep blocks, light artillery",
        "that could be repositioned in the middle of a battle, and a hard",
        "discipline that limited plundering — as long as the pay came. On",
        "17 September 1631 he defeated Tilly's army together with",
        "Electoral Saxony at **Breitenfeld** north of Leipzig, the first",
        "time ever. In 1632 he marched into Franconia, to the Rhine and",
        "across the Lech into Bavaria; in May he stood in Munich.",
        '',
        "On 16 November 1632 he fell at **Lützen** — in the fog, separated",
        "from his men, at thirty-seven years of age. The Swedes held the",
        "field.",
        '',
        "And then what happened is what the story of the great commander",
        "bears hardest: almost nothing. Chancellor Oxenstierna continued",
        "the war, for sixteen years. The war had detached itself from the",
        "will of individual men.",
        '',
        '## 1635: A cardinal changes sides',
        '',
        "In 1634 the Swedes lost heavily at Nördlingen. In 1635 the emperor",
        "concluded the Peace of Prague with Electoral Saxony: the Edict of",
        "Restitution was practically dropped, the year 1627 agreed as the",
        "cut-off date, Lusatia went to Saxony. A Lutheran elector now",
        "fought at the side of the Catholic emperor against the Lutheran",
        "Swedes. The war could have ended here.",
        '',
        "It did not end, because in Paris **Cardinal Richelieu** was",
        "calculating. France was Catholic, its leading minister a prince",
        "of the church — and both saw the real danger not in heresy but in",
        "the encirclement by Habsburg: Spain in the south and west, Austria",
        "in the east. For years France had therefore paid Sweden instead",
        "of fighting itself. In 1635 it declared war on Spain.",
        '',
        "The rule by which Richelieu acted has a name: **reason of state**",
        "— whatever serves the state is permitted, even against one's own",
        "confession. On 19 May 1643 a French army under the",
        "twenty-one-year-old Duke of Enghien defeated the Spanish army at",
        "**Rocroi**, and the reputation of the Spanish tercios as",
        "invincible was gone.",
        '',
        "At the latest here, the story of a pure war of faith can no",
        "longer be maintained. But it was also never wholly false: for",
        "Ferdinand II the return of his lands to the old church was a",
        "matter of conscience, for Gustavus Adolphus the protection of",
        "fellow believers a genuine motive, and the people in the villages",
        "very well experienced which pastor stood in the church after the",
        "army had passed through. Faith and power lay not side by side but",
        "inside each other.",
        '',
        '## Why thirty years?',
        '',
        "The most honest answer of the decision-makers to this question",
        "is: because no one could win and no one wanted to lose.",
        '',
        "- **No victory was decisive.** After every won battle the enemy",
        "  was beaten, but not finished; armies could be re-raised with",
        "  money, and money came from the occupied land.",
        "- **The armies had interests of their own.** Officers had invested",
        "  in their regiments and wanted pay, booty and compensation.",
        "  Peace meant unemployment.",
        "- **Each side had minimum demands** below which it could not go",
        "  without losing face — and allies who had their own accounts",
        "  open.",
        "- **The neighbours did not allow it.** As soon as one side became",
        "  too strong, someone stepped in: Denmark in 1625, Sweden in",
        "  1630, France in 1635. A balance through intervention — the same",
        "  principle by which Europe made politics for two hundred years",
        "  afterwards.",
        '',
        '## 1648: Münster and Osnabrück',
        '',
        "Negotiations ran from 1644, in two cities, because the",
        "confessions did not want to sit at one table: the Catholic side",
        "with France in **Münster**, the Protestant with Sweden in",
        "**Osnabrück**. About 150 embassies, not a single meeting of all",
        "parties, years of quarrelling over ranks and forms of address.",
        "And meanwhile the war went on — one negotiated in order to",
        "improve one's own position.",
        '',
        "On 24 October 1648 it was signed. The **Peace of Westphalia**",
        "regulated what it could not decide:",
        '',
        "- The Peace of Augsburg was confirmed and extended to the",
        "  Reformed. For church property the **Normal Year** 1624 applied:",
        "  what belonged to whom in that year stayed that way — a",
        "  cut-off-date rule instead of a judgement about who was right.",
        "- The imperial estates received **territorial sovereignty** and",
        "  the right to conclude their own alliances, as long as these",
        "  were not directed against emperor and Empire. The Empire",
        "  definitively became a coexistence of almost sovereign princes.",
        "- Sweden received Western Pomerania with Rügen, Wismar, Bremen",
        "  and Verden — and with it seat and vote in the Imperial Diet.",
        "  France received the Habsburg rights in Alsace, Brandenburg",
        "  Hither Pomerania and several bishoprics, Bavaria kept the",
        "  electoral dignity, the Palatinate received a new, eighth one.",
        "- The Republic of the Netherlands and the Swiss Confederacy",
        "  formally left the Empire.",
        "- A general amnesty restored the state of 1618 — with one",
        "  exception the emperor had bargained for: in his hereditary",
        "  lands the recatholicisation remained. Bohemia, where everything",
        "  had begun, got nothing back.",
        '',
        "The pope protested against the treaty; it was concluded. Between",
        "France and Spain the war continued until 1659.",
        '',
        "Why this peace counts as the birth certificate of modern Europe:",
        "it treated all parties as equal partners of the treaty — large",
        "and small, Catholic and Protestant — and it made religion a",
        "matter that one regulates instead of decides. After it, Europe no",
        "longer negotiated about truth but about borders, rights and",
        "balance. That is less elevating than a victory, and it is the",
        "reason why congresses have since been the means of choice.",
        '',
        '## The uncomfortable spots of this narrative',
        '',
        "Everything said so far is told from the heights, and from the",
        "heights a war looks like a sequence of reasonable steps. Four",
        "things this voice must say itself so that the account adds up.",
        '',
        "**First: the numbers.** Before the war an estimated 16 to 18",
        "million people lived in the Empire, afterwards perhaps 10 to 13",
        "million — a loss of about a third. In Mecklenburg, Pomerania,",
        "Thuringia and Württemberg up to two thirds died regionally; in",
        "the northwest, in Hamburg, in the Alpine lands it remained",
        "comparatively calm. Most of the dead did not fall in battles but",
        "through hunger and epidemics that followed the armies. **The",
        "numbers are disputed** and rest on tax lists and church registers,",
        "not on censuses; what is certain is the order of magnitude, not",
        "the individual figure.",
        '',
        "**Second: those who paid this price had not decided it.** The",
        "decision-makers waged a war for thirty years in which they",
        "themselves rarely faced mortal danger — Gustavus Adolphus is the",
        "exception that stands out. They raised mercenary armies they",
        "could not pay and sent them into regions that had to foot the",
        'bill. "The war feeds the war" is no law of nature. It was a',
        "decision, and one can read in the contracts who made it.",
        '',
        "**Third: confession was often the pretext and seldom the whole",
        "reason.** A Catholic cardinal paid Lutheran armies. A Lutheran",
        "elector fought for the Catholic emperor. Catholic Bavaria",
        "secretly negotiated its own armistice in 1647. Whoever knows that",
        "should also not claim the opposite: faith was not only a mask.",
        "It was genuine for many — and precisely for that reason so",
        "useful.",
        '',
        "**Fourth: these men were neither saints nor monsters.**",
        "Wallenstein was a brilliant organiser and a ruthless war",
        "entrepreneur. Gustavus Adolphus was a devout man, a reformer of",
        "the art of war — and a conqueror whose armies lived like all the",
        "others. Tilly was a disciplined commander and stands for",
        "Magdeburg. Ferdinand II acted out of genuine conviction and with",
        "it caused terrible damage. Whoever turns them into heroes does",
        "not understand the war; whoever turns them into monsters does not",
        "either.",
        '',
        '## And the other side?',
        '',
        "This narrative has a place where it falls silent. It can say how",
        "many regiments stood where, what a contribution cost and which",
        "article of the peace treaty settled which dispute. It cannot say",
        "what it was like when that regiment came into the village.",
        '',
        'What is called "winter quarters" in the files of the',
        "decision-makers meant in a village: strange men in the house, all",
        "winter long, with weapons, who wanted to be fed. What is called",
        '"contribution" meant: handing over the seed corn meant for the',
        'next year. What is called "recruitment" meant: the son goes',
        "along, voluntarily or not — and the armies were full of people",
        "who had themselves been plundered before.",
        '',
        "These questions the view of the decision-makers cannot answer:",
        "How does one survive thirty years of war? Why did more people die",
        "of hunger and epidemics than in the battles? How does one settle",
        "into a world in which twice a year a different army collects the",
        "taxes and the pastor changes confession? And who actually were",
        "the mercenaries before they became mercenaries?",
        '',
        "They belong to a second voice: the view of those affected, of the",
        "towns and villages. It is equal to this one — and it has more to",
        "tell than the files of the decision-makers suggest.",
      ].join('\n'),
    },
    {
      id: 'betroffene-sicht',
      name: 'The view of those affected',
      stimme: 'Hermes',
      text: [
        "This voice belongs to the people in whose villages and towns the",
        "war took place: the peasants who had to hand over the seed corn;",
        'the craftsmen whose workshop paid the "contribution"; the pastors',
        "who wrote the dead into the church registers; the mothers whose",
        "sons went along because otherwise everything would have been",
        "lost.",
        '',
        "It has other sources than the first voice. The decision-makers",
        "left behind treaties, campaign plans, memoranda. Those affected",
        "left behind diaries, account books, church registers, court",
        "records — and the memory that was passed on in families and",
        "villages. What speaks from these sources is not what was decided",
        "but what arrived.",
        '',
        "And this voice too has a blind spot which it must name itself:",
        "whoever could write was not the poorest. The very poor, who kept",
        "no books, have left almost no voice. What we know about them we",
        "know from others — that too belongs to the honesty of this",
        "narrative.",
        '',
        '## When the war came to the village',
        '',
        "The war did not come as a battle. It came as billeting. What was",
        'called "winter quarters" in the files meant in the village:',
        "strange men in the house, all winter long, with weapons, who",
        "wanted to be fed — and when the food ran out they took the",
        "cattle, and when the cattle were gone they took whatever in the",
        "house was worth something.",
        '',
        'What was called "contribution" meant in the village: handing over',
        "the seed corn. Not the surplus — the seed meant for the next",
        "year. And because almost every party did it that way, a village",
        "often paid twice a year to two different armies, sometimes to",
        "three. There were villages that paid at the same time to the",
        "emperor, to the Swedes and to the French, because nobody knew who",
        "would hold power the next month. Whoever could not pay was",
        "distrained; whoever resisted, his village burned.",
        '',
        '"The war feeds the war" sounds in the field camps like an',
        "account. In the village it sounded like this: in autumn a",
        "regiment came and took the harvest. In winter the next one came",
        "and took the cattle. By spring nothing was left, and still a",
        "regiment came again in summer.",
        '',
        '## The mercenaries — who they really were',
        '',
        "The first voice speaks of armies that were raised and sold. This",
        "voice must say who was inside them — for that is one of the most",
        "uncomfortable truths of this war: many soldiers had previously",
        "been peasants. Whoever had lost everything had no reason left to",
        "stay in the village; whoever went along at least got what the",
        "booty yielded. The armies were full of people who had themselves",
        "been plundered before — and who now stood on the other side of",
        "the plundering, because survival has no clean side.",
        '',
        "We know one of them by name: **Peter Hagendorf**, a mercenary who",
        "kept a diary from 1625 to 1649 — the entire war. He marched",
        "through half of Europe, married, lost wife and children, marched",
        "on. In his diary, next to the marches and plunderings, stand",
        "sentences about his children, his marriage, his faith. History",
        'knows him as a "mercenary" — he himself saw himself as a father',
        "and husband who got through somehow. A human being, not a line",
        "item.",
        '',
        "And this too belongs here, however uncomfortable it is: there",
        "were people who profited from the war. Innkeepers who",
        "provisioned armies; merchants who supplied armies; entrepreneurs",
        'who procured "deliveries"; and some villagers who joined the',
        "plunderers when the opportunity was favourable. The war was a",
        "catastrophe for most — but not for all. Whoever conceals that",
        "tells a prettier story than the sources yield.",
        '',
        '## Hunger',
        '',
        "The worst years came towards the middle of the war: 1634 to",
        "1638. As the seed corn was taken or burned year after year,",
        "there was nothing left to harvest. People ate grass, roots, bread",
        "made of straw and acorns. The church registers of these years are",
        "the most harrowing sources of the whole war: page after page of",
        'death entries, often with the same cause of death — "hunger",',
        '"dysentery", "spotted fever", "died", simply.',
        '',
        "This voice must also speak out the darkest spot that appears in",
        "the sources: there are reports of cannibalism from the worst",
        "hunger years. They are rare, they are disputed, and one does not",
        "read them gladly. But if a chapter about this war wants to be",
        "honest, it cannot conceal them — for they show what happens when",
        "the order of everyday life breaks apart over years.",
        '',
        '## The epidemics',
        '',
        "Most of the dead of this war did not fall in battles but died of",
        "disease — the first voice says that too. From below it looks like",
        "this: plague and dysentery travelled with the armies. A regiment",
        "camped, and in the village next door people died before the",
        "soldiers had taken anything at all. The doctors had fled or were",
        "dead; the pastors recorded what they could not heal. Whole",
        "villages died within a few weeks — not of wounds but of fever,",
        "diarrhoea, exhaustion.",
        '',
        '## Flight, return, empty villages',
        '',
        "Many fled: into the towns, whose walls at least offered some",
        "protection; into the forests, into the mountains, to relatives in",
        "calmer regions. And many did not come back. Hundreds of villages",
        'disappeared entirely — scholarship calls them "Wüstungen"',
        "(abandoned settlements). Where fields had lain, forest grew;",
        "where people had lived, ruins stood. Whoever returned often found",
        "nothing: no house, no neighbours, no church. The church registers",
        "of some parishes break off for decades — as if someone had closed",
        "the book and no one had opened it again.",
        '',
        "And then there was the faith that changed with the rulers. The",
        "lord of the manor became Catholic, the pastor was removed, the",
        "church was reconsecrated. Whoever wanted to stay went along;",
        "whoever did not go along, went. Seen from below, the change of",
        "confession was seldom a matter of conscience and mostly a matter",
        "of survival: one prayed where one was allowed to live.",
        '',
        '## The witch persecutions',
        '',
        "Now this voice must speak out the most uncomfortable spot of its",
        "own story: the terror did not come only from the armies. It also",
        "came from the villages themselves.",
        '',
        "In the war years the witch trials reached their peak — above all",
        "in the 1630s, in exactly the regions that suffered worst.",
        "Accused were predominantly women, often old, often single.",
        'Denounced by neighbours, they "confessed" under torture and were',
        "burned. When crop failures and epidemics no longer had a natural",
        "explanation, people looked for the guilty — and found them in",
        "their own village. That does not make it better. But it explains",
        "why precisely then: the war destroyed not only houses and",
        "harvests, it also destroyed the trust that holds a village",
        "together.",
        '',
        '## What this voice concedes to the other side',
        '',
        "Fairness demands that this voice too names what is not wrong",
        "about the first one.",
        '',
        "The view of the decision-makers is not wrong — it is only",
        "incomplete. Without their decisions the war would not have",
        "begun, and without the peace of 1648 it would not have stopped.",
        "The peace was real. When the news came to the villages, people",
        "knew it would hold — not because they trusted the princes, but",
        "because no one any longer had the strength to break it. Those",
        "affected had no reason to love the decision-makers. But they had",
        "every reason to take the peace.",
        '',
        "And the decision-makers too paid a price: Gustavus Adolphus died",
        "at Lützen, Wallenstein was murdered, some princes ruined their",
        "lands and themselves. And some really tried to keep their",
        "territories out of it — with money, with negotiations, sometimes",
        "in vain. Not everyone at the top wanted the war. But those who",
        "ended it did so from above — and without them it could not have",
        "been ended from below.",
        '',
        '## The memory',
        '',
        "How did this war survive, in people's minds?",
        '',
        "In 1668, twenty years after the peace, a book appeared: \"The",
        "Adventurous Simplicissimus\" by **Hans Jakob Christoffel von",
        "Grimmelshausen**. Its author had experienced the war himself as",
        "a young soldier. His hero goes from peasant boy to mercenary, to",
        "beggar, to hermit — and in the end he knows only one thing for",
        "certain: that man in war is capable of anything. It is the great",
        "book about this war, and it is written from below.",
        '',
        "Beside it stand the silent witnesses: church registers, village",
        "chronicles, account books — and the proverbs that still told",
        'centuries later that "the Swedes had come". For generations the',
        "war was a word of terror with which one admonished children and",
        "made strangers distrusted. That is how long a wound takes to",
        "scar.",
        '',
        '## The question at the end',
        '',
        "War of religion or war of power? The first voice has shown how",
        "hard the question is to answer even from above. From below the",
        "most honest answer is: for the village it was both — and",
        "neither. It did not matter whether the soldiers fought for the",
        "emperor or for the King of Sweden: they came, they took, they",
        "went. Whoever sat in the cellar heard no difference between the",
        "confessions of the men who searched the house.",
        '',
        "But this voice can do something the first cannot: it can say how",
        "one recognises that a war is truly over. Not by the treaty. By",
        "the first winter without billeting. By the first year in which",
        "the seed one had sown oneself was allowed to grow. So when you",
        "answer whether this war was a war of religion or a war of power,",
        "remember: the people who endured it were not asked under what",
        "name it was waged.",
      ].join('\n'),
    },
  ],

  // Synthesis (Round 12, final). Brings both voices together — where they
  // agree, where they diverge, and why that is so.
  synthese: [
    "Now both voices stand side by side: the view of the emperor, the",
    "princes and the generals and the view of those affected. What can",
    "be learned from it?",
    '',
    "**Where they agree.** That is more than one would expect. Both",
    "voices name the same events — the Defenestration of Prague in 1618,",
    "the White Mountain, Magdeburg, Breitenfeld, Lützen, the Peace of",
    "Westphalia — and both name the same numbers: a third to two thirds",
    "of the population in the hardest-hit regions, most of the dead",
    "from hunger and epidemics, not from weapons. Both also agree on",
    'the most uncomfortable diagnosis: "The war feeds the war" was no',
    "law of nature but a system, and confession was often the pretext",
    "and seldom the whole reason. The first voice says it from the",
    "treaties, the second from the church registers — it is the same",
    "statement, from two archives.",
    '',
    "**Where they diverge.** The difference begins with the scale. The",
    "first voice tells in campaigns and treaty articles; in its",
    "narrative the population is a line item — contribution, quarters,",
    "recruitment. The second voice tells in winters, harvests and death",
    "entries; in its narrative the campaigns are the times when one hid",
    "the seed corn. Both tell the same war — but one from above, where",
    "it was justified, the other from below, where it arrived.",
    '',
    "The second difference is the question of the end. For the",
    "decision-makers the war ended with the peace of 1648: a negotiated",
    "body of treaties that settled the question of confession with a",
    "cut-off date, gave the estates sovereignty and founded the modern",
    "system of states. For those affected it ended later and",
    "differently: with the first winter without billeting, the first",
    "year in which the seed corn was allowed to grow. Both endings are",
    "true — but they do not fall on the same day.",
    '',
    "The third difference concerns the question of guilt — or rather:",
    "the question of who may ask it at all. The first voice names",
    "names, dates and decisions; it can say who prolonged the war and",
    "who ended it. The second voice reminds us that the people who paid",
    "the price were never asked — neither about the name of the war nor",
    "whether they liked it. That is no counter-account but a reminder",
    "of what stands in no treaty document.",
    '',
    "**What follows from it.** Whoever reads this chapter holds two",
    "narratives in hand that do not have to contradict each other —",
    "they only have different angles on the same misfortune. The",
    "synthesis cannot make a single truth out of them, and it does not",
    "want to. But it can show one thing both voices have in common:",
    "both know that the peace of 1648 was a beginning — the beginning",
    "of a Europe that no longer wanted to wage wars as questions of",
    "faith. That there were wars again anyway stands on a different",
    "page. Precisely there your judgement begins: war of religion or",
    "war of power — and on what would you base it if you had sat in a",
    "village in the year 1636?",
  ].join('\n'),

  urteil: {
    frage: "Was the Thirty Years' War a war of religion or a war of power — and on what would you base the difference? Which answer does the narrative from above give you, and which question remains open?",
    hinweis: 'There is no right and no wrong here. Three prompts: First, collect the cases that do not fit the scheme — a Catholic cardinal who pays Lutheran armies; a Lutheran elector who fights for the Catholic emperor; a Catholic Bavaria that secretly negotiates a separate peace. Second, test the counter-check: Ferdinand II could have ended the war with a stroke of the pen if he had withdrawn the Edict of Restitution — why did he not do it for years? Third, ask about the measure: the Peace of Westphalia did not decide the question of faith, it settled it with a cut-off date. Is that a victory of reason, an admission of exhaustion — or both?',
  },

  quiz: [
    {
      frage: 'What began the war in 1618?',
      antworten: [
        'With the invasion of Swedish troops into Pomerania.',
        'With the Defenestration of Prague: Bohemian nobles threw two imperial governors and their secretary out of a window of the castle.',
        'With the Edict of Restitution of Emperor Ferdinand II.',
      ],
      richtig: 1,
      erklaerung: 'All three survived the fall from about seventeen metres. Behind it stood the dispute over the "Letter of Majesty" of 1609, which had guaranteed the Bohemian estates freedom of faith. Bohemia was an elective kingdom: the estates deposed Ferdinand and elected Frederick V of the Palatinate. On 8 November 1620 they lost at the White Mountain.',
    },
    {
      frage: 'What did the principle "The war feeds the war" mean?',
      antworten: [
        'That soldiers only fought in summer, when there was enough to harvest.',
        "That the armies provisioned themselves from the occupied land — through contributions, quartering and plundering — because the princes' war chests were empty.",
        'That every battle triggered the next until one side won.',
      ],
      richtig: 1,
      erklaerung: 'The sentence is attributed to Wallenstein, and it describes a system: contributions were formally calculated sums that towns and regions paid in order not to be plundered. All sides worked this way. An army that feeds itself from the land must move on as soon as the land is empty — that is one of the reasons why the war lasted so long.',
    },
    {
      frage: 'Why did Catholic France enter the war in 1635 against Catholic Habsburg?',
      antworten: [
        'Because the pope called for it.',
        'Because the king and Cardinal Richelieu had secretly converted to Protestantism.',
        'Out of reason of state: France saw itself encircled by Spain and Austria and wanted to weaken Habsburg — confession or not.',
      ],
      richtig: 2,
      erklaerung: 'Cardinal Richelieu had already supported Sweden with money since the Treaty of Bärwalde of 1631 instead of fighting himself. In 1635 France declared war on Spain; in 1643 it won at Rocroi. At the latest then it was clear that this war was not only about faith — which does not mean that faith was unimportant for those involved.',
    },
    {
      frage: 'What was agreed in 1648 in Münster and Osnabrück?',
      antworten: [
        'The Empire was divided into a Catholic and a Protestant state.',
        'The religious peace was confirmed and extended to the Reformed, the Normal Year 1624 applied to church property, and the imperial estates received territorial sovereignty and the right to conclude their own alliances.',
        'The emperor received the sole decision over the confession in the whole Empire.',
      ],
      richtig: 1,
      erklaerung: 'Negotiated in two cities because the confessions did not want to sit at one table. Sweden received Western Pomerania, Wismar, Bremen and Verden, France the Habsburg rights in Alsace; the Netherlands and Switzerland formally left the Empire. The peace did not decide the question of faith — it settled it with a cut-off date.',
    },
    {
      frage: "What did most people in the Thirty Years' War die of?",
      antworten: [
        'In the great field battles such as Breitenfeld and Lützen.',
        'Of hunger and epidemics that followed the passing armies.',
        'During the siege of Magdeburg in 1631.',
      ],
      richtig: 1,
      erklaerung: 'The battles claimed many dead, but the great majority died of epidemics such as plague and typhus and of hunger when seed corn and cattle were gone. In the Empire the population fell from an estimated 16 to 18 million to 10 to 13 million, regionally by up to two thirds — elsewhere it stayed almost calm. The figures rest on tax lists and church registers and are disputed.',
    },
  ],
};

module.exports = dreissigjaehrigerKrieg;
