// Topic: Genghis Khan and the Mongols — the largest land empire in history.
//
// English translation of utils/themen/dschingis-khan.js. Field names follow
// the German schema (aufhaenger, perspektiven, synthese, urteil, quiz) — only
// the texts are translated. The map (karten/dschingis-khan.js) is omitted in
// this English module, as are the karteHinweise.
//
// Status: Round 5. The chapter has two voices: the European perspective
// (Voice: Opus) and the Chinese perspective on the Yuan period (Voice: Hermes).
// Europe experienced the Mongols for two years as catastrophe and then for a
// hundred years as an open road to the east. China experienced them for almost
// a century as rulers in its own land. These are two very different
// experiences of the same people.
//
// Pure data — no UI imports (architecture rule).

const dschingisKhan = {
  id: 'dschingis-khan',
  titel: 'Genghis Khan and the Mongols — the largest land empire in history',
  epoche: 'From the kurultai of 1206 to the end of the Yuan dynasty in 1368',

  aufhaenger: {
    frage: 'A people without cities, without writing, without any art of siege conquers in fifty years the largest contiguous land empire that has ever existed — larger than Rome and China combined. How is that possible?',
    text: [
      'Do the arithmetic for a moment. The Roman Empire at its height covered about',
      'five million square kilometres. The Han Empire was of similar size. The',
      'Mongol Empire reached roughly twenty-four million — a fifth',
      'of the earth\'s land surface, from Korea to Poland, from Siberia to the',
      'Persian Gulf. At the start there stood perhaps one million people',
      'on the steppe. Rome alone, in the city of Rome, had more inhabitants.',
      '',
      'And these people had none of the things one assumes are needed. No cities',
      'from which to draw supplies. No writing in which to',
      'record orders — they only got that along the way, from a',
      'captured scribe. No experience in cracking walls; their',
      'first sieges failed miserably.',
      '',
      'What they had were horses, bows, a new law — and a man',
      'who grew up as the son of an abducted woman, whose father was poisoned',
      'and who as a boy was held captive in a wooden yoke. His name was',
      'Temüjin. We know him by the title the assembled',
      'tribes gave him in 1206: Genghis Khan.',
      '',
      'In Europe, at first, nobody knew him at all. People knew only what in 1241',
      'came out of the east — and took it for the end of the world.',
    ].join('\n'),
  },

  // "History in motion" — the map would come after the hook and before the
  // perspectives. Omitted in this English module (see karten/dschingis-khan.js).

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'European perspective',
      stimme: 'Opus',
      text: [
        'This is how the history of the Mongols is told in Europe: first as terror,',
        'then as wonder, later as a matter of dispute. Europe never experienced this',
        'empire from within — it feared it for two years and used it for a hundred',
        'years afterwards. That shapes the story to this day. So read it',
        'for what it is: the view from the western edge of a world whose centre',
        'lay elsewhere.',
        '',
        '## 1241: The scourge of God at the door',
        '',
        'On 9 April 1241, at Liegnitz in Silesia, an army of',
        'knights, miners and brethren of the military orders faced a host of which',
        'nobody knew exactly where it came from. Duke Henry II of Silesia',
        'led it. The battle did not last long.',
        '',
        'The Mongols did what they always did: they feigned a retreat,',
        'the knights gave chase, their formation dissolved — and then the',
        'trap closed. Duke Henry fell. His head was carried on a lance',
        'before the walls of Liegnitz. The place has been called Wahlstatt ever since,',
        'after the old word for battlefield.',
        '',
        'Two days later, several hundred kilometres to the south, the same happened at Mohi',
        'in Hungary to the army of King Béla IV. Two European armies,',
        'two days, two defeats — coordinated over a distance for which',
        'European messengers would have needed weeks. That was precisely what was',
        'terrifying: these horsemen were not wild, they were organised.',
        '',
        'Europe had no explanation. What it had was the Bible. People read the',
        'horsemen as the peoples of Gog and Magog, who at the end of times break forth',
        'from behind the mountains. They called them **Tatars** — and because in',
        'Latin that sounded almost like *Tartarus*, the underworld, the word was',
        'at once an explanation in itself: these people came from hell. Louis',
        'IX of France is said to have told his mother that either one sent',
        'the Tatars back to Tartarus, or they sent everyone to',
        'heaven. The chronicler Matthew Paris wrote in faraway England of',
        'people who eat raw meat and drink blood; he had never seen a Mongol.',
        '',
        'In northern Germany the herring trade failed that year, because the',
        'fishermen from Gotland and Friesland did not put to sea. The fear reached',
        'further than the horsemen.',
        '',
        '## Saved by a death',
        '',
        'And then, in the spring of 1242, the Mongols turned back. They had been on the',
        'Danube, they had laid waste to Hungary, their vanguard had Vienna in sight',
        '— and they withdrew, eastwards, for no apparent reason.',
        '',
        'The explanation Europe has told itself ever since is a death: On',
        '11 December 1241 the Great Khan Ögödei, the son and',
        'successor of Genghis Khan, died in Karakorum. The princes of the empire, among them Batu,',
        'the leader of the western army, had to return for the kurultai — the',
        'assembly that elected the new Great Khan. A death in',
        'Mongolia, 6,000 kilometres away, saved Central Europe.',
        '',
        'That is a good story, and it probably contains truth. But',
        'it is also convenient: it spares Europe the question of whether it could',
        'have defended itself. Historians today name further',
        'reasons — the Hungarian winter of 1241/42 was wet, the pastures gave too',
        'little for hundreds of thousands of horses; Hungary\'s stone castles were',
        'tougher than the wooden towns of the Rus; and the goal of the campaign may',
        'never have been the conquest of Europe, but the securing of the',
        'western flank.',
        '',
        'Mark this passage. Here you watch, as an observer, how history',
        'is made: out of "we do not know exactly why they left" becomes, over',
        'the centuries, "Europe was saved". Whoever tells, selects.',
        '',
        'For one part of Europe the rescue did not hold anyway. The princes',
        'of the Rus — later Russia and Ukraine — remained. Kiev had fallen in 1240;',
        'for about 240 years the Russian princes paid tribute to',
        'the Golden Horde and obtained in its camp on the Volga the',
        'permission to rule. Russian historiography calls this',
        'time the "Tatar Yoke". Seen from the west, 1242 was a fortunate',
        'ending. Seen from Kiev, it was the beginning.',
        '',
        '## The Pax Mongolica — suddenly the road is open',
        '',
        'Then the strangest thing in this whole story happened: out of',
        'the terror came an opportunity.',
        '',
        'For the first and only time in history, the entire',
        'land route from China to Europe belonged to a single order. The Mongols',
        'lived off trade — tolls were their revenue, caravans their capital.',
        'So they protected the roads. Highway robbery was severely punished. On the',
        'great routes stood stations every 40 kilometres of the **Jam**, the',
        'postal system: fresh horses, lodging, provisions. A courier with',
        'a paiza — a passport tablet of wood, silver or gold — could cover in',
        'a single day what a caravan needed a week for.',
        '',
        'A merchant from Florence wrote in his handbook around 1340 that the road',
        'to China was "quite safe, by day and by night". That had not been true since',
        'the Romans, and would not be true again for centuries afterwards.',
        '',
        'Added to that was an attitude foreign to Europe: the Mongols did not ask',
        'about faith. They hired tax officials whether they were Muslims,',
        'Buddhists, Nestorians or Confucians. Priests of all',
        'religions were exempt from levies. In Karakorum in 1254, Möngke Khan had',
        'Christians, Muslims and Buddhists publicly dispute with one another',
        'while he listened — in the middle of a century in which Europe was waging Crusades.',
        'His tolerance was also useful to him: whoever has no',
        'state religion has none to enforce.',
        '',
        'So Europe sent envoys. In 1245 Pope Innocent IV sent the',
        'Franciscan John of Plano Carpini on his way, an old, heavy man',
        'who rode through the steppe on a horse for two years. He actually',
        'got as far as Karakorum, saw the election of Great Khan Güyük and brought',
        'back a letter. The pope had asked for peace and baptism. The',
        'answer was brief: if the pope wanted peace, he should come in person',
        'and submit. A few years later William of',
        'Rubruck travelled the same road and wrote the first sober account of the',
        'Mongols that Europe possessed — with observations instead of demons.',
        '',
        '## Marco Polo and the wonder nobody believed',
        '',
        'The most famous of these travellers was no monk, but a young',
        'merchant from Venice. **Marco Polo** set out in 1271 with his father and uncle',
        'and only returned in 1295 — twenty-four years later. He spent a large',
        'part of that time in the service of the Great Khan Kublai, the grandson of',
        'Genghis Khan, who by then ruled over all of China.',
        '',
        'What he told was simply unbelievable to European ears:',
        '',
        '- **Money made of paper.** The Khan had bark from mulberry trees pressed into sheets,',
        '  stamped with his seal — and everyone accepted that as',
        '  payment, as if it were gold. In Europe, money was something you weighed.',
        '- **Stones that burn.** People dug black stones out of the earth and',
        '  heated their houses with them; they held their glow longer than wood. Marco',
        '  Polo had seen coal.',
        '- **Cities without end.** Quinsai — today\'s Hangzhou — was said to have twelve thousand',
        '  bridges and more inhabitants than Venice could imagine. Venice',
        '  then had perhaps a hundred thousand.',
        '- **A post that flies.** Messages covered distances with the Jam system',
        '  for which European messengers needed months.',
        '',
        'Nobody believed him. His book got the mocking name *Il',
        'Milione* in Italy — the teller of millions, that is, the braggart. Legend',
        'has it that friends at his deathbed asked him finally to recant,',
        'and that he answered he had not told even half.',
        '',
        'Even so, the book was copied and read, again and again. Two',
        'centuries later a Genoese seafarer owned a copy,',
        'covered with notes in the margin, and wanted to reach the wealth of that',
        'East by sailing west. His name was Christopher',
        'Columbus. On this detour the Mongol Empire made America known to',
        'Europe.',
        '',
        'The open road, however, had a second side that nobody',
        'had ordered. In the middle of the 14th century, over those same routes,',
        'a disease travelled west. The Black Death may have cost Europe',
        'a third of its people. Whatever transports goods and ideas also',
        'carries fleas.',
        '',
        '## The barbarian and the pathfinder',
        '',
        'So how does Europe remember Genghis Khan? Honest answer: in two',
        'images that cannot stand each other.',
        '',
        'The older one is the image of the **destroyer**. The numbers are terrible,',
        'even if they are disputed: cities like Nishapur, Merv, Herat and',
        'Baghdad were plundered, their populations killed or carried off.',
        'Baghdad was in 1258 the intellectual centre of the Islamic world — Hülegü, a',
        'grandson of Genghis Khan, ended the caliphate of the Abbasids, and the',
        'libraries of the city went under. The irrigation systems of',
        'Mesopotamia and Persia, built over centuries, never fully recovered.',
        'Some estimates speak of millions of dead. Whoever says',
        'that this is "also a point of view" has missed the point: destruction is',
        'no perspective.',
        '',
        'The younger one is the image of the **pathfinder**. It stresses: the Mongols',
        'united Eurasia for the first and only time under one order.',
        'They protected trade routes, let religions exist side by side,',
        'gathered craftsmen and scholars instead of killing them, and carried',
        'techniques across continents: printing, paper, the compass, gunpowder',
        'went west, Persian astronomy and medicine went east. Without',
        'these hundred open years — so the thesis — Europe would have received its',
        'modern age later or differently.',
        '',
        'Both images are true, and they describe the same people. It is only',
        'hard to hold them in mind at the same time. If that makes you',
        'uncomfortable, you are in the right place: this is exactly where history',
        'begins to get interesting.',
        '',
        'Incidentally, Mongolia itself sees it unambiguously. Genghis Khan is',
        'there the founder of the nation; the airport of Ulaanbaatar bears his',
        'name, his face is on the banknotes. In the Soviet era',
        'his name was forbidden, afterwards it came back immediately. One man, three countries,',
        'three answers.',
        '',
        '## And the other side?',
        '',
        'Everything you have just read is the view from outside — and,',
        'additionally, the view from very far outside. For the Mongols, Europe was',
        'a peripheral region, a campaign of two years, afterwards a trading partner',
        'at the far western end of the world.',
        '',
        'For China it was something entirely different. There the Mongols did not wage',
        'a campaign, there they ruled: Kublai Khan proclaimed in 1271 a Chinese',
        'dynasty, the **Yuan**, built himself a capital in Dadu — today\'s Beijing —',
        'and in 1279 ended the realm of the Song. For almost a',
        'century China was ruled by foreigners, in a land that',
        'understands itself as the centre of the world. How do you tell that from inside?',
        'Is Kublai a Chinese emperor or an occupier? And what does it do',
        'to a narrative in which dynasties come and go, when this time the',
        'dynasty comes from the steppe?',
        '',
        'These questions the European perspective cannot answer. They',
        'belong to a second voice, one that tells these hundred years from inside.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Chinese perspective',
      stimme: 'Hermes',
      text: [
        'This perspective tells the history of the Mongols from inside — from',
        'China, where they ruled for almost a century. For the Chinese',
        'narrative this is the most difficult story of all: the Middle',
        'Kingdom, for the first time in its long history, completely',
        'ruled by people from the steppe. How do you tell that without',
        'breaking your own self-image? The answer of Chinese',
        'historiography is as bold as it is consistent.',
        '',
        '## The Mandate knows no origin',
        '',
        'The key is the Mandate of Heaven — which you already know from the chapter on',
        'China. It says: Heaven grants rule',
        'to whom it will, and takes it back when it is badly exercised.',
        'From this follows something that sounds surprising to outsiders:',
        'Heaven does not ask about origin. It has often given the mandate',
        'to peasants and soldiers who founded a realm — why not',
        'once, too, to riders from the steppe?',
        '',
        'The Chinese narrative therefore reads the Mongol conquest',
        'not as a breach from outside, but as a judgment from above: the',
        'Song dynasty had forfeited the mandate. It was weak, its',
        'generals mistrusted one another, its officials quarrelled — and a realm',
        'that cannot defend itself has, by this logic, lost the right to',
        'rule. That the new masters came from the steppe was',
        'no contradiction of the order of the world. It was the order of the world.',
        '',
        '## Kublai became Chinese',
        '',
        'And then something happened that shaped the history of the world:',
        'Kublai Khan committed himself to China. He gave his rule the',
        'dynasty name **Yuan** — "origin" — and thereby placed himself in the',
        'line of the Chinese dynasties. He moved the capital to',
        'Dadu, today\'s Beijing, took over the official bureaucracy, adopted the',
        'calendar, had the imperial history written. Out of the conqueror became',
        'an emperor — and Beijing has been China\'s capital ever since, to this day.',
        '',
        'The Chinese narrative sees in this the proof that the Middle',
        'Kingdom was stronger than its conquerors: the Mongols conquered China,',
        'but China shaped the Mongols. Whoever ruled in Dadu ruled',
        'Chinese-style — with Chinese officials, Chinese ceremonial,',
        'Chinese script. The steppe lord became the Son of Heaven.',
        '',
        '## What the Yuan brought',
        '',
        'The Chinese narrative is not blind to what the Yuan period',
        'brought. The most important thing: **reunification.** Since the end of the Tang,',
        'China had fallen apart into separate realms — Song in the south, Jin in the north,',
        'plus Tanguts and others. Almost three hundred years of separation, three',
        'centuries in which the Middle Kingdom was divided. The Mongols',
        'made one China out of it again. For a civilisation that defines itself over',
        'unity, that is no small point.',
        '',
        'Added to that was the open world. Under the Yuan the Silk Road was',
        'safer than ever — and again the world came to the centre: merchants from',
        'Persia, traders from Venice, scholars who were welcome in Dadu.',
        'Marco Polo, of whom the European narrative reports, was in the',
        'Chinese narrative one of many foreigners who served at the emperor\'s',
        'court — interesting, but no wonder of the world. That the West',
        'considered this visitor the sensation says, from a Chinese point of view,',
        'more about the West than about China.',
        '',
        '## The price',
        '',
        'The Chinese narrative stays honest, too: the Mongols',
        'did not rule like Chinese emperors. They divided the people into',
        'four classes — Mongols at the top, then foreign allies, then',
        'the northern Chinese, last the southern Chinese, who had resisted the longest.',
        'Chinese were second-class citizens in their own capital. The tax burden',
        'was high, and more than one official in the',
        'heartland of the empire served a lord whose language he did not',
        'understand.',
        '',
        'That, too, belongs to the narrative. The Yuan dynasty ruled with',
        'the Mandate of Heaven — but it ruled as foreigners, and in the long run',
        'that was unbearable. When in the 14th century crop failures, floods',
        'and uprisings shook the realm,',
        'historiography read that as a sign: the Mandate left the Yuan,',
        'as it had left the Song. In 1368 the Mongols withdrew into',
        'the steppe, and the Ming dynasty took over — again a',
        'Chinese dynasty, again the cycle.',
        '',
        '## And then the Ming wrote the history',
        '',
        'Here the history of the Yuan itself becomes a lesson about',
        'history. The official chronicle of the Yuan dynasty was, in fact,',
        'written by the Ming dynasty — by the victors who had driven the',
        'Mongols out. And the Ming did something astonishing:',
        'they let the Yuan stand in the line of the Chinese dynasties.',
        'Not out of generosity. But because their own rule was only',
        'legitimate if it appeared as the next dynasty in the cycle of the',
        'mandate — and the cycle demanded that the Yuan',
        'had belonged. The admission of the foreign rulers into the',
        'dynastic line was itself a political act.',
        '',
        'That is the answer to the question that stands at the end of the European',
        'narrative: Is Kublai a Chinese emperor or an',
        'occupier? The Chinese narrative says: whoever unites the realm and',
        'bears the mandate is emperor — origin is secondary. And',
        'yet China argues about it to this day, over how the Yuan are to be judged.',
        'Some celebrate the reunification and the open world,',
        'others remember the four classes and the foreign rule.',
        '',
        'That a people cannot agree on how to tell its own history',
        'is no weakness — it is the most honest thing',
        'a civilisation can say about itself. The',
        'Chinese narrative, too, is no truth. It is a voice that',
        'comes from the centre — and one that knows the victors write.',
      ].join('\n'),
    },
  ],

  // Synthese (Round 5, jointly revised after the Chinese perspective was
  // added by Hermes).
  synthese: [
    'Three names for the same people: "Tatars" — those who come from Tartarus,',
    'from hell. "Yuan" — a dynasty name in the line of the',
    'Chinese dynasties. "Tatar Yoke" — the word Russian',
    'historiography found for 240 years of tribute. Three words,',
    'three narratives, one empire. That is exactly what this chapter is about.',
    '',
    '**Where they meet:** Both perspectives call the same empire',
    'unprecedented — larger than anything before, from Korea to Poland. Both',
    'tell the Pax Mongolica: secured trade routes, the Jam postal system,',
    'religious tolerance, the open road east. And both make the',
    'withdrawal of 1242 or, respectively, the conquest of 1279 the turning point',
    'of their narrative.',
    '',
    '**Where they diverge:** The European narrative experienced the',
    'Mongols for two years as terror — "scourge of God", "saved by',
    'a death" — and afterwards for a hundred years as a distant opportunity:',
    'envoys, Marco Polo, business. For Europe the Mongols were an',
    'event. The Chinese narrative experienced them for almost a century',
    'as rulers: Kublai became emperor, China was reunited, the',
    'world came to Dadu. For China the Mongols were an epoch. And the',
    'third voice at the margin — that of the Rus — calls the same time a yoke.',
    'Three experiences, three words, three judgments of the same',
    'rule.',
    '',
    '**What follows from it:** The names are the interpretation. Whoever says "Tatars",',
    'tells of hell; whoever says "Yuan", tells of the Mandate of',
    'Heaven, which can also be granted to steppe riders; whoever says',
    '"Tatar Yoke", tells of oppression. And the Chinese',
    'narrative adds the finest point: even the official',
    'history of the Yuan was written by its vanquishers — the Ming,',
    'who admitted them into the dynastic line because their own',
    'legitimacy depended on it. The victor writes history — and',
    'sometimes he even writes the history of the victor he',
    'defeated.',
    '',
    '**Your judgment begins here:** Was Genghis Khan a conqueror or a',
    'path-opener? The question may lead astray — he was both,',
    'and the answer depends on whom you ask: the merchants, the',
    'descendants of the slain, Mongolia, which celebrates him as founder,',
    'or the historiographers of the Ming. Which voice speaks to you',
    'most — and which would you like to hear as well?',
  ].join('\n'),

  urteil: {
    frage: 'Genghis Khan had cities wiped out and at the same time created a space in which goods, knowledge and people could travel safely between China and Europe. Was he a conqueror and destroyer or an establisher of order and opener of paths — and who is actually entitled to decide that: the descendants of the slain, the merchants who lived off it, or Mongolia, which celebrates him as the founder of its country?',
    hinweis: 'There is no right and no wrong here. Consider whether the question may be wrongly posed — must one decide for one of the two? And test your answer for whether you would apply the same standards to conquerors closer to you: to Caesar, for example, or to Alexander "the Great".',
  },

  quiz: [
    {
      frage: 'Did Genghis Khan conquer China?',
      antworten: [
        'Yes, he subjugated all of China down to the southern coast.',
        'Only the north — the realm of the Tanguts and large parts of the Jin realm. All of China was conquered only by his grandson Kublai, in 1279.',
        'No, China remained independent throughout the whole Mongol period.',
      ],
      richtig: 1,
      erklaerung: 'Genghis Khan died in 1227, in the middle of the campaign against the Tanguts. The south — the realm of the Song — held out for over fifty years. Only Kublai Khan ended it in 1279 and ruled over all of China as emperor of the Yuan dynasty.',
    },
    {
      frage: 'Did the Mongols conquer Europe?',
      antworten: [
        'No, they never got beyond the Vistula.',
        'Yes, all of Europe was Mongol by 1300.',
        'Partly: in 1241 they defeated the armies in Poland and Hungary and withdrew again in 1242 — but the Russian principalities remained under the Golden Horde for about 240 years.',
      ],
      richtig: 2,
      erklaerung: 'For Central Europe, what had begun in 1241 was over in 1242. Not for the Rus: Kiev fell in 1240, and the princes paid tribute for almost two and a half centuries. Whether "Europe was conquered" therefore depends on where in Europe you ask.',
    },
    {
      frage: 'Why did the Mongols withdraw from Hungary in 1242?',
      antworten: [
        'Because a European army defeated them in a great battle.',
        'The best-known explanation is the death of the Great Khan Ögödei in 1241 — the princes had to return for the election of his successor. It is not known for certain.',
        'Because the pope paid them gold in exchange for the withdrawal.',
      ],
      richtig: 1,
      erklaerung: 'A death 6,000 kilometres away — that is the explanation Europe has told itself for centuries. Today further reasons are named: wet pastures in the winter of 1241/42, tough stone castles — and perhaps the conquest of Europe was never the goal.',
    },
    {
      frage: 'Who was Marco Polo?',
      antworten: [
        'A Venetian merchant who was away for 24 years, served at the court of Kublai Khan — and whom hardly anyone at home believed.',
        'A military commander who defeated the Mongols at Liegnitz.',
        'A papal envoy who was supposed to baptize the Mongols.',
      ],
      richtig: 0,
      erklaerung: 'In the vernacular his book was mockingly called "Il Milione" — the braggart: paper money, burning black stones and cities with millions of people were taken for invented. Two centuries later Christopher Columbus read this book — and wanted to reach that East from the West.',
    },
    {
      frage: 'What does "Pax Mongolica" mean?',
      antworten: [
        'A peace treaty between the pope and the Great Khan.',
        'The time in which the entire land route between China and Europe belonged to one empire — trade routes were protected, religions tolerated, messages ran over a postal system with relay stations.',
        'The name of the Mongol law code.',
      ],
      richtig: 1,
      erklaerung: 'The Mongols lived off tolls, so they secured the roads. A Florentine merchant wrote around 1340 that the road to China was "quite safe, by day and by night". Along those same open routes, however, the Black Death also came to Europe.',
    },
  ],
  karteHinweise: [
    {
      label: "1206",
      hinweis: "At the kurultai at the source of the Onon, the assembled tribes proclaim Temüjin as Genghis Khan. What he rules is not an empire but a confederation: perhaps one million people, more horses than people, not a single city. Look at this spot closely — the next map is twenty-one years later.",
    },
    {
      label: "1227",
      hinweis: "In the year of Genghis Khan’s death the empire reaches from the Caspian Sea to the Yellow Sea. The Khwarezmian Empire, in 1219 still a great power with Samarkand and Bukhara, has disappeared. In China the advance ends at the Yellow River: the south still belongs to the Song — and will remain so for fifty years.",
    },
    {
      label: "1259",
      hinweis: "The greatest extent: from Korea to the Carpathians, from Siberia to the Persian Gulf. About twenty-four million square kilometres, a fifth of the earth’s land — never before has an empire held so much together, and never again afterwards. Four patches of colour, one empire: one Great Khan still applies to all.",
    },
    {
      label: "1294",
      hinweis: "At the death of Kublai Khan the empire is still huge — but it is no longer one. Four successor empires go their own ways, fight their own wars, adopt their own religions. In China Kublai rules as emperor of a Chinese dynasty, the Yuan, from Dadu — today’s Beijing. The steppe has become a province.",
    },
  ],
};

module.exports = dschingisKhan;
