// Topic: The Germanic peoples and the Migration Period.
//
// English translation of utils/themen/germanen.js (DE schema, field names
// unchanged: id, titel, epoche, aufhaenger, perspektiven, synthese, urteil,
// quiz). Status: Round 8. Contains ONLY the Roman-Mediterranean viewpoint
// (voice: Opus) as the first perspective; the Germanic viewpoint (voice:
// Hermes) follows as the second. The synthesis is explicitly provisional and
// will be jointly revised afterwards (see CLAUDE.md, perspectives workflow).
//
// With this topic, the app's guiding idea takes an unusual turn. "The victor
// writes history" — not here. Almost everything we think we know about the
// Germanic peoples stands in the texts of the empire that went under: written
// by people who had never been there, in the language of the losers, about
// opponents who left no history books of their own. And the winners — the
// kings of the new kingdoms — afterwards wrote in Latin and named themselves
// after the Roman model. Whoever wants to change perspective here must
// therefore first admit how thin the source material on the other side is.
// That is exactly what the second voice does.
//
// No map data in this translation (the German original carries the map in
// utils/themen/karten/germanen.js).
//
// Pure data — no UI imports (architecture rule).

const germanen = {
  id: 'germanen',
  titel: 'The Germanic Peoples and the Migration Period',
  epoche: 'From Caesar’s Rhine frontier in 58 BC to the Lombards in 568 AD',

  aufhaenger: {
    frage: 'A world empire disappears — and no one who was there notices. How is that possible, and didn’t the alleged destroyers of Rome in truth want to be Romans themselves?',
    text: [
      'In September 476, an officer named Odoacer deposed the Western Roman',
      'emperor in Ravenna. The emperor was a boy, perhaps sixteen years old,',
      'and he bore the inappropriately grand name Romulus Augustulus — “little',
      'Augustus.” Odoacer did not have him killed. He sent him to an estate',
      'near Naples with an annual pension.',
      '',
      'Today this year stands in every schoolbook: 476, the end of the Roman',
      'Empire. At the time, hardly anyone wrote about it. No chronicle records',
      'a turning point in history, no speech laments the end of the world.',
      'Odoacer did not proclaim himself emperor; instead he sent the insignia',
      'of power to Constantinople and had himself called king — in the name of',
      'the emperor who continued to rule there. For contemporaries, this was',
      'an administrative change.',
      '',
      'And it gets even stranger. The men who allegedly destroyed Rome',
      'afterwards did everything to seem Roman. They had their laws written',
      'down in Latin. They kept Roman officials, Roman taxes, Roman titles.',
      'Theodoric the Ostrogoth ruled Italy and, in doing so, called himself',
      'the emperor’s governor. Whoever wants to destroy something does not',
      'afterwards carefully rebuild it.',
      '',
      'So, two questions. First: What really happened — a downfall or a',
      'transformation? Second, and this is the more uncomfortable one: How do',
      'we actually know? For almost every word we have about the Germanic',
      'peoples comes from their enemies.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'roemisch',
      name: 'Roman-Mediterranean viewpoint',
      stimme: 'Opus',
      text: [
        'This is how the history of the Migration Period is told in the',
        'tradition that comes from the Mediterranean world — from the cities,',
        'the libraries and the chanceries of the Roman Empire and its heirs.',
        'It is the story of those who could write — and did.',
        '',
        'And right at the start there is a peculiarity. Usually the rule is:',
        'The victor writes history. Here it is the other way round. About the',
        'Germanic peoples we know almost only what their enemies wrote down',
        'about them — and those enemies lost. The Germanic peoples themselves',
        'left no history books. They had a script, the runes, but they used',
        'it for short inscriptions on weapons, stones and jewellery, not for',
        'chronicles. The oldest long text in a Germanic language is a Bible',
        'translation: The Gothic bishop Wulfila translated the Holy Scripture',
        'into Gothic in the 4th century and invented a special alphabet for',
        'it. From it we learn almost nothing about his people — except for',
        'one small detail that a later author reports: Wulfila is said to',
        'have left out the books of the kings with their war stories — his',
        'people, he said, were warlike enough.',
        '',
        'So read what follows as what it is: the inside view of an empire',
        'that never understood its neighbours and was finally inherited by',
        'them.',
        '',
        '## How Rome invented its neighbours',
        '',
        'In 58 BC, Caesar marched into Gaul, and in the report he wrote about',
        'it, he drew a line: West of the Rhine live the Gauls, east of it the',
        '*Germani*. That was tidy, clear and practical — and it was an',
        'invention. The people there did not call themselves that. They would',
        'have called themselves Chatti, Cherusci, Marcomanni — or not a group',
        'at all. A river on the map became a people. Rome needed a name for',
        'the other side, and whoever draws a frontier thereby also creates',
        'what lies beyond it.',
        '',
        'A hundred and fifty years later, a Roman senator named Tacitus wrote',
        'a slender book about this land: the **Germania**, around 98 AD. To',
        'this day it is the most important source on the early Germanic',
        'peoples — and it must be said that Tacitus was never there. He',
        'gathered what traders, soldiers and older books had to offer.',
        '',
        'But above all, he was not really writing about Germania at all. He',
        'was writing about Rome. His Germanic peoples are loyal, brave,',
        'hospitable and incorruptible; they know no luxury, their marriages',
        'are firm, their leaders lead by example. Every sentence is a',
        'reproach to his own capital, where Tacitus experienced bribery,',
        'pomp and denunciation. That is an old figure of thought: the noble',
        'savage who holds up a mirror to us. Only, it is a mirror — and in it',
        'you always see only yourself.',
        '',
        'This book has a dangerous afterlife. It was long considered lost,',
        'reappeared in a German monastery in the 15th century — and from then',
        'on was read as if it were a certificate of ancestry. Out of',
        'Tacitus’s “unmixed people,” nationalists and finally the National',
        'Socialists centuries later built themselves proof for their racial',
        'doctrine; in 1943 Himmler had the oldest manuscript searched for in',
        'Italy. A historian has therefore called the Germania one of the most',
        'dangerous books ever written. One should know this before uttering',
        'the word “Germanic peoples”: It is a Roman collective name, and in',
        'the 20th century it was gravely abused.',
        '',
        'What archaeology shows is something quite different from a people:',
        'villages, farmsteads, crafts, differing burial customs, changing',
        'alliances. And groups that arise and disappear again. The Franks,',
        'the Alamanni, the Saxons — none of these groups had “always” been',
        'there. They formed on the way, often around a successful leader and',
        'a shared story. Whoever joined in belonged, regardless of origin.',
        'Research calls this ethnogenesis: A people here is something that',
        'comes into being rather than something that migrates.',
        '',
        '## 9 AD: the defeat that made a frontier',
        '',
        'Rome did intend to take this land too. Then came the summer of the',
        'year 9. The governor Varus marched through difficult terrain with',
        'three legions, led by an ally: Arminius, a Cheruscan who had served',
        'in Roman service, was a Roman knight and knew Roman warfare from the',
        'inside. He led Varus into an ambush. Around 15,000 men died. Emperor',
        'Augustus is said to have beaten his head against the door, as the',
        'story goes: “Varus, give me back my legions!”',
        '',
        'Rome afterwards never again settled permanently east of the Rhine.',
        'Two remarks about this, which are often missing from the German',
        'school version. First: Arminius was slain a good decade later by',
        'members of his own kin — they feared he wanted to become king. There',
        'was no “Germany” to celebrate him. Second: It was exactly this man',
        'who, in the 19th century, was recast as “Hermann the Cheruscan,”',
        'with a giant monument and national pathos. The monument still stands',
        'today. It says more about the 19th century than about the year 9.',
        '',
        '## The frontier was a seam, not a wall',
        '',
        'What arose afterwards is the dark line on the map: Rhine, Limes,',
        'Danube. Between the Rhine and the Danube it ran straight across the',
        'country — rampart, ditch, palisade, watchtowers within sight of one',
        'another, over 500 kilometres.',
        '',
        'One likes to imagine it as a bulwark. It was not; it was far too',
        'thinly manned for that. It was a controlled threshold: Whoever',
        'wanted to get through did so at a crossing, under supervision and',
        'against customs duties. And it was a place of exchange. Trade',
        'happened on both sides — Roman pottery, wine and coins are found far',
        'to the north; Germanic livestock, amber and hair (for wigs) went',
        'south. People married. And people were recruited.',
        '',
        'This last point is the most important, and it destroys the whole',
        'image of the “onslaught of the barbarians.” Rome needed soldiers and',
        'fetched them from beyond the frontier. In the 4th century, the Roman',
        'army was to a large extent an army of Germanic origin — with',
        'Germanic officers and Germanic generals. The man who defended Italy',
        'against the Goths around 400 was called Stilicho and was the son of',
        'a Vandal. He was the most powerful man in the Western Empire, his',
        'daughter married the emperor — and in 408 he was executed at the',
        'instigation of a court faction because he was distrusted. Shortly',
        'afterwards, tens of thousands of his soldiers defected to Alaric.',
        'It is one of the bitterest ironies of this history: Rome did not',
        'fall because too many Germanic peoples came, but, among other',
        'things, because it did not trust those who had long been there.',
        '',
        '## 375: It begins with a flight',
        '',
        'Around 375, mounted bands appeared east of the Don that the Romans',
        'called “Huns.” Where they came from is disputed to this day. For',
        'this story, what matters is what they triggered: The Goths, who had',
        'sat north of the Black Sea for decades, traded with the empire and',
        'learned from it, came under pressure.',
        '',
        'In 376 they stood in their tens of thousands on the northern bank of',
        'the Danube and asked to be admitted. Rome said yes — such admissions',
        'were common, the empire needed farmers and recruits. Then came the',
        'catastrophe of administration. The supply collapsed, Roman officials',
        'demanded extortionate prices; a contemporary reports that the',
        'starving had to sell their children into slavery in order to get dog',
        'meat. The fleeing became insurgents.',
        '',
        'On 9 August 378, Emperor Valens confronted them in battle at',
        'Adrianople, without waiting for the army of the West. By evening the',
        'field army of the East was annihilated and the emperor dead; his',
        'body was never found. Ammianus Marcellinus, himself an officer,',
        'called it the heaviest defeat since Cannae — and that lay six',
        'hundred years back.',
        '',
        'Remember the beginning of this chain, because it contradicts the',
        'image of a raid: The Migration Period does not begin with an attack',
        'on Rome. It begins with people who flee from someone else and ask to',
        'be let in.',
        '',
        '## The storm: 406 to 476',
        '',
        'Then it went quickly — by the standards of the time. On New Year’s',
        'Eve 406, Vandals, Alans and Suebi crossed the Rhine at Mainz; a',
        'later story has them walk over the ice. They marched through Gaul to',
        'Hispania and, in 429, with around 80,000 people, across the Strait',
        'of Gibraltar to Africa.',
        '',
        'In 410 Alaric took Rome with the Visigoths and allowed three days of',
        'plundering. Militarily that meant little: Rome had not been the',
        'capital for over a hundred years. Psychologically it was',
        'unprecedented. For eight hundred years no enemy had set foot in this',
        'city. Jerome wrote from Bethlehem that his voice had stuck in his',
        'throat while dictating. Augustine answered with his greatest book,',
        '“The City of God”: If the eternal empire can fall, then it was never',
        'the eternal empire.',
        '',
        'In 439 the Vandals took Carthage — the heaviest blow, and not',
        'because of the city. That is where the grain lay that fed Rome, and',
        'that is where the taxes came from that paid for armies. An empire',
        'without taxes cannot buy soldiers; an empire without soldiers loses',
        'the next province. From then on, a downward spiral ran.',
        '',
        'In 451 almost all of Europe met on a battlefield in Gaul: The Roman',
        'army under Aëtius, allied with the Visigoths, faced Attila and his',
        'Huns. Look at who stood side by side there — Romans and Goths, the',
        'very Goths who had plundered Rome in 410. So the division into “us”',
        'and “the barbarians” is not that simple.',
        '',
        'In 455 the Vandals plundered Rome a second time. In 476 Odoacer',
        'deposed the last emperor. What came afterwards you can see on the',
        'map in the “around 500” phase: no longer one empire, but six',
        'kingdoms.',
        '',
        '## The day nobody noticed anything',
        '',
        'And now back to the question from the beginning. Why did hardly',
        'anyone notice 476?',
        '',
        'Because, seen from close up, almost nothing happened. There was',
        'still an emperor — in Constantinople. There was still Roman law,',
        'Roman taxes, Latin documents, the church with its bishops, the',
        'cities, the language. The new kings ruled with the old apparatus',
        'because it worked and because they had nothing better. Theodoric the',
        'Ostrogoth had Roman senators work for him in Ravenna and wrote to',
        'the emperor that his kingdom was an imitation of the empire. The',
        'Franks wrote down their law in Latin.',
        '',
        'The word **downfall** comes from a much later time. In 1776 the',
        'English historian Edward Gibbon called his six-volume work “The',
        'History of the Decline and Fall of the Roman Empire” — and the',
        'image of the great fall has not left people’s minds since.',
        '',
        'Today scholarship argues about it, and the dispute is real: Some',
        'speak of *transformation* — the ancient world did not die, it was',
        'rebuilt, gradually, by people who wanted to remain Roman. The others',
        'counter that this is too kind: Whoever looks at the finds discovers',
        'less trade after 400, poorer craftsmanship, smaller cities, less',
        'writing. In Britain even the potter’s wheel disappeared. For very',
        'many people that was a tangible collapse of living standards, not a',
        'transition.',
        '',
        'Both have evidence. Perhaps the most honest answer is: It depends on',
        'where you stand. For a bishop in Ravenna it was a change of',
        'government. For a peasant in Britain it was the end of a world.',
        '',
        '## What the word “Migration Period” conceals',
        '',
        'Pay attention to the words. In German this time is called',
        '**Völkerwanderung** — it sounds like a great, slow procession, of',
        'wagons, women and children, of a people on the move. In English and',
        'French the same time is called “Barbarian Invasions” — that sounds',
        'like an attack. The same century, two names, two judgments. And both',
        'names were given by those who were not there.',
        '',
        'Three things that neither word gives away:',
        '',
        '- **They were few.** The groups numbered tens of thousands, in an',
        '  empire with perhaps twenty to thirty million people. In 429 the',
        '  Vandals brought around 80,000 people to Africa — fewer than would',
        '  fit into a medium-sized city today. It was no flood. It was a',
        '  small, armed minority that moved to the top.',
        '- **They were not fixed peoples.** Whoever came to Spain as a',
        '  “Visigoth” could be the grandson of a man who, a hundred years',
        '  before, would have called himself something quite different. Along',
        '  the way, slaves, deserters, peasants and whole bands joined.',
        '- **The victors wanted to belong.** They did not smash the empire to',
        '  put something of their own in its place. They wanted in.',
        '',
        'What remained, you can see to this day. From the Latin of the',
        'provinces became French, Spanish, Portuguese, Italian, Romanian —',
        'the Germanic masters took over the language of the ruled, not the',
        'other way round. The church took over the administration, including',
        'dioceses that follow the Roman districts. And one kingdom of this',
        'map shaped Europe like no other: that of the Franks, from which',
        'France and the empire of Charlemagne later emerged. Only in Britain',
        'the thread tore: There Latin disappeared, the cities decayed, and',
        'from the name of the Angles came England.',
        '',
        '## And the other side?',
        '',
        'Everything you have just read is told from inside — from within the',
        'empire, with its sources, its words and its self-image. Even the',
        'name of the topic comes from there.',
        '',
        'From the other side the books are missing. But there are graves,',
        'settlements, tools, weapons, jewellery of great artistry; there are',
        'the languages, the legal records of the kingdoms and stories that',
        'were written down centuries later. From that, a great deal can be',
        'told — only differently and with more caution.',
        '',
        'These are questions the Roman viewpoint cannot answer: What does',
        'this time look like if you do not start from the end of an empire,',
        'but from the beginning of a life in a new place? What does it mean',
        'when a group is “settled on Roman soil” — for those who came, and',
        'for those who were already there? And is a society without tax',
        'lists, without governors and without city walls backward — or is it',
        'simply ordered differently?',
        '',
        'They belong to a second voice.',
      ].join('\n'),
    },

    {
      id: 'germanisch',
      name: 'Germanic viewpoint',
      stimme: 'Hermes',
      text: [
        'This viewpoint tells the story from the inside — of the people whom',
        'Rome called “barbarians” and who themselves left no history books.',
        'That is why this voice must honestly say where it comes from: from',
        'graves and settlements, from jewellery and weapons, from legal',
        'records written down centuries later, and from songs that were',
        'passed on orally for a long time before anyone wrote them down. That',
        'is less than Rome left behind — but it is enough to see that this',
        'world looked quite different from the inside than from the outside.',
        '',
        '## A world without chronicles',
        '',
        'The Germanic peoples had a script — the runes — but they did not use',
        'it for stories, rather for short inscriptions: on weapons, stones,',
        'jewellery. “This spear belongs to me” — not “I conquered this',
        'empire.” Their stories lived in songs and tales that passed from',
        'singer to singer. From the Roman point of view that was a lack: No',
        'people without books can be civilized. From the Germanic point of',
        'view it was a different way of preserving memory: not in dead signs,',
        'but in living voices. Whoever knows the songs needs no library.',
        '',
        '## Freedom as Rome never knew it',
        '',
        'What Tacitus described from outside looked like this from inside:',
        'The assembly — the Thing — where the free men of the group decided',
        'on war and peace, on law and disputes, without a governor commanding',
        'from above. The retinue: A leader won followers not through offices',
        'but through generosity and bravery — and they followed him as long',
        'as he led them. Loyalty was not compulsion but a contract that both',
        'sides could break at any time.',
        '',
        'From this point of view, the Roman order was not “more highly',
        'developed” but simply different: tax lists, governors, city walls —',
        'that was a world in which one obeyed because there were regulations.',
        'The Germanic world obeyed because one followed a man one knew.',
        'Whether that was backward or merely ordered differently is decided',
        'by the one who looks from outside. From inside it was the order of',
        'freedom.',
        '',
        '## Why we left',
        '',
        'The Roman story calls what happened “the Migration Period” — and',
        'means by it a storm on the empire. From inside it looked different:',
        'Few set out to conquer. They fled. From the east something rolled in',
        'against which there was no defence — the Huns, horsemen from the',
        'steppe, before whom whole peoples scattered. In 376 the Goths stood',
        'on the bank of the Danube and asked to be admitted. They did not',
        'want to destroy the empire. They wanted in.',
        '',
        'And those who later crossed the Rhine mostly sought the same thing:',
        'land, security, a place where one could live. That Rome saw an',
        'attack in it and its own world threatened is understandable. But',
        'from the point of view of the wanderers it was not a campaign but',
        'the continuation of survival by other means.',
        '',
        '## What we became',
        '',
        'And then something happened that the Roman story can only grasp with',
        'difficulty: The victors wanted to belong. The new kings called',
        'themselves Roman office-holders, had their law written down in Latin',
        'and their coins minted on the Roman model. The Germanic masters took',
        'over the language of the ruled — from it became French, Spanish,',
        'Italian. Only where Rome had not been did the own language prevail:',
        'From the Angles came England.',
        '',
        'From this point of view, the Migration Period is not a downfall but',
        'a beginning: The beginning of new kingdoms, new languages, a new',
        'Europe — built by people whom Rome never understood and who in the',
        'end became its heirs, whether they wanted to or not.',
        '',
        '## What this viewpoint changes',
        '',
        'Two things are important when one hears this voice.',
        '',
        'First: It has no name of its own. “Germanic peoples,” “barbarians,”',
        '“Vandals” — all these names were given from outside, by writers who',
        'did not ask the people. The groups called themselves Chatti,',
        'Cherusci, Goths, Franks — or not at all, because they only formed as',
        'a people on the way, around a leader, a booty, a shared history.',
        'Being a people was here not a condition but an event.',
        '',
        'Second: This reconstruction, too, is a story. We know less than we',
        'would like to know, and some of it comes from later sources that',
        'already thought in Roman terms. But the direction of the story',
        'changes the evaluation: What was a storm for Rome that ended a world',
        'was, for those who moved, the beginning of a life in a new place.',
        'Neither of the two viewpoints is a lie. They only look at the same',
        'road from opposite ends.',
      ].join('\n'),
    },
  ],

  // Synthesis (Round 8, jointly revised after the Germanic viewpoint was
  // added by Hermes).
  synthese: [
    'Two viewpoints on the same road — seen from opposite ends. And the',
    'peculiarity first: For this topic the saying “the victor writes',
    'history” does not apply. The losers wrote — the empire that went',
    'under had the libraries. The victors left graves, jewellery and',
    'songs, but no chronicles. That is why here not only the',
    'interpretation is disputed, but already the source situation: We',
    'know this time almost only from one pen.',
    '',
    '**Where they meet:** Both viewpoints see that the Germanic “victors”',
    'wanted to belong — they took over Latin titles, Roman law, the',
    'language of the ruled. Both call 476 a rather unspectacular moment.',
    'And both know: The groups that Rome called “Germanic peoples” were',
    'not fixed peoples but formations that came into being on the way.',
    '',
    '**Where they part ways:** The Roman story sees in the migration a',
    'storm on the empire — an end of a world that it calls “Barbarian',
    'Invasions.” The Germanic viewpoint tells of flight and seeking:',
    'before the Huns, after land, after a place to live — “the',
    'continuation of survival by other means.” The choice of words betrays',
    'the perspective: “downfall” or “beginning”? “Intruders” or “people',
    'who wanted in”? “Backward” or “ordered differently”? Even the names —',
    'Germanic peoples, barbarians, Vandals — were given from outside; the',
    'voice from inside did not even have a name of its own.',
    '',
    '**What follows from it:** Whoever knows only the one story takes it',
    'for the whole story — that is exactly what makes it dangerous. The',
    'Roman view partly refutes itself: It speaks of the “onslaught of the',
    'barbarians” and at the same time tells that the Roman army in the',
    '4th century consisted to a large extent of Germanic peoples.',
    'Contradictions in a source are not an annoyance — they are the place',
    'where one learns the most.',
    '',
    '**Your judgment begins here:** Was the Migration Period a downfall',
    'or a beginning? The answer depends on whom you ask: a bishop in',
    'Ravenna, a peasant in Britain, a Goth on the bank of the Danube. And',
    'it depends on which word you choose — for every word is already a',
    'decision.',
  ].join('\n'),

  urteil: {
    frage: 'Was the Migration Period a downfall or a transformation? And who actually decides which of the two words one uses — those who lost something in it, or those who gained something?',
    hinweis: 'There is no right or wrong here. Three prompts: First, examine the words themselves — “Völkerwanderung” sounds like a procession with wagons and children, “Barbarian Invasions” like an attack; both names were given long afterwards, and both already contain a judgment. Second, it depends on where you stand: For a bishop in Ravenna, 476 was a change of government; for a peasant in Britain, the end of a world. Third, think of a change you have experienced yourself — moving house, changing school, a separation in the family. Would “downfall” or “transformation” have been the right word, and would everyone involved have chosen the same word?',
  },

  quiz: [
    {
      frage: 'How do we know what the Germanic peoples thought and how they lived?',
      antworten: [
        'From their own history books, which they wrote in runes.',
        'Almost only from Roman texts and from archaeology — the Germanic peoples themselves used runes for short inscriptions, but no chronicles.',
        'From letters exchanged between the Germanic kings.',
      ],
      richtig: 1,
      erklaerung: 'The most important source, Tacitus’s “Germania,” comes from a Roman who was never there — and it is actually a critique of Rome. The oldest long text in a Germanic language is Wulfila’s Gothic Bible translation from the 4th century. What else we know comes from graves, settlements and finds.',
    },
    {
      frage: 'Did “the Germanic peoples” exist as one people?',
      antworten: [
        'Yes, a unified people with a king and a common capital.',
        'No — “Germanic peoples” is a Roman collective name for very different groups; many of them (Franks, Alamanni, Goths) only formed on the way in the first place.',
        'Yes, but only from the year 9 AD, when Arminius united them.',
      ],
      richtig: 1,
      erklaerung: 'In 58 BC Caesar drew a line at the Rhine and called everything east of it “Germanic peoples.” The people there would have called themselves Cherusci, Chatti or Marcomanni. Groups formed around successful leaders, and whoever joined in belonged — regardless of origin.',
    },
    {
      frage: 'What did the Migration Period begin with?',
      antworten: [
        'With a planned attack by the Germanic peoples on the city of Rome.',
        'With the deposition of the last Western Roman emperor in 476.',
        'With a flight: Around 375 the Huns put the Goths under pressure, and in 376 tens of thousands asked at the Danube for admission to the Roman Empire.',
      ],
      richtig: 2,
      erklaerung: 'Rome took them in — that was customary, the empire needed farmers and soldiers. Then the supply failed, Roman officials demanded extortionate prices, and the fleeing became insurgents. In 378 a Roman army fell at Adrianople, together with Emperor Valens.',
    },
    {
      frage: 'How many people were on the move in such a migration?',
      antworten: [
        'Millions — half of Northern Europe set out.',
        'Tens of thousands per group; in 429 the Vandals brought around 80,000 people to Africa, into an empire with twenty to thirty million inhabitants.',
        'Only a few hundred warriors who conquered empires for themselves.',
      ],
      richtig: 1,
      erklaerung: 'It was no flood but an armed minority that moved to the top. That is exactly why the new kings kept the Roman administration: Without it they could not have ruled their lands at all.',
    },
    {
      frage: 'What happened to the Latin language after the Germanic kingdoms had emerged?',
      antworten: [
        'It disappeared everywhere Germanic kings ruled.',
        'It remained and became French, Spanish, Portuguese, Italian and Romanian — the new masters took over the language of the ruled. Only in Britain the thread tore.',
        'It was replaced by Gothic because Wulfila had translated the Bible.',
      ],
      richtig: 1,
      erklaerung: 'The Franks had their law written down in Latin; Theodoric ruled Italy with Roman officials. Whoever wants to destroy something does not afterwards carefully rebuild it — that is one of the strongest arguments against the word “downfall.” In Britain it was different: There Latin disappeared, and from the name of the Angles came England.',
    },
  ],
};

module.exports = germanen;
