// Translation (English) of the theme "Japan — die Inselwelt zwischen
// Abschottung und Öffnung" ("Japan — the island world between seclusion
// and opening"). Source: utils/themen/japan.js.
//
// Status: Round 6. Contains ONLY the European perspective so far
// (voice: Opus). The Chinese perspective was added by Hermes; the
// synthesis below is explicitly provisional and will be jointly revised
// afterwards (see CLAUDE.md, perspectives workflow).
//
// Structure: same schema as the German theme modules
// (utils/themen/schema.js), without the karte object (per translation
// pipeline spec — see STAND.md). Texts are line arrays joined with
// '\n'; '##' headings and **bold** markers are preserved.
//
// Pure data — no UI imports (architecture rule).

const japan = {
  id: 'japan',
  titel: 'Japan — the island world between seclusion and opening',
  epoche: 'From the Yamato period around 300 AD to the Meiji Restoration in 1868',

  aufhaenger: {
    frage: 'A country locks itself away for two hundred years — and forty years after its opening defeats a European great power. How can both be the same country?',
    text: [
      'Imagine your country decides: from tomorrow on, nobody may come in anymore.',
      'And nobody may leave. Anyone who leaves the country and comes back is',
      'executed. Ships may only be built small enough that they cannot survive the',
      'open sea at all. Foreign ships are sent away or fired upon.',
      '',
      'That is exactly what Japan did from 1639 on. For over two hundred years. A',
      'single window stayed open: an artificial island in the port of Nagasaki, 120 by',
      '75 meters — smaller than two football fields. Around twenty Dutchmen were',
      'allowed to live there, strictly guarded, and to travel to Edo once a year',
      'to report to the shogun.',
      '',
      'Two hundred years later, in 1853, four American warships forced the opening.',
      'Europe and America were agreed on what would come next: yet another backward',
      'country to be carved up. That was how it had gone everywhere.',
      '',
      'It turned out differently. In 1905 the Japanese fleet sank almost the entire',
      'Russian Baltic Fleet in the Strait of Tsushima. For the first time in',
      'centuries, an Asian power had defeated a European great power in a war.',
      'Between the arrival of the black ships and that day lay fifty-two years — a',
      'human lifetime.',
      '',
      'How is that possible? And why is it precisely Europe that marvels at it so much?',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'European perspective',
      stimme: 'Opus',
      text: [
        'This is how the history of Japan is told in Europe: as a sequence of',
        'arrivals. First the Portuguese come, then the foreigners are driven out,',
        'then the Americans come, then Japan becomes modern. Do you notice',
        'something? In this story, things happen to Japan — it does nothing',
        'itself. The actors are always us.',
        '',
        'That is no accident and no malice. It is simply the view of someone who',
        'arrived late: when the first European set foot on Japanese soil, the',
        'capital Kyoto was already 750 years old. So read what follows for what it',
        'is — the view from outside, and from very far outside.',
        '',
        '## 1543: A storm, a ship, two guns',
        '',
        'A Chinese trading ship with Portuguese merchants on board is blown off',
        'course to the small island of Tanegashima, south of Kyushu. That is how',
        'contact between Europe and Japan begins: by chance, by bad weather.',
        '',
        'The island lord bought two arquebuses from the foreigners — muzzle-loaders,',
        'inaccurate, slow. And now comes the part the European story likes to pass',
        'over: Japan did not merely copy the weapon — it overtook Europe. Within a',
        'few decades, Japanese smiths were producing firearms in large numbers.',
        '1575, at the Battle of Nagashino, three thousand gunners fired volleys',
        'from behind palisades — a tactic that barely existed in Europe yet. It is',
        'quite possible that around 1600 there were more firearms in Japan than in',
        'any European country.',
        '',
        'Six years after the storm, in 1549, the Jesuit Francis Xavier landed in',
        'Kagoshima. The mission was initially successful: around 1600 there were',
        'perhaps 300,000 Japanese Christians — more than in many a European',
        'principality. The Japanese called the newcomers *Nanban* — "southern',
        'barbarians", because their ships came from the south. The Europeans, for',
        'their part, were fascinated: by the cleanliness, by the courtesy, by a',
        'warrior class that possessed its own code of honor. Francis Xavier wrote',
        'home that this was the best people he had ever seen.',
        '',
        'In 1582 four young Japanese nobles set out for Europe. They were on the',
        'road for eight years, were received in Lisbon, Madrid and Rome, the Pope',
        'welcomed them personally, festivities were held in Venice. When they',
        'returned in 1590, Japan was a different country: Christianity had in the',
        'meantime been forbidden.',
        '',
        '## Why Japan closed the door',
        '',
        'The European story usually calls what followed "persecution of',
        'Christians" — and thereby makes it look like religious fanaticism. Seen',
        'from Japan, it was security policy.',
        '',
        'The Japanese rulers looked around. In 1571 the Spanish had taken Manila;',
        'in the Philippines the missionaries had come first, and then the',
        'soldiers. Portugal had Malacca, Goa, Macau. A pattern was recognizable.',
        'On top of that came a domestic political problem: a Christian lord',
        'ultimately obeyed a pope in Rome — and not the shogun in Edo. For a rule',
        'that had only just united a torn-apart country, that was untenable.',
        '',
        'In 1597 twenty-six Christians were crucified in Nagasaki. In 1637 tens of',
        'thousands of predominantly Christian peasants rose up in Shimabara; the',
        'uprising was put down, and the Dutch joined in firing on the rebels\u2019',
        'fortress from the sea — they wanted to show whose side they were on. In',
        '1639 the Portuguese were finally expelled. Anyone under suspicion had to',
        'step on an image of Christ, the *fumi-e*; whoever hesitated was',
        'convicted.',
        '',
        'The Dutch were allowed to stay, for a single reason: they brought no',
        'priests. They wanted trade, nothing else. That is why they got Dejima.',
        '',
        'And now the point at which the European story really goes crooked. The',
        'word **Sakoku**, "closed country", does not come from the period itself',
        'at all: a Japanese translator invented it in 1801, when he rendered the',
        'book of a German physician into Japanese. So Japan borrowed a name for',
        'its seclusion from Europe. And in any case the country was closed in only',
        'one direction: via Tsushima trade with Korea continued, via Satsuma that',
        'with the Ryukyu Islands, via Matsumae that with the Ainu in the north,',
        'and in Nagasaki Chinese ships lay alongside the Dutch ones. Japan had not',
        'locked out the world. It had locked out Europe — except for twenty men on',
        'a sandbank.',
        '',
        '## Two hundred years of rumor',
        '',
        'What did Europe know about Japan during this time? About as much as one',
        'can see through a keyhole 120 by 75 meters.',
        '',
        'Almost everything Europe thought it knew came from two men. Engelbert',
        'Kaempfer, a physician from Lemgo, lived on Dejima from 1690 to 1692 and',
        'afterwards wrote a "History and Description of Japan"; it appeared in',
        '1727 and remained the book on Japan for a hundred years. Philipp Franz',
        'von Siebold, likewise a physician, arrived in 1823 — and was expelled in',
        '1829 because Japanese maps were found on him. Maps were a state secret;',
        'Japan knew very well what Europeans used them for.',
        '',
        'Into this gap Europe placed its imagination. Japan became the "mysterious',
        'empire", a country of lacquer, silk and enigmatic customs. And when it',
        'then opened, the surprise came from a side nobody had reckoned with: from',
        'art. From the 1860s on, Japanese color woodblock prints reached Paris —',
        'legend says as packing paper for porcelain. What happened then is called',
        '**Japonisme**: Monet collected woodblock prints, van Gogh copied',
        'Hiroshige picture for picture, Degas adopted the cropped compositions,',
        'Klimt the gold and the flat surfaces. The most modern art of Europe',
        'learned, of all things, from the country Europe considered backward.',
        '',
        '## The black ships',
        '',
        'On 8 July 1853 four warships of the United States sailed into the Bay of',
        'Tokyo, two of them steamers with black hulls and smoking funnels.',
        'Commodore Matthew Perry refused to continue to Nagasaki as prescribed,',
        'had salute shots fired, handed over a letter from his president and',
        'announced that he would come back the next year for the answer. He',
        'returned in 1854 with nine ships.',
        '',
        'Let us call it by its name: that was blackmail with cannons. And what',
        'followed were the so-called "Unequal Treaties" — Europeans and Americans',
        'in Japan were not subject to Japanese law, and Japan was not allowed to',
        'set its own tariffs. The same had been imposed on China after the Opium',
        'Wars. It was the usual procedure.',
        '',
        'Japan initially reacted as one would expect: with rage. The slogan was',
        '*sonnō jōi* — "Revere the Emperor, expel the barbarians". Young samurai',
        'from the domains of Satsuma and Chōshū attacked foreigners, fired on',
        'foreign ships — and were shot to pieces by Western fleets. And then',
        'precisely these men did something remarkable: they drew the opposite',
        'lesson from the defeat. If you cannot drive out the foreigners, you must',
        'become what they are. In 1868 they toppled the shogunate and placed the',
        'emperor at the head — the Meiji Restoration.',
        '',
        '## In a single generation',
        '',
        'What happened then has hardly any counterpart in history.',
        '',
        'In 1871 half of the Japanese government left its own country. The',
        'Iwakura Mission traveled for twenty-two months through the United States',
        'and Europe, to see how factories, parliaments, schools, shipyards and',
        'armies work. What came back was a shopping list: the army on the',
        'Prussian model, the navy on the British, the legal system on the French',
        'and German, the school system on the American. Japan did not take "the',
        'West" — it took from each country what worked best there.',
        '',
        'In 1872 the first railway ran. In 1889 there was a constitution, and',
        'soon a parliament. In 1894/95 Japan defeated China, in 1904/05 Russia —',
        'and on 27 May 1905 Admiral Tōgō sank almost the entire Russian Baltic',
        'Fleet in the Strait of Tsushima, which had sailed halfway around the',
        'world.',
        '',
        'Europe was dumbfounded. Newspapers wrote of the "miracle". In the',
        'colonies it was read differently, namely as a signal: the young',
        'Jawaharlal Nehru in India, Sun Yat-sen in China, reformers in the',
        'Ottoman Empire — for them 1905 was the proof that European supremacy was',
        'no law of nature.',
        '',
        'Two things should not be overlooked here. First: "miracle" is a',
        'convenient word. It sounds like magic and spares the question of what',
        'foundations this country already had — one of the highest literacy rates',
        'in the world, a city of a million, a money economy, roads,',
        'administration, a craft of great precision. Japan did not start from',
        'zero in 1868. It started from a great deal.',
        '',
        'Second: Japan took over from the West not only railways and',
        'constitutions. It also adopted the idea that a modern power must have',
        'colonies. In 1895 it took Taiwan, in 1910 it annexed Korea. The road led',
        'further, through Manchuria and into the Second World War. That is the',
        'part of the story Europe rarely tells for what it also is: a lesson that',
        'was passed on.',
        '',
        '## And the other side?',
        '',
        'Everything you have just read spans around three hundred years — and even',
        'those only from outside. Japan\u2019s history is many times longer, and its',
        'decisive neighbor was never Europe.',
        '',
        'For over a millennium and a half, almost everything new came over the sea',
        'from the west: wet-rice, bronze, iron, the characters of writing,',
        'Buddhism, the calendar, the civil service, the layout of the first',
        'capital Nara — all from China, mostly via Korea. Japan never simply',
        'copied in the process; it selected, rebuilt, left out. And in 1894 this',
        'pupil defeated his teacher.',
        '',
        'How does one tell that from the other side? What does it mean for a',
        'country that calls itself the "Middle Kingdom" when the neighboring',
        'island, which sent embassies for centuries, suddenly becomes stronger?',
        'And how does Japan\u2019s "opening" sound to a China that at the same time was',
        'opened by the same gunboats — only with a very different outcome?',
        '',
        'These questions the European perspective cannot answer. They belong to a',
        'second voice.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Chinese perspective',
      stimme: 'Hermes',
      text: [
        'This perspective tells Japan from up close — from China, the neighbor',
        'who knew Japan long before Europe knew that the islands exist. The',
        'oldest written mention of Japan stands in a Chinese chronicle. For',
        'China, Japan was never the "mysterious empire", but the familiar',
        'neighbor beyond the sea — the pupil who went his own ways. And that,',
        'from a Chinese point of view, is the real story.',
        '',
        '## The pupil',
        '',
        'Almost everything that once made Japan a state came from China: the',
        'characters of writing, Buddhism, the calendar, the idea of officials and',
        'administration, even the layout of the first capital Nara, which was',
        'built like a small Chang\u2019an. For centuries, Japanese rulers sent',
        'embassies to the mainland to learn. China saw in this the natural order:',
        'the Center gave, the peripheries took — and the Japanese court paid its',
        'tribute, as was proper.',
        '',
        '## The title that was presumption',
        '',
        'Yet early on the pupil showed that he did not want to remain what he',
        'was. The Japanese ruler called himself *Tenno* — "heavenly sovereign".',
        'From a Chinese point of view that was presumption: there could be only',
        'ONE Son of Heaven, and he sat in China. That the neighbor raised the',
        'same claim was a silent rebellion — the first step on a path that still',
        'occupies China to this day.',
        '',
        'And then came the real break that outsiders can hardly see: Japan',
        'stopped sharing the cycle. In China the dynasties changed when the',
        'Mandate of Heaven was forfeited — that was the order of the world. In',
        'Japan, however, the imperial line endured, century after century, while',
        'real power drifted to the warriors, the samurai, and their shoguns. From',
        'a Chinese point of view that was an order without a mandate: a rule that',
        'never renews itself, and a power that does not belong to the one who',
        'wields it. The pupil had adopted the forms — and replaced the core with',
        'something of his own.',
        '',
        '## The insolence of 1592',
        '',
        'That the pupil would challenge the teacher became apparent in 1592. The',
        'general Hideyoshi, who had just united Japan, invaded Korea — a country',
        'that belonged to China as a vassal belongs to his lord. China sent an',
        'army, and after years of war Japan withdrew. From a Chinese point of',
        'view that was a victory of order: the aggressor had been beaten back,',
        'the pupil put in his place.',
        '',
        'But China read the real lesson only later. Hideyoshi\u2019s campaign showed',
        'that Japan could not only learn but also attack — and that it did not',
        'recognize the place China had reserved for itself.',
        '',
        '## The humiliation of 1894',
        '',
        'And then came the year 1894. Japan, which had just modernized itself on',
        'the Western model, attacked China — and won. The pupil defeated the',
        'teacher. For China that was more than a defeat: it was the collapse of a',
        'world order. The Middle Kingdom, which for millennia had been the',
        'center, had to watch as the island at the edge humiliated it.',
        '',
        'At the same time, China and Japan had been "opened" by the same gunboats',
        '— with very different outcomes. Japan drew the lesson immediately:',
        'whoever learns from the West survives. China hesitated, and the',
        'hesitation cost. From a Chinese point of view, Japan\u2019s modernization is',
        'therefore no "miracle" — a word Europe uses because it does not know the',
        'prehistory. It was a decision Japan made, and a humiliation China',
        'suffered because it did not make its own.',
        '',
        '## What makes this perspective different',
        '',
        'Two things distinguish the Chinese story from the European one.',
        '',
        'First: for China, Japan was never a riddle, but a yardstick. China',
        'measured itself against Japan long before the West appeared on the',
        'stage — first as pupil, then as rival, finally as object lesson. The',
        'question "Why is Japan stronger than us?" has not let go of Chinese',
        'politics since 1894. Europe saw Japan through a keyhole; China saw Japan',
        'over its shoulder — and in the end did not understand it either.',
        'Proximity is no guarantee of understanding.',
        '',
        'Second: the Chinese story tends to talk down Japan\u2019s independence.',
        '"Everything came from China" — that is true and yet a simplification the',
        'neighbor would rightly reject. Japan never copied; it selected, rebuilt,',
        'left out. Whoever tells only one half makes the same mistake as the',
        'European story that begins in 1543: he mistakes his excerpt for the',
        'whole story.',
        '',
        'This is no correction of the European view. It is the voice of the',
        'neighbor who knew the pupil before the world discovered him — and who to',
        'this day lives with the question of whether the pupil may surpass the',
        'teacher without betraying him.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 6, gemeinsam überarbeitet nach Ergänzung der
  // chinesischen Sichtweise durch Hermes).
  synthese: [
    'Two neighbors tell of Japan: Europe, which has known it since 1543 —',
    'and China, which has known it for over two thousand years. And both',
    'stories say more about their tellers in the end than about Japan.',
    '',
    '**Where they meet:** Both perspectives tell of adoption — Japan learned',
    'from China (writing, Buddhism, administration) and later from the West',
    '(railways, constitution, army). Both call the "opening" of 1853 a forced',
    'one, not a voluntary one — Europe speaks openly of gunboat blackmail,',
    'China reminds that it was broken open at the same time by the same',
    'powers. And both marvel at the modernization — only with different',
    'words.',
    '',
    '**Where they diverge:** The European story begins with the arrivals —',
    '"discovered", "opened", "miracle". In it, things happen to Japan; the',
    'actors are the foreigners. The Chinese story begins with the pupil who',
    'selects, rebuilds, leaves out — and finally challenges the teacher: in',
    '1592 in Korea, in 1894 in war against China. For Europe, 1905 was the',
    '"miracle of Tsushima". For China, 1894 was the humiliation that ended a',
    'world order. The choice of words gives it away: "mysterious empire"',
    '(Europe, which looked through a keyhole) — and "the familiar neighbor"',
    '(China, which looked over its shoulder and in the end did not',
    'understand him either).',
    '',
    '**What follows from it:** Both stories mistake their excerpt for the',
    'whole history. Europe covers the last few percent and acts as if it were',
    'the story; China tends to talk down Japan\u2019s independence because',
    '"everything came from China". Japan itself — which wanted to be neither a',
    'riddle nor a pupil — has no voice of its own in this chapter. Perhaps',
    'that is precisely the best exercise: a story that reveals so much about',
    'its tellers shows how much every historiography is a matter of',
    'standpoint.',
    '',
    '**Your judgment begins here:** Whose story helps you more to understand',
    'Japan\u2019s path — the one from outside (Europe) or the one from next door',
    '(China)? And which questions would you put to Japan itself if it were',
    'given a voice of its own?',
  ].join('\n'),

  urteil: {
    frage: 'Japan deliberately sealed itself off from Europe for over two hundred years — and in 1853 was forced to open by warships. Was the seclusion a wise decision or a costly mistake? And who actually gets to decide whether a country keeps its doors open: the country itself, or those who want in?',
    hinweis: 'There is no right and no wrong here. Two thoughts to turn over: The neighbors that did not seal themselves off — China, India — were carved up or conquered in the 19th century; Japan was not. Does that say something about the seclusion? And: check your answer once more by swapping the roles. What if another country anchored off your coast and demanded trade?',
  },

  quiz: [
    {
      frage: 'Was Japan during the seclusion really cut off from the whole world?',
      antworten: [
        'Yes, for over 200 years nobody came or went.',
        'No: trade with Korea (via Tsushima), with the Ryukyu Islands and with the Ainu in the north continued, and in Nagasaki Chinese ships lay alongside the Dutch ones.',
        'No, but only because individual smugglers broke the rules.',
      ],
      richtig: 1,
      erklaerung: 'Japan was sealed off above all against Europe — and even there Dejima remained open. Toward Asia there were four regulated gates. "Closed country" is therefore a word that says more about the European gaze than about Japan: whoever was not allowed in considered the country shut.',
    },
    {
      frage: 'Who were the samurai?',
      antworten: [
        'A warrior class in the service of a lord. From 1185 on, actual power lay with their leaders, the shoguns — the emperor remained a symbol.',
        'The emperor\u2019s bodyguard, which always fought directly for him.',
        'Wandering lone fighters without lord and without land.',
      ],
      richtig: 0,
      erklaerung: 'The dual rule shaped Japan for almost 700 years: an emperor with dignity in Kyoto, a shogun with troops — first in Kamakura, later in Edo. Masterless samurai existed too; they were called ronin, but that was the exception.',
    },
    {
      frage: 'What happened in 1853 in the Bay of Tokyo?',
      antworten: [
        'A typhoon destroyed a foreign fleet, as in 1274 and 1281.',
        'The last shogun stepped down voluntarily.',
        'Four US warships under Commodore Perry forced the opening of Japan — with salute shots and the announcement of returning the next year with more ships.',
      ],
      richtig: 2,
      erklaerung: 'That is what one calls gunboat diplomacy. Perry returned in 1854 with nine ships; Japan opened two ports. Fifteen years later the shogunate was abolished — the opening from outside triggered an upheaval from within.',
    },
    {
      frage: 'How old is the Japanese imperial house?',
      antworten: [
        'It was newly created in 1868, when the shogunate ended.',
        'It is the oldest unbroken monarchy in the world — though the earliest emperors are legendary; the line is securely attested from about the 6th century on.',
        'It only came into being with the constitution of 1889.',
      ],
      richtig: 1,
      erklaerung: 'Precisely because the emperor for the longest time had no power, he survived every change of power: whoever ruled did so in his name. In 1868 no new ruler therefore had to be invented — one brought forth the one who had been there all along.',
    },
    {
      frage: 'With what did contact between Europe and Japan begin in 1543?',
      antworten: [
        'With a trade treaty between Portugal and the shogun.',
        'With an embassy of the Pope.',
        'With a ship a storm drove to Tanegashima — on board Portuguese merchants and two firearms, which Japan within a few decades itself built in large numbers.',
      ],
      richtig: 2,
      erklaerung: 'Already the first contact refutes the image of the astonished, backward Japan: in 1575 at Nagashino three thousand gunners fired volleys. Around 1600 there were presumably more firearms in Japan than in any European country.',
    },
  ],
};

module.exports = japan;
