// Topic: The new world order and the Cold War (1945–1991).
//
// English translation of utils/themen/kalter-krieg.js. Field names follow
// the German schema (aufhaenger, perspektiven, synthese, urteil, quiz) —
// only the texts are translated. The map is omitted in this English module
// (see karten/kalter-krieg.js), as are the karteHinweise.
//
// Status: Round 20 + Hermes pass. Three voices are finished: the view of
// the West (Voice: Opus), the view of the East — Soviet Union, Warsaw
// Pact, GDR (Voice: Hermes) and the view of the Germans in East and West,
// for whom the division was everyday life (Voice: Hermes). The synthesis
// brings all three together.
//
// Eighteenth topic and eleventh chapter of the modern-history arc
// (notizen/kapitel-planung.md, Chapter 11). It begins where "The Second
// World War and the New World Order" ends: in 1945, with the victors who
// are still shaking hands.
//
// The order of the voices is not a ranking. That the West speaks first
// here results solely from who took over this round; that is also stated
// in the text, so that nobody reads the order as a judgement.
//
// TONE RULE (CLAUDE.md, additional rule for sensitive topics — this chapter
// touches people who are still alive and a conflict whose after-effects
// shape the present): This perspective names its own uncomfortable spots —
// the McCarthy era, Vietnam, the support of dictatorships against
// communism (Iran 1953, Guatemala 1954, Chile, the colonels in Greece,
// Franco, Salazar, South Africa), the arms race and the fact that in 1953,
// 1956 and 1968 nobody came to help. The motives of the other side are
// rendered fairly, explicitly including the Soviet fear of encirclement,
// which from a Western point of view was exaggerated but not invented. The
// quiz questions remain questions of knowledge: they do not ask about
// guilt.
//
// The Two Plus Four Treaty stands prominently in the text, per the
// operator's directive, together with the question of whether it was
// upheld. In that regard: **Article 6** expressly allows the united
// Germany membership in alliances, **Article 7** ends the Four-Power
// rights and grants full sovereignty. The debate about the "spirit" of
// the treaty and NATO's eastward enlargement belongs in Chapter 12
// (Russia and the West); here only the finding stands that the treaty
// itself did not forbid membership.
//
// The map lives in karten/kalter-krieg.js — three states (1949, 1961/62,
// 1989–1991). Cuba lies outside the excerpt; why, is stated in the header
// of the map file.
//
// Pure data — no UI imports (architecture rule).

const kalterKrieg = {
  id: 'kalter-krieg',
  titel: 'The New World Order and the Cold War',
  epoche: '1945–1991',

  aufhaenger: {
    frage: 'Two countries that had together defeated Hitler turned their weapons on each other within two years — and forty years later one side disappeared, without a single shot having been fired between the two blocs. How do allies become the opposite so quickly, and why does a world empire collapse that nobody defeated?',
    text: [
      'In April 1945 American and Soviet soldiers met on the Elbe at Torgau.',
      'There are photographs of it: young men embracing each other, sitting on',
      'tanks, laughing into the camera. Two years later a condition had arisen',
      'between their countries for which a new word was needed — the Cold War.',
      'Cold, because the two great powers never fought each other directly.',
      'War, because otherwise they did everything that makes up a war: rearm,',
      'threaten, spy, gather allies and let others fight each other in foreign',
      'countries.',
      '',
      'Through the middle of it ran a line, and it ran through the middle of',
      'Germany. 1,393 kilometres of fence, mines and watchtowers, plus 155',
      'kilometres of the Berlin Wall around West Berlin. A city in which you',
      'could sit in a tram and, when you got off, stand in a different world',
      'system. Nowhere else was the Cold War so literally visible.',
      '',
      'Twice the world came close to its end: in October 1962, when Soviet',
      'missiles were discovered on Cuba, and again and again in the moments in',
      'which a radar screen showed something that was not there at all. At the',
      'height, over 60,000 nuclear warheads were stockpiled worldwide — enough',
      'to destroy every major city on earth several times over.',
      '',
      'And then, in 1989, one side collapsed. Not through a defeat in the',
      'field, but through empty shelves, an economy that could no longer keep',
      'up, an oil price that crashed, a general secretary who wanted to',
      'reform — and through people who went onto the streets unarmed and did',
      'not go away again. On 25 December 1991 the Soviet Union ceased to',
      'exist.',
      '',
      'This chapter begins with the view of the West. That is one of several',
      'voices, not the right one — who speaks first depends on who wrote this',
      'round, and is not a ranking.',
    ].join('\n'),
  },

  // "History in motion" — the map comes after the hook and before the
  // perspectives (utils/lernformat.js). Omitted in this English module
  // (see karten/kalter-krieg.js).

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'The view of the West — USA, Great Britain, Western Europe and the Federal Republic',
      stimme: 'Opus',
      text: [
        'This voice tells from Washington, London, Paris and Bonn: from the',
        'government districts in which the decisions were made, but also from',
        'the living rooms in which the news ran, from West Berlin, which saw',
        'itself as an island for forty years, and from the schools in which',
        'children learned what to do in the event of an attack.',
        '',
        "It is of equal worth with the other voices of this chapter. That it",
        "stands first here is not a ranking — it is merely because of who took",
        "over this round. And it has a task that it sets itself: it must not",
        "tell the victors' narrative that was so comfortable after 1989. The",
        "West fought the Cold War with means that contradicted its own",
        "principles, and this text names them — not in passing, but in its own",
        "section.",
        '',
        '## From allies to adversaries (1945–1947)',
        '',
        'The alliance against Hitler was a marriage of convenience. Franklin',
        'D. Roosevelt, Winston Churchill and Josef Stalin were united by a',
        'common enemy and little else. At the Yalta Conference in February',
        '1945 and in Potsdam in July and August it was settled what was to',
        'happen to Germany: disarmament, denazification, four occupation',
        'zones, reparations, the westward shift of Poland. What was not',
        'settled was the decisive thing — how it should continue once the',
        'common enemy was defeated.',
        '',
        'From the Western point of view the answer was given in Eastern',
        'Europe, and quickly. In Poland, Romania, Bulgaria and Hungary,',
        'between 1945 and 1948 governments came to power after elections',
        'whose regularity nobody in the West believed in. In February 1948',
        'the Communist Party took sole power in Czechoslovakia — the only',
        'country in the region with a functioning democracy between the',
        'wars. For many in the West that was the moment when distrust became',
        'certainty.',
        '',
        'And the other side? Its motives belong here, and this voice renders',
        'them as they were, not as a caricature. The Soviet Union had lost',
        'around 27 million people in the Second World War — more than any',
        'other country. It had been invaded from the West twice within thirty',
        'years, in 1914 and 1941, and the second time the attack had been a',
        'war of annihilation. Anyone in Moscow asking about security thought',
        'of a belt of friendly states between themselves and Germany. From',
        'the Western point of view the fear of encirclement derived from',
        'that was exaggerated — it did not explain why governments against',
        'the will of the population had to be installed in Warsaw, Prague and',
        'Budapest. But it was not invented, and whoever dismisses it as a',
        'mere pretext does not understand Soviet policy of those years.',
        '',
        'Two texts gave Western policy its form. In February 1946 the',
        'American diplomat George F. Kennan sent the "long telegram" from',
        'Moscow: the Soviet Union could not be appeased by concessions, but',
        'could be contained by patient counter-pressure at its borders. From',
        'the thought came a word — **containment** — and from the word the',
        'guideline of forty years. On 5 March 1946 Winston Churchill spoke in',
        'the American town of Fulton the sentence that became the headline',
        'of the epoch: from Stettin on the Baltic to Trieste on the Adriatic,',
        'an **Iron Curtain** had descended across the continent.',
        '',
        'On 12 March 1947 President Harry S. Truman announced before',
        'Congress what has since been called the **Truman Doctrine**: the',
        'USA would support free peoples who resisted armed minorities or',
        'outside pressure. The concrete occasion was Greece, where a civil',
        'war was raging, and Turkey, on which Moscow was exerting pressure;',
        'Great Britain could no longer provide the support from its own',
        'strength. But the claim was worldwide — and in that lay both: a',
        'rejection of the isolationism of the 1930s, which had watched',
        'Europe slide into war, and the beginning of a policy that in the',
        'end would also prop up dictators, as long as they were',
        'anti-communist.',
        '',
        '## The Marshall Plan (1947/48) — aid and power politics at once',
        '',
        'On 5 June 1947 Secretary of State George C. Marshall gave a speech',
        'at Harvard in which he offered American economic aid to Europe.',
        'From it became the European Recovery Program: around 13 billion',
        "dollars between 1948 and 1952 — in today's purchasing power well",
        'over a hundred billion — plus raw materials, machinery, food and',
        'expertise. The European cities lay in ruins, the winter of 1946/47',
        'had been the coldest in living memory, in several countries people',
        'were starving. The Marshall Plan ended this state, and that is no',
        'small thing.',
        '',
        'It was also power politics, and this voice says that itself instead',
        'of letting it be held against it. First: the money created sales',
        'markets for American industry, which stood after the war as the',
        'only one undestroyed, and tied Western Europe to the dollar.',
        'Second: it was tied to conditions — the recipients had to disclose',
        'their economic data, plan jointly and open up trade. Third, and',
        'this is the most important point: the offer went expressly also to',
        'the Soviet Union and to Poland and Czechoslovakia. Moscow declined',
        'in July 1947 in Paris and forbade it to the states of its sphere of',
        'influence; the Czechoslovak government, which initially wanted to',
        "accept, had to withdraw its acceptance. From the Moscow point of",
        "view, accepting would have meant giving Washington insight into",
        "one's own books and making oneself economically dependent — that",
        'too is a comprehensible thought, not mere defiance.',
        '',
        'With that the division of Europe had become an economic one. The',
        'West got credits and a common market, the East got the Council for',
        'Mutual Economic Assistance (1949) and an order in which Moscow set',
        'the prices. This switch of 1947 explains a good part of what was to',
        'be seen forty years later on the empty shelves.',
        '',
        '## Berlin 1948/49 — the Airlift',
        '',
        'On 20 June 1948 the Western zones introduced the Deutsche Mark;',
        'three days later it also applied in the Western sectors of Berlin.',
        'For the Western side that was a necessity — the old Reichsmark was',
        'worthless, the black market ruled. For the Soviet side it was the',
        'break with the joint administration of Germany, and this reading is',
        "not far-fetched: a currency of one's own is half the way to a state",
        "of one's own. On 24 June 1948 all roads, railway lines and",
        'waterways to West Berlin were blocked. Two million people were cut',
        'off.',
        '',
        'What happened then is the most impressive story the West has to',
        'tell from this chapter. The three air corridors had been agreed in',
        'writing in 1945 — the roads were blocked, the air route was',
        'assured. For eleven months around 280,000 flights supplied the city',
        'with about 2.3 million tonnes of coal, flour, medicine and even the',
        'individual parts of a power plant. At the peak a plane landed every',
        'three minutes. Tegel Airport was built in ninety days,',
        'predominantly by women of Berlin — the "rubble women" — who cleared',
        'away the debris. Around eighty people lost their lives in crashes,',
        'Britons, Americans and Germans.',
        '',
        'The American pilot **Gail Halvorsen** began dropping sweets on',
        'self-made parachutes over the residential districts. From the',
        'private idea became the operation "Little Vittles", from the planes',
        'became the **Candy Bombers**. On 12 May 1949 the Soviet side lifted',
        'the blockade.',
        '',
        'What really happened here was a reversal: three years after the end',
        'of a war that Germany had begun, children of Berlin stood at the',
        'flight path and waved at the planes that had bombed their city.',
        'From occupiers became protecting powers. This voice also names the',
        'uncomfortable part of it: the Airlift was a humanitarian',
        'achievement and a political success at once, and in Washington and',
        'London both were known from the start. Whoever wins the hearts of a',
        'city wins a position.',
        '',
        'In the same year two German states came into being: the Federal',
        'Republic (Basic Law of 23 May 1949) and the GDR (7 October 1949).',
        'Neither understood itself as final. Bonn became the capital because',
        'it was insignificant enough to seem provisional.',
        '',
        '## Two blocs: NATO 1949, Warsaw Pact 1955',
        '',
        'On 4 April 1949 twelve states signed the North Atlantic Treaty in',
        'Washington: the USA, Canada, Great Britain, France, Italy, Belgium,',
        'the Netherlands, Luxembourg, Norway, Denmark, Iceland and Portugal.',
        'The core is Article 5 — an attack on one counts as an attack on',
        'all. For the first time in their history the USA entered into an',
        'alliance with European states in peacetime.',
        '',
        'The first Secretary General, Lord Ismay, is said to have',
        'summarised the purpose of NATO like this: to keep the Americans in,',
        'the Russians out and the Germans down. Whether he ever said the',
        'sentence is unsettled — but it circulated because it had a true',
        'core, and this voice therefore cites it rather than letting it be',
        'used against itself. The alliance was also an instrument for',
        'integrating the Federal Republic, and Portugal was at that time a',
        'dictatorship.',
        '',
        'In 1952 Greece and Turkey joined, in 1955 the Federal Republic.',
        'Nine days after its accession, on 14 May 1955, the **Warsaw Pact**',
        'was founded in Warsaw — with the GDR as a member. With that stood',
        'the order that lasted until 1989. In the same year, however, the',
        'Austrian State Treaty showed that it could also be done',
        'differently: the Soviet troops withdrew from Austria, and the',
        'country declared itself permanently neutral. This example belongs',
        'in a fair narrative.',
        '',
        'Then there was the bomb. In 1949 the Soviet Union had its first',
        'nuclear weapon, in 1952 and 1953 the hydrogen bombs followed on',
        'both sides, in 1957 Moscow shot the first satellite into space with',
        'Sputnik — and thereby proved that it possessed rockets that could',
        'reach any point on earth. From the calculation arose a logic with a',
        'telling abbreviation: MAD, "mutual assured destruction", the',
        'guaranteed mutual annihilation. Peace through the certainty that an',
        'attack would destroy the attacker as well. At the height in the',
        'mid-1980s over 60,000 warheads were stockpiled worldwide.',
        '',
        'Three times people in the East rose up against their governments,',
        'and three times nothing happened from the Western side: on 17 June',
        '1953 in the GDR, in October and November 1956 in Hungary, in August',
        '1968 in Czechoslovakia. Western broadcasters had nourished hopes',
        'that nobody was willing to redeem. The calculation behind it was',
        'always the same and it was soberly correct: an intervention would',
        'have meant war between nuclear powers. But it has a price, and this',
        'text does not dodge it: the West invoked freedom and watched as',
        'people who had trusted precisely in that ran into tanks.',
        '',
        'Likewise with the building of the Berlin Wall. Between 1949 and',
        '1961 around 2.7 million people had left the GDR, most of them via',
        'Berlin. On 13 August 1961 the city was divided. The West protested',
        'sharply and did nothing; President John F. Kennedy said to his',
        'circle of advisers, in substance, that a wall was not a nice',
        'solution, but very much better than a war. That was realistic. It',
        'also meant: the freedom of West Berlin was guaranteed, that of the',
        'people in the East was not.',
        '',
        '## The thirteen days — the Cuban Missile Crisis 1962',
        '',
        'On 14 October 1962 an American U-2 reconnaissance aircraft',
        'photographed launch ramps for medium-range missiles on Cuba. From',
        'there Washington and half the continent would have been reachable',
        'in a few minutes. President Kennedy convened a tight circle of',
        'advisers, the **ExComm**, and for thirteen days a decision was',
        'fought over there of which the world knew nothing.',
        '',
        'The military pressed by a majority for air strikes and an',
        'invasion. On 22 October Kennedy decided for the mildest effective',
        'means: a naval blockade, which for reasons of international law was',
        'called a "quarantine", because a blockade counts as an act of war.',
        'On 24 October the Soviet ships turned back before the line. On',
        'Saturday 27 October — called "Black Saturday" in Washington — a U-2',
        'was shot down over Cuba, and the pilot, Rudolf Anderson, lost his',
        'life.',
        '',
        'How close it really was, almost nobody knew at the time. On the',
        'same day American destroyers forced the Soviet submarine **B-59**',
        'to the surface with practice depth charges. The boat had had no',
        'radio contact for days, the air was used up, the temperature over',
        '45 degrees — and on board there was a torpedo with a nuclear',
        'warhead. The commander considered the war to have broken out and',
        'wanted to use it. For the launch the consent of three officers was',
        'needed. One refused it: Vasili **Arkhipov**. That humanity survived',
        'this weekend hung on the steadfastness of a thirty-four-year-old in',
        'an overheated steel tube.',
        '',
        'The crisis was ended by a deal of which one half was public and the',
        'other half remained secret. Public: the Soviet Union withdraws the',
        'missiles, the USA refrains from an invasion of Cuba. Secret: the',
        'American **Jupiter** missiles in Turkey — and in Italy — are',
        'withdrawn within a few months. Because of the secrecy, Nikita',
        'Khrushchev looked for decades like the loser and Kennedy like the',
        'man who had stood firm. This voice names that as an uncomfortable',
        'spot of its own narrative: a good part of the Western triumphalism',
        'of 1962 rested on the fact that what one had conceded oneself was',
        'concealed.',
        '',
        'And the motives of the other side? From the Moscow point of view',
        'the stationing on Cuba was exactly what American missiles in Turkey',
        'would have been from the Washington point of view, if the signs had',
        'been reversed: unbearably close. Whoever does not think that',
        'through makes the crisis into a story about a madman who gave in —',
        'and learns nothing from it.',
        '',
        'Learned was indeed something: in 1963 the "hot line" between',
        'Washington and Moscow was established, in the same year the treaty',
        'banning above-ground nuclear tests was concluded, in 1968 the',
        'Nuclear Non-Proliferation Treaty.',
        '',
        '## Détente: Brandt, the Eastern Treaties, Helsinki 1975',
        '',
        'From the end of the 1960s both sides tried to make the state of',
        'affairs more bearable. In the Federal Republic this policy carried',
        'a name: **Willy Brandt**, Federal Chancellor from 1969, and his',
        'adviser Egon Bahr, from whom the formula "change through',
        'rapprochement" (1963) comes. The **Eastern Treaties** — Moscow and',
        'Warsaw 1970, the Basic Treaty with the GDR 1972 — recognised the',
        'existing borders as inviolable and in return made possible visiting',
        'rights, telephone lines and trade. That was highly controversial in',
        'the Federal Republic; the opponents saw in it the abandonment of',
        'reunification. On 7 December 1970 Brandt knelt before the memorial',
        'to the victims of the Warsaw Ghetto — a gesture that was also',
        'argued about at home.',
        '',
        'The biggest step was the Conference on Security and Co-operation in',
        'Europe. On 1 August 1975 in **Helsinki** 35 states signed the Final',
        'Act of the **CSCE**: all NATO countries, all Warsaw Pact states and',
        'the neutrals. The Soviet Union got what it had wanted for thirty',
        'years — the recognition of the borders of 1945. The West got for it',
        'the "Basket III": human rights, freedom of travel, family',
        'reunification, free exchange of information and opinions.',
        '',
        'Many in the West considered that a bad bargain — fixed borders',
        'against soft words. It became the most consequential deal of the',
        'whole Cold War. Because the Final Act had to be published in all',
        'signatory states, civil rights activists from Moscow to Prague',
        'could suddenly invoke a document that their own government had',
        'signed. In 1976 the Moscow Helsinki Group was founded, in 1977',
        'Charter 77 in Czechoslovakia, in 1980 the trade union Solidarność',
        'in Poland. What looked like a concession worked like a lever —',
        "applied from within, by one's own citizens.",
        '',
        'The détente did not hold. In 1979 NATO decided on the deployment of',
        'intermediate-range missiles, combined with the offer to negotiate;',
        'in December of the same year the Soviet Union invaded Afghanistan.',
        'The coldest years since 1962 followed: President Ronald Reagan',
        'spoke in 1983 of the "evil empire", in November 1983 the Soviet',
        'leadership temporarily took the NATO exercise "Able Archer" for the',
        'preparation of a real attack. And on 26 September 1983 a Soviet',
        'early-warning system reported the approach of American missiles.',
        'The officer on duty, Stanislav Petrov, did not pass the alarm on',
        'because the number seemed too small to him. It was a false alarm.',
        'For the second time everything hung on a single individual — and',
        'this time it was one from the other side.',
        '',
        '## The uncomfortable spots — what the West itself has to answer for',
        '',
        'This section stands here because otherwise it would be left to the',
        'counter-voice. The West fought the Cold War in the name of freedom',
        'and law and thereby violated both several times itself.',
        '',
        '**The McCarthy era.** Between 1947 and 1954 tens of thousands in',
        'the USA were checked for their political convictions. The House',
        'Committee on Un-American Activities summoned writers, directors and',
        'actors; whoever refused to testify ended up on blacklists and found',
        'no more work — the "Hollywood Ten" went to prison for it. From 1950',
        'Senator Joseph McCarthy claimed to possess lists of communists in',
        'the State Department that he never produced. People lost positions,',
        'friends and health on the basis of suspicions against which there',
        'was no defence. Only in 1954, when McCarthy took on the US Army and',
        'the hearings were broadcast on television, did the mood turn. A',
        'country that claimed for itself to defend freedom of opinion',
        'against dictatorship persecuted opinions for years.',
        '',
        '**Vietnam.** That is the own wound. From the support for France in',
        'its colonial war became, from 1964 — after an incident in the Gulf',
        "of Tonkin whose second, decisive part, by today's state of",
        'research, did not happen that way — a war of its own. At the peak',
        'over 540,000 American soldiers stood in the country. More bombs',
        'were dropped than in the entire Second World War, plus napalm and',
        'the defoliant Agent Orange, whose consequences continue to this day',
        'in birth defects. On 16 March 1968 American soldiers murdered',
        'several hundred civilians in My Lai, predominantly women, children',
        'and old people. Around 58,000 Americans died and, depending on the',
        'estimate, two to three million Vietnamese. The war was lost, and it',
        'destroyed the trust of a whole generation in its own government —',
        'not least because the Pentagon Papers showed in 1971 how long and',
        'how deliberately the public had been lied to.',
        '',
        '**The support of dictatorships.** From the principle of containing',
        'communism everywhere followed in practice: whoever was',
        'anti-communist got support, no matter how he governed. In 1953 the',
        'American and British intelligence services toppled in **Iran** the',
        'elected government of Mohammad Mossadegh, who had nationalised the',
        'oil industry, and propped up the Shah — a prehistory without which',
        'the Iranian Revolution of 1979 cannot be understood. In 1954 an',
        'elected government was toppled in Guatemala. In **Chile** the',
        'American government worked for years after the election of',
        'Salvador Allende in 1970 with covert means and economic pressure',
        'toward his overthrow; whether it was itself involved in the',
        'military coup of 11 September 1973 is disputed, the environment it',
        'helped create. What followed was the dictatorship of Augusto',
        'Pinochet with thousands of murdered and disappeared. In Greece',
        'colonels staged a coup in 1967 and ruled for seven years — in a',
        'NATO member state. Spain under Franco and Portugal under Salazar',
        'counted as partners, South Africa with its racial segregation as an',
        'anti-communist ally. And the proxy wars in Korea, Angola, Nicaragua',
        'and Afghanistan cost millions of people their lives who had nothing',
        'to do with the quarrel between Washington and Moscow.',
        '',
        '**The arms race.** It cost sums on both sides that are hard to',
        'imagine — the USA alone spent several trillion dollars on its',
        'nuclear weapons over the decades. The clearest warning against it',
        'came from within: in his farewell address on 17 January 1961,',
        'President Dwight D. Eisenhower, himself a general in the Second',
        'World War, spoke of the "military-industrial complex", against',
        'whose unjustified influence the citizens must be on guard. He knew',
        'what he was talking about.',
        '',
        '## Why the Eastern bloc collapsed',
        '',
        'That is the actual question of this chapter, and it has no simple',
        'answer. Five reasons interlocked.',
        '',
        '**First: planned economy against market economy.** In a planned',
        'economy an authority decides what is produced in what quantity.',
        'That works astonishingly well when a country needs few, clearly',
        'determinable things — steel, cement, tanks — and in the 1950s the',
        'Soviet economy grew quickly. It works badly as soon as a society',
        'becomes more complicated: nobody can calculate for 280 million',
        'people how many shoes in which size are needed. What was missing',
        'was the feedback that in a market economy the price provides. The',
        'result was simultaneously empty shelves and full warehouses of',
        'unsaleable goods, waiting lists of ten years for a car — and,',
        'because enterprises were rewarded for fulfilled plan targets and',
        'not for good products, little reason to improve anything.',
        '',
        '**Second: the technological gap.** In the 1970s and 1980s',
        'microelectronics began in the West. The East could not keep up —',
        'also because a device with which everyone can copy and disseminate',
        'is a problem in a state with censorship. Copy machines in the GDR',
        'were kept under lock and key. A system that must control',
        'information cannot win information technology.',
        '',
        '**Third: the burden of armaments.** The Soviet Union kept up',
        'militarily with the USA although its economy was only a fraction as',
        'large. Estimates assume 15 to 25 percent of economic output for the',
        'military, compared with about 6 percent in the USA. Every missile',
        'was missing elsewhere. The war in Afghanistan from 1979 came on top',
        'as a permanent burden and cost around 15,000 Soviet soldiers their',
        'lives.',
        '',
        '**Fourth: the oil price collapse of 1986.** Crude oil and natural',
        'gas were the most important source of foreign currency of the',
        'Soviet Union — with it grain and Western technology were paid for.',
        'In 1985/86 the **oil price** fell from around thirty to below ten',
        'dollars a barrel. From one year to the next a large part of the',
        'revenues collapsed with which the system had plugged its gaps.',
        '',
        "**Fifth: Gorbachev's reforms.** Mikhail **Gorbachev**, General",
        'Secretary since March 1985, saw the situation clearly and wanted',
        'to save socialism, not abolish it. **Perestroika** (restructuring)',
        'was to make the economy more flexible, **Glasnost** (openness) to',
        'break up the encrustation through public criticism — the reactor',
        'disaster of Chernobyl in April 1986, which was covered up for days,',
        'made the benefit of openness drastically clear to him. Both',
        'together had an explosive force that he had not intended: the half',
        'economic reforms destroyed the old procedures without creating',
        'functioning new ones, and the freedom of opinion turned quiet',
        'discontent into a public movement. Decisive was his renunciation of',
        'the Brezhnev Doctrine: in 1989 Moscow made clear that it would no',
        'longer end the reforms in Eastern Europe with tanks. A Soviet',
        'spokesman mockingly called that the "Sinatra Doctrine" — everyone',
        'may do it their own way. That was the moment in which 1953, 1956',
        'and 1968 could no longer repeat themselves.',
        '',
        'What is expressly missing from this enumeration is the Western',
        'favourite explanation: that the West had armed the East to death.',
        'The arms pressure was a real burden, but the decisive causes lay in',
        'the system itself and in the decisions that were made in Moscow.',
        'The West did not bring about this collapse. It experienced it — and',
        'was as surprised as everyone else.',
        '',
        '## 1989 to 1991 — the turn from the Western point of view',
        '',
        'From 1985 Reagan and Gorbachev negotiated: Geneva 1985, Reykjavík',
        '1986, where the complete abolition of all nuclear weapons was',
        'almost agreed, and in 1987 the INF Treaty — the first treaty in',
        'history that did not limit a whole class of weapons but abolished',
        'it. In June 1987 Reagan stood at the Brandenburg Gate and called on',
        'Gorbachev to tear down this Wall.',
        '',
        'Then everything went very fast. In Poland the government and',
        'Solidarność agreed in spring 1989 at the Round Table on partially',
        'free elections; in June the opposition won all the seats it was',
        'allowed to contest. Hungary began in May to dismantle the barriers',
        'at the border with Austria and opened the border completely on 11',
        'September. In Leipzig from September onward more and more people',
        'went onto the streets on Mondays; on 9 October there were around',
        '70,000, and not a shot was fired. On the evening of **9 November',
        '1989** the Wall opened, after a member of the GDR leadership had',
        'announced a new travel regulation ambiguously at a press',
        'conference. In Prague the Velvet Revolution brought a change of',
        'power without violence within weeks; in Romania it ended bloodily,',
        'with the execution of Nicolae Ceaușescu on 25 December 1989.',
        '',
        'In the West Gorbachev became a figure of respect — in Germany more',
        'than anywhere else. One knew to whom one owed that 1989 turned out',
        'differently than 1953. That he found far less approval for it in',
        'his own country belongs to the other half of this chapter.',
        '',
        '## The Two Plus Four Treaty, 12 September 1990',
        '',
        'German unity was not an internal German affair. Four powers had',
        'held rights over Germany since 1945, and without their consent a',
        'unification was not possible under international law. Therefore in',
        '1990 two German states negotiated with four victorious powers —',
        'hence the name. On **12 September 1990** the foreign ministers',
        'signed in Moscow the "Treaty on the Final Settlement with Respect',
        'to Germany". It is the keystone of this chapter, and what stands in',
        'it is worth reading closely:',
        '',
        '- **Article 1: the borders.** The united Germany comprises the',
        '  Federal Republic, the GDR and all of Berlin — and nothing else.',
        '  The **Oder–Neisse** border with Poland is finally recognised, all',
        '  territorial claims are excluded. A separate German–Polish border',
        '  treaty confirmed that on 14 November 1990.',
        '- **Article 2: the renunciation of wars of aggression.** From',
        '  German soil only peace shall go forth; the preparation of a war',
        '  of aggression is unconstitutional and punishable.',
        '- **Article 3: weapons and troop strength.** Germany renounces',
        '  nuclear, biological and chemical weapons and limits its armed',
        '  forces to 370,000 soldiers.',
        '- **Article 4: the troop withdrawal.** The Soviet troops withdraw',
        '  by the end of 1994 from the territory of the former GDR.',
        '- **Article 5: the territory of the former GDR.** There no foreign',
        '  troops are stationed and no nuclear weapons are deployed.',
        '- **Article 6: the freedom of alliance.** The right of the united',
        '  Germany to belong to alliances is not affected by this treaty.',
        '- **Article 7: the sovereignty.** The rights and responsibilities',
        '  of the four powers with regard to Berlin and Germany as a whole',
        '  end. The united Germany receives full sovereignty over its',
        '  internal and external affairs.',
        '',
        'On 3 October 1990 the GDR acceded to the scope of application of',
        'the Basic Law. Forty-five years after the end of the war Germany',
        'was again a state — and for the first time since 1871 one whose',
        'borders none of its neighbours disputed.',
        '',
        '**Was the treaty upheld?** This question is asked today, and it',
        'deserves a fair answer. Formally the answer is: yes. The Soviet',
        'troops withdrew by 31 August 1994, even somewhat earlier than',
        'agreed. Germany kept the renunciation of ABC weapons, confirmed the',
        'Oder–Neisse border and stationed no foreign troops in the East. And',
        'the NATO membership of the united Germany was no breach of treaty:',
        'Article 6 expressly permits belonging to an alliance — that was the',
        'core of the negotiations in 1990, and the Soviet side agreed to it.',
        '',
        'What became disputed afterwards is something else: not the wording,',
        'but the "spirit" of the arrangements of 1990 — and the question of',
        'what Western politicians said orally to Gorbachev at the time',
        'about a possible extension of NATO eastwards. This dispute belongs',
        'in the next chapter, "Russia and the West", and is treated there in',
        'detail with both points of view. Here only the finding stands: the',
        'Two Plus Four Treaty itself did not forbid NATO membership, and the',
        'eastward enlargement came later and was not its subject.',
        '',
        'On **25 December 1991** Mikhail Gorbachev resigned; in the evening',
        'the red flag was lowered over the Kremlin. One day later the',
        'Supreme Soviet dissolved itself. The Soviet Union had ceased to',
        'exist — without war, without capitulation, without anyone having',
        'defeated it.',
        '',
        '## "Who won the Cold War?"',
        '',
        'This question was asked everywhere in the West in 1990, and the',
        'answer seemed self-evident: we did. The political scientist Francis',
        'Fukuyama wrote of the "end of history" — liberal democracy and the',
        'market economy had prevailed as the best of all orders, the great',
        'dispute was decided.',
        '',
        'This voice gives a more uncomfortable answer to that, and it gives',
        'it itself, before anyone else demands it of it.',
        '',
        'First: it was less a victory than a collapse. The Soviet Union was',
        'not defeated, it went under from its own contradictions — and from',
        'the fact that its last leader refused to hold it together by force.',
        'Whoever makes an own victory out of the failure of others draws the',
        'wrong lessons from it.',
        '',
        'Second: the euphoria of 1989 was not experienced everywhere in the',
        'East as liberation. For millions of people the end also meant the',
        'end of their plant, their pension, the recognition of their working',
        'life. In East Germany over two thirds of the industrial jobs',
        'disappeared within a few years; in Russia economic output fell by',
        'almost half in the 1990s and the life expectancy of men by years.',
        'That people who had stood on the streets in 1989 were bitter ten',
        'years later is no contradiction — they are two truths of the same',
        'process.',
        '',
        'Third: much that is taken for granted today is owed to this end —',
        'the freedom of movement in Europe, the disarmament treaties, the',
        'fact that free elections are held in Warsaw and Prague. That too',
        'belongs in the same balance, without one cancelling out the other.',
        '',
        '## And the other voices',
        '',
        'What stands here is a narrative from one side of the line. It knows',
        'the Airlift from the cockpits, not from the cellars of the Soviet',
        'Kommandatura. It knows the Wall from the outside. It does not know',
        'how forty years of the Warsaw Pact felt for a country that had been',
        'invaded in 1941 and saw a threat in NATO, and it does not know what',
        'everyday life was like in a state that no longer exists — with',
        'kindergarten place and company holiday on the one side, Stasi and',
        'exit application on the other.',
        '',
        'That is why this perspective does not stand alone. The **view of',
        'the East** — of the Soviet Union, the Warsaw Pact and the GDR —',
        'Hermes complements after this round, and afterwards possibly the',
        'view of the Germans in East and West, for whom the division was not',
        'a chapter but their life. Only then can a synthesis bring together',
        'what here necessarily remains one-sided. Until then what applies',
        'for this whole chapter applies: this voice does not say "that is',
        'how it was". It says: that is how it is told from here.',
      ].join('\n'),
    },
    {
      id: 'osten-sicht',
      name: 'The view of the East — Soviet Union, Warsaw Pact, GDR',
      stimme: 'Hermes',
      text: [
        'This voice tells from Moscow, from Warsaw, from East Berlin: from',
        'the world that ceased to exist in 1991. It is of equal worth with',
        'the voice of the West — that it stood first there was only the',
        'order in which was written.',
        '',
        'This voice does not begin in 1945, but with a memory: the Soviet',
        'Union had to mourn **around 27 million dead** in this war — more',
        'than any other country. Within thirty years its territory had been',
        'invaded twice from the West, in 1914 and 1941. From this experience',
        'speaks every Eastern decision of the Cold War. What the West read',
        'as Soviet aggression was, from the Moscow point of view, first',
        'fear: the fear of a third invasion. A buffer zone of friendly',
        "states — the \"people's democracies\" — was for this voice not a",
        'conquest but insurance.',
        '',
        '## Building up in the East',
        '',
        'The East of Germany, too, lay in ruins in 1945. And here, too, was',
        'built up — among other things with reparations that the Soviet',
        'Union regarded as its due: after what the German armies had done in',
        'the Soviet Union. The GDR called its path the **"building of',
        'socialism"**: large enterprises, land reform, free education,',
        'kindergartens, the mass organisations. Whoever grew up in this',
        'world learned: we are building the better thing — a society without',
        'unemployment, without poverty, without the class antagonisms of the',
        'West. That the West claimed the same made up the rivalry that waged',
        'the Cold War also in everyday life.',
        '',
        '## Berlin 1948 and the Airlift — the other narrative',
        '',
        'The West tells the blockade of Berlin as the rescue of an enclosed',
        'city by the Airlift. This voice tells it differently, and both',
        'narratives are verifiable: from the Eastern point of view at the',
        'beginning stood the **currency reform of June 1948**, with which',
        'the Western powers unilaterally ended the joint Four-Power',
        'administration of Germany — a step that was to seal the division of',
        'the country even before the blockade of Berlin began. The blockade',
        'was, from the Moscow point of view, the answer to this unilateral',
        'action: whoever terminates the joint order must reckon with the',
        'consequences. The West won this round — the Airlift was a technical',
        'and human masterpiece. But that Berlin survived because the West',
        'supplied it confirmed, from the Eastern point of view, only what',
        'the division already was anyway: a competition that the East could',
        'not win.',
        '',
        '## The Berlin Wall — the "anti-fascist protection wall"',
        '',
        'The GDR had been losing its population since its foundation: **by',
        '1961 around 2.7 million people had gone to the West** — most of',
        'them young, many trained. Doctors, engineers, teachers left the',
        'country that had trained them. From the point of view of the GDR',
        'leadership the Wall of 13 August 1961 was therefore not a prison',
        'but **self-defence**: the "anti-fascist protection wall" against',
        'the poaching by the West, which with its prosperity bled the East',
        'dry. This voice says that not as a justification — the Wall tore',
        'families apart and cost people their lives. But it says it because',
        'without the distress of the GDR the Wall is not explicable. A state',
        'that locks up its citizens is no good state — and a state that must',
        'do it because its citizens leave is one in distress.',
        '',
        '## Everyday life in the East',
        '',
        'What this voice holds against the Western narrative is everyday',
        'life: full employment, a right to work that nobody questioned,',
        'kindergartens, education without school fees, inexpensive housing,',
        'a social net that let nobody fall. Whoever lived in the East also',
        'knew the dark sides — the **shortage economy** with its queues, the',
        'Stasi, the freedom to travel that did not exist, the SED that',
        'allowed no other opinion. This voice turns over both sides because',
        'only so becomes understandable why the East held out so long: it',
        'offered security where the West offered freedom. And it becomes',
        'understandable why it finally broke apart: the people wanted both.',
        '',
        '## The difficult years and détente',
        '',
        'This voice does not conceal what happened in the East when the',
        'order wavered: the **17 June 1953**, when Soviet tanks put down',
        'the uprising in the GDR; **Hungary 1956**; the **Prague Spring',
        '1968**, when troops of the Warsaw Pact ended the reforms in',
        'Czechoslovakia — the "Brezhnev Doctrine", according to which',
        'socialism must not be lost in any country. For the West these were',
        'proofs of the character of the system. For this voice they were the',
        "defence of one's own camp — and it knows how cynical that sounds",
        'today.',
        '',
        'And then came détente, and it also benefited the East: the',
        '**Eastern Treaties** of the early 1970s, the Basic Treaty with the',
        'Federal Republic, and in 1975 the **CSCE Final Act of Helsinki**.',
        'From the Eastern point of view Helsinki was the great gain: the',
        'West recognised the post-war borders — including the Oder–Neisse',
        'border and the existence of the GDR. That human rights also stood',
        'in the same Final Act appeared then as a concession to the West.',
        'That precisely these lines would hollow out the East from within',
        'twenty years later, nobody saw — not even this voice.',
        '',
        '## What this voice cannot do',
        '',
        'This voice cannot explain why the GDR citizens left in droves in',
        '1989 while their government still spoke of stability. It cannot',
        'explain why the system called "really existing socialism" had so',
        'little support in the end that a Monday demonstration brought it to',
        'collapse. That is the most uncomfortable spot of this voice: the',
        'East lost the competition not only economically, but also in the',
        'trust of its own people. The freedom that the West offered was no',
        'shop window — it was what the people really wanted.',
      ].join('\n'),
    },
    {
      id: 'deutsche-sicht',
      name: 'The view of the Germans in East and West',
      stimme: 'Hermes',
      text: [
        'This voice does not speak for a government, but for the people for',
        'whom the division was everyday life: for the family that stood at',
        'the border on the weekend, for the grandmother in Leipzig and the',
        'uncle in Hamburg, for the children who grew up in a divided city.',
        'It is the third voice of this chapter, and it is the quietest —',
        'because it does not tell of world politics, but of life within it.',
        '',
        '## Two lives in one country',
        '',
        'After 1945 there were no "the Germans" — there were the people in',
        'the West and the people in the East, and both soon told their own',
        'stories. In the West a generation grew up with the **economic',
        'miracle**: with the VW Beetle, with the holiday abroad, with the',
        'firm conviction that democracy and market are the right thing. The',
        'division was for them a matter of the news — the Wall was far away,',
        'even though it ran through the middle of Berlin.',
        '',
        'In the East a generation grew up with the building: with the',
        "Jugendweihe, with the company celebration, with the pride in one's",
        'own plant — and with the small compromises of everyday life.',
        'Whoever did not stand out lived best; whoever said what he thought',
        'got trouble. Between these two lives lay a border that was a',
        'holiday topic for the one and a wall of life for the other.',
        '',
        '## The Berlin Wall in everyday life',
        '',
        'The Wall was for the Germans in the East no metaphor, but a',
        "concrete wall in one's own cityscape: the death strip, the",
        'watchtowers, the order to shoot. Families were torn apart — **more',
        'than three million visits per year before 1961, after that almost',
        'none**. Letters, parcels, telephone calls under surveillance,',
        'funerals to which the relatives from the West could not travel.',
        'This voice does not want to play one side off against the other:',
        'there were people in the West who felt the division as an injustice',
        'and demonstrated against it — and there were people in the East who',
        'rejected the system and still stayed because they did not want to',
        'give up their country. But the asymmetry remains: only the one side',
        'needed a wall.',
        '',
        '## 1989 — the people and the Wall',
        '',
        'Then came autumn 1989. In Leipzig the **Monday demonstrations**',
        'began — first with candles, then with tens of thousands: "We are',
        'the people." The slogan was first a demand to one\'s own',
        'government, no call for the West. When the borders fell on **9',
        'November 1989**, people stood on the Wall who had never met before',
        '— East Germans and West Germans, crying and laughing at once.',
        'Whoever experienced this night tells it to this day as the',
        'happiness of a life.',
        '',
        '## Reunification — and its two sides',
        '',
        'The **3 October 1990** made out of two German states one again. The',
        'joy was real — and it was not the whole story. This voice also',
        'names the other side: the **Treuhand** sold or closed the East',
        'German enterprises, millions lost their work, the biographies of',
        'engineers and teachers suddenly counted for nothing. Some in the',
        'East experienced the reunification as a takeover instead of a',
        'liberation — and some in the West as a burden instead of a joy.',
        'From these two experiences grew the "**wall in the head**", which',
        'held longer than the one of concrete: the prejudices between',
        '"Wessis" and "Ossis", which echo to this day.',
        '',
        '## What this voice knows',
        '',
        'This voice knows that history consists not only of treaties and',
        'powers, but of what people make of them. The Two Plus Four Treaty',
        'of 12 September 1990 sealed the reunification — but the',
        'reunification itself the people had carried onto the streets. No',
        'head of government, no army tore down the Wall: it was the people',
        'who could no longer be stopped. This voice ends with a memory of',
        'those who did not make it — of the **around 140 dead at the',
        'inner-German border**, whose stories are the other side of this',
        'freedom.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Three voices, one country, one world. This synthesis brings',
    'together what the West, the East and the Germans in East and West',
    'have told — and it begins with the **fault lines** at which the',
    'same events began quite differently.',
    '',
    'With the **beginnings**: The Western narrative begins with a Soviet',
    'Union that installed governments in Eastern Europe — and derives',
    'containment from it. The Eastern narrative begins with a country',
    'that had to mourn 27 million dead and had been invaded twice from',
    'the West — and derives the security zone from it. Both beginnings',
    'are verifiable. Depending on which one you set, the other side is',
    'attacker or defender. That is the first lesson: history does not',
    'begin where the sources begin, but where the narrators set the',
    'beginning.',
    '',
    'With **Berlin 1948**: For the West the Airlift is the rescue of an',
    'enclosed city. For the East the currency reform before it is the',
    'actual break — the step with which the Western powers ended the',
    'joint administration. The same eleven months, two beginnings, two',
    'truths. The Airlift remains a masterpiece — and the currency reform',
    'remains a unilateral action. Both stand.',
    '',
    'With the **Wall**: The West sees a government that had to lock up',
    'its citizens. The East sees a state in distress that bled out while',
    'a shop window was being built next door. And the third voice sees',
    'the families that were torn apart. Whoever lets all three sentences',
    'stand side by side has no answer yet — but the right question: Why',
    'must a state lock up its citizens so that they stay?',
    '',
    'With the **economy**: The West led the competition of the systems',
    'that the East lost. The planned economy secured survival, but not',
    'prosperity; it promised equality and produced shortage. The freedom',
    'of the West was no shop window — it was what the people really',
    'wanted, and precisely that hollowed out the East: first from',
    'within, through the longing, then from outside, through the',
    'opening.',
    '',
    'And then the **Two Plus Four Treaty**: On 12 September 1990 the',
    'united Germany received back its full sovereignty; the Four-Power',
    'rights ended. The treaty itself expressly allowed the country to',
    "belong to alliances — the question of whether NATO's eastward",
    'enlargement violated the spirit of the treaty belongs in the next',
    'chapter. Here stands the finding: the Wall fell because the people',
    'no longer accepted it — not because a treaty so determined.',
    '',
    'The last fault line is **freedom**. The West and the East argued',
    'for decades about which system was better. The Germans in East and',
    'West gave the answer — not with weapons, but with their feet and',
    'with candles. What ended in 1991 was not only a state, but a',
    'promise that the people no longer wanted to buy. To remember that',
    'is the task of this chapter — and the lesson that reaches into the',
    'present.',
  ].join('\n'),

  urteil: {
    frage: 'For forty years two blocs faced each other with tens of thousands of nuclear weapons, without a war breaking out between them — and both sides say to this day that their deterrence was the reason. Did peace hold despite these weapons or because of them, and what does your answer mean for the question of how one creates security today?',
    hinweis: "There is no right and no wrong here. Two thoughts to think on: Some say deterrence worked — no politician could want to win a war in which one's own country would also go under, and precisely that secured forty years of peace between the great powers. Others say that is a calculation that only holds as long as all involved are rational, well informed and of sound mind — and the Cuban Missile Crisis, the Soviet submarine B-59 and the false alarm of 1983 showed how often that was precisely not the case. Perhaps the question helps: Would you enter a bet that works out 99 percent of the time, if the one remaining percentage point costs everything?",
  },

  quiz: [
    {
      frage: 'What was the Berlin Airlift of 1948/49?',
      antworten: [
        'The supply of West Berlin from the air, after all land and water routes had been blocked.',
        'A bridge over the Spree that connected the four sectors of the city.',
        'The removal of industrial plants from Berlin as a reparation payment.',
      ],
      richtig: 0,
      erklaerung: 'After the access routes were blocked on 24 June 1948, around 280,000 flights brought about 2.3 million tonnes of goods into the city in eleven months — at the peak a plane landed every three minutes. That was possible because the three air corridors had been agreed in writing in 1945. On 12 May 1949 the blockade was lifted.',
    },
    {
      frage: 'When were NATO and the Warsaw Pact founded?',
      antworten: [
        'NATO in 1949, the Warsaw Pact in 1955 — shortly after the Federal Republic had joined NATO.',
        'Both in the same year 1949, immediately after the founding of the two German states.',
        'The Warsaw Pact in 1945 in Potsdam, NATO as the answer to it in 1961.',
      ],
      richtig: 0,
      erklaerung: 'The North Atlantic Treaty was signed on 4 April 1949 by twelve states. The Federal Republic joined on 5 May 1955 — nine days later, on 14 May 1955, the Warsaw Pact came into being. In the same year the Soviet troops withdrew from Austria, which has been neutral since then.',
    },
    {
      frage: 'How did the Cuban Missile Crisis end in October 1962?',
      antworten: [
        'Through a deal: the Soviet Union withdrew the missiles, the USA publicly refrained from an invasion of Cuba and secretly withdrew its Jupiter missiles from Turkey.',
        'Through American air strikes that destroyed the launch ramps on Cuba.',
        'Through a resolution of the United Nations that declared Cuba a neutral zone.',
      ],
      richtig: 0,
      erklaerung: 'Kennedy decided against the advice of many military men for a naval blockade instead of an attack. The withdrawal of the Jupiter missiles remained secret for decades — which is why it long looked as if only one side had given in. How close it was was shown by the Soviet submarine B-59, on which an officer prevented the use of a nuclear torpedo.',
    },
    {
      frage: 'What was special about the CSCE Final Act of Helsinki 1975?',
      antworten: [
        'The signatories recognised the existing borders and at the same time committed themselves to human rights — which civil rights activists in the East could later invoke.',
        'It ended the Warsaw Pact and ordered the withdrawal of all Soviet troops from Eastern Europe.',
        'It forbade both sides the possession of nuclear weapons in Europe.',
      ],
      richtig: 0,
      erklaerung: '35 states signed on 1 August 1975. Because the Final Act had to be published in all countries, civil rights groups could invoke a document that their own government had signed: the Moscow Helsinki Group in 1976, Charter 77 one year later.',
    },
    {
      frage: 'What did the Two Plus Four Treaty of 12 September 1990 regulate?',
      antworten: [
        'It sealed German unity under international law: full sovereignty, end of the Four-Power rights, final recognition of the Oder–Neisse border, renunciation of ABC weapons and the withdrawal of the Soviet troops by the end of 1994.',
        'It divided Germany into four occupation zones and regulated the reparations.',
        'It obliged the united Germany to neutrality and forbade it membership in alliances.',
      ],
      richtig: 0,
      erklaerung: 'Negotiated were two German states and the four victorious powers — hence the name. Article 6 expressly states that the right of the united Germany to belong to alliances remains unaffected; Article 7 ends the rights of the four powers. On 3 October 1990 Germany was again a state, on 31 August 1994 the last Soviet soldiers left the country.',
    },
  ],
};

module.exports = kalterKrieg;

