// Topic: The early kingdoms — how conquerors became rulers.
//
// Status: Round 9. For now contains ONLY the view of the chroniclers and
// royal courts (Voice: Opus). The view from the villages is added by Hermes;
// the synthesis below is explicitly preliminary and will be revised
// together afterwards (see CLAUDE.md, perspectives workflow).
//
// The axis of this chapter is not geographic but social: top against
// bottom. This first voice belongs to those who had things written —
// kings, bishops, court scholars. It is therefore the voice of the
// powerful, and it must remain recognisable as such: legitimation is its
// purpose. That is why the dark side is explicitly part of the text (murder
// and betrayal at the courts), not as an addition from outside, but the way
// it stands in the same chronicles that praise the rulers. No
// glorification, no demonisation.
//
// The chapter links directly to "Germanic Peoples and the Migration
// Period": there the story ended with kingdoms that kept Roman officials
// and had their law written down in Latin. Here the question is how rule
// came into being from that — and the arc closes in 800 in Rome.
//
// The map is in karten/koenigreiche.js — four states between 476 and
// 800; the Frankish realm is the smallest patch in the first picture and
// the largest area in the last.
//
// Pure data — no UI imports (architecture rule).

const koenigreiche = {
  id: 'koenigreiche',
  titel: 'The early kingdoms — how conquerors became rulers',
  epoche: 'From the end of the Western Roman Empire in 476 to the imperial coronation of Charlemagne in 800',

  aufhaenger: {
    frage: 'They came as warriors without a chancery and without a chronicle — and three hundred years later one of their descendants had himself crowned emperor by the pope. How does a war band become a kingdom?',
    text: [
      "A war leader can give orders as long as he hands out loot. Imagine",
      "you are that war leader. Your men follow you because you make them",
      "rich — gold, weapons, horses, land. They follow you personally, not",
      "your office. And now you have won: the land belongs to you. It has",
      "cities you have never visited, roads you did not build, and a",
      "million people who do not understand a single word of your language.",
      '',
      "How do you rule it? How do you make sure that your orders also hold",
      "where you are not present? How do you collect taxes when nobody",
      "knows anymore who owes how much? And the hardest question of all:",
      "How do you make sure that your son may do the same as you — that",
      "people obey him even though he has never won a battle?",
      '',
      "Exactly this task faced the kings after 476. Their answers are the",
      "blueprint on which Europe built for a thousand years afterwards:",
      "an alliance with the Church, a baptism at the right moment, the",
      "right to parchment — and the claim that God himself had willed it",
      "so.",
      '',
      "On 25 December 800 one of their descendants stood in Rome and had",
      "an imperial crown placed on his head. The chroniclers wrote: The",
      "Empire is back. How that came about is told in this chapter — and",
      "first of all the way it was told by those who had something to",
      "gain from it.",
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'chronisten',
      name: 'The view of the chroniclers and royal courts',
      stimme: 'Opus',
      text: [
        "That is how the history of the early kingdoms is told where it",
        "was written down: at the courts, in the bishops' cities and in",
        "the monasteries. It is the story of the powerful — not because",
        "the others had nothing to say, but because only these had things",
        "written down.",
        '',
        "Keep four names ready while you read, for to them we owe almost",
        "everything: **Gregory of Tours**, bishop, wrote his “Ten Books of",
        "Histories” about the Franks around 590. **Fredegar** is the name",
        "of a chronicle of the seventh century whose author we do not",
        "know. **Bede**, a monk in Northumbria, completed the first",
        "history of the English people in 731. And **Einhard** wrote the",
        "life of Charlemagne around 830, after he had lived at his court",
        "for decades.",
        '',
        "Four churchmen. None of them wrote out of curiosity alone: Each",
        "wrote for someone, about someone and with an intention. That does",
        "not make their books worthless — it makes them sources one must",
        "read like a letter whose sender one knows.",
        '',
        '## The map after the end',
        '',
        "Look at the first phase on the map, the year 476. There is no",
        "empty land and no wilderness, but a map of ruins: seven",
        "lordships where just before there had been one. The Visigoths",
        "hold southern Gaul and Spain — the largest realm of the West.",
        "The Vandals sit in North Africa, the Burgundians on the Rhône,",
        "Odoacer in Italy. In Britain, Anglo-Saxon leaders have begun to",
        "call themselves kings. And the Franks? A strip around Tournai,",
        "the smallest patch in the whole picture.",
        '',
        "In 476 hardly anyone would have bet that precisely this patch",
        "would one day be the largest area of the map. In the last",
        "picture, in the year 800, it is.",
        '',
        "The question all these lords faced was the same: How do you hold",
        "it all together? An army follows one man. A kingdom must also",
        "work when the man happens to be elsewhere — and when he is dead.",
        '',
        '## Where the new lords drew their power from',
        '',
        "First from what they brought with them: **retinue**. A leader",
        "gathered men around him who swore him loyalty; he gave them",
        "weapons, jewellery, horses, a place at his table and a share of",
        "the loot. This is not a relationship of office but a personal",
        "bond — and an expensive one. A king who had nothing left to",
        "distribute was soon no king at all.",
        '',
        "Precisely here lies the problem of success. As long as you",
        "conquer, there is loot. Once the conquest is over, the king must",
        "get out of the land what he previously got out of war. That",
        "means: give land away (and thereby become poorer), collect dues",
        "(and for that need people who can count and write) — or wage war",
        "again. Almost everything that happens in the coming centuries",
        "has to do with this calculation.",
        '',
        "And then these kings needed something else that cannot be bought",
        "with loot: a reason why precisely their family was allowed to",
        "rule. The answer they found shaped Europe — they brought God on",
        "board.",
        '',
        '## Baptism as a tool',
        '',
        "Around 496 the Frankish king **Clovis** had himself baptised in",
        "Reims. Gregory of Tours tells it as a miracle: Clovis stands in",
        "a losing battle against the Alamanni, vows to become a Christian",
        "if he wins — and wins. Bishop Remigius is said to have called",
        "out to him at the baptism: “Bow your neck. Worship what you have",
        "burned, burn what you have worshipped.” Even the year is",
        "uncertain; it may also have been 498 or 499.",
        '',
        "What matters is not that Clovis became a Christian, but **what",
        "kind of Christian**. For the kings of the Goths, Vandals and",
        "Burgundians had long been Christians — but Arians, followers of",
        "a teaching that the Catholic Church had condemned as heresy. For",
        "the Catholic population of Gaul and its bishops, these kings",
        "were heretics. Clovis had himself baptised as a Catholic and was",
        "thus the only Germanic king behind whom the old Roman upper",
        "class could stand unreservedly. Overnight, a foreign warlord",
        "became a protector of the true faith.",
        '',
        "What a tool that was can be seen from the fact that others",
        "copied it. In 589 the Third Council of Toledo assembled, and",
        "the Visigothic king **Reccared** declared there that he and his",
        "people were giving up the Arian faith. After that, kings and",
        "bishops ruled Spain together; the councils of Toledo were half",
        "church council, half royal assembly. In 597 Æthelberht, king of",
        "Kent, received the Roman monk Augustine — cautiously, in the",
        "open air, out of fear of sorcery — and had himself baptised.",
        "Here too the pious account likes to pass over a small detail:",
        "Æthelberht's wife Bertha was a Frankish princess, already a",
        "Christian, and had brought her own bishop with her.",
        '',
        "Seen soberly, baptism was both for these kings: a step of faith",
        "and a step of power. The chroniclers tell only the first. One",
        "may nevertheless keep the second in mind.",
        '',
        '## The Church inherits the administration',
        '',
        "Now comes the most important sentence of this chapter, and it",
        "sounds unspectacular: **The kings usually could not write — the",
        "Church could.**",
        '',
        "When the Western Roman Empire collapsed, its administration did",
        "not simply vanish; it migrated. The bishops' sees lay in the old",
        "Roman cities, the church districts followed the Roman",
        "administrative districts — our dioceses are to a good part still",
        "the Roman map. Bishops often came from the same noble families",
        "that had previously provided governors. They knew Latin, knew",
        "the law, kept lists, managed grain, dispensed justice,",
        "negotiated with besiegers.",
        '',
        "For a king, a bishop was therefore doubly valuable: as an expert",
        "and as an intercessor with God. For a bishop, a king was doubly",
        "valuable: as protection and as patron. Both needed each other,",
        "and both knew it.",
        '',
        "You can see the result in an apparent trifle. The Franks had",
        "their law written down around 510, the **Lex Salica** — their",
        "own, ancient law with fines for theft, manslaughter and insult.",
        "But they had it written in **Latin**, by scribes of the Church,",
        "on the Roman model. The Visigoths, Burgundians and Lombards did",
        "the same. Whoever wants to make rule lasting needs writing —",
        "and writing lay in the monasteries.",
        '',
        "The chroniclers draw from this a formula that was to hold for",
        "six hundred years: the king rules **by the grace of God**. Not",
        "because he is the strongest warrior. But because God has willed",
        "him — and who attests that is the Church.",
        '',
        '## Theodoric: a king who wanted to be Roman',
        '',
        "The man who went furthest was **Theodoric the Great**. He came",
        "to Ravenna in 493, killed Odoacer with his own hand at a",
        "banquet — and then ruled for thirty-three years as Roman as it",
        "was possible to be. Roman officials, Roman law, a senate he let",
        "keep working, grain distributions, circus games, building",
        "programmes. He did not call himself emperor; formally he ruled",
        "in the name of the emperor in Constantinople. His churches and",
        "his mausoleum in Ravenna stand to this day; you can go and look",
        "at the mosaics.",
        '',
        "In the letters his chancellor Cassiodorus wrote for him, the",
        "programme is stated explicitly: the Goths provide the defence,",
        "the Romans the civilisation, and both benefit. It was a serious",
        "attempt to let two peoples live in one realm.",
        '',
        "And it did not hold to the end. Theodoric was an Arian, his",
        "subjects Catholic; when relations with Constantinople",
        "deteriorated, distrust turned into persecution. At the end of",
        "his life he had the scholar **Boethius** executed, who in",
        "prison wrote the “Consolation of Philosophy” — one of the most",
        "widely read books of the Middle Ages. A few decades later the",
        "Ostrogothic realm was smashed, not by barbarians but by the",
        "Eastern Roman Empire.",
        '',
        '## The dark side stands in the same books',
        '',
        "Anyone who believes the chroniclers only praised their kings",
        "has not read them. Gregory of Tours calls Clovis a new",
        "Constantine, led from heaven — and on the same pages reports",
        "how this king had his relatives eliminated one after another,",
        "one with an axe, one through hired killers, one through",
        "betrayal. In the end, according to Gregory, Clovis complained",
        "publicly that he now stood alone like a stranger and had no",
        "relatives left who could help him — and Gregory dryly adds that",
        "he said this not out of grief but to see whether anyone else",
        "would step forward whom one could kill.",
        '',
        "And so it continues. The Merovingians divided their realm among",
        "all their sons according to Frankish custom — and these sons",
        "waged war against one another. The queens Brunhild and",
        "Fredegund fought each other for decades; Brunhild, highly",
        "educated and influential for decades, was executed in 613 at",
        "about seventy years of age by being tied to a horse. That does",
        "not stand in an exposé; it stands in the chronicles themselves.",
        '',
        "Why did they write it down? Because they were churchmen and saw",
        "a pattern in it: pride is punished, God judges. Their books are",
        "praise **and** warning at once. For us this has a practical",
        "advantage — a source that also tells unpleasant things about",
        "its hero is more credible than one that only shines.",
        '',
        "Still, the frame remains theirs: it is about kings, bishops,",
        "battles and miracles. Whether the harvest sufficed stands in",
        "these books only when a famine was so great that it reached the",
        "court.",
        '',
        '## 751 and 800: the Church makes kings',
        '',
        "How far the alliance between throne and altar had carried",
        "showed in 751. The Merovingians then ruled only in name; the",
        "real power lay with their mayors of the palace, the",
        "Carolingians. Pepin, the ruling mayor of the palace, had a",
        "question put to the pope that was a loaded one: whether it was",
        "good that he be called king who had no power. The pope answered",
        "that he should rather be called king who actually exercised the",
        "power. Thereupon the last Merovingian was sent to a monastery,",
        "and Pepin became king — and, that was the new thing, **anointed**,",
        "following the example of the kings of the Old Testament.",
        '',
        "With that was said what had applied since Clovis: not descent",
        "alone makes the king, but recognition — and the most important",
        "recognition is granted by the Church.",
        '',
        "Pepin's son Charles ruled for forty-six years and waged war",
        "almost every year. He subdued the Lombards (774), Bavaria (788)",
        "and, in a thirty-year, very bloody struggle, the Saxons, who",
        "were forced to be baptised. In the end his realm reached from",
        "the Elbe to beyond the Pyrenees.",
        '',
        "On 25 December 800 Pope Leo III placed a crown on his head in",
        "Rome and had him proclaimed emperor. For the chroniclers that",
        "was the fulfilment, the arc back over three hundred years:",
        "**The Empire is back.** Einhard claims his lord had been",
        "completely surprised and would not have entered the church had",
        "he known — which most historians regard as courteous diplomacy.",
        "For in Constantinople there still sat an emperor, and there the",
        "event counted as presumption: one cannot crown a second empire",
        "while the first one still stands.",
        '',
        "In Aachen, meanwhile, Charles had something done that looks more",
        "inconspicuous and has reached further than his campaigns. He",
        "brought scholars to the court, above all the Anglo-Saxon Alcuin",
        "of York, and had ancient texts copied — in a new, clearly",
        "legible script. Very much of what we possess today from",
        "antiquity has only survived because it was copied in these",
        "decades. Charles himself, Einhard reports, tried to learn to",
        "write even as an old man and put writing tablets under his",
        "pillow; he never quite succeeded.",
        '',
        '## And the other side?',
        '',
        "Everything you have just read comes from the courts — from",
        "those who had things written down. It is a story of kings,",
        "bishops, battles and coronations, and within its frame it is",
        "honest: it conceals neither the murders nor the usefulness of",
        "faith.",
        '',
        "Only, in these kingdoms nine out of ten people lived on the",
        "land. They grew the grain from which the dues came and supplied",
        "the men from whom the armies were made. In the chronicles they",
        "appear almost only as a number: as famine, as plague, as a",
        "plundered village. Hardly any of them has left a name.",
        '',
        "These questions the view of the courts cannot answer: What",
        "changed for a village when the lord in distant Toulouse",
        "suddenly had a different name? Did one even notice the change",
        "from one realm to the next — or only in who came to collect the",
        "dues? What does “the king's baptism” mean for people who kept",
        "going to their old springs and trees? And what did the Church",
        "bring the villages besides dues: protection, care, a court that",
        "also judged against the powerful?",
        '',
        "They belong to a second voice.",
      ].join('\n'),
    },
    {
      id: 'doerfer',
      name: 'The view from the villages',
      stimme: 'Hermes',
      text: [
        "This perspective tells the story of the kingdoms from below —",
        "from the villages in which most people of this time lived.",
        "Whoever lived there ploughed, sowed, harvested and paid dues; he",
        "did not write and did not have things written. The chronicles",
        "mention these people only at the margin — if at all. That is why",
        "this voice too must honestly say where it comes from: from",
        "settlement finds and field structures, from grave goods, from",
        "place names, from the passages in laws where peasants suddenly",
        "appear. That is less than the courts left behind — but it is",
        "enough to see that the kingdoms looked quite different from",
        "below than from above.",
        '',
        '## The kingdoms, seen from below',
        '',
        "What changed for a peasant when a king died and another came?",
        "Little — except the name of the one who collected the dues. The",
        "village stayed, the fields stayed, the rhythm of the year",
        "stayed: sowing in spring, harvest in summer, slaughtering in",
        "autumn. The kingdoms changed at the top; below, the work went",
        "on. The chronicles tell of conquests and successions as if",
        "history were a tournament of the powerful. For most people it",
        "was a sequence of winters that had to be survived.",
        '',
        '## What the king needed came from our barns',
        '',
        "The glittering world of the courts — retinue, feasts, wars,",
        "gifts — was paid for with what the villages produced. The tithe",
        "to the Church, the dues to the lord, the corvée labour on his",
        "fields: the kingdom was a machine that lived off the harvest.",
        "When the chroniclers write of the conquerors' “loot”, they",
        "easily forget that the real loot grew on the fields every year",
        "— and that it was brought in by people whose names no chronicler",
        "mentions.",
        '',
        "## The king's baptism",
        '',
        "Clovis's baptism was an event of the greatest importance for",
        "the courts. For a village in Gaul, at first hardly: people kept",
        "going to the springs and trees where their ancestors had laid",
        "down their offerings, celebrated the old festivals and asked",
        "for protection for livestock and harvest. The king's baptism",
        "only became perceptible in the course of generations — when the",
        "Church came to the village, built a chapel, installed a priest,",
        "reinterpreted the festivals and enforced the new names. What",
        "was an event from above was from below a slow change that",
        "dragged on over decades. And in some places both existed side",
        "by side for a long time: the Christian faith and the old",
        "customs the Church tried in vain to forbid.",
        '',
        '## The Church in the village',
        '',
        "And what did the Church bring the villages? First the dues —",
        "the tithe that fed the court and the priest. But not only that.",
        "The monastery or the bishop's church was often the only place",
        "that bought up surplus harvest, handed out grain in times of",
        "need and took in the sick. The church festivals gave the year",
        "its rhythm. And the ecclesiastical court was sometimes the only",
        "place where even a powerful man could be called to account.",
        "Comfort and control, protection and dues lay in the same hand —",
        "for the villages the Church was both, and the chroniclers who",
        "wrote for it told only the one side.",
        '',
        '## What makes this perspective different',
        '',
        "This perspective too is a reconstruction, and it must admit",
        "that: about the lives of most people we know frighteningly",
        "little. But the direction of the narrative changes the",
        "judgement. What the chronicles celebrate as rise and",
        "fulfilment — Clovis's baptism, Charles's coronation — was for",
        "the majority of people work, corvée and worry about the",
        "harvest. The “golden age” of the early kingdoms was for nine",
        "out of ten people no golden age but a hard life one tried to",
        "survive. The history of the powerful is not the history of the",
        "majority — it is only the one that was written down.",
      ].join('\n'),
    },
  ],

  // Synthesis (Round 9, jointly revised after Hermes added the view
  // from the villages).
  synthese: [
    "In the chapters before, the perspectives lay side by side on the",
    "map — Rome and China, Europe and Japan. Here they lie on top of",
    "each other: above and below in the same land, in the same week,",
    "often in the same village. One side had things written, the other",
    "ploughed. Whoever only reads the chronicles learns much about",
    "twenty families and almost nothing about nine out of ten people.",
    '',
    "**Where they meet:** Both perspectives see the same machine: the",
    "kingdoms were held together by retinue and Church. The chroniclers",
    "tell it from above — the baptisms, the coronations, the alliances.",
    "The villages experienced it from below — the dues, the corvée, the",
    "tithe, the new names. And both know: the kings usually could not",
    "write; the Church could. That is why the Church is the secret main",
    "character in both accounts — there as the support of the throne,",
    "here as the hand that reached into the village.",
    '',
    "**Where they diverge:** What was an event above was a change over",
    "generations below. Clovis's baptism: for the courts the power move",
    "that founded the realm; for the villages a distant occurrence that",
    "only became perceptible when the chapel came. The year 800: for",
    "the chroniclers the fulfilment — the return of the Empire; for",
    "the peasants a winter like any other. And the names: in the",
    "chronicles stand kings, bishops, queens — not a single peasant.",
    "The history of the powerful is not the history of the majority;",
    "it is only the one that was written down.",
    '',
    "**What follows from it:** Whoever knows the age only from above",
    "takes the chronicles for the whole story. The view of the courts",
    "betrays its own intentions if you read closely: it tells the",
    "baptism as a miracle and lets you see how useful it was; it calls",
    "kings by the grace of God and at the same time reports how these",
    "kings had their relatives killed. Contradictions in a source are",
    "not an annoyance — they are the place where you learn the most.",
    '',
    "**Your judgement begins here:** What makes a king a king:",
    "descent, baptism, power — or those who recognise him? And if only",
    "the reports of the powerful survive from an age: can one then",
    "know at all what it was like — and where would you look if you",
    "wanted to try anyway?",
  ].join('\n'),

  urteil: {
    frage: 'What makes a king a king: his descent, his baptism, his power — or those who recognise him? And who actually decides whose story about a kingdom gets told?',
    hinweis: 'There is no right and no wrong here. Three prompts: First, in 751 Pepin put the question to the pope whether he should be called king who has no power — think about what this question reveals about power before you answer it. Second, Clovis had himself baptised and thereby became acceptable to the bishops and the old Roman upper class; was that faith, calculation, or can it not be separated at all? Third, think of a group you know — class, club, team. Whoever has the say there usually has it not through strength alone. What else does it come down to?',
  },

  quiz: [
    {
      frage: 'Why was it so important that Clovis had himself baptised as a Catholic?',
      antworten: [
        'Because he was thereby the first Christian among the Germanic kings.',
        "Because the other kings were Christians too, but Arians — heretics for the Catholic population of Gaul and its bishops. Clovis was thus the only king behind whom the old Roman upper class could stand.",
        'Because the pope promised him land in Italy for it.',
      ],
      richtig: 1,
      erklaerung: "The baptism was a step of faith and a step of power at once. Others copied it: in 589 King Reccared gave up the Arian faith in Toledo for the Visigoths. Gregory of Tours tells Clovis's baptism as a miracle — even the year is uncertain, 496, 498 or 499.",
    },
    {
      frage: 'Who was Theodoric the Great?',
      antworten: [
        'A Roman emperor who defended Italy against the Goths.',
        'The last Western Roman emperor, deposed by Odoacer.',
        "The Ostrogothic king who ruled from Ravenna from 493 — with Roman officials, Roman law and a senate he let keep working. Formally he ruled in the name of the emperor in Constantinople.",
      ],
      richtig: 2,
      erklaerung: "His chancellor Cassiodorus formulated the programme: the Goths defend, the Romans administer. The attempt was seriously meant — and it did not hold to the end: in the end Theodoric had the scholar Boethius executed, who in prison wrote the “Consolation of Philosophy”.",
    },
    {
      frage: 'How did the new kingdoms manage to create an administration although the Roman one had fallen apart?',
      antworten: [
        "Through the Church: bishops knew Latin, law and bookkeeping, the church districts followed the Roman administrative districts, and writing lay in the monasteries.",
        'They built a completely new administration out of Germanic warriors.',
        'They did without administration and ruled solely through leading armies.',
      ],
      richtig: 0,
      erklaerung: "King and bishop needed each other: the one experts and an intercessor with God, the other protection and money. This becomes visible in the Lex Salica — the Franks had their own, ancient law written down, but in Latin and by scribes of the Church.",
    },
    {
      frage: 'What happened on 25 December 800 in Rome?',
      antworten: [
        'The pope declared the Western Roman Empire restored and made himself emperor.',
        "Pope Leo III placed a crown on the Frankish king Charles and had him proclaimed emperor — for the chroniclers the fulfilment, for Constantinople a presumption, because an emperor already sat there.",
        'Charlemagne conquered Rome and had himself elected emperor by the senate.',
      ],
      richtig: 1,
      erklaerung: "Einhard claims Charles was surprised and would not have entered the church otherwise — most historians regard that as diplomacy. Rome was then no longer a city of millions but a place with perhaps 25,000 people among ruins. The title nevertheless weighed more heavily than the city.",
    },
    {
      frage: 'Did the kings of this time write down their own history?',
      antworten: [
        'Yes, every royal court kept its own diary.',
        "No — bishops and monks wrote: Gregory of Tours about the Franks, Bede about the Anglo-Saxons, Einhard about Charlemagne. Most kings could not write.",
        'No, all the reports come from Constantinople.',
      ],
      richtig: 1,
      erklaerung: "That is why one reads these books like a letter whose sender one knows: each wrote for someone and with an intention. According to Einhard, Charlemagne tried to learn to write even as an old man and put writing tablets under his pillow — he no longer quite succeeded.",
    },
  ],
};

module.exports = koenigreiche;
