// Topic: From the Middle Ages to the Modern Age — the birth of Europe.
//
// Status: Round 10. For now contains ONLY the view of the old order
// (Voice: Opus). The voice of the cities and of the new beginning is added
// by Hermes; the synthesis below is explicitly preliminary and will be
// revised together afterwards (see CLAUDE.md, perspectives workflow).
//
// This is the first chapter of the early-modern arc
// (notizen/kapitel-planung.md): the bridge from Charlemagne to the eve of
// the Thirty Years' War. It links directly to "The Early Kingdoms" — there
// the story ended with the imperial coronation in 800; here it begins with
// it.
//
// The axis is a social one, as in the previous chapter, but it tilts: this
// voice belongs to the order that stood at the top — emperor, pope,
// nobility, monastery. It may explain its world without whitewashing it:
// the crusades are faith AND violence, the Church is comfort AND power,
// the estates order is a worldview AND a justification. No glorification,
// no demonisation.
//
// A content decision that belongs to the guiding idea of the app: the
// "dark Middle Ages" is treated here as an interpretation, not as a fact.
// The name was given by the humanists of the Renaissance — about an age
// they themselves had never experienced, and with the intention of making
// their own present look bright. Whoever has understood this has learned,
// from a harmless example, how the names of epochs carry judgements.
//
// The map is in karten/mittelalter.js — four states between 800 and 1618,
// and an arrow that runs out of the picture in 1492.
//
// Pure data — no UI imports (architecture rule).

const mittelalter = {
  id: 'mittelalter',
  titel: 'From the Middle Ages to the Modern Age — the birth of Europe',
  epoche: "From the imperial coronation of Charlemagne in 800 to the eve of the Thirty Years' War in 1618",

  aufhaenger: {
    frage: 'Eight hundred years that people call "dark" — and out of which come the universities, the cities, the cathedrals and the languages of Europe. Who actually gave this age its name, and what did he gain from it?',
    text: [
      "Imagine someone calls the years you spent in school",
      "\"the dark time.\" Not you. Someone who lives long after you, who",
      "was not there and who thinks that only with him did something better",
      "begin.",
      '',
      "That is exactly what happened to the Middle Ages. The people of that",
      "time never called themselves that — they would not have understood the",
      "word. \"Middle Ages\" means: the time in between. In between the",
      "Antiquity that was admired and the present that believed itself to be",
      "its rebirth. The name was invented by Renaissance scholars, more than",
      "a thousand years after its beginning. It is a judgement disguised as",
      "a period of time.",
      '',
      "And what actually lies in these eight hundred years? An emperor who",
      "stands barefoot in the snow before a castle. Armies that march to",
      "Jerusalem and there commit a bloodbath. A ship that brings a plague to",
      "Messina from which every third European dies. The first universities.",
      "Cathedrals on which three generations built. A workshop in Mainz where",
      "a single book suddenly becomes a thousand. And a monk who sends out a",
      "polemical treatise and with it splits the Church.",
      '',
      "Dark? Bright? First read how the world looked — and from the",
      "perspective of those who stood at the very top of it. Afterwards you",
      "may judge.",
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'alte-ordnung',
      name: 'The view of the old order',
      stimme: 'Opus',
      text: [
        "This is the story of the old order: of the emperors and kings, the",
        "popes and bishops, the nobility in their castles and the monks in",
        "their monasteries. It is the world that believed itself to be willed",
        "by God — and that experiences, in the course of these eight hundred",
        "years, how another world grows over its head.",
        '',
        "This voice has one advantage and one blind spot. The advantage: it",
        "knows its world from the inside and can explain why it was built the",
        "way it was. The blind spot: it takes this construction to be the",
        "natural order of things, because it itself sits at the top of it.",
        '',
        '## A world of oaths of fealty',
        '',
        "Charlemagne had become emperor in 800. His realm fell apart as early",
        "as under his grandsons — and what took its place was not a state in",
        "the modern sense, but a web of personal promises.",
        '',
        "The basic transaction was called **fief**. A lord gave a man land,",
        "together with the peasants who worked on it. In return the man became",
        "his vassal: he swore fealty, came with his knights when the lord went",
        "to war, and advised him when he was asked. These vassals in turn had",
        "vassals of their own, and those again had theirs.",
        '',
        "Why so complicated? Because there was nothing else. There was not",
        "enough money, no tax registers, no officials, no roads that carried",
        "commands quickly. A king could not pay anyone, so he paid with the",
        "only thing he had: with land. And because the land was then gone, he",
        "constantly needed new land.",
        '',
        "The built-in flaw soon shows itself. Whoever held a fief long enough",
        "came to regard it as property and bequeathed it to his son. In this",
        "way the servant became a competitor. The whole history of the German",
        "emperors can be read as a fight against this arithmetic — and they",
        "lost it: in the end there was no strong kingship as in France or",
        "England, but a realm of hundreds of princes who could do as they",
        "pleased. In 1618 that will take its revenge.",
        '',
        '## Those who pray, those who fight, those who work',
        '',
        "How do you explain to people why the world is the way it is? You",
        "declare it God's plan. Around 1030 a bishop named Adalbero put the",
        "order into three words: there are those who pray, those who fight,",
        "and those who work. Each estate serves the others; none can exist",
        "without the others.",
        '',
        "That sounds peaceful, and it has a catch you see at once: of the",
        "three estates, one worked — and it made up over ninety percent of",
        "the people. The division does not only explain the world, it also",
        "justifies it. Whoever stands at the very bottom does not stand there",
        "because of some injustice, but because God arranged it so. Remember",
        "that: it is the most comfortable idea the powerful ever had.",
        '',
        "The daily life of this order was the **manorial system**. A peasant",
        "received land, protection and a court; in return he handed over part",
        "of the harvest and worked days each year for his lord. Usually he was",
        "not free — he was not allowed simply to move away or marry whom he",
        "wanted. But he was not a slave either: he had rights, and he could",
        "enforce them in court.",
        '',
        "The monasteries belonged to the same order, and they were more than",
        "houses of prayer: the largest landowners, the best farmers, the only",
        "libraries, the only hospitals, the only schools. If you could read in",
        "the year 1100, you were most likely a clergyman.",
        '',
        '## Two swords: emperor and pope',
        '',
        "And now comes the conflict that shaped Europe like no other — and",
        "that did not take place like this anywhere else in the world.",
        '',
        "The Church's teaching knew two swords, a spiritual and a secular one:",
        "the pope for the souls, the emperor for the bodies. As long as both",
        "wanted the same thing, it went well. The quarrel broke out at the",
        "most sober point one can imagine — over the question of who may",
        "appoint the bishops.",
        '',
        "For the emperor that was not a question of faith but of survival:",
        "bishops administered half countries, raised troops and, unlike",
        "counts, could not pass their offices on by inheritance. Whoever",
        "appointed them, ruled.",
        '',
        "In January 1077 Emperor **Henry IV** stood for three days in a",
        "penitent's robe before the castle of **Canossa**, where Pope Gregory",
        "VII was staying, and asked for the lifting of his excommunication. He",
        "received it. \"The walk to Canossa\" is to this day a proverb for the",
        "deepest humiliation.",
        '',
        "But it was not that simple. The ban had released Henry's vassals from",
        "their oath of fealty — that is why he had to get rid of it, and that",
        "is why he went. Hardly free, he gathered an army, marched to Italy",
        "and installed a pope of his own; Gregory died in exile. Humiliation",
        "and tactical move at once. The dispute was only ended in 1122 with a",
        "compromise, the Concordat of Worms.",
        '',
        "The consequence reaches into our own time. From then on there were",
        "two powers in Europe, neither of which could swallow the other.",
        "Whoever was at odds with one could turn to the other. Out of this",
        "permanent conflict grew the separation of spiritual and secular",
        "power — not out of insight, but because neither side prevailed.",
        '',
        '## "God wills it" — the crusades',
        '',
        "In 1095 Pope Urban II called at Clermont to help the Christians in",
        "the East and to liberate Jerusalem. The crowd is said to have",
        "answered: \"God wills it!\" Whoever joined had his sins forgiven.",
        '',
        "From the point of view of the old order this was a masterstroke: the",
        "pope now wielded the sword that had actually belonged to the emperor.",
        "And the knights, who endlessly waged feuds in their own country,",
        "finally had an enemy who was not their neighbour.",
        '',
        "What followed must be allowed to stand in the same story in which one",
        "lets the faith stand. Already on the way, in the Rhineland, crusader",
        "bands murdered Jewish communities — the first great pogroms of",
        "Europe. On 15 July 1099 they took Jerusalem and carried out a",
        "bloodbath among Muslims and Jews about which even their own",
        "chroniclers wrote with horror. In 1187 **Saladin** won the city back",
        "and let the inhabitants depart against ransom; in the West he was",
        "admired for it centuries later. In 1204 a crusade no longer went to",
        "the Holy Land at all, but to Constantinople: a Christian army",
        "plundered a Christian city because otherwise the crossing could not",
        "be paid for. In 1291 Acre, the last stronghold, fell. After barely",
        "two hundred years everything was lost.",
        '',
        "What remained was what nobody had planned. Through the contacts came",
        "goods, methods of calculation, medical knowledge and ancient texts to",
        "Europe — much of it translated from Arabic, which in turn had",
        "preserved the Greeks. And the experience remained that beyond the",
        "horizon lay a world richer than one's own.",
        '',
        '## When the order tore: the plague',
        '',
        "Around 1300 more people lived in Europe than ever before. Then came",
        "the catastrophe, and it came along the trade routes: in 1347 an",
        "epidemic broke out in Kaffa on the Crimea, in October the ships",
        "entered Messina, in winter Genoa and Marseille, in summer 1348 it",
        "was in Paris, in autumn in London. Within five years about **one",
        "third** of the people of Europe died, in some cities half.",
        '',
        "Nobody knew the cause. People suspected foul air, a punishment from",
        "God, a constellation of the stars — and they looked for the guilty.",
        "In 1348 and 1349 the Jewish communities were accused in dozens of",
        "cities of having poisoned the wells, and were murdered; in Strasbourg",
        "that happened before the epidemic had even arrived there.",
        '',
        "For the old order the plague was an earthquake. Where a third of the",
        "workers is missing, work suddenly becomes valuable: the survivors",
        "demanded higher wages and fewer dues, and whoever did not get it,",
        "moved away. Lords and kings tried to cap wages by law — it did not",
        "help. In England and France great uprisings broke out. From here on",
        "the matter-of-factness with which everyone stayed in his place",
        "crumbles.",
        '',
        "On top of that came the long war: from 1337 to 1453 England and",
        "France fought over the French crown. In it the ideal of the knight",
        "also went under — at Crécy and Agincourt English longbowmen shot the",
        "French cavalry to pieces. And in the middle of this war a peasant",
        "girl from Lorraine led an army: **Joan of Arc**, at seventeen. Two",
        "years later she was burned as a heretic; a later trial acquitted",
        "her, and today she is a saint.",
        '',
        '## Three numbers that change everything',
        '',
        "At the end of this age stand three dates that belong together more",
        "closely than it looks.",
        '',
        "**Around 1450, Mainz.** Johannes Gutenberg puts together what had",
        "long existed separately: movable metal type, a press and an ink that",
        "holds on metal. Before, a monk spent months writing one book; now",
        "hundreds of identical copies come into being. Fifty years later",
        "there are millions of books in Europe. For the first time in history",
        "a thought can travel faster than the human being who has it.",
        '',
        "**1453, Constantinople.** Sultan Mehmed II takes the city; the",
        "Eastern Roman Empire, which in the earlier chapters of this app was",
        "still standing when everything in the West had long since fallen",
        "apart, comes to an end after almost eleven hundred years. Greek",
        "scholars flee with their manuscripts to Italy and bring Antiquity",
        "with them. And the land route to the East now lies in Ottoman hands —",
        "whoever wants spices must look for a sea route.",
        '',
        "**1492, Spain.** In a single year Granada falls, the last Islamic",
        "kingdom of the peninsula; the Jews are expelled from Spain, many of",
        "them families who had lived there for a thousand years; and Columbus",
        "sails west to reach India. The three events belong together: the",
        "same rulers, the same conviction of being in the right. What came of",
        "the voyage is told in the next chapter.",
        '',
        '## Who invented the "dark Middle Ages"?',
        '',
        "Around the same time Italian scholars look back and rediscover",
        "Antiquity — books, architectural forms, sculpture. They call their",
        "own time a rebirth, a **Renaissance**. And because between the",
        "admired Antiquity and themselves there lay a thousand years, they",
        "needed a name for these years. They called them the time in between:",
        "the **Middle Ages**. The poet Petrarch already spoke in the 14th",
        "century of the darkness that had come after.",
        '',
        "Pause here for a moment. The name of this epoch comes from people",
        "who did not experience it and had an interest in making their own",
        "time look bright. It is advertising on one's own behalf — and it has",
        "worked, to this day.",
        '',
        "What the name conceals: in these centuries came into being the",
        "universities (Bologna 1088, Paris, Oxford), the Gothic cathedrals",
        "with their engineering and their light, the eyeglasses, the",
        "mechanical clock, paper, three-field crop rotation, the horse",
        "collar, with which a horse can pull without choking — and the",
        "languages in which Europe speaks today. The population grew between",
        "1000 and 1300 to about double. That is not a society standing",
        "still.",
        '',
        "And what the name also conceals: some things people like to ascribe",
        "to the Middle Ages do not belong there at all. The great witch",
        "hunts did not take place in the dark Middle Ages, but between 1560",
        "and 1630 — that is, in the modern age, in the time of printing,",
        "universities and science. The notion that people then thought the",
        "earth was flat is also wrong: that it is a sphere was known to every",
        "educated person since Antiquity; what people argued about was its",
        "size.",
        '',
        "None of this makes the age bright. There was hunger, epidemics,",
        "unfreedom, burnings of heretics and pogroms. The claim is a",
        "different one: whoever dismisses an entire epoch with a single word",
        "has spared himself the thinking.",
        '',
        '## The split',
        '',
        "In 1517 the monk **Martin Luther** turned in Wittenberg against the",
        "trade in indulgences — against the promise that one could buy off",
        "punishments in the afterlife with money. For the old order this was",
        "at first a quarrel among theologians. It had overlooked what had",
        "changed in the meantime: the printing press existed. Luther's theses",
        "were all over the realm within a few weeks, his pamphlets appeared",
        "in the hundreds of thousands.",
        '',
        "What followed was not only a conflict of faith. Princes who adopted",
        "the new teaching could confiscate church property and became masters",
        "of their own church — faith and calculation ran side by side. In",
        "1525 the peasants rose up and invoked Luther in doing so; Luther",
        "himself called for their suppression. Tens of thousands died.",
        '',
        "In 1555 the first round ended with the Peace of Augsburg, and the",
        "formula they agreed on says everything about this order: **cuius",
        "regio, eius religio** — whose the land, his the religion. It was not",
        "the individual who decided which confession he followed, but his",
        "territorial lord. Whoever believed differently was allowed to",
        "emigrate. For the time that was progress, and it shows at the same",
        "time how this world thought.",
        '',
        "The peace held for a good sixty years. In 1618 the imperial",
        "governors were thrown out of a window in Prague, and the quarrel",
        "that 1555 had silenced broke out as a war that was to last thirty",
        "years. With that this chapter ends — and the next one begins.",
        '',
        '## And the other side?',
        '',
        "Everything you have just read is told from above: from the imperial",
        "palaces, the bishop's sees, the monasteries and the castles. It is",
        "the world of the order that believed itself to be willed by God.",
        '',
        "But in the same centuries something else grew up between the",
        "castles, something that occurs in this story at most at the margins:",
        "the **cities**. Merchants who travelled on their own account.",
        "Craftsmen in guilds. Councils that governed themselves. The saying",
        "\"city air makes free\" meant literally that a runaway unfree person",
        "was free after a year and a day in the city — that is a hole in the",
        "estates order, and right in the middle of it. On top of that the",
        "universities, the printers, the bankers, the reformers.",
        '',
        "These questions the old order cannot answer: What does this age look",
        "like when you view it not from the throne but from the market? Where",
        "did the money come from that in the end paid for the princes' wars —",
        "and what did those who had it demand in return? Why did the new",
        "ideas arise almost all of them in cities? And was what the old",
        "order experienced as decay, seen from below, perhaps a new",
        "beginning?",
        '',
        "They belong to a second voice.",
      ].join('\n'),
    },
    {
      id: 'staedte',
      name: 'The voice of the cities and of the new beginning',
      stimme: 'Hermes',
      text: [
        "This view tells the story of those who stood neither at the very top",
        "nor at the very bottom: of citizens, merchants, craftsmen, students,",
        "printers and reformers — the people in the cities. They wrote no",
        "chronicles about kings, but they kept account books, building",
        "records, guild regulations and university registers. And they left",
        "behind the houses that still stand today. From their point of view,",
        "what the old order experienced as decay was a new beginning — the",
        "start of something new.",
        '',
        '## City air makes free',
        '',
        "The city was the place where the old order did not apply. Whoever",
        "moved into a city became free after a year and a day — \"city air",
        "makes free,\" it was said. Here it was not birth that counted but",
        "ability: a craftsman could gain respect through his work, a merchant",
        "wealth through his skill. The guilds regulated who was allowed to",
        "produce what — but they regulated it among equals, not from above.",
        "And the city had its own courts, its own walls, its own rights. For",
        "a peasant who had fled the manorial system, the city was the promise",
        "of a life one determined oneself.",
        '',
        '## The money the lords needed',
        '',
        "The princes built castles, waged wars and kept courts — and all of",
        "it cost money they did not have. Their land they had long since",
        "granted to vassals; what remained were the cities. The merchants",
        "gave credit, the cities paid taxes, and in return they negotiated:",
        "about rights, about tolls, about self-determination. The king of",
        "France, the English king, the German princes — they all needed the",
        "money from the cities, and whoever gives money gets a say. The city",
        "league of the Hanse dominated the trade of the Baltic and the North",
        "Sea without ever being a kingdom.",
        '',
        '## The new ideas grow between the houses',
        '',
        "And why did the new ideas arise almost all of them in cities?",
        "Because that is where the people came together who had something to",
        "say to one another: scholars who moved from university to",
        "university, merchants who brought news from all over the world,",
        "craftsmen who developed techniques further. Bologna, Paris, Oxford —",
        "the first universities were urban institutions, not princely",
        "privileges. Whoever could read and calculate found his place in the",
        "city; in the countryside both were useless.",
        '',
        '## Printing: the world becomes reproducible',
        '',
        "Around 1440 Gutenberg developed printing with movable type in Mainz.",
        "That sounds technical — it was a revolution. Until then, knowledge",
        "was what monks copied out in monasteries; now a single book could",
        "suddenly become a whole edition. The ideas left the libraries and",
        "went out into the streets. Without printing the Reformation would",
        "have been unthinkable: Luther's writings were printed in thousands",
        "of copies and spread everywhere within weeks — the first mass",
        "communication of history. The old order, which rested on the",
        "monopoly of knowledge, lost control over what people read.",
        '',
        '## The Reformation: the new beginning becomes irreversible',
        '',
        "And the Reformation itself was also an urban movement. The imperial",
        "cities and the citizens stood behind the reformers — against the",
        "payments to Rome, for a faith one could understand oneself, in one's",
        "own language. The Peace of Augsburg of 1555 gave the princes the",
        "right to determine the confession — but the ground for it had been",
        "prepared by the cities in which the new ideas first took root. What",
        "the old order fought as heresy and decay was, seen from below, the",
        "freedom to think for oneself.",
        '',
        '## What makes this view different',
        '',
        "This view is just as much a story as that of the courts — but its",
        "direction is the opposite. Where the old order saw the downfall of",
        "a God-willed world, it sees the growth of a new one: the freedom,",
        "the money, the knowledge, the press. The modern age was not made by",
        "kings — it came into being in the cities, between market square,",
        "guild hall and printing press. And it has given the word that the",
        "Renaissance found for the time before it, validity to this day:",
        "\"dark Middle Ages.\" From the point of view of the cities, this age",
        "was rather the birth of what we call Europe.",
      ].join('\n'),
    },
  ],

  // Synthesis (Round 10, jointly revised after Hermes added the voice of
  // the cities and of the new beginning).
  synthese: [
    "This chapter is about a transition — and transitions look opposite",
    "from above and from below. What appeared to the old order as decay —",
    "peasants who move away; cities that have their own courts; princes",
    "who break away from the pope; books that everyone can read — was for",
    "the others precisely the gain. The same years, the same events, two",
    "opposite words for them.",
    '',
    "**Where they meet:** Both views see the same world: the order of",
    "fiefs and oaths of fealty, the estates, the Church as a power. And",
    "both see that the change was unstoppable — the old order laments it,",
    "the cities welcome it. Both also know: the money came from the",
    "cities, and the new ideas grew between the houses. What separates",
    "them is not the observation but the interpretation.",
    '',
    "**Where they part ways:** \"Decay\" or \"new beginning\" — that is",
    "the whole difference. The old order saw God's plan falling apart,",
    "the cities saw freedom growing. The crusades: a march of faith or",
    "the beginning of trade and exchange? The plague: a punishment from",
    "God or the moment in which work became scarce and expensive? The",
    "Reformation: heresy or the right to think for oneself? And the word",
    "that sums it all up — \"dark Middle Ages\" — is not an observation",
    "but a judgement: given by humanists who had not experienced this",
    "age and had an interest in making their own time look bright.",
    '',
    "**What follows from it:** Whoever gives the names has already",
    "interpreted — that is the guiding idea of this app, and this chapter",
    "is its most beautiful example: a whole millennium is called to this",
    "day what its critics called it. The old order betrays itself in its",
    "own justifications — it declares the estates order to be God's",
    "plan, and one sees whom this plan benefits. The cities betray",
    "themselves in their faith in progress — in the new beginning they",
    "see only the growth and little of what was lost. Neither of the two",
    "views lies; both are a selection.",
    '',
    "**Your judgement begins here:** Which words do you yourself use for",
    "whole ages or groups — and whose judgement do you repeat with them?",
    "And: how would someone in five hundred years name our present — and",
    "on what would he base that?",
  ].join('\n'),

  urteil: {
    frage: 'Was the Middle Ages really "dark" — or is that a prejudice the Renaissance left behind and that we have been repeating for five hundred years? And which images of past times does our own age take for granted that might be judgements just the same?',
    hinweis: 'There is no right or wrong here. Three starting points: First, check who gave the name — the people of this age never called themselves "medieval"; the term comes from scholars who lived a thousand years later and celebrated their own time. Second, hold both side by side: universities, cathedrals, eyeglasses and clock on the one hand, plague, unfreedom and pogroms on the other — and ask yourself whether a single word can possibly suffice for eight hundred years. Third, turn it around: how would someone in five hundred years name our present, and on what would he base that?',
  },

  quiz: [
    {
      frage: 'What happened in 1077 at Canossa?',
      antworten: [
        'The pope submitted to the emperor and gave up the appointment of bishops.',
        "Emperor Henry IV stood as a penitent before the castle where Pope Gregory VII was staying and achieved the lifting of his excommunication.",
        'Emperor and pope concluded the first crusade treaty.',
      ],
      richtig: 1,
      erklaerung: "It was about the question of who may appoint the bishops — for the emperor a question of power, for bishops administered half countries. The walk to Canossa was humiliation and tactical move at once: Henry was rid of the ban, came back with an army and installed a pope of his own. The dispute was only ended in 1122 in the Concordat of Worms.",
    },
    {
      frage: 'What was the Black Death?',
      antworten: [
        'A famine that hit Europe between 1315 and 1317.',
        "A name for the Hundred Years' War between England and France.",
        "The plague of 1347 to 1353 — it came via the trade routes from the Crimea to Europe, and about a third of the people died.",
      ],
      richtig: 2,
      erklaerung: "The epidemic followed exactly the routes on which pepper and silk had come before: Kaffa, Messina, Genoa, Marseille, Paris, London. Because nobody knew the cause, people looked for the guilty — in 1348/49 the Jewish communities were accused and murdered in many cities. After that work was scarce and therefore valuable: the survivors demanded higher wages.",
    },
    {
      frage: 'Who in Europe was the first to print with movable metal type?',
      antworten: [
        'Johannes Gutenberg in Mainz, around 1450.',
        'Martin Luther in Wittenberg, 1517.',
        'The monks of the monastery of Cluny, in the 11th century.',
      ],
      richtig: 0,
      erklaerung: "Gutenberg combined movable type, a press and a durable printing ink. Fifty years later there were millions of books in Europe. Without this workshop Luther's polemical treatise of 1517 would have found few readers — with it, it was all over the realm within two weeks. In East Asia, by the way, printing had already been done earlier.",
    },
    {
      frage: 'What does the formula "cuius regio, eius religio" of 1555 mean?',
      antworten: [
        'Every person may choose for himself which confession he follows.',
        "The territorial lord determines the confession of his land — whoever believes differently may emigrate.",
        'The emperor determines the confession for the whole realm.',
      ],
      richtig: 1,
      erklaerung: "\"Whose the land, his the religion.\" The Peace of Augsburg ended the first round of the religious wars — for the time a progress, and at the same time the formula shows how this order thought: decisions were made at the top. The peace held for a good sixty years; in 1618 the Thirty Years' War began.",
    },
    {
      frage: 'Where does the term "dark Middle Ages" come from?',
      antworten: [
        'From the people of the Middle Ages themselves, who experienced their time as dark.',
        'From the scholars of the Renaissance, who admired Antiquity and devalued the thousand years in between — the term is a judgement, not a period of time.',
        'From historians of the 20th century who investigated the plague.',
      ],
      richtig: 1,
      erklaerung: 'Nobody in the Middle Ages would have called himself "medieval" — the word means "the time in between" and comes from people who wanted their own present to look bright. Two tests of the matter: the great witch hunts took place only between 1560 and 1630, that is, in the modern age. And that the earth is a sphere was known to every educated person in the Middle Ages.',
    },
  ],
};

module.exports = mittelalter;
