// Topic: The Roman Empire — rise, order, decline.
//
// English translation of the German module (utils/themen/roemisches-reich.js).
// Status: Round 1. Contains the European perspective (voice: Opus).
// The Chinese perspective is provided by Hermes; the synthesis is then
// revised jointly (see CLAUDE.md, perspectives workflow).
//
// Pure data — no UI imports (architecture rule).
//
// Note: unlike the German module, this English version has no `karte`
// (map) field — the map module was not translated, and the app simply
// skips the map section for topics without one.

const roemischesReich = {
  id: 'roemisches-reich',
  titel: 'The Roman Empire',
  epoche: 'Antiquity — from the founding of the city (traditionally 753 BC) to the end of the Western Roman Empire in 476 AD',

  aufhaenger: {
    frage: 'An empire that spanned half of Europe — how do you hold something like that together without telephones, without the internet, without cars?',
    text: [
      'Imagine you are put in charge of a territory that stretches from Scotland',
      'to the Sahara, and from Portugal to Iraq. An order from your',
      'capital takes weeks to reach the far edge. The people there',
      'speak dozens of languages, pray to different gods, and have',
      'never once laid eyes on one of your officials.',
      '',
      'That is exactly what the Romans did — and it worked for centuries.',
      'How? And why did it eventually stop working? That is the really',
      'fascinating question. The dates are just signposts along the way,',
      'not the main event.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'The European View',
      stimme: 'Opus',
      text: [
        'This is how the story of Rome is told in Europe — in schoolbooks, in',
        'museums, in films. It is the story of the heirs: Europe sees in Rome',
        'its own beginning. That colours the story, and it is worth',
        'keeping that in mind as you read.',
        '',
        '## From a village to a world empire',
        '',
        'Rome starts small. A few hills at a ford across the Tiber, farmers,',
        'cattle dealers, quarrels with the neighbours. Nothing hints that',
        'an empire will one day be ruled from here.',
        '',
        'The first turning point: the Romans drive out their king and turn',
        'Rome into a republic — a "public affair" (res publica). Instead of a',
        'ruler there are elected officials who hold office for just one year,',
        'and the Senate, the assembly of the influential families. The Romans',
        'are so proud of this that they put it on their standards: SPQR —',
        '"the Senate and People of Rome". To this day it appears on',
        'Roman manhole covers.',
        '',
        'Then Rome grows. First across Italy, then beyond. Its great',
        'rival is Carthage, the trading power of North Africa. For three wars',
        'the outcome swings back and forth — Hannibal even marches war',
        'elephants over the Alps and defeats the Romans decisively several times.',
        'Rome loses battle after battle and still wins the war, because it can',
        'replace its losses and refuses to give up. In the end Carthage lies in',
        'ruins, and the Mediterranean is a Roman lake. The Romans simply call it',
        '"mare nostrum" — our sea.',
        '',
        'Success nearly tears the republic apart. Victorious commanders like',
        'Caesar have armies that are loyal to them personally, not to the state.',
        'Civil wars follow. In the end Augustus prevails — officially only "the',
        'first citizen", in truth the first emperor. The republic survives as a',
        'backdrop, while power lies with one man.',
        '',
        '## How do you hold it together?',
        '',
        'This is where it gets interesting, because Rome did not just conquer —',
        'plenty of people could do that. Rome knew how to keep. Four things mattered:',
        '',
        '**The roads.** Roughly 80,000 kilometres of paved roads criss-cross',
        'the empire, dead straight over hills and through swamps. They were built',
        'not for traders but for the army: a legion had to get anywhere fast.',
        'But where soldiers can march, so can goods, letters, ideas and',
        'diseases travel. The roads bound the empire together — and some are',
        'still in use today.',
        '',
        '**The army.** The legions were not ragtag mobs,',
        'but professional soldiers with the same equipment, the same drill and',
        'the same camp layout from Britain to Syria. They did not only fight,',
        'they built: roads, bridges, frontier fortifications, entire cities. From',
        'legionary camps grew Cologne, Bonn, Vienna and London.',
        '',
        '**The law.** For the European story this is the most important',
        'point. The Romans wrote their laws down and displayed them publicly',
        'so that anyone could read them. They developed rules for',
        'contracts, property, inheritance and debt that were so well thought out',
        'that lawyers still study them today. Some of it survives almost',
        'unchanged in the German Civil Code.',
        '',
        '**Citizenship.** Perhaps Rome\'s smartest move. The conquered',
        'did not stay defeated forever: you could become a Roman citizen —',
        'as a soldier after 25 years of service, as a city by grant. In 212 AD',
        'almost all free inhabitants of the empire received citizenship. A',
        'North African could become emperor, and so could a Spaniard. The empire',
        'was held together not by origin but by belonging.',
        '',
        'Add something inconspicuous: peace. For about two centuries it was',
        'largely quiet at home — the Romans called it "pax Romana",',
        'the Roman peace. You could travel from Trier to Alexandria',
        'without crossing a single border, and pay everywhere with the same',
        'coins. Quite a few people in the empire thought that was good. Others',
        'saw in it above all the quiet that follows a conquest.',
        '',
        '## What Rome changed',
        '',
        'Speak English and you are speaking some Latin: wall, street, cellar,',
        'wine, church, school — all from Latin. Italian,',
        'Spanish, French, Portuguese and Romanian grew directly out of',
        'spoken Latin. The months July and August',
        'carry the names of Caesar and Augustus. Our calendar goes back to the',
        'Roman one. And Christianity, at first persecuted in the empire, became',
        'eventually its state religion — and via the Roman roads and',
        'cities the religion that shaped Europe.',
        '',
        '## Why did it come to an end?',
        '',
        'One single date is often quoted: 476 AD, when the last',
        'Western Roman emperor was deposed. A boy named Romulus Augustulus',
        'hands over his insignia, and nobody makes much of a fuss. No',
        'contemporary thought that day: "Now antiquity is over."',
        '',
        'The real process stretched over centuries, and the explanations',
        'for it contradict each other to this day:',
        '',
        '- The empire had grown too large to be ruled from one place — it',
        '  was split into a western and an eastern half.',
        '- Emperors were raised up and toppled by their own troops; in',
        '  the crisis years of the 3rd century, rulers changed on',
        '  average almost every year.',
        '- Epidemics and crop failures hit the population, the tax burden grew,',
        '  money lost its value.',
        '- Peoples pressed across the borders from the north and east —',
        '  sometimes as attackers, sometimes as refugees fleeing the Huns,',
        '  sometimes as hired soldiers. In the end Rome was defended by',
        '  forces that were "barbarians" themselves.',
        '',
        'And then there is the question of whether "fall" is even the right',
        'word. The eastern half of the empire, with its capital Constantinople,',
        'lasted almost a thousand years longer — its inhabitants naturally',
        'still called themselves Romans. And in the West, Roman law,',
        'the Roman language and the Roman church simply carried on',
        'under new rulers. Perhaps Rome did not fall so much as transform.',
        '',
        '## Why Europe tells the story this way',
        '',
        'For Europe, Rome has never been just the past, but always also',
        'a claim. Charlemagne had himself crowned Roman emperor. The',
        'Holy Roman Empire carried the name in its title for a thousand years.',
        'The tsars and the kaisers named themselves after Caesar. Napoleon had',
        'himself portrayed as a Roman general, and anyone looking at American',
        'government buildings sees Roman columns.',
        '',
        'Those who claim an ancestor rarely tell his story',
        'dispassionately. That is why Rome in European books often sounds like',
        'order, law and progress — and less often like what conquest meant for',
        'the conquered: destroyed cities, forced tribute, enslaved',
        'people. The Roman historian Tacitus put these words into the mouth',
        'of a British chieftain: "They',
        'make a desert and call it peace."',
        '',
        'That is the point where another perspective can begin. Because at the',
        'same time, at the other end of the Silk Road, there was an empire just',
        'as large, and hardly anyone in Europe talks about it.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'The Chinese View',
      stimme: 'Hermes',
      text: [
        'This perspective does not tell the story from Rome but from the East —',
        'from the standpoint of Chinese historiography, which observed Rome',
        'from afar. It, too, is just one narrative — but one with',
        'different questions and different words.',
        '',
        '## Da Qin — the distant empire at the end of the Silk Road',
        '',
        'China knew of Rome long before Europeans knew of China. In',
        'the imperial annals the Roman Empire is called "Da Qin" — the',
        'great Qin. Chinese chroniclers described it as a land',
        'at the other end of the world, rich in glass and gold, whose people',
        'were said to be honest in trade. For hundreds of years the',
        'Silk Road ran: silk woven in China clothed Roman',
        'emperors and senators — in Rome silk was so coveted that some weighed',
        'it against gold, and the Senate even debated a ban on wearing it.',
        '',
        'From the Chinese point of view, Rome was therefore never the centre',
        'of the world, but the western end of a trade route. That alone makes',
        'a difference: the European narrative begins with Rome and',
        'looks outward. The Chinese narrative looks at China — and',
        'Rome appears in it as a distant, respected trading partner on the',
        'horizon.',
        '',
        '## Two empires, one pattern',
        '',
        'At the same time that Rome was rising, the Han Empire was growing',
        'at the other end of the Silk Road — about the same size, about the',
        'same population. The two empires split the world almost in half, and',
        'both knew the same problems: enormous distances, many',
        'peoples, unrest on the borders. The Han dynasty held its empire',
        'together with officials chosen by examination, with roads and with',
        'the trading network of the Silk Road — much like Rome, only with',
        'different tools.',
        '',
        'The end is similar, too: the Han Empire fell apart in the year 220 AD,',
        'just a few decades before Rome slid into its great crisis. From',
        'a Chinese perspective that is no coincidence but a familiar',
        'pattern. Chinese historiography tells rule as a',
        'cycle: a dynasty founds an empire, brings order and',
        'prosperity, then grows weaker — through corruption, civil wars,',
        'crop failures — and finally loses the "Mandate of Heaven".',
        'Then a new dynasty emerges from the chaos, and the cycle',
        'begins again.',
        '',
        '## The Mandate of Heaven',
        '',
        'The "Mandate of Heaven" is the key to this perspective. It',
        'says: rule is not simply possession but a loan — and',
        'it lasts only as long as the ruler governs well. When the people',
        'suffer, when offices are sold, when peasants can no longer pay',
        'their taxes, then Heaven withdraws its mandate, whether anyone',
        'notices or not. The collapse then does not come suddenly;',
        'it is only the end of a long, visible weakness.',
        '',
        'Seen from here, Rome\'s fall was no tragedy and',
        'no mystery, but a familiar chapter: a great empire that',
        'had grown too big and too costly, whose emperors fought',
        'each other, whose offices were sold — an empire that fulfilled',
        'the signs of a lost mandate. The Chinese view does not so much ask',
        '"Why did Rome fall?" as "Which signs were',
        'visible long before?" — the same question Chinese',
        'chroniclers ask of their own dynasties.',
        '',
        '## What makes this view different',
        '',
        'Two differences stand out when you put the narratives',
        'side by side.',
        '',
        'First: Europe tells Rome\'s end as a great rupture — the',
        'end of a world. The Chinese view knows no single',
        'fall, but patterns: empires die, but civilisations',
        'carry on. After the Han Empire came the Three Kingdoms, then',
        'new dynasties that invoked the legacy of the Han. In this view, Rome',
        'did not "end the world" but is one empire among',
        'many in the cycle of empires.',
        '',
        'Second: the Chinese narrative marvels at how much',
        'Europe makes Rome its own beginning. In China, one\'s own',
        'history counts as central — the Han Empire, the Silk Road,',
        'paper and silk. That Europe seeks its roots in Rome while',
        'the China of the same era barely appeared in European books for a',
        'long time is, from this perspective, itself worth a story: whoever',
        'tells world history selects — and what gets selected depends',
        'on who is telling.',
        '',
        'This is not a correction of the European view. It is a second',
        'narrative with its own questions: what if world history',
        'did not begin in Rome but at both ends of the Silk Road',
        'at once?',
      ].join('\n'),
    },
  ],

  synthese: [
    'Now the two perspectives stand side by side — and you can already see',
    'how the same story changes depending on where you look from.',
    '',
    '**Where they meet:** Both narratives describe Rome as an',
    'empire that brought order and stability to a vast area —',
    'the European one with roads, law and citizenship, the Chinese one',
    'with the view from outside on an empire that mastered its borders',
    'and its peoples. Both know the tension between the centre and the',
    '"barbarians" at the edges — the Germanic peoples north of Rome, the',
    'Xiongnu north of China. And both narratives come from people who',
    'belong to the heirs or successors of the empires they describe:',
    'victors and scribes.',
    '',
    '**Where they diverge:** The European view makes Rome its',
    'own beginning — law, language, calendar and church all trace back to',
    'Rome, and its end is told as a great rupture. The',
    'Chinese view knows Rome as a distant trading partner at the end of',
    'the Silk Road ("Da Qin") and fits rise and fall into a',
    'familiar pattern: the Mandate of Heaven that a dynasty',
    'receives and loses. What is a one-time',
    'fall for one narrative is for the other a chapter in a cycle that',
    'China itself went through several times.',
    '',
    '**The choice of words reveals the perspective:** "Fall" or "transformation"?',
    '"Legacy" or "distant trading partner"? "Centre of the world" or',
    '"end of a trade route"? Same events — different words,',
    'different story. This is exactly where your own judgement begins:',
    'which narrative speaks to you more, which questions does it leave',
    'open — and what answer would you give to a third person who is at',
    'home neither in Rome nor in China?',
  ].join('\n'),

  urteil: {
    frage: 'Rome brought roads, law and peace — and at the same time destroyed cities, exacted tribute and enslaved people. In your opinion, was the Roman Empire more of a gain or more of a loss for the people who lived in it? And does it depend on whom you ask?',
    hinweis: 'There is no right or wrong here. Simply name two or three reasons for your view — and consider whether a Roman senator, an enslaved woman and a Germanic peasant would give the same answer.',
  },

  quiz: [
    {
      frage: 'Is it true that Rome was always ruled by emperors?',
      antworten: [
        'Yes, from its founding to its end.',
        'No — before that, Rome was a republic with elected officials for about 500 years.',
        'No — Rome was always ruled by priests.',
      ],
      richtig: 1,
      erklaerung: 'The imperial era is only the second half of the story. Before that, the Senate and elected officials who each stayed in office for just one year ruled — the republic. Augustus only became the first emperor in 27 BC.',
    },
    {
      frage: 'What were the famous Roman roads primarily built for?',
      antworten: [
        'For traders, so trade could flourish.',
        'For travellers and holiday traffic.',
        'For the army, so troops and messages could get anywhere quickly.',
      ],
      richtig: 2,
      erklaerung: 'It was first of all a military necessity: if you want to hold a vast empire together, you must be able to move soldiers quickly. That traders, letters and ideas used the same roads was a very effective side effect.',
    },
    {
      frage: 'Could someone who was not born in Rome become a Roman citizen?',
      antworten: [
        'Yes — citizenship was granted, and from 212 AD even to almost all free inhabitants of the empire.',
        'No, only those born in the city of Rome.',
        'Only people from Italy could get it.',
      ],
      richtig: 0,
      erklaerung: 'That was one of Rome\'s smartest moves: the conquered could belong instead of remaining defeated forever. Soldiers received citizenship after their term of service, whole cities by grant — and there were emperors from Spain and North Africa.',
    },
    {
      frage: 'Is it true that the Roman Empire fell in the year 476 AD?',
      antworten: [
        'Yes, on that day it was suddenly all over.',
        'Only half — the last Western Roman emperor was deposed, but the eastern half of the empire lasted almost 1,000 years longer.',
        'No, the empire still exists today.',
      ],
      richtig: 1,
      erklaerung: 'In 476 the last emperor of the West was deposed — quite unspectacularly. In the East, Constantinople kept ruling until 1453, and its inhabitants naturally continued to call themselves Romans. "Fall" is therefore already an interpretation, not a plain fact.',
    },
    {
      frage: 'Did Latin disappear along with the Roman Empire?',
      antworten: [
        'Yes, nobody used it afterwards.',
        'No — Italian, Spanish, French and other languages grew out of it; many Latin words are also embedded in German.',
        'No, it is still spoken as an everyday language all over Europe today.',
      ],
      richtig: 1,
      erklaerung: 'The Romance languages grew out of spoken Latin. And when you say "wall", "street" or "wine", you are using Latin words — they came to us through the Romans and simply stayed.',
    },
  ],
};

module.exports = roemischesReich;
