// Topic: Russia and the West (1991 to the present day).
//
// Status: Round 21 + Hermes pass. Three voices are finished: the view of the
// West (voice: Opus), the view of Russia (the Yeltsin years, Putin — per the
// operator directive "really objective", voice: Hermes) and the view of the
// Ukraine (voice: Hermes). The synthesis brings all three together.
//
// Nineteenth topic and twelfth chapter of the modern-era arc
// (notizen/kapitel-planung.md, chapter 12). It begins where "The New World
// Order and the Cold War" ends: on 25 December 1991, when the Soviet Union
// ceased to exist — and it takes up the debate that that chapter explicitly
// referred to this one: the debate about NATO enlargement and the "spirit"
// of the Two Plus Four Treaty.
//
// The order of the voices is not a ranking. That the West speaks first here
// results solely from who took over this round; that is also stated in the
// text so that nobody reads the order as a value judgment.
//
// TONE RULE (CLAUDE.md, additional rule for sensitive topics). This chapter
// is the most delicate of the whole app, because it is not finished: the
// people it is about are alive — in Ukraine, in Russia, in Europe — and
// while this text is being written, the war it tells of is being fought.
// That is why everything that applies elsewhere applies here more strictly:
//
//   * This perspective names its own uncomfortable spots itself: the
//     ambiguity of the 1990 assurances, the triumphalism of the nineties,
//     Western involvement in the shock therapy, the Kosovo war of 1999 and
//     the Iraq war of 2003 without a UN mandate, the Bucharest summit of
//     2008 as a decision that was neither protection nor refusal, and the
//     long trivialisation of developments in Russia.
//   * The motives of the Russian side are reproduced fairly — the
//     humiliation of the nineties, the security interests, the feeling of
//     having been passed over. Fair means: made comprehensible, not
//     justified. Keeping the two apart is the actual work of this chapter.
//   * **Operator directive "REALLY OBJECTIVE":** On Russia under Putin, both
//     findings stand side by side and with figures — the stabilisation and
//     growth of the 2000s AND the authoritarian turn together with the
//     wars. No demonisation, no glossing over. The app does not balance the
//     books and distributes no blame — but it also conceals nothing.
//   * The Russian attack on Ukraine of 24 February 2022 is called by its
//     name: a large-scale war of aggression, not a "conflict". That too is
//     part of objectivity — it is the finding of the UN General Assembly of
//     2 March 2022 (141 to 5 votes), not the opinion of this app.
//   * The quiz questions remain knowledge questions. This app does not ask
//     about guilt, here as little as in the eighteen chapters before.
//
// The map lives in karten/russland-westen.js — three states (1999, 2014,
// 2022–2024). Why the excerpt stands the way it does, and what it costs, is
// explained in the header of the map file. NOTE: this English translation
// deliberately does not include the karte field.
//
// Pure data — no UI imports (architecture rule).

const russlandWesten = {
  id: 'russland-westen',
  titel: 'Russia and the West',
  epoche: '1991–present',

  aufhaenger: {
    frage: 'Two sides that had won together in 1945 and in 1990 called each other "partners" now stand against each other again — and a sentence from February 1990 that nobody wrote down is still cited as proof today. How does a partnership become a front line again within thirty years?',
    text: [
      'On 21 November 1990, thirty-two European states, together with the USA',
      'and Canada, signed a document in Paris that declared the Cold War',
      'ended. "The era of confrontation and division of Europe has ended",',
      'reads the Charter of Paris. The signatures are those of Mikhail',
      'Gorbachev, George Bush, Helmut Kohl and François Mitterrand. One year',
      'later, the Soviet Union no longer existed.',
      '',
      'What came next was hope at first. In 1998 Russia was admitted to the',
      'circle of the seven major industrial nations, which was then called',
      'the G8. In 1997 NATO and Russia signed a Founding Act in which both',
      'sides expressly declared that they no longer regarded each other as',
      'adversaries. In 2002 they sat down at the same table in a joint',
      'council. Russian and American soldiers trained together.',
      '',
      'And then there was the other half of those same years. Russia’s',
      'economic output fell by around forty per cent between 1991 and 1998 —',
      'more than the American one during the Great Depression. The savings of',
      'an entire generation dissolved in inflation. The life expectancy of',
      'Russian men fell from 64 to 57 years within four years. In August 1998',
      'the state was insolvent.',
      '',
      'In between lies a sentence. On 9 February 1990, US Secretary of State',
      'James Baker said to Gorbachev in the Kremlin that NATO would not move',
      '"not one inch eastward". He said it in a conversation about German',
      'reunification; it never became a treaty, and whether he meant Poland',
      'and the Baltic states or only East Germany is disputed to this day.',
      'That one sentence stands in every debate about Russia and the West to',
      'this day — for some as proof of a breach of trust, for others as',
      'evidence of how unreliable memory is.',
      '',
      'This chapter begins with the view of the West. That is one of several',
      'voices, not the right one — which one speaks first depends on who',
      'wrote this round, and is not a ranking.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'The view of the West — the USA, NATO and Europe',
      stimme: 'Opus',
      text: [
        'This voice tells the story from Washington, Brussels, Berlin,',
        'Warsaw and Tallinn: from the capitals in which the decisions about',
        'NATO were made, but also from the countries that desperately wanted',
        'to join in 1999 and 2004 and had their own reasons for it.',
        '',
        'It is equal to the other voices of this chapter. That it stands',
        'first here is not a ranking — it is only because of who took over',
        'this round. And it has a task that is harder than in all previous',
        'chapters: this chapter is not finished. While these lines are being',
        'written, the war they deal with is being fought. Whoever writes',
        'about an ongoing story is himself a party — and the only honest way',
        'to deal with that is to say so and nevertheless be as precise as',
        'possible.',
        '',
        '## 1991: the hope, and what carried it',
        '',
        'The West did not understand the end of the Soviet Union as a victory',
        'over Russia — at least not in the official documents. The Charter of',
        'Paris of 21 November 1990 speaks of a common Europe, not of winners',
        'and losers. And it contains a sentence that will return three more',
        'times in this chapter: every state has the right to choose its',
        'alliances freely — or to belong to none. The Soviet Union signed',
        'that too; Russia confirmed it again in 1999 in the Istanbul Charter.',
        '',
        'What followed from that was a series of invitations. In 1994 Russia',
        'joined the "Partnership for Peace", the programme with which NATO',
        'bound its former adversaries to itself. In 1997 both sides signed',
        'the **NATO–Russia Founding Act**: they declared in it that they no',
        'longer regarded each other as adversaries, and NATO undertook not to',
        'station nuclear weapons or permanently deployed large combat',
        'formations in the new member states — a commitment it kept until',
        '2014. In 1998 the G7 became the **G8**. In 2002 the **NATO–Russia',
        'Council** was created, in which Russia sat not as a guest but as an',
        'equal member. In 2012 Russia joined the World Trade Organization —',
        'with Western support.',
        '',
        'After 11 September 2001, Vladimir Putin was the first foreign head',
        'of state to call George W. Bush. Russia opened its airspace for',
        'supplies to Afghanistan and helped build bases in Central Asia. On',
        '25 September 2001, Putin spoke in German before the German Bundestag',
        'and received a standing ovation. Whoever claims today that the West',
        'excluded Russia from the start must explain these years.',
        '',
        '## The nineties: what the West saw — and what it did not want to see',
        '',
        'And yet the first uncomfortable spot of this narrative also begins',
        'here, and it is a big one. The West did not merely observe Russia’s',
        'transformation of the nineties — it advised it and co-financed it.',
        '',
        'The price liberalisation of January 1992 — the "shock therapy" — was',
        'meant to be quick, because there was a fear that a slow',
        'transformation would be politically reversed. The consequence was',
        'inflation of over 2,500 per cent in the first year. Whoever had',
        'saved all their life was poor within months. The mass privatisation',
        'via voucher certificates gave every citizen a piece of state',
        'property; most sold it for a few dollars because they needed money.',
        'In 1995/96 came the "loans-for-shares" scheme: banks lent the state',
        'money against shares in the largest commodity companies — and when',
        'the state did not pay, they kept the shares. That is how the',
        'oligarchs emerged within a few years. On 17 August 1998 Russia',
        'declared state bankruptcy.',
        '',
        'Western advisers, the International Monetary Fund and Western',
        'governments recommended, supported and financed this path. In March',
        '1996, four months before the presidential election, the IMF gave',
        'Russia a loan of 10.2 billion dollars; Boris Yeltsin was polling at',
        'a few per cent — and won. One can argue about whether there were',
        'alternatives — the experts argue about it to this day. But this',
        'voice cannot pretend that the Russian misery of the nineties was a',
        'purely Russian affair. It was the time in which millions of people',
        'associated the word "democracy" with empty shelves, unpaid wages and',
        'a handful of new billionaires. Whoever wants to understand why order',
        'later counted for more than freedom in Russia will find the answer',
        'here.',
        '',
        'Added to that was the tone. "We won" was a common sentence in the',
        'West in the nineties. Francis Fukuyama’s formula of the "end of',
        'history" was read as if it were only a matter of waiting until',
        'everyone else became like us. This **triumphalism** was not official',
        'policy, but it was the mood — and in Moscow it was heard precisely.',
        'A great power that had just lost half of its state territory, its',
        'economy and its role in the world was treated like a pupil receiving',
        'tutoring. That was a mistake, and it cost more than many treaties.',
        '',
        '## Chechnya: the wars the West looked away from',
        '',
        'In December 1994 the Russian army marched into Chechnya, which had',
        'declared independence. Grozny was shot to pieces in a winter',
        'campaign; estimates of the civilian dead of this first war range',
        'from 30,000 to over 50,000. In 1996 it ended with a ceasefire that',
        'left the question open. In 1999 the second war began, this time',
        'under the new Prime Minister Vladimir Putin; in 2003 the United',
        'Nations called Grozny "the most destroyed city on earth".',
        '',
        'What did the West do? It protested in statements and otherwise',
        'carried on. Yeltsin remained the partner one supported because one',
        'feared what would come after him. And with the second war a second',
        'motive was added: after 11 September 2001, the West too classified',
        'Chechnya under "counter-terrorism". There were indeed attacks and',
        'hostage-takings on the Russian side with hundreds of dead — Moscow',
        '2002, Beslan 2004 — and there was, on the Russian side, action',
        'against the civilian population that the European Court of Human',
        'Rights has condemned in more than two hundred judgments. Both are',
        'true. For a long time the West said the second one more quietly than',
        'the first, and that belongs in this narrative.',
        '',
        '## The core: NATO enlargement',
        '',
        'Here lies the dispute this chapter is really about. It can be broken',
        'down into four questions, and this voice answers all four —',
        'including the ones it does not like.',
        '',
        '### First: What was said in 1990?',
        '',
        'On 9 February 1990, US Secretary of State **James Baker** told',
        'Gorbachev that if a united Germany remained in NATO, then NATO would',
        'not extend its area of responsibility "one inch eastward" — in the',
        'original, "not one inch eastward". On the same day and in the weeks',
        'that followed, similar things were said by: Chancellor Helmut Kohl,',
        'Foreign Minister Hans-Dietrich Genscher (in his Tutzing speech of 31',
        'January 1990), British Foreign Secretary Douglas Hurd and NATO',
        'Secretary General Manfred Wörner. These assurances are not a rumour:',
        'the records of the conversations have been declassified and have',
        'been publicly accessible since 2017 in the National Security Archive',
        'of the George Washington University.',
        '',
        '### Second: Did it become a treaty?',
        '',
        'No. There is no document in which NATO commits itself to admitting no',
        'new members. The **Two Plus Four Treaty** of 12 September 1990,',
        'which regulated German reunification under international law,',
        'expressly says the opposite in **Article 6**: "The right of the',
        'united Germany to belong to alliances, with all the rights and',
        'obligations arising therefrom, is not affected by this treaty."',
        'Article 5 regulates what may not be stationed on the territory of',
        'the former GDR — no nuclear weapons, no foreign troops — and this',
        'restriction applies to this day. The treaty says nothing about other',
        'countries, because other countries were not its subject.',
        '',
        'Gorbachev himself later confirmed that too. In 2014 he said in an',
        'interview that the topic of "NATO enlargement" had not been',
        'negotiated at all back then — that it had simply not come up in',
        'those years because the Warsaw Pact still existed. In the same',
        'breath he added that the **spirit** of the assurances of that time',
        'had later been violated. Both halves of that sentence belong',
        'together, and both sides usually cite only one of them.',
        '',
        '### Third: Why did the new members come anyway?',
        '',
        'Because they wanted to — and very much so. Poland, the Czech',
        'Republic and Hungary joined on 12 March 1999, seven further states',
        'on 29 March 2004 — among them Estonia, Latvia and Lithuania, which',
        'had been annexed by the Soviet Union in 1940. In each of these',
        'countries it was elected parliaments and governments that submitted',
        'the application; in several there were referendums on it with clear',
        'majorities. Accession was not something the West brought to these',
        'countries, but something they had asked for over years — and which',
        'was initially refused to them out of consideration for Moscow.',
        '',
        'From a Western point of view, the decisive distinction follows from',
        'this: an alliance one can join is something different from a bloc',
        'one is assigned to. In 1945 nobody asked the Poles. In 1999 nobody',
        'forced them. And that is exactly the right that the Charter of Paris',
        'grants every state — including the one whose neighbour does not like',
        'it.',
        '',
        '### Fourth: What did the West get wrong in the process?',
        '',
        'Three things, and they stand here because they belong here.',
        '',
        'First, the **ambiguity of 1990**. Sentences were said that were',
        'meant to reassure, without putting them on paper — and later one',
        'pointed to the paper. Legally that is clean. Politically it is the',
        'kind of cleverness that has a price, and the price was trust.',
        '',
        'Second, the **warnings from one’s own ranks** that were overridden.',
        'George F. Kennan, the father of containment policy, called the',
        'enlargement in 1997 in the New York Times "the most fateful error of',
        'American policy in the entire post-war era". The later CIA director',
        'William Burns wrote a telegram in 2008 as ambassador in Moscow with',
        'the title "Nyet means nyet": NATO membership for Ukraine was a red',
        'line for the entire Russian elite, not just for Putin. One may',
        'consider both wrong. But one cannot claim that nobody said it.',
        '',
        'Third, **Bucharest 2008**. At the summit of 3 April 2008, NATO',
        'declared that Ukraine and Georgia "will become members of NATO" —',
        'but decided no roadmap to get there, because Germany and France were',
        'against it. That was the worst of all possibilities: an announcement',
        'that Moscow read as a threat, without any protection for the two',
        'countries concerned. Four months later Russia waged war in Georgia;',
        'six years later in Crimea. Whoever looks at this sequence must take',
        'the Bucharest summit seriously without declaring it the cause —',
        'either would be too simple.',
        '',
        '### And the Russian view?',
        '',
        'It belongs here, even in this perspective, and it goes roughly like',
        'this: in 1990 we were given a verbal promise, then we were referred',
        'to the fine print, and in twenty-five years a military alliance was',
        'led from the Elbe to our border — while we were too weak to say no.',
        'From this view, the point is not the individual accession but the',
        'pattern: every time Russia was weak, the line moved closer.',
        '',
        'This voice counters with what stands above — treaties,',
        'self-determination, the Founding Act of 1997, which NATO adhered to',
        'for seventeen years. But it counters without declaring the other',
        'perception invented. A perception shared on both sides of the',
        'Kremlin by people who otherwise share little is not a propaganda',
        'invention. It just does not explain everything: whoever lets borders',
        'be changed because he feels threatened turns a feeling into a right',
        'that international law does not provide for.',
        '',
        'And so that this is not misunderstood: to reproduce fairly means to',
        'make comprehensible, not to justify. That is two different things,',
        'and keeping the distinction clean is the actual work of this chapter',
        '— on it depends whether one can understand without agreeing.',
        '',
        '## Russia under Putin — both halves, with figures',
        '',
        'On 31 December 1999 Yeltsin handed over the affairs of state to',
        'Vladimir Putin. What came then is often told in the West only by',
        'halves. That is why both halves stand here side by side — not to be',
        'balanced against each other, but because without the first one',
        'cannot understand the second.',
        '',
        '### What got better (2000–2008)',
        '',
        'The economy grew between 1999 and 2008 by an average of around seven',
        'per cent a year. Real disposable incomes roughly doubled in that',
        'decade; the poverty rate fell from around 29 per cent (2000) to',
        'about 13 per cent (2008). Pensions and wages were paid on time again',
        '— which had by no means been a matter of course in the nineties. The',
        'state worked again: taxes were collected (introduction of a 13 per',
        'cent flat tax in 2001), foreign debts were repaid early, the central',
        'bank built up reserves. The number of murders and alcohol-related',
        'mortality fell markedly; life expectancy rose again.',
        '',
        'A large part of that hung on the **oil price**: a barrel of Urals',
        'crude cost around 12 dollars in 1998 and almost 140 in the summer of',
        '2008. Without that inflow much would not have been possible — and',
        'Russian economists say so too. But it was not only the oil price,',
        'and it was very real for the people who experienced it. Whoever',
        'describes the 2000s in Russia exclusively as the beginning of a',
        'dictatorship does not describe what the majority experienced — and',
        'therefore also does not understand the approval that grew out of it.',
        '',
        '### What narrowed (2000–present)',
        '',
        'In the same decade and after, what makes up a democracy disappeared',
        'piece by piece. The list is long, and it is documented:',
        '',
        '- **The media.** In April 2001 the state-affiliated Gazprom group',
        '  took over NTV, the last major independent television channel. The',
        '  high-reach channels have been state-controlled ever since.',
        '- **The economy.** In October 2003 Mikhail Khodorkovsky, at the time',
        '  the richest man in the country and politically active, was',
        '  arrested; his oil company Yukos was broken up and went to a state',
        '  corporation.',
        '- **Federalism.** In 2004, after the hostage drama of Beslan, the',
        '  direct election of governors was abolished; they were henceforth',
        '  appointed from Moscow.',
        '- **The critics.** The journalist Anna Politkovskaya, who reported',
        '  on Chechnya, was shot in Moscow on 7 October 2006. The former',
        '  intelligence officer Alexander Litvinenko died in London in',
        '  November 2006 from poisoning with polonium-210; a British inquiry',
        '  concluded in 2016 that the act had "probably" been approved at the',
        '  highest level. The opposition politician Boris Nemtsov was shot on',
        '  27 February 2015 in sight of the Kremlin. Alexei Navalny was',
        '  poisoned with the nerve agent Novichok in August 2020, treated in',
        '  Berlin, returned, was imprisoned and died on 16 February 2024 in a',
        '  penal colony north of the Arctic Circle.',
        '- **The law.** Since 2012 organisations can be classified as',
        '  "foreign agents"; the regulation has been tightened several times',
        '  and today also applies to individuals. In 2020 the constitution',
        '  was changed so that Putin can run until 2036. Since March 2022,',
        '  describing the war as a war carries a prison sentence.',
        '',
        'These two lists stand side by side, and neither cancels out the',
        'other. The boom of the 2000s was real. So was the narrowing.',
        'Whoever tells only the one tells advertising; whoever tells only the',
        'other tells a caricature.',
        '',
        '## The wars',
        '',
        '**Georgia, August 2008.** The dispute over South Ossetia and',
        'Abkhazia was old. In the night of 8 August 2008 the Georgian army',
        'shelled Tskhinvali; Russian troops moved in and advanced far beyond',
        'the disputed territories. The investigation report commissioned by',
        'the EU under Heidi Tagliavini reached an uncomfortable double',
        'finding in 2009: the Georgian attack had not been justifiable under',
        'international law — and the Russian reaction had gone far beyond',
        'what was proportionate, prepared by years of provocation. This voice',
        'reproduces the report as it is, even though its first half',
        'contradicts the Western narrative.',
        '',
        '**Crimea and Donbas, 2014.** After the fall of President',
        'Yanukovych, soldiers without insignia occupied Crimea at the end of',
        'February 2014; Putin confirmed a few weeks later that they were',
        'Russian soldiers. A referendum under occupation on 16 March was not',
        'recognised internationally; on 27 March the UN General Assembly',
        'declared the annexation invalid by 100 votes to 11. In the spring',
        'the war began in the Donbas, in which the Russian military was',
        'involved, even though Moscow denied that for years. On 17 July 2014',
        'the passenger aircraft MH17 with 298 people on board was shot down',
        'over the Donbas; a Dutch court convicted three of those involved in',
        'absentia in 2022. The Minsk agreements (September 2014 and February',
        '2015) froze the war without ending it; they were never fully',
        'implemented by either side.',
        '',
        '**24 February 2022.** On this day Russia began a large-scale war of',
        'aggression against Ukraine — from the east, from the south and from',
        'the north, across Belarusian territory, towards Kyiv. It is',
        'important to call it exactly that and not say "conflict": a conflict',
        'has two sides that start something; here one side crossed a border.',
        'On 2 March 2022 the UN General Assembly condemned the attack by 141',
        'votes to 5 and demanded withdrawal. The thrust towards Kyiv failed',
        'and was broken off in early April; in the liberated places, among',
        'them Bucha, investigators found numerous killed civilians. In March',
        '2023 the International Criminal Court issued an arrest warrant',
        'against Putin over the deportation of Ukrainian children.',
        '',
        'And the consequence nobody had planned: **Finland joined NATO on 4',
        'April 2023, Sweden on 7 March 2024.** Finland had maintained its',
        'non-alignment since 1945, Sweden since 1814. Before February 2022',
        'about 20 to 25 per cent in Finland were in favour of joining; a few',
        'weeks later over 70 per cent. NATO’s land border with Russia has',
        'thereby more than doubled — exactly what the war, by its own',
        'justification, was supposed to prevent.',
        '',
        '## The most uncomfortable spot: one’s own yardstick',
        '',
        'This perspective invokes a rule — borders are not changed by force.',
        'Then it must say where it itself violated that rule.',
        '',
        '**Kosovo 1999.** NATO bombed Yugoslavia for 78 days without a',
        'mandate from the UN Security Council. The occasion — the expulsion',
        'of the Albanian population — was real; the legal basis was missing.',
        'In 2008 Kosovo declared its independence, which the West recognised',
        'and Russia did not. Moscow has cited this case in every debate',
        'since, and the reference is not far-fetched.',
        '',
        '**Iraq 2003.** The USA and its allies waged a war against a state',
        'that had not attacked them, without a UN mandate and with a',
        'justification — weapons of mass destruction — that turned out to be',
        'false. Whoever does not name that cannot speak credibly about',
        'international law.',
        '',
        '**Libya 2011.** The Security Council authorised the protection of',
        'the civilian population; the military action ended with the',
        'overthrow of the regime. Russia and China, which had abstained, felt',
        'deceived — and have since agreed to nothing comparable.',
        '',
        '**And the business.** Before 2022 Germany obtained over half of its',
        'natural gas from Russia and expanded the dependence further with',
        'Nord Stream 1 and 2 — against the explicit warnings of Poland, the',
        'Baltic states and the USA. "Wandel durch Handel" — change through',
        'trade — was the formula. After 2008 and after 2014 one could have',
        'reviewed it. One did not, because it would have been expensive. When',
        'Putin gave a speech at the Munich Security Conference on 10 February',
        '2007 in which he said in plain language how he saw Western policy,',
        'that was regarded in Berlin and Paris as a bad mood. It was an',
        'announcement.',
        '',
        '## What the West does today — and what that costs',
        '',
        'Since 2022 the USA, the EU and other states have supported Ukraine',
        'with weapons, money and the reception of refugees, and they have',
        'imposed the most comprehensive sanctions of the post-war era on',
        'Russia. NATO soldiers do not fight alongside; the alliance declared',
        'from the start that it does not do that, because a direct war',
        'between nuclear powers would be something else.',
        '',
        'Here too, the counter-account belongs. The sanctions have not',
        'brought the Russian economy to collapse; it has restructured itself,',
        'at a cost. A large part of the world — India, China, Brazil, South',
        'Africa and most African states — does not go along with them and',
        'accuses the West of suddenly discovering principles here that it',
        'does not apply elsewhere. This criticism is uncomfortable, and it is',
        'not unfounded. And in Europe itself the question is open how long',
        'societies will carry a support that costs money and has no',
        'foreseeable end.',
        '',
        '## What this view cannot see',
        '',
        'It sees the nineties from outside — as a transition period, not as',
        'the collapse of one’s own world. It sees the enlargement as the sum',
        'of free decisions, not as a line moving closer. It sees the Russian',
        'narrative as a narrative and its own as a description — and that is',
        'exactly the blind spot against which this app warns in every',
        'chapter.',
        '',
        'That is why this voice does not stand here alone. The **view of',
        'Russia** — the Yeltsin years from inside, the stabilisation, the',
        'encirclement, its own justification of the wars — is written by',
        'Hermes; a third voice may be added, that of the Ukraine, which in',
        'this chapter so far mostly appears rather than speaks. Only then',
        'does the synthesis bring together what belongs together.',
      ].join('\n'),
    },
    {
      id: 'russland-sicht',
      name: 'The view of Russia — the nineties and Putin',
      stimme: 'Hermes',
      text: [
        'This voice tells the story from Moscow: from the world that',
        'collapsed with the Soviet Union on 25 December 1991, and from the',
        'Russia that emerged afterwards. It is equal to the voice of the West',
        '— that it stood first there was only the order in which things were',
        'written.',
        '',
        '## The nineties — the great humiliation',
        '',
        'Whoever lived through the nineties in Russia remembers them as a',
        'time of collapse: prices rose beyond all measure, the savings of a',
        'lifetime were worthless within months, salaries and pensions did not',
        'come for months on end, life expectancy fell, and the state seemed',
        'no longer to exist. The **hyperinflation** of the years 1992 to 1995',
        'ate up the savings of the entire population. Into this void stepped',
        'the **oligarchs**: a few men who, in the wave of privatisation, took',
        'over the largest enterprises of the country for a fraction of their',
        'value. The "shock therapy" was a Western recommendation, and this',
        'voice says that without malice: the West meant well and had no idea',
        'what it was doing.',
        '',
        'In 1998 the bubble burst: the **rouble crisis** — the state could no',
        'longer pay its debts, the banks collapsed, again millions lost their',
        'savings. And into this period fell the first **Chechen war**',
        '(1994–1996), a humiliating, brutal war that Russia lost. Whoever',
        'lived through these years experienced shame. When the West',
        'celebrated the nineties as the "triumph of freedom", Russia',
        'experienced them as a national trauma — that is the **fault line**',
        'at which this voice begins.',
        '',
        '## Putin — the restoration of order',
        '',
        'Vladimir Putin entered this world in 1999/2000 — and the operator',
        'directive for this voice says: **really objective**. So both things',
        'stand here, without demonisation and without glossing over.',
        '',
        '**What Putin did for Russia:** He ended the time in which the state',
        'no longer functioned. Pensions were paid out again and rose,',
        'salaries came on time, the **economy grew** — between 2000 and 2008',
        'by an average of around seven per cent a year, carried by the oil',
        'price, but also by a policy that brought back trust in one’s own',
        'currency and in the state. The oligarchs were pushed back, the',
        '"vertical of power" restored order, the second Chechen war ended',
        'with a harsh pacification. For many Russians Putin was the man who',
        'ended the humiliation of the nineties — his approval was very high',
        'for years, and that was not forced approval but gratitude for lived',
        'stability. This achievement is real, and this voice calls it by its',
        'name.',
        '',
        '**And what Putin took for it:** The media were brought into line —',
        'the independent channel NTV was broken up in 2001. The oligarchs',
        'were not only pushed back but expropriated and imprisoned when they',
        'resisted (Khodorkovsky 2003). Opponents disappeared: Alexander',
        'Litvinenko died in 2006 in London of polonium, Alexei Navalny was',
        'poisoned with Novichok in 2020 and died in 2024 in a penal colony.',
        'The elections were controlled, the opposition criminalised, press',
        'freedom extinguished. And there were the wars: **Georgia 2008**,',
        'the **annexation of Crimea** in 2014 — which this voice also calls',
        'by its name: unlawful under international law — and the',
        '**large-scale attack on Ukraine in 2022**, which continues to this',
        'day. This side of the balance is just as real as the first. To place',
        'both side by side without balancing them is the work of this voice.',
        '',
        '## The encirclement — from Moscow’s point of view',
        '',
        'This voice must also say what Russia itself sees as the reason for',
        'this development: **NATO enlargement**. James Baker had promised',
        'Gorbachev in 1990 that NATO would not move "one inch eastward" — to',
        'this day there is a dispute about whether the assurance was meant',
        'that way and how far it reached. But what counted from Moscow was',
        'the result: in 1999 Poland, the Czech Republic and Hungary joined,',
        'in 2004 the Baltic states — former Soviet republics. At the',
        '**Bucharest 2008** summit it was said that Georgia and Ukraine would',
        'join NATO — without a timetable and without a refusal. For Moscow',
        'that was a threat on one’s own border: the alliance one knew as an',
        'adversary from the Cold War was coming closer. The West sees the',
        'enlargement as a success story of free states; this voice sees it as',
        'a breach of trust. Both views stand side by side in this chapter —',
        'the synthesis will not balance them against each other.',
        '',
        '## The most uncomfortable spot of this voice',
        '',
        'This voice must admit what it cannot explain: that a people that had',
        'experienced the oppression of the Soviet era exchanged the freedom',
        'of the nineties so quickly for Putin’s order. That the fear of chaos',
        'was stronger than the love of freedom — that is the tragedy of',
        'Russian democracy. And it must admit that the war of 2022 has',
        'brought the isolation that Russia itself chose: the economy sank,',
        'the young men left or fled, and a country that feared the West has',
        'made the West its enemy. This voice does not end with a',
        'justification but with the question it asks itself: What has become',
        'of a people that lost its freedom twice in a century — and the',
        'second time almost voluntarily?',
      ].join('\n'),
    },
    {
      id: 'ukraine-sicht',
      name: 'The view of the Ukraine',
      stimme: 'Hermes',
      text: [
        'This voice is the youngest and the most vulnerable of this chapter:',
        'it tells the story from a country that has existed in this form',
        'only since 1991 — and whose existence is currently threatened by a',
        'war while these lines are being written. It is equal to the other',
        'two voices. That it speaks last is not a ranking but caution: this',
        'voice speaks about people who are still alive.',
        '',
        '## The independent Ukraine',
        '',
        'In 1991 Ukraine became independent — the most populous country in',
        'Europe after Russia, with a long history of its own (the Kievan Rus,',
        'the Cossacks, the Hetmanate) and a society split between East and',
        'West: in the East and South many spoke Russian, in the West the',
        'Ukrainian identity was stronger. The first period of independence',
        'was hard — the economy collapsed, corruption flourished, politics',
        'swayed between Moscow and Brussels. This voice does not conceal its',
        'own mistakes: the oligarchs, the bought elections, the reforms that',
        'never came. Ukraine was long no model state — that makes its history',
        'human, not perfect.',
        '',
        '## Two revolutions',
        '',
        'In 2004 the **Orange Revolution** brought hundreds of thousands onto',
        'the streets against a falsified election — and initially won. In',
        '2013/14 followed the **Euromaidan**: the government had rejected an',
        'association agreement with the EU at the last minute, the people',
        'took to the streets, the police shot, and in the end the president',
        'fled. For this voice the Maidan was not a conspiracy but the moment',
        'in which a country made its decision: towards Europe, not back to',
        'Moscow. Many people in Ukraine had no strong opinion until then —',
        'the Maidan forced them to have one.',
        '',
        '## The annexation of Crimea and the Donbas war',
        '',
        'In February 2014 soldiers without insignia occupied Crimea — they',
        'were Russian troops. The referendum that then decided Crimea "for',
        'Russia" took place under occupation; the **annexation was unlawful',
        'under international law**, and this voice says that without beating',
        'around the bush. In the Donbas a war began that lasted until 2022:',
        'separatists, supported by Russia, against the Ukrainian army — over',
        '14,000 dead, in the middle of Europe, for eight years, while the',
        'world watched. This voice also says that the Ukrainian government',
        'was not innocent of the estrangement of the East: the language, the',
        'symbols, Kyiv’s disinterest in the eastern regions contributed to',
        'the division. But it also says: none of that explains a war of',
        'aggression.',
        '',
        '## The great war since 2022',
        '',
        'On 24 February 2022 Russia attacked Ukraine. The planning was',
        'designed for a quick victory — the capital was supposed to fall',
        'within days. Instead the country resisted: the army, the civilian',
        'population, the farmers who towed away tanks with tractors.',
        'Millions of people fled — the largest flight movement in Europe',
        'since 1945. In Bucha, in Mariupol, in countless cities mass graves',
        'were found. This voice calls the atrocities by their name: they are',
        'war crimes, documented by international organisations. And it says',
        'what it means to live in a war: the sirens, the nights in the',
        'cellar, the men at the front, the children growing up abroad.',
        'Whoever has not experienced it should not pretend to be able to',
        'imagine it.',
        '',
        '## What this voice wants',
        '',
        'This voice wants neither revenge nor triumph. It wants the world to',
        'understand what is at stake here: the existence of a country that',
        'wants to choose freely where it belongs — a right that the West',
        'takes for granted and that Ukraine pays for with blood. It knows',
        'that Ukrainian society is not perfect and that the peace, when it',
        'comes, will demand compromises. But it ends with a sentence it keeps',
        'telling itself: A country that defends its freedom may be able to',
        'lose — but it has already lost when it stops trying.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Three voices, one continent, one war. This synthesis brings together',
    'what the West, Russia and the Ukraine have told — and it begins with',
    'the **fault lines** at which the same story began completely',
    'differently.',
    '',
    'The first **fault line** is the year 1991. The West celebrated the',
    'collapse of the Soviet Union as a triumph of freedom — rightly so, for',
    'it was freedom that won. Russia experienced those same years as',
    'humiliation and chaos: hyperinflation, oligarchs, the rouble crisis,',
    'the Chechen wars. Both are true. Whoever tells only one of them tells',
    'half a story — and may have laid the foundation for the next conflict',
    'without noticing.',
    '',
    'The second **fault line** is NATO enlargement. The West saw an',
    'alliance of free states that brought democracy and security to Eastern',
    'Europe; the new members wanted accession of their own free will. Russia',
    'saw a breach of trust: the assurance of 1990 that promised "not one',
    'inch eastward", and an alliance that moved up to its own border. Both',
    'views are documented in this chapter — this synthesis **does not',
    'balance** who was more right. But it says: a victor who humiliates the',
    'vanquished plants the next war. That is the lesson of Versailles, and',
    'it also applies to 1991.',
    '',
    'The third **fault line** is 24 February 2022. Here the symmetry of the',
    'perspectives ends. The Russian voice explains why the war came — the',
    'encirclement, the humiliation, the fear. But explaining is not',
    'justifying: a war of aggression remains a war of aggression, the',
    'annexation remains unlawful under international law, and the atrocities',
    'in Bucha and Mariupol are war crimes. The Russian voice of this chapter',
    'says that too. Ukraine defends its existence — that is not a',
    'standpoint, that is a fact.',
    '',
    'What remains is the question to the future. In 1991 the West failed to',
    'see what would become of Russia’s humiliation. Whoever wants to',
    'understand the world today must know both sides — Moscow’s fear and',
    'Kyiv’s suffering — and nevertheless say clearly what is non-negotiable:',
    'that no state has the right to attack its neighbour, and that the',
    'history the victor writes is not the whole story. Perhaps that is',
    'exactly the answer to the guiding question of this chapter: how allies',
    'of 1945 became enemies — and what we can do so that it does not end',
    'that way again.',
  ].join('\n'),

  urteil: {
    frage: 'A state may freely choose its alliances — that stands in the Charter of Paris, and Russia signed it. A neighbour can nevertheless feel threatened by it. How would you have solved this problem if you had sat at the table in 1997 — and what would you have accepted in exchange?',
    hinweis: 'There is no right answer here, and that is not meant politely but seriously. Some say: whoever would have refused the accession would have done to Poland and the Baltic states the same as in 1945 — decided over their heads, out of consideration for a great power. Others say: whoever pushed the enlargement asserted a right and lost a country one would have needed. Both sentences can be substantiated, and neither of the two is the whole answer. When you give your reasoning, check which source you use and who wrote it.',
  },

  quiz: [
    {
      frage: 'The sentence "not one inch eastward" by US Secretary of State James Baker (9 February 1990) — in what form does it exist?',
      antworten: [
        'As an article in a treaty under international law between NATO and the Soviet Union',
        'As a spoken remark in a negotiating conversation with Gorbachev, recorded in the minutes and declassified today',
        'As a resolution of the UN General Assembly',
      ],
      richtig: 1,
      erklaerung: 'Baker said the sentence, and the record of the conversation has been publicly accessible for years. A treaty about it does not exist — and that is exactly why the dispute continues to this day: one side asks what a word without a treaty is worth, the other what a treaty without a word is worth.',
    },
    {
      frage: 'What does Article 6 of the Two Plus Four Treaty of 12 September 1990 say about alliances?',
      antworten: [
        'That the united Germany may not belong to any alliance',
        'That the right of the united Germany to belong to alliances is not affected by the treaty',
        'That NATO may not admit any new members',
      ],
      richtig: 1,
      erklaerung: 'Article 6 expressly leaves alliance membership unaffected — the treaty thus forbids neither Germany’s NATO membership nor the admission of other states. It says nothing about other countries, because other countries were not its subject. Article 5, in turn, limits what may be stationed on the territory of the former GDR.',
    },
    {
      frage: 'Which three states were the first to join NATO after the Cold War, on 12 March 1999?',
      antworten: [
        'Estonia, Latvia and Lithuania',
        'Poland, the Czech Republic and Hungary',
        'Finland, Sweden and Austria',
      ],
      richtig: 1,
      erklaerung: 'Poland, the Czech Republic and Hungary made the start in 1999. Estonia, Latvia and Lithuania joined in 2004 together with four further states, Finland in 2023 and Sweden in 2024. Austria is not a member to this day.',
    },
    {
      frage: 'How did the Russian economy develop in the two decades after 1991?',
      antworten: [
        'It grew continuously from 1991 to 2008',
        'It fell by around 40 per cent until 1998 and then grew by an average of about seven per cent a year until 2008',
        'It remained roughly the same over both decades',
      ],
      richtig: 1,
      erklaerung: 'First the collapse — with hyperinflation in 1992 and the state bankruptcy of 17 August 1998 — then the boom of the 2000s, carried also by the oil price: a barrel of Urals cost about 12 dollars in 1998 and almost 140 in 2008. Both halves belong together if one wants to understand how people experienced those years.',
    },
    {
      frage: 'What happened to Finland and Sweden after the Russian attack on Ukraine of 24 February 2022?',
      antworten: [
        'Both declared their permanent neutrality',
        'Both joined NATO — Finland in 2023, Sweden in 2024',
        'Both left the European Union',
      ],
      richtig: 1,
      erklaerung: 'Finland had maintained its non-alignment since 1945, Sweden since 1814. In Finland support for accession rose within weeks from about a fifth to over two thirds. NATO’s land border with Russia has thereby more than doubled.',
    },
  ],
  karteHinweise: [
    {
      label: "1999 — the first eastern enlargement",
      hinweis: "Eight years after the end of the Soviet Union, Poland, the Czech Republic and Hungary join NATO (12 March 1999). Russia has shrunk, but it is not an adversary: in 1997 Moscow and Brussels signed the NATO-Russia Founding Act. The USA and Canada, the two largest members, lie outside this map section.",
    },
    {
      label: "2014 — Crimea and Donbas",
      hinweis: "Two further enlargements lie in between: in 2004 Estonia, Latvia, Lithuania, Slovakia, Slovenia, Romania and Bulgaria joined, in 2009 Albania and Croatia. Since 2004 NATO has had a land border with Russia. In March 2014 Russia annexes Crimea; in spring the war in the Donbas begins.",
    },
    {
      label: "2022–2024 — the war of aggression and the Nordic enlargement",
      hinweis: "On 24 February 2022 Russia attacks Ukraine in full force. The front on this map is an approximate state of 2024, not a fixed condition. And it shows a consequence that nobody in Moscow had planned: Finland (2023) and Sweden (2024) give up their decades-long non-alignment and join NATO.",
    },
  ],
};

module.exports = russlandWesten;
