// Topic: The Weimar Republic and the Road to Dictatorship (1918–1933).
//
// English translation of utils/themen/weimar-ns.js (German original).
//
// Status: Round 18 + Hermes pass. Both voices are complete: the view of
// those who built and defended the Republic (Voice: Opus) and the view of
// the persecuted and disenfranchised — the Jewish Germans, the Communists,
// the Social Democrats and trade unionists, the people without work and
// without advocates (Voice: Hermes); the synthesis below brings both
// together. Both voices are of equal weight; the order results only from
// who took the round, and is not a judgment.
//
// Sixteenth topic and ninth chapter of the modern-era arc
// (notizen/kapitel-planung.md). It follows "The Road to the First World
// War" and "The USA: Rise to World Power": the war whose July Crisis
// chapter 14 tells ends here — and out of its end the first German
// democracy arises.
//
// Why this voice first? The chapter is about the destruction of a
// democracy. It is told most honestly when the side speaks first that
// built and defended this democracy — and through its own wrong decisions
// contributed to its failure. The most uncomfortable passage of the whole
// chapter belongs precisely to this voice: the Republic was destroyed not
// only by its enemies but also by its own guardians — from the emergency
// decrees from 1930 on to the back rooms of January 1933.
//
// TONE RULE (CLAUDE.md, additional rule for sensitive topics): This
// perspective names its own uncomfortable passages itself — the alliance
// with the old army leadership in 1918/19, the Freikorps, the emergency
// decrees, the underestimation of Hitler, the disunity of the republican
// forces, the accepted "Prussian coup" of 1932. The motives of the other
// sides are represented fairly — those of the Communists, the
// Conservatives and also of those who voted for the NSDAP — without
// trivializing the crimes. The quiz questions remain questions of
// knowledge: they do not ask about guilt.
//
// No map in this module: the German original ships its map separately in
// karten/weimar-ns.js — three states (1919, 1924–1929, 1933) in the same
// national territory. Its central determination: the borders of the Reich
// do not change between 1919 and 1933. What changed was not on the map
// but in the statute books.
//
// Pure data — no UI imports (architecture rule).

const weimarNs = {
  id: 'weimar-ns',
  titel: 'The Weimar Republic and the Road to Dictatorship',
  epoche: '1918–1933',

  aufhaenger: {
    frage: 'The first German democracy was fourteen years old when it died — abolished not by a foreign army but from within, largely in the forms of its own constitution. How do you destroy a democracy without conquering it?',
    text: [
      'In November 1918, an empire that had fought and lost four years of war went',
      'down. What took its place was the first democracy on German soil: universal',
      'suffrage for men and women, fundamental rights, a freely elected Reichstag.',
      'In the years that followed, Berlin became one of the most exciting cities in',
      'the world, German scientists collected Nobel Prizes, the Bauhaus invented',
      'the forms in which we still live today, and "Metropolis" was playing in the',
      'cinemas.',
      '',
      'Fourteen years later, none of that was left. On 30 January 1933, the Reich',
      'President appointed as Chancellor a man whose party had never won a',
      'majority; eight weeks later, the Reichstag had stripped itself of power.',
      'In between lie a lost war, an inflation that turned savings into paper, six',
      'million unemployed — and a chain of decisions made by people, not by',
      'natural laws.',
      '',
      'This chapter therefore tells the story not as fate but as a sequence of',
      'forks in the road. And it tells it from more than one direction: someone',
      'who builds a democracy sees different things than someone it failed to',
      'protect. The map shows something strange along the way — between 1919 and',
      '1933 almost nothing changes about the country’s borders. What changed was',
      'not on the map.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'republik-sicht',
      name: 'The view of those who built and defended the Republic',
      stimme: 'Opus',
      text: [
        'This voice tells the story from the middle of the Republic: from the',
        'offices of the Reich Chancellery, from the assembly halls of the National',
        'Assembly, from the editorial offices of the democratic newspapers, from',
        'the trade union houses and from the official rooms of the civil servants',
        'and judges who served the new state. It is the voice of the Social',
        'Democrats around Friedrich Ebert, of the founding fathers and mothers of',
        'Weimar, of the Catholics of the Centre Party, of the Liberals — of that',
        '"Weimar Coalition" that built this democracy and wanted to defend it to',
        'the last against enemies from right and left.',
        '',
        'It is of equal weight with the second voice of this chapter — the view of',
        'the persecuted and disenfranchised. That it stands first here is no',
        'ranking but simply the order in which it was written.',
        '',
        'And it has one advantage and one blind spot that one should know before',
        'listening to it. The advantage: it was there when the decisions were',
        'made, and it can say what those involved knew and feared at that moment —',
        'not what we know today. The blind spot: this voice has an interest in',
        'making its own mistakes look small. That is why it names them here',
        'explicitly itself, instead of leaving them to the counter-voice. The',
        'hardest truth of this chapter reads: the Republic failed not only because',
        'of its enemies but also because of its guardians.',
        '',
        '## November 1918: a republic born of defeat',
        '',
        'At the end of September 1918, the Supreme Army Command — General Erich',
        'Ludendorff and Field Marshal Paul von Hindenburg — informed the Kaiser',
        'that the war was militarily lost; an armistice had to be requested at',
        'once. For four years, this same army command had effectively governed the',
        'country and promised the population victory. Now a parliamentary',
        'government was supposed to conduct the negotiations. Some historians call',
        'this the "revolution from above": democracy came to Germany at the moment',
        'when there was something to lose — and those who had waged the war',
        'stepped aside.',
        '',
        'What came next came from below. On 29 October 1918, the sailors of the',
        'High Seas Fleet in Wilhelmshaven refused the order for one last,',
        'senseless battle. Within a week, the uprising in Kiel on 3 and 4 November',
        'became a revolution: in Hamburg, Bremen, Hanover, Munich and finally in',
        'Berlin, workers’ and soldiers’ councils took power — almost everywhere',
        'without bloodshed. On 9 November 1918, Wilhelm II abdicated, Reich',
        'Chancellor Max von Baden handed the office to the Social Democrat',
        'Friedrich Ebert, and Philipp Scheidemann proclaimed the Republic from the',
        'Reichstag. Two hours later, Karl Liebknecht proclaimed the "free',
        'socialist republic" from the City Palace. Two republics in one day — in',
        'that already lay the conflict that would shape the next fourteen years.',
        '',
        'On 11 November 1918, a civilian delegation under the Centre Party',
        'politician Matthias Erzberger signed the armistice in Compiègne. The',
        'generals who had waged the war stayed away from this signature. That was',
        'one of the most consequential junctions of German history — but nobody',
        'knew it then.',
        '',
        '## This voice’s own uncomfortable place: the alliance with the old army',
        '',
        'In the night of 10 November 1918, General Wilhelm Groener telephoned',
        'Friedrich Ebert. The army command offered the new government its support',
        'against a possible coup on the Russian model; Ebert agreed to leave the',
        'military command authority of the officers untouched. This Ebert–Groener',
        'Pact probably saved the Republic from civil war in the first weeks. In',
        'the long run, it came to cost it dearly.',
        '',
        'For in this way the Republic left the power apparatuses of the Empire',
        'largely untouched: the officer corps, the administration, the judiciary,',
        'the universities. When the January Uprising broke out in Berlin in early',
        '1919, the Social Democratic People’s Deputy Gustav Noske had Freikorps',
        'deployed against the insurgents — volunteer formations of front-line',
        'soldiers whose officers despised the Republic. "Someone has to be the',
        'bloodhound," Noske is reported to have said; he later quoted it himself.',
        'Rosa Luxemburg and Karl Liebknecht were murdered by Freikorps officers on',
        '15 January 1919, and their murderers got away with ridiculous sentences.',
        'In Munich, Freikorps shot over a thousand people in May 1919, many of',
        'them without trial.',
        '',
        'This voice cannot explain that away, and it does not try. The SPD',
        'leadership faced a real decision — it feared civil war, hunger and a',
        'dictatorship on the Russian model, and it had no loyal instrument of',
        'power other than the old army. But the calculation did not add up: the',
        'very Freikorps that were supposed to save the Republic in 1919 marched',
        'against it in the Kapp Putsch of 1920. And the workers’ movement remained',
        'divided for the rest of the Republic — into a Social Democracy that',
        'carried the state and a Left that considered it a betrayal. This wound',
        'never healed, and in 1933 it was fatal.',
        '',
        '## Weimar 1919: the constitution',
        '',
        'On 19 January 1919, the National Assembly was elected — the first',
        'election in Germany in which women were allowed to vote and stand for',
        'election. 82 percent of those eligible went to the polls; 37 women moved',
        'into parliament. The Weimar Coalition of SPD, Centre and the liberal DDP',
        'together received more than three quarters of the votes. The assembly met',
        'in Weimar because there was shooting in Berlin — and because the name of',
        'Goethe’s city was meant to give the new state a different face than that',
        'of the barracks.',
        '',
        'What was issued on 11 August 1919 was an extraordinary text for its time.',
        '"State authority derives from the people," says Article 1. There were',
        'fundamental rights, equality of the sexes in principle, freedom of',
        'religion, freedom of expression, the right to vote from age 20, works',
        'councils, the eight-hour day as a goal, social insurance. Women could',
        'study and become judges. In 1919, when no woman in France and Italy was',
        'yet allowed to vote, millions voted in Germany.',
        '',
        'This voice names the weaknesses of the constitution itself, because it',
        'shares responsibility for them:',
        '',
        '- **Article 48** gave the Reich President the right, in the event of a',
        '  "considerable disturbance of public security and order", to govern by',
        '  emergency decrees and to suspend fundamental rights. It was conceived',
        '  as a fire extinguisher for the exceptional case. It was built like a',
        '  second, quiet path to power — and from 1930 on, precisely this path',
        '  became the normal case.',
        '- **The directly elected Reich President** was meant to be a',
        '  counterweight to parliament, a "substitute emperor", as mockers said.',
        '  He appointed and dismissed the Chancellor and could dissolve the',
        '  Reichstag. Whoever held this office thereby decided about a great deal.',
        '- **Pure proportional representation without an electoral threshold**',
        '  mirrored every mood exactly — and shattered parliament. In the last',
        '  years, more than a dozen parties sat in the Reichstag; forming a',
        '  government became an exercise in arithmetic.',
        '- **Initiatives and referendums** were conceived as participation and',
        '  became a tool of the opponents: in 1929, the initiative against the',
        '  Young Plan made a previously unknown party leader named Adolf Hitler',
        '  known across the Reich for the first time, because the campaign ran',
        '  through the newspapers of the media entrepreneur Alfred Hugenberg.',
        '',
        'None of these weaknesses had to lead to catastrophe. All together they',
        'produced a constitution that did not brake a determined president and a',
        'blocked parliament, but accelerated them.',
        '## Versailles and the stab-in-the-back legend',
        '',
        'On 28 June 1919, the German delegation signed the Treaty of Versailles.',
        'It cost the Reich about a seventh of its territory and a',
        'tenth of its population: Alsace-Lorraine to France, Eupen and Malmedy to',
        'Belgium, North Schleswig to Denmark after a plebiscite, Posen and West',
        'Prussia to the newly created Poland, and part of Upper Silesia likewise',
        'after the 1921 vote; Danzig became a Free City, the Memel Territory was',
        'separated off, the Saar Territory was placed under the League of Nations',
        'for fifteen years, all colonies were lost. On top of that, reparations,',
        'an army of 100,000 men, the occupied and demilitarized Rhineland — and',
        'Article 231, which assigned Germany and its allies responsibility for all',
        'war damage.',
        '',
        'Almost all Germans felt this treaty to be a dictated peace, and the',
        'government that had to sign it called it that itself. It belongs to the',
        'honesty of this voice to put the counter-calculation beside it: the',
        'Treaty of Brest-Litovsk, which the Empire had imposed on defeated Russia',
        'in 1918, was far harsher — and in France, whose north lay in ruins, many',
        'found Versailles too lenient. Whoever knows this understands better why',
        'the victors did not give way, and will nevertheless not find the outrage',
        'of 1919 silly.',
        '',
        'What did the greatest damage was not the treaty but a story about it.',
        'Already in autumn 1919, Hindenburg told a parliamentary committee of',
        'inquiry that the German army had been "stabbed in the back with a dagger',
        'from behind". The stab-in-the-back legend claimed: the war had not been',
        'lost at the front but at home, by Social Democrats, Jews and democrats —',
        'the "November criminals". It was demonstrably false; the army command',
        'itself had admitted the defeat in September 1918. And it was enormously',
        'effective, because it came precisely from the two men whom many Germans',
        'believed. Whoever believed this legend could see the Republic only as the',
        'result of a betrayal. Matthias Erzberger, who had signed the armistice,',
        'was murdered in 1921; the Foreign Minister Walther Rathenau, who pursued',
        'the policy of fulfilment, in 1922. The right-wing radicals sang mocking',
        'songs about it.',
        '',
        '## 1923: the year in which everything happened at once',
        '',
        'The inflation did not begin in 1923 but in 1914. The Empire had financed',
        'the war not through taxes but through war bonds — in the expectation that',
        'the defeated would pay in the end. The war was lost, the bill remained.',
        'When the Reich fell into arrears with reparation deliveries, French and',
        'Belgian troops occupied the Ruhr on 11 January 1923. The Reich government',
        'declared "passive resistance" — a strike throughout the entire district —',
        'and paid the wages for it with freshly printed money. With that, the',
        'devaluation tipped into free fall. A dollar cost about 18,000 marks in',
        'January 1923, and over four trillion in November.',
        '',
        'Those who owned tangible assets got through. Those who had saved — civil',
        'servants, pensioners, small craftsmen, the entire middle class — lost the',
        'security of a lifetime within a few months. The Republic paid more dearly',
        'for this experience than for any reparation instalment: millions of',
        'people learned that diligence and thrift were of no use, and many did not',
        'hold the war financing of 1914 responsible but the state that stood there',
        'in 1923.',
        '',
        'In August 1923, Gustav Stresemann took over the government. He did the',
        'most unpopular thing possible: he called off passive resistance, because',
        'the Reich could no longer pay for it. In November came the Rentenmark,',
        'and the currency stood again. In the same year, the Republic had to',
        'survive a communist uprising attempt in Hamburg, a council government in',
        'Saxony and Thuringia, and, on 8/9 November, Adolf Hitler’s putsch attempt',
        'in Munich. It survived all three. That it survived strengthened many at',
        'the time in the belief that the worst was over.',
        '',
        '## The judiciary: blind in the right eye',
        '',
        'This, too, belongs to the places that this voice must name itself,',
        'because it concerns its own offices. The judges of the Republic were the',
        'same as those of the Empire, appointed for life and for the most part',
        'averse to the new order. The statistician Emil Julius Gumbel counted more',
        'than 300 political murders from the right for 1919 to 1922, which on',
        'average were punished with a few months in prison, and a good two dozen',
        'from the left, for which numerous death sentences were passed. In 1924,',
        'Hitler was allowed to use his high treason trial as a stage and was',
        'released after nine months of fortress detention.',
        '',
        'A democracy that treats its enemies unequally disarms itself. The',
        'Republic could have changed this — it could have transferred judges,',
        'vetted civil servants, rebuilt the Reichswehr. It did not do it, out of',
        'consideration for internal peace and out of respect for the independence',
        'of the judiciary. The respect was honourable. The price was high.',
        '',
        '## The golden years 1924–1929 — and the error within them',
        '',
        'For five years it looked as though the Republic had won. The Dawes Plan',
        'of 1924 reorganized the reparations, American money flowed into Germany,',
        'and in 1927 production overtook the pre-war level again. Gustav',
        'Stresemann, by now Foreign Minister, concluded the Treaties of Locarno in',
        '1925, in which Germany, France and Belgium recognized their common',
        'borders; in 1926 Germany joined the League of Nations, and in the same',
        'year Stresemann and his French colleague Aristide Briand received the',
        'Nobel Peace Prize. The Cologne zone of the occupied Rhineland was',
        'evacuated in 1926, the whole Rhineland in 1930 — five years earlier than',
        'provided for in the treaty. Negotiating brought more than defiance; that',
        'was the lesson of these years.',
        '',
        'And they were years in which this country was more interesting to the',
        'world than ever before. The Bauhaus in Weimar and Dessau, Fritz Lang’s',
        '"Metropolis", The Threepenny Opera, Berlin cabaret, Thomas Mann and',
        'Alfred Döblin, Albert Einstein, Max Planck, Werner Heisenberg. Women with',
        'short hair, their own bank account and their own profession. For the',
        'first time, in 1925, the Germans elected a Reich President directly — and',
        'elected Paul von Hindenburg, the field marshal of the monarchy. That,',
        'too, belongs to the golden years: the Republic functioned, but it was not',
        'loved.',
        '',
        'The error of these years was the belief that the danger was over. The',
        'NSDAP won 2.6 percent in the Reichstag election of 1928. Whoever took it',
        'seriously back then was considered hysterical. The upswing stood on',
        'short-term American credits; in October 1929 the New York stock exchange',
        'collapsed, and in the same month Stresemann died at the age of 51. The',
        'Republic lost its most capable politician at the moment when it would',
        'have needed him most urgently.',
        '',
        '## From 1930 on: the democracy is hollowed out by its guardians',
        '',
        'Here lies the most uncomfortable place of this whole narrative, and it',
        'belongs not to the enemies of the Republic but to its administrators.',
        '',
        'In March 1930, the last parliamentary government of the Republic broke',
        'apart over a question of unemployment insurance — over half a percentage',
        'point of contributions. Reich President Hindenburg appointed Heinrich',
        'Brüning of the Centre Party as Chancellor, without the latter having a',
        'majority. When the Reichstag rejected Brüning’s austerity package in July',
        '1930, he put it into force by emergency decree under Article 48 — and,',
        'when the Reichstag demanded its repeal, had the parliament dissolved.',
        'From then on, government was conducted without a majority approving: in',
        '1930 there were five emergency decrees and 94 Reichstag sessions, in 1932',
        'there were 66 emergency decrees and 13 sessions. The parliament hardly',
        'met any more.',
        '',
        'Two things about this were fateful. First the policy itself: Brüning',
        'saved his way into the Great Depression — wages, salaries and benefits',
        'were cut by decree, while unemployment rose from three million (1930) to',
        'over six million (early 1932). He did it for comprehensible reasons: he',
        'wanted to prove that the reparations could not be paid, and after 1923 he',
        'feared nothing as much as a new inflation. The result was nevertheless',
        'that millions of people associated democracy with hardship.',
        '',
        'Second, the form: the new election of September 1930 made the NSDAP the',
        'second-strongest party with 18.3 percent. The Reichstag that Brüning had',
        'had dissolved in order to become freer was afterwards more ungovernable',
        'than before. And the habituation was there. Whoever has got used, for',
        'three years, to laws coming from the palace of the Reich President',
        'instead of from parliament will notice nothing new in 1933. The emergency',
        'decrees were passed in order to save the Republic. They laid ready the',
        'instruments with which it was abolished. This is no reproach in',
        'hindsight — Social Democrats and Liberals said it back then.',
        '',
        '## The underestimation: "we hired him"',
        '',
        'Hardly anyone in the republican camp took Hitler for what he was. Some',
        'saw a loudmouth from Munich whose movement would wear itself out under',
        'the responsibility of government. Others considered him a tool that one',
        'could use and then set aside. From Franz von Papen the sentence is',
        'handed down that one had "hired" Hitler — within two months one would',
        'have pushed him so far into a corner that he would squeak. Hindenburg',
        'disparagingly called him the "Bohemian corporal" and appointed him',
        'nevertheless.',
        '',
        'Added to this was the disunity of those who should have defended the',
        'Republic — the second great uncomfortable place of this voice. The SPD',
        'supported Brüning in order to prevent worse, and lost voters to the',
        'Communists over it. The KPD fought the Social Democrats as "social',
        'fascists" and saw in the National Socialists a transitional phenomenon',
        'after which it would be one’s own turn. In Prussia, the largest state of',
        'the Reich, a stable republican coalition under the Social Democrat Otto',
        'Braun had governed for years — until Papen, on 20 July 1932, removed the',
        'entire Prussian government by emergency decree and made himself Reich',
        'Commissioner. This government had the police of the largest German state',
        'behind it. It offered no resistance but went before the Reich Court in',
        'Leipzig. The verdict of October 1932 turned out half-hearted; the removal',
        'remained.',
        '',
        'One can understand the decision: a civil war against the Reichswehr, with',
        'six million unemployed at one’s back, would presumably not have saved the',
        'Republic either. But on that day, the strongest republican position of',
        'power in the country gave way without a fight, and everyone saw it. Six',
        'months later Hitler was Chancellor.',
        '',
        '## Why people voted for the enemies of the Republic',
        '',
        'This voice cannot avoid representing the motives of the other sides',
        'fairly — otherwise it explains nothing in the end.',
        '',
        'The **Communists** had a reason for their distrust that one cannot argue',
        'away: in 1919, a Social Democratic government had had Freikorps shoot at',
        'workers, and the murderers of Rosa Luxemburg had remained unpunished.',
        'Whoever had experienced that no longer believed a word the SPD said. That',
        'the KPD made of this the thesis of "social fascism" and sought the main',
        'enemy on the left instead of the right was a fateful mistake — but it',
        'grew on real ground that Social Democracy itself had helped to create.',
        '',
        'The **Conservatives** had not wanted the Republic. For many of them,',
        'parliamentary democracy was a Western import, "un-German", a state of',
        'contention where there should be authority. They came from a state in',
        'which the Kaiser ruled and civil servants served, and they feared',
        'Bolshevism like a natural catastrophe. Their goal was mostly not the',
        'dictatorship of an Adolf Hitler but an authoritarian order without',
        'parties — and precisely for that reason they considered him usable. They',
        'were mistaken to an extent for which there are few comparisons.',
        '',
        'And the **voters of the NSDAP**: in 1930 and 1932, millions of people',
        'voted for a party that had never made a secret of its contempt for',
        'democracy. Many of them had lost the war, lost their savings in the',
        'inflation and then their jobs; they felt Versailles as a humiliation and',
        'the Republic as a sequence of governments that did not improve their',
        'situation. The NSDAP promised work, order, pride and a culprit for',
        'everything. Whoever wants to understand why that had an appeal must take',
        'these experiences seriously.',
        '',
        'Taking seriously, however, does not mean glossing over. What this party',
        'wanted stood open from the beginning: in the party programme of 1920,',
        'which denied Jews citizenship, in "Mein Kampf", in the speeches, in the',
        'violence of the SA on the streets. Nobody had to guess in 1932 what would',
        'come if these people got the state. Hardship explains an electoral',
        'decision; it does not justify what followed from it.',
        '',
        '## 1932/33: the last months',
        '',
        'In spring 1932, Hindenburg was re-elected — with the votes, of all',
        'people, of the Social Democrats who had fought him in 1925, because he',
        'now counted as the lesser evil against Hitler. A few weeks later he',
        'dismissed Brüning and made Franz von Papen Chancellor, a man without',
        'support in the Reichstag. Papen removed the Prussian government, had the',
        'Reichstag dissolved — and the NSDAP became the strongest party in July',
        '1932 with 37.4 percent. In the next election in November, it fell back to',
        '33.1 percent; the party was in financial difficulty, and some in its',
        'leadership considered the peak to have passed. The NSDAP never achieved a',
        'majority in a free election.',
        '',
        'What happened afterwards did not happen at the ballot box but in back',
        'rooms. General Kurt von Schleicher became Chancellor and failed within',
        'eight weeks. Papen, offended and intent on returning, met Hitler on 4',
        'January 1933 in the house of a Cologne banker and agreed on a government',
        'in which Hitler was to be Chancellor — flanked by conservative ministers',
        'who would keep him in check. On 30 January 1933, Hindenburg appointed him',
        'Reich Chancellor. In this cabinet sat, besides Hitler, only two further',
        'National Socialists. The calculation worked out within four weeks — for',
        'the other side.',
        '',
        'On 27 February 1933, the Reichstag burned. As early as the next day,',
        'Hindenburg signed the "Decree for the Protection of People and State",',
        'which suspended the fundamental rights of the Weimar constitution — based',
        'on Article 48, the same provision with which government had been',
        'conducted for three years. Thousands of political opponents were',
        'arrested. The election of 5 March took place under these conditions; the',
        'NSDAP won 43.9 percent, a majority only together with its coalition',
        'partner.',
        '',
        'On 23 March 1933, the Reichstag voted in the Kroll Opera House on the',
        'Enabling Act, which transferred legislation to the government. The',
        'deputies of the KPD were arrested or on the run, SA men stood in the',
        'hall. 94 Social Democrats voted against it; their chairman Otto Wels held',
        'the last free speech of the German parliament: "Freedom and life can be',
        'taken from us, not honour." All other parties agreed, including the',
        'Centre Party, which had co-founded the Republic. With that, the first',
        'German democracy was ended — not by a foreign army, but in its own',
        'forms.',
        '',
        '## What this voice can say in the end — and what not',
        '',
        'It can say that this Republic was better than its reputation: it made a',
        'constitution out of a defeat, survived the inflation, came to an',
        'understanding with its wartime enemies and, in fourteen years, produced a',
        'culture from which the world still lives today. It can say that its',
        'defenders were no cowards: the general strike against the Kapp Putsch of',
        '1920 came from the trade unions, the Reichsbanner mobilized hundreds of',
        'thousands, the 94 no-votes of 23 March 1933 were cast by people who knew',
        'what was in store for them.',
        '',
        'And it must say where it itself failed: at the alliance with the old',
        'powers of 1918, which left the enemies of the Republic in their offices;',
        'at a judiciary that it did not touch; at a division of the workers’',
        'movement that it had helped to bring about; at the readiness, from 1930',
        'on, to govern without parliament because it was more convenient; at the',
        'refusal to defend its own position of power in July 1932; and at a',
        'self-assurance that did not take seriously a man who had publicly',
        'announced for years what he would do.',
        '',
        '## And the other side?',
        '',
        'What this voice cannot tell is how all of this felt from below — for',
        'those who were supposed to be protected by the Republic and were not, and',
        'for those for whom 1933 was not the end of a form of state but the',
        'beginning of persecution. Jewish Germans, whose equality had stood in the',
        'constitutional text since 1919 while agitation on the street was an',
        'everyday occurrence. Communists, whose comrades had been shot by Freikorps',
        'in 1919 and who, from February 1933 on, were the first to come to the',
        'camps. Social Democrats and trade unionists, whose houses were occupied in',
        'May 1933. The unemployed, whose benefits were cut by emergency decrees.',
        'People at the margin, whom no party represented.',
        '',
        'The second voice of this chapter — the view of the persecuted and',
        'disenfranchised — is of equal weight with this one. Without it, the',
        'answer to the question of the hook would remain a half answer. Only both',
        'together produce the picture: a democracy that was meant sincerely by its',
        'builders and was co-damaged by its builders — and people for whom the',
        'difference between a damaged democracy and no democracy decided over',
        'life and death.',
      ].join('\n'),
    },
    {
      id: 'verfolgte-sicht',
      name: 'The view of the persecuted and disenfranchised',
      stimme: 'Hermes',
      text: [
        'This voice does not tell the story from the cabinets but from below —',
        'from the streets, the back courtyards, the apartments, the party',
        'offices, the synagogues and the trade union houses. It is the voice of',
        'those whom the dictatorship hit first: the Jewish Germans, whose',
        'equality had stood in the constitutional text since 1919 while the',
        'agitation on the street was an everyday occurrence; the Communists,',
        'whose comrades had already been shot by Freikorps in 1919 and who, from',
        'February 1933 on, were the first to come to the camps; the Social',
        'Democrats and trade unionists, whose houses were occupied in May 1933;',
        'the unemployed, whose benefits were cut by emergency decrees; the people',
        'at the margin, whom no party represented.',
        '',
        'It is of equal weight with the first voice — that it stands last here is',
        'no ranking but simply the order in which it was written. And it has one',
        'advantage and one blind spot. The advantage: it can tell how the end of',
        'the democracy felt from below — not as a sequence of decisions but as a',
        'sequence of days on which the world became narrower. The blind spot:',
        'this voice tends to whitewash its own side. The persecuted, too, were no',
        'mere victims without a share of their own — they were at odds with one',
        'another, often blind to the danger, and some dealt with the situation in',
        'a way that they themselves no longer understood later. This voice names',
        'that, because it is true.',
        '',
        '## What the Republic was for them first',
        '',
        'Whoever wants to hear this voice must first hear what the Weimar',
        'Republic was for those whom it later did not protect. For many it was',
        'first a liberation: the women’s suffrage of 1919 applied to all,',
        'equality stood in the law, Jews were citizens with equal rights, the',
        'trade unions had co-determination for the first time, the eight-hour day',
        'was anchored as a goal. In the Jewish communities of Berlin and',
        'Frankfurt, a self-confident life flourished; Jewish Germans were',
        'everywhere part of science, medicine, art and politics. Many of them',
        'felt, in 1919, truly German for the first time — and precisely in that',
        'lay their later vulnerability.',
        '',
        'And this voice must name what this Republic also was for them: a',
        'democracy that treated its enemies unequally. The judiciary that was',
        'blind in the right eye. The street violence of the early years, against',
        'which the state often intervened only when it was too late. The hate',
        'sheets that wrote year after year against "the Jews" and that nobody',
        'banned, because freedom of expression also applied to hatred. Whoever',
        'wanted to say in 1933 that one had seen nothing coming had not looked.',
        '',
        '## This voice’s own uncomfortable place: the fragmentation',
        '',
        'The hardest truth of this voice is its own powerlessness — and its own',
        'discord. The Left stood divided in 1933 where it should have stood',
        'together. The KPD called the Social Democrats "social fascists" and the',
        'main enemy on the right instead of the left; the SPD kept its distance',
        'from the Communists, whose leadership in Moscow looked to Berlin. When',
        'the NSDAP became the second-strongest party in 1930, the two workers’',
        'parties demonstrated separately — and were defeated separately. The KPD',
        'hoped even in January 1933 that Hitler would wear out "the bourgeoisie";',
        'the SPD hoped for the constitutional state that would protect them. Both',
        'hopes were mistakes, and this voice calls them by name: the persecuted,',
        'too, underestimated the danger — not because they were stupid, but',
        'because they judged the Republic by its own rules and not by the rules of',
        'those who wanted to abolish it.',
        '',
        'And it must name a second uncomfortable place: the antisemitism that did',
        'not begin only with Hitler and did not sit only in the SA barracks. It',
        'was at home in the offices, the universities, the clubs and many living',
        'rooms, long before 1933. The Republic did little against it — but also',
        'the democratic parties, also parts of the workers’ movement, rarely',
        'stood up loudly against it. When the NSDAP became the strongest party in',
        'many middle-class neighbourhoods in 1932, that was no operational',
        'accident but a finding.',
        '',
        '## 1933: the first hundred days',
        '',
        'What happened after 30 January 1933 happened quickly — faster than most',
        'considered possible. Already in the night after the Reichstag Fire, on',
        '28 February 1933, thousands were arrested; most of them were Communists.',
        'In March 1933, the first of the great concentration camps arose near',
        'Dachau, in which initially above all political opponents disappeared —',
        '"for improvement", as the language of the perpetrators put it. On 1',
        'April 1933, the SA called for a boycott of Jewish shops, doctors and',
        'lawyers; SA guards stood in front of the shops, many customers stayed',
        'away. On 7 April 1933, Jewish and "politically unreliable" civil',
        'servants were removed from service. On 2 May 1933, the houses of the',
        'trade unions were occupied, their funds confiscated, their leaders',
        'arrested. And on 10 May 1933, on the squares of the university cities,',
        'the books burned — works by Heinrich Mann, Erich Kästner, Sigmund Freud,',
        'Kurt Tucholsky, by Marx and the Mann brothers. Whoever saw that on one',
        'of these squares knew exactly what was burning here: thoughts.',
        '',
        'This voice tells these days not as a row of numbers but as what they',
        'were: individual days in the lives of individual people. The day on',
        'which the Jewish doctor learned of his hospital ban. The day on which',
        'the trade unionist found his office locked. The day on which the child',
        'came home from school and asked why it was no longer allowed to play',
        'along. The day on which someone packed the suitcase.',
        '',
        '## Emigration: to go or to stay',
        '',
        'Between 1933 and 1941, around half a million people left the German',
        'Reich — most of them Jewish Germans. Scientists like Albert Einstein and',
        'the Mann brothers left early; those who stayed stayed for the most',
        'varied reasons: out of age, out of concern for relatives, out of the',
        'hope that it would pass, out of the belief that one would "hold out".',
        'This voice does not condemn those who stayed — it knows how hard it was',
        'to leave a life. But it also names the illusion in it: most of those who',
        'stayed could not know what would come — and precisely that made their',
        'decision so human and so tragic. Abroad did not take everyone in for a',
        'long time; many who wanted to go were not allowed to. The emigration was',
        'no orderly exodus but a stream of individual decisions under pressure.',
        '',
        '## Staying fair: the other sides',
        '',
        'This voice must also represent the motives of the other sides fairly,',
        'otherwise it explains nothing. The republicans who had built the',
        'democracy were no traitors — the first voice named their mistakes',
        'itself: the alliance with the old army, the emergency decrees, the',
        'underestimation of Hitler. Nor were the millions who in 1932 did not',
        'vote for the NSDAP but looked away out of despair or indifference all',
        'evil — many were tired, many were afraid, many thought it would only hit',
        'others. And the NSDAP voters: whoever wants to understand why people',
        'voted for a party that openly spoke of annihilation must take the',
        'humiliation of Versailles, the inflation and the unemployment seriously',
        '— without making an excuse out of it. The perpetrators remain',
        'responsible even when one understands their motives. This voice draws',
        'exactly this line: explaining is not excusing.',
        '',
        '## And the other side?',
        '',
        'What this voice cannot tell is the other side of the same chapter: how',
        'the Republic felt from above, for those who built and defended it — the',
        'negotiations, the concessions, the deliberations in the cabinets, the',
        'desperate attempts to prevent the worst. The first voice of this chapter',
        'tells exactly that, more honestly than many memoirs do. Only both voices',
        'together produce the picture: a democracy that was meant sincerely by',
        'its builders and was co-damaged by its builders — and people for whom',
        'the difference between a damaged democracy and no democracy decided over',
        'life and death.',
        '',
        '## What remains',
        '',
        'What this voice can say in the end is simple: it was not numbers that',
        'began to yield in 1933 but people with names. The book burning of 10 May',
        '1933 burned works, not authors — but the authors left the country or',
        'disappeared. The memory of the first German democracy belongs to both',
        'voices: to the builders who meant it sincerely and to the persecuted who',
        'paid first. And the lesson from 1933 that this voice can pass on is a',
        'simple one: a democracy is measured by how it treats those who stand at',
        'the margin — for those at the margin see first when it tips over.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Two voices belong to this chapter, and both speak now. The first tells the',
    'Weimar Republic from the middle of power — from the cabinets, the National',
    'Assembly, the editorial offices and the trade union houses. The second',
    'tells the same chapter from below — from the streets, the back courtyards',
    'and the apartments of those whom the dictatorship hit first. Both are of',
    'equal weight; which one was written first is no ranking.',
    '',
    'Where they meet: they use the same facts, the same forks in the road —',
    'November 1918, Weimar 1919, the inflation of 1923, the emergency decrees',
    'from 1930 on, 20 July 1932, 30 January 1933 — and both say the same thing',
    'about the decisive question of this chapter: the Republic was not',
    'conquered but hollowed out from within, and it also failed because of its',
    'own guardians. The first voice names these mistakes itself — the alliance',
    'with the old army leadership, the Freikorps, the untouched judiciary,',
    'governing without parliament, the underestimation of Hitler, the disunity',
    'of those who wanted to defend the same Republic. The second voice confirms',
    'this from its experience: whoever watched from below how the Republic',
    'treated its enemies unequally knew earlier that it would tip over.',
    '',
    'Where they diverge is the yardstick. Whoever decides calculates in',
    'cabinets, majorities and deadlines; whoever is affected calculates in',
    'apartments, jobs and lives. For the one side, the Republic was a building',
    'that had to be secured against storms; for the other, a roof that was not',
    'watertight in decisive places — not in 1919, not in 1923, not in 1930, and',
    'in 1933 not at all any more. Both calculations use the same numbers and',
    'arrive at different sums. And they also diverge in what 1933 meant for',
    'them: for the one, the end of a form of state that they had built; for the',
    'other, the beginning of persecution that began with names, faces and',
    'suitcases.',
    '',
    'Both voices name their own uncomfortable places — the first the mistakes of',
    'the guardians, the second the fragmentation of the persecuted and the',
    'antisemitism that was older than the NSDAP. And both represent the motives',
    'of the other side fairly, without trivializing: the first explains why',
    'people voted for Hitler; the second explains why the republicans could not',
    'save what they had built.',
    '',
    'What remains is the lesson that both carry together: a democracy is',
    'measured by how it treats those who stand at the margin — and it does not',
    'die from a single blow but from many small concessions that individually',
    'seem comprehensible. Only both voices together produce the whole picture;',
    'neither of them is "that is how it was".',
  ].join('\n'),

  urteil: {
    frage: 'The Weimar Republic was not conquered but hollowed out from within — with emergency decrees that its own defenders passed, and with an appointment that was constitutional. What should a democracy have had to do at this point, and how does one even recognize that a democracy is in danger?',
    hinweis: 'There is no right and no wrong here. A thought to think on: some say a democracy must be capable of defending itself and, if necessary, fight its enemies with their own means — others consider precisely that to be the first step with which it abolishes itself. Both sides invoke 1933. What do you think?',
  },

  quiz: [
    {
      frage: 'Why did the National Assembly meet in Weimar in 1919 and not in Berlin?',
      antworten: [
        'Because there was armed fighting in Berlin and the deputies wanted to work undisturbed.',
        'Because Berlin was still occupied by French troops at that time.',
        'Because the constitution stipulated that parliaments must meet outside the capital.',
      ],
      richtig: 0,
      erklaerung: 'In January 1919 there was fighting in Berlin. Weimar was considered calm and easy to secure — and the name of the city of Goethe and Schiller was meant to give the new state a different face than that of the barracks.',
    },
    {
      frage: 'What was new about the German suffrage in 1919?',
      antworten: [
        'For the first time, women were also allowed to vote and stand for election.',
        'For the first time, one was allowed to vote from the age of 16.',
        'For the first time, the government was elected directly by the people.',
      ],
      richtig: 0,
      erklaerung: 'In the election to the National Assembly on 19 January 1919, men and women from the age of 20 were allowed to vote. 82 percent of those eligible went to the polls, 37 women moved into parliament.',
    },
    {
      frage: 'What did Article 48 of the Weimar constitution regulate?',
      antworten: [
        'It allowed the Reich President to govern by decrees in emergencies and to suspend fundamental rights.',
        'It stipulated that the Reichstag is re-elected every four years.',
        'It banned parties that rejected the constitution.',
      ],
      richtig: 0,
      erklaerung: 'Article 48 was conceived as an emergency tool. From 1930 on, government was conducted with it permanently: in 1932, the Reich President issued 66 emergency decrees, while the Reichstag met only 13 times.',
    },
    {
      frage: 'What caused the devaluation of money to get completely out of control in 1923?',
      antworten: [
        'The Reich paid for the strike against the occupation of the Ruhr with freshly printed money.',
        'The Allies suddenly demanded the reparations in gold instead of goods.',
        'An earthquake destroyed the Reichsbank in Berlin.',
      ],
      richtig: 0,
      erklaerung: 'The devaluation had been running since the war financing of 1914. When the Reich in 1923 paid the wages of the passive resistance in the occupied Ruhr from the printing press, it tipped into hyperinflation. In November 1923, the Rentenmark ended it.',
    },
    {
      frage: 'How did Adolf Hitler become Reich Chancellor on 30 January 1933?',
      antworten: [
        'Reich President Hindenburg appointed him after negotiations by conservative politicians.',
        'His party had won the absolute majority in the election of November 1932.',
        'The Reichstag elected him Chancellor with a two-thirds majority.',
      ],
      richtig: 0,
      erklaerung: 'The NSDAP never achieved a majority in a free election — in July 1932 it reached 37.4 percent, in November 33.1. Hitler came into office through the appointment of the Reich President, arranged by conservatives who believed they could frame him in.',
    },
  ],
};

module.exports = weimarNs;
