// Thema: Der Aufstieg Asiens und die Zukunft des Westens (1945 bis heute).
//
// Stand: Runde 22 + Hermes-Pass. Dies ist der ABSCHLUSS der App — das
// dreizehnte und LETZTE Kapitel des Neuzeit-Bogens. Vier Stimmen sind
// fertig: die Sicht des Westens (Deutschland und Europa, Stimme: Opus),
// die Sicht Japans, Südkoreas und Taiwans (die „fliegenden Gänse",
// Stimme: Hermes), die Sicht Chinas (Stimme: Hermes) und die Sicht Indiens
// (Stimme: Hermes). Die finale Synthese endet bewusst offen — mit einer
// Frage an die Zukunft, nicht mit einem Punkt.
//
// Zwanzigstes Thema. Es beginnt dort, wo „Der Zweite Weltkrieg und die neue
// Weltordnung" endet: 1945, in Trümmern — und erzählt, wie aus den Trümmern
// binnen einer Generation Wirtschaftswunder wurden, zuerst in Westeuropa und
// Japan, dann in immer weiteren Ländern Ostasiens. Anders als in den zwölf
// Kapiteln davor ist der Gegenstand dieses letzten Kapitels nicht
// abgeschlossen — und er soll es nach Betreiber-Vorgabe auch nicht sein: Die
// App beginnt mit der Leitidee „Der Sieger schreibt die Geschichte", und
// dieses letzte Kapitel zeigt, dass eine Geschichte, die noch geschrieben
// wird, niemand abschließend schreiben kann.
//
// TONE-REGEL (CLAUDE.md, Zusatzregel für Themen mit Gegenwartsbezug). Die
// Betreiber-These „Deutschland ein sterbendes Land, Europa ein alter
// Kontinent mit wenig Zukunft?" wird FAIR behandelt: relativer
// Bedeutungsverlust ja, absoluter Absturz nein — „Aufholen" ist nicht
// dasselbe wie „Überholen". Deshalb gilt hier, strenger als sonst:
//
//   * Diese Perspektive benennt ihre unbequemen Stellen selbst: die
//     Exportabhängigkeit, die versäumte Digitalisierung, die demografische
//     Alterung, die German Angst vor dem eigenen Abstieg.
//   * Sie würdigt den asiatischen Aufstieg fair — keine Herablassung
//     („Kopierer, keine Erfinder"), keine German-Angst-Rhetorik
//     („die überholen uns alle"), sondern Fakten und Zahlen.
//   * Die Taiwan-Frage und die chinesische Systemfrage werden sachlich und
//     faktenbasiert behandelt, ohne Wertung — die Karte entscheidet nichts,
//     sie zeichnet, wer wo regiert (Kopf der Kartendatei, Festlegung 4).
//   * Die Quizfragen bleiben Wissensfragen. Nach Schuld oder danach, wessen
//     System „besser" ist, fragt diese App nicht.
//
// Die Karte liegt in karten/aufstieg-asiens.js — drei Zustände (1955–1968 /
// 1990 / 2024) und mit 4,5 SVG-Einheiten je Längengrad der gröbste Ausschnitt
// der App, weil Frankfurt und Tokio auf ein Bild müssen. Warum der Ausschnitt
// so steht, wie er steht, und was er kostet (vor allem: die USA liegen
// außerhalb), steht im Kopf der Kartendatei.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/aufstieg-asiens');

const aufstiegAsiens = {
  id: 'aufstieg-asiens',
  titel: 'Der Aufstieg Asiens und die Zukunft des Westens',
  epoche: '1945–heute',

  aufhaenger: {
    frage: 'Der Kontinent, der 1945 in Trümmern lag, stellt heute mit Deutschland die drittgrößte Volkswirtschaft der Welt. Der Kontinent, der 1955 zu den ärmsten der Welt gehörte, stellt heute mit China die zweitgrößte. Ist das eine Geschichte des westlichen Abstiegs — oder zweier Aufstiege zugleich?',
    text: [
      'Im Mai 1945 lagen die meisten deutschen Großstädte in Trümmern, rund',
      'acht Millionen Menschen waren auf der Flucht oder vertrieben, und die',
      'Industrieproduktion war auf einen Bruchteil des Vorkriegsstands',
      'gefallen. 1961 kam Südkorea auf rund 100 US-Dollar Wirtschaftsleistung',
      'je Einwohner — weniger als Ghana. China erlebte in denselben Jahren mit',
      'dem „Großen Sprung nach vorn" eine selbst verursachte',
      'Hungerkatastrophe mit Millionen Toten.',
      '',
      'Weniger als eine Generation später war die Bundesrepublik die',
      'drittgrößte Volkswirtschaft der Welt. Weniger als zwei Generationen',
      'später war China die zweitgrößte, Südkorea reicher als manches',
      'westeuropäische Land, und auf einer Insel namens Taiwan entstanden',
      'neun von zehn der modernsten Halbleiter der Welt.',
      '',
      'Dieses letzte Kapitel der App erzählt von zwei Aufstiegen, die',
      'gleichzeitig stattfanden, und von der Frage, die daraus wurde: Verliert',
      'der Westen, weil Asien gewinnt? Oder ist das die falsche Frage — weil',
      'Wirtschaft, anders als ein Krieg, kein Nullsummenspiel ist? Ganz am',
      'Ende steht eine These, die der Betreiber dieser App ausdrücklich',
      'gestellt haben wollte: Ist Deutschland ein sterbendes Land, Europa ein',
      'alter Kontinent mit wenig Zukunft? Die App gibt darauf keine fertige',
      'Antwort — dieses Kapitel endet bewusst offen, mit einer Frage an die',
      'Zukunft, nicht mit einem Punkt. Es beginnt mit der Sicht des Westens.',
      'Das ist eine von mehreren Stimmen, nicht die einzige, und dass sie hier',
      'zuerst steht, ist keine Rangfolge.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'Die Sicht des Westens — Deutschland und Europa',
      stimme: 'Opus',
      text: [
        'Diese Stimme erzählt aus Frankfurt, Bonn, Brüssel und Berlin: aus der',
        'Wirtschaft, die 1945 bei null anfing und heute zu den stärksten der',
        'Welt gehört — und die zugleich weiß, dass sie relativ an Gewicht',
        'verliert, während anderswo aufgeholt wird.',
        '',
        'Sie ist gleichwertig mit den Stimmen, die noch folgen. Dass sie hier',
        'zuerst steht, ist keine Rangfolge — es liegt nur daran, wer diese',
        'Runde übernommen hat. Und',
        'sie hat, wie schon die vorherige Perspektive im vorigen Kapitel, eine',
        'besondere Aufgabe: Dieses Kapitel ist nicht abgeschlossen. Die',
        'Gegenwart, von der es handelt, ist noch offen — und jede Zahl in',
        'diesem Text ist ein Stand, kein Endergebnis.',
        '',
        '## 1945: der Nullpunkt, der keiner war',
        '',
        'Am Ende des Zweiten Weltkriegs war Deutschland zerstört, aber nicht',
        'entkernt. Diese Unterscheidung ist wichtig, und sie wird oft',
        'übersehen. Die „Stunde Null" war ein Gefühl, kein wirtschaftlicher',
        'Befund: Ingenieure, Facharbeiter, Verwaltungswissen und',
        'Ausbildungssysteme überstanden den Krieg besser als die Gebäude.',
        'Ökonomen sprechen deshalb heute eher von einer schnellen',
        'Wiederherstellung als von einem Wunder — der Kapitalstock war',
        '1945 tatsächlich nicht viel niedriger als 1936, weil auch während',
        'des Krieges investiert worden war.',
        '',
        'Was fehlte, war Geld, das umlief, und ein Markt, der funktionierte.',
        'Am 20. Juni 1948 änderte die **Währungsreform** das: Aus der',
        'wertlosen Reichsmark wurde die D-Mark, jede Person bekam vierzig',
        'Mark „Kopfgeld", und über Nacht füllten sich die Schaufenster — nicht,',
        'weil plötzlich mehr Waren da waren, sondern weil sich Horten nicht',
        'mehr lohnte. Ludwig Erhard hob am selben Wochenende, gegen den',
        'Widerstand der Militärregierung, einen Großteil der',
        'Preiskontrollen auf. Damit begann, was als **Soziale',
        'Marktwirtschaft** in die Geschichte einging: freie Preise UND ein',
        'Sozialstaat, der die Härten abfedern sollte — ein Mittelweg',
        'zwischen dem ungebremsten',
        'Kapitalismus, den viele fürchteten, und der Planwirtschaft, die im',
        'Osten des Landes entstand.',
        '',
        'Der **Marshallplan** kam dazu, aber kleiner, als die Legende sagt:',
        'Von den rund 13 Milliarden Dollar, die zwischen 1948 und 1952 an',
        'sechzehn Länder flossen, gingen etwa 1,4 Milliarden nach',
        'Westdeutschland — gemessen an der westdeutschen Wirtschaftsleistung',
        'ein eher kleiner Betrag. Entscheidend war weniger die Summe als die',
        'Wirkung: Rohstoffe und Devisen genau dann, als beides fehlte, und',
        'ein Zwang zur wirtschaftlichen Zusammenarbeit, den die',
        'Empfängerländer sich gegenseitig auferlegten und aus dem später die',
        'Europäische Wirtschaftsgemeinschaft wurde.',
        '',
        'Dazu kam etwas, das sich schwerer in Zahlen fassen lässt: acht',
        'Millionen Vertriebene aus den ehemaligen Ostgebieten, die',
        'integriert werden mussten und die, so hart es klingt, vor allem',
        'eines waren — zusätzliche Arbeitskräfte in einem Land, das sie',
        'brauchte. Und ein Bildungssystem mit einer langen Tradition in',
        'Technik und Ingenieurwesen, das nach 1945 rasch wieder',
        'ausbildungsfähig war. Das „Wirtschaftswunder" der 1950er Jahre —',
        'im Schnitt rund acht Prozent Wachstum im Jahr — war deshalb kein',
        'Wunder, sondern eine Rechnung aus mehreren Posten. Wichtig ist',
        'auch: Es war nicht einzigartig. Frankreich, Italien und, wie das',
        'Kapitel gleich zeigen wird, Japan wuchsen in denselben Jahren',
        'ähnlich schnell. Wer nur die deutsche Geschichte kennt, hält für',
        'ein deutsches Wunder, was ein Muster des westeuropäischen',
        'Wiederaufbaus war.',
        '',
        '## Was daraus wurde: eine der stärksten Volkswirtschaften der Welt',
        '',
        'Aus diesem Anfang wurde über acht Jahrzehnte eine Volkswirtschaft,',
        'die 2024 mit rund 4,7 Billionen Dollar die drittgrößte der Welt',
        'ist — hinter den USA und China, vor Japan, Indien und',
        'Großbritannien. Die sechs Gründerstaaten der Europäischen',
        'Wirtschaftsgemeinschaft von 1957 sind heute Teil einer Union mit',
        '27 Mitgliedern, die zusammen für rund ein Sechstel der',
        'Weltwirtschaft stehen. Drei Stärken tragen das bis heute:',
        '',
        '**Export.** Deutschland ist seit Jahrzehnten eine der größten',
        'Exportnationen der Welt — Maschinenbau, Autos, Chemie, seit den',
        '2000er Jahren zunehmend auch spezialisierte Anlagentechnik, die',
        'kein anderes Land in derselben Tiefe herstellt. **Industrie.**',
        'Anders als Großbritannien oder die USA hat Deutschland seinen',
        'industriellen Kern nie in dem Maß verloren, wie es',
        '„Deindustrialisierung" in anderen westlichen Ländern seit den',
        '1980er Jahren beschreibt; der Anteil der Industrie an der',
        'Wirtschaftsleistung liegt bis heute deutlich über dem',
        'westeuropäischen Durchschnitt. **Stabile Währung und',
        'Institutionen.** Der Euro, verwaltet von der Europäischen',
        'Zentralbank in Frankfurt, gehört zu den wichtigsten',
        'Reservewährungen der Welt; Deutschland gilt Investoren seit',
        'Jahrzehnten als eines der verlässlichsten Länder für Kapital, mit',
        'unabhängigen Gerichten, geringer Korruption und einer Bonität, die',
        'zu den höchsten der Welt zählt.',
        '',
        '## Die unbequemen Stellen — diese Stimme benennt sie selbst',
        '',
        'Wer nur die Stärken erzählt, erzählt Werbung. Vier Schwächen gehören',
        'ebenso in diese Bilanz, und der Westen selbst muss sie benennen.',
        '',
        '**Die Exportabhängigkeit.** Was Stärke ist, ist zugleich',
        'Verwundbarkeit. Als 2021 in Taiwan Halbleiter knapp wurden,',
        'standen deutsche Autowerke in Kurzarbeit — nicht wegen eines',
        'eigenen Fehlers, sondern weil ein einzelnes Bauteil aus einem',
        'einzigen Land fehlte. Als Russland 2022 kein Gas mehr lieferte,',
        'geriet die energieintensive Industrie unter Druck. Ein Land, das',
        'so viel exportiert, wie es importiert, ist reich UND abhängig —',
        'beides zugleich, nicht das eine trotz des anderen.',
        '',
        '**Die versäumte Digitalisierung.** Es gibt kein deutsches oder',
        'europäisches Gegenstück zu Google, Amazon, Apple, Meta oder',
        'Microsoft — und auch keines zu den großen chinesischen',
        'Digitalkonzernen. Die Gründe werden diskutiert (Kapitalmärkte,',
        'Regulierung, Risikoscheu, ein Bildungssystem, das auf',
        'Ingenieurwesen statt auf Software setzte) — der Befund selbst ist',
        'unstrittig: In der Software- und Plattformökonomie des',
        '21. Jahrhunderts spielt Europa nicht in der ersten Reihe.',
        '',
        '**Die Demografie.** Deutschland hat, wie fast der ganze Kontinent,',
        'eine alternde Gesellschaft: ein mittleres Alter von rund 46 Jahren',
        '(gegenüber 28 in Indien), eine Geburtenziffer von rund 1,5 Kindern',
        'je Frau seit Jahrzehnten deutlich unter dem Bestandserhaltungswert',
        'von 2,1, und eine wachsende Zahl von Rentnern auf eine langsamer',
        'wachsende Zahl von Erwerbstätigen. Der Fachkräftemangel ist keine',
        'Prognose mehr, sondern gegenwärtiger Alltag in Handwerk, Pflege und',
        'Technik.',
        '',
        '**Das langsame Wachstum.** Seit rund zwei Jahrzehnten wächst',
        'Deutschland langsamer als die meisten vergleichbaren',
        'Volkswirtschaften — im Schnitt der 2010er und 2020er Jahre unter',
        'einem Prozent im Jahr. Bürokratie, hohe Energiekosten, eine',
        'gealterte Infrastruktur (Brücken, Bahn, Breitband) und ein',
        'politisches System, das Reformen langsam beschließt, gehören zu',
        'den meistgenannten Gründen. Das ist kein Kollaps — es ist',
        'Stagnation, und Stagnation zehrt langsamer, aber genauso sicher.',
        '',
        '## „Ein sterbendes Land"? Was die Zahlen wirklich sagen',
        '',
        'Hier steht die Frage im Zentrum, die dieses Kapitel nach',
        'Betreiber-Vorgabe stellen soll — und die Antwort ist keine',
        'einzelne Zahl, sondern eine Unterscheidung, die leicht',
        'verwechselt wird: **relativ** und **absolut** sind zwei',
        'verschiedene Fragen.',
        '',
        '**Relativ** verliert Deutschland an Gewicht, und das ist',
        'unbestreitbar. 1960 stellten die westeuropäischen Volkswirtschaften',
        'zusammen einen deutlich größeren Anteil der Weltwirtschaft als',
        'heute — nicht weil sie schrumpften, sondern weil der Rest der Welt',
        'schneller wuchs. Wenn ein Kontinent mit 1,4 Milliarden Menschen',
        'von 2 Prozent der Weltwirtschaft (China 1990) auf rund',
        '18 Billionen Dollar und ein Sechstel der Weltwirtschaft (China',
        '2024) wächst, sinkt automatisch der Anteil jedes anderen Landes —',
        'selbst wenn dessen eigene Wirtschaft weiterwächst. Das ist Mathematik,',
        'keine Krankheit.',
        '',
        '**Absolut** ist Deutschland 2024 eine der stärksten',
        'Volkswirtschaften der Welt geblieben — die drittgrößte, mit einem',
        'Wohlstandsniveau, das historisch beispiellos ist. Die',
        'Lebenserwartung liegt bei rund 81 Jahren, die soziale Absicherung',
        'gehört zu den umfassendsten der Welt, die Infrastruktur ist trotz',
        'aller berechtigten Kritik im weltweiten Vergleich immer noch',
        'überdurchschnittlich. „Aufholen" ist nicht dasselbe wie',
        '„Überholen": China hat den Abstand zu Deutschland in der',
        'Wirtschaftsleistung je Einwohner in dreißig Jahren dramatisch',
        'verringert — von China lag 1990 bei rund einem Sechzigstel des',
        'deutschen Werts, 2024 bei etwa einem Viertel. Verringert, nicht',
        'geschlossen.',
        '',
        'Wer „sterbendes Land" sagt, meint meist das erste (relativ) und',
        'redet wie über das zweite (absolut). Diese Verwechslung ist der',
        'Kern vieler German-Angst-Debatten — und diese Stimme widersteht',
        'sowohl der Panikmache als auch der Beschönigung: Die Sorgen sind',
        'real (Demografie, Wachstum, Digitalisierung), aber sie sind keine',
        'Nahtoderfahrung. Ein Land mit den drittstärksten Exporten der',
        'Welt stirbt nicht — es altert, und Altern ist etwas anderes als',
        'Sterben.',
        '',
        '## Und was macht das mit dem Blick auf Asien?',
        '',
        'Diese Stimme will den asiatischen Aufstieg fair würdigen — ohne',
        'Herablassung und ohne German Angst. Beide Fehler kommen im',
        'öffentlichen Gespräch vor, und beide sind falsch.',
        '',
        'Herablassend ist die Erzählung, Asien habe „nur kopiert", was der',
        'Westen erfunden habe. Sie war schon in den 1980er Jahren gegenüber',
        'Japan falsch und ist es gegenüber Südkorea, Taiwan und China erst',
        'recht: TSMC in Taiwan fertigt heute Chips in Strukturgrößen, die',
        'kein westliches Unternehmen allein herstellen kann; Südkoreas',
        'Samsung und LG sind bei Displays und Speicherchips',
        'Weltmarktführer; Chinas Vorsprung bei Batterietechnik und',
        'Solarzellen ist real und selbst erarbeitet. Wer das kleinredet,',
        'redet sich selbst groß.',
        '',
        'Panisch ist die Erzählung, der Westen habe schon verloren. Auch',
        'sie ist falsch: Die USA bleiben mit rund einem Viertel der',
        'Weltwirtschaft die größte Volkswirtschaft der Welt, Europa bleibt',
        'einer der größten Binnenmärkte, und die Innovationskraft in Bio-',
        'und Pharmatechnik, in bestimmten Feldern der Spitzentechnologie und',
        'in der Grundlagenforschung ist ungebrochen hoch. Wirtschaft ist,',
        'anders als der Krieg, von dem die App in ihren früheren Kapiteln',
        'oft erzählt hat, kein Nullsummenspiel: Dass China und Indien',
        'wachsen, bedeutet nicht automatisch, dass Deutschland schrumpft —',
        'es bedeutet vor allem, dass Milliarden Menschen aus extremer Armut',
        'herausgekommen sind, und das ist, gemessen an jedem humanen',
        'Maßstab, eine gute Nachricht und keine Bedrohung.',
        '',
        '## Die eigenen Sorgen — und die der anderen',
        '',
        'Was diese Stimme am Ende festhalten will, ist eine Symmetrie, die',
        'im öffentlichen Gespräch oft fehlt: Auch der asiatische Aufstieg',
        'hat seine eigenen ungelösten Fragen, und sie sind nicht kleiner',
        'als die deutschen. Japan altert schneller als Deutschland und',
        'schrumpft bereits in absoluten Zahlen. China altert wegen der',
        'Ein-Kind-Politik von 1980 bis 2015 in einem Tempo, das Ökonomen',
        'als „alt werden, bevor man reich wird" beschreiben. Indien wächst',
        'schnell, aber mit einer Ungleichheit, die zwischen den',
        'IT-Metropolen und dem ländlichen Hinterland enorm ist. Und über',
        'Taiwan liegt eine politische Frage, die keine wirtschaftliche',
        'Kennzahl auflösen kann.',
        '',
        'Deshalb steht diese Stimme hier nicht allein. Die **Sichtweisen',
        'Asiens** — Japan, China, Indien, Südkorea und Taiwan, jedes mit',
        'eigenem Aufstieg, eigenen Kosten und eigenen offenen Fragen —',
        'schreibt Hermes; das Schema erlaubt hier ausdrücklich mehr als',
        'zwei Stimmen. Erst danach führt die endgültige Synthese zusammen,',
        'was zusammengehört — und stellt die Frage, mit der diese ganze App',
        'endet: Wessen Geschichte wird die nächste sein?',
      ].join('\n'),
    },
    {
      id: 'japan-sicht',
      name: 'Die Sicht Japans, Südkoreas und Taiwans — die fliegenden Gänse',
      stimme: 'Hermes',
      text: [
        'Diese Stimme erzählt aus Ostasien — aus Tokio, Seoul und Taipeh —',
        'und sie erzählt die Geschichte einer Formation, die Historiker die',
        '„fliegenden Gänse" nennen: Japan flog voran, und die anderen folgten',
        'in seiner Spur. Sie ist gleichwertig mit den Stimmen des Westens,',
        'Chinas und Indiens.',
        '',
        '## Japan — das erste Wunder',
        '',
        '1945 lag Japan in Trümmern: Hiroshima und Nagasaki, die',
        'zerbombten Städte, die besiegte Armee. Zwanzig Jahre später war',
        'Japan die zweitgrößte Volkswirtschaft der Welt. Wie? Diese Stimme',
        'nennt die Faktoren ehrlich: die amerikanische Hilfe und die',
        'Aufträge des Koreakriegs, den entschlossenen Staat (das',
        'Ministerium MITI lenkte die Industrie), die Banken, die',
        'Unternehmen mit billigem Geld versorgten, die Firmen wie Toyota,',
        'Sony und Honda, die Qualität nicht als Kosten, sondern als',
        'Strategie begriffen — und die Arbeiterinnen und Arbeiter, die',
        'für das Unternehmen lebten. Japan wurde zum Vorbild für ganz',
        'Asien: der Beweis, dass ein nicht-westliches Land den Westen',
        'einholen konnte.',
        '',
        'Dann kam 1989/91 die Blase: Die Aktien- und Immobilienpreise',
        'hatten sich von der Realität gelöst, und als sie platzten, folgte',
        'die **„verlorenen Jahrzehnte"** — Stagnation, Deflation, eine',
        'Gesellschaft, die älter wurde, ohne dass die Wirtschaft',
        'nachwuchs. Diese Stimme nennt das beim Namen: Der Übermut war',
        'echt, die Fehler der Banken und der Politik waren echt. Japan ist',
        'heute immer noch eine der größten Volkswirtschaften der Welt —',
        'aber es zeigt, dass Aufstieg keine Einbahnstraße ist.',
        '',
        '## Südkorea — vom Armenhaus zum High-Tech',
        '',
        '1960 war Südkorea ärmer als Ghana. Heute stellt es die',
        'Halbleiter, die Schiffe und die Smartphones, die die Welt',
        'benutzt. Der Weg dorthin war hart: Die **Chaebols** — die',
        'Familienkonzerne wie Samsung und Hyundai — wurden vom Staat',
        'gelenkt und subventioniert, und die Kehrseite war eine',
        '**Militärdiktatur**, die Jahrzehnte dauerte und Arbeiter und',
        'Studenten blutig unterdrückte (Gwangju 1980). Erst 1987 errang',
        'Korea die Demokratie — und es ist eine der großen Lektionen',
        'dieser Stimme, dass das Land nach der Demokratisierung',
        'wirtschaftlich nicht zusammenbrach, sondern weiterwuchs. Die',
        'Kultur kam dazu (K-Pop, die Serien), und mit ihr ein neuer',
        'Stolz. Die Schattenseiten bleiben: der Druck in der',
        'Gesellschaft, die Überarbeitung, die niedrigste Geburtenrate der',
        'Welt.',
        '',
        '## Taiwan — die kleine Insel, die die Welt versorgt',
        '',
        'Taiwan ist kleiner als Dänemark — und doch hängt die',
        'Weltwirtschaft an ihm. Der Grund heißt **TSMC**: das 1987',
        'gegründete Unternehmen, das die Idee hatte, Chips nicht nur für',
        'sich, sondern für alle zu fertigen — die „Foundry". Heute werden',
        'die modernsten Chips der Welt fast alle in Taiwan produziert;',
        'ohne sie liefe kein Smartphone, kein Auto, keine KI.',
        '',
        'Diese Stimme muss auch die Frage benennen, die über Taiwan',
        'liegt: China sieht die Insel als abtrünnige Provinz, Taiwan sieht',
        'sich als eigenes Land mit eigener Demokratie und eigenen',
        'Wahlen. Beide Sichtweisen stehen in diesem Kapitel nebeneinander',
        '— die App rechnet nicht auf, wer recht hat. Aber diese Stimme',
        'sagt, was alle drei Länder verbindet: Sie haben den Aufstieg',
        'nicht geschenkt bekommen — sie haben ihn erkämpft, oft gegen den',
        'Westen, oft mit dem Westen, und immer mit einem Preis.',
      ].join('\n'),
    },
    {
      id: 'china-sicht',
      name: 'Die Sicht Chinas — der Riese erwacht',
      stimme: 'Hermes',
      text: [
        'Diese Stimme erzählt aus Peking, Shanghai und Shenzhen — aus dem',
        'Land, das die größte Aufholjagd der Geschichte hingelegt hat: In',
        'vierzig Jahren ist China von einem armen Agrarland zur',
        'zweitgrößten Volkswirtschaft der Welt geworden, und Hunderte',
        'Millionen Menschen haben die Armut verlassen.',
        '',
        '## Von Mao zu Deng — die Wende von 1978',
        '',
        'Diese Stimme beginnt nicht mit dem Aufstieg, sondern mit dem',
        'Preis davor: Die **Kulturrevolution** (1966–1976) war eine',
        'Katastrophe — Millionen Tote, zerstörte Familien, eine Wirtschaft',
        'am Boden. Erst **Deng Xiaoping** führte China 1978 aus dieser',
        'Sackgasse. Sein Satz wurde berühmt: „Es ist egal, ob die Katze',
        'schwarz oder weiß ist — Hauptsache, sie fängt Mäuse." Deng',
        'öffnete das Land: die **Sonderwirtschaftszonen** (Shenzhen wurde',
        'aus einem Fischerdorf eine Stadt von 17 Millionen), die',
        'Bauern, die wieder für sich selbst arbeiten durften, die',
        'ausländischen Investoren, die willkommen waren. Was folgte, war',
        'das größte Wirtschaftswachstum der Geschichte: Jahrzehnte mit',
        'Wachstumsraten von rund zehn Prozent, Hunderte Millionen aus der',
        'Armut geholt.',
        '',
        '## Die Schattenseiten — diese Stimme nennt sie selbst',
        '',
        'Diese Stimme verschweigt nicht, was der Aufstieg kostete: die',
        '**Ein-Kind-Politik**, die eine Generation geprägt hat; die',
        'Umweltverschmutzung, die Städte erstickte; die wachsende',
        'Ungleichheit zwischen Küste und Hinterland; die Schulden; und',
        'die Politik: die **Niederschlagung der Proteste auf dem',
        'Tiananmen-Platz 1989**, die Unterdrückung der Uiguren in',
        'Xinjiang, die fehlende Pressefreiheit, die Überwachung. China',
        'ist keine Demokratie — das sagt diese Stimme ohne Umschweife.',
        'Und sie sagt auch: Viele Chinesen tragen diesen Kompromiss mit,',
        'weil sie den Aufstieg selbst erlebt haben — die Eltern, deren',
        'Kinder es besser haben; die Dörfer, die ans Stromnetz kamen. Ob',
        'dieser Kompromiss hält, ist eine der offenen Fragen, mit denen',
        'dieses Kapitel endet.',
        '',
        '## Der Preis der Größe — und die Zukunft',
        '',
        'China steht heute vor dem, was Japan früher erlebte: Die',
        'Bevölkerung altert — die Ein-Kind-Politik war so erfolgreich,',
        'dass China bald mehr Alte als Junge hat. Das schnelle Wachstum',
        'verlangsamt sich, die Immobilienkrise und die Schulden lasten,',
        'und die Welt schaut misstrauisch auf die Ambitionen Pekings —',
        'vom Südchinesischen Meer bis Taiwan. Diese Stimme sagt, was',
        'China erreicht hat, ohne die Kosten zu verschweigen: Der Riese',
        'ist erwacht — aber erwacht ist nicht dasselbe wie angekommen.',
      ].join('\n'),
    },
    {
      id: 'indien-sicht',
      name: 'Die Sicht Indiens — die größte Demokratie der Welt',
      stimme: 'Hermes',
      text: [
        'Diese Stimme erzählt aus Delhi, Mumbai und Bengaluru — aus dem',
        'Land, das seit 2023 mehr Einwohner hat als China und das die',
        'jüngste große Bevölkerung der Welt besitzt. Indien ist der',
        'demokratische Gegenentwurf zum chinesischen Weg — und diese',
        'Stimme erzählt, was das bedeutet.',
        '',
        '## Die lange Lähmung und die Wende von 1991',
        '',
        'Nach der Unabhängigkeit 1947 wählte Indien unter Nehru einen',
        'sozialistischen Weg: die Planwirtschaft, die „License Raj" —',
        'ein System, in dem fast alles genehmigt werden musste und fast',
        'nichts schnell ging. Jahrzehntelang wuchs Indien langsam — der',
        '„hindu rate of growth" wurde zum Spitznamen für den Stillstand.',
        '1991 kam die Wende: Eine Zahlungskrise zwang Indien zur',
        'Öffnung, Finanzminister Manmohan Singh hob die Fesseln auf, und',
        'die Folge war die **IT-Revolution**: Bengaluru wurde zum',
        'Software-Zentrum der Welt, Firmen wie Infosys und TCS, die',
        'indische Diaspora stieg in den USA zu den erfolgreichsten',
        'Führungskräften auf — die CEOs von Microsoft, Google und IBM',
        'waren plötzlich Inder. Indien bewies: Demokratie und',
        'Wachstum schließen sich nicht aus.',
        '',
        '## Die demografische Dividende',
        '',
        'Indiens größter Schatz ist seine Bevölkerung: Das Medianalter',
        'liegt bei etwa 28 Jahren — Europa ist doppelt so alt, China',
        'auch deutlich älter. Diese jungen Menschen sind die Arbeitskräfte',
        'der Zukunft, während die alte Welt altert. Diese Stimme sagt',
        'auch, was nötig wäre, um die Dividende einzulösen: Schulen für',
        'alle, Jobs für Millionen, die jedes Jahr auf den Arbeitsmarkt',
        'drängen. Ohne diese Investitionen wird aus der Dividende eine',
        'Last.',
        '',
        '## Die Schattenseiten — ungeschönt',
        '',
        'Diese Stimme nennt die eigenen Wunden: die **Ungleichheit**, die',
        'zu den größten der Welt gehört; das **Kastensystem**, das',
        'Millionen bis heute benachteiligt; die Armut, die trotz allen',
        'Wachstums bleibt; die mangelhafte Infrastruktur; die',
        'Religionsspannungen, die immer wieder in Gewalt ausbrechen. Und',
        'sie sagt, was die Demokratie kostet: Sie ist laut, chaotisch und',
        'langsam — aber sie ist frei, und genau das unterscheidet Indien',
        'von China. Ob Indien seine Chance nutzt, ist die Frage, die',
        'diese Stimme offen lässt — so wie dieses ganze Kapitel offen',
        'enden wird.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Vier Stimmen, ein Jahrhundert, eine offene Zukunft. Diese Synthese',
    'führt zusammen, was der Westen, Japan mit den fliegenden Gänsen,',
    'China und Indien erzählt haben — und sie bleibt bewusst **offen**,',
    'weil die Geschichte, die dieses letzte Kapitel erzählt, noch',
    'geschrieben wird.',
    '',
    'Die erste Lektion ist die Verschiebung der Gewichte. 1945 lag der',
    'Westen auf dem Höhepunkt seiner Macht; Europa lag in Trümmern,',
    'aber die Weltordnung war die seine. Heute ist Asien die',
    'dynamischste Region der Welt: Japan zeigte den Weg, die Tiger',
    'folgten, China holte in vierzig Jahren auf, was der Westen in zwei',
    'Jahrhunderten gebaut hatte, und Indien hat die jüngste Bevölkerung',
    'der Welt. Wer diese Verschiebung nicht versteht, versteht die',
    'Gegenwart nicht.',
    '',
    'Die zweite Lektion ist die Betreiber-These — fair bilanziert:',
    'Deutschland ist kein sterbendes Land, und Europa ist kein alter',
    'Kontinent ohne Zukunft. Absolut gesehen gehören sie weiterhin zu',
    'den stärksten Volkswirtschaften der Welt; relativ gesehen',
    'schrumpft ihr Anteil, weil andere schneller wachsen. **Aufholen ist',
    'nicht dasselbe wie Überholen** — und umgekehrt. Die Demografie ist',
    'der Schlüssel: Europa altert, Japan altert, China altert — nur',
    'Indien ist jung. Die Zukunft gehört denen, die mit ihrer',
    'Bevölkerung umgehen können.',
    '',
    'Die dritte Lektion ist die Ehrlichkeit der Bilanzen. Jede Stimme',
    'dieses Kapitels hat ihren Preis genannt: der Westen seine',
    'Exportabhängigkeit und seine Zukunftsangst, Japan seine verlorenen',
    'Jahrzehnte, Korea seine Diktatur, China seinen Kompromiss mit der',
    'Freiheit, Indien seine Ungleichheit. Keine dieser Geschichten ist',
    'nur Erfolg, keine nur Misserfolg — und genau das macht sie zu',
    'Geschichte im Sinne dieser App: verstehbar, nicht schwarz-weiß.',
    '',
    'Und die letzte Frage bleibt offen, weil sie offen bleiben muss:',
    'Wessen Geschichte wird die nächste sein?',
  ].join('\n'),

  urteil: {
    frage: 'Deutschland verliert wirtschaftlich an relativem Gewicht, bleibt aber absolut eine der stärksten Volkswirtschaften der Welt. Ist das ein Grund zur Sorge, ein Grund zur Gelassenheit — oder beides zugleich, und wenn ja, worin unterscheiden sich die beiden Sorten von Sorge und Gelassenheit?',
    hinweis: 'Es gibt hier keine richtige Antwort. Die einen sagen: Relativer Bedeutungsverlust ist der Anfang vom Ende, wer nicht mit der Weltwirtschaft mitwächst, fällt am Ende auch absolut zurück. Die anderen sagen: Dass Milliarden Menschen in Asien aus Armut herauswachsen, während Deutschland reich bleibt, ist kein Nullsummenspiel, sondern der bestmögliche Ausgang für die meisten Menschen auf der Welt. Prüfe bei deiner Antwort, ob du von Deutschland aus denkst oder von der ganzen Welt aus — beide Blickwinkel führen zu unterschiedlichen Antworten, und keiner davon ist falsch.',
  },

  quiz: [
    {
      frage: 'Was änderte die Währungsreform vom 20. Juni 1948 in den westlichen Besatzungszonen konkret?',
      antworten: [
        'Sie führte den Euro als gemeinsame Währung Westeuropas ein',
        'Sie ersetzte die wertlose Reichsmark durch die D-Mark und hob zugleich weitgehend die Preiskontrollen auf',
        'Sie verstaatlichte die deutsche Industrie',
      ],
      richtig: 1,
      erklaerung: 'Jede Person erhielt 40 Mark „Kopfgeld"; Ludwig Erhard hob zugleich einen Großteil der Preiskontrollen auf. Über Nacht füllten sich die Schaufenster — nicht, weil plötzlich mehr Waren da waren, sondern weil sich Horten nicht mehr lohnte.',
    },
    {
      frage: 'Wie groß war der Anteil des Marshallplans an der westdeutschen Wirtschaftsleistung im Vergleich zu seiner Wirkung?',
      antworten: [
        'Er war gemessen an der Wirtschaftsleistung eher klein, aber zur richtigen Zeit wichtig (Rohstoffe, Devisen, erzwungene Zusammenarbeit)',
        'Er finanzierte den größten Teil des westdeutschen Wiederaufbaus',
        'Er hatte für Westdeutschland keinerlei Bedeutung',
      ],
      richtig: 0,
      erklaerung: 'Von rund 13 Milliarden Dollar zwischen 1948 und 1952 gingen etwa 1,4 Milliarden nach Westdeutschland — gemessen an der Wirtschaftsleistung eher wenig. Wichtig war er trotzdem: als Rohstoff- und Devisenquelle in einer Mangelzeit und weil er die europäischen Empfängerländer zur Zusammenarbeit zwang.',
    },
    {
      frage: 'Was bedeutet es, wenn Deutschlands Anteil an der Weltwirtschaft seit 1990 sinkt, seine Wirtschaftsleistung selbst aber weiterwächst?',
      antworten: [
        'Das ist unmöglich — sinkender Anteil bedeutet zwingend, dass die eigene Wirtschaft schrumpft',
        'Beides kann gleichzeitig gelten: Wenn andere Volkswirtschaften schneller wachsen, sinkt der eigene Anteil rechnerisch, auch ohne eigenen Rückgang',
        'Das bedeutet, dass die Statistik falsch berechnet wird',
      ],
      richtig: 1,
      erklaerung: 'Das ist der Unterschied zwischen relativ und absolut: Wenn China zwischen 1990 und 2024 von 2 Prozent auf rund ein Sechstel der Weltwirtschaft wächst, sinkt der Anteil jedes langsamer wachsenden Landes automatisch — auch wenn dessen eigene Wirtschaft im selben Zeitraum weiterwächst.',
    },
    {
      frage: 'Welche Volkswirtschaft war 2024 nach den USA, China und Deutschland die viertgrößte der Welt?',
      antworten: [
        'Japan',
        'Frankreich',
        'Indien',
      ],
      richtig: 0,
      erklaerung: 'Japan blieb trotz der „verlorenen Jahrzehnte" nach 1990 die viertgrößte Volkswirtschaft der Welt. Indien lag 2024 auf Platz fünf, war aber die am schnellsten wachsende der großen Volkswirtschaften.',
    },
    {
      frage: 'Was zeigt das Beispiel der Halbleiter-Knappheit von 2021 für deutsche Autowerke?',
      antworten: [
        'Dass Deutschland technologisch komplett von China abhängig ist',
        'Dass eine hohe Exportverflechtung Stärke und Verwundbarkeit zugleich bedeuten kann',
        'Dass Deutschland keine eigene Automobilindustrie mehr besitzt',
      ],
      richtig: 1,
      erklaerung: 'Als 2021 Halbleiter aus Taiwan knapp wurden, standen deutsche Autowerke in Kurzarbeit — ein einzelnes fehlendes Bauteil aus einem einzigen Land genügte. Genau diese enge Verflechtung, die Deutschland zur Exportmacht macht, macht es zugleich verwundbar.',
    },
  ],
};

module.exports = aufstiegAsiens;
