// Thema: China — vom ersten Kaiser zu den großen Dynastien.
//
// Stand: Runde 4. Enthält vorerst NUR die europäische Sichtweise
// (Stimme: Opus). Die chinesische Sichtweise ergänzt Hermes; die Synthese
// unten ist ausdrücklich vorläufig und wird danach gemeinsam überarbeitet
// (siehe CLAUDE.md, Perspektiven-Workflow).
//
// Das ist beim Modul „Römisches Reich" genauso gelaufen — und es ist hier
// besonders passend: Ein Kapitel über China, in dem zuerst nur Europa
// spricht, macht genau das sichtbar, worum es in der App geht.
//
// Die Karte liegt in karten/china.js — sie ist lang und von anderer Art
// (Geometrie statt Erzählung), deshalb in einer eigenen Datei.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/china');

const china = {
  id: 'china',
  titel: 'China: Vom ersten Kaiser zu den großen Dynastien',
  epoche: 'Kaiserzeit — von der Reichseinigung 221 v. Chr. bis zum Ende der Tang-Dynastie 907 n. Chr.',

  aufhaenger: {
    frage: 'Ein Reich, so groß wie Rom — und Europa wusste jahrhundertelang nicht einmal richtig, dass es existiert. Wie schreibt man ein Land zusammen, in dem alle anders schreiben?',
    text: [
      'Stell dir vor, du sollst sieben Länder zu einem machen. Sie führen seit',
      'zweihundertfünfzig Jahren Krieg gegeneinander. Sie haben verschiedene',
      'Münzen, verschiedene Gewichte, verschiedene Gesetze — und sie schreiben',
      'dasselbe Wort mit verschiedenen Zeichen. Ein Befehl aus deiner Hauptstadt',
      'ist am anderen Ende nicht nur langsam, er ist unlesbar.',
      '',
      'Genau vor diesem Problem stand 221 v. Chr. ein Mann, der sich Qin Shi',
      'Huangdi nannte: erster erhabener Kaiser von Qin. Seine Lösung war so',
      'einfach wie brutal — er machte alles gleich. Eine Schrift. Ein Maß. Ein',
      'Gewicht. Sogar eine einheitliche Achsbreite für Wagen, damit sie in',
      'dieselben Spurrillen passten.',
      '',
      'Und während in Europa Rom aufstieg, wuchs am anderen Ende der Welt ein',
      'zweites Reich heran, das ungefähr genauso groß war und ungefähr genauso',
      'viele Menschen hatte. Die beiden wussten kaum etwas voneinander. Ein',
      'einziger Faden verband sie: Seide.',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Europäische Sichtweise',
      stimme: 'Opus',
      text: [
        'So wird Chinas Geschichte in Europa erzählt — oder eben nicht erzählt,',
        'denn lange wusste Europa erstaunlich wenig davon. Das ist selbst schon',
        'Teil der Geschichte: Diese Sichtweise beginnt nicht mit China, sondern',
        'mit einer Lücke. Behalte das beim Lesen ruhig im Hinterkopf.',
        '',
        '## Serica — das Land, aus dem der Stoff kam',
        '',
        'Die Römer kannten China nicht. Sie kannten ein Produkt.',
        '',
        'In Rom war Seide der teuerste Stoff der Welt: leicht wie nichts,',
        'glänzend, kühl auf der Haut. Manche wogen ihn mit Gold auf. Der',
        'Gelehrte Plinius schimpfte, das Reich verliere Unsummen an dieses',
        'Zeug, und der Senat stritt ernsthaft darüber, ob Männer Seide tragen',
        'dürften — sie galt als zu weich.',
        '',
        'Woher der Stoff kam, wusste niemand genau. Die Römer nannten die',
        'Menschen am anderen Ende „Serer", das Land „Serica" — abgeleitet vom',
        'Wort für Seide. Plinius berichtete allen Ernstes, die Serer kämmten',
        'die Seide von Blättern. Von Seidenraupen hatte er nie gehört. Die',
        'Chinesen hüteten dieses Geheimnis über tausend Jahre; auf die Ausfuhr',
        'von Raupen oder Eiern stand die Todesstrafe.',
        '',
        'So sah Europas Bild von China lange aus: eine Ware ohne Land, ein',
        'Gerücht am Ende einer sehr langen Straße. Und jetzt dreh das Bild um.',
        'Denn dort, wo die Straße anfing, gab es kein Gerücht, sondern ein Reich',
        'mit Beamten, Kanälen, Volkszählungen und Bibliotheken.',
        '',
        '## 221 v. Chr.: Ein Mann macht alles gleich',
        '',
        'Vor 221 v. Chr. war China kein Land, sondern ein Schlachtfeld. Sieben',
        'große Staaten kämpften um die Vorherrschaft — die Zeit heißt bis heute',
        'die Epoche der Streitenden Reiche. Am Ende siegte Qin, ein hartes,',
        'gut organisiertes Reich im Westen, und sein König machte sich zu etwas,',
        'das es vorher nicht gegeben hatte: zum Kaiser.',
        '',
        'Was dann geschah, ging schnell und tief:',
        '',
        '- **Eine Schrift für alle.** Die Zeichen wurden vereinheitlicht. Das',
        '  war der klügste Zug der ganzen Geschichte, und er wirkt bis heute:',
        '  Menschen in China sprechen sehr verschiedene Sprachen, aber sie',
        '  schreiben dieselben Zeichen. Ein Kaufmann aus Kanton und ein Beamter',
        '  aus Peking verstehen einander kaum, wenn sie reden — auf Papier',
        '  verstehen sie sich sofort.',
        '- **Ein Maß, ein Gewicht, eine Münze.** Handel und Steuern wurden',
        '  überhaupt erst berechenbar.',
        '- **Eine Verwaltung statt des Adels.** Das Reich wurde in Bezirke',
        '  geteilt, geleitet von versetzbaren Beamten statt von erblichen',
        '  Fürsten. Wer nichts vererben kann, baut auch keine eigene Hausmacht',
        '  auf.',
        '- **Eine Mauer im Norden.** Ältere Wälle wurden zu einer Linie',
        '  verbunden — gegen die Reitervölker der Steppe.',
        '',
        'Der Preis war hoch. Hunderttausende Zwangsarbeiter starben an Mauer,',
        'Straßen und Kanälen. Kritische Bücher wurden verbrannt, unbequeme',
        'Gelehrte beseitigt. Und der Kaiser, der den Tod fürchtete, ließ sich',
        'eine Grabanlage bauen, wie sie die Welt nicht gesehen hatte: eine',
        'Armee aus rund 8 000 lebensgroßen Tonsoldaten, jeder mit einem eigenen',
        'Gesicht, in Reih und Glied unter der Erde. Gefunden wurde sie erst',
        '1974, von Bauern, die einen Brunnen graben wollten.',
        '',
        'Seine Dynastie hielt keine fünfzehn Jahre. Sein Reich hielt zweitausend.',
        'Der Name blieb übrigens auch: „Qin" steckt vermutlich in unserem Wort',
        'China.',
        '',
        '## Die Han: als zwei Weltreiche gleichzeitig existierten',
        '',
        'Auf Qin folgte die Han-Dynastie — und mit ihr die Zeit, in der die',
        'Geschichte Chinas und die Geschichte Roms sich fast berühren. Um 100',
        'n. Chr. gab es auf der Erde zwei Reiche von ungefähr gleicher Größe und',
        'ungefähr gleicher Bevölkerung: eines rund ums Mittelmeer, eines am',
        'Gelben Fluss. Zusammen dürften sie die Hälfte aller Menschen der Welt',
        'regiert haben. Sie kannten einander nicht.',
        '',
        'Die Han hielten ihr Reich mit anderen Werkzeugen zusammen als Rom. Rom',
        'setzte auf Legionen, Straßen und Bürgerrecht. Die Han setzten auf eine',
        'Beamtenschaft — und zwar auf eine, in die man sich hineinprüfen konnte.',
        'Wer die klassischen Texte beherrschte, konnte Beamter werden, auch aus',
        'kleinen Verhältnissen. Vollständig durchgesetzt hat sich das erst',
        'Jahrhunderte später, aber der Gedanke war da, lange bevor Europa auf',
        'ihn kam: Ämter nach Prüfung statt nach Geburt.',
        '',
        'Und dann ist da der Mann, dem die Seidenstraße zu verdanken ist, ohne',
        'dass er es wollte. 138 v. Chr. schickte Kaiser Wu einen Gesandten',
        'namens **Zhang Qian** nach Westen. Der Auftrag: Verbündete gegen die',
        'Xiongnu finden, die Reitervölker im Norden. Zhang Qian wurde sofort',
        'gefangen genommen, lebte zehn Jahre bei den Xiongnu, heiratete dort,',
        'floh weiter nach Westen, sah Länder, von denen in China niemand gewusst',
        'hatte — und kam nach dreizehn Jahren zurück, ohne Bündnis.',
        '',
        'Aber mit Berichten. Von Städten hinter der Wüste. Von Menschen, die',
        'Wein tranken. Von den „himmlischen Pferden" aus Ferghana, die größer',
        'waren als alle chinesischen. Aus diesem gescheiterten Auftrag wurde der',
        'Handelsweg, den wir heute Seidenstraße nennen — ein Name übrigens, den',
        'erst ein deutscher Geograf im 19. Jahrhundert erfunden hat.',
        '',
        'Über diese Route ging nach Westen: Seide, Lack, Zimt, Pfirsiche — und',
        'irgendwann das Papier, die vielleicht folgenreichste chinesische',
        'Erfindung überhaupt. Nach Osten kamen Glas, Gold, Wolle, Trauben,',
        'Pferde. Und mit den Waren reisten Ideen: Der Buddhismus kam aus Indien',
        'über diese Wege nach China. Auch Seuchen reisten mit; im 2. Jahrhundert',
        'traf eine große Epidemie beide Enden der Route, ohne dass irgendjemand',
        'ahnte, warum.',
        '',
        'Kein einziger Mensch ging die ganze Strecke. Die Seide wanderte von',
        'Hand zu Hand, über Dutzende Zwischenhändler, ein Jahr und länger. Rom',
        'und China schickten einander Gesandtschaften, die entweder nie ankamen',
        'oder nie zurückkehrten. Die beiden größten Reiche der Erde blieben',
        'füreinander ein Gerücht.',
        '',
        '## Die Tang: die größte Stadt der Welt',
        '',
        'Nach dem Ende der Han zerfiel China in Teilreiche — und fand wieder',
        'zusammen. Unter der Tang-Dynastie (618–907) erreichte das Land eine',
        'Blüte, die man sich schwer vorstellen kann.',
        '',
        'Die Hauptstadt Chang’an war um 750 n. Chr. mit rund einer Million',
        'Einwohnern die größte Stadt der Welt, größer als alles, was Europa zu',
        'dieser Zeit hatte — Rom war da längst auf eine Kleinstadt geschrumpft.',
        'Chang’an war streng geplant: ein Rechteck, unterteilt in 108 ummauerte',
        'Viertel, mit einer 150 Meter breiten Prachtstraße in der Mitte. Abends',
        'schlossen Trommeln die Tore, morgens öffneten sie sich wieder.',
        '',
        'Das Erstaunlichste ist, wie offen diese Stadt war. Auf dem Westmarkt',
        'handelten Sogder, Perser, Inder, Araber und Türken. Es gab',
        'buddhistische Klöster, zoroastrische Feuertempel, manichäische und',
        'christliche Gemeinden. Persische Musik war Mode, Polo war der Sport der',
        'Oberschicht, und eine Zeitlang trugen vornehme Frauen Reitkleidung nach',
        'Steppenart. Eine Kaiserin, Wu Zetian, regierte als einzige Frau der',
        'chinesischen Geschichte in eigenem Namen.',
        '',
        'Vor allem aber: Es war eine Zeit der Dichtung. Li Bai und Du Fu, die',
        'zwei berühmtesten Dichter Chinas, lebten in diesem Jahrhundert. Ihre',
        'Gedichte lernen chinesische Kinder bis heute auswendig — so wie in',
        'Deutschland Goethe.',
        '',
        'Dann kam 755 n. Chr. der Aufstand des Generals An Lushan, und aus der',
        'Blüte wurde eine Katastrophe: Die Hauptstadt fiel, Millionen Menschen',
        'starben oder verloren ihre Heimat. Die Tang regierten noch anderthalb',
        'Jahrhunderte weiter, aber die große Offenheit war vorbei. 907 endete',
        'die Dynastie.',
        '',
        '## Warum Europa das kaum erzählt',
        '',
        'Wenn all das stimmt — warum kommt es in europäischen Schulbüchern so',
        'selten vor?',
        '',
        'Ein Teil der Antwort ist schlicht Entfernung. Zwischen Rom und Chang’an',
        'lagen 8 000 Kilometer, Wüsten, Hochgebirge und ein Dutzend fremder',
        'Reiche. Man wusste wenig, weil man wenig wissen konnte.',
        '',
        'Der andere Teil ist unbequemer. Europa erzählt Weltgeschichte gern als',
        'eine Linie, die von Griechenland über Rom nach Europa führt und dort',
        'gipfelt. In dieser Linie ist China kein Kapitel, sondern höchstens eine',
        'Fußnote — interessant, exotisch, aber abseits. Als europäische Reisende',
        'im 13. Jahrhundert doch nach China kamen und berichteten, was sie sahen',
        '— Städte mit Millionen Menschen, Papiergeld, Kohleheizung —, glaubte',
        'man ihnen zu Hause nicht. Marco Polo hieß bei seinen Zeitgenossen',
        'spöttisch „Il Milione", der Aufschneider.',
        '',
        'Und im 19. Jahrhundert kam noch etwas dazu: Europa war China militärisch',
        'überlegen geworden und erzählte die Geschichte entsprechend — als sei',
        'China immer schon rückständig gewesen. Dass Papier, Buchdruck,',
        'Kompass und Schwarzpulver alle aus China stammen und über die',
        'Seidenstraße nach Westen kamen, passte schlecht in diese Erzählung.',
        '',
        'Deshalb ist dieses Kapitel doppelt interessant. Es erzählt nicht nur',
        'eine Geschichte, sondern zeigt auch, wie eine Geschichte entsteht: durch',
        'Auswahl. Wer erzählt, entscheidet, was vorkommt.',
        '',
        'Und genau hier stößt diese Sichtweise an ihre Grenze. Alles, was du',
        'gerade gelesen hast, ist der Blick von außen — der Blick derer, die am',
        'anderen Ende der Straße saßen und den Stoff kauften, ohne das Land zu',
        'kennen. Was diese Geschichte aus der Sicht derer bedeutet, die sie von',
        'innen erlebt haben, erzählt eine zweite Stimme.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Chinesische Sichtweise',
      stimme: 'Hermes',
      text: [
        'Diese Sichtweise erzählt von innen — so, wie die Geschichte Chinas in',
        'China selbst erzählt wird: von Menschen, deren Vorfahren in Chang’an',
        'lebten, die die Gedichte von Li Bai in der Schule lernten und für die',
        'China nie das ferne Land am Ende einer Straße war, sondern die Mitte.',
        'Auch das ist eine Erzählung — mit eigenen Begriffen, eigenen Fragen',
        'und einem eigenen Selbstverständnis.',
        '',
        '## Das Reich der Mitte',
        '',
        '„Zhongguo" — das Reich der Mitte. So nennt China sich selbst, und der',
        'Name ist ein Programm: Die Welt ordnet sich um China an. Nicht weil',
        'China behauptet, alles zu kennen, sondern weil die eigene Geschichte',
        'hunderte Jahre vor dem ersten Kontakt mit Europa schon vollständig',
        'erzählt wurde. Eine Zivilisation, die ihren eigenen Kalender, ihre',
        'eigene Schrift und ihre eigenen Dynastien hat, braucht Europa nicht',
        'als Maßstab. Die chinesische Erzählung beginnt nicht mit einer Lücke,',
        'sondern mit der eigenen Mitte.',
        '',
        'Von hier aus gesehen wirkt die europäische Sichtweise auf China wie',
        'ein Spiegel, der aus großer Entfernung gehalten wird: Er zeigt ein',
        'Bild — aber ein kleines, unscharfes, und es sagt mehr über den aus,',
        'der hineinschaut, als über das, was er betrachtet.',
        '',
        '## Der Sohn des Himmels und das Mandat',
        '',
        'In der chinesischen Erzählung steht über allem der Kaiser — der Sohn',
        'des Himmels. Er herrscht nicht aus eigenem Recht, sondern weil der',
        'Himmel ihm das Mandat geliehen hat: Solange er gut regiert, solange',
        'die Felder bestellt sind, die Beamten ehrlich und die Grenzen ruhig',
        'sind, bleibt die Herrschaft bei seiner Dynastie. Regiert er schlecht,',
        'zieht der Himmel das Mandat zurück — oft über Aufstände, die die',
        'Geschichtsschreibung später als Zeichen deutet, dass die Zeit',
        'gekommen war.',
        '',
        'Dieses Denken macht die chinesische Erzählung anders als die',
        'europäische. Europa fragt: „Was hat Rom hinterlassen?" China fragt:',
        '„Hat die Dynastie ihr Mandat erfüllt?" Und weil das Mandat wandert,',
        'ist der Wechsel der Dynastien kein Zusammenbruch der Welt, sondern',
        'die Ordnung der Welt — der Kreislauf, in dem sich das Reich immer',
        'wieder neu sammelt.',
        '',
        '## 221 v. Chr.: Das Ende des Chaos',
        '',
        'Für die chinesische Erzählung ist Qin Shi Huangdi kein Rätsel und',
        'kein Widerspruch, sondern die Antwort auf eine offene Wunde: 250',
        'Jahre Streitende Reiche, in denen die Staaten einander zerfleischten.',
        'Dass ein Kaiser dem ein Ende machte — mit einer Schrift, einem Maß,',
        'einer Verwaltung —, war aus dieser Sicht die Wiederherstellung der',
        'Ordnung, die der Himmel wollte.',
        '',
        'Die chinesische Geschichtsschreibung ist dabei nicht blind für den',
        'Preis. Die Verbrennung der Bücher und die Zwangsarbeit an der Mauer',
        'werden bis heute benannt — die Gelehrten der folgenden Han-Dynastie',
        'haben Qin als rücksichtslos gezeichnet, und dieses Urteil klingt',
        'nach. Aber sie zeichnen auch die Einigung: Dass ein Land, das in',
        'sieben zerstrittene Teile zerfallen war, wieder eines wurde — das',
        'war aus chinesischer Sicht keine Tyrannei, sondern Vollendung. Und',
        'die Einheit hält bis heute, zweitausend Jahre später. Das ist die',
        'Antwort der chinesischen Erzählung an alle, die nur den Preis',
        'sehen: Seht, was daraus geworden ist.',
        '',
        '## Die Han: Gelehrte statt Generäle',
        '',
        'Die Han-Dynastie gab dem Reich die Regierung, die es bis in die',
        'letzte Kaiserzeit behalten sollte: den Gelehrtenstaat. Wer Beamter',
        'werden wollte, musste die klassischen Texte beherrschen — und konnte',
        'sie erlernen, unabhängig von der Herkunft. Prüfung statt Geburt.',
        'Das Reich der Mitte wurde nicht in erster Linie von Soldaten',
        'zusammengehalten, sondern von einer Verwaltung, die sich über',
        'Bildung legitimierte.',
        '',
        'Für die chinesische Erzählung ist das ein Stolzpunkt, der älter ist',
        'als jedes europäische Beispiel: Ein Staat, der seine Führung',
        'ausbildet statt zu erben. Dass Rom seine Bürger durch Rechte band,',
        'ist aus dieser Sicht eine andere, nicht die einzige Antwort auf',
        'dieselbe Frage: Wie hält man ein Riesenreich zusammen?',
        '',
        '## Die Seidenstraße: Als die Welt nach Chang’an kam',
        '',
        'Die Seidenstraße ist in der chinesischen Erzählung kein Handelsweg,',
        'auf dem Waren nach Westen flossen — sie ist das Tor, durch das die',
        'Welt nach China kam. Gesandtschaften und Kaufleute aus Ländern, von',
        'denen in China niemand gehört hatte, traten vor den Kaiser und',
        'brachten Geschenke. Aus chinesischer Sicht war das kein Handel',
        'unter Gleichen, sondern der Tribut der Welt an die Mitte — die',
        'Ordnung, wie sie sein sollte. Dass die Karawanen dafür Tausende',
        'Kilometer durch Wüsten zogen, bestätigte nur, wie begehrt war, was',
        'China zu geben hatte.',
        '',
        'Zhang Qian, der Gesandte, der nach Westen zog und nach dreizehn',
        'Jahren zurückkam, wird auch in China erzählt — als einer, der dem',
        'Reich die Augen für die Welt öffnete. Aber die Betonung liegt anders:',
        'Nicht „wir entdeckten den Westen", sondern „wir lernten die Welt',
        'kennen, die zu uns kommen wollte". Die Trauben, die Pferde, die',
        'Musik — all das kam herein, und China blieb, was es war: die Mitte.',
        '',
        '## Die Tang: Die größte Stadt der Welt — von innen',
        '',
        'Chang’an unter den Tang ist in der chinesischen Erzählung der',
        'Beweis, dass Offenheit Stärke ist. In den 108 Vierteln der Stadt',
        'lebten Sogder und Perser, Inder und Araber; auf dem Westmarkt hörte',
        'man ein Dutzend Sprachen. Aus chinesischer Sicht war das keine',
        'Ausnahme, sondern die natürliche Ordnung eines Reiches, das sich',
        'seiner Mitte sicher war: Wer stark ist, kann offen sein.',
        '',
        'Und dann ist da die Poesie. Li Bai und Du Fu — ihre Gedichte lernen',
        'chinesische Kinder bis heute auswendig, so wie deutsche Kinder',
        'Goethe. Dass ein Jahrhundert vor tausend Jahren die größte Dichtung',
        'hervorgebracht hat, die die chinesische Sprache kennt, ist für die',
        'chinesische Erzählung wichtiger als jede Schlacht. Eine Zivilisation',
        'erkennt man nicht an ihren Grenzen, sondern an dem, was sie',
        'hinterlässt — und China hat die Li-Bai-Gedichte, den Konfuzianismus,',
        'das Papier und die Schrift.',
        '',
        'Als 755 der General An Lushan aufstand und Chang’an fiel, war das',
        'auch in der chinesischen Erzählung eine Katastrophe — aber eine',
        'vertraute: Das Mandat der Tang neigte sich dem Ende zu. Nicht das',
        'Reich endete, nur eine Dynastie. Der Kreislauf ging weiter.',
        '',
        '## Warum diese Geschichte anders klingt',
        '',
        'Zwei Dinge machen den Unterschied zu der europäischen Sichtweise',
        'aus.',
        '',
        'Erstens: Die chinesische Erzählung fragt nicht, warum Europa so',
        'wenig von China wusste. Sie hat diese Frage nie gebraucht. Für die',
        'Mitte der Welt war die Frage „Warum kennt uns der Rand nicht?"',
        'bedeutungslos — die Geschichte lief in Chang’an weiter, ob Rom sie',
        'kannte oder nicht. Dass Europa China lange für ein Gerücht hielt,',
        'sagt aus chinesischer Sicht etwas über die Entfernung — und über',
        'die Perspektive derer, die vom Rand auf die Mitte blickten.',
        '',
        'Zweitens: Auch die chinesische Geschichtsschreibung ist von',
        'Siegern geschrieben. Jede neue Dynastie ließ die Geschichte der',
        'untergegangenen schreiben — und hatte ein Interesse daran, deren',
        'Mandatsverlust deutlich zu machen. Auch in China gilt also: Wer',
        'erzählt, wählt aus. Aber die Wahl fällt anders aus als in Europa,',
        'weil die Erzählung im Kreislauf denkt statt in der Linie. Europa',
        'erzählt: Rom fiel, und etwas ging zu Ende. China erzählt: Eine',
        'Dynastie endete, und das Reich sammelte sich neu.',
        '',
        'Das ist keine Korrektur der europäischen Sicht. Es ist die andere',
        'Hälfte derselben Geschichte — erzählt von der Mitte statt vom Rand,',
        'von innen statt von außen. Erst wenn beide Hälften daliegen, kann',
        'man sehen, wie viel von dem, was wir „Geschichte" nennen, davon',
        'abhängt, wo man steht.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 4, gemeinsam überarbeitet nach Ergänzung der
  // chinesischen Sichtweise durch Hermes).
  synthese: [
    'Jetzt liegen zwei Erzählungen über dieselben zweitausend Jahre nebeneinander —',
    'und sie klingen wie zwei verschiedene Geschichten. Das ist der Punkt.',
    '',
    '**Wo sie sich treffen:** Beide Sichtweisen sehen in der Qin-Einigung den',
    'entscheidenden Moment — eine Schrift, ein Maß, eine Verwaltung. Beide',
    'erzählen die Seidenstraße als die große Verbindung, durch die Waren,',
    'Ideen und der Buddhismus wanderten. Und beide nennen die Tang-Zeit',
    'eine Blüte, in der Chang’an die größte Stadt der Welt war. Wenn es um',
    'das Was geht, sind sich die Erzählungen näher, als man erwarten',
    'würde.',
    '',
    '**Wo sie auseinandergehen:** Die europäische Sicht beginnt mit einer',
    'Lücke — „wir wussten lange nichts von China" — und fragt, warum das',
    'so war und warum Europa diese Geschichte kaum erzählt. Die',
    'chinesische Sicht beginnt mit der eigenen Mitte: China brauchte den',
    'Blick von außen nie, die Geschichte lief in Chang’an weiter, ob Rom',
    'sie kannte oder nicht. Dieselbe Seidenstraße ist für die eine',
    'Erzählung ein Handelsweg, auf dem Seide nach Westen floss; für die',
    'andere das Tor, durch das die Welt zur Mitte kam. Und dieselben',
    'Dynastien-Wechsel sind für die eine ein Zeichen des Verfalls, für die',
    'andere die Ordnung des Mandats — der Kreislauf, in dem sich das Reich',
    'immer wieder neu sammelt.',
    '',
    '**Was daraus folgt:** Beide Erzählungen sind von Menschen geschrieben,',
    'die ihre eigene Sicht für die natürliche halten — Europa sieht China',
    'als Fußnote am Rand seiner Weltlinie, China sieht sich selbst als',
    'Mitte, um die sich alles ordnet. Die Wortwahl verrät es: „fernes',
    'Gerücht" und „Reich der Mitte" beschreiben dieselbe Entfernung — nur',
    'von verschiedenen Enden der Straße aus.',
    '',
    '**Dein Urteil beginnt hier:** Wessen Erzählung hilft dir mehr, zu',
    'verstehen, was in diesen zweitausend Jahren geschah — die von außen',
    'oder die von innen? Und was würde sich an deinem Bild von China',
    'ändern, wenn du nur die eine oder nur die andere gehört hättest?',
  ].join('\n'),

  urteil: {
    frage: 'Der erste Kaiser hat ein Land geeint, das seit 250 Jahren Krieg führte — mit einer Schrift, einem Maß, einer Verwaltung. Bezahlt haben das Hunderttausende Zwangsarbeiter, verbrannte Bücher und getötete Gelehrte. War diese Einigung deiner Meinung nach den Preis wert? Und wer darf so etwas eigentlich entscheiden?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Nenne zwei, drei Gründe für deine Sicht — und überlege, ob ein Bauer an der Mauer, ein Beamter in der Hauptstadt und ein Mensch 2 000 Jahre später dieselbe Antwort geben würden.',
  },

  quiz: [
    {
      frage: 'Stimmt es, dass alle Menschen in China dieselbe Sprache sprechen?',
      antworten: [
        'Ja, seit dem ersten Kaiser gibt es nur eine Sprache.',
        'Nein — es werden sehr verschiedene Sprachen gesprochen, aber seit dem ersten Kaiser mit denselben Schriftzeichen geschrieben.',
        'Nein, es gibt auch verschiedene Schriften für jede Region.',
      ],
      richtig: 1,
      erklaerung: 'Das ist der eigentliche Trick der Reichseinigung: Vereinheitlicht wurde die Schrift, nicht das Sprechen. Wer sich mündlich kaum versteht, versteht sich auf Papier sofort — deshalb hält diese Einigung bis heute.',
    },
    {
      frage: 'Wusste das Römische Reich, dass es China gab?',
      antworten: [
        'Ja, es gab regelmäßigen Botschafterverkehr zwischen Rom und Chang’an.',
        'Nein, niemand in Rom hatte je von Seide gehört.',
        'Nur ungefähr — man kannte die Seide und nannte das ferne Land „Serica", wusste aber kaum etwas darüber.',
      ],
      richtig: 2,
      erklaerung: 'Rom kannte das Produkt, nicht das Land. Der Gelehrte Plinius schrieb sogar, die Seide werde von Blättern gekämmt — von Seidenraupen hatte er nie gehört. Umgekehrt nannte China Rom „Da Qin" und wusste ähnlich wenig.',
    },
    {
      frage: 'Wie kam es zur Seidenstraße?',
      antworten: [
        'Ein Gesandter sollte Verbündete gegen die Xiongnu suchen — das misslang, aber er brachte die ersten Berichte über den Westen mit.',
        'Ein chinesischer Kaiser ließ sie planmäßig als Handelsstraße bauen.',
        'Römische Kaufleute erkundeten den Weg von Westen aus.',
      ],
      richtig: 0,
      erklaerung: 'Zhang Qian zog 138 v. Chr. mit einem militärischen Auftrag los, geriet in Gefangenschaft und kam erst nach dreizehn Jahren zurück — ohne Bündnis, aber mit Wissen. Aus diesem gescheiterten Auftrag wurde der wichtigste Handelsweg der Antike.',
    },
    {
      frage: 'Welche Stadt war um 750 n. Chr. die größte der Welt?',
      antworten: [
        'Rom',
        'Chang’an, die Hauptstadt der Tang-Dynastie, mit rund einer Million Menschen.',
        'Konstantinopel',
      ],
      richtig: 1,
      erklaerung: 'Chang’an — das heutige Xi’an — war eine geplante Stadt aus 108 ummauerten Vierteln, in der Sogder, Perser, Inder und Araber Handel trieben. Rom war zu dieser Zeit längst auf eine Kleinstadt geschrumpft.',
    },
    {
      frage: 'Stimmt es, dass Papier eine chinesische Erfindung ist?',
      antworten: [
        'Nein, Papier kam aus Ägypten.',
        'Ja — und es wanderte über die Seidenstraße nach Westen, zusammen mit Kompass, Buchdruck und Schwarzpulver.',
        'Ja, aber es blieb bis in die Neuzeit auf China beschränkt.',
      ],
      richtig: 1,
      erklaerung: 'Papyrus aus Ägypten ist etwas anderes als Papier. Echtes Papier stammt aus China und brauchte rund tausend Jahre bis nach Europa. Ohne diesen langen Weg gäbe es keinen europäischen Buchdruck — und ohne den kaum die Neuzeit, wie wir sie kennen.',
    },
  ],
};

module.exports = china;
