// Thema: Der Dreißigjährige Krieg (1618–1648).
//
// Stand: Runde 12. Enthält vorerst NUR die Sicht von Kaiser, Fürsten und
// Feldherren (Stimme: Opus) — die Sicht derer, die entschieden. Die Sicht der
// Betroffenen (Städte und Dörfer: Söldner, Hunger, Pest, Flucht, Überleben)
// ergänzt Hermes; die Synthese unten ist ausdrücklich vorläufig und wird
// danach gemeinsam überarbeitet (siehe CLAUDE.md, Perspektiven-Workflow).
//
// Drittes Kapitel des Neuzeit-Bogens (notizen/kapitel-planung.md). Es beginnt
// genau dort, wo „Vom Mittelalter zur Neuzeit" endet: 1618 in Prag, mit dem
// Fenstersturz, den jenes Kapitel als letzten Satz hat.
//
// Die Achse ist wieder eine soziale — oben und unten im selben Land, wie bei
// den frühen Königreichen und beim Mittelalter. Diese Stimme gehört denen, die
// entschieden: dem Kaiser, den Kurfürsten, den Königen von Dänemark, Schweden
// und Frankreich, den Feldherren. Sie darf ihre Rechnungen erklären, ohne sie
// zu beschönigen.
//
// TONE-REGEL (CLAUDE.md, Zusatzregel für sensible Themen, sinngemäß auf die
// Konfessionsfrage angewandt): Die Kriegsparteien waren politisch-religiöse
// Mächte, keine Karikaturen. Keine Seite wird dämonisiert, keine verharmlost.
// Die eigene Erzählung benennt ihre unbequemen Stellen selbst — vor allem das
// Söldner- und Kontributionssystem, das den Krieg auf Kosten der Bevölkerung
// finanzierte —, und die Beweggründe der jeweils anderen Seite werden fair
// wiedergegeben, auch innerhalb dieser Perspektive. Die Quizfragen bleiben
// Wissensfragen: nach Schuld fragt diese App nicht.
//
// Die Karte liegt in karten/dreissigjaehriger-krieg.js — drei Zustände (1618,
// 1631/32, 1648) und eine Reichsgrenze, die als Linie und nicht als Fläche
// über dem Untergrund liegt.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/dreissigjaehriger-krieg');

const dreissigjaehrigerKrieg = {
  id: 'dreissigjaehriger-krieg',
  titel: 'Der Dreißigjährige Krieg',
  epoche: '1618–1648',

  aufhaenger: {
    frage: 'Drei Männer fliegen in Prag aus einem Fenster und überleben — dreißig Jahre später ist die Mitte Europas verwüstet und ein Friede geschlossen, der die Landkarte bis heute prägt. Wie wird aus einem Streit über Kirchen ein Krieg, an dem am Ende halb Europa beteiligt ist?',
    text: [
      'Am 23. Mai 1618 warfen böhmische Adlige zwei kaiserliche Statthalter und',
      'deren Schreiber aus einem Fenster der Prager Burg. Siebzehn Meter tief.',
      'Alle drei standen wieder auf und liefen davon.',
      '',
      'Das klingt fast wie eine Anekdote — und ist der Anfang von dreißig',
      'Jahren Krieg. Nicht weil ein Fenstersturz so mächtig wäre, sondern weil',
      'in diesem Wurf alles steckte, was sich seit Jahrzehnten aufgestaut',
      'hatte: die Frage, wer im Reich über den Glauben bestimmt. Die Frage, wie',
      'viel Macht ein Kaiser über Fürsten hat, die ihn selbst gewählt haben.',
      'Und die Frage, wer in Europa den Ton angibt.',
      '',
      'Was daraus wurde, kannten die Beteiligten selbst nicht als „den',
      'Dreißigjährigen Krieg" — der Name kam später. Sie erlebten mehrere',
      'Kriege hintereinander: erst den böhmischen, dann den dänischen, dann den',
      'schwedischen, zuletzt den französisch-schwedischen. Jeder begann, weil',
      'jemand ausrechnete, dass sich der Einstieg lohnt. Und jeder endete,',
      'ohne dass irgendetwas entschieden war.',
      '',
      'Dieses Kapitel erzählt zuerst von oben: von denen, die entschieden —',
      'Kaiser, Kurfürsten, Königen, Feldherren. Sie haben ihre Gründe',
      'aufgeschrieben, in Briefen, Verträgen und Instruktionen; man kann ihnen',
      'beim Rechnen zusehen. Was ihre Entscheidungen unten anrichteten, erzählt',
      'die zweite Stimme.',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'herrscher-sicht',
      name: 'Die Sicht von Kaiser, Fürsten und Feldherren',
      stimme: 'Opus',
      text: [
        'Das hier ist die Sicht derer, die entschieden: des Kaisers in Wien, der',
        'sieben Kurfürsten, der Könige von Dänemark, Schweden, Frankreich und',
        'Spanien, der Feldherren, die Heere aufstellten und verkauften. Es ist',
        'die Erzählung aus den Kabinetten und Feldlagern — dort, wo man Krieg',
        'als Rechnung führte.',
        '',
        'Diese Stimme hat einen Vorteil und einen blinden Fleck. Der Vorteil:',
        'Sie kann erklären, warum jeder einzelne Schritt aus der Sicht dessen,',
        'der ihn tat, vernünftig aussah — und das ist das eigentlich',
        'Erschreckende an diesem Krieg. Der blinde Fleck: In dieser Rechnung',
        'kommen die Menschen, die den Preis bezahlten, als Posten vor. Als',
        '„Kontribution", als „Quartier", als „Werbung". Nicht als Menschen.',
        '',
        'Beide Stimmen dieses Kapitels sind gleichwertig. Dass diese hier',
        'zuerst steht, ist keine Rangfolge, sondern nur die Reihenfolge, in der',
        'geschrieben wurde.',
        '',
        '## 1618: Ein Fenster in Prag',
        '',
        'Böhmen war ein Wahlkönigreich, und seine Stände waren mehrheitlich',
        'protestantisch. 1609 hatte Kaiser Rudolf II. ihnen im **Majestätsbrief**',
        'die Glaubensfreiheit verbrieft — nicht aus Überzeugung, sondern weil er',
        'ihre Unterstützung brauchte. Als danach in zwei protestantischen Orten',
        'Kirchen geschlossen und abgerissen wurden, sahen die Stände das Recht',
        'gebrochen.',
        '',
        'Am 23. Mai 1618 kamen sie auf die Burg und warfen die beiden',
        'Statthalter aus dem Fenster. Das war kein Wutausbruch, sondern eine',
        'förmliche Handlung mit Vorbild: In Böhmen hatte man das 1419 schon',
        'einmal getan. Es hieß: Wir kündigen dem König den Gehorsam.',
        '',
        'Aus Sicht der Stände war das Notwehr. Aus Sicht Wiens war es Aufruhr —',
        'und der Erzherzog **Ferdinand**, der bald Kaiser werden sollte, war',
        'kein Mann für Kompromisse: tief gläubig, jesuitisch erzogen, überzeugt,',
        'dass ein Herrscher vor Gott für den Glauben seiner Untertanen haftet.',
        'Er hatte in seinen eigenen Ländern den Protestantismus bereits',
        'zurückgedrängt. Die Böhmen wussten das. Genau deshalb handelten sie.',
        '',
        'Sie setzten Ferdinand ab und wählten einen neuen König: **Friedrich V.',
        'von der Pfalz**, calvinistischer Kurfürst, Schwiegersohn des englischen',
        'Königs. Er nahm an — gegen den Rat fast aller, die rechnen konnten. Am',
        '8. November 1620 verlor sein Heer am **Weißen Berg** vor Prag in gut',
        'zwei Stunden. Er floh und ging als „Winterkönig" in die Geschichte ein.',
        '',
        'Was folgte, zeigt, wie Sieger damals dachten: 1621 wurden auf dem',
        'Altstädter Ring 27 Anführer hingerichtet, der protestantische Adel',
        'enteignet, das Land katholisch gemacht. Ein Teil des eingezogenen',
        'Besitzes machte einen bis dahin mittleren böhmischen Adligen sehr',
        'reich — er hieß Albrecht von Wallenstein.',
        '',
        '## Warum ein Fenstersturz einen Krieg auslösen konnte',
        '',
        'Damit man versteht, warum das nicht nach zwei Jahren vorbei war, muss',
        'man wissen, wie das Reich gebaut war.',
        '',
        'Das Heilige Römische Reich war kein Staat. Es war ein Verband aus über',
        'dreihundert Herrschaften: Kurfürstentümer, Fürstentümer, Bistümer,',
        'Reichsstädte, Reichsritter — jede mit eigenem Recht, eigener Münze,',
        'eigenen Truppen. An der Spitze stand ein Kaiser, der gewählt wurde und',
        'der ohne die Zustimmung der Reichsstände weder Geld noch Heer bekam.',
        '',
        'Und darüber lag seit 1555 der **Augsburger Religionsfriede** mit seiner',
        'berühmten Formel: **cuius regio, eius religio** — wessen das Land,',
        'dessen die Religion. Man liest sie meist als Glaubensregel. Sie war vor',
        'allem eine Machtregel: Sie machte jeden Landesherrn zum Herrn über die',
        'Kirche seines Landes, mitsamt ihrem Besitz. Wer die Konfession wechselt,',
        'wechselt auch die Einnahmen.',
        '',
        'Der Friede hatte drei Konstruktionsfehler, und alle drei explodierten',
        'ab 1618:',
        '',
        '- Die **Calvinisten** kamen darin nicht vor — 1555 gab es sie im Reich',
        '  kaum. Sechzig Jahre später waren die Pfalz, Hessen-Kassel und',
        '  Brandenburg reformiert, und der Friede schützte sie nicht.',
        '- Der **geistliche Vorbehalt** bestimmte, dass ein Bischof, der',
        '  protestantisch wird, sein Bistum abgeben muss. Daran hielt sich der',
        '  Norden nicht: Halberstadt, Magdeburg, Bremen und viele andere',
        '  Bistümer waren längst in protestantischer Hand.',
        '- Und die Reichsgerichte, die solche Streitfälle hätten schlichten',
        '  sollen, waren selbst konfessionell blockiert.',
        '',
        'Wer heute fragt, ob dies ein Religionskrieg war oder ein Machtkrieg,',
        'stellt eine Frage, die die Zeitgenossen nicht verstanden hätten. Für',
        'sie war beides dasselbe: Kirchengut war Macht, Glaubensfreiheit war ein',
        'Recht der Stände gegen den Fürsten, und ein Bündnis schloss man mit',
        'dem, der denselben Katechismus benutzte — bis es sich nicht mehr',
        'lohnte.',
        '',
        '## 1629: Das Restitutionsedikt — der Sieg, der zu weit ging',
        '',
        'Die erste Kriegshälfte gewann der Kaiser. Böhmen war niedergeworfen,',
        'die Pfalz erobert und ihre Kurwürde 1623 an Bayern übertragen — ein',
        'ungeheurer Vorgang, denn damit veränderte der Kaiser eigenmächtig, wer',
        'ihn künftig wählte. 1625 griff der dänische König **Christian IV.** ein,',
        'zugleich als protestantischer Fürst und als Herzog von Holstein und',
        'Konkurrent Schwedens um die Ostsee; 1629 musste er im Frieden von',
        'Lübeck aufgeben.',
        '',
        'Auf dem Höhepunkt seiner Macht erließ Ferdinand II. im März 1629 das',
        '**Restitutionsedikt**: Alles Kirchengut, das seit 1552 protestantisch',
        'geworden war, sollte zurückgegeben werden. Zwei Erzbistümer, ein Dutzend',
        'Bistümer, Hunderte Klöster.',
        '',
        'Juristisch ließ sich das begründen — es stand so im Frieden von 1555.',
        'Politisch war es der größte Fehler des Krieges. Denn erstens nahm es',
        'den protestantischen Fürsten die Grundlage ihres Besitzes. Und zweitens',
        'erschrak auch die katholische Seite: Ein Kaiser, der so weit greifen',
        'konnte, war für jeden Fürsten gefährlich. Im Sommer 1630 zwangen die',
        'Kurfürsten — die katholischen voran — den Kaiser in Regensburg, seinen',
        'eigenen Feldherrn zu entlassen. Sie fürchteten ihn mehr als den Feind.',
        '',
        '## Wallenstein: der Unternehmer des Krieges',
        '',
        '**Albrecht von Wallenstein** ist die Figur, an der man die Logik der',
        'Entscheider am besten begreift — und ihre Grenze.',
        '',
        'Er war böhmischer Adliger, protestantisch getauft, katholisch',
        'geworden, durch Heirat und durch die Güterverkäufe nach 1620 reich.',
        '1625 bot er dem Kaiser etwas an, das niemand sonst bieten konnte: ein',
        'ganzes Heer, aufgestellt auf eigene Rechnung. Der Kaiser hatte kein',
        'Geld; Wallenstein hatte Kredit. Er wurde Herzog von Friedland, später',
        'auch von Mecklenburg, und führte Heere von zeitweise über hunderttausend',
        'Mann.',
        '',
        'Bezahlt wurden sie nach einem Grundsatz, der zum Kernsatz dieses',
        'Krieges wurde: **Der Krieg ernährt den Krieg.** Das Heer holte sich',
        'aus dem Land, was die Kriegskasse nicht hergab. Städte und Landschaften',
        'mussten **Kontributionen** zahlen — regelmäßige, förmlich ausgerechnete',
        'Summen, gegen die Zusicherung, nicht geplündert zu werden. Wer nicht',
        'zahlte, hatte die Soldaten im Haus.',
        '',
        'Man muss sehen, was daran neu und was daran alt war. Alt war, dass',
        'Heere sich aus dem Land versorgten; das taten alle. Neu war die',
        'Größenordnung und die Kaltblütigkeit der Rechnung: Wallenstein machte',
        'aus dem Notbehelf ein System und aus dem Krieg ein Geschäft, das sich',
        'selbst trug — und das genau deshalb nicht mehr aufhörte. Ein Heer, das',
        'sich aus dem Land ernährt, muss weiterziehen, sobald das Land leer ist.',
        '',
        'Das ist keine Nachrede von außen. Es war Absicht, sie stand in den',
        'Verträgen, und sie galt für alle Seiten — kaiserlich, ligistisch,',
        'schwedisch, französisch. Nur an einem Punkt scheiterte Wallenstein',
        'sichtbar: 1628 belagerte er **Stralsund** und bekam die Stadt nicht,',
        'weil sie über die See versorgt wurde. Wer die Ostsee nicht hat, gewinnt',
        'im Norden nicht. Diese Lehre zog zwei Jahre später ein anderer.',
        '',
        '1630 entlassen, 1632 zurückgeholt, wurde Wallenstein am 25. Februar',
        '1634 in **Eger** von eigenen Offizieren erschlagen. Der Kaiser hatte',
        'ihn für abgesetzt erklärt und seine Ergreifung befohlen, tot oder',
        'lebendig; Wallenstein hatte auf eigene Faust mit dem Gegner verhandelt.',
        'Ob das Verrat war oder der Versuch, den Krieg zu beenden, streitet die',
        'Forschung bis heute. Sicher ist: Der Mann, der den Krieg finanzierbar',
        'gemacht hatte, wurde von dem System erledigt, das er gebaut hatte.',
        '',
        '## Magdeburg 1631 — was dieses System kostete',
        '',
        'Am 20. Mai 1631 fiel **Magdeburg**, seit November von Pappenheim, seit',
        'April von Tilly belagert. Beim Sturm brach Feuer aus; von rund 25 000',
        'bis 30 000 Menschen starben etwa 20 000. Es war die größte einzelne',
        'Katastrophe des Krieges, und aus dem Namen der Stadt wurde ein Wort:',
        '„magdeburgisieren".',
        '',
        'Wer das Feuer legte, ist bis heute umstritten. Tilly beschuldigte die',
        'Verteidiger, die protestantischen Flugschriften die kaiserlichen',
        'Truppen; die Forschung hält beides für möglich und keines für bewiesen.',
        'Was nicht umstritten ist, gehört in diese Erzählung, weil es die',
        'Rechnung der Entscheider offenlegt: Tillys Heer stand seit Monaten vor',
        'der Stadt, war nicht bezahlt und hatte die Umgebung aufgezehrt. Die',
        'Plünderung einer eroberten Stadt war der zugesagte Lohn. Das war kein',
        'Ausrutscher einzelner Unmenschen — es war die Folge einer Entscheidung',
        'darüber, wie man Krieg bezahlt.',
        '',
        'Besser wird es dadurch nicht. Es wird nur erklärbar. Und wer erklären',
        'kann, sieht auch, wer verantwortlich war: nicht der Söldner, der in die',
        'Bresche stieg, sondern die, die ihn ohne Sold dorthin schickten.',
        '',
        'Magdeburg wurde außerdem der erste große Medienkrieg Europas.',
        'Hunderte Flugschriften und Bilder gingen durch den ganzen Kontinent —',
        'und weil der Buchdruck inzwischen billig war, konnte jede Seite ihre',
        'Version verbreiten. Wer die Leitidee dieser App im Kopf hat, findet',
        'hier ein frühes Beispiel: Dieselbe Nacht, zwei Erzählungen, beide',
        'gedruckt, beide interessiert.',
        '',
        '## Gustav Adolf 1630–1632',
        '',
        'Am 6. Juli 1630 landete **Gustav Adolf**, König von Schweden, mit rund',
        '13 000 Mann auf Usedom. Möglich wurde das erst durch den',
        'Waffenstillstand von Altmark 1629, der seinen Krieg gegen Polen beendet',
        'hatte.',
        '',
        'Er kam als Retter der Protestanten — und er meinte das ernst. Er war',
        'ein frommer Lutheraner, der jeden Tag mit seinen Truppen betete, und im',
        'Reich sahen viele in ihm den „Löwen aus Mitternacht", der die',
        'Glaubensgenossen befreit.',
        '',
        'Er kam zugleich als Machtpolitiker, und auch das ist offen',
        'nachzulesen. Schweden wollte die Ostsee beherrschen — kein Gegner an',
        'ihren Südküsten, keine kaiserliche Flotte, die Zölle und Handel',
        'bedrohte. Und er kam mit fremdem Geld: Im Vertrag von Bärwalde 1631',
        'sagte ihm das katholische Frankreich jährliche Subsidien zu.',
        '',
        'Militärisch war er der modernste Feldherr seiner Zeit: kleinere,',
        'bewegliche Einheiten, Salvenfeuer statt tiefer Blöcke, leichte',
        'Geschütze, die man mitten in der Schlacht umsetzen konnte, dazu eine',
        'harte Disziplin, die Plünderungen einschränkte — solange der Sold kam.',
        'Am 17. September 1631 schlug er mit Kursachsen bei **Breitenfeld**',
        'nördlich von Leipzig Tillys Heer, das erste Mal überhaupt. 1632 zog er',
        'nach Franken, an den Rhein und über den Lech nach Bayern; im Mai stand',
        'er in München.',
        '',
        'Am 16. November 1632 fiel er bei **Lützen** — im Nebel, von seinen',
        'Leuten getrennt, mit siebenunddreißig Jahren. Die Schweden behielten',
        'das Feld.',
        '',
        'Und dann geschah das, was die Erzählung vom großen Feldherrn am',
        'schwersten aushält: fast nichts. Reichskanzler Oxenstierna führte den',
        'Krieg weiter, sechzehn Jahre lang. Der Krieg hatte sich vom Willen',
        'einzelner Männer gelöst.',
        '',
        '## 1635: Ein Kardinal wechselt die Seite',
        '',
        '1634 verloren die Schweden bei Nördlingen schwer. 1635 schloss der',
        'Kaiser mit Kursachsen den Prager Frieden: Das Restitutionsedikt wurde',
        'praktisch fallengelassen, ein Stichjahr 1627 vereinbart, die Lausitz',
        'ging an Sachsen. Ein lutherischer Kurfürst kämpfte nun an der Seite des',
        'katholischen Kaisers gegen die lutherischen Schweden. Der Krieg hätte',
        'hier enden können.',
        '',
        'Er endete nicht, weil in Paris **Kardinal Richelieu** rechnete.',
        'Frankreich war katholisch, sein leitender Minister ein Kirchenfürst —',
        'und beide sahen die eigentliche Gefahr nicht in der Ketzerei, sondern',
        'in der Umklammerung durch Habsburg: Spanien im Süden und Westen,',
        'Österreich im Osten. Jahrelang hatte Frankreich deshalb Schweden',
        'bezahlt, statt selbst zu kämpfen. 1635 erklärte es Spanien den Krieg.',
        '',
        'Die Regel, nach der Richelieu handelte, hat einen Namen:',
        '**Staatsräson** — was dem Staat nützt, ist erlaubt, auch gegen die',
        'eigene Konfession. Am 19. Mai 1643 schlug ein französisches Heer unter',
        'dem einundzwanzigjährigen Herzog von Enghien bei **Rocroi** die',
        'spanische Armee, und der Ruf der spanischen Tercios als unbesiegbar war',
        'dahin.',
        '',
        'Spätestens hier ist die Erzählung vom reinen Glaubenskrieg nicht mehr',
        'zu halten. Sie war aber auch nie ganz falsch: Für Ferdinand II. war die',
        'Rückkehr seiner Länder zur alten Kirche eine Gewissenssache, für',
        'Gustav Adolf der Schutz der Glaubensgenossen ein echtes Motiv, und die',
        'Menschen in den Dörfern erlebten sehr wohl, welcher Pfarrer nach dem',
        'Durchzug in der Kirche stand. Glaube und Macht lagen nicht neben-,',
        'sondern ineinander.',
        '',
        '## Warum dreißig Jahre?',
        '',
        'Die ehrlichste Antwort der Entscheider auf diese Frage lautet: weil',
        'niemand gewinnen konnte und niemand verlieren wollte.',
        '',
        '- **Kein Sieg war entscheidend.** Nach jeder gewonnenen Schlacht war',
        '  der Gegner geschlagen, aber nicht am Ende; Heere ließen sich mit Geld',
        '  neu aufstellen, und Geld kam aus dem besetzten Land.',
        '- **Die Heere hatten eigene Interessen.** Offiziere hatten in ihre',
        '  Regimenter investiert und wollten Sold, Beute und Entschädigung.',
        '  Frieden bedeutete Arbeitslosigkeit.',
        '- **Jede Seite hatte Mindestforderungen**, unter die sie nicht gehen',
        '  konnte, ohne das Gesicht zu verlieren — und Verbündete, die eigene',
        '  Rechnungen offen hatten.',
        '- **Die Nachbarn ließen es nicht zu.** Sobald eine Seite zu stark',
        '  wurde, trat jemand ein: Dänemark 1625, Schweden 1630, Frankreich',
        '  1635. Ein Gleichgewicht durch Dazwischentreten — dasselbe Prinzip,',
        '  nach dem Europa danach zweihundert Jahre lang Politik machte.',
        '',
        '## 1648: Münster und Osnabrück',
        '',
        'Verhandelt wurde ab 1644, in zwei Städten, weil die Konfessionen nicht',
        'an einem Tisch sitzen wollten: die katholische Seite mit Frankreich in',
        '**Münster**, die protestantische mit Schweden in **Osnabrück**. Rund',
        '150 Gesandtschaften, kein einziges Treffen aller Beteiligten,',
        'jahrelanger Streit über Rangfolgen und Anreden. Und währenddessen ging',
        'der Krieg weiter — man verhandelte, um die eigene Lage zu verbessern.',
        '',
        'Am 24. Oktober 1648 wurde unterzeichnet. Der **Westfälische Friede**',
        'regelte, was er nicht entscheiden konnte:',
        '',
        '- Der Augsburger Religionsfriede wurde bestätigt und auf die',
        '  Reformierten ausgedehnt. Für den Kirchenbesitz galt das',
        '  **Normaljahr** 1624: Was in diesem Jahr wem gehörte, blieb dabei —',
        '  eine Stichtagsregel statt eines Urteils darüber, wer recht hatte.',
        '- Die Reichsstände erhielten **Landeshoheit** und das Recht, eigene',
        '  Bündnisse zu schließen, solange sie sich nicht gegen Kaiser und Reich',
        '  richteten. Aus dem Reich wurde endgültig ein Nebeneinander fast',
        '  souveräner Fürsten.',
        '- Schweden bekam Vorpommern mit Rügen, Wismar, Bremen und Verden —',
        '  und damit Sitz und Stimme im Reichstag. Frankreich erhielt die',
        '  habsburgischen Rechte im Elsass, Brandenburg Hinterpommern und',
        '  mehrere Bistümer, Bayern behielt die Kurwürde, die Pfalz bekam eine',
        '  neue, achte.',
        '- Die Republik der Niederlande und die Schweizerische Eidgenossenschaft',
        '  schieden förmlich aus dem Reich aus.',
        '- Eine allgemeine Amnestie stellte den Stand von 1618 wieder her — mit',
        '  einer Ausnahme, die der Kaiser sich ausbedang: In seinen Erblanden',
        '  blieb es bei der Rekatholisierung. Böhmen, wo alles begonnen hatte,',
        '  bekam nichts zurück.',
        '',
        'Der Papst protestierte gegen den Vertrag; er wurde geschlossen.',
        'Zwischen Frankreich und Spanien ging der Krieg noch bis 1659 weiter.',
        '',
        'Warum dieser Friede als Geburtsurkunde des neuzeitlichen Europas gilt:',
        'Er behandelte alle Beteiligten als gleichberechtigte Vertragspartner —',
        'große und kleine, katholische und protestantische — und er machte die',
        'Religion zu einer Sache, die man regelt statt entscheidet. Nach ihm',
        'verhandelte Europa nicht mehr über die Wahrheit, sondern über',
        'Grenzen, Rechte und Gleichgewicht. Das ist weniger erhebend als ein',
        'Sieg, und es ist der Grund, warum Kongresse seitdem das Mittel der',
        'Wahl sind.',
        '',
        '## Die unbequemen Stellen dieser Erzählung',
        '',
        'Alles bisher Gesagte ist aus der Höhe erzählt, und aus der Höhe sieht',
        'ein Krieg wie eine Folge vernünftiger Schritte aus. Vier Dinge muss',
        'diese Stimme selbst aussprechen, damit die Rechnung stimmt.',
        '',
        '**Erstens: die Zahlen.** Im Reich lebten vor dem Krieg schätzungsweise',
        '16 bis 18 Millionen Menschen, danach vielleicht 10 bis 13 Millionen —',
        'ein Verlust von rund einem Drittel. In Mecklenburg, Pommern,',
        'Thüringen und Württemberg starben regional bis zu zwei Drittel; im',
        'Nordwesten, in Hamburg, in den Alpenländern blieb es dagegen',
        'vergleichsweise ruhig. Die meisten Toten fielen nicht in Schlachten,',
        'sondern durch Hunger und Seuchen, die den Heeren folgten. **Die Zahlen',
        'sind umstritten** und beruhen auf Steuerlisten und Kirchenbüchern,',
        'nicht auf Zählungen; sicher ist die Größenordnung, nicht die einzelne',
        'Ziffer.',
        '',
        '**Zweitens: Wer diesen Preis bezahlte, hatte ihn nicht beschlossen.**',
        'Die Entscheider führten dreißig Jahre lang einen Krieg, in dem sie',
        'selbst selten in Lebensgefahr gerieten — Gustav Adolf ist die',
        'Ausnahme, die auffällt. Sie stellten Söldnerheere auf, die sie nicht',
        'bezahlen konnten, und schickten sie in Landschaften, die dafür',
        'aufkommen mussten. „Der Krieg ernährt den Krieg" ist kein Naturgesetz.',
        'Es war eine Entscheidung, und man kann in den Verträgen nachlesen, wer',
        'sie getroffen hat.',
        '',
        '**Drittens: Die Konfession war oft der Vorwand und selten der ganze',
        'Grund.** Ein katholischer Kardinal bezahlte lutherische Heere. Ein',
        'lutherischer Kurfürst kämpfte für den katholischen Kaiser. Das',
        'katholische Bayern verhandelte 1647 heimlich einen eigenen',
        'Waffenstillstand. Wer das weiß, sollte auch das Umgekehrte nicht',
        'behaupten: Der Glaube war nicht nur Maske. Er war für viele echt — und',
        'gerade deshalb so brauchbar.',
        '',
        '**Viertens: Diese Männer waren keine Heiligen und keine Ungeheuer.**',
        'Wallenstein war ein genialer Organisator und ein rücksichtsloser',
        'Kriegsunternehmer. Gustav Adolf war ein frommer Mann, ein Reformer des',
        'Kriegswesens — und ein Eroberer, dessen Heere lebten wie alle anderen.',
        'Tilly war ein disziplinierter Feldherr und steht für Magdeburg.',
        'Ferdinand II. handelte aus echter Überzeugung und richtete damit',
        'furchtbaren Schaden an. Wer sie zu Helden macht, versteht den Krieg',
        'nicht; wer sie zu Monstern macht, auch nicht.',
        '',
        '## Und die andere Seite?',
        '',
        'Diese Erzählung hat einen Ort, an dem sie verstummt. Sie kann sagen,',
        'wie viele Regimenter wo standen, was eine Kontribution kostete und',
        'welcher Artikel im Friedensvertrag welchen Streit beilegte. Sie kann',
        'nicht sagen, wie es war, wenn dieses Regiment ins Dorf kam.',
        '',
        'Was in den Akten der Entscheider „Winterquartier" heißt, hieß in einem',
        'Dorf: fremde Männer im Haus, den ganzen Winter, mit Waffen, die',
        'verpflegt werden wollten. Was „Kontribution" heißt, hieß: die Saat',
        'hergeben, die für das nächste Jahr gedacht war. Was „Werbung" heißt,',
        'hieß: Der Sohn geht mit, freiwillig oder nicht — und die Heere waren',
        'voll von Menschen, die vorher selbst ausgeplündert worden waren.',
        '',
        'Diese Fragen kann die Sicht der Entscheider nicht beantworten: Wie',
        'überlebt man dreißig Jahre Krieg? Warum starben mehr Menschen an',
        'Hunger und Seuchen als in den Schlachten? Wie richtet man sich in einer',
        'Welt ein, in der zweimal im Jahr eine andere Armee die Steuern eintreibt',
        'und der Pfarrer die Konfession wechselt? Und wer waren die Söldner',
        'eigentlich, bevor sie Söldner wurden?',
        '',
        'Sie gehören einer zweiten Stimme: der Sicht der Betroffenen, der',
        'Städte und Dörfer. Sie ist dieser hier gleichwertig — und sie hat mehr',
        'zu erzählen, als die Akten der Entscheider ahnen lassen.',
      ].join('\n'),
    },
    {
      id: 'betroffene-sicht',
      name: 'Die Sicht der Betroffenen',
      stimme: 'Hermes',
      text: [
        'Diese Stimme gehört den Menschen, in deren Dörfern und Städten der',
        'Krieg stattfand: den Bauern, die die Saat hergeben mussten; den',
        'Handwerkern, deren Werkstatt die „Kontribution\" zahlte; den Pfarrern,',
        'die die Toten in die Kirchenbücher schrieben; den Müttern, deren Söhne',
        'mitgingen, weil sonst alles verloren war.',
        '',
        'Sie hat andere Quellen als die erste Stimme. Die Entscheider',
        'hinterließen Verträge, Feldzugspläne, Denkschriften. Die Betroffenen',
        'hinterließen Tagebücher, Rechnungsbücher, Kirchenbücher, Gerichtsakten',
        '— und die Erinnerung, die in Familien und Dörfern weitergereicht',
        'wurde. Aus diesen Quellen spricht nicht, was beschlossen wurde,',
        'sondern was ankam.',
        '',
        'Und auch diese Stimme hat einen blinden Fleck, den sie selbst benennen',
        'muss: Wer schreiben konnte, war nicht der Ärmste. Die ganz Armen, die',
        'keine Bücher führten, haben fast keine Stimme hinterlassen. Was wir',
        'über sie wissen, wissen wir von anderen — auch das gehört zur',
        'Ehrlichkeit dieser Erzählung.',
        '',
        '## Als der Krieg ins Dorf kam',
        '',
        'Der Krieg kam nicht als Schlacht. Er kam als Einquartierung. Was in',
        'den Akten „Winterquartier\" hieß, hieß im Dorf: fremde Männer im Haus,',
        'den ganzen Winter, mit Waffen, die verpflegt werden wollten — und wenn',
        'das Essen ausging, nahmen sie das Vieh, und wenn das Vieh weg war,',
        'nahmen sie das, was im Haus etwas wert war.',
        '',
        'Was „Kontribution\" hieß, hieß im Dorf: die Saat hergeben. Nicht den',
        'Überschuss — die Saat, die für das nächste Jahr gedacht war. Und weil',
        'fast jede Partei das so machte, zahlte ein Dorf oft zweimal im Jahr an',
        'zwei verschiedene Armeen, manchmal an drei. Es gab Dörfer, die',
        'zahlten gleichzeitig an den Kaiser, an die Schweden und an die',
        'Franzosen, weil niemand wusste, wer im nächsten Monat die Macht haben',
        'würde. Wer nicht zahlen konnte, wurde gepfändet; wer sich wehrte,',
        'dessen Dorf brannte.',
        '',
        '„Der Krieg ernährt den Krieg\" klingt in den Feldlagern wie eine',
        'Rechnung. Im Dorf klang er so: Im Herbst kam ein Regiment und nahm die',
        'Ernte. Im Winter kam das nächste und nahm das Vieh. Im Frühjahr war',
        'nichts mehr da, und trotzdem kam im Sommer wieder ein Regiment.',
        '',
        '## Die Söldner — wer sie wirklich waren',
        '',
        'Die erste Stimme spricht von Heeren, die aufgestellt und verkauft',
        'wurden. Diese Stimme muss sagen, wer in ihnen steckte — denn das ist',
        'eine der unbequemsten Wahrheiten dieses Krieges: Viele Soldaten waren',
        'vorher Bauern. Wer alles verloren hatte, hatte keinen Grund mehr, im',
        'Dorf zu bleiben; wer mitging, bekam zumindest das, was die Beute',
        'hergab. Die Heere waren voll von Menschen, die vorher selbst',
        'ausgeplündert worden waren — und die nun auf der anderen Seite des',
        'Plünderns standen, weil Überleben keine saubere Seite hat.',
        '',
        'Wir kennen einen von ihnen beim Namen: **Peter Hagendorf**, ein',
        'Söldner, der von 1625 bis 1649 — den ganzen Krieg über — Tagebuch',
        'führte. Er zog durch halb Europa, heiratete, verlor Frau und Kinder,',
        'zog weiter. In seinem Tagebuch stehen neben den Märschen und',
        'Plünderungen Sätze über seine Kinder, seine Ehe, seinen Glauben. Die',
        'Geschichte kennt ihn als „Söldner\" — er selbst sah sich als Vater und',
        'Ehemann, der irgendwie durchkam. Ein Mensch, kein Posten.',
        '',
        'Und auch das gehört hierher, so unangenehm es ist: Es gab Menschen,',
        'die am Krieg verdienten. Wirte, die Heere verpflegten; Händler, die',
        'an Armeen lieferten; Unternehmer, die „Lieferungen\" besorgten; und',
        'manche Dörfler, die sich den Plünderern anschlossen, wenn die Gelegen-',
        'heit günstig war. Der Krieg war für die meisten eine Katastrophe —',
        'aber nicht für alle. Wer das verschweigt, erzählt eine schönere',
        'Geschichte, als die Quellen hergeben.',
        '',
        '## Hunger',
        '',
        'Die schlimmsten Jahre kamen gegen Mitte des Krieges: 1634 bis 1638.',
        'Als die Saat Jahr für Jahr genommen oder verbrannt wurde, gab es',
        'nichts mehr zu ernten. Die Menschen aßen Gras, Wurzeln, Brot aus',
        'Stroh und Eicheln. Die Kirchenbücher dieser Jahre sind die',
        'erschütterndsten Quellen des ganzen Krieges: Seite um Seite',
        'Sterbeeinträge, oft mit derselben Todesursache — „Hunger\", „Ruhr\",',
        '„Flecken\", „gestorben\", einfach.',
        '',
        'Diese Stimme muss auch die dunkelste Stelle aussprechen, die in den',
        'Quellen auftaucht: Es gibt Berichte über Kannibalismus aus den',
        'schlimmsten Hungerjahren. Sie sind selten, sie sind umstritten, und',
        'man liest sie nicht gern. Aber wenn ein Kapitel über diesen Krieg',
        'ehrlich sein will, kann es sie nicht verschweigen — denn sie zeigen,',
        'was geschieht, wenn die Ordnung des Alltags über Jahre zerbricht.',
        '',
        '## Die Seuchen',
        '',
        'Die meisten Toten dieses Krieges fielen nicht in Schlachten, sondern',
        'an Krankheiten — das sagt auch die erste Stimme. Von unten sieht es',
        'so aus: Die Pest und die Ruhr reisten mit den Heeren. Ein Regiment',
        'lagerte, und im Dorf daneben starben die Leute, bevor die Soldaten',
        'überhaupt etwas genommen hatten. Die Ärzte waren geflohen oder tot;',
        'die Pfarrer trugen ein, was sie nicht heilen konnten. Ganze Dörfer',
        'starben innerhalb weniger Wochen — nicht an Wunden, sondern an',
        'Fieber, Durchfall, Erschöpfung.',
        '',
        '## Flucht, Rückkehr, leere Dörfer',
        '',
        'Viele flohen: in die Städte, deren Mauern wenigstens etwas schützten;',
        'in die Wälder, in die Berge, zu Verwandten in ruhigeren Gegenden. Und',
        'viele kamen nicht zurück. Hunderte Dörfer verschwanden ganz — die',
        'Forschung nennt sie „Wüstungen\". Wo vorher Felder lagen, wuchs Wald;',
        'wo vorher Menschen lebten, standen Ruinen. Wer zurückkehrte, fand',
        'oft nichts vor: kein Haus, keine Nachbarn, keine Kirche. Die',
        'Kirchenbücher mancher Gemeinden brechen für Jahrzehnte ab — als',
        'hätte jemand das Buch zugeklappt und niemand mehr aufgeschlagen.',
        '',
        'Und dann war da der Glaube, der mit den Herrschern wechselte. Der',
        'Grundherr wurde katholisch, der Pfarrer wurde abgesetzt, die Kirche',
        'wurde neu geweiht. Wer bleiben wollte, ging mit; wer nicht mitging,',
        'ging. Von unten gesehen war der Konfessionswechsel selten eine',
        'Gewissensfrage und meist eine Überlebensfrage: Man betete dort, wo',
        'man leben durfte.',
        '',
        '## Die Hexenverfolgung',
        '',
        'Jetzt muss diese Stimme die unbequemste Stelle der eigenen Geschichte',
        'aussprechen: Der Schrecken kam nicht nur von den Armeen. Er kam auch',
        'aus den Dörfern selbst.',
        '',
        'In den Kriegsjahren erreichten die Hexenprozesse ihren Höhepunkt —',
        'vor allem in den 1630er Jahren, in genau den Regionen, die am',
        'schlimmsten litten. Angeklagt wurden überwiegend Frauen, oft alte,',
        'oft alleinstehend. Angezeigt von Nachbarn, „gestanden\" sie unter',
        'Folter, wurden verbrannt. Wenn Missernten und Seuchen keine',
        'natürliche Erklärung mehr hatten, suchten die Menschen nach',
        'Schuldigen — und fanden sie im eigenen Dorf. Das macht es nicht',
        'besser. Aber es erklärt, warum ausgerechnet dann: Der Krieg zerstörte',
        'nicht nur Häuser und Ernten, er zerstörte auch das Vertrauen, das ein',
        'Dorf zusammenhält.',
        '',
        '## Was diese Stimme der anderen Seite zugesteht',
        '',
        'Fairness verlangt, dass auch diese Stimme benennt, was an der ersten',
        'nicht falsch ist.',
        '',
        'Die Sicht der Entscheider ist nicht falsch — sie ist nur unvollständig.',
        'Ohne ihre Entscheidungen hätte der Krieg nicht begonnen, und ohne den',
        'Frieden von 1648 hätte er nicht aufgehört. Der Friede war echt. Als',
        'die Nachricht in die Dörfer kam, wusste man, dass er halten würde —',
        'nicht weil man den Fürsten vertraute, sondern weil niemand mehr die',
        'Kraft hatte, ihn zu brechen. Die Betroffenen hatten keinen Grund, die',
        'Entscheider zu lieben. Aber sie hatten allen Grund, den Frieden zu',
        'nehmen.',
        '',
        'Und auch die Entscheider zahlten einen Preis: Gustav Adolf starb bei',
        'Lützen, Wallenstein wurde ermordet, manche Fürsten ruinierten ihre',
        'Länder und sich selbst. Und manche versuchten wirklich, ihre Gebiete',
        'herauszuhalten — mit Geld, mit Verhandlungen, manchmal vergeblich.',
        'Nicht alle an der Spitze wollten den Krieg. Aber die, die ihn',
        'beendeten, taten es von oben — und ohne sie wäre er von unten nicht zu',
        'beenden gewesen.',
        '',
        '## Die Erinnerung',
        '',
        'Wie hat dieser Krieg überlebt, in den Köpfen der Menschen?',
        '',
        '1668, zwanzig Jahre nach dem Frieden, erschien ein Buch: „Der',
        'abenteuerliche Simplicissimus\" von **Hans Jakob Christoffel von',
        'Grimmelshausen**. Sein Autor hatte den Krieg als junger Soldat selbst',
        'erlebt. Sein Held wird vom Bauernjungen zum Söldner, zum Bettler, zum',
        'Einsiedler — und am Ende weiß er nur eines sicher: dass der Mensch',
        'im Krieg zu allem fähig ist. Es ist das große Buch über diesen Krieg,',
        'und es ist von unten geschrieben.',
        '',
        'Daneben stehen die stillen Zeugen: Kirchenbücher, Dorfchroniken,',
        'Rechnungsbücher — und die Sprichwörter, die noch Jahrhunderte später',
        'erzählten, dass „die Schweden gekommen\" seien. Generationen lang war',
        'der Krieg ein Schreckenswort, mit dem man Kinder ermahnte und',
        'Fremde misstrauisch machte. So lange braucht eine Wunde, um zu',
        'vernarben.',
        '',
        '## Die Frage am Ende',
        '',
        'Religionskrieg oder Machtkrieg? Die erste Stimme hat gezeigt, wie',
        'schwer die Frage schon von oben zu beantworten ist. Von unten lautet',
        'die ehrlichste Antwort: Für das Dorf war es beides — und keines von',
        'beiden. Es war egal, ob die Soldaten für den Kaiser oder für den König',
        'von Schweden kämpften: Sie kamen, sie nahmen, sie gingen. Wer im',
        'Keller saß, hörte keinen Unterschied zwischen den Konfessionen der',
        'Männer, die das Haus durchsuchten.',
        '',
        'Aber diese Stimme kann etwas, was die erste nicht kann: Sie kann',
        'sagen, woran man erkennt, dass ein Krieg wirklich vorbei ist. Nicht',
        'am Vertrag. Am ersten Winter ohne Einquartierung. Am ersten Jahr, in',
        'dem die Saat aufgehen durfte, die man selbst gesät hatte. Wenn du',
        'also antwortest, ob dieser Krieg ein Religionskrieg oder ein',
        'Machtkrieg war, denk daran: Die Menschen, die ihn erlitten haben,',
        'wurden nicht gefragt, unter welchem Namen er geführt wurde.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 12, final). Führt beide Stimmen zusammen — wo sie
  // übereinstimmen, wo sie auseinandergehen, und warum das so ist.
  synthese: [
    'Jetzt stehen beide Stimmen nebeneinander: die Sicht von Kaiser,',
    'Fürsten und Feldherren und die Sicht der Betroffenen. Was lässt sich',
    'daraus lernen?',
    '',
    '**Wo sie übereinstimmen.** Das ist mehr, als man erwarten würde. Beide',
    'Stimmen nennen dieselben Ereignisse — den Prager Fenstersturz 1618, den',
    'Weißen Berg, Magdeburg, Breitenfeld, Lützen, den Westfälischen Frieden',
    '— und beide nennen dieselben Zahlen: ein Drittel bis zwei Drittel der',
    'Bevölkerung in den am schwersten betroffenen Landschaften, die meisten',
    'Toten durch Hunger und Seuchen, nicht durch Waffen. Beide stimmen auch',
    'in der unbequemsten Diagnose überein: „Der Krieg ernährt den Krieg"',
    'war kein Naturgesetz, sondern ein System, und die Konfession war',
    'oft der Vorwand und selten der ganze Grund. Die erste Stimme sagt es',
    'aus den Verträgen, die zweite aus den Kirchenbüchern — es ist',
    'dieselbe Aussage, aus zwei Archiven.',
    '',
    '**Wo sie auseinandergehen.** Der Unterschied beginnt beim Maßstab. Die',
    'erste Stimme erzählt in Feldzügen und Vertragsartikeln; in ihrer',
    'Erzählung ist die Bevölkerung ein Posten — Kontribution, Quartier,',
    'Werbung. Die zweite Stimme erzählt in Wintern, Ernten und',
    'Sterbeeinträgen; in ihrer Erzählung sind die Feldzüge die Zeiten, in',
    'denen man die Saat versteckte. Beide erzählen denselben Krieg — aber',
    'die eine von oben, wo er begründet wurde, die andere von unten, wo er',
    'ankam.',
    '',
    'Der zweite Unterschied ist die Frage nach dem Ende. Für die',
    'Entscheider endete der Krieg mit dem Frieden von 1648: einem',
    'ausgehandelten Vertragswerk, das die Konfessionsfrage mit einem',
    'Stichtag regelte, den Ständen Souveränität gab und das moderne',
    'Staatensystem begründete. Für die Betroffenen endete er später und',
    'anders: mit dem ersten Winter ohne Einquartierung, dem ersten Jahr, in',
    'dem die Saat aufgehen durfte. Beide Enden sind wahr — aber sie fallen',
    'nicht auf denselben Tag.',
    '',
    'Der dritte Unterschied betrifft die Schuldfrage — oder besser: die',
    'Frage, wer sie überhaupt stellen darf. Die erste Stimme nennt Namen,',
    'Daten und Entscheidungen; sie kann sagen, wer den Krieg verlängerte',
    'und wer ihn beendete. Die zweite Stimme erinnert daran, dass die',
    'Menschen, die den Preis zahlten, nie gefragt wurden — weder nach dem',
    'Namen des Krieges noch danach, ob er ihnen gefiel. Das ist keine',
    'Gegenrechnung, sondern eine Erinnerung an das, was in keiner',
    'Vertragsakte steht.',
    '',
    '**Was daraus folgt.** Wer dieses Kapitel liest, hält zwei Erzählungen',
    'in der Hand, die sich nicht widersprechen müssen — sie haben nur',
    'verschiedene Blickwinkel auf dasselbe Unglück. Die Synthese kann',
    'daraus keine einzige Wahrheit machen, und sie will es nicht. Sie kann',
    'aber eines zeigen, was beide Stimmen gemeinsam haben: Beide wissen,',
    'dass der Friede von 1648 ein Anfang war — der Anfang eines Europas,',
    'das Kriege nicht mehr als Glaubensfragen führen wollte. Dass es',
    'trotzdem wieder Kriege gab, steht auf einem anderen Blatt. Genau dort',
    'beginnt Dein Urteil: Religionskrieg oder Machtkrieg — und woran',
    'würdest du es festmachen, wenn du in einem Dorf des Jahres 1636',
    'gesessen hättest?',
  ].join('\n'),

  urteil: {
    frage: 'War der Dreißigjährige Krieg ein Religionskrieg oder ein Machtkrieg — und woran würdest du den Unterschied festmachen? Welche Antwort gibt dir die Erzählung von oben, und welche Frage bleibt dabei offen?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Drei Anstöße: Erstens, sammle die Fälle, die nicht ins Schema passen — ein katholischer Kardinal, der lutherische Heere bezahlt; ein lutherischer Kurfürst, der für den katholischen Kaiser kämpft; ein katholisches Bayern, das heimlich einen Sonderfrieden verhandelt. Zweitens, prüfe die Gegenprobe: Ferdinand II. hätte den Krieg mit einem Federstrich beenden können, wenn er das Restitutionsedikt zurückgenommen hätte — warum tat er es jahrelang nicht? Drittens, frag nach dem Maßstab: Der Westfälische Friede entschied die Glaubensfrage nicht, er regelte sie mit einem Stichtag. Ist das ein Sieg der Vernunft, ein Eingeständnis der Erschöpfung — oder beides?',
  },

  quiz: [
    {
      frage: 'Womit begann 1618 der Krieg?',
      antworten: [
        'Mit dem Einmarsch schwedischer Truppen in Pommern.',
        'Mit dem Prager Fenstersturz: Böhmische Adlige warfen zwei kaiserliche Statthalter und deren Schreiber aus einem Fenster der Burg.',
        'Mit dem Restitutionsedikt Kaiser Ferdinands II.',
      ],
      richtig: 1,
      erklaerung: 'Alle drei überlebten den Sturz aus rund siebzehn Metern. Dahinter stand der Streit um den „Majestätsbrief" von 1609, der den böhmischen Ständen Glaubensfreiheit verbrieft hatte. Böhmen war ein Wahlkönigreich: Die Stände setzten Ferdinand ab und wählten Friedrich V. von der Pfalz. Am 8. November 1620 verloren sie am Weißen Berg.',
    },
    {
      frage: 'Was bedeutete der Grundsatz „Der Krieg ernährt den Krieg"?',
      antworten: [
        'Dass Soldaten nur im Sommer kämpften, wenn es genug zu ernten gab.',
        'Dass die Heere sich aus dem besetzten Land versorgten — durch Kontributionen, Quartier und Plünderung —, weil die Kriegskassen der Fürsten leer waren.',
        'Dass jede Schlacht die nächste auslöste, bis eine Seite gewann.',
      ],
      richtig: 1,
      erklaerung: 'Der Satz wird Wallenstein zugeschrieben, und er beschreibt ein System: Kontributionen waren förmlich ausgerechnete Summen, die Städte und Landschaften zahlten, um nicht geplündert zu werden. Alle Seiten arbeiteten so. Ein Heer, das sich aus dem Land ernährt, muss weiterziehen, sobald das Land leer ist — das ist einer der Gründe, warum der Krieg so lange dauerte.',
    },
    {
      frage: 'Warum trat das katholische Frankreich 1635 gegen das katholische Habsburg in den Krieg ein?',
      antworten: [
        'Weil der Papst es dazu aufforderte.',
        'Weil König und Kardinal Richelieu insgeheim zum Protestantismus übergetreten waren.',
        'Aus Staatsräson: Frankreich sah sich von Spanien und Österreich umklammert und wollte Habsburg schwächen — Konfession hin oder her.',
      ],
      richtig: 2,
      erklaerung: 'Kardinal Richelieu hatte Schweden schon seit dem Vertrag von Bärwalde 1631 mit Geld unterstützt, statt selbst zu kämpfen. 1635 erklärte Frankreich Spanien den Krieg; 1643 siegte es bei Rocroi. Spätestens damit war klar, dass es in diesem Krieg nicht allein um den Glauben ging — was nicht heißt, dass der Glaube für die Beteiligten unwichtig gewesen wäre.',
    },
    {
      frage: 'Was wurde 1648 in Münster und Osnabrück vereinbart?',
      antworten: [
        'Das Reich wurde in einen katholischen und einen protestantischen Staat geteilt.',
        'Der Religionsfriede wurde bestätigt und auf die Reformierten ausgedehnt, für den Kirchenbesitz galt das Normaljahr 1624, und die Reichsstände erhielten Landeshoheit und das Recht auf eigene Bündnisse.',
        'Der Kaiser erhielt die alleinige Entscheidung über die Konfession im ganzen Reich.',
      ],
      richtig: 1,
      erklaerung: 'Verhandelt wurde in zwei Städten, weil die Konfessionen nicht an einem Tisch sitzen wollten. Schweden bekam Vorpommern, Wismar, Bremen und Verden, Frankreich die habsburgischen Rechte im Elsass; die Niederlande und die Schweiz schieden förmlich aus dem Reich aus. Der Friede entschied die Glaubensfrage nicht — er regelte sie mit einem Stichtag.',
    },
    {
      frage: 'Woran starben die meisten Menschen im Dreißigjährigen Krieg?',
      antworten: [
        'In den großen Feldschlachten wie Breitenfeld und Lützen.',
        'An Hunger und Seuchen, die den durchziehenden Heeren folgten.',
        'Bei der Belagerung von Magdeburg 1631.',
      ],
      richtig: 1,
      erklaerung: 'Die Schlachten forderten viele Tote, aber die große Mehrheit starb an Seuchen wie Pest und Typhus und an Hunger, wenn Saatgut und Vieh weg waren. Im Reich sank die Bevölkerung von schätzungsweise 16 bis 18 Millionen auf 10 bis 13 Millionen, regional bis zu zwei Dritteln — anderswo blieb es fast ruhig. Die Zahlen beruhen auf Steuerlisten und Kirchenbüchern und sind umstritten.',
    },
  ],
};

module.exports = dreissigjaehrigerKrieg;
