// Thema: Dschingis Khan und die Mongolen — das größte Landreich der Geschichte.
//
// Stand: Runde 5. Enthält vorerst NUR die europäische Sichtweise
// (Stimme: Opus). Die chinesische Sichtweise auf die Yuan-Zeit ergänzt
// Hermes; die Synthese unten ist ausdrücklich vorläufig und wird danach
// gemeinsam überarbeitet (siehe CLAUDE.md, Perspektiven-Workflow).
//
// So ist es bei „Römisches Reich" und bei „China" auch gelaufen. Bei diesem
// Thema ist die Lücke besonders sichtbar: Europa erlebte die Mongolen zwei
// Jahre lang als Katastrophe und danach hundert Jahre lang als offene Straße
// nach Osten. China erlebte sie fast ein Jahrhundert lang als Herrscher im
// eigenen Land. Das sind zwei sehr verschiedene Erfahrungen mit denselben
// Menschen.
//
// Die Karte liegt in karten/dschingis-khan.js — sie ist lang und von anderer
// Art (Geometrie statt Erzählung), deshalb in einer eigenen Datei.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/dschingis-khan');

const dschingisKhan = {
  id: 'dschingis-khan',
  titel: 'Dschingis Khan und die Mongolen — das größte Landreich der Geschichte',
  epoche: 'Vom Kurultai 1206 bis zum Ende der Yuan-Dynastie 1368',

  aufhaenger: {
    frage: 'Ein Volk ohne Städte, ohne Schrift, ohne Belagerungskunst erobert in fünfzig Jahren das größte zusammenhängende Landreich, das es je gab — größer als Rom und China zusammen. Wie kann das gehen?',
    text: [
      'Rechne kurz nach. Das Römische Reich umfasste auf seinem Höhepunkt rund',
      'fünf Millionen Quadratkilometer. Das Reich der Han war ähnlich groß. Das',
      'Mongolenreich brachte es auf etwa vierundzwanzig Millionen — ein Fünftel',
      'der Landfläche der Erde, von Korea bis nach Polen, von Sibirien bis an',
      'den Persischen Golf. Am Anfang standen vielleicht eine Million Menschen',
      'in der Steppe. Rom hatte allein in der Stadt Rom mehr Einwohner.',
      '',
      'Und diese Menschen hatten nichts von dem, was man dafür zu brauchen',
      'glaubt. Keine Städte, aus denen man Nachschub zieht. Keine Schrift, in',
      'der man Befehle festhält — die bekamen sie erst unterwegs, von einem',
      'gefangenen Schreiber. Keine Erfahrung darin, Mauern zu knacken; ihre',
      'ersten Belagerungen scheiterten kläglich.',
      '',
      'Was sie hatten, waren Pferde, Bögen, ein neues Gesetz — und einen Mann,',
      'der als Sohn einer geraubten Frau aufwuchs, dessen Vater vergiftet wurde',
      'und der als Junge in einem Holzjoch gefangen gehalten wurde. Er hieß',
      'Temüdschin. Wir kennen ihn unter dem Titel, den ihm die versammelten',
      'Stämme 1206 gaben: Dschingis Khan.',
      '',
      'In Europa kannte man ihn zuerst gar nicht. Man kannte nur, was 1241 aus',
      'dem Osten kam — und hielt es für das Ende der Welt.',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Europäische Sichtweise',
      stimme: 'Opus',
      text: [
        'So wird die Geschichte der Mongolen in Europa erzählt: erst als Schrecken,',
        'dann als Staunen, später als Streitfall. Europa hat dieses Reich nie von',
        'innen erlebt — es hat es zwei Jahre lang gefürchtet und danach hundert',
        'Jahre lang benutzt. Das prägt die Erzählung bis heute. Lies sie deshalb',
        'als das, was sie ist: der Blick vom Westrand einer Welt, deren Mitte',
        'woanders lag.',
        '',
        '## 1241: Der Gotteszorn steht vor der Tür',
        '',
        'Am 9. April 1241 stellte sich bei Liegnitz in Schlesien ein Heer aus',
        'Rittern, Bergleuten und Ordensbrüdern einer Armee entgegen, von der',
        'niemand genau wusste, woher sie kam. Herzog Heinrich II. von Schlesien',
        'führte es an. Die Schlacht dauerte nicht lange.',
        '',
        'Die Mongolen taten, was sie immer taten: Sie täuschten eine Flucht vor,',
        'die Ritter setzten nach, die Ordnung löste sich auf — und dann schloss',
        'sich die Falle. Herzog Heinrich fiel. Sein Kopf wurde auf einer Lanze',
        'vor die Mauern von Liegnitz getragen. Der Ort heißt seither Wahlstatt,',
        'nach dem alten Wort für Schlachtfeld.',
        '',
        'Zwei Tage später, mehrere hundert Kilometer südlich, geschah bei Mohi',
        'in Ungarn dasselbe mit dem Heer König Bélas IV. Zwei europäische Heere,',
        'zwei Tage, zwei Niederlagen — koordiniert über eine Entfernung, für die',
        'europäische Boten Wochen gebraucht hätten. Genau das war das',
        'Erschreckende: Diese Reiter waren nicht wild, sie waren organisiert.',
        '',
        'Europa hatte keine Erklärung. Was es hatte, war die Bibel. Man las die',
        'Reiter als die Völker Gog und Magog, die am Ende der Zeiten hinter den',
        'Bergen hervorbrechen. Man nannte sie **Tataren** — und weil das im',
        'Lateinischen fast wie *Tartarus* klang, wie die Unterwelt, war das Wort',
        'gleich eine Erklärung mit: Diese Menschen kamen aus der Hölle. Ludwig',
        'IX. von Frankreich soll seiner Mutter gesagt haben, entweder man schicke',
        'die Tataren zurück in den Tartarus, oder sie schickten alle in den',
        'Himmel. Der Chronist Matthäus Paris schrieb im fernen England von',
        'Menschen, die roh essen und Blut trinken; er hatte nie einen Mongolen',
        'gesehen.',
        '',
        'In Norddeutschland fiel in diesem Jahr der Heringshandel aus, weil die',
        'Fischer aus Gotland und Friesland nicht ausliefen. Die Angst reichte',
        'weiter als die Reiter.',
        '',
        '## Gerettet durch einen Todesfall',
        '',
        'Und dann, im Frühjahr 1242, drehten die Mongolen um. Sie waren an der',
        'Donau, sie hatten Ungarn verwüstet, ihre Vorhut hatte Wien in Sichtweite',
        '— und sie zogen ab, nach Osten, ohne Not.',
        '',
        'Die Erklärung, die Europa sich seither erzählt, ist ein Sterbefall: Am',
        '11. Dezember 1241 starb in Karakorum der Großkhan Ögödei, der Sohn und',
        'Nachfolger Dschingis Khans. Die Fürsten des Reiches, unter ihnen Batu,',
        'der Anführer des Westheeres, mussten zum Kurultai zurück — zur',
        'Versammlung, die den neuen Großkhan wählte. Ein Todesfall in der',
        'Mongolei, 6 000 Kilometer entfernt, rettete Mitteleuropa.',
        '',
        'Das ist eine gute Geschichte, und sie enthält vermutlich Wahres. Aber',
        'sie ist auch bequem: Sie erspart Europa die Frage, ob es sich hätte',
        'wehren können. Historikerinnen und Historiker nennen heute weitere',
        'Gründe — der ungarische Winter 1241/42 war nass, die Weiden gaben zu',
        'wenig her für Hunderttausende Pferde; Ungarns Burgen aus Stein waren',
        'zäher als die Holzstädte der Rus; und das Ziel des Feldzugs war',
        'vielleicht nie die Eroberung Europas, sondern die Sicherung der',
        'Westflanke.',
        '',
        'Merk dir diese Stelle. Hier siehst du beim Zuschauen zu, wie Geschichte',
        'gemacht wird: Aus „wir wissen nicht genau, warum sie gingen" wird über',
        'die Jahrhunderte „Europa wurde gerettet". Wer erzählt, wählt aus.',
        '',
        'Für einen Teil Europas stimmte die Rettung ohnehin nicht. Die Fürsten',
        'der Rus — das spätere Russland und die Ukraine — blieben. Kiew war 1240',
        'gefallen; rund 240 Jahre lang zahlten die russischen Fürsten Tribut an',
        'die Goldene Horde und holten sich in ihrem Lager an der Wolga die',
        'Erlaubnis zu regieren. Die russische Geschichtsschreibung nennt diese',
        'Zeit das „Tatarenjoch". Von Westen aus gesehen war 1242 ein glückliches',
        'Ende. Von Kiew aus gesehen war es der Anfang.',
        '',
        '## Die Pax Mongolica — plötzlich ist die Straße offen',
        '',
        'Dann geschah das Merkwürdigste an dieser ganzen Geschichte: Aus dem',
        'Schrecken wurde eine Chance.',
        '',
        'Zum ersten und einzigen Mal in der Geschichte gehörte der gesamte',
        'Landweg von China nach Europa einer einzigen Ordnung. Die Mongolen',
        'lebten vom Handel — Zölle waren ihre Einnahme, Karawanen ihr Kapital.',
        'Also schützten sie die Wege. Straßenraub wurde hart bestraft. Auf den',
        'großen Routen standen alle 40 Kilometer Stationen des **Jam**, des',
        'Postsystems: frische Pferde, Unterkunft, Verpflegung. Ein Kurier mit',
        'einer Paiza — einer Passtafel aus Holz, Silber oder Gold — konnte an',
        'einem Tag zurücklegen, wofür eine Karawane eine Woche brauchte.',
        '',
        'Ein Kaufmann aus Florenz schrieb um 1340 in seinem Handbuch, der Weg',
        'nach China sei „ganz sicher, bei Tag und bei Nacht". Das war seit den',
        'Römern nicht wahr gewesen und danach für Jahrhunderte nicht wieder.',
        '',
        'Dazu kam eine Haltung, die Europa fremd war: Die Mongolen fragten nicht',
        'nach dem Glauben. Sie stellten Steuerbeamte ein, ob sie Muslime,',
        'Buddhisten, Nestorianer oder Konfuzianer waren. Priester aller',
        'Religionen waren von Abgaben befreit. In Karakorum ließ Möngke Khan 1254',
        'Christen, Muslime und Buddhisten öffentlich miteinander streiten,',
        'während er zuhörte — mitten in einem Jahrhundert, in dem Europa Kreuzzüge',
        'führte. Nützlich war ihm die Toleranz auch: Wer keine Staatsreligion',
        'hat, muss keine durchsetzen.',
        '',
        'Also schickte Europa Gesandte. Papst Innozenz IV. sandte 1245 den',
        'Franziskaner Johannes von Plano Carpini los, einen alten, schweren Mann,',
        'der auf einem Pferd zwei Jahre lang durch die Steppe ritt. Er kam',
        'tatsächlich bis Karakorum, sah die Wahl des Großkhans Güyük und brachte',
        'einen Brief zurück. Der Papst hatte um Frieden und Taufe gebeten. Die',
        'Antwort war knapp: Wenn der Papst den Frieden wolle, solle er persönlich',
        'kommen und sich unterwerfen. Wenige Jahre später reiste Wilhelm von',
        'Rubruk denselben Weg und schrieb den ersten nüchternen Bericht über die',
        'Mongolen, den Europa besaß — mit Beobachtungen statt Dämonen.',
        '',
        '## Marco Polo und das Staunen, das keiner glaubte',
        '',
        'Der berühmteste dieser Reisenden war kein Mönch, sondern ein junger',
        'Kaufmann aus Venedig. **Marco Polo** brach 1271 mit Vater und Onkel auf',
        'und kam erst 1295 zurück — vierundzwanzig Jahre später. Einen großen',
        'Teil davon verbrachte er im Dienst des Großkhans Kublai, des Enkels',
        'Dschingis Khans, der inzwischen über ganz China herrschte.',
        '',
        'Was er erzählte, war für europäische Ohren schlicht unglaublich:',
        '',
        '- **Geld aus Papier.** Der Khan lasse Rinde von Maulbeerbäumen zu Blättern',
        '  pressen, mit seinem Siegel stempeln — und alle nähmen das als',
        '  Bezahlung an, als wäre es Gold. In Europa war Geld etwas, das man wog.',
        '- **Steine, die brennen.** Man grabe schwarze Steine aus der Erde und',
        '  heize damit die Häuser; sie hielten die Glut länger als Holz. Marco',
        '  Polo hatte Kohle gesehen.',
        '- **Städte ohne Ende.** Quinsai — das heutige Hangzhou — habe zwölftausend',
        '  Brücken und mehr Einwohner, als Venedig sich vorstellen könne. Venedig',
        '  hatte damals vielleicht hunderttausend.',
        '- **Eine Post, die fliegt.** Nachrichten legten mit dem Jam-System',
        '  Strecken zurück, für die europäische Boten Monate brauchten.',
        '',
        'Man glaubte ihm nicht. Sein Buch bekam in Italien den Spottnamen *Il',
        'Milione* — der Millionenerzähler, also der Aufschneider. Die Legende',
        'will, dass Freunde ihn auf dem Sterbebett baten, endlich zu widerrufen,',
        'und dass er antwortete, er habe nicht einmal die Hälfte erzählt.',
        '',
        'Trotzdem wurde das Buch abgeschrieben und gelesen, immer wieder. Zwei',
        'Jahrhunderte später besaß ein genuesischer Seefahrer ein Exemplar,',
        'vollgeschrieben mit Notizen am Rand, und wollte den Reichtum dieses',
        'Ostens erreichen, indem er nach Westen segelte. Er hieß Christoph',
        'Kolumbus. Auf diesem Umweg hat das Mongolenreich Amerika mit Europa',
        'bekannt gemacht.',
        '',
        'Die offene Straße hatte allerdings eine zweite Seite, die niemand',
        'bestellt hatte. Mitte des 14. Jahrhunderts reiste über dieselben Routen',
        'eine Krankheit nach Westen. Der Schwarze Tod kostete Europa vielleicht',
        'ein Drittel seiner Menschen. Was Waren und Ideen transportiert, trägt',
        'auch Flöhe.',
        '',
        '## Der Barbar und der Wegbereiter',
        '',
        'Wie also erinnert Europa Dschingis Khan? Ehrliche Antwort: in zwei',
        'Bildern, die sich gegenseitig nicht ausstehen können.',
        '',
        'Das ältere ist das Bild des **Zerstörers**. Die Zahlen sind furchtbar,',
        'auch wenn sie umstritten sind: Städte wie Nischapur, Merw, Herat und',
        'Bagdad wurden geplündert, ihre Bevölkerung getötet oder verschleppt.',
        'Bagdad war 1258 das geistige Zentrum der islamischen Welt — Hülegü, ein',
        'Enkel Dschingis Khans, beendete das Kalifat der Abbasiden, und die',
        'Bibliotheken der Stadt gingen unter. Die Bewässerungssysteme',
        'Mesopotamiens und Persiens, über Jahrhunderte gebaut, erholten sich',
        'nie ganz. Manche Schätzungen sprechen von Millionen Toten. Wer sagt,',
        'das sei „auch eine Sichtweise", hat den Punkt verfehlt: Zerstörung ist',
        'kein Blickwinkel.',
        '',
        'Das jüngere ist das Bild des **Wegbereiters**. Es betont: Die Mongolen',
        'vereinigten Eurasien zum ersten und einzigen Mal unter einer Ordnung.',
        'Sie schützten Handelswege, ließen Religionen nebeneinander bestehen,',
        'sammelten Handwerker und Gelehrte statt sie zu töten, und trugen',
        'Techniken über Kontinente: Buchdruck, Papier, Kompass, Schwarzpulver',
        'gingen nach Westen, persische Astronomie und Medizin nach Osten. Ohne',
        'diese hundert offenen Jahre — so die These — hätte Europa seine Neuzeit',
        'später oder anders bekommen.',
        '',
        'Beide Bilder stimmen, und sie beschreiben dieselben Menschen. Es fällt',
        'nur schwer, sie gleichzeitig im Kopf zu behalten. Wenn dir das',
        'unangenehm ist, bist du an der richtigen Stelle: Genau hier fängt',
        'Geschichte an, interessant zu werden.',
        '',
        'Übrigens sieht die Mongolei selbst das eindeutig. Dschingis Khan ist',
        'dort der Gründer der Nation; der Flughafen von Ulaanbaatar trägt seinen',
        'Namen, sein Gesicht ist auf den Geldscheinen. In der Sowjetzeit war',
        'sein Name verboten, danach kam er sofort zurück. Ein Mann, drei Länder,',
        'drei Antworten.',
        '',
        '## Und die andere Seite?',
        '',
        'Alles, was du gerade gelesen hast, ist der Blick von außen — und',
        'zusätzlich der Blick von ganz weit außen. Europa war für die Mongolen',
        'ein Randgebiet, ein Feldzug von zwei Jahren, danach ein Handelspartner',
        'am äußersten Westende der Welt.',
        '',
        'Für China war es etwas völlig anderes. Dort führten die Mongolen keinen',
        'Feldzug, dort regierten sie: Kublai Khan rief 1271 eine chinesische',
        'Dynastie aus, die **Yuan**, baute sich in Dadu — dem heutigen Peking —',
        'eine Hauptstadt und beendete 1279 das Reich der Song. Fast ein',
        'Jahrhundert lang wurde China von Fremden beherrscht, in einem Land, das',
        'sich selbst als Mitte der Welt versteht. Wie erzählt man das von innen?',
        'Ist Kublai ein chinesischer Kaiser oder ein Besatzer? Und was macht es',
        'mit einer Erzählung, in der Dynastien kommen und gehen, wenn die',
        'Dynastie diesmal aus der Steppe kommt?',
        '',
        'Diese Fragen kann die europäische Sichtweise nicht beantworten. Sie',
        'gehören einer zweite Stimme, die diese hundert Jahre von innen erzählt.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Chinesische Sichtweise',
      stimme: 'Hermes',
      text: [
        'Diese Sichtweise erzählt die Geschichte der Mongolen von innen — aus',
        'China, wo sie fast ein Jahrhundert lang regierten. Für die chinesische',
        'Erzählung ist das die schwierigste Geschichte überhaupt: das Reich der',
        'Mitte, das zum ersten Mal in seiner langen Geschichte vollständig von',
        'Menschen aus der Steppe beherrscht wurde. Wie erzählt man das, ohne',
        'das eigene Selbstbild zu zerbrechen? Die Antwort der chinesischen',
        'Geschichtsschreibung ist so kühn wie folgerichtig.',
        '',
        '## Das Mandat kennt keine Herkunft',
        '',
        'Der Schlüssel ist das Mandat des Himmels — das du aus dem Kapitel über',
        'China schon kennst. Es besagt: Der Himmel verleiht die Herrschaft,',
        'wem er will, und er nimmt sie zurück, wenn sie schlecht geführt wird.',
        'Daraus folgt etwas, das für Außenstehende überraschend klingt: Der',
        'Himmel fragt nicht nach der Herkunft. Er hat das Mandat schon oft an',
        'Bauern und Soldaten gegeben, die ein Reich gründeten — warum nicht',
        'auch einmal an Reiter aus der Steppe?',
        '',
        'Die chinesische Erzählung deutet die mongolische Eroberung deshalb',
        'nicht als Einbruch von außen, sondern als Urteil von oben: Die',
        'Song-Dynastie hatte das Mandat verwirkt. Sie war schwach, ihre',
        'Generäle misstrauten einander, ihre Beamten stritten — und ein Reich,',
        'das sich nicht verteidigen kann, hat nach dieser Logik das Recht zu',
        'herrschen verloren. Dass die neuen Herren aus der Steppe kamen, war',
        'kein Widerspruch zur Ordnung der Welt. Es war die Ordnung der Welt.',
        '',
        '## Kublai wurde Chinese',
        '',
        'Und dann geschah etwas, das die Geschichte der Welt geprägt hat:',
        'Kublai Khan ließ sich auf China ein. Er gab seiner Herrschaft den',
        'Dynastie-Namen **Yuan** — „Ursprung" — und stellte sich damit in die',
        'Reihe der chinesischen Dynastien. Er verlegte die Hauptstadt nach',
        'Dadu, dem heutigen Peking, übernahm die Beamtenverwaltung, führte den',
        'Kalender, ließ die Reichsgeschichte schreiben. Aus dem Eroberer wurde',
        'ein Kaiser — und Peking ist seitdem Hauptstadt Chinas, bis heute.',
        '',
        'Die chinesische Erzählung sieht darin den Beweis, dass das Reich der',
        'Mitte stärker war als seine Eroberer: Die Mongolen eroberten China,',
        'aber China formte die Mongolen. Wer in Dadu regierte, regierte',
        'chinesisch — mit chinesischen Beamten, chinesischem Zeremoniell,',
        'chinesischer Schrift. Der Steppenfürst wurde zum Sohn des Himmels.',
        '',
        '## Was die Yuan brachten',
        '',
        'Die chinesische Erzählung ist nicht blind für das, was die Yuan-Zeit',
        'brachte. Das Wichtigste: **Wiedervereinigung.** Seit dem Ende der Tang',
        'war China in Teilreiche zerfallen — Song im Süden, Jin im Norden,',
        'dazu Tanguten und andere. Fast dreihundert Jahre Trennung, drei',
        'Jahrhunderte, in denen das Reich der Mitte geteilt war. Die Mongolen',
        'machten daraus wieder ein China. Für eine Zivilisation, die sich über',
        'die Einheit definiert, ist das kein kleiner Punkt.',
        '',
        'Dazu kam die offene Welt. Unter den Yuan war die Seidenstraße so',
        'sicher wie nie — und wieder kam die Welt zur Mitte: Kaufleute aus',
        'Persien, Händler aus Venedig, Gelehrte, die in Dadu willkommen waren.',
        'Marco Polo, von dem die europäische Erzählung berichtet, war in der',
        'chinesischen Erzählung einer von vielen Fremden, die am Hof des',
        'Kaisers dienten — interessant, aber kein Weltwunder. Dass der Westen',
        'diesen Besucher für die Sensation hielt, sagt aus chinesischer Sicht',
        'mehr über den Westen als über China.',
        '',
        '## Der Preis',
        '',
        'Ehrlich bleibt die chinesische Erzählung auch: Die Mongolen',
        'regierten nicht wie chinesische Kaiser. Sie teilten die Menschen in',
        'vier Klassen — Mongolen an der Spitze, dann fremde Verbündete, dann',
        'die Nordchinesen, zuletzt die Südchinesen, die sich am längsten',
        'gewehrt hatten. Chinesen waren in ihrer eigenen Hauptstadt Bürger',
        'zweiter Klasse. Die Steuerlast war hoch, und mancher Beamte im',
        'Reichsinnenland diente einem Herrn, dessen Sprache er nicht',
        'verstand.',
        '',
        'Auch das gehört zur Erzählung. Die Yuan-Dynastie regierte mit dem',
        'Mandat des Himmels — aber sie regierte fremd, und das war auf Dauer',
        'nicht zu ertragen. Als im 14. Jahrhundert Missernten, Überschwem-',
        'mungen und Aufstände das Reich erschütterten, deutete die',
        'Geschichtsschreibung das als Zeichen: Das Mandat verließ die Yuan,',
        'wie es die Song verlassen hatte. 1368 zogen sich die Mongolen in',
        'die Steppe zurück, und die Ming-Dynastie übernahm — wieder eine',
        'chinesische Dynastie, wieder der Kreislauf.',
        '',
        '## Und dann schrieben die Ming die Geschichte',
        '',
        'Hier wird die Geschichte der Yuan selbst zur Lektion über',
        'Geschichte. Die offizielle Chronik der Yuan-Dynastie wurde nämlich',
        'von der Ming-Dynastie geschrieben — von den Siegern, die die',
        'Mongolen vertrieben hatten. Und die Ming taten etwas Erstaunliches:',
        'Sie ließen die Yuan in der Reihe der chinesischen Dynastien stehen.',
        'Nicht aus Großzügigkeit. Sondern weil ihre eigene Herrschaft nur',
        'rechtmäßig war, wenn sie als nächste Dynastie im Kreislauf des',
        'Mandats erschien — und der Kreislauf verlangte, dass die Yuan',
        'dazugehört hatten. Die Aufnahme der Fremdherrscher in die',
        'Dynastie-Reihe war selbst ein politischer Akt.',
        '',
        'Das ist die Antwort auf die Frage, die am Ende der europäischen',
        'Erzählung steht: Ist Kublai ein chinesischer Kaiser oder ein',
        'Besatzer? Die chinesische Erzählung sagt: Wer das Reich eint und',
        'das Mandat trägt, ist Kaiser — die Herkunft ist zweitrangig. Und',
        'doch streitet China bis heute darüber, wie die Yuan zu bewerten',
        'sind. Die einen feiern die Wiedervereinigung und die offene Welt,',
        'die anderen erinnern an die vier Klassen und die Fremdherrschaft.',
        '',
        'Dass ein Volk sich nicht einig ist, wie es seine eigene Geschichte',
        'erzählen soll, ist keine Schwäche — es ist die ehrlichste Sache,',
        'die eine Zivilisation über sich selbst sagen kann. Auch die',
        'chinesische Erzählung ist keine Wahrheit. Sie ist eine Stimme, die',
        'aus der Mitte kommt — und die weiß, dass die Sieger schreiben.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 5, gemeinsam überarbeitet nach Ergänzung der
  // chinesischen Sichtweise durch Hermes).
  synthese: [
    'Drei Namen für dasselbe Volk: „Tataren" — die aus dem Tartarus, der',
    'Hölle, kommen. „Yuan" — ein Dynastie-Name in der Reihe der',
    'chinesischen Dynastien. „Tatarenjoch" — das Wort, das die russische',
    'Geschichtsschreibung für 240 Jahre Tributpflicht fand. Drei Wörter,',
    'drei Erzählungen, ein Reich. Genau darum geht es in diesem Kapitel.',
    '',
    '**Wo sie sich treffen:** Beide Sichtweisen nennen dasselbe Reich',
    'beispiellos — größer als alles zuvor, von Korea bis Polen. Beide',
    'erzählen die Pax Mongolica: gesicherte Handelswege, das Jam-Postsystem,',
    'religiöse Toleranz, die offene Straße nach Osten. Und beide machen den',
    'Abzug von 1242 beziehungsweise die Eroberung von 1279 zum Wendepunkt',
    'ihrer Erzählung.',
    '',
    '**Wo sie auseinandergehen:** Die europäische Erzählung erlebte die',
    'Mongolen zwei Jahre als Schrecken — „Gotteszorn", „gerettet durch',
    'einen Todesfall" — und danach hundert Jahre als ferne Chance:',
    'Gesandte, Marco Polo, Geschäfte. Die Mongolen waren für Europa ein',
    'Ereignis. Die chinesische Erzählung erlebte sie fast ein Jahrhundert',
    'als Herrscher: Kublai wurde Kaiser, China wurde wiedervereinigt, die',
    'Welt kam nach Dadu. Die Mongolen waren für China eine Epoche. Und die',
    'dritte Stimme am Rand — die der Rus — nennt dieselbe Zeit ein Joch.',
    'Drei Erfahrungen, drei Wörter, drei Urteile über dieselbe',
    'Herrschaft.',
    '',
    '**Was daraus folgt:** Die Namen sind die Deutung. Wer „Tataren" sagt,',
    'erzählt von der Hölle; wer „Yuan" sagt, erzählt vom Mandat des',
    'Himmels, das auch an Steppenreiter vergeben werden kann; wer',
    '„Tatarenjoch" sagt, erzählt von Unterdrückung. Und die chinesische',
    'Erzählung fügt die feinste Pointe hinzu: Selbst die offizielle',
    'Geschichte der Yuan wurde von ihren Besiegern geschrieben — den Ming,',
    'die sie in die Dynastie-Reihe aufnahmen, weil ihre eigene',
    'Rechtmäßigkeit davon abhing. Der Sieger schreibt die Geschichte — und',
    'manchmal schreibt er sogar die Geschichte des Siegers, den er',
    'besiegte.',
    '',
    '**Dein Urteil beginnt hier:** War Dschingis Khan ein Eroberer oder ein',
    'Wegeöffner? Die Frage führt vielleicht in die Irre — er war beides,',
    'und die Antwort hängt davon ab, wen du fragst: die Kaufleute, die',
    'Nachfahren der Getöteten, die Mongolei, die ihn als Gründer feiert,',
    'oder die Geschichtsschreiber der Ming. Welche Stimme spricht dich am',
    'meisten an — und welche würdest du gerne noch hören?',
  ].join('\n'),

  urteil: {
    frage: 'Dschingis Khan hat Städte auslöschen lassen und zugleich einen Raum geschaffen, in dem Waren, Wissen und Menschen sicher zwischen China und Europa reisen konnten. War er ein Eroberer und Zerstörer oder ein Ordnungsstifter und Wegeöffner — und wer darf das eigentlich entscheiden: die Nachfahren der Getöteten, die Kaufleute, die davon lebten, oder die Mongolei, die ihn als Gründer ihres Landes feiert?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Überlege, ob die Frage vielleicht falsch gestellt ist — muss man sich für eines von beiden entscheiden? Und prüfe an deiner Antwort, ob du dieselben Maßstäbe auch an Eroberer anlegen würdest, die dir näher sind: an Caesar zum Beispiel, oder an Alexander „den Großen".',
  },

  quiz: [
    {
      frage: 'Hat Dschingis Khan China erobert?',
      antworten: [
        'Ja, er unterwarf ganz China bis zur Südküste.',
        'Nur den Norden — das Reich der Tanguten und große Teile des Jin-Reiches. Ganz China eroberte erst sein Enkel Kublai, 1279.',
        'Nein, China blieb während der ganzen Mongolenzeit unabhängig.',
      ],
      richtig: 1,
      erklaerung: 'Dschingis Khan starb 1227, mitten im Feldzug gegen die Tanguten. Der Süden — das Reich der Song — hielt sich noch über fünfzig Jahre. Erst Kublai Khan beendete es 1279 und regierte als Kaiser der Yuan-Dynastie über ganz China.',
    },
    {
      frage: 'Haben die Mongolen Europa erobert?',
      antworten: [
        'Nein, sie kamen nie über die Weichsel hinaus.',
        'Ja, ganz Europa war bis 1300 mongolisch.',
        'Teilweise: Sie schlugen 1241 die Heere in Polen und Ungarn und zogen 1242 wieder ab — aber die russischen Fürstentümer blieben rund 240 Jahre unter der Goldenen Horde.',
      ],
      richtig: 2,
      erklaerung: 'Für Mitteleuropa war 1242 vorbei, was 1241 begonnen hatte. Für die Rus nicht: Kiew fiel 1240, und die Fürsten zahlten fast zweieinhalb Jahrhunderte Tribut. Ob „Europa erobert wurde", hängt also davon ab, wo in Europa du fragst.',
    },
    {
      frage: 'Warum zogen die Mongolen 1242 aus Ungarn wieder ab?',
      antworten: [
        'Weil ein europäisches Heer sie in einer großen Schlacht besiegte.',
        'Die bekannteste Erklärung ist der Tod des Großkhans Ögödei 1241 — die Fürsten mussten zur Wahl des Nachfolgers zurück. Sicher weiß man es nicht.',
        'Weil der Papst ihnen im Tausch gegen den Abzug Gold zahlte.',
      ],
      richtig: 1,
      erklaerung: 'Ein Todesfall 6 000 Kilometer entfernt — das ist die Erklärung, die Europa sich seit Jahrhunderten erzählt. Heute nennt man weitere Gründe: nasse Weiden im Winter 1241/42, zähe Steinburgen, und vielleicht war die Eroberung Europas nie das Ziel.',
    },
    {
      frage: 'Wer war Marco Polo?',
      antworten: [
        'Ein venezianischer Kaufmann, der 24 Jahre unterwegs war, am Hof Kublai Khans diente — und dem zu Hause kaum jemand glaubte.',
        'Ein Feldherr, der die Mongolen bei Liegnitz besiegte.',
        'Ein Gesandter des Papstes, der die Mongolen taufen sollte.',
      ],
      richtig: 0,
      erklaerung: 'Sein Buch hieß im Volksmund spöttisch „Il Milione", der Aufschneider: Papiergeld, brennende schwarze Steine und Städte mit Millionen Menschen hielt man für erfunden. Zwei Jahrhunderte später las Christoph Kolumbus dieses Buch — und wollte diesen Osten von Westen aus erreichen.',
    },
    {
      frage: 'Was bedeutet „Pax Mongolica"?',
      antworten: [
        'Ein Friedensvertrag zwischen dem Papst und dem Großkhan.',
        'Die Zeit, in der der ganze Landweg zwischen China und Europa zu einem Reich gehörte — Handelswege wurden geschützt, Religionen geduldet, Nachrichten liefen über ein Postsystem mit Wechselstationen.',
        'Der Name des mongolischen Gesetzbuches.',
      ],
      richtig: 1,
      erklaerung: 'Die Mongolen lebten von Zöllen, also sicherten sie die Straßen. Ein Florentiner Kaufmann schrieb um 1340, der Weg nach China sei „ganz sicher, bei Tag und bei Nacht". Über dieselben offenen Wege kam allerdings auch der Schwarze Tod nach Europa.',
    },
  ],
};

module.exports = dschingisKhan;
