// Thema: Germanen und Völkerwanderung.
//
// Stand: Runde 8. Enthält vorerst NUR die römisch-mediterrane Sichtweise
// (Stimme: Opus). Die germanische Sichtweise ergänzt Hermes; die Synthese
// unten ist ausdrücklich vorläufig und wird danach gemeinsam überarbeitet
// (siehe CLAUDE.md, Perspektiven-Workflow).
//
// Bei diesem Thema hat die Leitidee der App eine ungewöhnliche Wendung. „Der
// Sieger schreibt die Geschichte" — hier nicht. Fast alles, was wir über die
// Germanen zu wissen glauben, steht in Texten des Reiches, das unterging:
// geschrieben von Leuten, die nie dort waren, in der Sprache der Verlierer,
// über Gegner, die selbst keine Geschichtsbücher hinterließen. Und die
// Gewinner — die Könige der neuen Reiche — schrieben danach Latein und
// nannten sich nach römischem Vorbild. Wer hier die Perspektive wechseln
// will, muss deshalb zuerst zugeben, wie dünn die Quellenlage auf der
// anderen Seite ist. Genau das leistet die zweite Stimme.
//
// Die Karte liegt in karten/germanen.js — sie zeigt fünf Zustände zwischen
// 100 und 568 n. Chr. und lässt Germanien in der ersten Phase bewusst als
// unbegrenzte Fläche frei (Begründung dort im Kopf der Datei).
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/germanen');

const germanen = {
  id: 'germanen',
  titel: 'Germanen und Völkerwanderung',
  epoche: 'Von Caesars Rheingrenze 58 v. Chr. bis zu den Langobarden 568 n. Chr.',

  aufhaenger: {
    frage: 'Ein Weltreich verschwindet — und keiner, der dabei war, merkt es. Wie geht das, und wollten die angeblichen Zerstörer Roms nicht in Wahrheit selbst Römer sein?',
    text: [
      'Im September 476 setzte ein Offizier namens Odoaker in Ravenna den',
      'weströmischen Kaiser ab. Der Kaiser war ein Junge, vielleicht sechzehn,',
      'und er trug den unpassend großen Namen Romulus Augustulus — „kleiner',
      'Augustus". Odoaker ließ ihn nicht töten. Er schickte ihn mit einer',
      'jährlichen Rente auf ein Landgut bei Neapel.',
      '',
      'Heute steht dieses Jahr in jedem Schulbuch: 476, das Ende des Römischen',
      'Reiches. Damals schrieb kaum jemand darüber. Keine Chronik meldet eine',
      'Zeitenwende, keine Rede beklagt das Ende der Welt. Odoaker rief sich',
      'nicht zum Kaiser aus, sondern schickte die Herrschaftszeichen nach',
      'Konstantinopel und ließ sich König nennen — im Namen des Kaisers, der',
      'dort weiterregierte. Für die Zeitgenossen war das eine',
      'Verwaltungsänderung.',
      '',
      'Und es kommt noch merkwürdiger. Die Männer, die angeblich Rom zerstört',
      'haben, taten hinterher alles, um römisch zu wirken. Sie ließen ihre',
      'Gesetze auf Latein aufschreiben. Sie behielten römische Beamte,',
      'römische Steuern, römische Titel. Theoderich, der Ostgote, regierte',
      'Italien und nannte sich dabei Statthalter des Kaisers. Wer eine Sache',
      'zerstören will, baut sie danach nicht sorgfältig wieder auf.',
      '',
      'Zwei Fragen also. Erstens: Was ist da wirklich passiert — ein Untergang',
      'oder ein Umbau? Zweitens, und das ist die unangenehmere: Woher wissen',
      'wir das eigentlich? Denn fast jedes Wort, das wir über die Germanen',
      'haben, stammt von ihren Gegnern.',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'roemisch',
      name: 'Römisch-mediterrane Sichtweise',
      stimme: 'Opus',
      text: [
        'So wird die Geschichte der Völkerwanderung in der Tradition erzählt,',
        'die aus dem Mittelmeerraum stammt — aus den Städten, den Bibliotheken',
        'und den Kanzleien des Römischen Reiches und seiner Erben. Es ist die',
        'Erzählung derer, die schreiben konnten und es taten.',
        '',
        'Und hier steckt gleich am Anfang eine Merkwürdigkeit. Sonst gilt: Der',
        'Sieger schreibt die Geschichte. Hier ist es umgekehrt. Über die',
        'Germanen wissen wir fast nur, was ihre Gegner über sie aufschrieben —',
        'und diese Gegner haben verloren. Die Germanen selbst hinterließen',
        'keine Geschichtsbücher. Sie hatten eine Schrift, die Runen, aber die',
        'benutzten sie für kurze Inschriften auf Waffen, Steinen und Schmuck,',
        'nicht für Chroniken. Der älteste lange Text in einer germanischen',
        'Sprache ist eine Bibelübersetzung: Der gotische Bischof Wulfila',
        'übertrug im 4. Jahrhundert die Heilige Schrift ins Gotische und',
        'erfand dafür eigens ein Alphabet. Von seinem Volk erfahren wir daraus',
        'fast nichts — außer einer Kleinigkeit, die ein späterer Autor',
        'berichtet: Die Bücher der Könige mit ihren Kriegsgeschichten habe',
        'Wulfila weggelassen, seine Leute seien kriegerisch genug.',
        '',
        'Lies das Folgende also als das, was es ist: die Innensicht eines',
        'Reiches, das seine Nachbarn nie verstanden hat und am Ende von ihnen',
        'beerbt wurde.',
        '',
        '## Wie Rom sich seine Nachbarn erfand',
        '',
        'Im Jahr 58 v. Chr. rückte Caesar nach Gallien ein, und in dem Bericht,',
        'den er darüber schrieb, zog er eine Linie: Westlich des Rheins wohnen',
        'die Gallier, östlich davon die *Germani*. Das war ordentlich, klar und',
        'praktisch — und es war eine Erfindung. Die Menschen dort nannten sich',
        'nicht so. Sie hätten sich als Chatten, Cherusker, Markomannen',
        'bezeichnet, oder gar nicht als Gruppe. Aus einem Fluss auf der Karte',
        'wurde ein Volk. Rom brauchte einen Namen für die andere Seite, und wer',
        'eine Grenze zieht, erschafft damit auch das, was jenseits liegt.',
        '',
        'Hundertfünfzig Jahre später schrieb ein römischer Senator namens',
        'Tacitus ein schmales Buch über dieses Land: die **Germania**, um',
        '98 n. Chr. Es ist bis heute die wichtigste Quelle über die frühen',
        'Germanen — und man muss dazusagen, dass Tacitus nie dort war. Er',
        'sammelte, was Händler, Soldaten und ältere Bücher hergaben.',
        '',
        'Vor allem aber schrieb er gar nicht wirklich über Germanien. Er',
        'schrieb über Rom. Seine Germanen sind treu, tapfer, gastfreundlich',
        'und unbestechlich; sie kennen keinen Luxus, ihre Ehen sind fest, ihre',
        'Anführer führen durch Vorbild. Jeder Satz ist ein Vorwurf an die',
        'eigene Hauptstadt, in der Tacitus Bestechung, Prunk und Denunziation',
        'erlebte. Das ist eine alte Denkfigur: der edle Wilde, der uns den',
        'Spiegel vorhält. Nur ist es eben ein Spiegel — und man erkennt darin',
        'immer nur sich selbst.',
        '',
        'Dieses Buch hat eine gefährliche Nachgeschichte. Es galt lange als',
        'verschollen, tauchte im 15. Jahrhundert in einem deutschen Kloster',
        'wieder auf — und wurde von da an gelesen, als sei es ein Ahnenpass.',
        'Aus Tacitus’ „unvermischtem Volk" bastelten sich Jahrhunderte',
        'später Nationalisten und schließlich die Nationalsozialisten einen',
        'Beweis für ihre Rassenlehre; Himmler ließ 1943 in Italien nach der',
        'ältesten Handschrift suchen. Ein Historiker hat die Germania deshalb',
        'eines der gefährlichsten Bücher genannt, die je geschrieben wurden.',
        'Man sollte das wissen, bevor man das Wort „Germanen" in den Mund',
        'nimmt: Es ist ein römischer Sammelname, und er ist im 20. Jahrhundert',
        'schwer missbraucht worden.',
        '',
        'Was die Archäologie zeigt, ist etwas ganz anderes als ein Volk:',
        'Dörfer, Höfe, Handwerk, unterschiedliche Bestattungssitten,',
        'wechselnde Bündnisse. Und Gruppen, die entstehen und wieder',
        'verschwinden. Die Franken, die Alamannen, die Sachsen — keine dieser',
        'Gruppen war „schon immer" da. Sie bildeten sich unterwegs, oft um',
        'einen erfolgreichen Anführer und eine gemeinsame Erzählung herum. Wer',
        'mitzog, gehörte dazu, gleich welcher Herkunft. Die Forschung nennt das',
        'Stammesbildung: Ein Volk ist hier eher etwas, das entsteht, als etwas,',
        'das wandert.',
        '',
        '## 9 n. Chr.: die Niederlage, die eine Grenze machte',
        '',
        'Rom hatte durchaus vor, auch dieses Land zu nehmen. Dann kam der',
        'Sommer des Jahres 9. Der Statthalter Varus zog mit drei Legionen durch',
        'unwegsames Gelände, geführt von einem Verbündeten: Arminius, einem',
        'Cherusker, der in römischen Diensten gestanden hatte, römischer Ritter',
        'war und die römische Kriegführung von innen kannte. Er führte Varus in',
        'einen Hinterhalt. Rund 15 000 Mann kamen um. Kaiser Augustus soll',
        'sich, so erzählt man, den Kopf gegen die Tür geschlagen haben: „Varus,',
        'gib mir meine Legionen wieder!"',
        '',
        'Rom hat sich danach nie wieder dauerhaft östlich des Rheins',
        'festgesetzt. Zwei Anmerkungen dazu, die in der deutschen Schulversion',
        'oft fehlen. Erstens: Arminius wurde ein gutes Jahrzehnt später von',
        'Angehörigen seiner eigenen Verwandtschaft erschlagen — sie fürchteten,',
        'er wolle König werden. Es gab kein „Deutschland", das ihn feierte.',
        'Zweitens: Genau dieser Mann wurde im 19. Jahrhundert zum „Hermann dem',
        'Cherusker" umgedichtet, mit Riesendenkmal und Nationalpathos. Das',
        'Denkmal steht bis heute. Es sagt mehr über das 19. Jahrhundert als',
        'über das Jahr 9.',
        '',
        '## Die Grenze war eine Naht, keine Wand',
        '',
        'Was danach entstand, ist auf der Karte die dunkle Linie: Rhein, Limes,',
        'Donau. Zwischen Rhein und Donau lief sie quer durchs Land — Wall,',
        'Graben, Palisade, Wachtürme in Sichtweite, über 500 Kilometer.',
        '',
        'Man stellt sich das gern als Bollwerk vor. Das war es nicht; dafür war',
        'es viel zu dünn besetzt. Es war eine kontrollierte Schwelle: Wer',
        'hindurchwollte, tat es an einem Übergang, unter Aufsicht und gegen',
        'Zoll. Und es war ein Ort des Austauschs. Auf beiden Seiten wurde',
        'gehandelt — römisches Geschirr, Wein und Münzen finden sich weit im',
        'Norden, germanisches Vieh, Bernstein und Haare (für Perücken) gingen',
        'nach Süden. Es wurde geheiratet. Und es wurde angeworben.',
        '',
        'Dieser letzte Punkt ist der wichtigste, und er zerstört das ganze Bild',
        'vom „Ansturm der Barbaren". Rom brauchte Soldaten und holte sie sich',
        'jenseits der Grenze. Im 4. Jahrhundert war das römische Heer in weiten',
        'Teilen ein Heer germanischer Herkunft — mit germanischen Offizieren',
        'und germanischen Generälen. Der Mann, der um 400 Italien gegen die',
        'Goten verteidigte, hieß Stilicho und war der Sohn eines Vandalen. Er',
        'war der mächtigste Mann des Westreichs, seine Tochter heiratete den',
        'Kaiser — und 408 wurde er auf Betreiben einer Hofpartei hingerichtet,',
        'weil man ihm misstraute. Kurz darauf liefen Zehntausende seiner',
        'Soldaten zu Alarich über. Es ist eine der bittersten Ironien dieser',
        'Geschichte: Rom fiel nicht, weil zu viele Germanen kamen, sondern',
        'unter anderem, weil es denen nicht traute, die längst da waren.',
        '',
        '## 375: Es fängt mit einer Flucht an',
        '',
        'Um 375 tauchten östlich des Don berittene Verbände auf, die die Römer',
        '„Hunnen" nannten. Woher sie kamen, ist bis heute umstritten. Für diese',
        'Geschichte ist entscheidend, was sie auslösten: Die Goten, die',
        'jahrzehntelang nördlich des Schwarzen Meeres saßen, mit dem Reich',
        'handelten und von ihm gelernt hatten, gerieten unter Druck.',
        '',
        '376 standen sie zu Zehntausenden am Nordufer der Donau und baten um',
        'Aufnahme. Rom sagte ja — solche Aufnahmen waren üblich, das Reich',
        'brauchte Bauern und Rekruten. Dann kam die Katastrophe der',
        'Verwaltung. Die Versorgung brach zusammen, römische Beamte trieben',
        'Wucherpreise; ein Zeitgenosse berichtet, Hungernde hätten ihre Kinder',
        'in die Sklaverei verkaufen müssen, um Hundefleisch zu bekommen. Aus',
        'Flüchtenden wurden Aufständische.',
        '',
        'Am 9. August 378 stellte Kaiser Valens sie bei Adrianopel zur',
        'Schlacht, ohne auf das Heer des Westens zu warten. Am Abend war das',
        'Feldheer des Ostens vernichtet und der Kaiser tot; seine Leiche wurde',
        'nie gefunden. Ammianus Marcellinus, selbst Offizier, nannte es die',
        'schwerste Niederlage seit Cannae — und das lag sechshundert Jahre',
        'zurück.',
        '',
        'Merk dir den Anfang dieser Kette, denn er widerspricht dem Bild vom',
        'Raubzug: Die Völkerwanderung beginnt nicht mit einem Angriff auf Rom.',
        'Sie beginnt mit Menschen, die vor jemand anderem fliehen und um',
        'Einlass bitten.',
        '',
        '## Der Sturm: 406 bis 476',
        '',
        'Dann ging es schnell — für damalige Verhältnisse. Silvester 406',
        'überquerten Vandalen, Alanen und Sueben bei Mainz den Rhein; eine',
        'spätere Erzählung lässt sie über das Eis gehen. Sie zogen durch',
        'Gallien nach Hispanien und 429 mit rund 80 000 Menschen über die',
        'Meerenge von Gibraltar nach Afrika.',
        '',
        '410 nahm Alarich mit den Westgoten Rom und ließ drei Tage plündern.',
        'Militärisch bedeutete das wenig: Rom war seit über hundert Jahren',
        'nicht mehr Hauptstadt. Seelisch war es beispiellos. Achthundert Jahre',
        'lang hatte kein Feind diese Stadt betreten. Hieronymus schrieb in',
        'Bethlehem, ihm sei beim Diktieren die Stimme im Halse steckengeblieben.',
        'Augustinus antwortete mit seinem größten Buch, „Vom Gottesstaat": Wenn',
        'das ewige Reich fallen kann, dann war es eben nie das ewige Reich.',
        '',
        '439 nahmen die Vandalen Karthago — der schwerste Schlag, und zwar',
        'nicht wegen der Stadt. Dort lag das Getreide, das Rom ernährte, und',
        'dort kamen die Steuern her, aus denen Heere bezahlt wurden. Ein Reich',
        'ohne Steuern kann keine Soldaten kaufen; ein Reich ohne Soldaten',
        'verliert die nächste Provinz. Von da an lief eine Abwärtsspirale.',
        '',
        '451 traf sich fast ganz Europa auf einem Schlachtfeld in Gallien: Das',
        'römische Heer unter Aëtius, verbündet mit den Westgoten, stellte sich',
        'Attila und dessen Hunnen. Sieh dir an, wer da nebeneinander stand —',
        'Römer und Goten, dieselben Goten, die 410 Rom geplündert hatten. So',
        'einfach ist die Aufteilung in „wir" und „die Barbaren" also nicht.',
        '',
        '455 plünderten die Vandalen Rom ein zweites Mal. 476 setzte Odoaker',
        'den letzten Kaiser ab. Was danach kam, siehst du auf der Karte in der',
        'Phase „um 500": kein Reich mehr, sondern sechs Königreiche.',
        '',
        '## Der Tag, an dem niemand etwas merkte',
        '',
        'Und jetzt zurück zur Frage vom Anfang. Warum hat 476 kaum jemand',
        'bemerkt?',
        '',
        'Weil aus der Nähe fast nichts geschah. Es gab weiterhin einen Kaiser —',
        'in Konstantinopel. Es gab weiterhin römisches Recht, römische Steuern,',
        'lateinische Urkunden, die Kirche mit ihren Bischöfen, die Städte, die',
        'Sprache. Die neuen Könige regierten mit dem alten Apparat, weil er',
        'funktionierte und weil sie nichts Besseres hatten. Theoderich der',
        'Ostgote ließ in Ravenna römische Senatoren für sich arbeiten und',
        'schrieb an den Kaiser, sein Königreich sei eine Nachahmung des',
        'Kaiserreichs. Die Franken schrieben ihr Recht auf Latein auf.',
        '',
        'Das Wort **Untergang** stammt aus einer viel späteren Zeit. Der',
        'englische Historiker Edward Gibbon nannte sein sechsbändiges Werk',
        '1776 „Verfall und Untergang des Römischen Reiches" — und das Bild vom',
        'großen Sturz ist seither nicht mehr aus den Köpfen gegangen.',
        '',
        'Heute streitet die Forschung darüber, und der Streit ist echt: Die',
        'einen sprechen von *Transformation* — die antike Welt sei nicht',
        'gestorben, sondern umgebaut worden, allmählich, von Menschen, die',
        'römisch bleiben wollten. Die anderen halten dagegen, das sei zu',
        'freundlich: Wer die Funde ansieht, findet nach 400 weniger Handel,',
        'schlechteres Handwerk, kleinere Städte, weniger Schrift. In Britannien',
        'verschwand sogar die Töpferscheibe. Das war für sehr viele Menschen',
        'ein spürbarer Absturz des Lebensstandards, kein Übergang.',
        '',
        'Beide haben Belege. Vielleicht ist die ehrlichste Antwort: Es kommt',
        'darauf an, wo man steht. Für einen Bischof in Ravenna war es ein',
        'Regierungswechsel. Für einen Bauern in Britannien war es das Ende',
        'einer Welt.',
        '',
        '## Was das Wort „Völkerwanderung" verschweigt',
        '',
        'Achte auf die Wörter. Im Deutschen heißt diese Zeit',
        '**Völkerwanderung** — das klingt nach einem großen, langsamen Zug,',
        'nach Wagen, Frauen und Kindern, nach einem Volk auf Reisen. Im',
        'Englischen und Französischen heißt dieselbe Zeit',
        '„Barbareneinfälle" — das klingt nach Überfall. Dasselbe Jahrhundert,',
        'zwei Namen, zwei Urteile. Und beide Namen wurden von denen vergeben,',
        'die nicht dabei waren.',
        '',
        'Drei Dinge, die beide Wörter nicht hergeben:',
        '',
        '- **Es waren wenige.** Die Gruppen zählten Zehntausende, in einem',
        '  Reich mit vielleicht zwanzig bis dreißig Millionen Menschen. Die',
        '  Vandalen brachten 429 rund 80 000 Menschen nach Afrika — weniger,',
        '  als heute in eine mittelgroße Stadt passen. Es war keine Flut. Es',
        '  war eine kleine, bewaffnete Minderheit, die an die Spitze rückte.',
        '- **Es waren keine festen Völker.** Wer als „Westgote" nach Spanien',
        '  kam, konnte der Enkel eines Mannes sein, der sich hundert Jahre',
        '  vorher noch ganz anders genannt hätte. Unterwegs schlossen sich',
        '  Sklaven, Deserteure, Bauern und ganze Verbände an.',
        '- **Die Sieger wollten dazugehören.** Sie zerschlugen das Reich nicht,',
        '  um etwas Eigenes an seine Stelle zu setzen. Sie wollten hinein.',
        '',
        'Was blieb, siehst du bis heute. Aus dem Latein der Provinzen wurden',
        'Französisch, Spanisch, Portugiesisch, Italienisch, Rumänisch — die',
        'germanischen Herren übernahmen die Sprache der Beherrschten, nicht',
        'umgekehrt. Die Kirche übernahm die Verwaltung, samt Diözesen, die den',
        'römischen Bezirken folgen. Und ein Königreich dieser Karte hat Europa',
        'geprägt wie kein anderes: das der Franken, aus dem später Frankreich',
        'und das Reich Karls des Großen hervorgingen. Nur in Britannien riss',
        'der Faden: Dort verschwand das Latein, die Städte verfielen, und aus',
        'dem Namen der Angeln wurde England.',
        '',
        '## Und die andere Seite?',
        '',
        'Alles, was du gerade gelesen hast, ist von innen erzählt — aus dem',
        'Reich heraus, mit seinen Quellen, seinen Wörtern und seinem',
        'Selbstbild. Sogar der Name des Themas stammt von dort.',
        '',
        'Von der anderen Seite fehlen die Bücher. Aber es gibt Gräber,',
        'Siedlungen, Werkzeuge, Waffen, Schmuck von großer Kunst; es gibt die',
        'Sprachen, die Rechtsaufzeichnungen der Königreiche und Erzählungen,',
        'die Jahrhunderte später aufgeschrieben wurden. Daraus lässt sich sehr',
        'wohl etwas erzählen — nur eben anders und mit mehr Vorsicht.',
        '',
        'Diese Fragen kann die römische Sichtweise nicht beantworten: Wie sieht',
        'diese Zeit aus, wenn man nicht vom Ende eines Reiches ausgeht, sondern',
        'vom Beginn eines Lebens an einem neuen Ort? Was heißt es, wenn eine',
        'Gruppe „auf römischem Boden angesiedelt" wird — für die, die kamen,',
        'und für die, die schon da waren? Und ist eine Gesellschaft ohne',
        'Steuerlisten, ohne Statthalter und ohne Stadtmauern rückständig, oder',
        'ist sie einfach anders geordnet?',
        '',
        'Sie gehören einer zweiten Stimme.',
      ].join('\n'),
    },
    {
      id: 'germanisch',
      name: 'Germanische Sichtweise',
      stimme: 'Hermes',
      text: [
        'Diese Sichtweise erzählt die Geschichte von innen — von den Menschen,',
        'die Rom „Barbaren" nannte und die selbst keine Geschichtsbücher',
        'hinterließen. Deshalb muss diese Stimme ehrlich sagen, woher sie',
        'kommt: aus Gräbern und Siedlungen, aus Schmuck und Waffen, aus',
        'Rechtsaufzeichnungen, die Jahrhunderte später aufgeschrieben wurden,',
        'und aus Liedern, die lange mündlich weitergegeben wurden, bevor',
        'jemand sie aufschrieb. Das ist weniger, als Rom hinterließ — aber es',
        'reicht, um zu sehen, dass diese Welt von innen ganz anders aussah',
        'als von außen.',
        '',
        '## Eine Welt ohne Chroniken',
        '',
        'Die Germanen hatten eine Schrift — die Runen —, aber sie benutzten',
        'sie nicht für Geschichten, sondern für kurze Inschriften: auf',
        'Waffen, Steinen, Schmuck. „Dieser Speer gehört mir" — nicht „Dieses',
        'Reich habe ich erobert". Ihre Geschichten lebten in Liedern und',
        'Erzählungen, die von Sänger zu Sänger gingen. Aus römischer Sicht',
        'war das ein Mangel: Kein Volk ohne Bücher kann zivilisiert sein.',
        'Aus germanischer Sicht war es eine andere Art, Erinnerung zu',
        'bewahren: nicht in toten Zeichen, sondern in lebendigen Stimmen.',
        'Wer die Lieder kennt, braucht keine Bibliothek.',
        '',
        '## Freiheit, wie Rom sie nicht kannte',
        '',
        'Was Tacitus von außen beschrieb, sah von innen so aus: Die',
        'Versammlung — das Thing —, auf der die Freien der Gruppe über Krieg',
        'und Frieden, über Recht und Streit entschieden, ohne dass ein',
        'Statthalter von oben befahl. Die Gefolgschaft: Ein Anführer',
        'gewann Gefolgsleute nicht durch Ämter, sondern durch Großzügigkeit',
        'und Tapferkeit — und sie folgten ihm, solange er sie führte.',
        'Treue war kein Zwang, sondern ein Vertrag, den beide Seiten',
        'jederzeit brechen konnten.',
        '',
        'Aus dieser Sicht war die römische Ordnung nicht „höher entwickelt",',
        'sondern einfach anders: Steuerlisten, Statthalter, Stadtmauern —',
        'das war eine Welt, in der man gehorchte, weil es Vorschriften gab.',
        'Die germanische Welt gehorchte, weil man einem Mann folgte, den man',
        'kannte. Ob das rückständig oder nur anders geordnet war, entscheidet',
        'der, der von außen schaut. Von innen war es die Ordnung der',
        'Freiheit.',
        '',
        '## Warum wir gingen',
        '',
        'Die römische Erzählung nennt das, was geschah, „Völkerwanderung" —',
        'und meint damit einen Sturm auf das Reich. Von innen sah es anders',
        'aus: Die wenigsten zogen los, um zu erobern. Sie flohen. Von Osten',
        'rollte etwas an, gegen das es keine Verteidigung gab — die Hunnen,',
        'Reiter aus der Steppe, vor denen ganze Völker auseinanderliefen.',
        '376 standen die Goten am Ufer der Donau und baten um Aufnahme. Sie',
        'wollten nicht das Reich zerstören. Sie wollten hinein.',
        '',
        'Und die, die später über den Rhein gingen, suchten meist dasselbe:',
        'Land, Sicherheit, einen Platz, an dem man leben konnte. Dass Rom',
        'darin einen Angriff sah und die eigene Welt bedroht, ist',
        'verständlich. Aber aus der Sicht der Wandernden war es kein Feldzug,',
        'sondern die Fortsetzung des Überlebens mit anderen Mitteln.',
        '',
        '## Was wir wurden',
        '',
        'Und dann geschah etwas, das die römische Erzählung nur schwer',
        'fassen kann: Die Sieger wollten dazugehören. Die neuen Könige',
        'nannten sich römische Amtsträger, ließen ihr Recht auf Latein',
        'aufschreiben und ihre Münzen nach römischem Vorbild prägen. Die',
        'germanischen Herren übernahmen die Sprache der Beherrschten —',
        'daraus wurden Französisch, Spanisch, Italienisch. Nur wo Rom nicht',
        'gewesen war, setzte sich die eigene Sprache durch: Aus den Angeln',
        'wurde England.',
        '',
        'Aus dieser Sicht ist die Völkerwanderung kein Untergang, sondern',
        'ein Anfang: Der Anfang neuer Königreiche, neuer Sprachen, eines',
        'neuen Europas — aufgebaut von Menschen, die Rom nie verstanden hat',
        'und die am Ende seine Erben wurden, ob sie wollten oder nicht.',
        '',
        '## Was diese Sicht anders macht',
        '',
        'Zwei Dinge sind wichtig, wenn man diese Stimme hört.',
        '',
        'Erstens: Sie hat keinen eigenen Namen. „Germanen", „Barbaren",',
        '„Vandalen" — alle diese Namen wurden von außen vergeben, von',
        'Schriftstellern, die die Menschen nicht fragten. Die Gruppen',
        'nannten sich Chatten, Cherusker, Goten, Franken — oder gar nicht,',
        'weil sie sich erst unterwegs als Volk bildeten, um einen Anführer,',
        'eine Beute, eine gemeinsame Geschichte herum. Ein Volk zu sein, war',
        'hier kein Zustand, sondern ein Ereignis.',
        '',
        'Zweitens: Auch diese Rekonstruktion ist eine Erzählung. Wir wissen',
        'weniger, als wir gern wüssten, und manches stammt aus späteren',
        'Quellen, die schon römisch dachten. Aber die Richtung der',
        'Erzählung ändert die Wertung: Was für Rom ein Sturm war, der eine',
        'Welt beendete, war für die, die zogen, der Anfang eines Lebens an',
        'einem neuen Ort. Keine der beiden Sichtweisen ist gelogen. Sie',
        'blicken nur von entgegengesetzten Enden auf dieselbe Straße.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 8, gemeinsam überarbeitet nach Ergänzung der
  // germanischen Sichtweise durch Hermes).
  synthese: [
    'Zwei Sichtweisen auf dieselbe Straße — von entgegengesetzten Enden',
    'gesehen. Und die Merkwürdigkeit vorweg: Bei diesem Thema gilt der Satz',
    '„Der Sieger schreibt die Geschichte" nicht. Die Verlierer haben',
    'geschrieben — das Reich, das unterging, hatte die Bibliotheken. Die',
    'Sieger hinterließen Gräber, Schmuck und Lieder, aber keine Chroniken.',
    'Deshalb ist hier nicht nur die Deutung umstritten, sondern schon die',
    'Quellenlage: Wir kennen diese Zeit fast nur aus einer Feder.',
    '',
    '**Wo sie sich treffen:** Beide Sichtweisen sehen, dass die germanischen',
    '„Sieger" dazugehören wollten — sie übernahmen lateinische Titel,',
    'römisches Recht, die Sprache der Beherrschten. Beide nennen 476 einen',
    'eher unspektakulären Moment. Und beide wissen: Die Gruppen, die Rom',
    '„Germanen" nannte, waren keine festen Völker, sondern Gebilde, die',
    'sich unterwegs bildeten.',
    '',
    '**Wo sie auseinandergehen:** Die römische Erzählung sieht in der',
    'Wanderung einen Sturm auf das Reich — ein Weltende, das sie',
    '„Barbareneinfälle" nennt. Die germanische Sicht erzählt von Flucht',
    'und Suche: vor den Hunnen, nach Land, nach einem Platz zum Leben —',
    '„die Fortsetzung des Überlebens mit anderen Mitteln". Die Wortwahl',
    'verrät die Perspektive: „Untergang" oder „Anfang"? „Eindringlinge"',
    'oder „Menschen, die hinein wollten"? „Rückständig" oder „anders',
    'geordnet"? Sogar die Namen — Germanen, Barbaren, Vandalen — sind',
    'von außen vergeben; die Stimme von innen hatte nicht einmal einen',
    'eigenen Namen.',
    '',
    '**Was daraus folgt:** Wer nur die eine Erzählung kennt, hält sie für',
    'die ganze Geschichte — genau das macht sie gefährlich. Die römische',
    'Sicht widerlegt sich stellenweise selbst: Sie spricht vom „Ansturm',
    'der Barbaren" und erzählt zugleich, dass das römische Heer im',
    '4. Jahrhundert zu großen Teilen aus Germanen bestand. Widersprüche',
    'in einer Quelle sind kein Ärgernis — sie sind die Stelle, an der man',
    'am meisten lernt.',
    '',
    '**Dein Urteil beginnt hier:** War die Völkerwanderung ein Untergang',
    'oder ein Anfang? Die Antwort hängt davon ab, wen du fragst: einen',
    'Bischof in Ravenna, einen Bauern in Britannien, einen Goten am Ufer',
    'der Donau. Und sie hängt davon ab, welches Wort du wählst — denn',
    'jedes Wort ist schon eine Entscheidung.',
  ].join('\n'),

  urteil: {
    frage: 'War die Völkerwanderung ein Untergang oder ein Umbau? Und wer entscheidet eigentlich, welches der beiden Wörter man benutzt — die, die dabei etwas verloren haben, oder die, die etwas gewonnen haben?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Drei Anstöße: Erstens, prüfe die Wörter selbst — „Völkerwanderung" klingt nach einem Zug mit Wagen und Kindern, „Barbareneinfälle" nach Überfall; beide Namen wurden lange danach vergeben, und beide enthalten schon ein Urteil. Zweitens, es kommt auf den Standort an: Für einen Bischof in Ravenna war 476 ein Regierungswechsel, für einen Bauern in Britannien das Ende einer Welt. Drittens, denk an eine Veränderung, die du selbst erlebt hast — Umzug, Schulwechsel, eine Trennung in der Familie. Wäre „Untergang" oder „Umbau" das richtige Wort gewesen, und hätten alle Beteiligten dasselbe Wort gewählt?',
  },

  quiz: [
    {
      frage: 'Woher wissen wir, was die Germanen dachten und wie sie lebten?',
      antworten: [
        'Aus ihren eigenen Geschichtsbüchern, die sie in Runen schrieben.',
        'Fast nur aus römischen Texten und aus der Archäologie — die Germanen selbst schrieben Runen für kurze Inschriften, aber keine Chroniken.',
        'Aus Briefen, die zwischen den germanischen Königen ausgetauscht wurden.',
      ],
      richtig: 1,
      erklaerung: 'Die wichtigste Quelle, die „Germania" des Tacitus, stammt von einem Römer, der nie dort war — und sie ist eigentlich eine Kritik an Rom. Der älteste lange Text in einer germanischen Sprache ist Wulfilas gotische Bibelübersetzung aus dem 4. Jahrhundert. Was wir sonst wissen, kommt aus Gräbern, Siedlungen und Funden.',
    },
    {
      frage: 'Gab es „die Germanen" als ein Volk?',
      antworten: [
        'Ja, ein einheitliches Volk mit einem König und einer gemeinsamen Hauptstadt.',
        'Nein — „Germanen" ist ein römischer Sammelname für sehr verschiedene Gruppen; viele davon (Franken, Alamannen, Goten) bildeten sich überhaupt erst unterwegs.',
        'Ja, aber erst ab dem Jahr 9 n. Chr., als Arminius sie einte.',
      ],
      richtig: 1,
      erklaerung: 'Caesar zog 58 v. Chr. am Rhein eine Linie und nannte alles östlich davon „Germanen". Die Menschen dort hätten sich als Cherusker, Chatten oder Markomannen bezeichnet. Gruppen entstanden um erfolgreiche Anführer herum, und wer mitzog, gehörte dazu — unabhängig von der Herkunft.',
    },
    {
      frage: 'Womit begann die Völkerwanderung?',
      antworten: [
        'Mit einem geplanten Angriff der Germanen auf die Stadt Rom.',
        'Mit der Absetzung des letzten weströmischen Kaisers 476.',
        'Mit einer Flucht: Um 375 setzten die Hunnen die Goten unter Druck, und 376 baten Zehntausende an der Donau um Aufnahme ins Römische Reich.',
      ],
      richtig: 2,
      erklaerung: 'Rom nahm sie auf — das war üblich, das Reich brauchte Bauern und Soldaten. Dann versagte die Versorgung, römische Beamte verlangten Wucherpreise, und aus Flüchtenden wurden Aufständische. 378 fiel bei Adrianopel ein römisches Heer samt Kaiser Valens.',
    },
    {
      frage: 'Wie viele Menschen waren bei einer solchen Wanderung unterwegs?',
      antworten: [
        'Millionen — halb Nordeuropa setzte sich in Bewegung.',
        'Zehntausende je Gruppe; die Vandalen brachten 429 rund 80 000 Menschen nach Afrika, in ein Reich mit zwanzig bis dreißig Millionen Einwohnern.',
        'Nur wenige hundert Krieger, die sich Reiche eroberten.',
      ],
      richtig: 1,
      erklaerung: 'Es war keine Flut, sondern eine bewaffnete Minderheit, die an die Spitze rückte. Genau deshalb behielten die neuen Könige die römische Verwaltung: Ohne sie hätten sie ihre Länder gar nicht regieren können.',
    },
    {
      frage: 'Was geschah mit der lateinischen Sprache, nachdem die germanischen Reiche entstanden waren?',
      antworten: [
        'Sie verschwand überall, wo germanische Könige herrschten.',
        'Sie blieb und wurde zu Französisch, Spanisch, Portugiesisch, Italienisch und Rumänisch — die neuen Herren übernahmen die Sprache der Beherrschten. Nur in Britannien riss der Faden.',
        'Sie wurde durch das Gotische ersetzt, weil Wulfila die Bibel übersetzt hatte.',
      ],
      richtig: 1,
      erklaerung: 'Die Franken ließen ihr Recht auf Latein aufschreiben, Theoderich regierte Italien mit römischen Beamten. Wer eine Sache zerstören will, baut sie danach nicht sorgfältig wieder auf — das ist eines der stärksten Argumente gegen das Wort „Untergang". In Britannien war es anders: Dort verschwand das Latein, und aus dem Namen der Angeln wurde England.',
    },
  ],
};

module.exports = germanen;
