// Thema: Japan — die Inselwelt zwischen Abschottung und Öffnung.
//
// Stand: Runde 6. Enthält vorerst NUR die europäische Sichtweise
// (Stimme: Opus). Die chinesische Sichtweise ergänzt Hermes; die Synthese
// unten ist ausdrücklich vorläufig und wird danach gemeinsam überarbeitet
// (siehe CLAUDE.md, Perspektiven-Workflow).
//
// Bei diesem Thema ist die Lücke besonders schief. Europa kennt Japan seit
// 1543 — China kennt es seit über zweitausend Jahren. Wer die europäische
// Erzählung für die Geschichte Japans hält, hält die letzten fünf Prozent
// für das Ganze. Genau das macht das Thema für diese App wertvoll.
//
// Die Karte liegt in karten/japan.js — sie ist lang und von anderer Art
// (Geometrie statt Erzählung), deshalb in einer eigenen Datei.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/japan');

const japan = {
  id: 'japan',
  titel: 'Japan — die Inselwelt zwischen Abschottung und Öffnung',
  epoche: 'Von der Yamato-Zeit um 300 n. Chr. bis zur Meiji-Restauration 1868',

  aufhaenger: {
    frage: 'Ein Land schließt sich zweihundert Jahre lang selbst ein — und schlägt vierzig Jahre nach seiner Öffnung eine europäische Großmacht. Wie kann beides dasselbe Land sein?',
    text: [
      'Stell dir vor, dein Land beschließt: Ab morgen darf niemand mehr herein.',
      'Und niemand mehr hinaus. Wer das Land verlässt und zurückkommt, wird',
      'hingerichtet. Schiffe dürfen nur noch so klein gebaut werden, dass sie das',
      'offene Meer gar nicht überstehen. Fremde Schiffe werden weggeschickt oder',
      'beschossen.',
      '',
      'Genau das tat Japan ab 1639. Über zweihundert Jahre lang. Offen blieb ein',
      'einziges Fenster: eine künstliche Insel im Hafen von Nagasaki, 120 mal',
      '75 Meter groß — kleiner als zwei Fußballfelder. Dort durften rund zwanzig',
      'Niederländer wohnen, streng bewacht, und einmal im Jahr nach Edo reisen,',
      'um dem Shogun Bericht zu erstatten.',
      '',
      'Zweihundert Jahre später, 1853, erzwangen vier amerikanische Kriegsschiffe',
      'die Öffnung. Europa und Amerika waren sich einig, was jetzt käme: noch ein',
      'rückständiges Land, das man aufteilen kann. So war es überall gelaufen.',
      '',
      'Es kam anders. 1905 versenkte die japanische Flotte in der Meerenge von',
      'Tsushima fast die gesamte russische Ostseeflotte. Zum ersten Mal seit',
      'Jahrhunderten hatte eine asiatische Macht eine europäische Großmacht in',
      'einem Krieg besiegt. Zwischen der Ankunft der schwarzen Schiffe und diesem',
      'Tag lagen zweiundfünfzig Jahre — ein Menschenleben.',
      '',
      'Wie geht das? Und warum staunt ausgerechnet Europa darüber so sehr?',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Europäische Sichtweise',
      stimme: 'Opus',
      text: [
        'So wird die Geschichte Japans in Europa erzählt: als Abfolge von',
        'Ankünften. Erst kommen die Portugiesen, dann werden die Fremden',
        'vertrieben, dann kommen die Amerikaner, dann wird Japan modern. Merkst',
        'du etwas? In dieser Erzählung passiert Japan etwas — es tut selbst',
        'nichts. Die Handelnden sind immer wir.',
        '',
        'Das ist kein Zufall und keine Bosheit. Es ist einfach die Sicht von',
        'jemandem, der spät dazukam: Als der erste Europäer japanischen Boden',
        'betrat, war die Hauptstadt Kyoto bereits 750 Jahre alt. Lies das Folgende',
        'also als das, was es ist — der Blick von außen, und zwar von sehr weit',
        'außen.',
        '',
        '## 1543: Ein Sturm, ein Schiff, zwei Gewehre',
        '',
        'Ein chinesisches Handelsschiff mit portugiesischen Kaufleuten an Bord',
        'wird auf die kleine Insel Tanegashima südlich von Kyushu verschlagen. So',
        'beginnt der Kontakt zwischen Europa und Japan: durch Zufall, durch',
        'schlechtes Wetter.',
        '',
        'Der Inselherr kaufte den Fremden zwei Arkebusen ab — Vorderlader,',
        'ungenau, langsam. Und jetzt kommt der Teil, den die europäische',
        'Erzählung gern übergeht: Japan kopierte die Waffe nicht nur, es',
        'überholte Europa. Innerhalb weniger Jahrzehnte stellten japanische',
        'Schmiede Feuerwaffen in großer Zahl her. 1575, in der Schlacht von',
        'Nagashino, feuerten dreitausend Schützen hinter Palisaden in',
        'Reihenfeuer — eine Taktik, die es so in Europa noch kaum gab. Es ist gut',
        'möglich, dass es um 1600 in Japan mehr Feuerwaffen gab als in irgendeinem',
        'europäischen Land.',
        '',
        'Sechs Jahre nach dem Sturm, 1549, landete der Jesuit Franz Xaver in',
        'Kagoshima. Die Mission war zunächst erfolgreich: Um 1600 gab es',
        'vielleicht 300 000 japanische Christen, mehr als in manchem europäischen',
        'Fürstentum. Die Japaner nannten die Neuankömmlinge *Nanban* — „südliche',
        'Barbaren", weil ihre Schiffe aus dem Süden kamen. Die Europäer wiederum',
        'waren fasziniert: von der Sauberkeit, von der Höflichkeit, von einer',
        'Kriegerschicht, die einen eigenen Ehrbegriff besaß. Franz Xaver schrieb',
        'nach Hause, dies sei das beste Volk, das er je gesehen habe.',
        '',
        '1582 brachen vier junge japanische Adlige nach Europa auf. Sie waren',
        'acht Jahre unterwegs, wurden in Lissabon, Madrid und Rom empfangen, der',
        'Papst begrüßte sie persönlich, in Venedig wurden Feste gegeben. Als sie',
        '1590 zurückkamen, war Japan ein anderes Land: Das Christentum war',
        'inzwischen verboten.',
        '',
        '## Warum Japan die Tür zuzog',
        '',
        'Die europäische Erzählung nennt das, was folgte, meist',
        '„Christenverfolgung" — und lässt es damit wie religiösen Fanatismus',
        'aussehen. Von Japan aus betrachtet war es Sicherheitspolitik.',
        '',
        'Die japanischen Machthaber sahen sich um. 1571 hatten die Spanier Manila',
        'genommen; auf den Philippinen waren erst die Missionare gekommen und',
        'dann die Soldaten. Portugal hatte Malakka, Goa, Macau. Ein Muster war',
        'erkennbar. Dazu kam ein innenpolitisches Problem: Ein christlicher',
        'Landesfürst gehorchte am Ende einem Papst in Rom — und nicht dem Shogun',
        'in Edo. Für eine Herrschaft, die gerade erst ein zerrissenes Land geeint',
        'hatte, war das untragbar.',
        '',
        '1597 wurden in Nagasaki 26 Christen gekreuzigt. 1637 erhoben sich in',
        'Shimabara zehntausende überwiegend christliche Bauern; der Aufstand wurde',
        'niedergeschlagen, und die Niederländer feuerten von See aus mit auf die',
        'Festung der Aufständischen — sie wollten zeigen, auf welcher Seite sie',
        'standen. 1639 wurden die Portugiesen endgültig ausgewiesen. Wer',
        'verdächtig war, musste auf ein Bildnis Christi treten, das *fumi-e*; wer',
        'zögerte, war überführt.',
        '',
        'Die Niederländer durften bleiben, aus einem einzigen Grund: Sie brachten',
        'keine Priester mit. Sie wollten Handel, sonst nichts. Deshalb bekamen sie',
        'Dejima.',
        '',
        'Und jetzt der Punkt, an dem die europäische Erzählung wirklich schief',
        'wird. Das Wort **Sakoku**, „geschlossenes Land", stammt gar nicht aus der',
        'Zeit selbst: Ein japanischer Übersetzer erfand es 1801, als er das Buch',
        'eines deutschen Arztes ins Japanische übertrug. Japan hat sich also einen',
        'Namen für seine Abschottung von Europa geliehen. Und geschlossen war das',
        'Land ohnehin nur in eine Richtung: Über Tsushima lief der Handel mit',
        'Korea weiter, über Satsuma der mit den Ryukyu-Inseln, über Matsumae der',
        'mit den Ainu im Norden, und in Nagasaki lagen neben den niederländischen',
        'auch chinesische Schiffe. Japan hatte nicht die Welt ausgesperrt. Es',
        'hatte Europa ausgesperrt — bis auf zwanzig Männer auf einer Sandbank.',
        '',
        '## Zweihundert Jahre Gerücht',
        '',
        'Was wusste Europa in dieser Zeit über Japan? Ungefähr so viel, wie man',
        'durch ein Schlüsselloch von 120 mal 75 Metern sehen kann.',
        '',
        'Fast alles, was Europa zu wissen glaubte, stammte von zwei Männern.',
        'Engelbert Kaempfer, ein Arzt aus Lemgo, lebte von 1690 bis 1692 auf',
        'Dejima und schrieb danach eine „Geschichte und Beschreibung von Japan";',
        'sie erschien 1727 und blieb hundert Jahre lang das Buch über Japan.',
        'Philipp Franz von Siebold, ebenfalls Arzt, kam 1823 — und wurde 1829',
        'ausgewiesen, weil man bei ihm japanische Landkarten fand. Karten waren',
        'Staatsgeheimnis; Japan wusste sehr genau, wozu Europäer sie benutzten.',
        '',
        'In diese Lücke setzte Europa seine Fantasie. Japan wurde das',
        '„geheimnisvolle Reich", ein Land aus Lack, Seide und rätselhaften',
        'Bräuchen. Und als es sich dann öffnete, kam die Überraschung von einer',
        'Seite, mit der niemand gerechnet hatte: aus der Kunst. Ab den 1860er',
        'Jahren erreichten japanische Farbholzschnitte Paris — die Legende sagt,',
        'als Packpapier für Porzellan. Was dann passierte, nennt man',
        '**Japonismus**: Monet sammelte Holzschnitte, van Gogh malte Hiroshige',
        'Bild für Bild ab, Degas übernahm die angeschnittenen Bildausschnitte,',
        'Klimt das Gold und die Flächen. Die modernste Kunst Europas lernte',
        'ausgerechnet von dem Land, das Europa für rückständig hielt.',
        '',
        '## Die schwarzen Schiffe',
        '',
        'Am 8. Juli 1853 liefen vier Kriegsschiffe der Vereinigten Staaten in die',
        'Bucht von Tokio ein, zwei davon Dampfer mit schwarzen Rümpfen und',
        'rauchenden Schloten. Kommodore Matthew Perry weigerte sich, wie',
        'vorgeschrieben nach Nagasaki weiterzufahren, ließ Salutschüsse abfeuern,',
        'überreichte einen Brief seines Präsidenten und kündigte an, im nächsten',
        'Jahr die Antwort zu holen. Er kam 1854 mit neun Schiffen wieder.',
        '',
        'Nennen wir das beim Namen: Das war Erpressung mit Kanonen. Und was',
        'danach kam, waren die sogenannten „Ungleichen Verträge" — Europäer und',
        'Amerikaner unterstanden in Japan nicht japanischem Recht, und Japan',
        'durfte seine eigenen Zölle nicht festsetzen. Dasselbe hatte man China',
        'nach den Opiumkriegen aufgezwungen. Es war das übliche Verfahren.',
        '',
        'Japan reagierte zunächst so, wie man es erwartet: mit Wut. Die Losung',
        'hieß *sonnō jōi* — „Verehrt den Kaiser, vertreibt die Barbaren". Junge',
        'Samurai aus den Fürstentümern Satsuma und Chōshū griffen Ausländer an,',
        'beschossen fremde Schiffe — und wurden von westlichen Flotten',
        'zusammengeschossen. Und dann taten genau diese Männer etwas',
        'Bemerkenswertes: Sie zogen aus der Niederlage die entgegengesetzte',
        'Lehre. Wenn man die Fremden nicht vertreiben kann, muss man werden, was',
        'sie sind. 1868 stürzten sie das Shogunat und stellten den Kaiser an die',
        'Spitze — die Meiji-Restauration.',
        '',
        '## In einer Generation',
        '',
        'Was dann geschah, hat in der Geschichte kaum eine Entsprechung.',
        '',
        '1871 verließ die halbe japanische Regierung das eigene Land. Die',
        'Iwakura-Mission reiste zweiundzwanzig Monate durch die Vereinigten',
        'Staaten und Europa, um sich anzusehen, wie Fabriken, Parlamente,',
        'Schulen, Werften und Armeen funktionieren. Zurück kam eine Einkaufsliste:',
        'das Heer nach preußischem Vorbild, die Flotte nach britischem, das',
        'Rechtswesen nach französischem und deutschem, das Schulwesen nach',
        'amerikanischem. Japan nahm nicht „den Westen" — es nahm aus jedem Land',
        'das, was dort am besten funktionierte.',
        '',
        '1872 fuhr die erste Eisenbahn. 1889 gab es eine Verfassung und bald ein',
        'Parlament. 1894/95 besiegte Japan China, 1904/05 Russland — und am',
        '27. Mai 1905 versenkte Admiral Tōgō in der Meerenge von Tsushima fast',
        'die gesamte russische Ostseeflotte, die um die halbe Welt gefahren war.',
        '',
        'Europa war fassungslos. Zeitungen schrieben vom „Wunder". In den',
        'Kolonien las man es anders, nämlich als Signal: Der junge Jawaharlal',
        'Nehru in Indien, Sun Yat-sen in China, Reformer im Osmanischen Reich —',
        'für sie war 1905 der Beweis, dass die europäische Vorherrschaft kein',
        'Naturgesetz war.',
        '',
        'Zwei Dinge sollte man dabei nicht überhören. Erstens: „Wunder" ist ein',
        'bequemes Wort. Es klingt nach Zauberei und erspart die Frage, welche',
        'Voraussetzungen dieses Land schon hatte — eine der höchsten',
        'Alphabetisierungsraten der Welt, eine Millionenstadt, eine Geldwirtschaft,',
        'Straßen, Verwaltung, ein Handwerk von großer Präzision. Japan begann',
        '1868 nicht bei null. Es begann bei sehr viel.',
        '',
        'Zweitens: Japan übernahm vom Westen nicht nur Eisenbahnen und',
        'Verfassungen. Es übernahm auch die Idee, dass eine moderne Macht Kolonien',
        'haben muss. 1895 nahm es Taiwan, 1910 annektierte es Korea. Der Weg',
        'führte weiter, über die Mandschurei bis in den Zweiten Weltkrieg. Das ist',
        'der Teil der Erzählung, den Europa selten als das erzählt, was er auch',
        'ist: eine Lehre, die weitergegeben wurde.',
        '',
        '## Und die andere Seite?',
        '',
        'Alles, was du gerade gelesen hast, umfasst rund dreihundert Jahre — und',
        'auch die nur von außen. Japans Geschichte ist um ein Vielfaches länger,',
        'und ihr entscheidender Nachbar war nie Europa.',
        '',
        'Über anderthalb Jahrtausende kam fast alles Neue über das Meer aus',
        'Westen: Nassreis, Bronze, Eisen, die Schriftzeichen, der Buddhismus, der',
        'Kalender, das Beamtenwesen, der Grundriss der ersten Hauptstadt Nara —',
        'alles aus China, meist über Korea. Japan hat dabei nie einfach',
        'abgeschrieben; es hat ausgewählt, umgebaut, weggelassen. Und 1894 besiegte',
        'dieser Schüler seinen Lehrer.',
        '',
        'Wie erzählt man das von der anderen Seite? Was heißt es für ein Land, das',
        'sich „Reich der Mitte" nennt, wenn die Nachbarinsel, die jahrhundertelang',
        'Gesandtschaften schickte, plötzlich stärker ist? Und wie klingt Japans',
        '„Öffnung" für ein China, das zur selben Zeit von denselben Kanonenbooten',
        'geöffnet wurde — nur mit einem ganz anderen Ausgang?',
        '',
        'Diese Fragen kann die europäische Sichtweise nicht beantworten. Sie',
        'gehören einer zweiten Stimme.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Chinesische Sichtweise',
      stimme: 'Hermes',
      text: [
        'Diese Sichtweise erzählt Japan aus der Nähe — aus China, dem',
        'Nachbarn, der Japan kannte, lange bevor Europa wusste, dass die Inseln',
        'existieren. Die älteste schriftliche Erwähnung Japans steht in einer',
        'chinesischen Chronik. Für China ist Japan nie das „geheimnisvolle',
        'Reich" gewesen, sondern der vertraute Nachbar jenseits des Meeres —',
        'der Schüler, der eigene Wege ging. Und das ist aus chinesischer Sicht',
        'die eigentliche Geschichte.',
        '',
        '## Der Schüler',
        '',
        'Fast alles, was Japan einst zu einem Staat machte, kam aus China: die',
        'Schriftzeichen, der Buddhismus, der Kalender, die Vorstellung von',
        'Beamten und Verwaltung, sogar der Grundriss der ersten Hauptstadt',
        'Nara, die wie eine kleine Chang’an gebaut wurde. Jahrhunderte lang',
        'schickten japanische Herrscher Gesandtschaften aufs Festland, um zu',
        'lernen. China sah darin die natürliche Ordnung: Die Mitte gab, die',
        'Ränder nahmen — und der japanische Hof zahlte seinen Tribut, wie es',
        'sich gehörte.',
        '',
        '## Der Titel, der Anmaßung war',
        '',
        'Doch schon früh zeigte der Schüler, dass er nicht bleiben wollte, was',
        'er war. Der japanische Herrscher nannte sich *Tenno* — „himmlischer',
        'Herrscher". Aus chinesischer Sicht war das eine Anmaßung: Es konnte',
        'nur EINEN Sohn des Himmels geben, und der saß in China. Dass der',
        'Nachbar denselben Anspruch erhob, war eine stille Rebellion — der',
        'erste Schritt auf einem Weg, der China bis heute beschäftigt.',
        '',
        'Und dann kam der eigentliche Bruch, den Außenstehende kaum sehen:',
        'Japan hörte auf, den Kreislauf zu teilen. In China wechselten die',
        'Dynastien, wenn das Mandat des Himmels verwirkt war — das war die',
        'Ordnung der Welt. In Japan aber blieb die Kaiserlinie bestehen,',
        'Jahrhundert um Jahrhundert, während die wahre Macht zu den',
        'Kriegern, den Samurai, und ihren Shogunen wanderte. Aus chinesischer',
        'Sicht war das eine Ordnung ohne Mandat: eine Herrschaft, die sich',
        'nie erneuert, und eine Macht, die nicht zu dem gehört, der sie',
        'ausübt. Der Schüler hatte die Formen übernommen — und den Kern',
        'durch etwas Eigenes ersetzt.',
        '',
        '## Die Unverschämtheit von 1592',
        '',
        'Dass der Schüler den Lehrer herausfordern würde, zeigte sich 1592.',
        'Der Feldherr Hideyoshi, der Japan gerade geeint hatte, fiel in Korea',
        'ein — in ein Land, das zu China gehörte wie ein Vasall zu seinem',
        'Herrn. China schickte ein Heer, und nach Jahren des Krieges zog',
        'Japan sich zurück. Aus chinesischer Sicht war das ein Sieg der',
        'Ordnung: Der Angreifer war zurückgeschlagen worden, der Schüler in',
        'die Schranken gewiesen.',
        '',
        'Doch die eigentliche Lektion las China erst später. Hideyoshis',
        'Feldzug zeigte, dass Japan nicht nur lernen, sondern auch angreifen',
        'konnte — und dass es den Platz, den China für sich selbst reserviert',
        'hatte, nicht anerkannte.',
        '',
        '## Die Demütigung von 1894',
        '',
        'Und dann kam das Jahr 1894. Japan, das sich gerade nach westlichem',
        'Vorbild modernisiert hatte, griff China an — und gewann. Der',
        'Schüler besiegte den Lehrer. Für China war das mehr als eine',
        'Niederlage: Es war der Zusammenbruch einer Weltordnung. Das Reich',
        'der Mitte, das seit Jahrtausenden die Mitte gewesen war, musste',
        'zusehen, wie die Insel am Rand es demütigte.',
        '',
        'Zur selben Zeit waren China und Japan von denselben Kanonenbooten',
        '„geöffnet" worden — mit ganz unterschiedlichem Ausgang. Japan zog',
        'die Lehre sofort: Wer vom Westen lernt, überlebt. China zögerte,',
        'und das Zögern kostete. Aus chinesischer Sicht ist Japans',
        'Modernisierung deshalb kein „Wunder" — ein Wort, das Europa',
        'benutzt, weil es die Vorgeschichte nicht kennt. Es war eine',
        'Entscheidung, die Japan traf, und eine Demütigung, die China erlitt,',
        'weil es die eigene nicht traf.',
        '',
        '## Was diese Sicht anders macht',
        '',
        'Zwei Dinge unterscheiden die chinesische Erzählung von der',
        'europäischen.',
        '',
        'Erstens: Japan war für China nie ein Rätsel, sondern ein',
        'Maßstab. China maß sich an Japan, lange bevor der Westen auf der',
        'Bühne erschien — erst als Schüler, dann als Rivale, schließlich als',
        'Lehrstück. Die Frage „Warum ist Japan stärker als wir?" hat die',
        'chinesische Politik seit 1894 nicht losgelassen. Europa sah Japan',
        'durch ein Schlüsselloch; China sah Japan über die Schulter — und',
        'verstand es am Ende auch nicht. Nähe ist keine Garantie für',
        'Verstehen.',
        '',
        'Zweitens: Die chinesische Erzählung neigt dazu, Japans',
        'Eigenständigkeit kleinzureden. „Alles kam aus China" — das ist',
        'wahr und doch eine Vereinfachung, die der Nachbar mit Recht',
        'zurückweisen würde. Japan hat nie abgeschrieben; es hat ausgewählt,',
        'umgebaut, weggelassen. Wer nur die eine Hälfte erzählt, macht',
        'denselben Fehler wie die europäische Erzählung, die bei 1543',
        'beginnt: Er verwechselt seinen Ausschnitt mit der ganzen',
        'Geschichte.',
        '',
        'Das ist keine Korrektur der europäischen Sicht. Es ist die Stimme',
        'des Nachbarn, der den Schüler kannte, bevor die Welt ihn',
        'entdeckte — und der bis heute mit der Frage lebt, ob der Schüler',
        'den Lehrer übertreffen darf, ohne ihn zu verraten.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 6, gemeinsam überarbeitet nach Ergänzung der
  // chinesischen Sichtweise durch Hermes).
  synthese: [
    'Zwei Nachbarn erzählen von Japan: Europa, das es seit 1543 kennt —',
    'und China, das es seit über zweitausend Jahren kennt. Und beide',
    'Erzählungen sagen am Ende mehr über die Erzähler als über Japan.',
    '',
    '**Wo sie sich treffen:** Beide Sichtweisen erzählen von der',
    'Übernahme — Japan lernte von China (Schrift, Buddhismus, Verwaltung)',
    'und später vom Westen (Eisenbahnen, Verfassung, Heer). Beide nennen',
    'die „Öffnung" von 1853 eine erzwungene, keine freiwillige — Europa',
    'spricht offen von Kanonenboot-Erpressung, China erinnert daran, dass',
    'es zur selben Zeit von denselben Mächten aufgebrochen wurde. Und',
    'beide staunen über die Modernisierung — nur mit verschiedenen',
    'Wörtern.',
    '',
    '**Wo sie auseinandergehen:** Die europäische Erzählung beginnt bei',
    'den Ankünften — „entdeckt", „geöffnet", „Wunder". In ihr passiert',
    'Japan etwas; die Handelnden sind die Fremden. Die chinesische',
    'Erzählung beginnt beim Schüler, der wählt, umbaut, weglässt — und',
    'schließlich den Lehrer herausfordert: 1592 in Korea, 1894 im Krieg',
    'gegen China. Für Europa war 1905 das „Wunder von Tsushima". Für',
    'China war 1894 die Demütigung, die eine Weltordnung beendete. Die',
    'Wortwahl verrät es: „geheimnisvolles Reich" (Europa, das durch ein',
    'Schlüsselloch sah) — und „der vertraute Nachbar" (China, das über',
    'die Schulter sah und ihn am Ende auch nicht verstand).',
    '',
    '**Was daraus folgt:** Beide Erzählungen verwechseln ihren Ausschnitt',
    'mit der ganzen Geschichte. Europa deckt die letzten paar Prozent ab',
    'und tut so, als sei es die Geschichte; China neigt dazu, Japans',
    'Eigenständigkeit kleinzureden, weil „alles aus China kam". Japan',
    'selbst — das weder ein Rätsel noch ein Schüler sein wollte — hat in',
    'diesem Kapitel keine eigene Stimme. Vielleicht ist genau das die',
    'beste Übung: Eine Geschichte, die so viel über die Erzähler verrät,',
    'macht sichtbar, wie sehr jede Geschichtsschreibung eine',
    'Standortbestimmung ist.',
    '',
    '**Dein Urteil beginnt hier:** Wessen Erzählung hilft dir mehr, Japans',
    'Weg zu verstehen — die von außen (Europa) oder die von nebenan',
    '(China)? Und welche Fragen würdest du Japan selbst stellen, wenn es',
    'eine eigene Stimme bekäme?',
  ].join('\n'),

  urteil: {
    frage: 'Japan hat sich über zweihundert Jahre lang bewusst von Europa abgeschottet — und wurde 1853 mit Kriegsschiffen zur Öffnung gezwungen. War die Abschottung eine kluge Entscheidung oder ein teurer Fehler? Und wer darf eigentlich bestimmen, ob ein Land seine Türen offen hält: das Land selbst, oder die, die hineinwollen?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Zwei Gedanken zum Weiterdrehen: Die Nachbarn, die sich nicht abschotteten — China, Indien —, wurden im 19. Jahrhundert aufgeteilt oder erobert; Japan nicht. Sagt das etwas über die Abschottung? Und: Prüfe deine Antwort noch einmal, indem du die Rollen tauschst. Was, wenn ein anderes Land vor deiner Küste ankert und Handel verlangt?',
  },

  quiz: [
    {
      frage: 'War Japan während der Abschottung wirklich von der ganzen Welt abgeschnitten?',
      antworten: [
        'Ja, über 200 Jahre lang kam und ging niemand.',
        'Nein: Der Handel mit Korea (über Tsushima), mit den Ryukyu-Inseln und mit den Ainu im Norden lief weiter, und in Nagasaki lagen chinesische Schiffe neben den niederländischen.',
        'Nein, aber nur, weil einzelne Schmuggler die Regeln brachen.',
      ],
      richtig: 1,
      erklaerung: 'Abgeschottet war Japan vor allem gegen Europa — und selbst dort blieb Dejima offen. Nach Asien hin gab es vier geregelte Tore. „Geschlossenes Land" ist deshalb ein Wort, das mehr über den europäischen Blick sagt als über Japan: Wer nicht hineindurfte, hielt das Land für zu.',
    },
    {
      frage: 'Wer waren die Samurai?',
      antworten: [
        'Eine Kriegerschicht im Dienst eines Herrn. Ab 1185 lag die tatsächliche Macht bei ihren Anführern, den Shogunen — der Kaiser blieb Symbol.',
        'Die Leibwache des Kaisers, die immer direkt für ihn kämpfte.',
        'Wandernde Einzelkämpfer ohne Herrn und ohne Land.',
      ],
      richtig: 0,
      erklaerung: 'Die Doppelherrschaft prägte Japan fast 700 Jahre: ein Kaiser mit Würde in Kyoto, ein Shogun mit Truppen — erst in Kamakura, später in Edo. Herrenlose Samurai gab es auch, man nannte sie Ronin, aber das war die Ausnahme.',
    },
    {
      frage: 'Was geschah 1853 in der Bucht von Tokio?',
      antworten: [
        'Ein Taifun zerstörte eine fremde Flotte, wie schon 1274 und 1281.',
        'Der letzte Shogun trat freiwillig zurück.',
        'Vier US-Kriegsschiffe unter Kommodore Perry erzwangen die Öffnung Japans — mit Salutschüssen und der Ankündigung, im nächsten Jahr mit mehr Schiffen wiederzukommen.',
      ],
      richtig: 2,
      erklaerung: 'Man nennt so etwas Kanonenbootdiplomatie. Perry kam 1854 mit neun Schiffen zurück; Japan öffnete zwei Häfen. Fünfzehn Jahre später war das Shogunat abgeschafft — die Öffnung von außen löste eine Umwälzung von innen aus.',
    },
    {
      frage: 'Wie alt ist das japanische Kaiserhaus?',
      antworten: [
        'Es wurde 1868 neu geschaffen, als das Shogunat endete.',
        'Es ist die älteste ununterbrochene Monarchie der Welt — die frühesten Kaiser sind allerdings sagenhaft, sicher belegt wird die Linie ab etwa dem 6. Jahrhundert.',
        'Es entstand erst mit der Verfassung von 1889.',
      ],
      richtig: 1,
      erklaerung: 'Gerade weil der Kaiser die längste Zeit keine Macht hatte, überstand er jeden Machtwechsel: Wer regierte, tat es in seinem Namen. 1868 musste man deshalb keinen neuen Herrscher erfinden — man holte den hervor, der die ganze Zeit dagewesen war.',
    },
    {
      frage: 'Womit begann 1543 der Kontakt zwischen Europa und Japan?',
      antworten: [
        'Mit einem Handelsvertrag zwischen Portugal und dem Shogun.',
        'Mit einer Gesandtschaft des Papstes.',
        'Mit einem Schiff, das ein Sturm nach Tanegashima verschlug — an Bord portugiesische Kaufleute und zwei Feuerwaffen, die Japan innerhalb weniger Jahrzehnte selbst in großer Zahl baute.',
      ],
      richtig: 2,
      erklaerung: 'Schon der erste Kontakt widerlegt das Bild vom staunenden, rückständigen Japan: 1575 feuerten bei Nagashino dreitausend Schützen in Reihenfeuer. Um 1600 gab es in Japan vermutlich mehr Feuerwaffen als in irgendeinem europäischen Land.',
    },
  ],
};

module.exports = japan;
