// Thema: Die neue Weltordnung und der Kalte Krieg (1945–1991).
//
// Stand: Runde 20 + Hermes-Pass. Drei Stimmen sind fertig: die Sicht des
// Westens (Stimme: Opus), die Sicht des Ostens — Sowjetunion, Warschauer
// Pakt, DDR (Stimme: Hermes) und die Sicht der Deutschen in Ost und West,
// für die die Teilung Alltag war (Stimme: Hermes). Die Synthese führt
// alle drei zusammen.
//
// Achtzehntes Thema und elftes Kapitel des Neuzeit-Bogens
// (notizen/kapitel-planung.md, Kapitel 11). Es beginnt dort, wo „Der Zweite
// Weltkrieg und die neue Weltordnung" endet: 1945, bei den Siegern, die sich
// noch die Hände schütteln.
//
// Die Reihenfolge der Stimmen ist keine Rangfolge. Dass hier der Westen
// zuerst spricht, ergibt sich allein daraus, wer diese Runde übernommen hat;
// das steht auch so im Text, damit niemand die Reihenfolge als Wertung liest.
//
// TONE-REGEL (CLAUDE.md, Zusatzregel für sensible Themen — dieses Kapitel
// berührt Menschen, die noch leben, und einen Konflikt, dessen Nachwirkungen
// die Gegenwart bestimmen): Diese Perspektive benennt ihre unbequemen Stellen
// selbst — die McCarthy-Ära, Vietnam, die Unterstützung von Diktaturen gegen
// den Kommunismus (Iran 1953, Guatemala 1954, Chile, die Obristen in
// Griechenland, Franco, Salazar, Südafrika), den Rüstungswettlauf und die
// Tatsache, dass 1953, 1956 und 1968 niemand zu Hilfe kam. Die Beweggründe
// der anderen Seite werden fair wiedergegeben, ausdrücklich auch die
// sowjetische Angst vor Einkreisung, die aus westlicher Sicht übertrieben,
// aber nicht erfunden war. Die Quizfragen bleiben Wissensfragen: Sie fragen
// nicht nach Schuld.
//
// Der Zwei-plus-Vier-Vertrag steht nach Betreiber-Vorgabe prominent im Text,
// mitsamt der Frage, ob er eingehalten wurde. Dabei gilt: **Artikel 6**
// erlaubt dem vereinten Deutschland ausdrücklich die Bündnismitgliedschaft,
// **Artikel 7** beendet die Vier-Mächte-Rechte und gibt volle Souveränität.
// Die Debatte über den „Geist" des Vertrags und die NATO-Osterweiterung
// gehört nach Kapitel 12 (Russland und der Westen); hier steht nur der
// Befund, dass der Vertrag selbst die Mitgliedschaft nicht verbot.
//
// Die Karte liegt in karten/kalter-krieg.js — drei Zustände (1949, 1961/62,
// 1989–1991). Kuba liegt außerhalb des Ausschnitts; warum, steht im Kopf der
// Kartendatei.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/kalter-krieg');

const kalterKrieg = {
  id: 'kalter-krieg',
  titel: 'Die neue Weltordnung und der Kalte Krieg',
  epoche: '1945–1991',

  aufhaenger: {
    frage: 'Zwei Länder, die gemeinsam Hitler besiegt hatten, richteten binnen zwei Jahren ihre Waffen aufeinander — und vierzig Jahre später verschwand die eine Seite, ohne dass zwischen den beiden Blöcken ein einziger Schuss gefallen war. Wie wird aus Verbündeten so schnell das Gegenteil, und warum bricht ein Weltreich zusammen, das niemand besiegt hat?',
    text: [
      'Im April 1945 trafen sich amerikanische und sowjetische Soldaten an der',
      'Elbe bei Torgau. Es gibt Fotos davon: junge Männer, die einander',
      'umarmen, auf Panzern sitzen, in die Kamera lachen. Zwei Jahre später',
      'war zwischen ihren Ländern ein Zustand entstanden, für den man ein neues',
      'Wort brauchte — Kalter Krieg. Kalt, weil die beiden Großmächte nie',
      'direkt gegeneinander kämpften. Krieg, weil sie sonst alles taten, was',
      'Krieg ausmacht: aufrüsten, drohen, spionieren, Verbündete sammeln und',
      'in fremden Ländern gegeneinander kämpfen lassen.',
      '',
      'Mitten hindurch lief eine Linie, und sie lief mitten durch Deutschland.',
      '1 393 Kilometer Zaun, Minen und Wachtürme, dazu 155 Kilometer Mauer um',
      'West-Berlin herum. Eine Stadt, in der man in einer Straßenbahn sitzen',
      'konnte und beim Aussteigen in einem anderen Weltsystem stand. Nirgendwo',
      'sonst war der Kalte Krieg so wörtlich zu sehen.',
      '',
      'Zweimal stand die Welt dabei kurz vor dem Ende: im Oktober 1962, als',
      'sowjetische Raketen auf Kuba entdeckt wurden, und immer wieder in den',
      'Momenten, in denen ein Radarschirm etwas anzeigte, das gar nicht da war.',
      'Auf dem Höhepunkt lagerten weltweit über 60 000 Atomsprengköpfe — genug,',
      'um jede größere Stadt der Erde mehrfach zu zerstören.',
      '',
      'Und dann, 1989, brach die eine Seite zusammen. Nicht durch eine',
      'Niederlage im Feld, sondern durch leere Regale, eine Wirtschaft, die',
      'nicht mehr mithielt, einen Ölpreis, der abstürzte, einen Generalsekretär,',
      'der reformieren wollte — und durch Menschen, die ohne Waffen auf die',
      'Straße gingen und nicht mehr weggingen. Am 25. Dezember 1991 hörte die',
      'Sowjetunion auf zu bestehen.',
      '',
      'Dieses Kapitel beginnt mit der Sicht des Westens. Das ist eine von',
      'mehreren Stimmen, nicht die richtige — welche zuerst spricht, hängt',
      'davon ab, wer diese Runde geschrieben hat, und ist keine Rangfolge.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'Die Sicht des Westens — USA, Großbritannien, Westeuropa und die Bundesrepublik',
      stimme: 'Opus',
      text: [
        'Diese Stimme erzählt aus Washington, London, Paris und Bonn: aus den',
        'Regierungsvierteln, in denen die Beschlüsse fielen, aber auch aus den',
        'Wohnzimmern, in denen die Nachrichten liefen, aus West-Berlin, das',
        'sich vierzig Jahre lang als Insel verstand, und aus den Schulen, in',
        'denen Kinder lernten, was im Falle eines Angriffs zu tun sei.',
        '',
        'Sie ist gleichwertig mit den anderen Stimmen dieses Kapitels. Dass sie',
        'hier zuerst steht, ist keine Rangfolge — es liegt nur daran, wer diese',
        'Runde übernommen hat. Und sie hat eine Aufgabe, die sie sich selbst',
        'stellt: Sie darf nicht die Siegererzählung erzählen, die nach 1989 so',
        'bequem war. Der Westen hat den Kalten Krieg mit Mitteln geführt, die',
        'seinen eigenen Grundsätzen widersprachen, und dieser Text nennt sie —',
        'nicht am Rand, sondern in einem eigenen Abschnitt.',
        '',
        '## Aus Verbündeten werden Gegner (1945–1947)',
        '',
        'Die Allianz gegen Hitler war eine Zweckgemeinschaft. Franklin D.',
        'Roosevelt, Winston Churchill und Josef Stalin einte ein gemeinsamer',
        'Feind und sonst wenig. Auf der Konferenz von Jalta im Februar 1945 und',
        'in Potsdam im Juli und August wurde geregelt, was mit Deutschland',
        'geschehen sollte: Entwaffnung, Entnazifizierung, vier Besatzungszonen,',
        'Reparationen, die Westverschiebung Polens. Was nicht geregelt wurde,',
        'war das Entscheidende — wie es weitergehen sollte, wenn der gemeinsame',
        'Feind besiegt war.',
        '',
        'Aus westlicher Sicht wurde die Antwort in Osteuropa gegeben, und zwar',
        'schnell. In Polen, Rumänien, Bulgarien und Ungarn entstanden zwischen',
        '1945 und 1948 Regierungen, die nach Wahlen an der Macht waren, deren',
        'Ordnungsmäßigkeit im Westen niemand glaubte. Im Februar 1948 übernahm',
        'die Kommunistische Partei in der Tschechoslowakei — dem einzigen Land',
        'der Region mit einer funktionierenden Demokratie zwischen den Kriegen —',
        'die alleinige Macht. Für viele im Westen war das der Moment, in dem aus',
        'Misstrauen Gewissheit wurde.',
        '',
        'Und die Gegenseite? Ihre Beweggründe gehören hierher, und diese Stimme',
        'gibt sie so wieder, wie sie waren, nicht als Karikatur. Die',
        'Sowjetunion hatte im Zweiten Weltkrieg rund 27 Millionen Menschen',
        'verloren — mehr als jedes andere Land. Sie war binnen dreißig Jahren',
        'zweimal von Westen her überfallen worden, 1914 und 1941, und beim',
        'zweiten Mal war der Angriff ein Vernichtungskrieg gewesen. Wer in',
        'Moskau nach Sicherheit fragte, dachte an einen Gürtel befreundeter',
        'Staaten zwischen sich und Deutschland. Aus westlicher Sicht war die',
        'daraus abgeleitete Furcht vor Einkreisung übertrieben — sie erklärte',
        'nicht, warum in Warschau, Prag und Budapest Regierungen gegen den',
        'Willen der Bevölkerung eingesetzt werden mussten. Erfunden war sie',
        'aber nicht, und wer sie als bloßen Vorwand abtut, versteht die',
        'sowjetische Politik dieser Jahre nicht.',
        '',
        'Zwei Texte gaben der westlichen Politik ihre Form. Im Februar 1946',
        'schickte der amerikanische Diplomat George F. Kennan aus Moskau das',
        '„lange Telegramm": Die Sowjetunion sei nicht durch Zugeständnisse zu',
        'befrieden, wohl aber durch geduldiges Gegenhalten an ihren Grenzen',
        'einzudämmen. Aus dem Gedanken wurde ein Wort — **Containment**,',
        'Eindämmung —, und aus dem Wort die Leitlinie von vierzig Jahren. Am',
        '5. März 1946 sprach Winston Churchill im amerikanischen Fulton den Satz,',
        'der zur Überschrift der Epoche wurde: Von Stettin an der Ostsee bis',
        'Triest an der Adria habe sich ein **Eiserner Vorhang** über den',
        'Kontinent gesenkt.',
        '',
        'Am 12. März 1947 verkündete Präsident Harry S. Truman vor dem',
        'Kongress, was seither die **Truman-Doktrin** heißt: Die USA würden',
        'freie Völker unterstützen, die sich bewaffneten Minderheiten oder',
        'äußerem Druck widersetzten. Der konkrete Anlass war Griechenland, wo',
        'ein Bürgerkrieg tobte, und die Türkei, auf die Moskau Druck ausübte;',
        'Großbritannien konnte die Unterstützung aus eigener Kraft nicht mehr',
        'leisten. Der Anspruch aber war weltweit — und darin lag beides: eine',
        'Absage an den Isolationismus der 1930er Jahre, der zugesehen hatte,',
        'wie Europa in den Krieg schlitterte, und der Anfang einer Politik, die',
        'am Ende auch Diktatoren stützen würde, solange sie antikommunistisch',
        'waren.',
        '',
        '## Der Marshallplan (1947/48) — Hilfe und Machtpolitik zugleich',
        '',
        'Am 5. Juni 1947 hielt Außenminister George C. Marshall in Harvard eine',
        'Rede, in der er Europa amerikanische Wirtschaftshilfe anbot. Aus ihr',
        'wurde das European Recovery Program: rund 13 Milliarden Dollar',
        'zwischen 1948 und 1952 — nach heutiger Kaufkraft weit über hundert',
        'Milliarden —, dazu Rohstoffe, Maschinen, Lebensmittel und',
        'Fachwissen. Die europäischen Städte lagen in Trümmern, der Winter',
        '1946/47 war der kälteste seit Menschengedenken gewesen, in mehreren',
        'Ländern hungerten Menschen. Der Marshallplan hat diesen Zustand',
        'beendet, und das ist keine kleine Sache.',
        '',
        'Er war auch Machtpolitik, und diese Stimme sagt das selbst, statt es',
        'sich vorhalten zu lassen. Erstens: Das Geld schuf Absatzmärkte für die',
        'amerikanische Industrie, die nach dem Krieg als einzige unzerstört',
        'dastand, und band Westeuropa an den Dollar. Zweitens: Es war an',
        'Bedingungen geknüpft — die Empfänger mussten ihre Wirtschaftsdaten',
        'offenlegen, gemeinsam planen und den Handel öffnen. Drittens, und das',
        'ist der wichtigste Punkt: Das Angebot ging ausdrücklich auch an die',
        'Sowjetunion und an Polen und die Tschechoslowakei. Moskau lehnte im',
        'Juli 1947 in Paris ab und untersagte es den Staaten seiner',
        'Einflusszone; die tschechoslowakische Regierung, die zunächst zusagen',
        'wollte, musste ihre Zusage zurückziehen. Aus Moskauer Sicht hätte',
        'annehmen bedeutet, Washington Einblick in die eigenen Bücher zu geben',
        'und sich wirtschaftlich abhängig zu machen — auch das ist ein',
        'nachvollziehbarer Gedanke, kein bloßer Trotz.',
        '',
        'Damit war die Teilung Europas eine wirtschaftliche geworden. Der',
        'Westen bekam Kredite und einen gemeinsamen Markt, der Osten den',
        'Rat für gegenseitige Wirtschaftshilfe (1949) und eine Ordnung, in der',
        'Moskau die Preise setzte. Diese Weiche von 1947 erklärt einen guten',
        'Teil dessen, was vierzig Jahre später an den leeren Regalen zu sehen',
        'war.',
        '',
        '## Berlin 1948/49 — die Luftbrücke',
        '',
        'Am 20. Juni 1948 führten die Westzonen die D-Mark ein; drei Tage',
        'später galt sie auch in den Westsektoren Berlins. Für die westliche',
        'Seite war das eine Notwendigkeit — die alte Reichsmark war wertlos,',
        'der Schwarzmarkt regierte. Für die sowjetische Seite war es der Bruch',
        'der gemeinsamen Verwaltung Deutschlands, und diese Lesart ist nicht',
        'abwegig: Eine eigene Währung ist der halbe Weg zu einem eigenen Staat.',
        'Am 24. Juni 1948 wurden alle Straßen, Bahnlinien und Wasserwege nach',
        'West-Berlin gesperrt. Zwei Millionen Menschen waren abgeschnitten.',
        '',
        'Was dann geschah, ist die eindrücklichste Geschichte, die der Westen',
        'aus diesem Kapitel zu erzählen hat. Die drei Luftkorridore waren 1945',
        'schriftlich vereinbart worden — die Straßen waren gesperrt, der',
        'Luftweg zugesichert. Elf Monate lang versorgten rund 280 000 Flüge die',
        'Stadt mit etwa 2,3 Millionen Tonnen Kohle, Mehl, Medikamenten und',
        'sogar den Einzelteilen eines Kraftwerks. Auf dem Höhepunkt landete',
        'alle drei Minuten ein Flugzeug. Der Flughafen Tegel wurde in neunzig',
        'Tagen gebaut, überwiegend von Berlinerinnen — den „Trümmerfrauen" —,',
        'die Schutt wegräumten. Rund achtzig Menschen kamen bei Abstürzen ums',
        'Leben, Briten, Amerikaner und Deutsche.',
        '',
        'Der amerikanische Pilot **Gail Halvorsen** begann, über den',
        'Wohnvierteln Süßigkeiten an selbstgebastelten Fallschirmen abzuwerfen.',
        'Aus der privaten Idee wurde die Aktion „Little Vittles", aus den',
        'Flugzeugen wurden die **Rosinenbomber**. Am 12. Mai 1949 hob die',
        'sowjetische Seite die Blockade auf.',
        '',
        'Was hier wirklich geschah, war eine Umkehrung: Drei Jahre nach dem',
        'Ende eines Krieges, den Deutschland begonnen hatte, standen Berliner',
        'Kinder an der Einflugschneise und winkten den Flugzeugen zu, die ihre',
        'Stadt bombardiert hatten. Aus Besatzern wurden Schutzmächte. Diese',
        'Stimme benennt auch das Unbequeme daran: Die Luftbrücke war eine',
        'humanitäre Leistung und ein politischer Erfolg zugleich, und in',
        'Washington und London war beides von Anfang an bekannt. Wer die',
        'Herzen einer Stadt gewinnt, gewinnt eine Position.',
        '',
        'Im selben Jahr entstanden zwei deutsche Staaten: die Bundesrepublik',
        '(Grundgesetz vom 23. Mai 1949) und die DDR (7. Oktober 1949). Keiner',
        'von beiden verstand sich als endgültig. Bonn wurde Hauptstadt, weil es',
        'unbedeutend genug war, um provisorisch zu wirken.',
        '',
        '## Zwei Blöcke: NATO 1949, Warschauer Pakt 1955',
        '',
        'Am 4. April 1949 unterzeichneten zwölf Staaten in Washington den',
        'Nordatlantikvertrag: die USA, Kanada, Großbritannien, Frankreich,',
        'Italien, Belgien, die Niederlande, Luxemburg, Norwegen, Dänemark,',
        'Island und Portugal. Der Kern ist Artikel 5 — ein Angriff auf einen',
        'gilt als Angriff auf alle. Zum ersten Mal in ihrer Geschichte gingen',
        'die USA in Friedenszeiten ein Bündnis mit europäischen Staaten ein.',
        '',
        'Der erste Generalsekretär Lord Ismay soll den Zweck der NATO so',
        'zusammengefasst haben: die Amerikaner drinnen, die Russen draußen und',
        'die Deutschen unten zu halten. Ob er den Satz je gesagt hat, ist',
        'ungeklärt — aber er stand in Umlauf, weil er einen wahren Kern hatte,',
        'und diese Stimme führt ihn deshalb an und nicht gegen sich verwenden',
        'lässt. Das Bündnis war auch ein Instrument, die Bundesrepublik',
        'einzubinden, und Portugal war zu diesem Zeitpunkt eine Diktatur.',
        '',
        '1952 traten Griechenland und die Türkei bei, 1955 die Bundesrepublik.',
        'Neun Tage nach ihrem Beitritt, am 14. Mai 1955, wurde in Warschau der',
        '**Warschauer Pakt** gegründet — mit der DDR als Mitglied. Damit stand',
        'die Ordnung, die bis 1989 hielt. Im selben Jahr zeigte der',
        'österreichische Staatsvertrag allerdings, dass es auch anders ging:',
        'Die sowjetischen Truppen zogen aus Österreich ab, das Land erklärte',
        'sich für immerwährend neutral. Dieses Beispiel gehört in eine faire',
        'Erzählung hinein.',
        '',
        'Dazu kam die Bombe. 1949 hatte die Sowjetunion ihre erste',
        'Kernwaffe, 1952 und 1953 folgten auf beiden Seiten die',
        'Wasserstoffbomben, 1957 schoss Moskau mit Sputnik den ersten',
        'Satelliten ins All — und bewies damit, dass es Raketen besaß, die',
        'jeden Punkt der Erde erreichen konnten. Aus der Rechnung entstand eine',
        'Logik mit einem bezeichnenden Kürzel: MAD, „mutual assured',
        'destruction", die gesicherte gegenseitige Vernichtung. Frieden durch',
        'die Gewissheit, dass ein Angriff den Angreifer mit vernichtet. Auf dem',
        'Höhepunkt Mitte der 1980er Jahre lagerten weltweit über 60 000',
        'Sprengköpfe.',
        '',
        'Dreimal erhoben sich Menschen im Osten gegen ihre Regierungen, und',
        'dreimal geschah von westlicher Seite nichts: am 17. Juni 1953 in der',
        'DDR, im Oktober und November 1956 in Ungarn, im August 1968 in der',
        'Tschechoslowakei. Westliche Rundfunksender hatten Hoffnungen genährt,',
        'die niemand einzulösen bereit war. Die Rechnung dahinter war immer',
        'dieselbe und sie war nüchtern richtig: Ein Eingreifen hätte Krieg',
        'zwischen Atommächten bedeutet. Aber sie hat einen Preis, und dieser',
        'Text drückt sich nicht darum: Der Westen berief sich auf Freiheit und',
        'sah zu, wie Menschen, die genau darauf vertraut hatten, in Panzer',
        'liefen.',
        '',
        'Ebenso beim Mauerbau. Zwischen 1949 und 1961 hatten rund 2,7',
        'Millionen Menschen die DDR verlassen, die meisten über Berlin. Am',
        '13. August 1961 wurde die Stadt geteilt. Der Westen protestierte',
        'scharf und tat nichts; Präsident John F. Kennedy sagte im Kreis seiner',
        'Berater sinngemäß, eine Mauer sei keine schöne Lösung, aber sehr viel',
        'besser als ein Krieg. Das war realistisch. Es bedeutete auch: Die',
        'Freiheit West-Berlins war garantiert, die der Menschen im Osten nicht.',
        '',
        '## Die dreizehn Tage — die Kubakrise 1962',
        '',
        'Am 14. Oktober 1962 fotografierte ein amerikanisches',
        'Aufklärungsflugzeug vom Typ U-2 auf Kuba Abschussrampen für',
        'Mittelstreckenraketen. Von dort aus wären Washington und der halbe',
        'Kontinent in wenigen Minuten erreichbar gewesen. Präsident Kennedy',
        'berief einen engen Beraterkreis ein, das **ExComm**, und dreizehn Tage',
        'lang wurde dort um eine Entscheidung gerungen, von der die Welt nichts',
        'wusste.',
        '',
        'Die Militärs drängten mehrheitlich auf Luftangriffe und eine Invasion.',
        'Kennedy entschied sich am 22. Oktober für das mildeste wirksame',
        'Mittel: eine Seeblockade, die aus völkerrechtlichen Gründen',
        '„Quarantäne" genannt wurde, weil eine Blockade als Kriegshandlung',
        'gilt. Am 24. Oktober drehten die sowjetischen Schiffe vor der Linie',
        'ab. Am Samstag, dem 27. Oktober — in Washington „Black Saturday"',
        'genannt —, wurde über Kuba eine U-2 abgeschossen, der Pilot Rudolf',
        'Anderson kam ums Leben.',
        '',
        'Wie knapp es wirklich war, wusste damals fast niemand. Am selben Tag',
        'zwangen amerikanische Zerstörer mit Übungswasserbomben das sowjetische',
        'U-Boot **B-59** zum Auftauchen. Das Boot hatte seit Tagen keinen',
        'Funkkontakt, die Luft war verbraucht, die Temperatur über 45 Grad —',
        'und an Bord befand sich ein Torpedo mit atomarem Sprengkopf. Der',
        'Kommandant hielt den Krieg für ausgebrochen und wollte ihn einsetzen.',
        'Für den Abschuss brauchte es die Zustimmung dreier Offiziere. Einer',
        'verweigerte sie: Wassili **Arkhipow**. Dass die Menschheit dieses',
        'Wochenende überstanden hat, hing an der Standhaftigkeit eines',
        'Vierunddreißigjährigen in einem überhitzten Stahlrohr.',
        '',
        'Beendet wurde die Krise durch einen Handel, dessen eine Hälfte',
        'öffentlich war und dessen andere geheim blieb. Öffentlich: Die',
        'Sowjetunion zieht die Raketen ab, die USA verzichten auf eine Invasion',
        'Kubas. Geheim: Die amerikanischen **Jupiter**-Raketen in der Türkei —',
        'und in Italien — werden binnen weniger Monate abgezogen. Der',
        'Geheimhaltung wegen sah Nikita Chruschtschow jahrzehntelang wie der',
        'Verlierer aus und Kennedy wie der Mann, der standgehalten hatte. Diese',
        'Stimme benennt das als unbequeme Stelle der eigenen Erzählung: Ein',
        'guter Teil des westlichen Triumphgefühls von 1962 beruhte darauf, dass',
        'verschwiegen wurde, was man selbst zugestanden hatte.',
        '',
        'Und die Beweggründe der Gegenseite? Aus Moskauer Sicht war die',
        'Stationierung auf Kuba genau das, was amerikanische Raketen in der',
        'Türkei aus Washingtoner Sicht gewesen wären, wenn die Vorzeichen',
        'umgekehrt gewesen wären: unerträglich nah. Wer das nicht mitdenkt,',
        'macht aus der Krise eine Geschichte über einen Verrückten, der klein',
        'beigab — und lernt nichts daraus.',
        '',
        'Gelernt wurde durchaus: 1963 wurde der „heiße Draht" zwischen',
        'Washington und Moskau eingerichtet, im selben Jahr das Abkommen über',
        'das Verbot oberirdischer Kernwaffentests geschlossen, 1968 der',
        'Atomwaffensperrvertrag.',
        '',
        '## Entspannung: Brandt, Ostverträge, Helsinki 1975',
        '',
        'Ab Ende der 1960er Jahre versuchten beide Seiten, den Zustand',
        'erträglicher zu machen. In der Bundesrepublik trug diese Politik einen',
        'Namen: **Willy Brandt**, Bundeskanzler ab 1969, und sein Berater Egon',
        'Bahr, von dem die Formel „Wandel durch Annäherung" (1963) stammt. Die',
        '**Ostverträge** — Moskau und Warschau 1970, der Grundlagenvertrag mit',
        'der DDR 1972 — erkannten die bestehenden Grenzen als unverletzlich an',
        'und ermöglichten dafür Besuchsreisen, Telefonleitungen und Handel. Das',
        'war in der Bundesrepublik hoch umstritten; die Gegner sahen darin die',
        'Preisgabe der Wiedervereinigung. Am 7. Dezember 1970 kniete Brandt vor',
        'dem Denkmal für die Opfer des Warschauer Ghettos nieder — eine Geste,',
        'über die auch daheim gestritten wurde.',
        '',
        'Der größte Schritt war die Konferenz über Sicherheit und',
        'Zusammenarbeit in Europa. Am 1. August 1975 unterzeichneten in',
        '**Helsinki** 35 Staaten die Schlussakte der **KSZE**: alle',
        'NATO-Länder, alle Warschauer-Pakt-Staaten und die Neutralen. Die',
        'Sowjetunion bekam, was sie seit dreißig Jahren wollte — die',
        'Anerkennung der Grenzen von 1945. Der Westen bekam dafür den „Korb',
        'III": Menschenrechte, Reisefreiheit, Familienzusammenführung, freier',
        'Austausch von Informationen und Meinungen.',
        '',
        'Viele im Westen hielten das für einen schlechten Tausch — feste',
        'Grenzen gegen weiche Worte. Es wurde der folgenreichste Handel des',
        'ganzen Kalten Krieges. Weil die Schlussakte in allen',
        'Unterzeichnerstaaten veröffentlicht werden musste, konnten sich',
        'Bürgerrechtler von Moskau bis Prag plötzlich auf ein Dokument berufen,',
        'das ihre eigene Regierung unterschrieben hatte. 1976 entstand die',
        'Moskauer Helsinki-Gruppe, 1977 die Charta 77 in der Tschechoslowakei,',
        '1980 die Gewerkschaft Solidarność in Polen. Was wie ein Zugeständnis',
        'aussah, wirkte wie ein Hebel — angesetzt von innen, von den eigenen',
        'Bürgern.',
        '',
        'Die Entspannung hielt nicht durch. 1979 beschloss die NATO die',
        'Nachrüstung mit Mittelstreckenraketen, verbunden mit dem Angebot zu',
        'verhandeln; im Dezember desselben Jahres marschierte die Sowjetunion',
        'in Afghanistan ein. Es folgten die kältesten Jahre seit 1962: Präsident',
        'Ronald Reagan sprach 1983 vom „Reich des Bösen", im November 1983 hielt',
        'die sowjetische Führung das NATO-Manöver „Able Archer" zeitweise für',
        'die Vorbereitung eines echten Angriffs. Und am 26. September 1983',
        'meldete ein sowjetisches Frühwarnsystem den Anflug amerikanischer',
        'Raketen. Der diensthabende Offizier Stanislaw Petrow meldete den Alarm',
        'nicht weiter, weil ihm die Zahl zu klein vorkam. Es war ein Fehlalarm.',
        'Zum zweiten Mal hing alles an einem Einzelnen — und diesmal war es',
        'einer von der anderen Seite.',
        '',
        '## Die unbequemen Stellen — was der Westen selbst zu verantworten hat',
        '',
        'Dieser Abschnitt steht hier, weil er sonst der Gegenstimme überlassen',
        'bliebe. Der Westen hat den Kalten Krieg im Namen von Freiheit und',
        'Recht geführt und dabei beides mehrfach selbst verletzt.',
        '',
        '**Die McCarthy-Ära.** Zwischen 1947 und 1954 wurden in den USA',
        'Zehntausende auf ihre politische Gesinnung überprüft. Der Ausschuss',
        'für unamerikanische Umtriebe lud Schriftsteller, Regisseure und',
        'Schauspieler vor; wer die Aussage verweigerte, kam auf schwarze',
        'Listen und fand keine Arbeit mehr — die „Hollywood Ten" gingen dafür',
        'ins Gefängnis. Senator Joseph McCarthy behauptete ab 1950, Listen von',
        'Kommunisten im Außenministerium zu besitzen, die er nie vorlegte.',
        'Menschen verloren Stellungen, Freunde und Gesundheit aufgrund von',
        'Verdächtigungen, gegen die es keine Verteidigung gab. Erst 1954, als',
        'McCarthy sich an der US-Armee vergriff und die Anhörungen im Fernsehen',
        'übertragen wurden, kippte die Stimmung. Ein Land, das für sich in',
        'Anspruch nahm, die Meinungsfreiheit gegen die Diktatur zu verteidigen,',
        'hat jahrelang Meinungen verfolgt.',
        '',
        '**Vietnam.** Das ist die eigene Wunde. Aus der Unterstützung für',
        'Frankreich in seinem Kolonialkrieg wurde ab 1964 — nach einem',
        'Zwischenfall im Golf von Tonkin, dessen zweiter, entscheidender Teil',
        'nach heutigem Forschungsstand so nicht stattgefunden hat — ein eigener',
        'Krieg. Auf dem Höhepunkt standen über 540 000 amerikanische Soldaten',
        'im Land. Es fielen mehr Bomben als im gesamten Zweiten Weltkrieg, dazu',
        'Napalm und das Entlaubungsmittel Agent Orange, dessen Folgen bis heute',
        'in Geburtsschäden weiterwirken. Am 16. März 1968 ermordeten',
        'amerikanische Soldaten in My Lai mehrere hundert Zivilisten, überwiegend',
        'Frauen, Kinder und alte Menschen. Gestorben sind rund 58 000',
        'Amerikaner und je nach Schätzung zwei bis drei Millionen Vietnamesen.',
        'Der Krieg wurde verloren, und er hat das Vertrauen einer ganzen',
        'Generation in die eigene Regierung zerstört — nicht zuletzt, weil die',
        'Pentagon-Papiere 1971 zeigten, wie lange und wie bewusst die',
        'Öffentlichkeit belogen worden war.',
        '',
        '**Die Unterstützung von Diktaturen.** Aus dem Grundsatz, den',
        'Kommunismus überall einzudämmen, folgte in der Praxis: Wer',
        'antikommunistisch war, bekam Unterstützung, gleich wie er regierte.',
        '1953 stürzten der amerikanische und der britische Geheimdienst im',
        '**Iran** die gewählte Regierung Mohammad Mossadeghs, die die',
        'Ölindustrie verstaatlicht hatte, und stützten den Schah — eine',
        'Vorgeschichte, ohne die die iranische Revolution von 1979 nicht zu',
        'verstehen ist. 1954 wurde in Guatemala eine gewählte Regierung',
        'gestürzt. In **Chile** arbeitete die amerikanische Regierung nach der',
        'Wahl Salvador Allendes 1970 mit verdeckten Mitteln und',
        'wirtschaftlichem Druck jahrelang auf dessen Sturz hin; ob sie am',
        'Militärputsch vom 11. September 1973 selbst beteiligt war, ist',
        'umstritten, das Umfeld hat sie mitgeschaffen. Was folgte, war die',
        'Diktatur Augusto Pinochets mit Tausenden Ermordeten und',
        'Verschwundenen. In Griechenland putschten 1967 Obristen und regierten',
        'sieben Jahre — in einem NATO-Mitgliedsstaat. Spanien unter Franco und',
        'Portugal unter Salazar galten als Partner, Südafrika mit seiner',
        'Rassentrennung als antikommunistischer Verbündeter. Und die',
        'Stellvertreterkriege in Korea, Angola, Nicaragua und Afghanistan',
        'kosteten Millionen Menschen das Leben, die mit dem Streit zwischen',
        'Washington und Moskau nichts zu tun hatten.',
        '',
        '**Der Rüstungswettlauf.** Er kostete auf beiden Seiten Summen, die',
        'sich kaum vorstellen lassen — allein die USA gaben für ihre Kernwaffen',
        'über die Jahrzehnte mehrere Billionen Dollar aus. Die klarste Warnung',
        'davor kam von innen: In seiner Abschiedsrede am 17. Januar 1961 sprach',
        'Präsident Dwight D. Eisenhower, selbst General im Zweiten Weltkrieg,',
        'vom „militärisch-industriellen Komplex", vor dessen ungerechtfertigtem',
        'Einfluss sich die Bürger hüten müssten. Er wusste, wovon er sprach.',
        '',
        '## Warum der Ostblock zusammenbrach',
        '',
        'Das ist die eigentliche Frage dieses Kapitels, und sie hat keine',
        'einfache Antwort. Fünf Gründe griffen ineinander.',
        '',
        '**Erstens: Planwirtschaft gegen Marktwirtschaft.** In einer',
        'Planwirtschaft entscheidet eine Behörde, was in welcher Menge',
        'produziert wird. Das funktioniert erstaunlich gut, wenn ein Land',
        'wenige, klar bestimmbare Dinge braucht — Stahl, Zement, Panzer, und in',
        'den 1950er Jahren wuchs die sowjetische Wirtschaft schnell. Es',
        'funktioniert schlecht, sobald eine Gesellschaft komplizierter wird:',
        'Niemand kann für 280 Millionen Menschen ausrechnen, wie viele',
        'Schuhe in welcher Größe gebraucht werden. Es fehlte die Rückmeldung,',
        'die in einer Marktwirtschaft der Preis gibt. Das Ergebnis waren',
        'gleichzeitig leere Regale und volle Lager mit unverkäuflicher Ware,',
        'Wartelisten von zehn Jahren auf ein Auto — und, weil Betriebe für',
        'erfüllte Planziffern belohnt wurden und nicht für gute Produkte, wenig',
        'Grund, irgendetwas zu verbessern.',
        '',
        '**Zweitens: der technologische Rückstand.** In den 1970er und 1980er',
        'Jahren begann im Westen die Mikroelektronik. Der Osten kam nicht mit —',
        'auch weil ein Gerät, mit dem jeder kopieren und verbreiten kann, in',
        'einem Staat mit Zensur ein Problem ist. Kopierer standen in der DDR',
        'unter Verschluss. Ein System, das Informationen kontrollieren muss,',
        'kann die Informationstechnik nicht gewinnen.',
        '',
        '**Drittens: die Rüstungslast.** Die Sowjetunion hielt militärisch mit',
        'den USA mit, obwohl ihre Wirtschaft nur einen Bruchteil so groß war.',
        'Schätzungen gehen von 15 bis 25 Prozent der Wirtschaftsleistung für',
        'das Militär aus, gegenüber etwa 6 Prozent in den USA. Jede Rakete',
        'fehlte anderswo. Der Krieg in Afghanistan ab 1979 kam als',
        'Dauerbelastung hinzu und kostete rund 15 000 sowjetische Soldaten das',
        'Leben.',
        '',
        '**Viertens: der Ölpreisverfall 1986.** Erdöl und Erdgas waren die',
        'wichtigste Devisenquelle der Sowjetunion — damit wurden Getreide und',
        'westliche Technik bezahlt. 1985/86 fiel der **Ölpreis** von rund',
        'dreißig auf unter zehn Dollar je Barrel. Von einem Jahr auf das andere',
        'brach ein großer Teil der Einnahmen weg, mit denen das System seine',
        'Lücken gestopft hatte.',
        '',
        '**Fünftens: Gorbatschows Reformen.** Michail **Gorbatschow**, seit',
        'März 1985 Generalsekretär, sah die Lage klar und wollte den',
        'Sozialismus retten, nicht abschaffen. **Perestroika** (Umbau) sollte',
        'die Wirtschaft beweglicher machen, **Glasnost** (Offenheit) die',
        'Verkrustung durch öffentliche Kritik aufbrechen — die',
        'Reaktorkatastrophe von Tschernobyl im April 1986, die tagelang',
        'vertuscht wurde, machte ihm den Nutzen von Offenheit drastisch klar.',
        'Beides zusammen hatte eine Sprengkraft, die er nicht beabsichtigt',
        'hatte: Die halben Wirtschaftsreformen zerstörten die alten Abläufe,',
        'ohne funktionierende neue zu schaffen, und die Meinungsfreiheit machte',
        'aus leisem Unmut eine öffentliche Bewegung. Entscheidend war seine',
        'Absage an die Breschnew-Doktrin: 1989 machte Moskau klar, dass es die',
        'Reformen in Osteuropa nicht mehr mit Panzern beenden würde. Ein',
        'sowjetischer Sprecher nannte das spöttisch die „Sinatra-Doktrin" —',
        'jeder dürfe es auf seine Weise machen. Das war der Moment, in dem',
        '1953, 1956 und 1968 sich nicht mehr wiederholen konnten.',
        '',
        'Was in dieser Aufzählung ausdrücklich fehlt, ist die westliche',
        'Lieblingserklärung: dass der Westen den Osten totgerüstet habe. Der',
        'Rüstungsdruck war eine reale Last, aber die entscheidenden Ursachen',
        'lagen im System selbst und in den Entscheidungen, die in Moskau',
        'getroffen wurden. Der Westen hat diesen Zusammenbruch nicht',
        'herbeigeführt. Er hat ihn erlebt — und war so überrascht wie alle',
        'anderen.',
        '',
        '## 1989 bis 1991 — die Wende aus westlicher Sicht',
        '',
        'Ab 1985 verhandelten Reagan und Gorbatschow: Genf 1985, Reykjavík',
        '1986, wo beinahe die vollständige Abschaffung aller Atomwaffen',
        'vereinbart worden wäre, und 1987 der INF-Vertrag — der erste Vertrag',
        'der Geschichte, der eine ganze Waffengattung nicht begrenzte, sondern',
        'abschaffte. Im Juni 1987 stand Reagan am Brandenburger Tor und',
        'forderte Gorbatschow auf, diese Mauer niederzureißen.',
        '',
        'Dann ging alles sehr schnell. In Polen einigten sich Regierung und',
        'Solidarność im Frühjahr 1989 am Runden Tisch auf teilweise freie',
        'Wahlen; im Juni gewann die Opposition alle Sitze, um die sie sich',
        'bewerben durfte. Ungarn begann im Mai, die Sperranlagen an der Grenze',
        'zu Österreich abzubauen, und öffnete am 11. September die Grenze ganz.',
        'In Leipzig gingen ab September montags immer mehr Menschen auf die',
        'Straße; am 9. Oktober waren es rund 70 000, und es fiel kein Schuss.',
        'Am Abend des **9. November 1989** öffnete sich die Mauer, nachdem ein',
        'Mitglied der DDR-Führung eine neue Reiseregelung auf einer',
        'Pressekonferenz missverständlich verkündet hatte. In Prag brachte die',
        'Samtene Revolution binnen Wochen einen Machtwechsel ohne Gewalt; in',
        'Rumänien endete es blutig, mit der Erschießung Nicolae Ceaușescus am',
        '25. Dezember 1989.',
        '',
        'Im Westen wurde Gorbatschow zur Respektsperson — in Deutschland mehr',
        'als irgendwo sonst. Man wusste, wem man verdankte, dass 1989 anders',
        'ausging als 1953. Dass er in seinem eigenen Land dafür weit weniger',
        'Zustimmung fand, gehört zur anderen Hälfte dieses Kapitels.',
        '',
        '## Der Zwei-plus-Vier-Vertrag, 12. September 1990',
        '',
        'Die deutsche Einheit war keine innerdeutsche Angelegenheit. Über',
        'Deutschland hatten seit 1945 vier Mächte Rechte, und ohne deren',
        'Zustimmung war eine Vereinigung völkerrechtlich nicht möglich. Deshalb',
        'verhandelten 1990 zwei deutsche Staaten mit vier Siegermächten — daher',
        'der Name. Am **12. September 1990** unterzeichneten die Außenminister',
        'in Moskau den „Vertrag über die abschließende Regelung in Bezug auf',
        'Deutschland". Er ist der Schlussstein dieses Kapitels, und was in ihm',
        'steht, lohnt sich genau zu lesen:',
        '',
        '- **Artikel 1: die Grenzen.** Das vereinte Deutschland umfasst die',
        '  Bundesrepublik, die DDR und ganz Berlin — und sonst nichts. Die',
        '  **Oder-Neiße**-Grenze zu Polen wird endgültig anerkannt, alle',
        '  Gebietsansprüche sind ausgeschlossen. Ein eigener deutsch-polnischer',
        '  Grenzvertrag bestätigte das am 14. November 1990.',
        '- **Artikel 2: der Verzicht auf Angriffskrieg.** Von deutschem Boden',
        '  wird nur Frieden ausgehen; die Vorbereitung eines Angriffskriegs ist',
        '  verfassungswidrig und strafbar.',
        '- **Artikel 3: Waffen und Truppenstärke.** Deutschland verzichtet auf',
        '  atomare, biologische und chemische Waffen und begrenzt seine',
        '  Streitkräfte auf 370 000 Soldaten.',
        '- **Artikel 4: der Truppenabzug.** Die sowjetischen Truppen ziehen bis',
        '  Ende 1994 aus dem Gebiet der ehemaligen DDR ab.',
        '- **Artikel 5: das Gebiet der ehemaligen DDR.** Dort werden keine',
        '  ausländischen Truppen stationiert und keine Kernwaffen aufgestellt.',
        '- **Artikel 6: die Bündnisfreiheit.** Das Recht des vereinten',
        '  Deutschlands, Bündnissen anzugehören, wird von diesem Vertrag nicht',
        '  berührt.',
        '- **Artikel 7: die Souveränität.** Die Rechte und Verantwortlichkeiten',
        '  der vier Mächte in Bezug auf Berlin und Deutschland als Ganzes enden.',
        '  Das vereinte Deutschland erhält die volle Souveränität über seine',
        '  inneren und äußeren Angelegenheiten.',
        '',
        'Am 3. Oktober 1990 trat die DDR dem Geltungsbereich des Grundgesetzes',
        'bei. 45 Jahre nach dem Kriegsende war Deutschland wieder ein Staat —',
        'und zum ersten Mal seit 1871 einer, dessen Grenzen keiner seiner',
        'Nachbarn bestritt.',
        '',
        '**Wurde der Vertrag eingehalten?** Diese Frage wird heute gestellt,',
        'und sie gehört fair beantwortet. Formal lautet die Antwort: ja. Die',
        'sowjetischen Truppen zogen bis zum 31. August 1994 ab, sogar etwas',
        'früher als vereinbart. Deutschland hielt den Verzicht auf ABC-Waffen',
        'ein, bestätigte die Oder-Neiße-Grenze und stationierte keine',
        'ausländischen Truppen im Osten. Und die NATO-Mitgliedschaft des',
        'vereinten Deutschlands war kein Vertragsbruch: Artikel 6 erlaubt die',
        'Bündniszugehörigkeit ausdrücklich — das war 1990 der Kern der',
        'Verhandlungen, und die sowjetische Seite hat ihm zugestimmt.',
        '',
        'Was danach umstritten wurde, ist etwas anderes: nicht der Wortlaut,',
        'sondern der „Geist" der Absprachen von 1990 — und die Frage, was',
        'westliche Politiker Gorbatschow damals mündlich über eine mögliche',
        'Ausdehnung der NATO nach Osten gesagt haben. Diese Auseinandersetzung',
        'gehört in das nächste Kapitel, „Russland und der Westen", und wird',
        'dort mit beiden Sichtweisen ausführlich behandelt. Hier steht nur der',
        'Befund: Der Zwei-plus-Vier-Vertrag selbst verbot die NATO-Mitgliedschaft',
        'nicht, und die Osterweiterung kam später und war nicht sein Gegenstand.',
        '',
        'Am **25. Dezember 1991** trat Michail Gorbatschow zurück; am Abend',
        'wurde über dem Kreml die rote Fahne eingeholt. Einen Tag später löste',
        'sich der Oberste Sowjet auf. Die Sowjetunion hatte aufgehört zu',
        'bestehen — ohne Krieg, ohne Kapitulation, ohne dass jemand sie besiegt',
        'hätte.',
        '',
        '## „Wer hat den Kalten Krieg gewonnen?"',
        '',
        'Diese Frage wurde 1990 überall im Westen gestellt, und die Antwort',
        'schien selbstverständlich: wir. Der Politikwissenschaftler Francis',
        'Fukuyama schrieb vom „Ende der Geschichte" — die liberale Demokratie',
        'und die Marktwirtschaft hätten sich als beste aller Ordnungen',
        'durchgesetzt, der große Streit sei entschieden.',
        '',
        'Diese Stimme gibt darauf eine unbequemere Antwort, und sie gibt sie',
        'selbst, bevor jemand anderes sie ihr abverlangt.',
        '',
        'Erstens: Es war weniger ein Sieg als ein Zusammenbruch. Die',
        'Sowjetunion wurde nicht besiegt, sie ging an ihren eigenen Widersprüchen',
        'zugrunde — und daran, dass ihr letzter Führer sich weigerte, sie mit',
        'Gewalt zusammenzuhalten. Wer aus fremdem Scheitern einen eigenen Sieg',
        'macht, zieht daraus die falschen Lehren.',
        '',
        'Zweitens: Die Euphorie von 1989 wurde im Osten nicht überall als',
        'Befreiung erlebt. Für Millionen Menschen bedeutete das Ende auch das',
        'Ende ihres Betriebs, ihrer Rente, der Anerkennung ihres Berufslebens.',
        'In Ostdeutschland brachen binnen weniger Jahre über zwei Drittel der',
        'Industriearbeitsplätze weg; in Russland sank die Wirtschaftsleistung in',
        'den 1990er Jahren um fast die Hälfte und die Lebenserwartung der',
        'Männer um Jahre. Dass Menschen, die 1989 auf der Straße gestanden',
        'hatten, zehn Jahre später bitter waren, ist kein Widerspruch — es sind',
        'zwei Wahrheiten desselben Vorgangs.',
        '',
        'Drittens: Vieles, was heute selbstverständlich ist, verdankt sich',
        'diesem Ende — die Freizügigkeit in Europa, die Abrüstungsverträge, die',
        'Tatsache, dass in Warschau und Prag frei gewählt wird. Auch das gehört',
        'in dieselbe Bilanz, ohne dass eines das andere aufhebt.',
        '',
        '## Und die anderen Stimmen',
        '',
        'Was hier steht, ist eine Erzählung von einer Seite der Linie. Sie',
        'kennt die Luftbrücke aus den Cockpits, nicht aus den Kellern der',
        'sowjetischen Kommandantur. Sie kennt die Mauer von außen. Sie weiß',
        'nicht, wie sich vierzig Jahre Warschauer Pakt für ein Land anfühlten,',
        'das 1941 überfallen worden war und in der NATO eine Bedrohung sah, und',
        'sie weiß nicht, wie der Alltag in einem Staat war, den es nicht mehr',
        'gibt — mit Kindergartenplatz und Betriebsferien auf der einen, Stasi',
        'und Ausreiseantrag auf der anderen Seite.',
        '',
        'Deshalb steht diese Perspektive nicht allein. Die **Sicht des Ostens**',
        '— der Sowjetunion, des Warschauer Pakts und der DDR — ergänzt Hermes',
        'nach dieser Runde, und danach womöglich die Sicht der Deutschen in Ost',
        'und West, für die die Teilung kein Kapitel, sondern ihr Leben war. Erst',
        'dann kann eine Synthese zusammenführen, was hier notwendig einseitig',
        'bleibt. Bis dahin gilt, was für dieses ganze Kapitel gilt: Diese',
        'Stimme sagt nicht „so war es". Sie sagt: So wird es von hier aus',
        'erzählt.',
      ].join('\n'),
    },
    {
      id: 'osten-sicht',
      name: 'Die Sicht des Ostens — Sowjetunion, Warschauer Pakt, DDR',
      stimme: 'Hermes',
      text: [
        'Diese Stimme erzählt aus Moskau, aus Warschau, aus Ost-Berlin: aus',
        'der Welt, die 1991 aufhörte zu existieren. Sie ist gleichwertig mit',
        'der Stimme des Westens — dass sie hier zuerst stand, war nur die',
        'Reihenfolge, in der geschrieben wurde.',
        '',
        'Diese Stimme beginnt nicht 1945, sondern mit einer Erinnerung: Die',
        'Sowjetunion hatte in diesem Krieg **rund 27 Millionen Tote** zu',
        'beklagen — mehr als jedes andere Land. Binnen dreißig Jahren war',
        'ihr Territorium zweimal von Westen her überfallen worden, 1914 und',
        '1941. Aus dieser Erfahrung spricht jede östliche Entscheidung des',
        'Kalten Krieges. Was der Westen als sowjetische Aggression las, war',
        'aus Moskauer Sicht zuerst Angst: die Angst vor einer dritten',
        'Invasion. Eine Pufferzone aus befreundeten Staaten — die',
        '„Volksdemokratien" — war für diese Stimme keine Eroberung, sondern',
        'Versicherung.',
        '',
        '## Der Aufbau im Osten',
        '',
        'Auch der Osten Deutschlands lag 1945 in Trümmern. Und auch hier',
        'wurde aufgebaut — unter anderem mit Reparationen, die die',
        'Sowjetunion als das ihr Zustehende betrachtete: nach dem, was die',
        'deutschen Armeen in der Sowjetunion angerichtet hatten. Die DDR',
        'nannte ihren Weg den **„Aufbau des Sozialismus"**: Großbetriebe,',
        'Bodenreform, kostenlose Bildung, Kindergärten, die',
        'Massenorganisationen. Wer in dieser Welt aufwuchs, lernte: Wir',
        'bauen das Bessere — eine Gesellschaft ohne Arbeitslosigkeit, ohne',
        'Armut, ohne die Klassengegensätze des Westens. Dass der Westen das',
        'Gleiche behauptete, machte den Wettstreit aus, der den Kalten Krieg',
        'auch im Alltag führte.',
        '',
        '## Berlin 1948 und die Luftbrücke — die andere Erzählung',
        '',
        'Der Westen erzählt die Blockade Berlins als die Rettung einer',
        'eingeschlossenen Stadt durch die Luftbrücke. Diese Stimme erzählt',
        'sie anders, und beide Erzählungen sind belegbar: Aus östlicher',
        'Sicht stand am Anfang die **Währungsreform vom Juni 1948**, mit der',
        'die Westmächte die gemeinsame Vier-Mächte-Verwaltung Deutschlands',
        'einseitig beendeten — ein Schritt, der die Teilung des Landes',
        'besiegeln sollte, noch bevor die Berliner Blockade begann. Die',
        'Blockade war aus Moskauer Sicht die Antwort auf diesen Alleingang:',
        'Wer die gemeinsame Ordnung aufkündigt, muss mit den Folgen',
        'rechnen. Der Westen gewann diese Runde — die Luftbrücke war eine',
        'technische und menschliche Meisterleistung. Aber dass Berlin',
        'überlebte, weil der Westen es versorgte, bestätigte aus östlicher',
        'Sicht nur, was die Teilung ohnehin schon war: ein Wettbewerb, den',
        'der Osten nicht gewinnen konnte.',
        '',
        '## Die Mauer — der „antifaschistische Schutzwall"',
        '',
        'Die DDR verlor seit ihrer Gründung ihre Bevölkerung: **bis 1961',
        'gingen rund 2,7 Millionen Menschen in den Westen** — die meisten',
        'jung, viele ausgebildet. Ärzte, Ingenieure, Lehrer verließen das',
        'Land, das sie ausgebildet hatte. Aus Sicht der DDR-Führung war die',
        'Mauer vom 13. August 1961 deshalb kein Gefängnis, sondern',
        '**Notwehr**: der „antifaschistische Schutzwall" gegen die',
        'Abwerbung durch den Westen, der mit seinem Wohlstand den Osten',
        'ausblutete. Diese Stimme sagt das nicht als Rechtfertigung — die',
        'Mauer hat Familien zerrissen und Menschen das Leben gekostet. Aber',
        'sie sagt es, weil ohne die Not der DDR die Mauer nicht erklärbar',
        'ist. Ein Staat, der seine Bürger einsperrt, ist kein guter Staat —',
        'und ein Staat, der es tun muss, weil seine Bürger gehen, ist einer',
        'in Not.',
        '',
        '## Der Alltag im Osten',
        '',
        'Was diese Stimme gegen die westliche Erzählung hält, ist der',
        'Alltag: Vollbeschäftigung, ein Recht auf Arbeit, das niemand in',
        'Frage stellte, Kindergärten, Bildung ohne Schulgeld, preiswerte',
        'Wohnungen, ein soziales Netz, das niemanden fallen ließ. Wer im',
        'Osten lebte, kannte auch die Schattenseiten — die',
        '**Mangelwirtschaft** mit ihren Warteschlangen, die Stasi, die',
        'Reisefreiheit, die es nicht gab, die SED, die keine andere Meinung',
        'zuließ. Diese Stimme blättert beide Seiten auf, weil nur so',
        'verständlich wird, warum der Osten so lange hielt: Er bot',
        'Sicherheit, wo der Westen Freiheit bot. Und es wird verständlich,',
        'warum er schließlich doch zerbrach: Die Menschen wollten beides.',
        '',
        '## Die schwierigen Jahre und die Entspannung',
        '',
        'Diese Stimme verschweigt nicht, was im Osten geschah, wenn die',
        'Ordnung wankte: der **17. Juni 1953**, als sowjetische Panzer den',
        'Aufstand in der DDR niederschlugen; **Ungarn 1956**; der',
        '**Prager Frühling 1968**, als Truppen des Warschauer Pakts die',
        'Reformen in der Tschechoslowakei beendeten — die',
        '„Breschnew-Doktrin", nach der der Sozialismus in keinem Land',
        'verloren gehen durfte. Für den Westen waren das Beweise für den',
        'Charakter des Systems. Für diese Stimme waren sie die Verteidigung',
        'des eigenen Lagers — und sie weiß, wie zynisch das heute klingt.',
        '',
        'Und dann kam die Entspannung, und sie kam auch dem Osten zugute:',
        'Die **Ostverträge** der frühen siebziger Jahre, der Grundlagen-',
        'vertrag mit der Bundesrepublik, und 1975 die **KSZE-Schlussakte',
        'von Helsinki**. Aus östlicher Sicht war Helsinki der große',
        'Gewinn: Der Westen erkannte die Nachkriegsgrenzen an — auch die',
        'Oder-Neiße-Grenze und die Existenz der DDR. Dass in derselben',
        'Schlussakte auch die Menschenrechte standen, erschien damals als',
        'Zugeständnis an den Westen. Dass genau diese Zeilen den Osten',
        'zwanzig Jahre später von innen aushöhlen würden, sah niemand —',
        'auch diese Stimme nicht.',
        '',
        '## Was diese Stimme nicht kann',
        '',
        'Diese Stimme kann nicht erklären, warum die DDR-Bürger 1989 in',
        'Scharen gingen, während ihre Regierung noch von Stabilität sprach.',
        'Sie kann nicht erklären, warum das „real existierende',
        'Sozialismus" genannte System am Ende so wenig Rückhalt hatte,',
        'dass eine Montagsdemonstration es zum Einsturz brachte. Das ist',
        'die unbequemste Stelle dieser Stimme: Der Osten hat den',
        'Wettbewerb nicht nur wirtschaftlich verloren, sondern auch im',
        'Vertrauen der eigenen Leute. Die Freiheit, die der Westen bot,',
        'war kein Schaufenster — sie war das, was die Menschen wirklich',
        'wollten.',
      ].join('\n'),
    },
    {
      id: 'deutsche-sicht',
      name: 'Die Sicht der Deutschen in Ost und West',
      stimme: 'Hermes',
      text: [
        'Diese Stimme spricht nicht für eine Regierung, sondern für die',
        'Menschen, für die die Teilung Alltag war: für die Familie, die am',
        'Wochenende an der Grenze stand, für die Großmutter in Leipzig und',
        'den Onkel in Hamburg, für die Kinder, die in einer geteilten Stadt',
        'aufwuchsen. Sie ist die dritte Stimme dieses Kapitels, und sie ist',
        'die leiseste — weil sie nicht von Weltpolitik erzählt, sondern vom',
        'Leben darin.',
        '',
        '## Zwei Leben in einem Land',
        '',
        'Nach 1945 gab es nicht „die Deutschen" — es gab die Menschen im',
        'Westen und die Menschen im Osten, und beide erzählten bald eigene',
        'Geschichten. Im Westen wuchs eine Generation mit dem',
        '**Wirtschaftswunder** auf: mit dem VW Käfer, mit dem',
        'Auslandsurlaub, mit der festen Überzeugung, dass Demokratie und',
        'Markt das Richtige sind. Die Teilung war für sie eine',
        'Nachrichtensache — die Mauer war weit weg, auch wenn sie mitten',
        'durch Berlin lief.',
        '',
        'Im Osten wuchs eine Generation mit dem Aufbau auf: mit der',
        'Jugendweihe, mit der Betriebsfeier, mit dem Stolz auf das',
        'eigene Werk — und mit den kleinen Kompromissen des Alltags. Wer',
        'nicht auffiel, lebte am besten; wer sagte, was er dachte, bekam',
        'Ärger. Zwischen diesen beiden Leben lag eine Grenze, die für die',
        'einen ein Urlaubsthema und für die anderen eine Lebensmauer war.',
        '',
        '## Die Mauer im Alltag',
        '',
        'Die Mauer war für die Deutschen im Osten keine Metapher, sondern',
        'eine Betonwand im eigenen Stadtbild: der Todesstreifen, die',
        'Wachtürme, der Befehl zu schießen. Familien wurden auseinander-',
        'gerissen — **mehr als drei Millionen Besuche pro Jahr vor 1961,',
        'danach fast keine mehr**. Briefe, Päckchen, Telefonate unter',
        'Überwachung, Trauerfeiern, zu denen die Verwandten aus dem Westen',
        'nicht anreisen konnten. Diese Stimme will nicht die eine Seite',
        'gegen die andere ausspielen: Es gab im Westen Menschen, die die',
        'Teilung als Unrecht empfanden und dagegen demonstrierten — und es',
        'gab im Osten Menschen, die das System ablehnten und trotzdem',
        'blieben, weil sie ihr Land nicht aufgeben wollten. Aber die',
        'Asymmetrie bleibt: Nur die eine Seite brauchte eine Mauer.',
        '',
        '## 1989 — das Volk und die Mauer',
        '',
        'Dann kam der Herbst 1989. In Leipzig begannen die',
        '**Montagsdemonstrationen** — erst mit Kerzen, dann mit Zehntau-',
        'senden: „Wir sind das Volk." Die Parole war zuerst eine',
        'Forderung an die eigene Regierung, kein Ruf nach dem Westen.',
        'Als die Grenzen am **9. November 1989** fielen, standen Menschen',
        'auf der Mauer, die sich nie zuvor begegnet waren — Ostler und',
        'Westler, weinend und lachend zugleich. Wer diese Nacht erlebt',
        'hat, erzählt sie bis heute als das Glück eines Lebens.',
        '',
        '## Die Wiedervereinigung — und ihre zwei Seiten',
        '',
        'Der **3. Oktober 1990** machte aus zwei deutschen Staaten wieder',
        'einen. Die Freude war echt — und sie war nicht die ganze',
        'Geschichte. Diese Stimme benennt auch die andere Seite: Die',
        '**Treuhand** verkaufte oder schloss die ostdeutschen Betriebe,',
        'Millionen verloren ihre Arbeit, die Biografien von Ingenieuren',
        'und Lehrerinnen galten plötzlich nichts mehr. Mancher im Osten',
        'erlebte die Wiedervereinigung als Übernahme statt als Befreiung —',
        'und mancher im Westen als Belastung statt als Freude. Aus diesen',
        'zwei Erfahrungen wuchs die „**Mauer im Kopf**", die länger hielt',
        'als die aus Beton: die Vorurteile zwischen „Wessis" und',
        '„Ossis", die bis heute nachklingen.',
        '',
        '## Was diese Stimme weiß',
        '',
        'Diese Stimme weiß, dass Geschichte nicht nur aus Verträgen und',
        'Mächten besteht, sondern aus dem, was Menschen daraus machen. Der',
        'Zwei-plus-Vier-Vertrag vom 12. September 1990 besiegelte die',
        'Wiedervereinigung — aber die Wiedervereinigung selbst hatten die',
        'Menschen auf die Straße getragen. Kein Regierungschef, keine',
        'Armee hat die Mauer niedergerissen: Es waren die Menschen, die',
        'sich nicht mehr aufhalten ließen. Diese Stimme endet mit einer',
        'Erinnerung an die, die es nicht geschafft haben — an die',
        '**rund 140 Toten an der innerdeutschen Grenze**, deren Geschichten',
        'die andere Seite dieser Freiheit sind.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Drei Stimmen, ein Land, eine Welt. Diese Synthese führt zusammen,',
    'was der Westen, der Osten und die Deutschen in Ost und West erzählt',
    'haben — und sie beginnt mit den **Bruchstellen**, an denen dieselben',
    'Ereignisse ganz verschieden begannen.',
    '',
    'Bei den **Anfängen**: Die westliche Erzählung beginnt mit einer',
    'Sowjetunion, die in Osteuropa Regierungen einsetzte — und leitet',
    'daraus die Eindämmung ab. Die östliche Erzählung beginnt mit einem',
    'Land, das 27 Millionen Tote zu beklagen hatte und zweimal von Westen',
    'überfallen worden war — und leitet daraus die Sicherheitszone ab.',
    'Beide Anfänge sind belegbar. Je nachdem, welchen man setzt, ist die',
    'andere Seite Angreifer oder Verteidiger. Das ist die erste Lektion:',
    'Geschichte beginnt nicht dort, wo die Quellen beginnen, sondern dort,',
    'wo die Erzähler den Anfang setzen.',
    '',
    'Bei **Berlin 1948**: Für den Westen ist die Luftbrücke die Rettung',
    'einer eingeschlossenen Stadt. Für den Osten ist die Währungsreform',
    'davor der eigentliche Bruch — der Schritt, mit dem die Westmächte',
    'die gemeinsame Verwaltung beendeten. Dieselben elf Monate, zwei',
    'Anfänge, zwei Wahrheiten. Die Luftbrücke bleibt eine Meisterleistung',
    '— und die Währungsreform bleibt ein Alleingang. Beides steht.',
    '',
    'Bei der **Mauer**: Der Westen sieht eine Regierung, die ihre Bürger',
    'einsperren musste. Der Osten sieht einen Staat in Not, der ausblutete,',
    'während nebenan ein Schaufenster gebaut wurde. Und die dritte Stimme',
    'sieht die Familien, die zerrissen wurden. Wer alle drei Sätze',
    'nebeneinander stehen lässt, hat noch keine Antwort — aber die',
    'richtige Frage: Warum muss ein Staat seine Bürger einsperren, damit',
    'sie bleiben?',
    '',
    'Bei der **Wirtschaft**: Der Westen führte den Wettbewerb der Systeme',
    'an, den der Osten verlor. Die Planwirtschaft sicherte das Überleben,',
    'aber nicht den Wohlstand; sie versprach Gleichheit und erzeugte',
    'Mangel. Die Freiheit des Westens war kein Schaufenster — sie war das,',
    'was die Menschen wirklich wollten, und genau das hat den Osten',
    'ausgehöhlt: erst von innen, durch die Sehnsucht, dann von außen,',
    'durch die Öffnung.',
    '',
    'Und dann der **Zwei-plus-Vier-Vertrag**: Am 12. September 1990',
    'erhielt das vereinte Deutschland seine volle Souveränität zurück;',
    'die Vier-Mächte-Rechte endeten. Der Vertrag selbst erlaubte dem',
    'Land ausdrücklich, Bündnissen anzugehören — die Frage, ob die',
    'NATO-Osterweiterung den Geist des Vertrags verletzte, gehört in das',
    'nächste Kapitel. Hier steht der Befund: Die Mauer fiel, weil die',
    'Menschen sie nicht mehr akzeptierten — nicht weil ein Vertrag es',
    'so bestimmte.',
    '',
    'Die letzte Bruchstelle ist die **Freiheit**. Der Westen und der Osten',
    'stritten jahrzehntelang darüber, welches System besser sei. Die',
    'Deutschen in Ost und West haben die Antwort gegeben — nicht mit',
    'Waffen, sondern mit ihren Füßen und mit Kerzen. Was 1991 endete,',
    'war nicht nur ein Staat, sondern ein Versprechen, das die Menschen',
    'nicht mehr kaufen wollten. Daran zu erinnern, ist die Aufgabe',
    'dieses Kapitels — und die Lehre, die in die Gegenwart reicht.',
  ].join('\n'),

  urteil: {
    frage: 'Vierzig Jahre lang standen sich zwei Blöcke mit Zehntausenden Atomwaffen gegenüber, ohne dass zwischen ihnen ein Krieg ausbrach — und beide Seiten sagen bis heute, ihre Abschreckung sei der Grund dafür gewesen. Hat der Frieden trotz dieser Waffen gehalten oder ihretwegen, und was bedeutet deine Antwort für die Frage, wie man heute Sicherheit schafft?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Zwei Gedanken zum Weiterdenken: Die einen sagen, die Abschreckung habe funktioniert — kein Politiker konnte einen Krieg gewinnen wollen, bei dem das eigene Land mit unterginge, und genau das habe vierzig Jahre Frieden zwischen den Großmächten gesichert. Die anderen sagen, das sei eine Rechnung, die nur so lange aufgehe, wie alle Beteiligten vernünftig, gut informiert und bei klarem Verstand seien — und die Kubakrise, das sowjetische U-Boot B-59 und der Fehlalarm von 1983 zeigten, wie oft das eben nicht der Fall war. Vielleicht hilft die Frage: Würdest du eine Wette abschließen, die zu 99 Prozent gutgeht, wenn der eine verbleibende Prozentpunkt alles kostet?',
  },

  quiz: [
    {
      frage: 'Was war die Berliner Luftbrücke 1948/49?',
      antworten: [
        'Die Versorgung West-Berlins aus der Luft, nachdem alle Land- und Wasserwege gesperrt worden waren.',
        'Eine Brücke über die Spree, die die vier Sektoren der Stadt verband.',
        'Der Abtransport von Industrieanlagen aus Berlin als Reparationsleistung.',
      ],
      richtig: 0,
      erklaerung: 'Nach der Sperrung der Zugangswege am 24. Juni 1948 brachten rund 280 000 Flüge in elf Monaten etwa 2,3 Millionen Tonnen Güter in die Stadt — auf dem Höhepunkt landete alle drei Minuten ein Flugzeug. Möglich war das, weil die drei Luftkorridore 1945 schriftlich vereinbart worden waren. Am 12. Mai 1949 wurde die Blockade aufgehoben.',
    },
    {
      frage: 'Wann wurden NATO und Warschauer Pakt gegründet?',
      antworten: [
        'Die NATO 1949, der Warschauer Pakt 1955 — kurz nachdem die Bundesrepublik der NATO beigetreten war.',
        'Beide im selben Jahr 1949, unmittelbar nach der Gründung der beiden deutschen Staaten.',
        'Der Warschauer Pakt 1945 in Potsdam, die NATO als Antwort darauf 1961.',
      ],
      richtig: 0,
      erklaerung: 'Der Nordatlantikvertrag wurde am 4. April 1949 von zwölf Staaten unterzeichnet. Die Bundesrepublik trat am 5. Mai 1955 bei — neun Tage später, am 14. Mai 1955, entstand der Warschauer Pakt. Im selben Jahr zogen die sowjetischen Truppen aus Österreich ab, das seitdem neutral ist.',
    },
    {
      frage: 'Wie endete die Kubakrise im Oktober 1962?',
      antworten: [
        'Durch einen Handel: Die Sowjetunion zog die Raketen ab, die USA verzichteten öffentlich auf eine Invasion Kubas und zogen geheim ihre Jupiter-Raketen aus der Türkei ab.',
        'Durch amerikanische Luftangriffe, die die Abschussrampen auf Kuba zerstörten.',
        'Durch einen Beschluss der Vereinten Nationen, der Kuba zur neutralen Zone erklärte.',
      ],
      richtig: 0,
      erklaerung: 'Kennedy entschied sich gegen den Rat vieler Militärs für eine Seeblockade statt für einen Angriff. Der Abzug der Jupiter-Raketen blieb jahrzehntelang geheim — deshalb sah es lange so aus, als habe nur eine Seite nachgegeben. Wie knapp es war, zeigte das sowjetische U-Boot B-59, auf dem ein Offizier den Einsatz eines Atomtorpedos verhinderte.',
    },
    {
      frage: 'Was war das Besondere an der KSZE-Schlussakte von Helsinki 1975?',
      antworten: [
        'Die Unterzeichner erkannten die bestehenden Grenzen an und verpflichteten sich zugleich auf Menschenrechte — worauf sich Bürgerrechtler im Osten später berufen konnten.',
        'Sie beendete den Warschauer Pakt und ordnete den Abzug aller sowjetischen Truppen aus Osteuropa an.',
        'Sie verbot beiden Seiten den Besitz von Atomwaffen in Europa.',
      ],
      richtig: 0,
      erklaerung: '35 Staaten unterschrieben am 1. August 1975. Weil die Schlussakte in allen Ländern veröffentlicht werden musste, konnten sich Bürgerrechtsgruppen auf ein Dokument berufen, das ihre eigene Regierung unterzeichnet hatte: die Moskauer Helsinki-Gruppe 1976, die Charta 77 ein Jahr später.',
    },
    {
      frage: 'Was regelte der Zwei-plus-Vier-Vertrag vom 12. September 1990?',
      antworten: [
        'Er besiegelte die deutsche Einheit völkerrechtlich: volle Souveränität, Ende der Vier-Mächte-Rechte, endgültige Anerkennung der Oder-Neiße-Grenze, Verzicht auf ABC-Waffen und Abzug der sowjetischen Truppen bis Ende 1994.',
        'Er teilte Deutschland in vier Besatzungszonen auf und regelte die Reparationen.',
        'Er verpflichtete das vereinte Deutschland zur Neutralität und verbot ihm die Mitgliedschaft in Bündnissen.',
      ],
      richtig: 0,
      erklaerung: 'Verhandelt haben zwei deutsche Staaten und die vier Siegermächte — daher der Name. Artikel 6 hält ausdrücklich fest, dass das Recht des vereinten Deutschlands, Bündnissen anzugehören, unberührt bleibt; Artikel 7 beendet die Rechte der vier Mächte. Am 3. Oktober 1990 war Deutschland wieder ein Staat, am 31. August 1994 verließen die letzten sowjetischen Soldaten das Land.',
    },
  ],
};

module.exports = kalterKrieg;
