// Thema: Die frühen Königreiche — wie aus Eroberern Herrscher wurden.
//
// Stand: Runde 9. Enthält vorerst NUR die Sicht der Chronisten und
// Königshöfe (Stimme: Opus). Die Sicht aus den Dörfern ergänzt Hermes; die
// Synthese unten ist ausdrücklich vorläufig und wird danach gemeinsam
// überarbeitet (siehe CLAUDE.md, Perspektiven-Workflow).
//
// Die Achse dieses Kapitels ist keine geografische, sondern eine soziale:
// oben gegen unten. Diese erste Stimme gehört denen, die schreiben ließen —
// Königen, Bischöfen, Hofgelehrten. Sie ist damit die Stimme der Mächtigen,
// und sie muss als solche erkennbar bleiben: Legitimation ist ihr Zweck.
// Deshalb steht die Schattenseite ausdrücklich mit im Text (Mord und Verrat
// an den Höfen), und zwar nicht als Zusatz von außen, sondern so, wie sie in
// denselben Chroniken steht, die die Herrscher rühmen. Keine Verherrlichung,
// keine Dämonisierung.
//
// Das Kapitel knüpft direkt an „Germanen und Völkerwanderung" an: Dort endete
// die Erzählung mit Königreichen, die römische Beamte behielten und ihr Recht
// auf Latein aufschreiben ließen. Hier wird gefragt, wie daraus Herrschaft
// wurde — und der Bogen schließt sich 800 in Rom.
//
// Die Karte liegt in karten/koenigreiche.js — vier Zustände zwischen 476 und
// 800; das Frankenreich ist auf dem ersten Bild der kleinste Fleck und auf dem
// letzten die größte Fläche.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/koenigreiche');

const koenigreiche = {
  id: 'koenigreiche',
  titel: 'Die frühen Königreiche — wie aus Eroberern Herrscher wurden',
  epoche: 'Vom Ende Westroms 476 bis zur Kaiserkrönung Karls des Großen 800',

  aufhaenger: {
    frage: 'Sie kamen als Krieger ohne Kanzlei und ohne Chronik — und dreihundert Jahre später ließ sich einer ihrer Nachfahren vom Papst zum Kaiser krönen. Wie wird aus einem Kriegshaufen ein Königreich?',
    text: [
      'Ein Heerführer kann befehlen, solange er Beute verteilt. Stell dir vor,',
      'du bist dieser Heerführer. Deine Männer folgen dir, weil du sie reich',
      'machst — Gold, Waffen, Pferde, Land. Sie folgen dir persönlich, nicht',
      'deinem Amt. Und jetzt hast du gewonnen: Das Land gehört dir. Es hat',
      'Städte, in denen du nie warst, Straßen, die du nicht gebaut hast, und',
      'eine Million Menschen, die kein Wort deiner Sprache verstehen.',
      '',
      'Wie regierst du das? Wie sorgst du dafür, dass deine Befehle auch dort',
      'gelten, wo du nicht bist? Wie ziehst du Steuern ein, wenn niemand mehr',
      'weiß, wer wie viel schuldet? Und die schwierigste Frage von allen: Wie',
      'sorgst du dafür, dass dein Sohn dasselbe darf wie du — dass die Leute',
      'ihm gehorchen, obwohl er noch nie eine Schlacht gewonnen hat?',
      '',
      'Genau vor dieser Aufgabe standen die Könige nach 476. Ihre Antworten',
      'sind der Grundriss, auf dem Europa danach tausend Jahre lang gebaut hat:',
      'ein Bündnis mit der Kirche, eine Taufe zur richtigen Zeit, das Recht auf',
      'Pergament — und die Behauptung, Gott selbst habe das so gewollt.',
      '',
      'Am 25. Dezember 800 stand einer ihrer Nachfahren in Rom und bekam eine',
      'Kaiserkrone aufgesetzt. Die Chronisten schrieben: Das Reich ist wieder',
      'da. Wie es dazu kam, erzählt dieses Kapitel — und zwar zuerst so, wie es',
      'die erzählen, die dabei etwas zu gewinnen hatten.',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'chronisten',
      name: 'Die Sicht der Chronisten und Königshöfe',
      stimme: 'Opus',
      text: [
        'So wird die Geschichte der frühen Königreiche dort erzählt, wo sie',
        'aufgeschrieben wurde: an den Höfen, in den Bischofsstädten und in den',
        'Klöstern. Es ist die Erzählung der Mächtigen — nicht, weil die anderen',
        'nichts zu sagen gehabt hätten, sondern weil nur diese schreiben',
        'ließen.',
        '',
        'Halte dir beim Lesen vier Namen bereit, denn ihnen verdanken wir fast',
        'alles: **Gregor von Tours**, Bischof, schrieb um 590 seine „Zehn Bücher',
        'Geschichten" über die Franken. **Fredegar** heißt eine Chronik des',
        '7. Jahrhunderts, deren Verfasser wir nicht kennen. **Beda**, ein Mönch',
        'in Northumbrien, vollendete 731 die erste Geschichte des englischen',
        'Volkes. Und **Einhard** schrieb um 830 das Leben Karls des Großen,',
        'nachdem er jahrzehntelang an dessen Hof gelebt hatte.',
        '',
        'Vier Kirchenmänner. Keiner von ihnen schrieb aus Neugier allein: Jeder',
        'schrieb für jemanden, über jemanden und mit einer Absicht. Das macht',
        'ihre Bücher nicht wertlos — es macht sie zu Quellen, die man lesen',
        'muss wie einen Brief, bei dem man den Absender kennt.',
        '',
        '## Die Karte nach dem Ende',
        '',
        'Sieh dir auf der Karte die erste Phase an, das Jahr 476. Da ist kein',
        'leeres Land und keine Wildnis, sondern eine Trümmerkarte: sieben',
        'Herrschaften, wo eben noch eine war. Die Westgoten halten Südgallien',
        'und Spanien — das größte Reich des Westens. Die Vandalen sitzen in',
        'Nordafrika, die Burgunder an der Rhône, Odoaker in Italien. In',
        'Britannien haben angelsächsische Anführer angefangen, sich Könige zu',
        'nennen. Und die Franken? Ein Streifen um Tournai, der kleinste Fleck',
        'auf dem ganzen Bild.',
        '',
        'Kaum jemand hätte 476 darauf gewettet, dass ausgerechnet dieser Fleck',
        'einmal die größte Fläche der Karte sein würde. Auf dem letzten Bild,',
        'im Jahr 800, ist er es.',
        '',
        'Die Frage, vor der alle diese Herren standen, war dieselbe: Wie hält',
        'man das zusammen? Ein Heer folgt einem Mann. Ein Königreich muss auch',
        'dann funktionieren, wenn der Mann gerade woanders ist — und wenn er',
        'tot ist.',
        '',
        '## Woher die neuen Herren ihre Macht nahmen',
        '',
        'Zuerst aus dem, was sie mitbrachten: **Gefolgschaft**. Ein Anführer',
        'sammelte Männer um sich, die ihm Treue schworen; er gab ihnen Waffen,',
        'Schmuck, Pferde, einen Platz an seiner Tafel und einen Anteil an der',
        'Beute. Das ist kein Beamtenverhältnis, sondern ein persönliches Band —',
        'und ein teures. Ein König, der nichts mehr zu verteilen hatte, war',
        'bald kein König mehr.',
        '',
        'Genau hier liegt das Problem des Erfolgs. Solange man erobert, gibt es',
        'Beute. Ist die Eroberung vorbei, muss der König aus dem Land',
        'herausholen, was er vorher aus dem Krieg holte. Das heißt: Land',
        'verschenken (und damit ärmer werden), Abgaben eintreiben (und dafür',
        'Leute brauchen, die rechnen und schreiben können) — oder wieder Krieg',
        'führen. Fast alles, was in den nächsten Jahrhunderten passiert, hat',
        'mit dieser Rechnung zu tun.',
        '',
        'Und dann brauchten diese Könige noch etwas, das sich mit Beute nicht',
        'kaufen lässt: einen Grund, warum ausgerechnet ihre Familie herrschen',
        'darf. Die Antwort, die sie fanden, hat Europa geprägt — sie holten',
        'sich Gott ins Boot.',
        '',
        '## Die Taufe als Werkzeug',
        '',
        'Um 496 ließ sich der Frankenkönig **Chlodwig** in Reims taufen. Gregor',
        'von Tours erzählt es als Wunder: Chlodwig steht in einer verlorenen',
        'Schlacht gegen die Alamannen, gelobt, Christ zu werden, wenn er',
        'gewinnt — und gewinnt. Bischof Remigius soll ihm bei der Taufe',
        'zugerufen haben: „Beuge deinen Nacken. Bete an, was du verbrannt hast,',
        'verbrenne, was du angebetet hast." Selbst das Jahr ist unsicher; es',
        'kann auch 498 oder 499 gewesen sein.',
        '',
        'Entscheidend ist nicht, dass Chlodwig Christ wurde, sondern **welcher',
        'Christ**. Die Könige der Goten, Vandalen und Burgunder waren nämlich',
        'längst Christen — aber Arianer, Anhänger einer Lehre, die die',
        'katholische Kirche als Irrlehre verurteilt hatte. Für die katholische',
        'Bevölkerung Galliens und ihre Bischöfe waren diese Könige Ketzer.',
        'Chlodwig ließ sich katholisch taufen und war damit der einzige',
        'germanische König, hinter den sich die alte römische Oberschicht',
        'vorbehaltlos stellen konnte. Aus einem fremden Kriegsherrn wurde über',
        'Nacht ein Beschützer des rechten Glaubens.',
        '',
        'Was für ein Werkzeug das war, sieht man daran, dass es andere',
        'nachmachten. 589 trat in Toledo das dritte Konzil zusammen, und der',
        'Westgotenkönig **Reccared** erklärte dort, er und sein Volk gäben den',
        'arianischen Glauben auf. Danach regierten in Spanien Könige und',
        'Bischöfe gemeinsam; die Konzilien von Toledo waren halb',
        'Kirchenversammlung, halb Reichstag. 597 empfing der Kentische König',
        'Æthelberht den römischen Mönch Augustinus — vorsichtig, unter freiem',
        'Himmel, aus Furcht vor Zauberei —, und ließ sich taufen. Auch hier',
        'übergeht die fromme Erzählung gern eine Kleinigkeit: Æthelberhts Frau',
        'Bertha war eine fränkische Prinzessin, längst Christin und hatte ihren',
        'eigenen Bischof mitgebracht.',
        '',
        'Nüchtern betrachtet war die Taufe für diese Könige beides: ein',
        'Glaubensschritt und ein Machtschritt. Die Chronisten erzählen nur das',
        'erste. Man darf trotzdem das zweite mitdenken.',
        '',
        '## Die Kirche erbt die Verwaltung',
        '',
        'Jetzt kommt der wichtigste Satz dieses Kapitels, und er klingt',
        'unspektakulär: **Die Könige konnten meistens nicht schreiben — die',
        'Kirche konnte es.**',
        '',
        'Als das Weströmische Reich zerfiel, verschwand seine Verwaltung nicht',
        'einfach; sie wanderte. Die Bischofssitze lagen in den alten römischen',
        'Städten, die Kirchenbezirke folgten den römischen Verwaltungsbezirken —',
        'unsere Diözesen sind zum guten Teil noch römische Landkarte. Bischöfe',
        'kamen häufig aus denselben vornehmen Familien, die vorher Statthalter',
        'gestellt hatten. Sie konnten Latein, kannten das Recht, führten Listen,',
        'verwalteten Getreide, sprachen Recht, verhandelten mit Belagerern.',
        '',
        'Für einen König war ein Bischof deshalb doppelt wertvoll: als',
        'Fachmann und als Fürsprecher bei Gott. Für einen Bischof war ein',
        'König doppelt wertvoll: als Schutz und als Geldgeber. Beide brauchten',
        'einander, und beide wussten es.',
        '',
        'Man sieht das Ergebnis an einer scheinbaren Kleinigkeit. Die Franken',
        'ließen um 510 ihr Recht aufschreiben, die **Lex Salica** — ihr eigenes,',
        'altes Recht mit Bußen für Diebstahl, Totschlag und Beleidigung. Aber',
        'sie ließen es auf **Latein** aufschreiben, von Schreibern der Kirche,',
        'nach römischem Muster. Dasselbe taten Westgoten, Burgunder und',
        'Langobarden. Wer Herrschaft dauerhaft machen will, braucht Schrift —',
        'und die Schrift lag in Klöstern.',
        '',
        'Die Chronisten ziehen daraus eine Formel, die sechshundert Jahre',
        'halten sollte: Der König regiert **von Gottes Gnaden**. Nicht, weil er',
        'der stärkste Krieger ist. Sondern weil Gott ihn gewollt hat — und wer',
        'das bezeugt, ist die Kirche.',
        '',
        '## Theoderich: ein König, der Römer sein wollte',
        '',
        'Der Mann, der am weitesten ging, war **Theoderich der Große**. Er kam',
        '493 nach Ravenna, tötete Odoaker bei einem Gastmahl eigenhändig — und',
        'regierte danach dreiunddreißig Jahre lang so römisch, wie es nur ging.',
        'Römische Beamte, römisches Recht, ein Senat, den er weiterarbeiten',
        'ließ, Getreideverteilungen, Zirkusspiele, Bauprogramme. Er nannte sich',
        'nicht Kaiser; formal regierte er im Namen des Kaisers in',
        'Konstantinopel. Seine Kirchen und sein Grabmal in Ravenna stehen bis',
        'heute; die Mosaiken kann man sich ansehen.',
        '',
        'In den Briefen, die sein Kanzler Cassiodor für ihn schrieb, steht das',
        'Programm ausdrücklich: Die Goten sorgen für die Verteidigung, die',
        'Römer für die Zivilisation, und beide profitieren. Es war ein',
        'ernstgemeinter Versuch, zwei Völker in einem Reich leben zu lassen.',
        '',
        'Und er hielt nicht bis zuletzt. Theoderich war Arianer, seine',
        'Untertanen katholisch; als sich das Verhältnis zu Konstantinopel',
        'verschlechterte, wurde aus Misstrauen Verfolgung. Am Ende seines',
        'Lebens ließ er den Gelehrten **Boethius** hinrichten, der im Kerker',
        'noch den „Trost der Philosophie" schrieb — eines der meistgelesenen',
        'Bücher des Mittelalters. Wenige Jahrzehnte später war das',
        'Ostgotenreich zerschlagen, nicht von Barbaren, sondern von Ostrom.',
        '',
        '## Die Schattenseite steht in denselben Büchern',
        '',
        'Wer glaubt, die Chronisten hätten ihre Könige nur gelobt, hat sie',
        'nicht gelesen. Gregor von Tours nennt Chlodwig einen neuen Konstantin,',
        'vom Himmel geführt — und berichtet auf denselben Seiten, wie dieser',
        'König seine Verwandten der Reihe nach beseitigen ließ, einen mit der',
        'Axt, einen durch gedungene Mörder, einen durch Verrat. Am Ende, so',
        'Gregor, habe Chlodwig öffentlich geklagt, er stehe nun allein da wie',
        'ein Fremder und habe keine Verwandten mehr, die ihm helfen könnten —',
        'und Gregor fügt trocken hinzu, das habe er nicht aus Trauer gesagt,',
        'sondern um zu sehen, ob sich noch jemand meldete, den man umbringen',
        'könnte.',
        '',
        'So geht es weiter. Die Merowinger teilten ihr Reich nach fränkischem',
        'Brauch unter allen Söhnen auf — und diese Söhne führten Krieg',
        'gegeneinander. Die Königinnen Brunhild und Fredegunde bekämpften sich',
        'über Jahrzehnte; Brunhild, hochgebildet und jahrzehntelang',
        'einflussreich, wurde 613 im Alter von etwa siebzig Jahren hingerichtet,',
        'indem man sie an ein Pferd band. Das steht nicht in einem',
        'Enthüllungsbuch, das steht in den Chroniken selbst.',
        '',
        'Warum schrieben sie das auf? Weil sie Kirchenmänner waren und ein',
        'Muster darin sahen: Hochmut wird bestraft, Gott richtet. Ihre Bücher',
        'sind Rühmung **und** Warnung zugleich. Für uns hat das einen',
        'praktischen Vorteil — eine Quelle, die auch Unangenehmes über ihren',
        'Helden erzählt, ist glaubwürdiger als eine, die nur strahlt.',
        '',
        'Trotzdem bleibt der Rahmen ihrer: Es geht um Könige, Bischöfe, Schlachten',
        'und Wunder. Ob die Ernte reichte, steht in diesen Büchern nur dann, wenn',
        'eine Hungersnot so groß war, dass sie den Hof erreichte.',
        '',
        '## 751 und 800: die Kirche macht Könige',
        '',
        'Wie weit das Bündnis zwischen Thron und Altar getragen hatte, zeigte',
        'sich 751. Die Merowinger regierten da nur noch dem Namen nach; die',
        'wirkliche Macht lag bei ihren Hausmeiern, den Karolingern. Pippin, der',
        'amtierende Hausmeier, ließ dem Papst eine Frage stellen, die es in sich',
        'hat: Ob es gut sei, dass der König heiße, wer keine Macht habe. Der',
        'Papst antwortete, besser solle der König heißen, der die Macht',
        'tatsächlich ausübe. Daraufhin wurde der letzte Merowinger ins Kloster',
        'geschickt, und Pippin wurde König — und, das war das Neue, **gesalbt**,',
        'nach dem Vorbild der Könige des Alten Testaments.',
        '',
        'Damit war ausgesprochen, was seit Chlodwig gegolten hatte: Nicht die',
        'Abstammung allein macht den König, sondern die Anerkennung — und die',
        'wichtigste Anerkennung vergibt die Kirche.',
        '',
        'Pippins Sohn Karl regierte sechsundvierzig Jahre und führte fast jedes',
        'Jahr Krieg. Er unterwarf die Langobarden (774), Bayern (788) und in',
        'einem dreißigjährigen, sehr blutigen Ringen die Sachsen, die zur Taufe',
        'gezwungen wurden. Sein Reich reichte am Ende von der Elbe bis über die',
        'Pyrenäen.',
        '',
        'Am 25. Dezember 800 setzte ihm Papst Leo III. in Rom eine Krone auf',
        'und ließ ihn als Kaiser ausrufen. Für die Chronisten war das die',
        'Vollendung, der Bogen zurück über dreihundert Jahre: **Das Reich ist',
        'wieder da.** Einhard behauptet, sein Herr sei völlig überrascht gewesen',
        'und hätte die Kirche nicht betreten, wenn er es geahnt hätte — was die',
        'meisten Historiker für höfliche Diplomatie halten. Denn in',
        'Konstantinopel saß weiterhin ein Kaiser, und dort galt der Vorgang als',
        'Anmaßung: Man kann nicht ein zweites Reich krönen, wenn das erste noch',
        'steht.',
        '',
        'In Aachen ließ Karl derweil etwas tun, das unscheinbarer aussieht und',
        'weiter gereicht hat als seine Feldzüge. Er holte Gelehrte an den Hof,',
        'allen voran den Angelsachsen Alkuin aus York, und ließ antike Texte',
        'abschreiben — in einer neuen, klar lesbaren Schrift. Sehr viel von dem,',
        'was wir heute aus der Antike besitzen, hat nur überlebt, weil es in',
        'diesen Jahrzehnten kopiert wurde. Karl selbst, berichtet Einhard,',
        'versuchte noch als alter Mann schreiben zu lernen und legte',
        'Schreibtafeln unter sein Kopfkissen; recht gelingen wollte es ihm',
        'nicht.',
        '',
        '## Und die andere Seite?',
        '',
        'Alles, was du gerade gelesen hast, kommt von den Höfen — von denen,',
        'die schreiben ließen. Es ist eine Geschichte von Königen, Bischöfen,',
        'Schlachten und Krönungen, und sie ist in ihrem Rahmen ehrlich: Sie',
        'verschweigt weder die Morde noch den Nutzen des Glaubens.',
        '',
        'Nur lebten in diesen Königreichen neun von zehn Menschen auf dem Land.',
        'Sie bauten das Getreide an, aus dem die Abgaben kamen, und stellten die',
        'Männer, aus denen die Heere wurden. In den Chroniken tauchen sie fast',
        'nur als Zahl auf: als Hungersnot, als Seuche, als geplündertes Dorf.',
        'Kaum einer von ihnen hat einen Namen hinterlassen.',
        '',
        'Diese Fragen kann die Sicht der Höfe nicht beantworten: Was änderte',
        'sich für ein Dorf, wenn der Herr im fernen Toulouse plötzlich anders',
        'hieß? Merkte man den Wechsel von einem Reich zum nächsten überhaupt —',
        'oder nur daran, wer die Abgaben abholte? Was heißt „Taufe des Königs"',
        'für Leute, die weiter zu ihren alten Quellen und Bäumen gingen? Und',
        'was hat die Kirche den Dörfern gebracht, außer Abgaben: Schutz,',
        'Versorgung, ein Gericht, das auch gegen Mächtige urteilte?',
        '',
        'Sie gehören einer zweiten Stimme.',
      ].join('\n'),
    },
    {
      id: 'doerfer',
      name: 'Die Sicht aus den Dörfern',
      stimme: 'Hermes',
      text: [
        'Diese Sichtweise erzählt die Geschichte der Königreiche von unten —',
        'aus den Dörfern, in denen die meisten Menschen dieser Zeit lebten.',
        'Wer dort wohnte, pflügte, säte, erntete und bezahlte Abgaben; er',
        'schrieb nicht und ließ nicht schreiben. Die Chroniken erwähnen',
        'diese Menschen nur am Rand — wenn überhaupt. Deshalb muss auch',
        'diese Stimme ehrlich sagen, woher sie kommt: aus Siedlungsfunden',
        'und Feldstrukturen, aus Grabbeigaben, aus Ortsnamen, aus den',
        'Stellen in Gesetzen, an denen plötzlich Bauern vorkommen. Das ist',
        'weniger, als die Höfe hinterließen — aber es reicht, um zu sehen,',
        'dass die Königreiche von unten ganz anders aussahen als von oben.',
        '',
        '## Die Königreiche, von unten gesehen',
        '',
        'Was änderte sich für einen Bauern, wenn ein König starb und ein',
        'anderer kam? Wenig — außer dem Namen dessen, der die Abgaben',
        'abholte. Das Dorf blieb, die Felder blieben, der Jahreslauf blieb:',
        'Aussaat im Frühjahr, Ernte im Sommer, Schlachten im Herbst. Die',
        'Königreiche wechselten oben; unten ging die Arbeit weiter. Die',
        'Chroniken erzählen von Eroberungen und Thronfolgen, als sei die',
        'Geschichte ein Turnier der Mächtigen. Für die meisten Menschen war',
        'sie eine Abfolge von Wintern, die man überstehen musste.',
        '',
        '## Was der König brauchte, kam aus unseren Scheunen',
        '',
        'Die glänzende Welt der Höfe — Gefolge, Feste, Kriege, Geschenke —',
        'wurde bezahlt mit dem, was die Dörfer erarbeiteten. Der Zehnt an',
        'die Kirche, die Abgaben an den Herrn, die Fronarbeit auf dessen',
        'Feldern: Das Königreich war eine Maschine, die von der Ernte',
        'lebte. Wenn die Chronisten von der „Beute" der Eroberer',
        'schreiben, vergessen sie leicht, dass die eigentliche Beute',
        'jedes Jahr auf den Feldern wuchs — und dass sie von Menschen',
        'eingebracht wurde, deren Namen kein Chronist nennt.',
        '',
        '## Die Taufe des Königs',
        '',
        'Chlodwigs Taufe war für die Höfe ein Ereignis von größter',
        'Bedeutung. Für ein Dorf in Gallien zunächst kaum: Man ging',
        'weiter zu den Quellen und Bäumen, an denen die Vorfahren ihre',
        'Gaben niedergelegt hatten, feierte die alten Feste und bat um',
        'Schutz für Vieh und Ernte. Die Taufe des Königs wurde erst im',
        'Laufe von Generationen spürbar — als die Kirche ins Dorf kam,',
        'eine Kapelle baute, einen Pfarrer setzte, die Feste umdeutete und',
        'die neuen Namen durchsetzte. Was von oben ein Ereignis war, war',
        'von unten ein langsamer Wandel, der sich über Jahrzehnte',
        'hinzog. Und mancherorts hielt sich beides lange nebeneinander:',
        'der christliche Glaube und die alten Bräuche, die die Kirche',
        'vergeblich zu verbieten suchte.',
        '',
        '## Die Kirche im Dorf',
        '',
        'Und was brachte die Kirche den Dörfern? Zuerst die Abgaben — den',
        'Zehnt, der den Hof und den Pfarrer ernährte. Aber nicht nur. Das',
        'Kloster oder die Bischofskirche war oft der einzige Ort, der',
        'überschüssige Ernte aufkaufte, in Notzeiten Getreide ausgab und',
        'Kranke aufnahm. Die Kirchenfeste gaben dem Jahr seinen Rhythmus.',
        'Und das kirchliche Gericht war manchmal der einzige Ort, an dem',
        'auch ein Mächtiger zur Rechenschaft gezogen werden konnte. Trost',
        'und Kontrolle, Schutz und Abgabe lagen in derselben Hand — die',
        'Kirche war für die Dörfer beides, und die Chronisten, die für',
        'sie schrieben, erzählten nur die eine Seite.',
        '',
        '## Was diese Sicht anders macht',
        '',
        'Auch diese Sichtweise ist eine Rekonstruktion, und sie muss das',
        'zugeben: Über das Leben der meisten Menschen wissen wir',
        'erschreckend wenig. Aber die Richtung der Erzählung ändert die',
        'Wertung. Was die Chroniken als Aufstieg und Vollendung feiern —',
        'die Taufe Chlodwigs, die Krönung Karls —, war für die Mehrheit',
        'der Menschen Arbeit, Fron und die Sorge um die Ernte. Die',
        '„Goldene Zeit" der frühen Königreiche war für neun von zehn',
        'Menschen kein goldenes Zeitalter, sondern ein hartes Leben, das',
        'man zu überleben suchte. Die Geschichte der Mächtigen ist nicht',
        'die Geschichte der Mehrheit — sie ist nur die, die aufgeschrieben',
        'wurde.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 9, gemeinsam überarbeitet nach Ergänzung der Sicht
  // aus den Dörfern durch Hermes).
  synthese: [
    'In den Kapiteln davor lagen die Perspektiven nebeneinander auf der',
    'Landkarte — Rom und China, Europa und Japan. Hier liegen sie',
    'übereinander: oben und unten im selben Land, in derselben Woche, oft',
    'im selben Dorf. Die eine Seite ließ schreiben, die andere pflügte.',
    'Wer nur die Chroniken liest, erfährt viel über zwanzig Familien und',
    'fast nichts über neun von zehn Menschen.',
    '',
    '**Wo sie sich treffen:** Beide Sichtweisen sehen dieselbe Maschine:',
    'Die Königreiche wurden zusammengehalten von Gefolgschaft und Kirche.',
    'Die Chronisten erzählen das von oben — die Taufen, die Krönungen,',
    'die Bündnisse. Die Dörfer erlebten es von unten — die Abgaben, die',
    'Fron, den Zehnt, die neuen Namen. Und beide wissen: Die Könige',
    'konnten meistens nicht schreiben; die Kirche konnte es. Deshalb ist',
    'die Kirche in beiden Erzählungen die heimliche Hauptfigur — dort',
    'als Stütze des Throns, hier als die Hand, die ins Dorf griff.',
    '',
    '**Wo sie auseinandergehen:** Was oben ein Ereignis war, war unten',
    'ein Wandel über Generationen. Die Taufe Chlodwigs: für die Höfe der',
    'Machtgriff, der das Reich begründete; für die Dörfer ein ferner',
    'Vorgang, der erst spürbar wurde, als die Kapelle kam. Das Jahr 800:',
    'für die Chronisten die Vollendung — die Wiederkehr des Reiches; für',
    'die Bauern ein Winter wie jeder andere. Und die Namen: In den',
    'Chroniken stehen Könige, Bischöfe, Königinnen — kein einziger',
    'Bauer. Die Geschichte der Mächtigen ist nicht die Geschichte der',
    'Mehrheit; sie ist nur die, die aufgeschrieben wurde.',
    '',
    '**Was daraus folgt:** Wer die Zeit nur von oben kennt, hält die',
    'Chroniken für die ganze Geschichte. Die Sicht der Höfe verrät ihre',
    'eigenen Absichten, wenn man genau liest: Sie erzählt die Taufe als',
    'Wunder und lässt erkennen, wie nützlich sie war; sie nennt Könige',
    'von Gottes Gnaden und berichtet zugleich, wie diese Könige ihre',
    'Verwandten umbringen ließen. Widersprüche in einer Quelle sind kein',
    'Ärgernis — sie sind die Stelle, an der man am meisten lernt.',
    '',
    '**Dein Urteil beginnt hier:** Was macht einen König zum König:',
    'Herkunft, Taufe, Macht — oder die, die ihn anerkennen? Und wenn von',
    'einer Zeit nur die Berichte der Mächtigen übrig sind: Kann man dann',
    'überhaupt wissen, wie sie war — und wo würdest du suchen, wenn du',
    'es trotzdem versuchen wolltest?',
  ].join('\n'),

  urteil: {
    frage: 'Was macht einen König zum König: seine Herkunft, seine Taufe, seine Macht — oder die, die ihn anerkennen? Und wer entscheidet eigentlich, wessen Geschichte über ein Königreich erzählt wird?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Drei Anstöße: Erstens, 751 stellte Pippin dem Papst die Frage, ob König heißen solle, wer keine Macht hat — überlege, was diese Frage über Macht verrät, bevor du sie beantwortest. Zweitens, Chlodwig ließ sich taufen und wurde dadurch für die Bischöfe und die alte römische Oberschicht wählbar; war das Glaube, Berechnung, oder lässt sich das gar nicht trennen? Drittens, denk an eine Gruppe, die du kennst — Klasse, Verein, Mannschaft. Wer dort das Sagen hat, hat es meistens nicht allein durch Stärke. Woran liegt es sonst?',
  },

  quiz: [
    {
      frage: 'Warum war es so wichtig, dass Chlodwig sich katholisch taufen ließ?',
      antworten: [
        'Weil er damit der erste Christ unter den germanischen Königen war.',
        'Weil die anderen Könige zwar Christen waren, aber Arianer — für die katholische Bevölkerung Galliens und ihre Bischöfe Ketzer. Chlodwig war damit der einzige König, hinter den sich die alte römische Oberschicht stellen konnte.',
        'Weil der Papst ihm dafür Land in Italien versprach.',
      ],
      richtig: 1,
      erklaerung: 'Die Taufe war Glaubensschritt und Machtschritt zugleich. Andere machten es nach: 589 gab König Reccared in Toledo für die Westgoten den arianischen Glauben auf. Gregor von Tours erzählt Chlodwigs Taufe als Wunder — sogar das Jahr ist unsicher, 496, 498 oder 499.',
    },
    {
      frage: 'Wer war Theoderich der Große?',
      antworten: [
        'Ein römischer Kaiser, der Italien gegen die Goten verteidigte.',
        'Der letzte weströmische Kaiser, den Odoaker absetzte.',
        'Der Ostgotenkönig, der ab 493 von Ravenna aus regierte — mit römischen Beamten, römischem Recht und einem Senat, den er weiterarbeiten ließ. Formal regierte er im Namen des Kaisers in Konstantinopel.',
      ],
      richtig: 2,
      erklaerung: 'Sein Kanzler Cassiodor formulierte das Programm: Die Goten verteidigen, die Römer verwalten. Der Versuch war ernst gemeint — und er hielt nicht bis zuletzt: Am Ende ließ Theoderich den Gelehrten Boethius hinrichten, der im Kerker noch den „Trost der Philosophie" schrieb.',
    },
    {
      frage: 'Wie brachten die neuen Königreiche eine Verwaltung zustande, obwohl die römische zerfallen war?',
      antworten: [
        'Über die Kirche: Bischöfe konnten Latein, Recht und Rechnung, die Kirchenbezirke folgten den römischen Verwaltungsbezirken, und in den Klöstern lag die Schrift.',
        'Sie bauten eine ganz neue Verwaltung aus germanischen Kriegern auf.',
        'Sie verzichteten auf Verwaltung und regierten allein durch Heerführung.',
      ],
      richtig: 0,
      erklaerung: 'König und Bischof brauchten einander: der eine Fachleute und Fürsprecher bei Gott, der andere Schutz und Geld. Sichtbar wird das an der Lex Salica — die Franken ließen ihr eigenes, altes Recht aufschreiben, aber auf Latein und von Schreibern der Kirche.',
    },
    {
      frage: 'Was geschah am 25. Dezember 800 in Rom?',
      antworten: [
        'Der Papst erklärte das Weströmische Reich für wiederhergestellt und wurde selbst Kaiser.',
        'Papst Leo III. setzte dem Frankenkönig Karl eine Krone auf und ließ ihn als Kaiser ausrufen — für die Chronisten die Vollendung, für Konstantinopel eine Anmaßung, weil dort schon ein Kaiser saß.',
        'Karl der Große eroberte Rom und ließ sich vom Senat zum Kaiser wählen.',
      ],
      richtig: 1,
      erklaerung: 'Einhard behauptet, Karl sei überrascht gewesen und hätte die Kirche sonst nicht betreten — die meisten Historiker halten das für Diplomatie. Rom war damals keine Millionenstadt mehr, sondern ein Ort mit vielleicht 25 000 Menschen zwischen Ruinen. Der Titel wog trotzdem schwerer als die Stadt.',
    },
    {
      frage: 'Schrieben die Könige dieser Zeit ihre Geschichte selbst auf?',
      antworten: [
        'Ja, jeder Königshof führte ein eigenes Tagebuch.',
        'Nein — es schrieben Bischöfe und Mönche: Gregor von Tours über die Franken, Beda über die Angelsachsen, Einhard über Karl den Großen. Die meisten Könige konnten nicht schreiben.',
        'Nein, die Berichte stammen alle aus Konstantinopel.',
      ],
      richtig: 1,
      erklaerung: 'Deshalb liest man diese Bücher wie einen Brief, bei dem man den Absender kennt: Jeder schrieb für jemanden und mit einer Absicht. Karl der Große versuchte laut Einhard noch als alter Mann das Schreiben zu lernen und legte Schreibtafeln unter sein Kopfkissen — es gelang ihm nicht mehr richtig.',
    },
  ],
};

module.exports = koenigreiche;
