// Thema: Vom Mittelalter zur Neuzeit — die Geburtsstunde Europas.
//
// Stand: Runde 10. Enthält vorerst NUR die Sicht der alten Ordnung
// (Stimme: Opus). Die Stimme der Städte und des Aufbruchs ergänzt Hermes; die
// Synthese unten ist ausdrücklich vorläufig und wird danach gemeinsam
// überarbeitet (siehe CLAUDE.md, Perspektiven-Workflow).
//
// Dies ist das erste Kapitel des Neuzeit-Bogens (notizen/kapitel-planung.md):
// die Brücke von Karl dem Großen bis zum Vorabend des Dreißigjährigen
// Krieges. Es knüpft direkt an „Die frühen Königreiche" an — dort endete die
// Erzählung mit der Kaiserkrönung 800, hier fängt sie damit an.
//
// Die Achse ist wie im Kapitel davor eine soziale, aber sie kippt: Diese
// Stimme gehört der Ordnung, die oben stand — Kaiser, Papst, Adel, Kloster.
// Sie darf ihre Welt erklären, ohne sie zu beschönigen: Die Kreuzzüge sind
// Glaube UND Gewalt, die Kirche ist Trost UND Macht, die Ständeordnung ist
// Weltbild UND Rechtfertigung. Keine Verherrlichung, keine Dämonisierung.
//
// Eine inhaltliche Festlegung, die zur Leitidee der App gehört: Das
// „finstere Mittelalter" wird hier als Deutung behandelt, nicht als Tatsache.
// Den Namen haben die Humanisten der Renaissance vergeben — über eine Zeit,
// die sie selbst nicht erlebt hatten, und mit der Absicht, ihre eigene
// Gegenwart hell aussehen zu lassen. Wer das begriffen hat, hat an einem
// harmlosen Beispiel gelernt, wie Epochennamen Urteile transportieren.
//
// Die Karte liegt in karten/mittelalter.js — vier Zustände zwischen 800 und
// 1618, und ein Pfeil, der 1492 aus dem Bild hinausläuft.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/mittelalter');

const mittelalter = {
  id: 'mittelalter',
  titel: 'Vom Mittelalter zur Neuzeit — die Geburtsstunde Europas',
  epoche: 'Von der Kaiserkrönung Karls des Großen 800 bis zum Vorabend des Dreißigjährigen Krieges 1618',

  aufhaenger: {
    frage: 'Achthundert Jahre, die man „finster" nennt — und aus denen die Universitäten, die Städte, die Kathedralen und die Sprachen Europas kommen. Wer hat dieser Zeit eigentlich ihren Namen gegeben, und was hatte er davon?',
    text: [
      'Stell dir vor, jemand nennt die Jahre, in denen du zur Schule gegangen',
      'bist, „die dunkle Zeit". Nicht du. Jemand, der lange nach dir lebt, der',
      'nicht dabei war und der findet, dass erst mit ihm etwas Besseres',
      'angefangen hat.',
      '',
      'Genau das ist dem Mittelalter passiert. Die Menschen dieser Zeit haben',
      'sich nie so genannt — sie hätten das Wort nicht verstanden. „Mittelalter"',
      'heißt: die Zeit dazwischen. Dazwischen zwischen der Antike, die man',
      'bewunderte, und der eigenen Gegenwart, die man für deren Wiedergeburt',
      'hielt. Den Namen erfanden Gelehrte der Renaissance, mehr als tausend',
      'Jahre nach seinem Anfang. Es ist ein Urteil, das sich als Zeitangabe',
      'verkleidet.',
      '',
      'Und was liegt nun wirklich in diesen achthundert Jahren? Ein Kaiser, der',
      'barfuß im Schnee vor einer Burg steht. Heere, die nach Jerusalem ziehen',
      'und dort ein Blutbad anrichten. Ein Schiff, das eine Seuche nach Messina',
      'bringt, an der jeder dritte Europäer stirbt. Die ersten Universitäten.',
      'Kathedralen, an denen drei Generationen bauten. Eine Werkstatt in Mainz,',
      'in der aus einem Buch plötzlich tausend werden. Und ein Mönch, der eine',
      'Streitschrift verschickt und damit die Kirche spaltet.',
      '',
      'Finster? Hell? Lies erst einmal, wie die Welt aussah — und zwar aus der',
      'Sicht derer, die ganz oben in ihr standen. Danach darfst du urteilen.',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'alte-ordnung',
      name: 'Die Sicht der alten Ordnung',
      stimme: 'Opus',
      text: [
        'Das hier ist die Erzählung der alten Ordnung: der Kaiser und Könige,',
        'der Päpste und Bischöfe, des Adels auf seinen Burgen und der Mönche in',
        'ihren Klöstern. Es ist die Welt, die sich für die gottgewollte hielt —',
        'und die im Verlauf dieser achthundert Jahre erlebt, wie ihr eine andere',
        'über den Kopf wächst.',
        '',
        'Diese Stimme hat einen Vorteil und einen blinden Fleck. Der Vorteil:',
        'Sie kennt ihre Welt von innen und kann erklären, warum sie so gebaut',
        'war. Der blinde Fleck: Sie hält diese Bauweise für die natürliche',
        'Ordnung der Dinge, weil sie selbst oben darin sitzt.',
        '',
        '## Eine Welt aus Treueiden',
        '',
        'Karl der Große war 800 Kaiser geworden. Sein Reich zerfiel schon unter',
        'seinen Enkeln — und was an seine Stelle trat, war kein Staat im',
        'heutigen Sinn, sondern ein Netz aus persönlichen Versprechen.',
        '',
        'Das Grundgeschäft hieß **Lehen**. Ein Herr gab einem Mann Land, samt',
        'den Bauern, die darauf arbeiteten. Der Mann wurde dafür sein Vasall:',
        'Er schwor Treue, kam mit seinen Reitern, wenn der Herr in den Krieg',
        'zog, und beriet ihn, wenn er gefragt wurde. Diese Vasallen hatten',
        'wieder eigene Vasallen, und die wieder eigene.',
        '',
        'Warum so umständlich? Weil es nichts anderes gab. Es gab kein Geld in',
        'ausreichender Menge, keine Steuerlisten, keine Beamten, keine Straßen,',
        'die Befehle schnell trugen. Ein König konnte niemanden bezahlen, also',
        'bezahlte er mit dem Einzigen, was er hatte: mit Land. Und weil das',
        'Land dann weg war, brauchte er ständig neues.',
        '',
        'Der eingebaute Fehler zeigt sich schnell. Wer ein Lehen lange genug',
        'hatte, betrachtete es als Eigentum und vererbte es an seinen Sohn.',
        'Damit wurde aus dem Diener ein Konkurrent. Die ganze Geschichte der',
        'deutschen Kaiser lässt sich als Kampf gegen diese Rechnung lesen — und',
        'sie haben ihn verloren: Am Ende stand kein starkes Königtum wie in',
        'Frankreich oder England, sondern ein Reich aus Hunderten von Fürsten,',
        'die tun konnten, was sie wollten. 1618 wird sich das rächen.',
        '',
        '## Beter, Kämpfer, Arbeiter',
        '',
        'Wie erklärt man den Leuten, warum die Welt so ist? Man erklärt sie zum',
        'Plan Gottes. Um 1030 brachte ein Bischof namens Adalbero die Ordnung',
        'in drei Wörter: Es gebe die, die beten, die, die kämpfen, und die, die',
        'arbeiten. Jeder Stand diene den anderen, keiner könne ohne die anderen',
        'bestehen.',
        '',
        'Das klingt friedlich und hat einen Haken, den du sofort siehst: Von den',
        'drei Ständen arbeitete einer — und der stellte über neunzig Prozent',
        'der Menschen. Die Einteilung erklärt nicht nur die Welt, sie',
        'rechtfertigt sie auch. Wer ganz unten steht, steht dort nicht wegen',
        'irgendeiner Ungerechtigkeit, sondern weil Gott es so eingerichtet hat.',
        'Merke dir das: Es ist der bequemste Gedanke, den Mächtige je hatten.',
        '',
        'Der Alltag dieser Ordnung war die **Grundherrschaft**. Ein Bauer',
        'bekam Land, Schutz und ein Gericht; dafür lieferte er einen Teil der',
        'Ernte ab und arbeitete Tage im Jahr für den Herrn. Er war meist nicht',
        'frei — er durfte nicht einfach wegziehen oder heiraten, wen er wollte.',
        'Sklave war er allerdings auch nicht: Er hatte Rechte, und er konnte sie',
        'vor Gericht einklagen.',
        '',
        'Die Klöster gehörten zur selben Ordnung, und sie waren mehr als',
        'Gebetshäuser: die größten Landbesitzer, die besten Landwirte, die',
        'einzigen Bibliotheken, die einzigen Krankenhäuser, die einzigen',
        'Schulen. Wenn du im Jahr 1100 lesen konntest, warst du mit hoher',
        'Wahrscheinlichkeit ein Geistlicher.',
        '',
        '## Zwei Schwerter: Kaiser und Papst',
        '',
        'Und jetzt kommt die Auseinandersetzung, die Europa geprägt hat wie',
        'keine zweite — und die anderswo auf der Welt so nicht stattfand.',
        '',
        'Die Lehre der Kirche kannte zwei Schwerter, ein geistliches und ein',
        'weltliches: der Papst für die Seelen, der Kaiser für die Leiber.',
        'Solange beide dasselbe wollten, ging das gut. Der Streit brach am',
        'nüchternsten Punkt aus, den man sich denken kann — an der Frage, wer',
        'die Bischöfe einsetzen darf. Für den Kaiser war das keine',
        'Glaubensfrage, sondern Existenz: Bischöfe verwalteten halbe Länder,',
        'stellten Truppen und konnten, anders als Grafen, ihre Ämter nicht',
        'vererben. Wer sie ernannte, regierte.',
        '',
        'Im Januar 1077 stand Kaiser **Heinrich IV.** drei Tage lang im',
        'Büßergewand vor der Burg **Canossa**, in der Papst Gregor VII. saß,',
        'und bat um die Aufhebung des Kirchenbanns. Er bekam sie. „Der Gang',
        'nach Canossa" ist bis heute ein Sprichwort für die tiefste Demütigung.',
        '',
        'Nur war es so einfach nicht. Der Bann hatte Heinrichs Vasallen von',
        'ihrem Treueid entbunden — deshalb musste er ihn loswerden, und deshalb',
        'ging er. Kaum war er frei, sammelte er ein Heer, zog nach Italien und',
        'setzte einen eigenen Papst ein; Gregor starb im Exil. Demütigung und',
        'Schachzug zugleich. Beendet wurde der Streit erst 1122 mit einem',
        'Kompromiss, dem Wormser Konkordat.',
        '',
        'Die Folge reicht bis heute. In Europa gab es von da an zwei Mächte, von',
        'denen keine die andere schlucken konnte. Wer mit der einen im Streit',
        'lag, konnte sich an die andere wenden. Aus diesem Dauerkonflikt ist',
        'die Trennung von geistlicher und weltlicher Gewalt hervorgegangen —',
        'nicht aus Einsicht, sondern weil sich keiner durchsetzte.',
        '',
        '## „Gott will es" — die Kreuzzüge',
        '',
        '1095 rief Papst Urban II. in Clermont dazu auf, den Christen im Osten',
        'zu helfen und Jerusalem zu befreien. Die Menge soll geantwortet haben:',
        '„Gott will es!" Wer mitzog, dem wurden seine Sünden erlassen.',
        '',
        'Aus Sicht der alten Ordnung war das ein Meisterstück: Der Papst führte',
        'nun das Schwert, das eigentlich dem Kaiser gehörte. Und die Ritter,',
        'die im eigenen Land unaufhörlich Fehden führten, hatten endlich einen',
        'Feind, der nicht der Nachbar war.',
        '',
        'Was folgte, muss man in derselben Erzählung stehen lassen, in der man',
        'den Glauben stehen lässt. Schon auf dem Weg, im Rheinland, ermordeten',
        'Kreuzfahrergruppen jüdische Gemeinden — die ersten großen Pogrome',
        'Europas. Am 15. Juli 1099 nahmen sie Jerusalem und richteten unter',
        'Muslimen und Juden ein Blutbad an, über das schon die eigenen',
        'Chronisten mit Entsetzen schrieben. 1187 gewann **Saladin** die Stadt',
        'zurück und ließ die Bewohner gegen Lösegeld abziehen; im Westen',
        'bewunderte man ihn dafür noch Jahrhunderte später. 1204 lief ein',
        'Kreuzzug überhaupt nicht mehr ins Heilige Land, sondern nach',
        'Konstantinopel: Ein christliches Heer plünderte eine christliche Stadt,',
        'weil die Überfahrt sonst nicht zu bezahlen war. 1291 fiel Akkon, der',
        'letzte Stützpunkt. Nach knapp zweihundert Jahren war alles verloren.',
        '',
        'Geblieben ist, was niemand geplant hatte. Über die Kontakte kamen',
        'Waren, Rechenverfahren, medizinisches Wissen und antike Texte nach',
        'Europa — vieles davon aus dem Arabischen übersetzt, das seinerseits die',
        'Griechen bewahrt hatte. Und es blieb die Erfahrung, dass hinter dem',
        'Horizont eine Welt lag, die reicher war als die eigene.',
        '',
        '## Als die Ordnung riss: die Pest',
        '',
        'Um 1300 lebten in Europa mehr Menschen als je zuvor. Dann kam die',
        'Katastrophe, und sie kam auf den Handelswegen: 1347 brach in Kaffa auf',
        'der Krim eine Seuche aus, im Oktober liefen die Schiffe in Messina ein,',
        'im Winter in Genua und Marseille, im Sommer 1348 war sie in Paris, im',
        'Herbst in London. In fünf Jahren starb etwa **ein Drittel** der',
        'Menschen Europas, in manchen Städten die Hälfte.',
        '',
        'Niemand kannte die Ursache. Man vermutete verdorbene Luft, eine',
        'Strafe Gottes, eine Sternenkonstellation — und man suchte Schuldige.',
        '1348 und 1349 wurden in Dutzenden Städten die jüdischen Gemeinden',
        'beschuldigt, die Brunnen vergiftet zu haben, und ermordet; in Straßburg',
        'geschah das, bevor die Seuche überhaupt dort war.',
        '',
        'Für die alte Ordnung war die Pest ein Erdbeben. Wo ein Drittel der',
        'Arbeitenden fehlt, wird Arbeit plötzlich wertvoll: Die Überlebenden',
        'forderten mehr Lohn und weniger Abgaben, und wer es nicht bekam, zog',
        'fort. Herren und Könige versuchten, Löhne per Gesetz zu deckeln — es',
        'half nichts. In England und Frankreich brachen große Aufstände aus.',
        'Von hier an bröckelt die Selbstverständlichkeit, mit der jeder auf',
        'seinem Platz blieb.',
        '',
        'Dazu kam der lange Krieg: Von 1337 bis 1453 stritten England und',
        'Frankreich um die französische Krone. In ihm ging auch das Ideal des',
        'Ritters unter — bei Crécy und Azincourt schossen englische Bogenschützen',
        'die französische Reiterei zusammen. Und mitten in diesem Krieg führte',
        'ein Bauernmädchen aus Lothringen ein Heer: **Jeanne d’Arc**, mit',
        'siebzehn. Zwei Jahre später verbrannte man sie als Ketzerin; ein',
        'späteres Verfahren sprach sie frei, und heute ist sie eine Heilige.',
        '',
        '## Drei Zahlen, die alles ändern',
        '',
        'Am Ende dieser Zeit stehen drei Jahreszahlen, die enger zusammenhängen,',
        'als es aussieht.',
        '',
        '**Um 1450, Mainz.** Johannes Gutenberg setzt zusammen, was es einzeln',
        'längst gab: bewegliche Metalllettern, eine Presse und eine Farbe, die',
        'auf Metall hält. Vorher schrieb ein Mönch Monate an einem Buch, jetzt',
        'entstehen Hunderte gleicher Exemplare. Fünfzig Jahre später gibt es in',
        'Europa Millionen Bücher. Zum ersten Mal in der Geschichte kann ein',
        'Gedanke schneller reisen als der Mensch, der ihn hat.',
        '',
        '**1453, Konstantinopel.** Sultan Mehmed II. nimmt die Stadt; das',
        'Oströmische Reich, das in den früheren Kapiteln dieser App immer noch',
        'dastand, wenn im Westen längst alles zerfallen war, ist nach fast',
        'elfhundert Jahren zu Ende. Griechische Gelehrte fliehen mit ihren',
        'Handschriften nach Italien und bringen die Antike mit. Und der Landweg',
        'nach Osten liegt nun in osmanischer Hand — wer Gewürze will, muss einen',
        'Seeweg suchen.',
        '',
        '**1492, Spanien.** In einem einzigen Jahr fällt Granada, das letzte',
        'islamische Königreich der Halbinsel; werden die Juden aus Spanien',
        'vertrieben, viele von ihnen Familien, die dort seit tausend Jahren',
        'lebten; und segelt Kolumbus nach Westen, um Indien zu erreichen. Die',
        'drei Ereignisse gehören zusammen: Dieselben Herrscher, dieselbe',
        'Überzeugung, im Recht zu sein. Was aus der Fahrt wurde, erzählt das',
        'nächste Kapitel.',
        '',
        '## Wer hat das „finstere Mittelalter" erfunden?',
        '',
        'Ungefähr zur selben Zeit blicken italienische Gelehrte zurück und',
        'entdecken die Antike neu — Bücher, Bauformen, Bildhauerei. Sie nennen',
        'ihre eigene Zeit eine Wiedergeburt, eine **Renaissance**. Und weil',
        'zwischen der bewunderten Antike und ihnen selbst nun einmal tausend',
        'Jahre lagen, brauchten sie für diese Jahre einen Namen. Sie nannten sie',
        'die Zeit dazwischen: das **Mittelalter**. Der Dichter Petrarca sprach',
        'schon im 14. Jahrhundert davon, dass danach Finsternis gekommen sei.',
        '',
        'Halte hier einen Moment inne. Der Name dieser Epoche stammt von Leuten,',
        'die sie nicht erlebt haben und ein Interesse daran hatten, dass ihre',
        'eigene Zeit hell wirkte. Es ist Werbung in eigener Sache — und sie hat',
        'funktioniert, bis heute.',
        '',
        'Was der Name verschweigt: In diesen Jahrhunderten entstanden die',
        'Universitäten (Bologna 1088, Paris, Oxford), die gotischen Kathedralen',
        'mit ihrer Technik und ihrem Licht, die Brille, die mechanische Uhr, das',
        'Papier, die dreifelderige Landwirtschaft, das Kummet, mit dem ein Pferd',
        'ziehen kann, ohne sich zu würgen — und die Sprachen, in denen Europa',
        'heute redet. Die Bevölkerung wuchs zwischen 1000 und 1300 auf etwa das',
        'Doppelte. Das ist keine Gesellschaft im Stillstand.',
        '',
        'Und was der Name auch verschweigt: Manches, was man dem Mittelalter',
        'gern zuschreibt, gehört gar nicht dorthin. Die großen Hexenverfolgungen',
        'fanden nicht im finsteren Mittelalter statt, sondern zwischen 1560 und',
        '1630 — also in der Neuzeit, in der Zeit von Buchdruck, Universitäten',
        'und Wissenschaft. Auch die Vorstellung, man habe damals die Erde für',
        'eine Scheibe gehalten, ist falsch: Dass sie eine Kugel ist, wusste',
        'jeder gebildete Mensch seit der Antike; gestritten wurde über ihre',
        'Größe.',
        '',
        'Nichts davon macht die Zeit hell. Es gab Hunger, Seuchen,',
        'Unfreiheit, Ketzerverbrennungen und Pogrome. Die Aussage ist eine',
        'andere: Wer eine ganze Epoche mit einem einzigen Wort erledigt, hat',
        'sich das Nachdenken gespart.',
        '',
        '## Die Spaltung',
        '',
        '1517 wandte sich der Mönch **Martin Luther** in Wittenberg gegen den',
        'Ablasshandel — gegen das Versprechen, man könne sich mit Geld Strafen',
        'im Jenseits erlassen. Für die alte Ordnung war das zunächst ein Streit',
        'unter Theologen. Sie hatte übersehen, was sich inzwischen geändert',
        'hatte: Es gab die Druckerpresse. Luthers Thesen waren in wenigen Wochen',
        'im ganzen Reich, seine Flugschriften erschienen in Hunderttausenden.',
        '',
        'Was folgte, war nicht nur Glaubensstreit. Fürsten, die die neue Lehre',
        'annahmen, konnten Kirchengut einziehen und wurden Herren über ihre',
        'eigene Kirche — Glaube und Rechnung liefen nebeneinanderher. 1525',
        'erhoben sich die Bauern und beriefen sich dabei auf Luther; Luther',
        'selbst rief zu ihrer Niederschlagung auf. Zehntausende starben.',
        '',
        '1555 endete die erste Runde mit dem Augsburger Religionsfrieden, und',
        'die Formel, auf die man sich einigte, sagt alles über diese Ordnung:',
        '**cuius regio, eius religio** — wessen das Land, dessen die Religion.',
        'Nicht der Einzelne entschied, welchem Bekenntnis er folgte, sondern',
        'sein Landesherr. Wer anders glaubte, durfte auswandern. Das war für',
        'die Zeit ein Fortschritt, und es zeigt zugleich, wie diese Welt dachte.',
        '',
        'Der Frieden hielt gut sechzig Jahre. 1618 flogen in Prag die',
        'kaiserlichen Statthalter aus dem Fenster, und der Streit, den 1555',
        'stillgestellt hatte, brach als Krieg aus, der dreißig Jahre dauern',
        'sollte. Damit endet dieses Kapitel — und beginnt das nächste.',
        '',
        '## Und die andere Seite?',
        '',
        'Alles, was du gerade gelesen hast, ist von oben erzählt: aus den',
        'Pfalzen, den Bischofssitzen, den Klöstern und von den Burgen. Es ist',
        'die Welt der Ordnung, die sich selbst für gottgewollt hielt.',
        '',
        'Aber in denselben Jahrhunderten wuchs zwischen den Burgen etwas',
        'anderes heran, das in dieser Erzählung höchstens am Rand vorkommt: die',
        '**Städte**. Kaufleute, die auf eigene Rechnung reisten. Handwerker in',
        'Zünften. Räte, die sich selbst regierten. Der Satz „Stadtluft macht',
        'frei" bedeutete wörtlich, dass ein entlaufener Unfreier nach Jahr und',
        'Tag in der Stadt frei war — das ist ein Loch in der Ständeordnung, und',
        'zwar mitten in ihr. Dazu die Universitäten, die Drucker, die Bankiers,',
        'die Reformer.',
        '',
        'Diese Fragen kann die alte Ordnung nicht beantworten: Wie sieht diese',
        'Zeit aus, wenn man sie nicht vom Thron her betrachtet, sondern vom',
        'Markt? Wo kam das Geld her, das den Fürsten am Ende ihre Kriege',
        'bezahlte — und was verlangten die dafür, die es hatten? Warum',
        'entstanden die neuen Ideen fast alle in Städten? Und war das, was die',
        'alte Ordnung als Zerfall erlebte, von unten gesehen vielleicht ein',
        'Aufbruch?',
        '',
        'Sie gehören einer zweiten Stimme.',
      ].join('\n'),
    },
    {
      id: 'staedte',
      name: 'Die Stimme der Städte und des Aufbruchs',
      stimme: 'Hermes',
      text: [
        'Diese Sichtweise erzählt die Geschichte von denen, die weder ganz',
        'oben noch ganz unten standen: von Bürgern, Kaufleuten, Handwerkern,',
        'Studenten, Druckern und Reformern — den Menschen in den Städten.',
        'Sie schrieben keine Chroniken über Könige, aber sie führten',
        'Geschäftsbücher, Baufälligkeiten, Zunftordnungen und Universitäts-',
        'matrikel. Und sie hinterließen die Häuser, die noch heute stehen.',
        'Aus ihrer Sicht war das, was die alte Ordnung als Zerfall erlebte,',
        'ein Aufbruch — der Anfang von etwas Neuem.',
        '',
        '## Stadtluft macht frei',
        '',
        'Die Stadt war der Ort, an dem die alte Ordnung nicht griff. Wer in',
        'eine Stadt zog, wurde nach Jahr und Tag frei — „Stadtluft macht',
        'frei", hieß es. Hier galt nicht die Geburt, sondern das Können:',
        'Ein Handwerker konnte durch seine Arbeit zu Ansehen kommen, ein',
        'Kaufmann durch sein Geschick zu Reichtum. Die Zünfte regelten, wer',
        'was herstellen durfte — aber sie regelten es unter Gleichen, nicht',
        'von oben herab. Und die Stadt hatte eigene Gerichte, eigene Mauern,',
        'eigene Rechte. Für einen Bauern, der der Grundherrschaft entfloh,',
        'war die Stadt das Versprechen auf ein Leben, das man selbst',
        'bestimmte.',
        '',
        '## Das Geld, das die Herren brauchten',
        '',
        'Die Fürsten bauten Burgen, führten Kriege und hielten Höfe — und',
        'alles kostete Geld, das sie nicht hatten. Ihr Land hatten sie',
        'längst an Vasallen vergeben; was blieb, waren die Städte. Die',
        'Kaufleute gaben Kredite, die Städte zahlten Steuern, und dafür',
        'verhandelten sie: um Rechte, um Zölle, um Selbstbestimmung. Der',
        'König von Frankreich, der englische König, die deutschen Fürsten —',
        'sie alle brauchten das Geld aus den Städten, und wer Geld gibt,',
        'kann mitreden. Der Städtebund der Hanse beherrschte den Handel der',
        'Ostsee und Nordsee, ohne je ein Königreich zu sein.',
        '',
        '## Die neuen Ideen wachsen zwischen den Häusern',
        '',
        'Und warum entstanden die neuen Ideen fast alle in Städten? Weil',
        'dort die Menschen zusammenkamen, die einander etwas zu sagen',
        'hatten: Gelehrte, die von Universität zu Universität zogen,',
        'Kaufleute, die Nachrichten aus aller Welt mitbrachten, Handwerker,',
        'die Techniken weiterentwickelten. Bologna, Paris, Oxford — die',
        'ersten Universitäten waren städtische Einrichtungen, kein',
        'fürstliches Privileg. Wer lesen und rechnen konnte, fand in der',
        'Stadt seinen Platz; auf dem Land war beides nutzlos.',
        '',
        '## Der Buchdruck: die Welt wird vervielfältigbar',
        '',
        'Um 1440 entwickelte Gutenberg in Mainz den Druck mit beweglichen',
        'Lettern. Das klingt technisch — es war eine Revolution. Bisher',
        'war Wissen das, was Mönche in Klöstern abschrieben; jetzt konnte',
        'aus einem Buch plötzlich eine ganze Auflage werden. Die Ideen',
        'verließen die Bibliotheken und gingen auf die Straße. Ohne den',
        'Druck wäre die Reformation nicht denkbar gewesen: Luthers',
        'Schriften wurden in Tausenden von Exemplaren gedruckt und in',
        'Wochen überallhin verbreitet — die erste Massenkommunikation der',
        'Geschichte. Die alte Ordnung, die auf dem Monopol des Wissens',
        'beruhte, verlor die Kontrolle über das, was die Leute lasen.',
        '',
        '## Die Reformation: der Aufbruch wird unumkehrbar',
        '',
        'Und die Reformation selbst war auch eine städtische Bewegung. Die',
        'Reichsstädte und die Bürger standen hinter den Reformatoren —',
        'gegen die Abgaben nach Rom, für einen Glauben, den man selbst',
        'verstehen konnte, in der eigenen Sprache. Der Augsburger',
        'Religionsfrieden von 1555 gab den Fürsten das Recht, die',
        'Konfession zu bestimmen — aber den Boden dafür hatten die Städte',
        'bereitet, in denen die neuen Ideen zuerst Fuß fassten. Was die',
        'alte Ordnung als Ketzerei und Zerfall bekämpfte, war von unten',
        'die Freiheit, selbst zu denken.',
        '',
        '## Was diese Sicht anders macht',
        '',
        'Diese Sichtweise ist ebenso eine Erzählung wie die der Höfe —',
        'aber ihre Richtung ist entgegengesetzt. Wo die alte Ordnung den',
        'Untergang einer gottgewollten Welt sah, sieht sie das Wachstum',
        'einer neuen: die Freiheit, das Geld, das Wissen, die Presse. Die',
        'Neuzeit wurde nicht von Königen gemacht — sie ist in den Städten',
        'entstanden, zwischen Marktplatz, Zunfthaus und Druckerpresse.',
        'Und sie hat dem Wort, das die Renaissance für die Zeit davor',
        'fand, bis heute Geltung verschafft: „finsteres Mittelalter". Aus',
        'der Sicht der Städte war diese Zeit eher die Geburtsstunde',
        'dessen, was wir Europa nennen.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 10, gemeinsam überarbeitet nach Ergänzung der Stimme
  // der Städte und des Aufbruchs durch Hermes).
  synthese: [
    'Dieses Kapitel handelt von einem Übergang — und Übergänge sehen von',
    'oben und von unten entgegengesetzt aus. Was der alten Ordnung als',
    'Zerfall erschien — Bauern, die wegziehen; Städte, die eigene Gerichte',
    'haben; Fürsten, die sich vom Papst lossagen; Bücher, die jeder lesen',
    'kann —, war für die anderen genau der Gewinn. Dieselben Jahre,',
    'dieselben Ereignisse, zwei entgegengesetzte Wörter dafür.',
    '',
    '**Wo sie sich treffen:** Beide Sichtweisen sehen dieselbe Welt: die',
    'Ordnung aus Lehen und Treueid, die Stände, die Kirche als Macht. Und',
    'beide sehen, dass der Wandel unaufhaltsam war — die alte Ordnung',
    'beklagt ihn, die Städte begrüßen ihn. Beide wissen auch: Das Geld',
    'kam aus den Städten, und die neuen Ideen wuchsen zwischen den',
    'Häusern. Was sie trennt, ist nicht die Beobachtung, sondern die',
    'Deutung.',
    '',
    '**Wo sie auseinandergehen:** „Zerfall" oder „Aufbruch" — das ist der',
    'ganze Unterschied. Die alte Ordnung sah den Plan Gottes zerfallen,',
    'die Städte sahen die Freiheit wachsen. Die Kreuzzüge: Zug des',
    'Glaubens oder der Anfang von Handel und Austausch? Die Pest: Strafe',
    'Gottes oder der Moment, in dem Arbeit knapp und teuer wurde? Die',
    'Reformation: Ketzerei oder das Recht, selbst zu denken? Und das',
    'Wort, das alles zusammenfasst — „finsteres Mittelalter" — ist keine',
    'Beobachtung, sondern ein Urteil: vergeben von Humanisten, die diese',
    'Zeit nicht erlebt hatten und ein Interesse daran hatten, dass ihre',
    'eigene Zeit hell wirkte.',
    '',
    '**Was daraus folgt:** Wer die Namen vergibt, hat schon gedeutet —',
    'das ist die Leitidee dieser App, und dieses Kapitel ist ihr',
    'schönstes Beispiel: Ein ganzes Jahrtausend heißt bis heute so, wie',
    'es seine Kritiker nannten. Die alte Ordnung verrät sich an ihren',
    'eigenen Begründungen — sie erklärt die Ständeordnung zum Plan',
    'Gottes, und man sieht, wem dieser Plan nützt. Die Städte verraten',
    'sich an ihrem Fortschrittsglauben — sie sehen im Aufbruch nur das',
    'Wachstum und wenig von dem, was verloren ging. Keine der beiden',
    'Sichtweisen ist gelogen; beide sind Auswahl.',
    '',
    '**Dein Urteil beginnt hier:** Welche Wörter benutzt du selbst für',
    'ganze Zeiten oder Gruppen — und wessen Urteil sprichst du damit',
    'nach? Und: Wie würde jemand in fünfhundert Jahren unsere Gegenwart',
    'nennen — und woran würde er das festmachen?',
  ].join('\n'),

  urteil: {
    frage: 'War das Mittelalter wirklich „finster" — oder ist das ein Vorurteil, das die Renaissance hinterlassen hat und das wir seit fünfhundert Jahren nachsprechen? Und welche Bilder von vergangenen Zeiten hält unsere eigene Zeit für selbstverständlich, die vielleicht genauso Urteile sind?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Drei Anstöße: Erstens, prüfe, wer den Namen vergeben hat — die Menschen dieser Zeit nannten sich nie „mittelalterlich", der Begriff stammt von Gelehrten, die tausend Jahre später lebten und ihre eigene Zeit gefeiert haben. Zweitens, halte beides nebeneinander: Universitäten, Kathedralen, Brille und Uhr auf der einen Seite, Pest, Unfreiheit und Pogrome auf der anderen — und frage dich, ob ein einziges Wort für achthundert Jahre überhaupt reichen kann. Drittens, dreh es um: Wie würde jemand in fünfhundert Jahren unsere Gegenwart nennen, und woran würde er das festmachen?',
  },

  quiz: [
    {
      frage: 'Was geschah 1077 in Canossa?',
      antworten: [
        'Der Papst unterwarf sich dem Kaiser und gab die Bischofsernennung ab.',
        'Kaiser Heinrich IV. stand als Büßer vor der Burg, in der Papst Gregor VII. saß, und erreichte die Aufhebung seines Kirchenbanns.',
        'Kaiser und Papst schlossen den ersten Kreuzzug-Vertrag.',
      ],
      richtig: 1,
      erklaerung: 'Es ging um die Frage, wer die Bischöfe einsetzen darf — für den Kaiser eine Machtfrage, denn Bischöfe verwalteten halbe Länder. Der Gang nach Canossa war Demütigung und Schachzug zugleich: Heinrich war den Bann los, kam mit einem Heer zurück und setzte einen eigenen Papst ein. Beendet wurde der Streit erst 1122 im Wormser Konkordat.',
    },
    {
      frage: 'Was war der Schwarze Tod?',
      antworten: [
        'Eine Hungersnot, die Europa zwischen 1315 und 1317 traf.',
        'Ein Name für den Hundertjährigen Krieg zwischen England und Frankreich.',
        'Die Pest von 1347 bis 1353 — sie kam über die Handelswege von der Krim nach Europa, und etwa ein Drittel der Menschen starb.',
      ],
      richtig: 2,
      erklaerung: 'Die Seuche folgte genau den Straßen, auf denen vorher Pfeffer und Seide kamen: Kaffa, Messina, Genua, Marseille, Paris, London. Weil niemand die Ursache kannte, suchte man Schuldige — 1348/49 wurden in vielen Städten die jüdischen Gemeinden beschuldigt und ermordet. Danach war Arbeit knapp und damit wertvoll: Die Überlebenden forderten mehr Lohn.',
    },
    {
      frage: 'Wer druckte in Europa als Erster mit beweglichen Metalllettern?',
      antworten: [
        'Johannes Gutenberg in Mainz, um 1450.',
        'Martin Luther in Wittenberg, 1517.',
        'Die Mönche des Klosters Cluny, im 11. Jahrhundert.',
      ],
      richtig: 0,
      erklaerung: 'Gutenberg kombinierte bewegliche Lettern, eine Presse und eine haltbare Druckerfarbe. Fünfzig Jahre später gab es in Europa Millionen Bücher. Ohne diese Werkstatt hätte Luthers Streitschrift von 1517 wenige Leser gefunden — mit ihr war sie in zwei Wochen im ganzen Reich. In Ostasien wurde übrigens schon früher gedruckt.',
    },
    {
      frage: 'Was bedeutet die Formel „cuius regio, eius religio" von 1555?',
      antworten: [
        'Jeder Mensch darf selbst wählen, welchem Bekenntnis er folgt.',
        'Der Landesherr bestimmt das Bekenntnis seines Landes — wer anders glaubt, darf auswandern.',
        'Der Kaiser bestimmt das Bekenntnis für das ganze Reich.',
      ],
      richtig: 1,
      erklaerung: '„Wessen das Land, dessen die Religion." Der Augsburger Religionsfrieden beendete die erste Runde der Glaubenskämpfe — für die Zeit ein Fortschritt, und zugleich zeigt die Formel, wie diese Ordnung dachte: Entschieden wurde oben. Der Frieden hielt gut sechzig Jahre; 1618 begann der Dreißigjährige Krieg.',
    },
    {
      frage: 'Woher kommt der Ausdruck „finsteres Mittelalter"?',
      antworten: [
        'Von den Menschen des Mittelalters selbst, die ihre Zeit als dunkel empfanden.',
        'Von den Gelehrten der Renaissance, die die Antike bewunderten und die tausend Jahre dazwischen abwerteten — der Begriff ist ein Urteil, keine Zeitangabe.',
        'Von Historikern des 20. Jahrhunderts, die die Pest untersuchten.',
      ],
      richtig: 1,
      erklaerung: 'Niemand im Mittelalter hätte sich „mittelalterlich" genannt — das Wort heißt „die Zeit dazwischen" und stammt von Leuten, die ihre eigene Gegenwart hell aussehen lassen wollten. Zwei Proben aufs Exempel: Die großen Hexenverfolgungen fanden erst zwischen 1560 und 1630 statt, also in der Neuzeit. Und dass die Erde eine Kugel ist, wusste im Mittelalter jeder Gebildete.',
    },
  ],
};

module.exports = mittelalter;
