// Thema: Das Römische Reich — Aufstieg, Ordnung, Untergang.
//
// Stand: Runde 1. Enthält die europäische Sichtweise (Stimme: Opus).
// Die chinesische Sichtweise ergänzt Hermes; die Synthese wird dann
// gemeinsam überarbeitet (siehe CLAUDE.md, Perspektiven-Workflow).
//
// Reine Daten — keine UI-Importe (Architektur-Regel).
//
// Runde 3: Dazugekommen ist das Feld `karte` für „Geschichte in Bewegung".
// Die Karte selbst liegt in karten/roemisches-reich.js — sie ist lang und
// von anderer Art (Geometrie statt Erzählung), deshalb in einer eigenen
// Datei. Die Texte unten sind unverändert.

const karte = require('./karten/roemisches-reich');

const roemischesReich = {
  id: 'roemisches-reich',
  titel: 'Das Römische Reich',
  epoche: 'Antike — von der Stadtgründung (der Sage nach 753 v. Chr.) bis zum Ende des Weströmischen Reiches 476 n. Chr.',

  aufhaenger: {
    frage: 'Ein Reich, das halb Europa umspannte — wie hält man so etwas zusammen, ohne Telefon, ohne Internet, ohne Autos?',
    text: [
      'Stell dir vor, du sollst ein Gebiet regieren, das von Schottland bis zur',
      'Sahara reicht und von Portugal bis zum Irak. Ein Befehl aus deiner',
      'Hauptstadt braucht bis an den Rand mehrere Wochen. Die Menschen dort',
      'sprechen Dutzende Sprachen, beten zu verschiedenen Göttern und haben',
      'noch nie einen von deinen Beamten gesehen.',
      '',
      'Genau das haben die Römer gemacht — und es hat über Jahrhunderte',
      'funktioniert. Wie? Und warum hat es am Ende doch aufgehört zu',
      'funktionieren? Das ist die eigentlich spannende Frage. Die Jahreszahlen',
      'sind dabei nur Wegmarken, keine Hauptsache.',
    ].join('\n'),
  },

  // „Geschichte in Bewegung" — die Karte kommt nach dem Aufhänger und vor
  // den Blickwinkeln (utils/lernformat.js).
  karte,

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Europäische Sichtweise',
      stimme: 'Opus',
      text: [
        'So wird die Geschichte Roms in Europa erzählt — in Schulbüchern, in',
        'Museen, in Filmen. Es ist die Erzählung der Erben: Europa sieht in Rom',
        'seinen eigenen Anfang. Das färbt die Geschichte, und das darfst du beim',
        'Lesen ruhig im Hinterkopf behalten.',
        '',
        '## Aus einem Dorf wird ein Weltreich',
        '',
        'Rom beginnt klein. Ein paar Hügel an einer Furt durch den Tiber, Bauern,',
        'Viehhändler, Streit mit den Nachbarn. Nichts deutet darauf hin, dass',
        'von hier einmal ein Reich regiert wird.',
        '',
        'Der erste Wendepunkt: Die Römer jagen ihren König davon und machen aus',
        'Rom eine Republik — eine „öffentliche Sache" (res publica). Statt eines',
        'Herrschers gibt es gewählte Beamte, die immer nur ein Jahr im Amt sind,',
        'und den Senat, die Versammlung der einflussreichen Familien. Die Römer',
        'sind so stolz darauf, dass sie es auf ihre Feldzeichen schreiben: SPQR —',
        '„Senat und Volk von Rom". Bis heute steht das auf römischen',
        'Kanaldeckeln.',
        '',
        'Dann wächst Rom. Erst über Italien, dann darüber hinaus. Der große',
        'Gegner ist Karthago, die Handelsmacht in Nordafrika. Drei Kriege lang',
        'geht es hin und her — Hannibal führt sogar Kriegselefanten über die',
        'Alpen und schlägt die Römer mehrfach vernichtend. Rom verliert Schlacht',
        'um Schlacht und gewinnt trotzdem den Krieg, weil es Verluste ersetzen',
        'kann und nicht aufgibt. Am Ende ist Karthago zerstört und das',
        'Mittelmeer ein römischer Binnensee. Die Römer nennen es schlicht „mare',
        'nostrum" — unser Meer.',
        '',
        'Der Erfolg zerreißt fast die Republik. Siegreiche Feldherren wie Caesar',
        'haben Heere, die ihnen persönlich treu sind, nicht dem Staat. Es folgen',
        'Bürgerkriege. Am Ende steht Augustus — offiziell nur „der erste Bürger",',
        'in Wahrheit der erste Kaiser. Die Republik bleibt als Kulisse bestehen,',
        'die Macht liegt bei einem Einzelnen.',
        '',
        '## Wie hält man das zusammen?',
        '',
        'Hier wird es interessant, denn Rom hat nicht nur erobert — Erobern',
        'konnten viele. Rom konnte behalten. Vier Dinge waren dafür wichtig:',
        '',
        '**Die Straßen.** Rund 80 000 Kilometer befestigte Straßen durchziehen',
        'das Reich, schnurgerade über Hügel und durch Sümpfe. Gebaut wurden sie',
        'nicht für Händler, sondern fürs Heer: Eine Legion sollte überall schnell',
        'hinkommen. Aber wo Soldaten marschieren können, können auch Waren,',
        'Briefe, Ideen und Krankheiten reisen. Die Straßen haben das Reich',
        'zusammengebunden — und manche werden noch heute befahren.',
        '',
        '**Das Heer.** Die Legionen waren keine zusammengewürfelten Haufen,',
        'sondern Berufssoldaten mit gleicher Ausrüstung, gleichem Drill und',
        'gleichem Lagerbauplan von Britannien bis Syrien. Sie kämpften nicht nur,',
        'sie bauten: Straßen, Brücken, Grenzanlagen, ganze Städte. Aus',
        'Legionslagern sind Köln, Bonn, Wien und London entstanden.',
        '',
        '**Das Recht.** Für die europäische Erzählung ist das der wichtigste',
        'Punkt. Die Römer schrieben ihre Gesetze auf und stellten sie öffentlich',
        'aus, damit jeder sie nachlesen konnte. Sie entwickelten Regeln für',
        'Verträge, Eigentum, Erbschaft und Schuld, die so durchdacht waren, dass',
        'Juristinnen und Juristen sie noch heute lernen. Manches steckt fast',
        'unverändert im deutschen Bürgerlichen Gesetzbuch.',
        '',
        '**Das Bürgerrecht.** Roms vielleicht klügster Zug. Wer unterworfen',
        'wurde, blieb nicht ewig Besiegter: Man konnte römischer Bürger werden —',
        'als Soldat nach 25 Dienstjahren, als Stadt durch Verleihung. 212 n. Chr.',
        'erhielten fast alle freien Bewohner des Reiches das Bürgerrecht. Ein',
        'Nordafrikaner konnte Kaiser werden, ein Spanier ebenso. Das Reich war',
        'nicht durch Herkunft zusammengehalten, sondern durch Zugehörigkeit.',
        '',
        'Dazu kam etwas Unscheinbares: Frieden. Über rund zwei Jahrhunderte war',
        'es im Inneren weitgehend ruhig — die Römer nannten es „pax Romana",',
        'den römischen Frieden. Man konnte von Trier nach Alexandria reisen,',
        'ohne eine Grenze zu überschreiten, und überall mit denselben Münzen',
        'zahlen. Nicht wenige Menschen im Reich fanden das gut. Andere sahen',
        'darin vor allem die Ruhe, die auf eine Eroberung folgt.',
        '',
        '## Was Rom verändert hat',
        '',
        'Sprich Deutsch, und du sprichst römisch mit: Fenster, Mauer, Straße,',
        'Keller, Wein, Kirche — alles aus dem Lateinischen. Italienisch,',
        'Spanisch, Französisch, Portugiesisch und Rumänisch sind unmittelbar aus',
        'dem gesprochenen Latein hervorgegangen. Die Monate Juli und August',
        'tragen die Namen von Caesar und Augustus. Unser Kalender geht auf den',
        'römischen zurück. Und das Christentum, anfangs im Reich verfolgt, wurde',
        'schließlich seine Staatsreligion — und über die römischen Straßen und',
        'Städte zur prägenden Religion Europas.',
        '',
        '## Warum ging es zu Ende?',
        '',
        'Ein einzelnes Datum wird gern genannt: 476 n. Chr., als der letzte',
        'weströmische Kaiser abgesetzt wird. Ein Junge namens Romulus Augustulus',
        'gibt seine Insignien ab, und niemand macht viel Aufhebens darum. Kein',
        'Zeitgenosse hat an diesem Tag gedacht: „Jetzt ist die Antike vorbei."',
        '',
        'Der eigentliche Vorgang zog sich über Jahrhunderte, und die Erklärungen',
        'dafür widersprechen einander bis heute:',
        '',
        '- Das Reich war zu groß geworden, um von einer Stelle aus regiert zu',
        '  werden — es wurde in eine westliche und eine östliche Hälfte geteilt.',
        '- Kaiser wurden von ihren eigenen Truppen erhoben und gestürzt; in',
        '  einer Krisenzeit des 3. Jahrhunderts wechselte die Herrschaft im',
        '  Schnitt fast jährlich.',
        '- Seuchen und Missernten trafen die Bevölkerung, die Steuerlast wuchs,',
        '  das Geld verlor an Wert.',
        '- Von Norden und Osten drängten Völker über die Grenzen — mal als',
        '  Angreifer, mal als Flüchtende vor den Hunnen, mal als angeworbene',
        '  Soldaten. Am Ende wurde Rom von Verbänden verteidigt, die selbst',
        '  „Barbaren" waren.',
        '',
        'Und dann ist da noch die Frage, ob „Untergang" überhaupt das richtige',
        'Wort ist. Die östliche Reichshälfte mit der Hauptstadt Konstantinopel',
        'bestand noch fast tausend Jahre weiter — ihre Bewohner nannten sich',
        'selbstverständlich weiter Römer. Und im Westen lebten römisches Recht,',
        'römische Sprache und römische Kirche einfach unter neuen Herrschern',
        'weiter. Vielleicht ist Rom weniger gefallen als sich verwandelt.',
        '',
        '## Warum Europa diese Geschichte so erzählt',
        '',
        'Rom ist für Europa nie nur Vergangenheit gewesen, sondern immer auch',
        'Anspruch. Karl der Große ließ sich zum römischen Kaiser krönen. Das',
        'Heilige Römische Reich trug den Namen tausend Jahre lang im Titel. Die',
        'Zaren und die Kaiser nannten sich nach Caesar. Napoleon ließ sich als',
        'römischer Feldherr darstellen, und wer amerikanische Regierungsgebäude',
        'ansieht, sieht römische Säulen.',
        '',
        'Wer sich auf einen Vorfahren beruft, erzählt dessen Geschichte selten',
        'nüchtern. Deshalb klingt Rom in europäischen Büchern oft nach Ordnung,',
        'Recht und Fortschritt — und seltener nach dem, was Eroberung für die',
        'Eroberten bedeutet: zerstörte Städte, Zwangsabgaben, versklavte',
        'Menschen. Der römische Geschichtsschreiber Tacitus hat einem',
        'britannischen Anführer selbst diesen Satz in den Mund gelegt: „Sie',
        'machen eine Wüste und nennen es Frieden."',
        '',
        'Das ist der Punkt, an dem eine andere Sichtweise anfangen kann. Denn zur',
        'selben Zeit, am anderen Ende der Seidenstraße, gab es ein Reich, das',
        'genauso groß war und von dem in Europa kaum jemand spricht.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Chinesische Sichtweise',
      stimme: 'Hermes',
      text: [
        'Diese Sichtweise erzählt nicht aus Rom, sondern aus dem Osten — aus',
        'der Sicht der chinesischen Geschichtsschreibung, die Rom von weitem',
        'beobachtet hat. Auch sie ist nur eine Erzählung, aber eine mit',
        'anderen Fragen und anderen Wörtern.',
        '',
        '## Da Qin — das ferne Reich am Ende der Seidenstraße',
        '',
        'China wusste von Rom, lange bevor die Europäer von China wussten. In',
        'den kaiserlichen Annalen heißt das Römische Reich „Da Qin" — das',
        'große Qin. Die chinesischen Chronisten beschrieben es als ein Land',
        'am anderen Ende der Welt, reich an Glas und Gold, dessen Menschen im',
        'Handel als ehrlich galten. Hunderte Jahre lang lief die',
        'Seidenstraße: Seide, die in China gewebt wurde, trug römische',
        'Kaiser und Senatoren — in Rom war Seide so begehrt, dass manche sie',
        'mit Gold aufwogen und der Senat sogar über ein Trageverbot stritt.',
        '',
        'Rom war aus chinesischer Sicht also nie der Mittelpunkt der Welt,',
        'sondern der westliche Endpunkt eines Handelswegs. Das allein macht',
        'einen Unterschied: Die europäische Erzählung beginnt mit Rom und',
        'schaut nach außen. Die chinesische Erzählung schaut auf China — und',
        'Rom erscheint darin als ferner, respektierter Handelspartner am',
        'Horizont.',
        '',
        '## Zwei Reiche, ein Muster',
        '',
        'Zur selben Zeit, in der Rom aufstieg, wuchs am anderen Ende der',
        'Seidenstraße das Han-Reich heran — etwa gleich groß, etwa gleich',
        'bevölkert. Beide Reiche teilten die Welt fast in zwei Hälften, und',
        'beide kannten dieselben Probleme: riesige Entfernungen, viele',
        'Völker, Unruhen an den Grenzen. Die Han-Dynastie hielt ihr Reich mit',
        'Beamten, die nach Prüfungen ausgewählt wurden, mit Straßen und mit',
        'dem Handelsnetz der Seidenstraße — Ähnliches wie Rom, nur mit',
        'anderen Werkzeugen.',
        '',
        'Auch das Ende ähnelt sich: Das Han-Reich zerfiel im Jahr 220 n. Chr.,',
        'wenige Jahrzehnte bevor Rom in seine große Krise geriet. Aus',
        'chinesischer Sicht ist das kein Zufall, sondern ein vertrautes',
        'Muster. Die chinesische Geschichtsschreibung erzählt Herrschaft als',
        'Kreislauf: Eine Dynastie gründet ein Reich, bringt Ordnung und',
        'Blüte, wird dann schwächer — durch Korruption, Bürgerkriege,',
        'Missernten — und verliert schließlich das „Mandat des Himmels".',
        'Dann entsteht aus dem Chaos eine neue Dynastie, und der Kreislauf',
        'beginnt von vorn.',
        '',
        '## Das Mandat des Himmels',
        '',
        'Das „Mandat des Himmels" ist der Schlüssel zu dieser Sichtweise. Es',
        'besagt: Herrschaft ist nicht einfach Besitz, sondern geliehen — und',
        'sie bleibt nur, solange der Herrscher gut regiert. Wenn das Volk',
        'leidet, wenn Ämter käuflich werden, wenn Bauern ihre Steuern nicht',
        'mehr zahlen können, dann zieht der Himmel sein Mandat zurück, ob man',
        'es merkt oder nicht. Der Zusammenbruch kommt dann nicht plötzlich;',
        'er ist nur das Ende einer langen, sichtbaren Schwäche.',
        '',
        'Von hier aus betrachtet, war der Untergang Roms keine Tragödie und',
        'kein Rätsel, sondern ein vertrautes Kapitel: Ein großes Reich, das',
        'zu groß und zu teuer geworden war, dessen Kaiser sich gegenseitig',
        'bekämpften, dessen Ämter verkauft wurden — ein Reich, das die',
        'Zeichen des Mandatsverlusts erfüllte. Die chinesische Sicht fragt',
        'nicht so sehr „Warum fiel Rom?", sondern „Welche Zeichen waren',
        'schon lange vorher zu sehen?" — dieselbe Frage, die chinesische',
        'Chronisten auch an eigene Dynastien stellen.',
        '',
        '## Was diese Sicht anders macht',
        '',
        'Zwei Unterschiede fallen auf, wenn man die Erzählungen',
        'nebeneinanderlegt.',
        '',
        'Erstens: Europa erzählt Roms Ende als einen großen Einschnitt — das',
        'Ende einer Welt. Die chinesische Sicht kennt keinen einzelnen',
        'Untergang, sondern Muster: Reiche sterben, aber Zivilisationen',
        'machen weiter. Nach dem Han-Reich kamen die Drei Königreiche, dann',
        'neue Dynastien, die sich auf das Erbe des Han beriefen. Rom hat aus',
        'dieser Sicht nicht „die Welt beendet", sondern ist ein Reich unter',
        'vielen im Kreislauf der Reiche.',
        '',
        'Zweitens: Die chinesische Erzählung wundert sich darüber, wie sehr',
        'Europa Rom zu seinem eigenen Anfang macht. In China gilt die eigene',
        'Geschichte als die zentrale — das Han-Reich, die Seidenstraße,',
        'Papier und Seide. Dass Europa seine Wurzeln in Rom sucht, während',
        'das gleichzeitige China in europäischen Büchern lange kaum vorkam,',
        'ist aus dieser Sicht selbst eine Geschichte wert: Wer',
        'Weltgeschichte erzählt, wählt aus — und was gewählt wird, hängt',
        'davon ab, wer erzählt.',
        '',
        'Das ist keine Korrektur der europäischen Sicht. Es ist eine zweite',
        'Erzählung mit eigenen Fragen: Was wäre, wenn die Weltgeschichte',
        'nicht in Rom begänne, sondern an beiden Enden der Seidenstraße',
        'zugleich?',
      ].join('\n'),
    },
  ],

  synthese: [
    'Jetzt stehen zwei Sichtweisen nebeneinander — und schon sieht man, wie',
    'dieselbe Geschichte anders wird, je nachdem, woher man schaut.',
    '',
    '**Wo sie sich treffen:** Beide Erzählungen beschreiben Rom als ein',
    'Reich, das über ein riesiges Gebiet Ordnung und Stabilität brachte —',
    'die europäische mit Straßen, Recht und Bürgerrecht, die chinesische',
    'mit dem Blick von außen auf ein Reich, das seine Grenzen und seine',
    'Völker beherrschte. Beide kennen die Spannung zwischen Zentrum und',
    '„Barbaren" an den Rändern — die Germanen im Norden Roms, die Xiongnu',
    'im Norden Chinas. Und beide Erzählungen stammen von Menschen, die zu',
    'den Erben oder Nachfolgern der beschriebenen Reiche gehören: Sieger',
    'und Schreiber.',
    '',
    '**Wo sie auseinandergehen:** Die europäische Sicht macht Rom zum',
    'eigenen Anfang — Recht, Sprache, Kalender und Kirche führen auf Rom',
    'zurück, und sein Ende wird als großer Einschnitt erzählt. Die',
    'chinesische Sicht kennt Rom als fernen Handelspartner am Ende der',
    'Seidenstraße („Da Qin") und ordnet Aufstieg und Fall in ein',
    'vertrautes Muster ein: das Mandat des Himmels, das eine Dynastie',
    'erhält und verliert. Was für die eine Erzählung ein einmaliger',
    'Untergang ist, ist für die andere ein Kapitel in einem Kreislauf, den',
    'China selbst mehrfach durchlief.',
    '',
    '**Die Wortwahl verrät die Sichtweise:** „Untergang" oder „Wandel"?',
    '„Erbe" oder „ferner Handelspartner"? „Mittelpunkt der Welt" oder',
    '„Endpunkt eines Handelswegs"? Dieselben Ereignisse — andere Wörter,',
    'andere Geschichte. Genau hier beginnt dein eigenes Urteil: Welche',
    'Erzählung spricht dich mehr an, welche Fragen lässt sie offen — und',
    'welche Antwort würdest du einer dritten Person geben, die weder in',
    'Rom noch in China zu Hause ist?',
  ].join('\n'),

  urteil: {
    frage: 'Rom hat Straßen, Recht und Frieden gebracht — und zugleich Städte zerstört, Abgaben erzwungen und Menschen versklavt. War das Römische Reich deiner Meinung nach mehr Gewinn oder mehr Verlust für die Menschen, die darin lebten? Und kommt es darauf an, wen man fragt?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Nenne einfach zwei, drei Gründe für deine Sicht — und überlege, ob ein römischer Senator, eine Sklavin und ein germanischer Bauer dieselbe Antwort geben würden.',
  },

  quiz: [
    {
      frage: 'Stimmt es, dass Rom immer von Kaisern regiert wurde?',
      antworten: [
        'Ja, von der Gründung an bis zum Ende.',
        'Nein — vorher war Rom rund 500 Jahre lang eine Republik mit gewählten Beamten.',
        'Nein — Rom wurde immer von Priestern regiert.',
      ],
      richtig: 1,
      erklaerung: 'Die Kaiserzeit ist erst die zweite Hälfte der Geschichte. Davor regierten Senat und gewählte Beamte, die jeweils nur ein Jahr im Amt blieben — die Republik. Augustus wurde erst 27 v. Chr. der erste Kaiser.',
    },
    {
      frage: 'Wofür wurden die berühmten römischen Straßen in erster Linie gebaut?',
      antworten: [
        'Für Händler, damit der Handel blüht.',
        'Für Reisende und den Urlaubsverkehr.',
        'Fürs Heer, damit Truppen und Nachrichten schnell überallhin kommen.',
      ],
      richtig: 2,
      erklaerung: 'Zuerst war es militärische Notwendigkeit: Wer ein Riesenreich halten will, muss schnell Soldaten verschieben können. Dass Händler, Briefe und Ideen dieselben Straßen nutzten, war ein sehr wirkungsvoller Nebeneffekt.',
    },
    {
      frage: 'Konnte jemand römischer Bürger werden, der nicht in Rom geboren war?',
      antworten: [
        'Ja — das Bürgerrecht wurde verliehen, ab 212 n. Chr. sogar an fast alle freien Bewohner des Reiches.',
        'Nein, nur wer in der Stadt Rom geboren wurde.',
        'Nur Menschen aus Italien konnten es bekommen.',
      ],
      richtig: 0,
      erklaerung: 'Das war einer der klügsten Züge Roms: Besiegte konnten dazugehören statt ewig Besiegte zu bleiben. Soldaten bekamen das Bürgerrecht nach ihrer Dienstzeit, ganze Städte durch Verleihung — und es gab Kaiser aus Spanien und Nordafrika.',
    },
    {
      frage: 'Stimmt es, dass das Römische Reich im Jahr 476 n. Chr. unterging?',
      antworten: [
        'Ja, an diesem Tag war schlagartig alles vorbei.',
        'Nur halb — der letzte weströmische Kaiser wurde abgesetzt, die östliche Reichshälfte bestand aber noch fast 1000 Jahre weiter.',
        'Nein, das Reich existiert bis heute.',
      ],
      richtig: 1,
      erklaerung: '476 wurde der letzte Kaiser des Westens abgesetzt — ziemlich unspektakulär. Im Osten regierte Konstantinopel weiter bis 1453, und seine Bewohner nannten sich selbstverständlich weiterhin Römer. „Untergang" ist deshalb schon eine Deutung, keine reine Tatsache.',
    },
    {
      frage: 'Ist Latein mit dem Römischen Reich verschwunden?',
      antworten: [
        'Ja, niemand hat es danach mehr benutzt.',
        'Nein — daraus wurden Italienisch, Spanisch, Französisch und andere Sprachen; auch im Deutschen stecken viele lateinische Wörter.',
        'Nein, es wird heute noch überall in Europa als Alltagssprache gesprochen.',
      ],
      richtig: 1,
      erklaerung: 'Aus dem gesprochenen Latein sind die romanischen Sprachen geworden. Und wenn du „Fenster", „Mauer", „Straße" oder „Wein" sagst, benutzt du lateinische Wörter — sie sind über die Römer zu uns gekommen und einfach geblieben.',
    },
  ],
};

module.exports = roemischesReich;
