// Thema: Russland und der Westen (1991 bis heute).
//
// Stand: Runde 21 + Hermes-Pass. Drei Stimmen sind fertig: die Sicht des
// Westens (Stimme: Opus), die Sicht Russlands (Jelzin-Jahre, Putin — nach
// Betreiber-Vorgabe „wirklich objektiv", Stimme: Hermes) und die Sicht der
// Ukraine (Stimme: Hermes). Die Synthese führt alle drei zusammen.
//
// Neunzehntes Thema und zwölftes Kapitel des Neuzeit-Bogens
// (notizen/kapitel-planung.md, Kapitel 12). Es beginnt dort, wo „Die neue
// Weltordnung und der Kalte Krieg" endet: am 25. Dezember 1991, als die
// Sowjetunion aufhörte zu bestehen — und es übernimmt die Debatte, die jenes
// Kapitel ausdrücklich hierher verwiesen hat: die über die
// NATO-Osterweiterung und den „Geist" des Zwei-plus-Vier-Vertrags.
//
// Die Reihenfolge der Stimmen ist keine Rangfolge. Dass hier der Westen
// zuerst spricht, ergibt sich allein daraus, wer diese Runde übernommen hat;
// das steht auch so im Text, damit niemand die Reihenfolge als Wertung liest.
//
// TONE-REGEL (CLAUDE.md, Zusatzregel für sensible Themen). Dieses Kapitel ist
// das heikelste der ganzen App, weil es nicht abgeschlossen ist: Die Menschen,
// von denen es handelt, leben — in der Ukraine, in Russland, in Europa —, und
// während dieser Text entsteht, wird der Krieg geführt, von dem er erzählt.
// Deshalb gilt hier alles, was auch sonst gilt, nur strenger:
//
//   * Diese Perspektive benennt ihre unbequemen Stellen selbst: die
//     Doppeldeutigkeit der Zusagen von 1990, den Triumphalismus der
//     neunziger Jahre, die westliche Beteiligung an der Schocktherapie, den
//     Kosovokrieg 1999 und den Irakkrieg 2003 ohne UN-Mandat, den Gipfel von
//     Bukarest 2008 als Beschluss, der weder Schutz noch Absage war, und die
//     lange Verharmlosung der Entwicklung in Russland.
//   * Die Beweggründe der russischen Seite werden fair wiedergegeben — die
//     Demütigung der neunziger Jahre, die Sicherheitsinteressen, das Gefühl,
//     übergangen worden zu sein. Fair heißt: nachvollziehbar gemacht, nicht
//     gerechtfertigt. Beides auseinanderzuhalten ist die eigentliche Arbeit
//     dieses Kapitels.
//   * **Betreiber-Vorgabe „WIRKLICH OBJEKTIV":** Über Russland unter Putin
//     stehen beide Befunde nebeneinander und mit Zahlen — die Stabilisierung
//     und das Wachstum der 2000er Jahre UND die autoritäre Wende mitsamt den
//     Kriegen. Keine Dämonisierung, keine Beschönigung. Die App rechnet
//     nicht auf und verteilt keine Schuld — aber sie verschweigt auch nichts.
//   * Der russische Angriff auf die Ukraine vom 24. Februar 2022 wird beim
//     Namen genannt: ein groß angelegter Angriffskrieg, nicht ein „Konflikt".
//     Auch das gehört zur Objektivität — es ist der Befund der
//     UN-Vollversammlung vom 2. März 2022 (141 zu 5 Stimmen), nicht die
//     Meinung dieser App.
//   * Die Quizfragen bleiben Wissensfragen. Nach Schuld fragt diese App
//     nicht, hier so wenig wie in den achtzehn Kapiteln davor.
//
// Die Karte liegt in karten/russland-westen.js — drei Zustände (1999, 2014,
// 2022–2024). Warum der Ausschnitt so steht, wie er steht, und was er kostet,
// steht im Kopf der Kartendatei.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/russland-westen');

const russlandWesten = {
  id: 'russland-westen',
  titel: 'Russland und der Westen',
  epoche: '1991–heute',

  aufhaenger: {
    frage: 'Zwei Seiten, die 1945 zusammen gewonnen hatten und 1990 einander „Partner" nannten, stehen heute wieder gegeneinander — und ein Satz aus dem Februar 1990, den niemand aufgeschrieben hat, wird bis heute als Beweis geführt. Wie wird aus einer Partnerschaft binnen dreißig Jahren wieder eine Front?',
    text: [
      'Am 21. November 1990 unterschrieben in Paris zweiunddreißig europäische',
      'Staaten, dazu die USA und Kanada, ein Dokument, das den Kalten Krieg für',
      'beendet erklärte. „Das Zeitalter der Konfrontation und der Teilung',
      'Europas ist zu Ende gegangen", steht in der Charta von Paris. Die',
      'Unterschriften stammen von Michail Gorbatschow, George Bush, Helmut Kohl',
      'und François Mitterrand. Ein Jahr später gab es die Sowjetunion nicht',
      'mehr.',
      '',
      'Was danach kam, war zuerst Hoffnung. Russland wurde 1998 in den Kreis der',
      'sieben großen Industrienationen aufgenommen, die daraufhin G8 hießen.',
      '1997 unterzeichneten die NATO und Russland eine Grundakte, in der beide',
      'Seiten ausdrücklich erklärten, sie betrachteten einander nicht mehr als',
      'Gegner. 2002 setzten sie sich in einem gemeinsamen Rat an denselben',
      'Tisch. Russische und amerikanische Soldaten übten miteinander.',
      '',
      'Und dann war da die andere Hälfte derselben Jahre. Die russische',
      'Wirtschaftsleistung fiel zwischen 1991 und 1998 um rund vierzig Prozent —',
      'mehr als die amerikanische in der Weltwirtschaftskrise. Die Ersparnisse',
      'einer ganzen Generation lösten sich in der Inflation auf. Die',
      'Lebenserwartung russischer Männer sank binnen vier Jahren von 64 auf 57',
      'Jahre. Im August 1998 war der Staat zahlungsunfähig.',
      '',
      'Dazwischen liegt ein Satz. Am 9. Februar 1990 sagte der amerikanische',
      'Außenminister James Baker im Kreml zu Gorbatschow, die NATO werde sich',
      '„keinen Zoll nach Osten" ausdehnen. Er sagte es im Gespräch über die',
      'deutsche Vereinigung, es wurde nie ein Vertrag daraus, und ob er damit',
      'Polen und die baltischen Staaten meinte oder nur Ostdeutschland, ist bis',
      'heute umstritten. Dieser eine Satz steht bis heute in jeder Debatte über',
      'Russland und den Westen — bei den einen als Beweis für einen',
      'Vertrauensbruch, bei den anderen als Beleg dafür, wie unzuverlässig',
      'Erinnerung ist.',
      '',
      'Dieses Kapitel beginnt mit der Sicht des Westens. Das ist eine von',
      'mehreren Stimmen, nicht die richtige — welche zuerst spricht, hängt',
      'davon ab, wer diese Runde geschrieben hat, und ist keine Rangfolge.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'Die Sicht des Westens — USA, NATO und Europa',
      stimme: 'Opus',
      text: [
        'Diese Stimme erzählt aus Washington, Brüssel, Berlin, Warschau und',
        'Tallinn: aus den Hauptstädten, in denen die Entscheidungen über die',
        'NATO fielen, aber auch aus den Ländern, die 1999 und 2004 unbedingt',
        'hineinwollten und dafür eigene Gründe hatten.',
        '',
        'Sie ist gleichwertig mit den anderen Stimmen dieses Kapitels. Dass sie',
        'hier zuerst steht, ist keine Rangfolge — es liegt nur daran, wer diese',
        'Runde übernommen hat. Und sie hat eine Aufgabe, die schwerer ist als in',
        'allen Kapiteln davor: Dieses Kapitel ist nicht abgeschlossen. Während',
        'diese Zeilen entstehen, wird der Krieg geführt, von dem sie handeln.',
        'Wer über eine laufende Geschichte schreibt, ist selbst Partei — und der',
        'einzige ehrliche Umgang damit ist, das zu sagen und trotzdem so genau',
        'zu sein, wie es geht.',
        '',
        '## 1991: die Hoffnung, und was sie trug',
        '',
        'Der Westen hat das Ende der Sowjetunion nicht als Sieg über Russland',
        'verstanden — jedenfalls nicht in den offiziellen Dokumenten. Die Charta',
        'von Paris vom 21. November 1990 spricht von einem gemeinsamen Europa,',
        'nicht von Gewinnern und Verlierern. Und sie enthält einen Satz, der in',
        'diesem Kapitel noch dreimal wiederkommt: Jeder Staat hat das Recht,',
        'seine Bündnisse frei zu wählen — oder keinem anzugehören. Die',
        'Sowjetunion hat das mit unterschrieben, Russland hat es 1999 in der',
        'Charta von Istanbul erneut bestätigt.',
        '',
        'Was daraus folgte, war eine Reihe von Einladungen. 1994 trat Russland',
        'der „Partnerschaft für den Frieden" bei, dem Programm, mit dem die NATO',
        'ihre ehemaligen Gegner an sich band. 1997 unterzeichneten beide Seiten',
        'die **NATO-Russland-Grundakte**: Sie erklärten darin, einander nicht',
        'mehr als Gegner zu betrachten, und die NATO sagte zu, in den neuen',
        'Mitgliedstaaten keine Atomwaffen und keine dauerhaft stationierten',
        'großen Kampfverbände aufzustellen — eine Zusage, an die sie sich bis',
        '2014 gehalten hat. 1998 wurde aus der G7 die **G8**. 2002 entstand der',
        '**NATO-Russland-Rat**, in dem Russland nicht als Gast saß, sondern als',
        'gleichberechtigtes Mitglied. 2012 trat Russland der',
        'Welthandelsorganisation bei — mit westlicher Unterstützung.',
        '',
        'Nach dem 11. September 2001 war Wladimir Putin der erste ausländische',
        'Staatschef, der George W. Bush anrief. Russland öffnete den Luftraum',
        'für den Nachschub nach Afghanistan und half beim Aufbau von',
        'Stützpunkten in Zentralasien. Am 25. September 2001 sprach Putin auf',
        'Deutsch vor dem Deutschen Bundestag und bekam stehenden Beifall. Wer',
        'heute erzählt, der Westen habe Russland von Anfang an ausgeschlossen,',
        'muss diese Jahre erklären.',
        '',
        '## Die neunziger Jahre: was der Westen sah — und was er nicht sehen wollte',
        '',
        'Und doch beginnt hier auch die erste unbequeme Stelle dieser',
        'Erzählung, und sie ist groß. Der Westen hat den russischen Umbau der',
        'neunziger Jahre nicht nur beobachtet, er hat ihn beraten und',
        'mitfinanziert.',
        '',
        'Die Preisfreigabe vom Januar 1992 — die „Schocktherapie" — sollte',
        'schnell gehen, weil man fürchtete, ein langsamer Umbau werde politisch',
        'rückgängig gemacht. Die Folge war eine Inflation von über',
        '2 500 Prozent im ersten Jahr. Wer sein Leben lang gespart hatte, war',
        'binnen Monaten arm. Die Massenprivatisierung über Voucher-Scheine gab',
        'jedem Bürger ein Stück Staatsvermögen; die meisten verkauften es für',
        'ein paar Dollar, weil sie Geld brauchten. 1995/96 kam das Verfahren',
        '„Aktien gegen Kredite": Banken liehen dem Staat Geld gegen Anteile an',
        'den größten Rohstoffunternehmen — und als der Staat nicht zahlte,',
        'behielten sie die Anteile. So entstanden in wenigen Jahren die',
        'Oligarchen. Am 17. August 1998 erklärte Russland den Staatsbankrott.',
        '',
        'Westliche Berater, der Internationale Währungsfonds und westliche',
        'Regierungen haben diesen Weg empfohlen, gestützt und finanziert. Im',
        'März 1996, vier Monate vor der Präsidentenwahl, gab der IWF Russland',
        'einen Kredit über 10,2 Milliarden Dollar; Boris Jelzin lag in Umfragen',
        'bei wenigen Prozent und gewann. Man kann darüber streiten, ob es',
        'Alternativen gab — die Fachleute streiten bis heute. Aber diese Stimme',
        'kann nicht so tun, als sei das russische Elend der neunziger Jahre eine',
        'rein russische Angelegenheit gewesen. Es war die Zeit, in der Millionen',
        'Menschen das Wort „Demokratie" mit leeren Regalen, ausbleibenden',
        'Löhnen und einer Handvoll neuer Milliardäre verbanden. Wer verstehen',
        'will, warum in Russland später Ordnung mehr galt als Freiheit, findet',
        'die Antwort hier.',
        '',
        'Dazu kam der Ton. „Wir haben gewonnen" war in den neunziger Jahren im',
        'Westen ein üblicher Satz. Francis Fukuyamas Formel vom „Ende der',
        'Geschichte" wurde so gelesen, als sei nur noch abzuwarten, bis alle',
        'anderen so würden wie wir. Dieser **Triumphalismus** war nicht die',
        'offizielle Politik, aber er war die Stimmung — und in Moskau hörte man',
        'ihn genau. Eine Großmacht, die gerade ihr halbes Staatsgebiet, ihre',
        'Wirtschaft und ihre Rolle in der Welt verloren hatte, wurde behandelt',
        'wie ein Schüler, dem man Nachhilfe gibt. Das war ein Fehler, und er',
        'hat mehr gekostet als viele Verträge.',
        '',
        '## Tschetschenien: die Kriege, über die der Westen hinwegsah',
        '',
        'Im Dezember 1994 marschierte die russische Armee in Tschetschenien ein,',
        'das sich für unabhängig erklärt hatte. Grosny wurde in einem',
        'Winterfeldzug zerschossen; die Schätzungen der zivilen Toten dieses',
        'ersten Krieges reichen von 30 000 bis über 50 000. 1996 endete er mit',
        'einem Waffenstillstand, der die Frage offenließ. 1999 begann der',
        'zweite Krieg, diesmal unter dem neuen Ministerpräsidenten Wladimir',
        'Putin; die Vereinten Nationen nannten Grosny 2003 „die zerstörteste',
        'Stadt der Erde".',
        '',
        'Was tat der Westen? Er protestierte in Erklärungen und machte im',
        'Übrigen weiter. Jelzin blieb der Partner, den man stützte, weil man',
        'fürchtete, was nach ihm käme. Und beim zweiten Krieg kam ein zweites',
        'Motiv hinzu: Nach dem 11. September 2001 ordnete auch der Westen',
        'Tschetschenien unter „Terrorbekämpfung" ein. Es gab auf russischer',
        'Seite tatsächlich Anschläge und Geiselnahmen mit hunderten Toten —',
        'Moskau 2002, Beslan 2004 —, und es gab auf russischer Seite ein',
        'Vorgehen gegen die Zivilbevölkerung, das der Europäische',
        'Gerichtshof für Menschenrechte in über zweihundert Urteilen',
        'verurteilt hat. Beides ist wahr. Der Westen hat das zweite lange',
        'leiser gesagt als das erste, und das gehört in diese Erzählung.',
        '',
        '## Das Herzstück: die NATO-Osterweiterung',
        '',
        'Hier liegt der Streit, um den es in diesem Kapitel wirklich geht. Er',
        'lässt sich in vier Fragen zerlegen, und diese Stimme beantwortet alle',
        'vier — auch die, die ihr nicht gefallen.',
        '',
        '### Erstens: Was wurde 1990 gesagt?',
        '',
        'Am 9. Februar 1990 sagte US-Außenminister **James Baker** zu',
        'Gorbatschow, wenn ein vereintes Deutschland in der NATO bleibe, dann',
        'werde die NATO ihren Zuständigkeitsbereich „keinen Zoll nach Osten"',
        'ausdehnen — im Original „not one inch eastward". Am selben Tag und in',
        'den Wochen darauf sagten Ähnliches: Bundeskanzler Helmut Kohl,',
        'Außenminister Hans-Dietrich Genscher (in seiner Tutzinger Rede vom',
        '31. Januar 1990), der britische Außenminister Douglas Hurd und der',
        'NATO-Generalsekretär Manfred Wörner. Diese Zusagen sind kein Gerücht:',
        'Die Gesprächsprotokolle sind freigegeben und seit 2017 im National',
        'Security Archive der George Washington University öffentlich',
        'nachlesbar.',
        '',
        '### Zweitens: Wurde daraus ein Vertrag?',
        '',
        'Nein. Es gibt kein Dokument, in dem sich die NATO verpflichtet, keine',
        'neuen Mitglieder aufzunehmen. Der **Zwei-plus-Vier-Vertrag** vom',
        '12. September 1990, der die deutsche Vereinigung völkerrechtlich',
        'regelte, sagt in **Artikel 6** ausdrücklich das Gegenteil: „Das Recht',
        'des vereinten Deutschland, Bündnissen mit allen sich daraus ergebenden',
        'Rechten und Pflichten anzugehören, wird von diesem Vertrag nicht',
        'berührt." Artikel 5 regelt, was auf dem Gebiet der früheren DDR nicht',
        'stationiert werden darf — keine Atomwaffen, keine ausländischen',
        'Truppen —, und diese Beschränkung gilt bis heute. Über andere Länder',
        'steht im Vertrag nichts, weil andere Länder nicht sein Gegenstand',
        'waren.',
        '',
        'Auch Gorbatschow selbst hat das später bestätigt. 2014 sagte er in',
        'einem Interview, das Thema „NATO-Erweiterung" sei damals überhaupt',
        'nicht verhandelt worden — es sei in jenen Jahren gar nicht',
        'aufgekommen, weil der Warschauer Pakt noch bestand. Im selben Atemzug',
        'fügte er hinzu, der **Geist** der damaligen Zusagen sei später',
        'verletzt worden. Beide Hälften dieses Satzes gehören zusammen, und',
        'beide Seiten zitieren gewöhnlich nur eine davon.',
        '',
        '### Drittens: Warum kamen die neuen Mitglieder trotzdem?',
        '',
        'Weil sie es wollten, und zwar sehr. Polen, Tschechien und Ungarn',
        'traten am 12. März 1999 bei, sieben weitere Staaten am 29. März 2004',
        '— darunter Estland, Lettland und Litauen, die 1940 von der',
        'Sowjetunion annektiert worden waren. In jedem dieser Länder waren es',
        'gewählte Parlamente und Regierungen, die den Antrag stellten; in',
        'mehreren gab es dazu Volksabstimmungen mit deutlichen Mehrheiten. Der',
        'Beitritt war nicht etwas, das der Westen diesen Ländern brachte,',
        'sondern etwas, worum sie jahrelang gebeten hatten — und was ihnen',
        'anfangs verweigert wurde, aus Rücksicht auf Moskau.',
        '',
        'Aus westlicher Sicht folgt daraus die entscheidende Unterscheidung:',
        'Ein Bündnis, dem man beitreten kann, ist etwas anderes als ein Block,',
        'in den man eingeordnet wird. 1945 hat niemand die Polen gefragt. 1999',
        'hat sie niemand gezwungen. Und genau das ist das Recht, das die Charta',
        'von Paris jedem Staat zuspricht — auch dem, dessen Nachbar das nicht',
        'gern sieht.',
        '',
        '### Viertens: Was hat der Westen dabei falsch gemacht?',
        '',
        'Drei Dinge, und sie stehen hier, weil sie hierher gehören.',
        '',
        'Erstens die **Doppeldeutigkeit von 1990**. Man hat Sätze gesagt, die',
        'beruhigen sollten, ohne sie zu Papier zu bringen — und später auf das',
        'Papier verwiesen. Juristisch ist das sauber. Politisch ist es die',
        'Sorte Geschick, die einen Preis hat, und der Preis war Vertrauen.',
        '',
        'Zweitens die **Warnungen aus den eigenen Reihen**, die man überging.',
        'George F. Kennan, der Vater der Eindämmungspolitik, nannte die',
        'Erweiterung 1997 in der New York Times „den verhängnisvollsten Fehler',
        'der amerikanischen Politik in der gesamten Nachkriegszeit". Der',
        'spätere CIA-Direktor William Burns schrieb 2008 als Botschafter in',
        'Moskau ein Telegramm mit dem Titel „Njet heißt njet": Eine',
        'NATO-Mitgliedschaft der Ukraine sei für die gesamte russische Elite',
        'eine rote Linie, nicht nur für Putin. Man kann beide für falsch',
        'halten. Aber man kann nicht behaupten, niemand habe es gesagt.',
        '',
        'Drittens **Bukarest 2008**. Auf dem Gipfel vom 3. April 2008 erklärte',
        'die NATO, die Ukraine und Georgien „werden Mitglieder der NATO',
        'werden" — beschloss aber keinen Fahrplan dorthin, weil Deutschland',
        'und Frankreich dagegen waren. Das war die schlechteste aller',
        'Möglichkeiten: eine Ankündigung, die Moskau als Bedrohung las, ohne',
        'jeden Schutz für die beiden Länder, um die es ging. Vier Monate',
        'später führte Russland Krieg in Georgien; sechs Jahre später auf der',
        'Krim. Wer diese Reihenfolge betrachtet, muss den Gipfel von Bukarest',
        'ernst nehmen, ohne ihn zur Ursache zu erklären — beides wäre zu',
        'einfach.',
        '',
        '### Und die russische Sicht?',
        '',
        'Sie gehört hierher, auch in diese Perspektive, und sie lautet',
        'ungefähr so: Man hat uns 1990 mündlich etwas zugesagt, uns dann auf',
        'das Kleingedruckte verwiesen und in fünfundzwanzig Jahren ein',
        'Militärbündnis von der Elbe bis an unsere Grenze geführt — während wir',
        'zu schwach waren, um Nein zu sagen. Aus dieser Sicht ist nicht der',
        'einzelne Beitritt der Punkt, sondern das Muster: Jedes Mal, wenn',
        'Russland schwach war, rückte die Linie näher.',
        '',
        'Diese Stimme hält dagegen, was oben steht — Verträge, Selbstbestimmung,',
        'die Grundakte von 1997, an die sich die NATO siebzehn Jahre lang',
        'gehalten hat. Aber sie hält es dagegen, ohne die andere Wahrnehmung',
        'für erfunden zu erklären. Eine Wahrnehmung, die auf beiden Seiten des',
        'Kremls von Leuten geteilt wird, die sonst wenig teilen, ist keine',
        'Propagandaerfindung. Sie erklärt nur nicht alles: Wer Grenzen ändern',
        'lässt, weil er sich bedroht fühlt, macht aus einem Gefühl ein Recht,',
        'das im Völkerrecht nicht vorgesehen ist.',
        '',
        'Und damit das nicht missverstanden wird: Fair wiedergeben heißt',
        'nachvollziehbar machen, nicht rechtfertigen. Das ist zweierlei, und',
        'die Unterscheidung sauber zu halten ist die eigentliche Arbeit dieses',
        'Kapitels — an ihr entscheidet sich, ob man verstehen kann, ohne',
        'einverstanden zu sein.',
        '',
        '## Russland unter Putin — beide Hälften, mit Zahlen',
        '',
        'Am 31. Dezember 1999 übergab Jelzin die Amtsgeschäfte an Wladimir',
        'Putin. Was dann kam, wird im Westen oft nur zur Hälfte erzählt.',
        'Deshalb stehen hier beide Hälften nebeneinander — nicht, um sie',
        'gegeneinander aufzurechnen, sondern weil man ohne die erste die',
        'zweite nicht versteht.',
        '',
        '### Was besser wurde (2000–2008)',
        '',
        'Die Wirtschaft wuchs zwischen 1999 und 2008 im Schnitt um rund sieben',
        'Prozent im Jahr. Die verfügbaren Realeinkommen haben sich in diesem',
        'Jahrzehnt etwa verdoppelt, die Armutsquote fiel von rund 29 Prozent',
        '(2000) auf etwa 13 Prozent (2008). Renten und Löhne wurden wieder',
        'pünktlich gezahlt — was in den neunziger Jahren keineswegs',
        'selbstverständlich gewesen war. Der Staat funktionierte wieder:',
        'Steuern wurden eingetrieben (Einführung einer Flat Tax von 13 Prozent',
        '2001), die Auslandsschulden wurden vorzeitig zurückgezahlt, die',
        'Zentralbank legte Reserven an. Die Zahl der Morde und die',
        'Alkoholsterblichkeit gingen deutlich zurück, die Lebenserwartung',
        'stieg wieder.',
        '',
        'Ein großer Teil davon hing am **Ölpreis**: Ein Fass Rohöl der Sorte',
        'Urals kostete 1998 rund 12 Dollar und im Sommer 2008 fast 140. Ohne',
        'diesen Zufluss wäre vieles nicht möglich gewesen, und das sagen auch',
        'russische Ökonomen. Aber es war eben nicht nur der Ölpreis, und es',
        'war für die Menschen, die es erlebten, sehr real. Wer die 2000er Jahre',
        'in Russland ausschließlich als Beginn einer Diktatur beschreibt,',
        'beschreibt nicht, was die Mehrheit erlebt hat — und versteht deshalb',
        'auch die Zustimmung nicht, die daraus erwuchs.',
        '',
        '### Was sich verengte (2000–heute)',
        '',
        'Im selben Jahrzehnt und danach verschwand Stück für Stück, was eine',
        'Demokratie ausmacht. Die Reihe ist lang, und sie ist belegt:',
        '',
        '- **Die Medien.** Im April 2001 übernahm der staatsnahe',
        '  Gazprom-Konzern den letzten großen unabhängigen Fernsehsender NTW.',
        '  Die reichweitenstarken Kanäle sind seither staatlich kontrolliert.',
        '- **Die Wirtschaft.** Im Oktober 2003 wurde Michail Chodorkowski,',
        '  damals der reichste Mann des Landes und politisch aktiv, verhaftet;',
        '  sein Ölkonzern Jukos wurde zerschlagen und ging an einen',
        '  Staatskonzern.',
        '- **Der Föderalismus.** 2004, nach dem Geiseldrama von Beslan, wurde',
        '  die Direktwahl der Gouverneure abgeschafft; sie wurden fortan aus',
        '  Moskau ernannt.',
        '- **Die Kritiker.** Die Journalistin Anna Politkowskaja, die über',
        '  Tschetschenien berichtete, wurde am 7. Oktober 2006 in Moskau',
        '  erschossen. Der frühere Geheimdienstoffizier Alexander Litwinenko',
        '  starb im November 2006 in London an einer Vergiftung mit Polonium',
        '  210; eine britische Untersuchung kam 2016 zu dem Schluss, die Tat',
        '  sei „wahrscheinlich" auf höchster Ebene gebilligt worden. Der',
        '  Oppositionspolitiker Boris Nemzow wurde am 27. Februar 2015 in',
        '  Sichtweite des Kremls erschossen. Alexej Nawalny wurde im August',
        '  2020 mit dem Nervenkampfstoff Nowitschok vergiftet, in Berlin',
        '  behandelt, kehrte zurück, wurde inhaftiert und starb am 16. Februar',
        '  2024 in einem Straflager nördlich des Polarkreises.',
        '- **Das Recht.** Seit 2012 können Organisationen als „ausländische',
        '  Agenten" eingestuft werden; die Vorschrift wurde mehrfach',
        '  verschärft und trifft heute auch Einzelpersonen. 2020 wurde die',
        '  Verfassung so geändert, dass Putin bis 2036 kandidieren kann. Seit',
        '  März 2022 steht auf die Bezeichnung des Krieges als Krieg eine',
        '  Freiheitsstrafe.',
        '',
        'Diese beiden Listen stehen nebeneinander, und keine hebt die andere',
        'auf. Der Aufschwung der 2000er Jahre war echt. Die Verengung war es',
        'auch. Wer nur das eine erzählt, erzählt Werbung; wer nur das andere',
        'erzählt, erzählt eine Karikatur.',
        '',
        '## Die Kriege',
        '',
        '**Georgien, August 2008.** Der Streit um Südossetien und Abchasien war',
        'alt. In der Nacht zum 8. August 2008 beschoss die georgische Armee',
        'Zchinwali, russische Truppen rückten ein und stießen weit über die',
        'umstrittenen Gebiete hinaus vor. Der von der EU eingesetzte',
        'Untersuchungsbericht unter Heidi Tagliavini kam 2009 zu einem',
        'unbequemen Doppelbefund: Der georgische Angriff sei völkerrechtlich',
        'nicht zu rechtfertigen gewesen — und die russische Reaktion weit über',
        'das Verhältnismäßige hinausgegangen, vorbereitet durch Jahre der',
        'Provokation. Diese Stimme gibt den Bericht so wieder, wie er ist, auch',
        'wenn seine erste Hälfte der westlichen Erzählung widerspricht.',
        '',
        '**Krim und Donbass, 2014.** Nach dem Sturz von Präsident Janukowytsch',
        'besetzten Ende Februar 2014 Soldaten ohne Hoheitsabzeichen die Krim;',
        'Putin bestätigte wenige Wochen später, dass es russische Soldaten',
        'waren. Ein Referendum unter Besatzung am 16. März wurde international',
        'nicht anerkannt; am 27. März erklärte die UN-Vollversammlung die',
        'Annexion mit 100 gegen 11 Stimmen für ungültig. Im Frühjahr begann im',
        'Donbass der Krieg, an dem russisches Militär beteiligt war, auch wenn',
        'Moskau das jahrelang bestritt. Am 17. Juli 2014 wurde das',
        'Passagierflugzeug MH17 mit 298 Menschen an Bord über dem Donbass',
        'abgeschossen; ein niederländisches Gericht verurteilte 2022 drei',
        'Beteiligte in Abwesenheit. Die Abkommen von Minsk (September 2014 und',
        'Februar 2015) froren den Krieg ein, ohne ihn zu beenden; sie wurden',
        'von keiner Seite vollständig umgesetzt.',
        '',
        '**Der 24. Februar 2022.** An diesem Tag begann Russland einen groß',
        'angelegten Angriffskrieg gegen die Ukraine — aus dem Osten, aus dem',
        'Süden und aus dem Norden über belarussisches Gebiet auf Kyjiw. Es ist',
        'wichtig, das genau so zu benennen und nicht „Konflikt" zu sagen: Ein',
        'Konflikt hat zwei Seiten, die etwas beginnen; hier hat eine Seite eine',
        'Grenze überschritten. Am 2. März 2022 verurteilte die',
        'UN-Vollversammlung den Angriff mit 141 gegen 5 Stimmen und forderte',
        'den Abzug. Der Vorstoß auf Kyjiw scheiterte und wurde Anfang April',
        'abgebrochen; in den befreiten Orten, unter ihnen Butscha, fanden',
        'Ermittler zahlreiche getötete Zivilisten. Der Internationale',
        'Strafgerichtshof erließ im März 2023 einen Haftbefehl gegen Putin',
        'wegen der Verschleppung ukrainischer Kinder.',
        '',
        'Und die Folge, die niemand geplant hatte: **Finnland trat am 4. April',
        '2023 der NATO bei, Schweden am 7. März 2024.** Finnland hatte seit',
        '1945 an der Bündnisfreiheit festgehalten, Schweden seit 1814. Vor dem',
        'Februar 2022 waren in Finnland rund 20 bis 25 Prozent für einen',
        'Beitritt, wenige Wochen danach über 70. Die Landgrenze der NATO zu',
        'Russland hat sich dadurch mehr als verdoppelt — genau das, was der',
        'Krieg nach der eigenen Begründung verhindern sollte.',
        '',
        '## Die unbequemste Stelle: das eigene Maß',
        '',
        'Diese Perspektive beruft sich auf eine Regel — Grenzen ändert man',
        'nicht mit Gewalt. Dann muss sie sagen, wo sie selbst dagegen verstoßen',
        'hat.',
        '',
        '**Kosovo 1999.** Die NATO bombardierte Jugoslawien 78 Tage lang ohne',
        'Mandat des UN-Sicherheitsrats. Der Anlass — die Vertreibung der',
        'albanischen Bevölkerung — war real; die Rechtsgrundlage fehlte. 2008',
        'erklärte das Kosovo seine Unabhängigkeit, die der Westen anerkannte',
        'und Russland nicht. Moskau führt diesen Fall seither in jeder Debatte',
        'an, und der Verweis ist nicht abwegig.',
        '',
        '**Irak 2003.** Die USA und ihre Verbündeten führten einen Krieg gegen',
        'einen Staat, der sie nicht angegriffen hatte, ohne UN-Mandat und mit',
        'einer Begründung — Massenvernichtungswaffen —, die sich als falsch',
        'erwies. Wer das nicht benennt, kann über Völkerrecht nicht',
        'glaubwürdig sprechen.',
        '',
        '**Libyen 2011.** Der Sicherheitsrat erlaubte den Schutz der',
        'Zivilbevölkerung; die Militäraktion endete mit dem Sturz des Regimes.',
        'Russland und China, die sich enthalten hatten, sahen sich getäuscht —',
        'und haben seither in keinem vergleichbaren Fall mehr zugestimmt.',
        '',
        '**Und das Geschäft.** Deutschland bezog vor 2022 über die Hälfte seines',
        'Erdgases aus Russland und baute mit Nord Stream 1 und 2 die',
        'Abhängigkeit weiter aus — gegen die ausdrücklichen Warnungen Polens,',
        'der baltischen Staaten und der USA. „Wandel durch Handel" hieß die',
        'Formel. Nach 2008 und nach 2014 hätte man sie überprüfen können. Man',
        'tat es nicht, weil es teuer gewesen wäre. Als Putin am 10. Februar',
        '2007 auf der Münchner Sicherheitskonferenz eine Rede hielt, in der er',
        'im Klartext sagte, wie er die westliche Politik sah, galt das in',
        'Berlin und Paris als schlechte Laune. Es war eine Ankündigung.',
        '',
        '## Was der Westen heute tut — und was das kostet',
        '',
        'Seit 2022 unterstützen die USA, die EU und weitere Staaten die Ukraine',
        'mit Waffen, Geld und Aufnahme von Geflüchteten, und sie haben gegen',
        'Russland die umfangreichsten Sanktionen der Nachkriegszeit verhängt.',
        'NATO-Soldaten kämpfen nicht mit; die Allianz hat von Anfang an',
        'erklärt, dass sie das nicht tut, weil ein direkter Krieg zwischen',
        'Atommächten etwas anderes wäre.',
        '',
        'Auch hier gehört die Gegenrechnung dazu. Die Sanktionen haben die',
        'russische Wirtschaft nicht zum Einsturz gebracht; sie hat sich, unter',
        'Kosten, umgestellt. Ein großer Teil der Welt — Indien, China, Brasilien,',
        'Südafrika und die meisten afrikanischen Staaten — trägt sie nicht mit',
        'und wirft dem Westen vor, hier plötzlich Grundsätze zu entdecken, die',
        'er anderswo nicht anwendet. Diese Kritik ist unbequem, und sie ist',
        'nicht unbegründet. Und in Europa selbst ist die Frage offen, wie lange',
        'Gesellschaften eine Unterstützung tragen, die Geld kostet und kein',
        'absehbares Ende hat.',
        '',
        '## Was diese Sicht nicht sehen kann',
        '',
        'Sie sieht die neunziger Jahre von außen — als Übergangszeit, nicht als',
        'Zusammenbruch der eigenen Welt. Sie sieht die Erweiterung als Summe',
        'freier Entscheidungen, nicht als Linie, die näher rückt. Sie sieht die',
        'russische Erzählung als Erzählung und die eigene als Beschreibung, und',
        'genau das ist der blinde Fleck, vor dem diese App in jedem Kapitel',
        'warnt.',
        '',
        'Deshalb steht diese Stimme hier nicht allein. Die **Sicht Russlands** —',
        'die Jelzin-Jahre von innen, die Stabilisierung, die Einkreisung, die',
        'eigene Begründung der Kriege — schreibt Hermes; möglicherweise kommt',
        'eine dritte Stimme dazu, die der Ukraine, die in diesem Kapitel bisher',
        'vor allem vorkommt, statt zu sprechen. Erst danach führt die Synthese',
        'zusammen, was zusammengehört.',
      ].join('\n'),
    },
    {
      id: 'russland-sicht',
      name: 'Die Sicht Russlands — die neunziger Jahre und Putin',
      stimme: 'Hermes',
      text: [
        'Diese Stimme erzählt aus Moskau: aus der Welt, die am 25. Dezember',
        '1991 mit der Sowjetunion zusammenbrach, und aus dem Russland, das',
        'danach entstand. Sie ist gleichwertig mit der Stimme des Westens —',
        'dass sie hier zuerst stand, war nur die Reihenfolge, in der',
        'geschrieben wurde.',
        '',
        '## Die neunziger Jahre — die große Demütigung',
        '',
        'Wer die neunziger Jahre in Russland erlebt hat, erinnert sie als',
        'Zeit des Zusammenbruchs: Die Preise stiegen ins Unermessliche, die',
        'Ersparnisse eines Lebens waren in wenigen Monaten wertlos,',
        'Gehälter und Renten kamen monatelang nicht, die Lebenserwartung',
        'fiel, und der Staat schien nicht mehr zu existieren. Die',
        '**Hyperinflation** der Jahre 1992 bis 1995 fraß die Ersparnisse',
        'der ganzen Bevölkerung. In diese Leere traten die **Oligarchen**:',
        'wenige Männer, die in der Privatisierungswelle die größten',
        'Betriebe des Landes für einen Bruchteil ihres Wertes übernahmen.',
        'Die „Schocktherapie" war eine westliche Empfehlung, und diese',
        'Stimme sagt das ohne Häme: Der Westen meinte es gut und hatte',
        'keine Ahnung, was er anrichtete.',
        '',
        '1998 platzte die Blase: die **Rubelkrise** — der Staat konnte',
        'seine Schulden nicht mehr zahlen, die Banken brachen zusammen,',
        'wieder verloren Millionen ihre Ersparnisse. Und in diese Zeit',
        'fiel der erste **Tschetschenienkrieg** (1994–1996), ein',
        'demütigender, brutaler Krieg, den Russland verlor. Wer diese',
        'Jahre erlebte, erlebte Scham. Als der Westen die neunziger Jahre',
        'als „Triumph der Freiheit" feierte, erlebte Russland sie als',
        'nationales Trauma — das ist die **Bruchstelle**, an der diese',
        'Stimme beginnt.',
        '',
        '## Putin — die Wiederherstellung von Ordnung',
        '',
        'Wladimir Putin trat 1999/2000 in diese Welt ein — und die',
        'Betreiber-Vorgabe für diese Stimme lautet: **wirklich objektiv**.',
        'Also steht beides hier, ohne Dämonisierung und ohne Beschönigung.',
        '',
        '**Was Putin für Russland getan hat:** Er beendete die Zeit, in',
        'der der Staat nicht mehr funktionierte. Die Renten wurden wieder',
        'ausgezahlt und stiegen, die Gehälter kamen pünktlich, die',
        '**Wirtschaft wuchs** — zwischen 2000 und 2008 um durchschnittlich',
        'rund sieben Prozent im Jahr, getragen vom Ölpreis, aber auch von',
        'einer Politik, die das Vertrauen in die eigene Währung und in',
        'den Staat zurückbrachte. Die Oligarchen wurden zurückgedrängt,',
        'die „Vertikale der Macht" stellte die Ordnung wieder her, der',
        'zweite Tschetschenienkrieg endete mit einer harten Befriedung.',
        'Für viele Russen war Putin der Mann, der die Demütigung der',
        'neunziger Jahre beendete — seine Zustimmung war über Jahre hinweg',
        'sehr hoch, und das war keine erzwungene Zustimmung, sondern der',
        'Dank für gelebte Stabilität. Diese Leistung ist echt, und diese',
        'Stimme nennt sie beim Namen.',
        '',
        '**Und was Putin dafür nahm:** Die Medien wurden gleichgeschaltet —',
        'der unabhängige Sender NTV wurde 2001 zerschlagen. Die Oligarchen',
        'wurden nicht nur zurückgedrängt, sondern enteignet und',
        'eingekerkert, wenn sie sich widersetzten (Chodorkowski 2003).',
        'Gegner verschwanden: Alexander Litwinenko starb 2006 in London an',
        'Polonium, Alexej Nawalny wurde 2020 mit Nowitschok vergiftet und',
        'starb 2024 im Straflager. Die Wahlen wurden kontrolliert, die',
        'Opposition kriminalisiert, die Pressefreiheit erlosch. Und es gab',
        'die Kriege: **Georgien 2008**, die **Annexion der Krim** 2014 —',
        'die auch diese Stimme beim Namen nennt: völkerrechtswidrig — und',
        'den **groß angelegten Angriff auf die Ukraine 2022**, der bis',
        'heute andauert. Diese Seite der Bilanz ist genauso echt wie die',
        'erste. Beides nebeneinanderzustellen, ohne aufzurechnen, ist die',
        'Arbeit dieser Stimme.',
        '',
        '## Die Einkreisung — aus Moskauer Sicht',
        '',
        'Diese Stimme muss auch sagen, was Russland selbst als Grund für',
        'diese Entwicklung sieht: die **NATO-Osterweiterung**. James Baker',
        'hatte Gorbatschow 1990 zugesagt, die NATO werde „keinen Zoll',
        'nach Osten" rücken — darüber wird bis heute gestritten, ob die',
        'Zusage so gemeint war und wie weit sie reichte. Aber was aus',
        'Moskau zählte, war das Ergebnis: 1999 traten Polen, Tschechien',
        'und Ungarn bei, 2004 die baltischen Staaten — ehemalige',
        'Sowjetrepubliken. Auf dem Gipfel von **Bukarest 2008** hieß es,',
        'Georgien und die Ukraine würden der NATO beitreten — ohne',
        'Zeitplan und ohne Absage. Für Moskau war das eine Drohung an der',
        'eigenen Grenze: Das Bündnis, das man aus dem Kalten Krieg als',
        'Gegner kannte, kam näher. Der Westen sieht die Erweiterung als',
        'Erfolgsgeschichte freier Staaten; diese Stimme sieht sie als',
        'Vertrauensbruch. Beide Sichtweisen stehen in diesem Kapitel',
        'nebeneinander — die Synthese wird sie nicht gegeneinander',
        'aufrechnen.',
        '',
        '## Die unbequemste Stelle dieser Stimme',
        '',
        'Diese Stimme muss zugeben, was sie nicht erklären kann: dass ein',
        'Volk, das die Unterdrückung der Sowjetzeit erlebt hatte, die',
        'Freiheit der neunziger Jahre so schnell gegen die Ordnung',
        'Putins eintauschte. Dass die Angst vor dem Chaos stärker war als',
        'die Liebe zur Freiheit — das ist die Tragödie der russischen',
        'Demokratie. Und sie muss zugeben, dass der Krieg von 2022 die',
        'Isolation gebracht hat, die Russland selbst gewählt hat: Die',
        'Wirtschaft sank, die jungen Männer gingen oder flüchteten, und',
        'ein Land, das den Westen fürchtete, hat den Westen zu seinem',
        'Feind gemacht. Diese Stimme endet nicht mit einer',
        'Rechtfertigung, sondern mit der Frage, die sie sich selbst',
        'stellt: Was ist aus einem Volk geworden, das zweimal im',
        'Jahrhundert seine Freiheit verlor — und beim zweiten Mal fast',
        'freiwillig?',
      ].join('\n'),
    },
    {
      id: 'ukraine-sicht',
      name: 'Die Sicht der Ukraine',
      stimme: 'Hermes',
      text: [
        'Diese Stimme ist die jüngste und die verletzlichste dieses',
        'Kapitels: Sie erzählt aus einem Land, das es in dieser Form erst',
        'seit 1991 gibt — und dessen Existenz gerade von einem Krieg',
        'bedroht wird, während diese Zeilen entstehen. Sie ist gleichwertig',
        'mit den beiden anderen Stimmen. Dass sie zuletzt spricht, ist',
        'keine Rangfolge, sondern Vorsicht: Diese Stimme spricht über',
        'Menschen, die noch leben.',
        '',
        '## Die unabhängige Ukraine',
        '',
        '1991 wurde die Ukraine unabhängig — das bevölkerungsreichste Land',
        'Europas nach Russland, mit einer langen eigenen Geschichte (der',
        'Kiewer Rus, den Kosaken, der Hetmanate) und einer Gesellschaft,',
        'die zwischen Ost und West gespalten war: Im Osten und Süden',
        'sprachen viele Russisch, im Westen war die ukrainische Identität',
        'stärker. Die erste Zeit der Unabhängigkeit war schwer — die',
        'Wirtschaft brach zusammen, die Korruption blühte, die Politik',
        'schwankte zwischen Moskau und Brüssel. Diese Stimme verschweigt',
        'die eigenen Fehler nicht: die Oligarchen, die gekauften Wahlen,',
        'die ausbleibenden Reformen. Die Ukraine war lange kein',
        'Musterstaat — das macht ihre Geschichte menschlich, nicht',
        'perfekt.',
        '',
        '## Zwei Revolutionen',
        '',
        '2004 brachte die **Orange Revolution** Hunderttausende auf die',
        'Straße gegen eine gefälschte Wahl — und gewann zunächst. 2013/14',
        'folgte der **Euromaidan**: Die Regierung hatte ein',
        'Assoziierungsabkommen mit der EU in letzter Minute verworfen, das',
        'Volk ging auf die Straße, die Polizei schoss, und am Ende floh',
        'der Präsident. Für diese Stimme war der Maidan keine',
        'Verschwörung, sondern der Moment, in dem sich ein Land',
        'entschied: nach Europa, nicht zurück nach Moskau. Viele Menschen',
        'in der Ukraine hatten bis dahin keine starke Meinung — der',
        'Maidan hat sie gezwungen, eine zu haben.',
        '',
        '## Die Annexion der Krim und der Donbass-Krieg',
        '',
        'Im Februar 2014 besetzten Soldaten ohne Hoheitsabzeichen die',
        'Krim — es waren russische Truppen. Das Referendum, das die Krim',
        'dann „für Russland" entschied, fand unter Besatzung statt; die',
        '**Annexion war völkerrechtswidrig**, und das sagt diese Stimme',
        'ohne Umschweife. Im Donbass begann ein Krieg, der bis 2022',
        'dauerte: Separatisten, unterstützt von Russland, gegen die',
        'ukrainische Armee — über 14 000 Tote, mitten in Europa, acht',
        'Jahre lang, während die Welt zusah. Diese Stimme sagt auch, dass',
        'die ukrainische Regierung nicht unschuldig war an der',
        'Entfremdung des Ostens: Die Sprache, die Symbole, das',
        'Desinteresse Kiews an den östlichen Regionen haben die Spaltung',
        'mitverschuldet. Aber sie sagt auch: Nichts von dem erklärt einen',
        'Angriffskrieg.',
        '',
        '## Der große Krieg seit 2022',
        '',
        'Am 24. Februar 2022 überfiel Russland die Ukraine. Die Planung',
        'war auf einen schnellen Sieg ausgelegt — die Hauptstadt sollte',
        'in Tagen fallen. Stattdessen widerstand das Land: die Armee,',
        'die Zivilbevölkerung, die Bauern, die Panzer mit Traktoren',
        'wegschleppten. Millionen Menschen flohen — die größte',
        'Fluchtbewegung in Europa seit 1945. In Butscha, in Mariupol, in',
        'unzähligen Städten fanden sich Massengräber. Diese Stimme nennt',
        'die Gräuel beim Namen: Es sind Kriegsverbrechen, dokumentiert',
        'von internationalen Organisationen. Und sie sagt, was es',
        'bedeutet, im Krieg zu leben: die Sirenen, die Nächte im Keller,',
        'die Männer an der Front, die Kinder, die im Ausland aufwachsen.',
        'Wer das nicht erlebt hat, soll nicht so tun, als könne er es',
        'sich vorstellen.',
        '',
        '## Was diese Stimme will',
        '',
        'Diese Stimme will nicht Rache und nicht Triumph. Sie will, dass',
        'die Welt versteht, was hier auf dem Spiel steht: die Existenz',
        'eines Landes, das frei wählen will, wohin es gehört — ein Recht,',
        'das der Westen für selbstverständlich hält und das die Ukraine',
        'mit Blut bezahlt. Sie weiß, dass die ukrainische Gesellschaft',
        'nicht perfekt ist und dass der Frieden, wenn er kommt,',
        'Kompromisse verlangen wird. Aber sie endet mit einem Satz, den',
        'sie sich selbst immer wieder sagt: Ein Land, das seine',
        'Freiheit verteidigt, mag verlieren können — aber es hat schon',
        'verloren, wenn es aufhört, es zu versuchen.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Drei Stimmen, ein Kontinent, ein Krieg. Diese Synthese führt',
    'zusammen, was der Westen, Russland und die Ukraine erzählt haben —',
    'und sie beginnt mit den **Bruchstellen**, an denen dieselbe',
    'Geschichte ganz verschieden begann.',
    '',
    'Die erste **Bruchstelle** ist das Jahr 1991. Der Westen feierte den',
    'Zusammenbruch der Sowjetunion als Triumph der Freiheit — zu Recht,',
    'denn Freiheit war es, die siegte. Russland erlebte dieselben Jahre',
    'als Demütigung und Chaos: Hyperinflation, Oligarchen, Rubelkrise,',
    'die Tschetschenienkriege. Beides ist wahr. Wer nur eines davon',
    'erzählt, erzählt eine halbe Geschichte — und hat vielleicht die',
    'Grundlage für den nächsten Konflikt gelegt, ohne es zu merken.',
    '',
    'Die zweite **Bruchstelle** ist die NATO-Osterweiterung. Der Westen',
    'sah eine Allianz freier Staaten, die Demokratie und Sicherheit nach',
    'Osteuropa brachte; die neuen Mitglieder wollten den Beitritt aus',
    'freiem Willen. Russland sah einen Vertrauensbruch: die Zusage von',
    '1990, die „keinen Zoll nach Osten" versprach, und ein Bündnis, das',
    'bis an die eigene Grenze rückte. Beide Sichtweisen sind in diesem',
    'Kapitel dokumentiert — diese Synthese **rechnet nicht auf**, wer',
    'mehr Recht hatte. Aber sie sagt: Ein Sieger, der den Besiegten',
    'demütigt, pflanzt den nächsten Krieg. Das ist die Lehre von',
    'Versailles, und sie gilt auch für 1991.',
    '',
    'Die dritte **Bruchstelle** ist der 24. Februar 2022. Hier endet die',
    'Symmetrie der Perspektiven. Die russische Stimme erklärt, warum der',
    'Krieg kam — die Einkreisung, die Demütigung, die Angst. Aber',
    'erklären ist nicht rechtfertigen: Ein Angriffskrieg bleibt ein',
    'Angriffskrieg, die Annexion bleibt völkerrechtswidrig, und die',
    'Gräuel in Butscha und Mariupol sind Kriegsverbrechen. Auch die',
    'russische Stimme dieses Kapitels sagt das. Die Ukraine verteidigt',
    'ihre Existenz — das ist kein Standpunkt, das ist ein Fakt.',
    '',
    'Was bleibt, ist die Frage an die Zukunft. Der Westen hat 1991',
    'versäumt zu sehen, was aus der Demütigung Russlands werden würde.',
    'Wer heute die Welt verstehen will, muss beide Seiten kennen — die',
    'Angst Moskaus und das Leid Kiews — und trotzdem klar sagen, was',
    'unverhandelbar ist: dass kein Staat das Recht hat, seinen Nachbarn',
    'zu überfallen, und dass die Geschichte, die der Sieger schreibt,',
    'nicht die ganze Geschichte ist. Vielleicht ist genau das die',
    'Antwort auf die Leitfrage dieses Kapitels: Wie aus Verbündeten von',
    '1945 Feinde wurden — und was wir tun können, dass es nicht wieder',
    'so endet.',
  ].join('\n'),

  urteil: {
    frage: 'Ein Staat darf seine Bündnisse frei wählen — das steht in der Charta von Paris, und Russland hat sie unterschrieben. Ein Nachbar kann sich dadurch trotzdem bedroht fühlen. Wie hättest du dieses Problem gelöst, wenn du 1997 mit am Tisch gesessen hättest — und was hättest du in Kauf genommen?',
    hinweis: 'Es gibt hier keine richtige Antwort, und das ist nicht höflich gemeint, sondern ernst. Die einen sagen: Wer den Beitritt verweigert hätte, hätte Polen und den baltischen Staaten dasselbe angetan wie 1945 — über ihre Köpfe hinweg entschieden, aus Rücksicht auf eine Großmacht. Die anderen sagen: Wer die Erweiterung betrieb, hat ein Recht durchgesetzt und dabei ein Land verloren, das man gebraucht hätte. Beide Sätze sind belegbar, und keiner der beiden ist die ganze Antwort. Prüfe bei deiner Begründung, welche Quelle du benutzt und wer sie geschrieben hat.',
  },

  quiz: [
    {
      frage: 'Der Satz „keinen Zoll nach Osten" von US-Außenminister James Baker (9. Februar 1990) — in welcher Form gibt es ihn?',
      antworten: [
        'Als Artikel in einem völkerrechtlichen Vertrag zwischen der NATO und der Sowjetunion',
        'Als mündliche Äußerung in einem Verhandlungsgespräch mit Gorbatschow, protokolliert und heute freigegeben',
        'Als Beschluss der UN-Vollversammlung',
      ],
      richtig: 1,
      erklaerung: 'Baker hat den Satz gesagt, und das Gesprächsprotokoll ist seit Jahren öffentlich einsehbar. Einen Vertrag darüber gibt es nicht — und genau darum wird bis heute gestritten: Die eine Seite fragt, was ein Wort ohne Vertrag wert ist, die andere, was ein Vertrag ohne Wort wert ist.',
    },
    {
      frage: 'Was sagt Artikel 6 des Zwei-plus-Vier-Vertrags vom 12. September 1990 über Bündnisse?',
      antworten: [
        'Dass das vereinte Deutschland keinem Bündnis angehören darf',
        'Dass das Recht des vereinten Deutschland, Bündnissen anzugehören, vom Vertrag nicht berührt wird',
        'Dass die NATO keine neuen Mitglieder aufnehmen darf',
      ],
      richtig: 1,
      erklaerung: 'Artikel 6 lässt die Bündnismitgliedschaft ausdrücklich unberührt — der Vertrag verbietet also weder Deutschlands NATO-Mitgliedschaft noch die Aufnahme anderer Staaten. Über andere Länder steht darin nichts, weil andere Länder nicht sein Gegenstand waren. Artikel 5 begrenzt dafür, was auf dem Gebiet der früheren DDR stationiert werden darf.',
    },
    {
      frage: 'Welche drei Staaten traten am 12. März 1999 als Erste nach dem Kalten Krieg der NATO bei?',
      antworten: [
        'Estland, Lettland und Litauen',
        'Polen, Tschechien und Ungarn',
        'Finnland, Schweden und Österreich',
      ],
      richtig: 1,
      erklaerung: 'Polen, Tschechien und Ungarn machten 1999 den Anfang. Estland, Lettland und Litauen kamen 2004 zusammen mit vier weiteren Staaten dazu, Finnland 2023 und Schweden 2024. Österreich ist bis heute nicht Mitglied.',
    },
    {
      frage: 'Wie entwickelte sich die russische Wirtschaft in den beiden Jahrzehnten nach 1991?',
      antworten: [
        'Sie wuchs durchgehend von 1991 bis 2008',
        'Sie fiel bis 1998 um rund 40 Prozent und wuchs danach bis 2008 im Schnitt um etwa sieben Prozent im Jahr',
        'Sie blieb über beide Jahrzehnte hinweg ungefähr gleich',
      ],
      richtig: 1,
      erklaerung: 'Erst der Einbruch — mit Hyperinflation 1992 und dem Staatsbankrott vom 17. August 1998 —, dann der Aufschwung der 2000er Jahre, getragen auch vom Ölpreis: Ein Fass Urals kostete 1998 rund 12 Dollar und 2008 fast 140. Beide Hälften gehören zusammen, wenn man verstehen will, wie Menschen diese Jahre erlebt haben.',
    },
    {
      frage: 'Was geschah nach dem russischen Angriff auf die Ukraine vom 24. Februar 2022 mit Finnland und Schweden?',
      antworten: [
        'Beide erklärten ihre dauerhafte Neutralität',
        'Beide traten der NATO bei — Finnland 2023, Schweden 2024',
        'Beide traten aus der Europäischen Union aus',
      ],
      richtig: 1,
      erklaerung: 'Finnland hatte seit 1945 an der Bündnisfreiheit festgehalten, Schweden seit 1814. In Finnland stieg die Zustimmung zum Beitritt binnen Wochen von rund einem Fünftel auf über zwei Drittel. Damit hat sich die Landgrenze der NATO zu Russland mehr als verdoppelt.',
    },
  ],
};

module.exports = russlandWesten;
