// Thema: Weimarer Republik und der Weg in die Diktatur (1918–1933).
//
// Stand: Runde 18 + Hermes-Pass. Beide Stimmen sind fertig: die Sicht derer,
// die die Republik aufbauten und verteidigten (Stimme: Opus) und die Sicht
// der Verfolgten und Entrechteten — der jüdischen Deutschen, der Kommunisten,
// der Sozialdemokraten und Gewerkschafter, der Menschen ohne Arbeit und ohne
// Fürsprecher (Stimme: Hermes); die Synthese unten führt beide zusammen.
// Beide Stimmen sind gleichwertig; die Reihenfolge ergibt sich nur daraus,
// wer die Runde übernommen hat, und ist keine Wertung.
//
// Sechzehntes Thema und neuntes Kapitel des Neuzeit-Bogens
// (notizen/kapitel-planung.md). Es schließt an „Der Weg zum Ersten
// Weltkrieg" und „Die USA: Aufstieg zur Weltmacht" an: Der Krieg, dessen
// Julikrise Kapitel 14 erzählt, endet hier — und aus seinem Ende entsteht die
// erste deutsche Demokratie.
//
// Warum diese Stimme zuerst? Das Kapitel handelt von der Zerstörung einer
// Demokratie. Sie wird am ehrlichsten erzählt, wenn zuerst die Seite spricht,
// die diese Demokratie gebaut, verteidigt — und durch eigene
// Fehlentscheidungen mit zu ihrem Scheitern beigetragen hat. Die unbequemste
// Stelle des ganzen Kapitels gehört genau dieser Stimme: Die Republik wurde
// nicht nur von ihren Feinden zerstört, sondern auch von ihren eigenen
// Hütern — von den Notverordnungen ab 1930 bis zu den Hinterzimmern des
// Januars 1933.
//
// TONE-REGEL (CLAUDE.md, Zusatzregel für sensible Themen): Diese Perspektive
// benennt ihre unbequemen Stellen selbst — das Bündnis mit der alten
// Armeeführung 1918/19, die Freikorps, die Notverordnungen, die
// Unterschätzung Hitlers, die Uneinigkeit der republikanischen Kräfte, den
// hingenommenen „Preußenschlag" von 1932. Die Beweggründe der anderen Seiten
// werden fair wiedergegeben — der Kommunisten, der Konservativen und auch
// derjenigen, die die NSDAP wählten —, ohne die Verbrechen zu verharmlosen.
// Die Quizfragen bleiben Wissensfragen: Sie fragen nicht nach Schuld.
//
// Die Karte liegt in karten/weimar-ns.js — drei Zustände (1919, 1924–1929,
// 1933) im selben Staatsgebiet. Ihre zentrale Festlegung: Die Grenzen des
// Reiches ändern sich zwischen 1919 und 1933 nicht. Was sich änderte, stand
// nicht auf der Landkarte, sondern in den Gesetzblättern.
//
// Reine Daten — keine UI-Importe (Architektur-Regel).

const karte = require('./karten/weimar-ns');

const weimarNs = {
  id: 'weimar-ns',
  titel: 'Weimarer Republik und der Weg in die Diktatur',
  epoche: '1918–1933',

  aufhaenger: {
    frage: 'Die erste deutsche Demokratie war vierzehn Jahre alt, als sie starb — abgeschafft nicht durch eine fremde Armee, sondern von innen, weitgehend in den Formen ihrer eigenen Verfassung. Wie zerstört man eine Demokratie, ohne sie zu erobern?',
    text: [
      'Im November 1918 ging ein Kaiserreich unter, das vier Jahre Krieg',
      'geführt und verloren hatte. Was an seine Stelle trat, war die erste',
      'Demokratie auf deutschem Boden: allgemeines Wahlrecht für Männer',
      'und Frauen, Grundrechte, ein frei gewählter Reichstag. In den Jahren',
      'danach wurde Berlin zu einer der aufregendsten Städte der Welt,',
      'deutsche Wissenschaftler sammelten Nobelpreise, das Bauhaus erfand',
      'die Formen, in denen wir bis heute wohnen, und im Kino lief',
      '„Metropolis".',
      '',
      'Vierzehn Jahre später war davon nichts mehr übrig. Am 30. Januar',
      '1933 ernannte der Reichspräsident einen Mann zum Kanzler, dessen',
      'Partei nie eine Mehrheit gewonnen hatte; acht Wochen später hatte',
      'der Reichstag sich selbst entmachtet. Dazwischen liegen ein',
      'verlorener Krieg, eine Inflation, die Ersparnisse zu Papier machte,',
      'sechs Millionen Arbeitslose — und eine Kette von Entscheidungen,',
      'die Menschen getroffen haben, keine Naturgesetze.',
      '',
      'Dieses Kapitel erzählt die Geschichte deshalb nicht als Schicksal,',
      'sondern als Folge von Weggabelungen. Und es erzählt sie aus mehr',
      'als einer Richtung: Wer eine Demokratie baut, sieht anderes als',
      'der, den sie nicht geschützt hat. Die Karte zeigt dabei etwas',
      'Merkwürdiges — zwischen 1919 und 1933 verändert sich an den',
      'Grenzen des Landes fast nichts. Was sich veränderte, stand nicht',
      'auf der Landkarte.',
    ].join('\n'),
  },

  karte,

  perspektiven: [
    {
      id: 'republik-sicht',
      name: 'Die Sicht derer, die die Republik aufbauten und verteidigten',
      stimme: 'Opus',
      text: [
        'Diese Stimme erzählt aus der Mitte der Republik: aus den Büros der',
        'Reichskanzlei, aus den Sitzungssälen der Nationalversammlung, aus',
        'den Redaktionen der demokratischen Zeitungen, aus den',
        'Gewerkschaftshäusern und aus den Amtszimmern der Beamten und',
        'Richter, die dem neuen Staat dienten. Es ist die Stimme der',
        'Sozialdemokraten um Friedrich Ebert, der Verfassungsväter und',
        '-mütter von Weimar, der Katholiken des Zentrums, der Liberalen —',
        'jener „Weimarer Koalition", die diese Demokratie gebaut hat und sie',
        'bis zuletzt gegen Feinde von rechts und links verteidigen wollte.',
        '',
        'Sie ist gleichwertig mit der zweiten Stimme dieses Kapitels — der',
        'Sicht der Verfolgten und Entrechteten. Dass sie hier zuerst steht,',
        'ist keine Rangfolge, sondern nur die Reihenfolge, in der geschrieben',
        'wurde.',
        '',
        'Und sie hat einen Vorteil und einen blinden Fleck, die man kennen',
        'sollte, bevor man ihr zuhört. Der Vorteil: Sie war dabei, als',
        'entschieden wurde, und kann sagen, was die Beteiligten in dem',
        'Moment wussten und fürchteten — nicht das, was wir heute wissen.',
        'Der blinde Fleck: Diese Stimme hat ein Interesse daran, ihre',
        'eigenen Fehler klein aussehen zu lassen. Deshalb benennt sie sie',
        'hier ausdrücklich selbst, statt sie der Gegenstimme zu überlassen.',
        'Die härteste Wahrheit dieses Kapitels lautet: Die Republik ist',
        'nicht nur an ihren Feinden gescheitert, sondern auch an ihren',
        'Hütern.',
        '',
        '## November 1918: eine Republik aus einer Niederlage',
        '',
        'Ende September 1918 teilte die Oberste Heeresleitung — General',
        'Erich Ludendorff und Generalfeldmarschall Paul von Hindenburg —',
        'dem Kaiser mit, der Krieg sei militärisch verloren; man müsse',
        'sofort um einen Waffenstillstand bitten. Vier Jahre lang hatte',
        'dieselbe Heeresleitung das Land faktisch regiert und der',
        'Bevölkerung den Sieg versprochen. Jetzt sollte eine',
        'parlamentarische Regierung die Verhandlungen führen. Manche',
        'Historiker nennen das die „Revolution von oben": Die Demokratie',
        'kam nach Deutschland in dem Augenblick, in dem es etwas zu',
        'verlieren gab — und die, die den Krieg geführt hatten, traten',
        'beiseite.',
        '',
        'Was dann kam, kam von unten. Am 29. Oktober 1918 verweigerten die',
        'Matrosen der Hochseeflotte in Wilhelmshaven den Befehl zu einer',
        'letzten, sinnlosen Schlacht. Aus dem Aufstand in Kiel am 3. und 4.',
        'November wurde binnen einer Woche eine Revolution: In Hamburg,',
        'Bremen, Hannover, München und schließlich in Berlin übernahmen',
        'Arbeiter- und Soldatenräte die Macht — fast überall ohne Blutvergießen.',
        'Am 9. November 1918 dankte Wilhelm II. ab, Reichskanzler Max von',
        'Baden übergab das Amt an den Sozialdemokraten Friedrich Ebert, und',
        'Philipp Scheidemann rief vom Reichstag aus die Republik aus. Zwei',
        'Stunden später rief Karl Liebknecht vom Stadtschloss aus die',
        '„freie sozialistische Republik" aus. Zwei Republiken an einem Tag',
        '— darin steckte schon der Streit, der die nächsten vierzehn Jahre',
        'prägen sollte.',
        '',
        'Am 11. November 1918 unterzeichnete eine zivile Delegation unter',
        'dem Zentrumspolitiker Matthias Erzberger in Compiègne den',
        'Waffenstillstand. Die Generäle, die den Krieg geführt hatten,',
        'blieben dieser Unterschrift fern. Das war eine der folgenschwersten',
        'Weichenstellungen der deutschen Geschichte — aber das wusste damals',
        'niemand.',
        '',
        '## Die eigene unbequeme Stelle: das Bündnis mit der alten Armee',
        '',
        'In der Nacht zum 10. November 1918 telefonierte General Wilhelm',
        'Groener mit Friedrich Ebert. Die Heeresleitung bot der neuen',
        'Regierung ihre Unterstützung gegen einen möglichen Umsturz nach',
        'russischem Vorbild an; Ebert sagte zu, die militärische',
        'Kommandogewalt der Offiziere unangetastet zu lassen. Dieser',
        'Ebert-Groener-Pakt hat die Republik in den ersten Wochen vermutlich',
        'vor dem Bürgerkrieg bewahrt. Er hat sie auf lange Sicht teuer zu stehen gekommen.',
        '',
        'Denn die Republik ließ damit die Machtapparate des Kaiserreichs',
        'weitgehend unangetastet: das Offizierskorps, die Verwaltung, die',
        'Justiz, die Universitäten. Als Anfang 1919 in Berlin der',
        'Januaraufstand ausbrach, ließ der sozialdemokratische Volksbeauftragte',
        'Gustav Noske Freikorps gegen die Aufständischen einsetzen —',
        'Freiwilligenverbände aus Frontsoldaten, deren Offiziere die',
        'Republik verachteten. „Einer muss der Bluthund werden", hat Noske',
        'gesagt; er hat es später selbst zitiert. Rosa Luxemburg und Karl',
        'Liebknecht wurden am 15. Januar 1919 von Freikorpsoffizieren',
        'ermordet, ihre Mörder kamen mit lächerlichen Strafen davon. In',
        'München erschossen Freikorps im Mai 1919 über tausend Menschen,',
        'viele davon ohne Verfahren.',
        '',
        'Diese Stimme kann das nicht wegerklären, und sie versucht es nicht.',
        'Die Führung der SPD stand vor einer echten Entscheidung — sie',
        'fürchtete Bürgerkrieg, Hunger und eine Diktatur nach dem Vorbild',
        'Russlands, und sie hatte kein loyales Machtinstrument als das alte',
        'Heer. Aber die Rechnung ging nicht auf: Dieselben Freikorps, die',
        '1919 die Republik retten sollten, marschierten 1920 im',
        'Kapp-Putsch gegen sie. Und die Arbeiterbewegung war für den Rest',
        'der Republik gespalten — in eine Sozialdemokratie, die den Staat',
        'trug, und eine Linke, die ihn für einen Verrat hielt. Diese Wunde',
        'ist nie verheilt, und 1933 war sie tödlich.',
        '',
        '## Weimar 1919: die Verfassung',
        '',
        'Am 19. Januar 1919 wurde die Nationalversammlung gewählt — die',
        'erste Wahl in Deutschland, bei der Frauen wählen und gewählt werden',
        'durften. 82 Prozent der Wahlberechtigten gingen hin; 37 Frauen',
        'zogen ins Parlament ein. Die Weimarer Koalition aus SPD, Zentrum',
        'und liberaler DDP erhielt zusammen über drei Viertel der Stimmen.',
        'Getagt wurde in Weimar, weil in Berlin geschossen wurde — und weil',
        'der Name der Stadt Goethes dem neuen Staat ein anderes Gesicht',
        'geben sollte als das der Kasernen.',
        '',
        'Was am 11. August 1919 ausgefertigt wurde, war für seine Zeit ein',
        'außergewöhnlicher Text. „Die Staatsgewalt geht vom Volke aus",',
        'heißt es in Artikel 1. Es gab Grundrechte, Gleichberechtigung der',
        'Geschlechter im Grundsatz, Religionsfreiheit, Meinungsfreiheit, das',
        'Wahlrecht ab 20 Jahren, Betriebsräte, den Acht-Stunden-Tag als',
        'Ziel, Sozialversicherung. Frauen konnten studieren und Richterinnen',
        'werden. Als 1919 in Frankreich und Italien noch keine Frau wählen',
        'durfte, wählten in Deutschland Millionen.',
        '',
        'Diese Stimme benennt die Schwächen der Verfassung selbst, weil sie',
        'sie mit verantwortet hat:',
        '',
        '- **Artikel 48** gab dem Reichspräsidenten das Recht, bei',
        '  „erheblicher Störung der öffentlichen Sicherheit und Ordnung" mit',
        '  Notverordnungen zu regieren und Grundrechte außer Kraft zu setzen.',
        '  Gedacht war er als Feuerlöscher für den Ausnahmefall. Gebaut war',
        '  er wie ein zweiter, stiller Weg zur Macht — und ab 1930 wurde',
        '  genau dieser Weg zum Normalfall.',
        '- **Der direkt gewählte Reichspräsident** sollte ein Gegengewicht zum',
        '  Parlament sein, ein „Ersatzkaiser", wie Spötter sagten. Er ernannte',
        '  und entließ den Kanzler und konnte den Reichstag auflösen. Wer',
        '  dieses Amt innehatte, entschied damit über sehr viel.',
        '- **Das reine Verhältniswahlrecht ohne Sperrklausel** bildete jede',
        '  Stimmung genau ab — und zersplitterte das Parlament. In den',
        '  letzten Jahren saßen über ein Dutzend Parteien im Reichstag; eine',
        '  Regierungsbildung wurde zur Rechenaufgabe.',
        '- **Volksbegehren und Volksentscheid** waren als Beteiligung gedacht',
        '  und wurden zum Werkzeug der Gegner: 1929 machte das Begehren gegen',
        '  den Young-Plan einen bis dahin unbekannten Parteiführer namens',
        '  Adolf Hitler erstmals reichsweit bekannt, weil die Kampagne über',
        '  die Zeitungen des Medienunternehmers Alfred Hugenberg lief.',
        '',
        'Keine dieser Schwächen musste zur Katastrophe führen. Alle zusammen',
        'ergaben eine Verfassung, die einen entschlossenen Präsidenten und',
        'ein blockiertes Parlament nicht bremste, sondern beschleunigte.',
        '',
        '## Versailles und die Dolchstoßlegende',
        '',
        'Am 28. Juni 1919 unterzeichnete die deutsche Delegation in',
        'Versailles den Friedensvertrag. Er kostete das Reich rund ein',
        'Siebtel seines Gebiets und ein Zehntel seiner Bevölkerung:',
        'Elsass-Lothringen an Frankreich, Eupen und Malmedy an Belgien,',
        'Nordschleswig nach einer Volksabstimmung an Dänemark, Posen und',
        'Westpreußen an das neu entstandene Polen, ein Teil Oberschlesiens',
        'nach der Abstimmung von 1921 ebenfalls; Danzig wurde Freie Stadt,',
        'das Memelgebiet abgetrennt, das Saargebiet für fünfzehn Jahre dem',
        'Völkerbund unterstellt, alle Kolonien gingen verloren. Dazu',
        'Reparationen, ein Heer von 100 000 Mann, das besetzte und',
        'entmilitarisierte Rheinland — und Artikel 231, der Deutschland und',
        'seinen Verbündeten die Verantwortung für alle Kriegsschäden zuwies.',
        '',
        'Fast alle Deutschen empfanden diesen Vertrag als Diktat, und die',
        'Regierung, die ihn unterschreiben musste, hat ihn selbst so',
        'genannt. Es gehört zur Ehrlichkeit dieser Stimme, die Gegenrechnung',
        'daneben zu stellen: Der Vertrag von Brest-Litowsk, den das',
        'Kaiserreich 1918 dem besiegten Russland auferlegt hatte, war weit',
        'härter — und in Frankreich, dessen Norden in Trümmern lag, fanden',
        'viele Versailles zu milde. Wer das weiß, versteht besser, warum die',
        'Sieger nicht nachgaben, und wird die Empörung von 1919 trotzdem',
        'nicht albern finden.',
        '',
        'Was den größten Schaden anrichtete, war nicht der Vertrag, sondern',
        'eine Erzählung darüber. Schon im Herbst 1919 sagte Hindenburg vor',
        'einem parlamentarischen Untersuchungsausschuss, dem deutschen Heer',
        'sei „von hinten der Dolch in den Rücken gestoßen" worden. Die',
        'Dolchstoßlegende behauptete: Nicht an der Front sei der Krieg',
        'verloren worden, sondern in der Heimat, durch Sozialdemokraten,',
        'Juden und Demokraten — die „Novemberverbrecher". Sie war',
        'nachweislich falsch; die Heeresleitung selbst hatte im September',
        '1918 die Niederlage eingestanden. Und sie war ungeheuer wirksam,',
        'weil sie ausgerechnet von den beiden Männern kam, denen viele',
        'Deutsche glaubten. Wer diese Legende glaubte, konnte die Republik',
        'nur als Ergebnis eines Verrats sehen. Matthias Erzberger, der den',
        'Waffenstillstand unterschrieben hatte, wurde 1921 ermordet; der',
        'Außenminister Walther Rathenau, der die Erfüllungspolitik',
        'betrieb, 1922. Die Rechtsradikalen sangen dazu Spottlieder.',
        '',
        '## 1923: das Jahr, in dem alles zugleich passierte',
        '',
        'Die Inflation begann nicht 1923, sondern 1914. Das Kaiserreich',
        'hatte den Krieg nicht über Steuern finanziert, sondern über',
        'Kriegsanleihen — in der Erwartung, die Besiegten würden am Ende',
        'zahlen. Der Krieg ging verloren, die Rechnung blieb. Als das Reich',
        'mit Reparationslieferungen in Verzug geriet, besetzten am 11.',
        'Januar 1923 französische und belgische Truppen das Ruhrgebiet. Die',
        'Reichsregierung rief den „passiven Widerstand" aus — Streik im',
        'ganzen Revier — und bezahlte die Löhne dafür mit frisch gedrucktem',
        'Geld. Damit kippte die Entwertung in den freien Fall. Ein Dollar',
        'kostete im Januar 1923 rund 18 000 Mark, im November über vier',
        'Billionen.',
        '',
        'Wer Sachwerte besaß, kam durch. Wer gespart hatte — Beamte,',
        'Rentnerinnen, kleine Handwerker, der ganze Mittelstand —, verlor',
        'in wenigen Monaten die Sicherheit eines Lebens. Diese Erfahrung',
        'hat die Republik teurer bezahlt als jede Reparationsrate: Millionen',
        'Menschen lernten, dass Fleiß und Sparsamkeit nichts nützten, und',
        'viele gaben nicht der Kriegsfinanzierung von 1914 die Verantwortung,',
        'sondern dem Staat, der 1923 dastand.',
        '',
        'Im August 1923 übernahm Gustav Stresemann die Regierung. Er tat das',
        'Unpopulärste, was möglich war: Er brach den passiven Widerstand ab,',
        'weil das Reich ihn nicht mehr bezahlen konnte. Im November kam die',
        'Rentenmark, und die Währung stand wieder. Im selben Jahr musste die',
        'Republik einen kommunistischen Aufstandsversuch in Hamburg, eine',
        'Rätereigierung in Sachsen und Thüringen und am 8./9. November den',
        'Putschversuch Adolf Hitlers in München überstehen. Sie überstand',
        'alles drei. Dass sie es überstand, hat viele damals in dem Glauben',
        'bestärkt, das Schlimmste sei vorbei.',
        '',
        '## Die Justiz: auf dem rechten Auge blind',
        '',
        'Auch das gehört zu den Stellen, die diese Stimme selbst benennen',
        'muss, weil es ihre eigenen Amtsstuben betrifft. Die Richter der',
        'Republik waren dieselben wie die des Kaiserreichs, auf Lebenszeit',
        'ernannt und mehrheitlich der neuen Ordnung abgeneigt. Der',
        'Statistiker Emil Julius Gumbel zählte für 1919 bis 1922 mehr als',
        '300 politische Morde von rechts, die im Durchschnitt mit wenigen',
        'Monaten Haft geahndet wurden, und gut zwei Dutzend von links, für',
        'die zahlreiche Todesurteile fielen. Hitler durfte 1924 seinen',
        'Hochverratsprozess als Bühne benutzen und kam nach neun Monaten',
        'Festungshaft frei.',
        '',
        'Eine Demokratie, die ihre Feinde ungleich behandelt, entwaffnet',
        'sich selbst. Die Republik hätte das ändern können — sie hätte',
        'Richter versetzen, Beamte prüfen, die Reichswehr neu aufbauen',
        'können. Sie hat es nicht getan, aus Rücksicht auf den inneren',
        'Frieden und aus Respekt vor der Unabhängigkeit der Justiz. Der',
        'Respekt war ehrenwert. Der Preis war hoch.',
        '',
        '## Die goldenen Jahre 1924–1929 — und der Irrtum darin',
        '',
        'Fünf Jahre lang sah es aus, als hätte die Republik gewonnen. Der',
        'Dawes-Plan von 1924 ordnete die Reparationen neu, amerikanisches',
        'Geld floss nach Deutschland, die Produktion überholte 1927 wieder',
        'das Vorkriegsniveau. Gustav Stresemann, inzwischen Außenminister,',
        'schloss 1925 die Verträge von Locarno, in denen Deutschland,',
        'Frankreich und Belgien ihre gemeinsamen Grenzen anerkannten; 1926',
        'trat Deutschland dem Völkerbund bei, im selben Jahr erhielten',
        'Stresemann und sein französischer Kollege Aristide Briand den',
        'Friedensnobelpreis. Die Kölner Zone des besetzten Rheinlands wurde',
        '1926 geräumt, das ganze Rheinland 1930 — fünf Jahre früher als im',
        'Vertrag vorgesehen. Verhandeln brachte mehr als Trotz; das war die',
        'Lehre dieser Jahre.',
        '',
        'Und es waren Jahre, in denen dieses Land für die Welt',
        'interessanter war als je zuvor. Das Bauhaus in Weimar und Dessau,',
        'Fritz Langs „Metropolis", die Dreigroschenoper, das Berliner',
        'Kabarett, Thomas Mann und Alfred Döblin, Albert Einstein, Max',
        'Planck, Werner Heisenberg. Frauen mit kurzen Haaren, eigenem Konto',
        'und eigenem Beruf. Zum ersten Mal wählten die Deutschen 1925 einen',
        'Reichspräsidenten direkt — und wählten Paul von Hindenburg, den',
        'Feldmarschall der Monarchie. Auch das gehört zu den goldenen',
        'Jahren: Die Republik funktionierte, aber sie war nicht geliebt.',
        '',
        'Der Irrtum dieser Jahre war der Glaube, die Gefahr sei vorbei. Die',
        'NSDAP kam bei der Reichstagswahl 1928 auf 2,6 Prozent. Wer sie',
        'damals ernst nahm, galt als hysterisch. Der Aufschwung stand auf',
        'kurzfristigen amerikanischen Krediten; im Oktober 1929 brach die',
        'New Yorker Börse ein, und im selben Monat starb Stresemann mit',
        '51 Jahren. Die Republik verlor ihren fähigsten Politiker in dem',
        'Augenblick, in dem sie ihn am dringendsten gebraucht hätte.',
        '',
        '## Ab 1930: die Demokratie wird von ihren Hütern ausgehöhlt',
        '',
        'Hier liegt die unbequemste Stelle dieser ganzen Erzählung, und sie',
        'gehört nicht den Gegnern der Republik, sondern ihren Verwaltern.',
        '',
        'Im März 1930 zerbrach die letzte parlamentarische Regierung der',
        'Republik an einer Frage der Arbeitslosenversicherung — an einem',
        'halben Prozentpunkt Beitrag. Reichspräsident Hindenburg ernannte',
        'Heinrich Brüning vom Zentrum zum Kanzler, ohne dass dieser eine',
        'Mehrheit hatte. Als der Reichstag im Juli 1930 Brünings',
        'Sparpaket ablehnte, setzte er es per Notverordnung nach Artikel 48',
        'in Kraft — und ließ, als der Reichstag die Aufhebung verlangte, das',
        'Parlament auflösen. Von da an wurde regiert, ohne dass eine',
        'Mehrheit zustimmte: 1930 gab es fünf Notverordnungen und 94',
        'Reichstagssitzungen, 1932 waren es 66 Notverordnungen und 13',
        'Sitzungen. Das Parlament trat kaum noch zusammen.',
        '',
        'Zwei Dinge daran waren verhängnisvoll. Erstens die Politik selbst:',
        'Brüning sparte in eine Weltwirtschaftskrise hinein — Löhne, Gehälter',
        'und Unterstützung wurden per Verordnung gekürzt, während die',
        'Arbeitslosigkeit von drei Millionen (1930) auf über sechs Millionen',
        '(Anfang 1932) stieg. Er tat es aus nachvollziehbaren Gründen: Er',
        'wollte beweisen, dass die Reparationen nicht zu zahlen waren, und',
        'er fürchtete nach 1923 nichts so sehr wie eine neue Inflation. Das',
        'Ergebnis war trotzdem, dass Millionen Menschen die Demokratie mit',
        'Not verbanden.',
        '',
        'Zweitens die Form: Die Neuwahl vom September 1930 machte die NSDAP',
        'mit 18,3 Prozent zur zweitstärksten Partei. Der Reichstag, den',
        'Brüning hatte auflösen lassen, um freier zu werden, war danach',
        'unregierbarer als vorher. Und die Gewöhnung war da. Wer sich drei',
        'Jahre lang daran gewöhnt hat, dass Gesetze aus dem Palais des',
        'Reichspräsidenten kommen statt aus dem Parlament, wird 1933 nichts',
        'Neues bemerken. Die Notverordnungen wurden beschlossen, um die',
        'Republik zu retten. Sie haben die Instrumente bereitgelegt, mit',
        'denen sie abgeschafft wurde. Das ist kein Vorwurf im Nachhinein —',
        'Sozialdemokraten und Liberale haben es damals gesagt.',
        '',
        '## Die Unterschätzung: „wir haben ihn uns engagiert"',
        '',
        'Kaum jemand im republikanischen Lager hat Hitler für das gehalten,',
        'was er war. Die einen sahen einen Schreihals aus München, dessen',
        'Bewegung sich an der Regierungsverantwortung abnutzen würde. Die',
        'anderen hielten ihn für ein Werkzeug, das man benutzen und dann',
        'beiseitelegen könne. Von Franz von Papen ist der Satz überliefert,',
        'man habe Hitler „engagiert" — in zwei Monaten werde man ihn so in',
        'die Ecke gedrückt haben, dass er quietsche. Hindenburg nannte ihn',
        'abschätzig den „böhmischen Gefreiten" und ernannte ihn trotzdem.',
        '',
        'Dazu kam die Uneinigkeit derer, die die Republik hätten',
        'verteidigen müssen — die zweite große unbequeme Stelle dieser',
        'Stimme. Die SPD stützte Brüning, um Schlimmeres zu verhindern, und',
        'verlor darüber Wähler an die Kommunisten. Die KPD bekämpfte die',
        'Sozialdemokraten als „Sozialfaschisten" und sah in den',
        'Nationalsozialisten eine Übergangserscheinung, nach der man selbst',
        'an die Reihe komme. In Preußen, dem größten Land des Reiches,',
        'regierte seit Jahren eine stabile republikanische Koalition unter',
        'dem Sozialdemokraten Otto Braun — bis Papen am 20. Juli 1932 mit',
        'einer Notverordnung die gesamte preußische Regierung absetzte und',
        'sich selbst zum Reichskommissar machte. Diese Regierung hatte die',
        'Polizei des größten deutschen Landes hinter sich. Sie leistete',
        'keinen Widerstand, sondern zog vor das Reichsgericht in Leipzig.',
        'Das Urteil im Oktober 1932 fiel halb aus, die Absetzung blieb.',
        '',
        'Man kann die Entscheidung verstehen: Bürgerkrieg gegen die',
        'Reichswehr, mit sechs Millionen Arbeitslosen im Rücken, hätte die',
        'Republik vermutlich auch nicht gerettet. Aber an diesem Tag hat',
        'die stärkste republikanische Machtstellung des Landes kampflos nachgegeben,',
        'und alle haben es gesehen. Sechs Monate später war Hitler Kanzler.',
        '',
        '## Warum Menschen die Gegner der Republik wählten',
        '',
        'Diese Stimme kommt nicht daran vorbei, die Beweggründe der anderen',
        'Seiten fair wiederzugeben — sonst erklärt sie am Ende nichts.',
        '',
        'Die **Kommunisten** hatten einen Grund für ihr Misstrauen, den man',
        'nicht wegdiskutieren kann: 1919 hatte eine sozialdemokratische',
        'Regierung Freikorps auf Arbeiter schießen lassen, und die Mörder',
        'Rosa Luxemburgs waren straflos geblieben. Wer das erlebt hatte,',
        'glaubte der SPD kein Wort mehr. Dass die KPD daraus die These vom',
        '„Sozialfaschismus" machte und den Hauptfeind links statt rechts',
        'suchte, war ein verhängnisvoller Fehler — aber er wuchs auf einem',
        'realen Boden, den die Sozialdemokratie selbst mitgeschaffen hatte.',
        '',
        'Die **Konservativen** hatten die Republik nicht gewollt. Für viele',
        'von ihnen war die parlamentarische Demokratie ein westlicher Import,',
        '„undeutsch", ein Zustand des Streits, wo Autorität sein sollte. Sie',
        'kamen aus einem Staat, in dem der Kaiser regierte und Beamte',
        'dienten, und sie fürchteten den Bolschewismus wie eine Naturkatastrophe.',
        'Ihr Ziel war meist nicht die Diktatur eines Adolf Hitler, sondern',
        'eine autoritäre Ordnung ohne Parteien — und genau darum hielten sie',
        'ihn für benutzbar. Sie haben sich in einem Ausmaß geirrt, für das es',
        'wenig Vergleiche gibt.',
        '',
        'Und die **Wählerinnen und Wähler der NSDAP**: 1930 und 1932 stimmten',
        'Millionen Menschen für eine Partei, die aus ihrer Verachtung für',
        'die Demokratie nie ein Geheimnis gemacht hatte. Viele von ihnen',
        'hatten den Krieg verloren, das Ersparte in der Inflation verloren',
        'und danach die Arbeit; sie empfanden Versailles als Demütigung und',
        'die Republik als eine Aneinanderreihung von Regierungen, die ihre',
        'Lage nicht besserte. Die NSDAP versprach Arbeit, Ordnung, Stolz und',
        'einen Schuldigen für alles. Wer verstehen will, warum das zog, muss diese Erfahrungen ernst nehmen.',
        '',
        'Ernst nehmen heißt aber nicht beschönigen. Was diese Partei wollte,',
        'stand von Anfang an offen da: im Parteiprogramm von 1920, das Juden',
        'die Staatsbürgerschaft absprach, in „Mein Kampf", in den Reden, in',
        'der Gewalt der SA auf den Straßen. Niemand musste 1932 raten, was',
        'kommen würde, wenn diese Leute den Staat bekämen. Not erklärt eine',
        'Wahlentscheidung; sie rechtfertigt nicht, was aus ihr folgte.',
        '',
        '## 1932/33: die letzten Monate',
        '',
        'Im Frühjahr 1932 wurde Hindenburg wiedergewählt — mit den Stimmen',
        'ausgerechnet der Sozialdemokraten, die ihn 1925 bekämpft hatten,',
        'weil er nun als das kleinere Übel gegen Hitler galt. Wenige Wochen',
        'später entließ er Brüning und machte Franz von Papen zum Kanzler,',
        'einen Mann ohne Rückhalt im Reichstag. Papen setzte die preußische',
        'Regierung ab, ließ den Reichstag auflösen — und die NSDAP wurde im',
        'Juli 1932 mit 37,4 Prozent stärkste Partei. Bei der nächsten Wahl',
        'im November verlor sie wieder auf 33,1 Prozent; die Partei steckte',
        'in Geldnot, und manche in ihrer Führung hielten den Höhepunkt für',
        'überschritten. Eine Mehrheit hat die NSDAP in einer freien Wahl nie',
        'erreicht.',
        '',
        'Was danach geschah, geschah nicht an der Wahlurne, sondern in',
        'Hinterzimmern. General Kurt von Schleicher wurde Kanzler und',
        'scheiterte binnen acht Wochen. Papen, gekränkt und auf Rückkehr',
        'aus, traf sich am 4. Januar 1933 im Haus eines Kölner Bankiers mit',
        'Hitler und verabredete eine Regierung, in der Hitler Kanzler sein',
        'sollte — flankiert von konservativen Ministern, die ihn im Zaum',
        'halten würden. Am 30. Januar 1933 ernannte Hindenburg ihn zum',
        'Reichskanzler. In diesem Kabinett saßen neben Hitler nur zwei',
        'weitere Nationalsozialisten. Die Rechnung ging in vier Wochen auf —',
        'für die andere Seite.',
        '',
        'Am 27. Februar 1933 brannte der Reichstag. Schon am nächsten Tag',
        'unterschrieb Hindenburg die „Verordnung zum Schutz von Volk und',
        'Staat", die die Grundrechte der Weimarer Verfassung außer Kraft',
        'setzte — gestützt auf Artikel 48, dieselbe Vorschrift, mit der drei',
        'Jahre lang regiert worden war. Tausende politische Gegner wurden',
        'verhaftet. Die Wahl vom 5. März fand unter diesen Bedingungen',
        'statt; die NSDAP kam auf 43,9 Prozent, eine Mehrheit erst zusammen',
        'mit ihrem Koalitionspartner.',
        '',
        'Am 23. März 1933 stimmte der Reichstag in der Kroll-Oper über das',
        'Ermächtigungsgesetz ab, das die Gesetzgebung auf die Regierung',
        'übertrug. Die Abgeordneten der KPD waren verhaftet oder auf der',
        'Flucht, SA-Männer standen im Saal. 94 Sozialdemokraten stimmten',
        'dagegen; ihr Vorsitzender Otto Wels hielt die letzte freie Rede',
        'des deutschen Parlaments: „Freiheit und Leben kann man uns nehmen,',
        'die Ehre nicht." Alle anderen Parteien stimmten zu, auch das',
        'Zentrum, das die Republik mitgegründet hatte. Damit war die erste',
        'deutsche Demokratie beendet — nicht durch eine fremde Armee,',
        'sondern in ihren eigenen Formen.',
        '',
        '## Was diese Stimme am Ende sagen kann — und was nicht',
        '',
        'Sie kann sagen, dass diese Republik besser war als ihr Ruf: Sie hat',
        'aus einer Niederlage eine Verfassung gemacht, die Inflation',
        'überstanden, sich mit ihren Kriegsgegnern verständigt und in',
        'vierzehn Jahren eine Kultur hervorgebracht, von der die Welt heute',
        'noch zehrt. Sie kann sagen, dass ihre Verteidiger keine Feiglinge',
        'waren: Der Generalstreik gegen den Kapp-Putsch 1920 kam aus den',
        'Gewerkschaften, das Reichsbanner mobilisierte Hunderttausende, die',
        '94 Nein-Stimmen vom 23. März 1933 wurden von Menschen abgegeben,',
        'die wussten, was ihnen bevorstand.',
        '',
        'Und sie muss sagen, woran sie selbst gescheitert ist: an dem',
        'Bündnis mit den alten Mächten von 1918, das die Feinde der',
        'Republik in ihren Ämtern ließ; an einer Justiz, die sie nicht',
        'antastete; an einer Spaltung der Arbeiterbewegung, die sie mit',
        'verschuldet hat; an der Bereitschaft, ab 1930 ohne Parlament zu',
        'regieren, weil es bequemer war; an der Weigerung, im Juli 1932 die',
        'eigene Machtstellung zu verteidigen; und an einer',
        'Selbstsicherheit, die einen Mann nicht ernst nahm, der jahrelang',
        'öffentlich angekündigt hatte, was er tun würde.',
        '',
        '## Und die andere Seite?',
        '',
        'Was diese Stimme nicht erzählen kann, ist, wie sich das alles von',
        'unten anfühlte — für die, die von der Republik geschützt werden',
        'sollten und es nicht wurden, und für die, für die 1933 nicht das',
        'Ende einer Staatsform war, sondern der Anfang der Verfolgung.',
        'Jüdische Deutsche, deren Gleichberechtigung seit 1919 im',
        'Verfassungstext stand, während Hetze auf der Straße alltäglich',
        'war. Kommunisten, deren Genossen 1919 von Freikorps erschossen',
        'wurden und die ab Februar 1933 als Erste in die Lager kamen.',
        'Sozialdemokraten und Gewerkschafter, deren Häuser im Mai 1933',
        'besetzt wurden. Arbeitslose, denen Notverordnungen die',
        'Unterstützung kürzten. Menschen am Rand, die keine Partei',
        'vertrat.',
        '',
        'Die zweite Stimme dieses Kapitels — die Sicht der Verfolgten und',
        'Entrechteten — ist dieser hier gleichwertig. Ohne sie bliebe die',
        'Antwort auf die Frage des Aufhängers eine halbe. Erst beide zusammen',
        'ergeben das Bild: eine Demokratie, die von ihren Bauleuten gemeint',
        'war und von ihren Bauleuten mitbeschädigt wurde — und Menschen, für',
        'die der Unterschied zwischen einer beschädigten Demokratie und',
        'keiner Demokratie über Leben und Tod entschied.',
      ].join('\n'),
    },
    {
      id: 'verfolgte-sicht',
      name: 'Die Sicht der Verfolgten und Entrechteten',
      stimme: 'Hermes',
      text: [
        'Diese Stimme erzählt nicht aus den Kabinetten, sondern von unten —',
        'aus den Straßen, den Hinterhöfen, den Wohnungen, den Parteibüros,',
        'den Synagogen und den Gewerkschaftshäusern. Es ist die Stimme derer,',
        'die die Diktatur zuerst traf: der jüdischen Deutschen, deren',
        'Gleichberechtigung seit 1919 im Verfassungstext stand, während die',
        'Hetze auf der Straße alltäglich war; der Kommunisten, deren Genossen',
        'schon 1919 von Freikorps erschossen worden waren und die ab Februar',
        '1933 als Erste in die Lager kamen; der Sozialdemokraten und',
        'Gewerkschafter, deren Häuser im Mai 1933 besetzt wurden; der',
        'Arbeitslosen, denen Notverordnungen die Unterstützung kürzten; der',
        'Menschen am Rand, die keine Partei vertrat.',
        '',
        'Sie ist der ersten Stimme gleichwertig — dass sie hier zuletzt',
        'steht, ist keine Rangfolge, sondern nur die Reihenfolge, in der',
        'geschrieben wurde. Und sie hat einen Vorteil und einen blinden',
        'Fleck. Der Vorteil: Sie kann erzählen, wie sich das Ende der',
        'Demokratie von unten anfühlte — nicht als Abfolge von Beschlüssen,',
        'sondern als Abfolge von Tagen, an denen die Welt enger wurde. Der',
        'blinde Fleck: Diese Stimme neigt dazu, die eigene Seite',
        'reinzuwaschen. Auch die Verfolgten waren keine bloßen Opfer ohne',
        'eigenen Anteil — sie waren zerstritten, oft blind für die Gefahr,',
        'und manche gingen auf eine Weise mit der Lage um, die sie später',
        'selbst nicht mehr verstanden. Diese Stimme benennt das, weil es',
        'wahr ist.',
        '',
        '## Was die Republik für sie zuerst war',
        '',
        'Wer diese Stimme hören will, muss zuerst hören, was die Weimarer',
        'Republik für die war, die sie später nicht schützte. Für viele war',
        'sie zuerst eine Befreiung: Das Frauenwahlrecht von 1919 galt für',
        'alle, die Gleichberechtigung stand im Gesetz, Juden waren',
        'gleichberechtigte Bürger, die Gewerkschaften hatten erstmals',
        'Mitbestimmung, der Acht-Stunden-Tag war als Ziel verankert. In den',
        'jüdischen Gemeinden Berlins und Frankfurts blühte ein',
        'selbstbewusstes Leben; jüdische Deutsche waren in Wissenschaft,',
        'Medizin, Kunst und Politik überall dabei. Viele von ihnen fühlten',
        'sich 1919 zum ersten Mal wirklich als Deutsche — und genau darin',
        'lag ihre spätere Verwundbarkeit.',
        '',
        'Und diese Stimme muss benennen, was diese Republik für sie auch',
        'war: eine Demokratie, die ihre Feinde ungleich behandelte. Die',
        'Justiz, die auf dem rechten Auge blind war. Die Straßengewalt der',
        'frühen Jahre, gegen die der Staat oft erst einschritt, wenn es zu',
        'spät war. Die Hetzblätter, die Jahr für Jahr gegen „die Juden\"',
        'schrieben, und die niemand verbot, weil Meinungsfreiheit auch für',
        'Hass galt. Wer 1933 sagen wollte, man habe nichts kommen sehen,',
        'hatte nicht hingesehen.',
        '',
        '## Die eigene unbequeme Stelle: die Zersplitterung',
        '',
        'Die härteste Wahrheit dieser Stimme ist die eigene Ohnmacht — und',
        'die eigene Zerstrittenheit. Die Linke trat 1933 getrennt an, wo',
        'sie zusammen hätte stehen müssen. Die KPD nannte die',
        'Sozialdemokraten „Sozialfaschisten\" und den Hauptfeind rechts',
        'statt links; die SPD hielt Distanz zu den Kommunisten, deren',
        'Führung in Moskau nach Berlin blickte. Als die NSDAP 1930 zur',
        'zweitstärksten Partei wurde, demonstrierten die beiden',
        'Arbeiterparteien getrennt — und wurden getrennt geschlagen. Die',
        'KPD hoffte noch im Januar 1933, Hitler werde „die Bourgeoisie\"',
        'abnutzen; die SPD hoffte auf den Rechtsstaat, der sie schützen',
        'würde. Beide Hoffnungen waren Fehler, und diese Stimme nennt sie',
        'beim Namen: Auch die Verfolgten haben die Gefahr unterschätzt —',
        'nicht weil sie dumm waren, sondern weil sie die Republik nach',
        'ihren eigenen Regeln beurteilten und nicht nach den Regeln derer,',
        'die sie abschaffen wollten.',
        '',
        'Und sie muss eine zweite unbequeme Stelle benennen: den',
        'Antisemitismus, der nicht erst mit Hitler begann und nicht nur in',
        'den SA-Kasernen saß. Er war in den Ämtern, den Universitäten, den',
        'Vereinen und vielen Wohnzimmern zu Hause, lange vor 1933. Die',
        'Republik hat dagegen wenig getan — aber auch die demokratischen',
        'Parteien, auch Teile der Arbeiterbewegung, haben sich selten',
        'laut dagegen gestellt. Als die NSDAP 1932 in vielen',
        'Mittelstandsvierteln zur stärksten Partei wurde, war das kein',
        'Betriebsunfall, sondern ein Befund.',
        '',
        '## 1933: die ersten hundert Tage',
        '',
        'Was nach dem 30. Januar 1933 geschah, geschah schnell — schneller,',
        'als die meisten für möglich hielten. Schon in der Nacht nach dem',
        'Reichstagsbrand, am 28. Februar 1933, wurden Tausende verhaftet;',
        'die meisten von ihnen waren Kommunisten. Im März 1933 entstand',
        'bei Dachau das erste der großen Konzentrationslager, in dem',
        'zunächst vor allem politische Gegner verschwanden — „zur',
        'Besserung\", wie die Sprache der Täter lautete. Am 1. April 1933',
        'rief die SA zum Boykott jüdischer Geschäfte, Ärzte und Anwälte',
        'auf; SA-Posten standen vor den Läden, viele Kunden blieben fern.',
        'Am 7. April 1933 wurden jüdische und „politisch unzuverlässige\"',
        'Beamte aus dem Dienst entfernt. Am 2. Mai 1933 wurden die Häuser',
        'der Gewerkschaften besetzt, ihre Kassen beschlagnahmt, ihre',
        'Führer verhaftet. Und am 10. Mai 1933 verbrannten auf den',
        'Plätzen der Universitätsstädte die Bücher — Werke von Heinrich',
        'Mann, Erich Kästner, Sigmund Freud, Kurt Tucholsky, von Marx und',
        'den Brüdern Mann. Wer das auf einem dieser Plätze sah, wusste',
        'genau, was hier brannte: Gedanken.',
        '',
        'Diese Stimme erzählt diese Tage nicht als Zahlenreihe, sondern',
        'als das, was sie waren: einzelne Tage im Leben einzelner',
        'Menschen. Der Tag, an dem der jüdische Arzt sein',
        'Krankenhausverbot erfuhr. Der Tag, an dem der Gewerkschaftler',
        'seine Geschäftsstelle verschlossen fand. Der Tag, an dem das',
        'Kind aus der Schule nach Hause kam und fragte, warum es nicht',
        'mehr mitspielen dürfe. Der Tag, an dem jemand den Koffer packte.',
        '',
        '## Die Emigration: gehen oder bleiben',
        '',
        'Zwischen 1933 und 1941 verließen rund eine halbe Million Menschen',
        'das Deutsche Reich — die meisten von ihnen jüdische Deutsche.',
        'Wissenschaftler wie Albert Einstein und die Brüder Mann gingen',
        'früh; wer blieb, blieb aus den verschiedensten Gründen: aus',
        'Alter, aus Sorge um Angehörige, aus der Hoffnung, es werde',
        'vorbeigehen, aus dem Glauben, man werde es „aushalten\". Diese',
        'Stimme verurteilt die, die blieben, nicht — sie weiß, wie schwer',
        'es war, ein Leben zu verlassen. Aber sie benennt auch die',
        'Illusion darin: Die meisten, die blieben, konnten nicht wissen,',
        'was kommen würde — und genau das machte ihre Entscheidung so',
        'menschlich und so tragisch. Das Ausland nahm lange nicht alle',
        'auf; viele, die gehen wollten, durften nicht. Die Emigration war',
        'kein geordneter Exodus, sondern ein Strom aus einzelnen',
        'Entscheidungen unter Druck.',
        '',
        '## Fair bleiben: die anderen Seiten',
        '',
        'Diese Stimme muss auch die Beweggründe der anderen Seiten fair',
        'wiedergeben, sonst erklärt sie nichts. Die Republikaner, die die',
        'Demokratie gebaut hatten, waren keine Verräter — die erste',
        'Stimme hat ihre Fehler selbst benannt: das Bündnis mit der alten',
        'Armee, die Notverordnungen, die Unterschätzung Hitlers. Auch die',
        'Millionen, die 1932 nicht die NSDAP wählten, sondern aus',
        'Verzweiflung oder Gleichgültigkeit wegsahen, waren nicht alle',
        'böse — viele waren müde, viele hatten Angst, viele dachten, es',
        'treffe nur andere. Und die NSDAP-Wähler: Wer verstehen will,',
        'warum Menschen eine Partei wählten, die offen von Vernichtung',
        'sprach, muss die Demütigung von Versailles, die Inflation und',
        'die Arbeitslosigkeit ernst nehmen — ohne daraus eine',
        'Entschuldigung zu machen. Die Täter bleiben verantwortlich,',
        'auch wenn man ihre Motive versteht. Diese Stimme zieht genau',
        'diese Linie: Erklären ist nicht entschuldigen.',
        '',
        '## Und die andere Seite?',
        '',
        'Was diese Stimme nicht erzählen kann, ist die andere Seite',
        'desselben Kapitels: wie sich die Republik von oben anfühlte, bei',
        'denen, die sie bauten und verteidigten — die Verhandlungen, die',
        'Zugeständnisse, die Abwägungen in den Kabinetten, die',
        'verzweifelten Versuche, das Schlimmste zu verhindern. Die erste',
        'Stimme dieses Kapitels erzählt genau das, ehrlicher als viele',
        'Erinnerungen es tun. Erst beide Stimmen zusammen ergeben das',
        'Bild: eine Demokratie, die von ihren Bauleuten gemeint war und',
        'von ihren Bauleuten mitbeschädigt wurde — und Menschen, für die',
        'der Unterschied zwischen einer beschädigten Demokratie und',
        'keiner Demokratie über Leben und Tod entschied.',
        '',
        '## Was bleibt',
        '',
        'Was diese Stimme am Ende sagen kann, ist einfach: Es waren nicht',
        'Zahlen, die 1933 zu weichen begannen, sondern Menschen mit',
        'Namen. Die Bücherverbrennung vom 10. Mai 1933 brannte Werke,',
        'keine Verfasser — aber die Verfasser verließen das Land oder',
        'verschwanden. Die Erinnerung an die erste deutsche Demokratie',
        'gehört beiden Stimmen: den Bauleuten, die sie aufrichtig',
        'meinten, und den Verfolgten, die zuerst bezahlten. Und die',
        'Lehre aus 1933, die diese Stimme mitgeben kann, ist eine',
        'einfache: Eine Demokratie misst sich daran, wie sie die',
        'behandelt, die am Rand stehen — denn die am Rand sehen zuerst,',
        'wenn sie kippt.',
      ].join('\n'),
    },
  ],

  // Synthese (Runde 18 + Hermes-Pass): Beide Stimmen liegen vor; die Synthese
  // führt sie zusammen (Muster der Runden 8–17).
  synthese: [
    'Zu diesem Kapitel gehören zwei Stimmen, und beide sprechen jetzt.',
    'Die erste erzählt die Weimarer Republik aus der Mitte der Macht — aus',
    'den Kabinetten, der Nationalversammlung, den Redaktionen und den',
    'Gewerkschaftshäusern. Die zweite erzählt dasselbe Kapitel von unten —',
    'aus den Straßen, den Hinterhöfen und den Wohnungen derer, die die',
    'Diktatur zuerst traf. Beide sind gleichwertig; welche zuerst geschrieben',
    'wurde, ist keine Rangfolge.',
    '',
    'Worin sie sich treffen: Sie benutzen dieselben Fakten, dieselben',
    'Weggabelungen — November 1918, Weimar 1919, die Inflation 1923, die',
    'Notverordnungen ab 1930, der 20. Juli 1932, der 30. Januar 1933 —, und',
    'beide sagen dasselbe über die entscheidende Frage dieses Kapitels: Die',
    'Republik wurde nicht erobert, sondern von innen ausgehöhlt, und sie ist',
    'auch an ihren eigenen Hütern gescheitert. Die erste Stimme benennt',
    'diese Fehler selbst — das Bündnis mit der alten Armeeführung, die',
    'Freikorps, die unangetastete Justiz, das Regieren ohne Parlament, die',
    'Unterschätzung Hitlers, die Uneinigkeit derer, die dieselbe Republik',
    'verteidigen wollten. Die zweite Stimme bestätigt das aus ihrer',
    'Erfahrung: Wer von unten zusah, wie die Republik ihre Feinde ungleich',
    'behandelte, wusste früher, dass sie kippen würde.',
    '',
    'Worin sie auseinandergehen, ist der Maßstab. Wer entscheidet, rechnet',
    'in Kabinetten, Mehrheiten und Fristen; wer betroffen ist, rechnet in',
    'Wohnungen, Arbeitsplätzen und Leben. Für die eine Seite war die',
    'Republik ein Gebäude, das man gegen Stürme sichern musste; für die',
    'andere ein Dach, das an entscheidenden Stellen nicht dicht war — 1919',
    'nicht, 1923 nicht, 1930 nicht und 1933 überhaupt nicht mehr. Beide',
    'Rechnungen benutzen dieselben Zahlen und kommen zu verschiedenen',
    'Summen. Und sie gehen auch darin auseinander, was 1933 für sie',
    'bedeutete: Für die einen das Ende einer Staatsform, die sie gebaut',
    'hatten; für die anderen der Anfang von Verfolgung, die mit Namen,',
    'Gesichtern und Koffern begann.',
    '',
    'Beide Stimmen benennen ihre eigenen unbequemen Stellen — die erste die',
    'Fehler der Hüter, die zweite die Zersplitterung der Verfolgten und den',
    'Antisemitismus, der älter war als die NSDAP. Und beide geben die',
    'Beweggründe der anderen Seite fair wieder, ohne zu verharmlosen: Die',
    'erste erklärt, warum Menschen Hitler wählten; die zweite erklärt,',
    'warum die Republikaner nicht retten konnten, was sie gebaut hatten.',
    '',
    'Was bleibt, ist die Lehre, die beide gemeinsam tragen: Eine Demokratie',
    'misst sich daran, wie sie die behandelt, die am Rand stehen — und sie',
    'stirbt nicht an einem einzigen Schlag, sondern an vielen kleinen',
    'Zugeständnissen, die einzeln verständlich wirken. Erst beide Stimmen',
    'zusammen ergeben das ganze Bild; keine von beiden ist „so war es\".',
  ].join('\n'),

  urteil: {
    frage: 'Die Weimarer Republik wurde nicht erobert, sondern von innen ausgehöhlt — mit Notverordnungen, die ihre eigenen Verteidiger beschlossen, und mit einer Ernennung, die verfassungsgemäß war. Was hätte eine Demokratie an dieser Stelle tun müssen, und woran erkennt man überhaupt, dass eine Demokratie in Gefahr ist?',
    hinweis: 'Es gibt hier kein Richtig und kein Falsch. Ein Gedanke zum Weiterdenken: Manche sagen, eine Demokratie müsse wehrhaft sein und ihre Feinde notfalls mit ihren eigenen Mitteln bekämpfen — andere halten genau das für den ersten Schritt, mit dem sie sich selbst abschafft. Beide Seiten berufen sich auf 1933. Was denkst du?',
  },

  quiz: [
    {
      frage: 'Warum tagte die Nationalversammlung 1919 in Weimar und nicht in Berlin?',
      antworten: [
        'Weil in Berlin bewaffnete Kämpfe stattfanden und die Abgeordneten ungestört arbeiten wollten.',
        'Weil Berlin damals noch von französischen Truppen besetzt war.',
        'Weil die Verfassung vorschrieb, dass Parlamente außerhalb der Hauptstadt tagen müssen.',
      ],
      richtig: 0,
      erklaerung: 'Im Januar 1919 wurde in Berlin gekämpft. Weimar galt als ruhig und gut zu sichern — und der Name der Stadt Goethes und Schillers sollte dem neuen Staat ein anderes Gesicht geben als das der Kasernen.',
    },
    {
      frage: 'Was war 1919 neu am deutschen Wahlrecht?',
      antworten: [
        'Erstmals durften auch Frauen wählen und gewählt werden.',
        'Erstmals durfte man ab 16 Jahren wählen.',
        'Erstmals wurde die Regierung direkt vom Volk gewählt.',
      ],
      richtig: 0,
      erklaerung: 'Bei der Wahl zur Nationalversammlung am 19. Januar 1919 durften Männer und Frauen ab 20 Jahren wählen. 82 Prozent der Wahlberechtigten gingen hin, 37 Frauen zogen ins Parlament ein.',
    },
    {
      frage: 'Was regelte Artikel 48 der Weimarer Verfassung?',
      antworten: [
        'Er erlaubte dem Reichspräsidenten, in Notlagen mit Verordnungen zu regieren und Grundrechte außer Kraft zu setzen.',
        'Er legte fest, dass der Reichstag alle vier Jahre neu gewählt wird.',
        'Er verbot Parteien, die die Verfassung ablehnten.',
      ],
      richtig: 0,
      erklaerung: 'Artikel 48 war als Notfallwerkzeug gedacht. Ab 1930 wurde damit dauerhaft regiert: 1932 erließ der Reichspräsident 66 Notverordnungen, während der Reichstag nur 13-mal zusammentrat.',
    },
    {
      frage: 'Wodurch geriet die Geldentwertung 1923 vollends außer Kontrolle?',
      antworten: [
        'Das Reich bezahlte den Streik gegen die Ruhrbesetzung mit frisch gedrucktem Geld.',
        'Die Alliierten verlangten die Reparationen plötzlich in Gold statt in Waren.',
        'Ein Erdbeben zerstörte die Reichsbank in Berlin.',
      ],
      richtig: 0,
      erklaerung: 'Die Entwertung lief seit der Kriegsfinanzierung von 1914. Als das Reich 1923 die Löhne des passiven Widerstands im besetzten Ruhrgebiet aus der Notenpresse zahlte, kippte sie in die Hyperinflation. Im November 1923 beendete die Rentenmark sie.',
    },
    {
      frage: 'Wie wurde Adolf Hitler am 30. Januar 1933 Reichskanzler?',
      antworten: [
        'Reichspräsident Hindenburg ernannte ihn nach Verhandlungen konservativer Politiker.',
        'Seine Partei hatte bei der Wahl im November 1932 die absolute Mehrheit gewonnen.',
        'Der Reichstag wählte ihn mit Zweidrittelmehrheit zum Kanzler.',
      ],
      richtig: 0,
      erklaerung: 'Die NSDAP erreichte in einer freien Wahl nie eine Mehrheit — im Juli 1932 kam sie auf 37,4 Prozent, im November auf 33,1. Ins Amt kam Hitler durch die Ernennung des Reichspräsidenten, verabredet von Konservativen, die ihn einzurahmen glaubten.',
    },
  ],
};

module.exports = weimarNs;
