// Oversættelse (dansk) af temaet „Asiens opstigning og Vestens fremtid"
// (1945 til i dag). Kilde: utils/themen/aufstieg-asiens.js, kortfaser:
// utils/themen/karten/aufstieg-asiens.js.
//
// Struktur: samme skema som de tyske temamoduler (utils/themen/schema.js),
// men uden karte-objektet; kortets faser er oversat i karteHinweise
// (label + hinweis), jf. STAND.md (oversættelsespipeline, da/ i repoet).
//
// Fire stemmer: Vestens syn (Tyskland og Europa, stemme: Opus), Japans,
// Sydkoreas og Taiwans syn (de „flyvende gæs", stemme: Hermes), Kinas syn
// (stemme: Hermes) og Indiens syn (stemme: Hermes). Den endelige syntese
// ender bevidst åbent — med et spørgsmål til fremtiden, ikke med et punktum.
// Kortet har tre faser (1955–1968 / 1990 / 2024).
//
// TONE-REGEL (CLAUDE.md, tillægsregel for emner med nutidsrelevans):
// operatørens tese „Tyskland et døende land, Europa et gammelt kontinent med
// ringe fremtid?" behandles fair: relativt tab af betydning ja, absolut
// sammenbrud nej — „at indhente" er ikke det samme som „at overhale". Quizzen
// forbliver vidensspørgsmål.
//
// Rene data — ingen UI-imports (arkitekturregel).

const aufstiegAsiens = {
  id: 'aufstieg-asiens',
  titel: 'Asiens opstigning og Vestens fremtid',
  epoche: '1945–i dag',

  aufhaenger: {
    frage: 'Det kontinent, der i 1945 lå i ruiner, er i dag med Tyskland verdens tredjestørste økonomi. Det kontinent, der i 1955 hørte til verdens fattigste, er i dag med Kina verdens næststørste. Er det en historie om Vestens nedgang — eller om to opstigninger på samme tid?',
    text: [
      'I maj 1945 lå de fleste store tyske byer i ruiner, omkring otte',
      'millioner mennesker var på flugt eller fordrevet, og industriproduktionen',
      'var faldet til en brøkdel af niveauet før krigen. I 1961 nåede Sydkorea op',
      'på omkring 100 US-dollar i økonomisk produktion per indbygger — mindre',
      'end Ghana. Kina oplevede i de samme år med „det store spring fremad" en',
      'selvforskyldt hungerkatastrofe med millioner af døde.',
      '',
      'Mindre end en generation senere var Forbundsrepublikken verdens',
      'tredjestørste økonomi. Mindre end to generationer senere var Kina verdens',
      'næststørste, Sydkorea rigere end adskillige vesteuropæiske lande, og på',
      'en ø ved navn Taiwan blev ni ud af ti af verdens mest moderne halvledere',
      'fremstillet.',
      '',
      'Dette sidste kapitel i appen fortæller om to opstigninger, der fandt sted',
      'samtidig, og om det spørgsmål, der opstod af det: Taber Vesten, fordi',
      'Asien vinder? Eller er det det forkerte spørgsmål — fordi økonomi, i',
      'modsætning til krig, ikke er et nullsumsspil? Til allersidst står en',
      'tese, som operatøren af denne app udtrykkeligt ønskede stillet: Er',
      'Tyskland et døende land, er Europa et gammelt kontinent med ringe',
      'fremtid? Appen giver ikke noget færdigt svar — dette kapitel ender',
      'bevidst åbent, med et spørgsmål til fremtiden, ikke med et punktum. Det',
      'begynder med Vestens syn. Det er én af flere stemmer, ikke den eneste,',
      'og at den står først her, er ikke en rangorden.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'Vestens syn — Tyskland og Europa',
      stimme: 'Opus',
      text: [
        'Denne stemme fortæller fra Frankfurt, Bonn, Bruxelles og Berlin: fra',
        'den økonomi, der i 1945 startede på nul og i dag hører til verdens',
        'stærkeste — og som samtidig ved, at den relativt taber vægt, mens der',
        'andre steder hentes ind.',
        '',
        'Den er ligeværdig med de stemmer, der følger efter. At den står først',
        'her, er ikke en rangorden — det skyldes blot, hvem der overtog denne',
        'runde. Og den har, ligesom den foregående synsvinkel i det forrige',
        'kapitel, en særlig opgave: Dette kapitel er ikke afsluttet. Den nutid,',
        'det handler om, er stadig åben — og hvert tal i denne tekst er en',
        'status, ikke et endeligt resultat.',
        '',
        '## 1945: nulpunktet, der ikke var et',
        '',
        'Ved slutningen af Anden Verdenskrig var Tyskland ødelagt, men ikke',
        'tømt for indhold. Den skelnen er vigtig, og den overses ofte. „Time',
        'nul" var en følelse, ikke en økonomisk diagnose: Ingeniører, faglærte',
        'arbejdere, forvaltningsviden og uddannelsessystemer overlevede krigen',
        'bedre end bygningerne. Økonomer taler derfor i dag snarere om en hurtig',
        'genoprettelse end om et mirakel — kapitalapparatet var i 1945 faktisk',
        'ikke meget mindre end i 1936, fordi der også under krigen var blevet',
        'investeret.',
        '',
        'Det, der manglede, var penge i omløb og et marked, der fungerede. Den',
        '20. juni 1948 ændrede **valutareformen** det: Af den værdiløse',
        'rigsmark blev D-marken, hver person fik fyrre mark i „hovedpenge", og',
        'over natten fyldtes butiksvinduerne — ikke fordi der pludselig var',
        'flere varer, men fordi det ikke længere kunne betale sig at hamstre.',
        'Ludwig Erhard ophævede samme weekend, mod militærregeringens modstand,',
        'en stor del af prisreguleringen. Dermed begyndte det, der gik over i',
        'historien som **den sociale markedsøkonomi**: frie priser OG en',
        'velfærdsstat, der skulle afbøde hårdhederne — en mellemvej mellem den',
        'uhæmmede kapitalisme, som mange frygtede, og planøkonomien, der opstod',
        'i landets øst.',
        '',
        '**Marshallplanen** kom til, men mindre, end legenden siger: Af de',
        'omkring 13 milliarder dollar, der mellem 1948 og 1952 flød til seksten',
        'lande, gik omkring 1,4 milliarder til Vesttyskland — målt mod den',
        'vesttyske økonomiske produktion et forholdsvis lille beløb. Afgørende',
        'var mindre summen end virkningen: råvarer og valuta præcis dengang,',
        'begge dele manglede, og en tvang til økonomisk samarbejde, som',
        'modtagerlandene pålagde hinanden, og som senere blev til Det',
        'Europæiske Økonomiske Fællesskab.',
        '',
        'Dertil kom noget, der er sværere at gøre op i tal: otte millioner',
        'fordrevne fra de tidligere østområder, som skulle integreres, og som,',
        'så hårdt det end lyder, først og fremmest var ét — ekstra arbejdskraft',
        'i et land, der havde brug for den. Og et uddannelsessystem med en lang',
        'tradition for teknik og ingeniørvidenskab, der efter 1945 hurtigt igen',
        'var i stand til at uddanne. „Det økonomiske mirakel" i 1950\'erne — i',
        'gennemsnit omkring otte procent vækst om året — var derfor ikke et',
        'mirakel, men en regning med flere poster. Vigtigt er også: Det var ikke',
        'enestående. Frankrig, Italien og, som kapitlet straks vil vise, Japan',
        'voksede i de samme år lige så hurtigt. Den, der kun kender den tyske',
        'historie, holder for et tysk mirakel, hvad der var et mønster i den',
        'vesteuropæiske genopbygning.',
        '',
        '## Hvad det blev til: en af verdens stærkeste økonomier',
        '',
        'Af denne begyndelse blev der over otte årtier en økonomi, der i 2024',
        'med omkring 4,7 billioner dollar er verdens tredjestørste — bag USA og',
        'Kina, foran Japan, Indien og Storbritannien. De seks stiftende stater i',
        'Det Europæiske Økonomiske Fællesskab fra 1957 er i dag en del af en',
        'union med 27 medlemmer, der tilsammen står for omkring en sjettedel af',
        'verdensøkonomien. Tre styrker bærer den den dag i dag:',
        '',
        '**Eksport.** Tyskland har i årtier været en af verdens største',
        'eksportnationer — maskinbygning, biler, kemi, siden 2000\'erne i',
        'stigende grad også specialiseret anlægsteknologi, som intet andet land',
        'fremstiller i samme dybde. **Industri.** I modsætning til Storbritannien',
        'eller USA har Tyskland aldrig i samme omfang mistet sin industrielle',
        'kerne, som „afindustrialisering" beskriver det i andre vestlige lande',
        'siden 1980\'erne; industriens andel af den økonomiske produktion ligger',
        'den dag i dag tydeligt over det vesteuropæiske gennemsnit. **Stabil',
        'valuta og institutioner.** Euroen, forvaltet af Den Europæiske',
        'Centralbank i Frankfurt, hører til verdens vigtigste reservevalutaer;',
        'Tyskland har i årtier gældt for investorer som et af de mest pålidelige',
        'lande for kapital, med uafhængige domstole, lav korruption og en',
        'kreditværdighed blandt verdens højeste.',
        '',
        '## De ubekvemme steder — denne stemme nævner dem selv',
        '',
        'Den, der kun fortæller om styrkerne, fortæller reklame. Fire svagheder',
        'hører lige så meget med i denne balance, og Vesten selv må nævne dem.',
        '',
        '**Eksportafhængigheden.** Hvad der er en styrke, er samtidig en',
        'sårbarhed. Da halvledere i 2021 blev knappe i Taiwan, måtte tyske',
        'bilfabrikker på korttidsarbejde — ikke på grund af en egen fejl, men',
        'fordi en enkelt komponent fra et enkelt land manglede. Da Rusland i',
        '2022 ikke længere leverede gas, kom den energiintensive industri under',
        'pres. Et land, der eksporterer lige så meget, som det importerer, er',
        'rigt OG afhængigt — begge dele på samme tid, ikke det ene på trods af',
        'det andet.',
        '',
        '**Den forsømte digitalisering.** Der findes ingen tysk eller europæisk',
        'modpart til Google, Amazon, Apple, Meta eller Microsoft — og heller',
        'ingen til de store kinesiske digitalkoncerner. Årsagerne diskuteres',
        '(kapitalmarkeder, regulering, risikoaversion, et uddannelsessystem, der',
        'satsede på ingeniørvidenskab frem for software) — selve diagnosen er',
        'ubestridt: I det 21. århundredes software- og platformøkonomi spiller',
        'Europa ikke i første række.',
        '',
        '**Demografien.** Tyskland har, som næsten hele kontinentet, et',
        'aldrende samfund: en medianalder på omkring 46 år (mod 28 i Indien), en',
        'fødselsrate på omkring 1,5 barn per kvinde i årtier tydeligt under',
        'reproduktionsniveauet på 2,1, og et voksende antal pensionister over',
        'for et langsommere voksende antal erhvervsaktive. Manglen på faglært',
        'arbejdskraft er ikke længere en prognose, men hverdag i håndværk,',
        'pleje og teknik.',
        '',
        '**Den langsomme vækst.** I omkring to årtier har Tyskland vokset',
        'langsommere end de fleste sammenlignelige økonomier — i gennemsnit af',
        '2010\'erne og 2020\'erne under en procent om året. Bureaukrati, høje',
        'energipriser, en ældet infrastruktur (broer, jernbane, bredbånd) og et',
        'politisk system, der vedtager reformer langsomt, hører til de oftest',
        'nævnte årsager. Det er ikke et kollaps — det er stagnation, og',
        'stagnation tærer langsommere, men lige så sikkert.',
        '',
        '## „Et døende land"? Hvad tallene reelt siger',
        '',
        'Her står det spørgsmål i centrum, som dette kapitel skal stille efter',
        'operatørens retningslinje — og svaret er ikke et enkelt tal, men en',
        'skelnen, der let forveksles: **relativt** og **absolut** er to',
        'forskellige spørgsmål.',
        '',
        '**Relativt** taber Tyskland vægt, og det er ubestrideligt. I 1960',
        'udgjorde de vesteuropæiske økonomier tilsammen en markant større andel',
        'af verdensøkonomien end i dag — ikke fordi de skrumpede, men fordi',
        'resten af verden voksede hurtigere. Når et kontinent med 1,4',
        'milliarder mennesker vokser fra 2 procent af verdensøkonomien (Kina',
        '1990) til omkring 18 billioner dollar og en sjettedel af',
        'verdensøkonomien (Kina 2024), falder andelen for ethvert andet land',
        'automatisk — selv hvis landets egen økonomi fortsat vokser. Det er',
        'matematik, ikke en sygdom.',
        '',
        '**Absolut** er Tyskland i 2024 forblevet en af verdens stærkeste',
        'økonomier — den tredjestørste, med et velstandsniveau, der er historisk',
        'enestående. Den forventede levealder ligger på omkring 81 år, den',
        'sociale sikring hører til verdens mest omfattende, infrastrukturen er',
        'trods al berettiget kritik stadig over gennemsnittet i',
        'verdenssammenligning. „At indhente" er ikke det samme som „at',
        'overhale": Kina har i tredive år dramatisk formindsket afstanden til',
        'Tyskland i økonomisk produktion per indbygger — fra omkring en',
        'tresindstyvendedel af den tyske værdi i 1990 til omkring en fjerdedel i',
        '2024. Formindsket, ikke lukket.',
        '',
        'Den, der siger „døende land", mener som regel det første (relativt) og',
        'taler, som om det var det andet (absolut). Denne forveksling er kernen',
        'i mange tysk-angst-debatter — og denne stemme modstår både panikken og',
        'skønmaleriet: Bekymringerne er reelle (demografi, vækst,',
        'digitalisering), men de er ikke en nærdødsoplevelse. Et land med',
        'verdens tredjestærkeste eksport dør ikke — det ældes, og at ældes er',
        'noget andet end at dø.',
        '',
        '## Og hvad gør det med blikket på Asien?',
        '',
        'Denne stemme vil anerkende Asiens opstigning fair — uden nedladenhed',
        'og uden tysk angst. Begge fejl forekommer i den offentlige samtale, og',
        'begge er forkerte.',
        '',
        'Nedladende er fortællingen om, at Asien „kun har kopieret", hvad Vesten',
        'opfandt. Den var allerede forkert over for Japan i 1980\'erne og er det',
        'så meget desto mere over for Sydkorea, Taiwan og Kina: TSMC i Taiwan',
        'fremstiller i dag chips i strukturstørrelser, som intet vestligt',
        'selskab kan producere alene; Sydkoreas Samsung og LG er',
        'verdensmarkedsledere på skærme og hukommelseschips; Kinas forspring',
        'inden for batteriteknologi og solceller er reelt og selvskabt. Den,',
        'der bagatelliserer det, gør sig selv stor.',
        '',
        'Panisk er fortællingen om, at Vesten allerede har tabt. Også den er',
        'forkert: USA forbliver med omkring en fjerdedel af verdensøkonomien',
        'verdens største økonomi, Europa forbliver et af de største indre',
        'markeder, og innovationskraften inden for bio- og farmateknologi, på',
        'visse områder af højteknologien og i grundforskningen er ubrudt høj.',
        'Økonomi er, i modsætning til den krig, som appen i sine tidligere',
        'kapitler ofte har fortalt om, ikke et nullsumsspil: At Kina og Indien',
        'vokser, betyder ikke automatisk, at Tyskland skrumper — det betyder',
        'først og fremmest, at milliarder af mennesker er kommet ud af ekstrem',
        'fattigdom, og det er, målt med enhver human målestok, en god nyhed og',
        'ikke en trussel.',
        '',
        '## De egne bekymringer — og de andres',
        '',
        'Det, denne stemme til sidst vil fastholde, er en symmetri, der ofte',
        'mangler i den offentlige samtale: Også Asiens opstigning har sine egne',
        'uløste spørgsmål, og de er ikke mindre end de tyske. Japan ældes',
        'hurtigere end Tyskland og skrumper allerede i absolutte tal. Kina ældes',
        'på grund af etbarnspolitikken fra 1980 til 2015 i et tempo, som',
        'økonomer beskriver som „at blive gammel, før man bliver rig". Indien',
        'vokser hurtigt, men med en ulighed, der er enorm mellem IT-metropolerne',
        'og det landlige bagland. Og over Taiwan ligger et politisk spørgsmål,',
        'som ingen økonomisk nøgletal kan løse.',
        '',
        'Derfor står denne stemme her ikke alene. **Asiens synsvinkler** —',
        'Japan, Kina, Indien, Sydkorea og Taiwan, hver med egen opstigning,',
        'egne omkostninger og egne åbne spørgsmål — skriver Hermes; skemaet',
        'tillader her udtrykkeligt mere end to stemmer. Først derefter samler',
        'den endelige syntese det, der hører sammen — og stiller det spørgsmål,',
        'som hele denne app ender med: Hvis historie bliver den næste?',
      ].join('\n'),
    },
    {
      id: 'japan-sicht',
      name: 'Japans, Sydkoreas og Taiwans syn — de flyvende gæs',
      stimme: 'Hermes',
      text: [
        'Denne stemme fortæller fra Østasien — fra Tokyo, Seoul og Taipei — og',
        'den fortæller historien om en formation, som historikerne kalder de',
        '„flyvende gæs": Japan fløj forrest, og de andre fulgte i dets spor.',
        'Den er ligeværdig med stemmerne fra Vesten, Kina og Indien.',
        '',
        '## Japan — det første mirakel',
        '',
        'I 1945 lå Japan i ruiner: Hiroshima og Nagasaki, de bombede byer, den',
        'besejrede hær. Tyve år senere var Japan verdens næststørste økonomi.',
        'Hvordan? Denne stemme nævner faktorerne ærligt: den amerikanske hjælp',
        'og Koreakrigens ordrer, den beslutsomme stat (ministeriet MITI styrede',
        'industrien), bankerne, der forsynede virksomhederne med billige penge,',
        'firmaer som Toyota, Sony og Honda, der forstod kvalitet ikke som en',
        'omkostning, men som en strategi — og arbejderne, der levede for',
        'virksomheden. Japan blev forbillede for hele Asien: beviset på, at et',
        'ikke-vestligt land kunne indhente Vesten.',
        '',
        'Så kom boblen i 1989/91: Aktie- og ejendomspriserne havde løsrevet sig',
        'fra virkeligheden, og da de brast, fulgte **„de tabte årtier"** —',
        'stagnation, deflation, et samfund, der blev ældre, uden at økonomien',
        'voksede op efter. Denne stemme kalder tingene ved navn: Overmodet var',
        'ægte, bankernes og politikens fejl var ægte. Japan er i dag stadig en',
        'af verdens største økonomier — men det viser, at opstigning ikke er en',
        'ensrettet gade.',
        '',
        '## Sydkorea — fra fattighus til højteknologi',
        '',
        'I 1960 var Sydkorea fattigere end Ghana. I dag fremstiller det de',
        'halvledere, skibene og smartphones, som verden bruger. Vejen dertil var',
        'hård: **Chaebolerne** — familiekonglomeraterne som Samsung og Hyundai —',
        'blev styret og subsidieret af staten, og bagsiden var et',
        '**militærdiktatur**, der varede i årtier og blodigt undertrykte',
        'arbejdere og studerende (Gwangju 1980). Først i 1987 opnåede Korea',
        'demokratiet — og det er en af denne stemmes store lektioner, at landet',
        'efter demokratiseringen ikke brød økonomisk sammen, men fortsatte med',
        'at vokse. Kulturen kom til (K-pop, serierne), og med den en ny',
        'stolthed. Skyggesiderne forbliver: presset i samfundet, overarbejdet,',
        'verdens laveste fødselsrate.',
        '',
        '## Taiwan — den lille ø, der forsyner verden',
        '',
        'Taiwan er mindre end Danmark — og alligevel hænger verdensøkonomien på',
        'det. Årsagen hedder **TSMC**: virksomheden grundlagt i 1987, der fik',
        'ideen til ikke kun at fremstille chips til sig selv, men for alle —',
        '„foundry"-modellen. I dag bliver næsten alle verdens mest moderne chips',
        'produceret i Taiwan; uden dem kørte ingen smartphone, ingen bil, ingen',
        'kunstig intelligens.',
        '',
        'Denne stemme må også nævne det spørgsmål, der ligger over Taiwan: Kina',
        'ser øen som en udbryderprovins, Taiwan ser sig selv som et eget land',
        'med eget demokrati og egne valg. Begge synsvinkler står i dette kapitel',
        'side om side — appen gør ikke op, hvem der har ret. Men denne stemme',
        'siger, hvad der forbinder alle tre lande: De fik opstigningen ikke',
        'foræret — de kæmpede sig til den, ofte mod Vesten, ofte med Vesten, og',
        'altid til en pris.',
      ].join('\n'),
    },
    {
      id: 'china-sicht',
      name: 'Kinas syn — kæmpen vågner',
      stimme: 'Hermes',
      text: [
        'Denne stemme fortæller fra Peking, Shanghai og Shenzhen — fra landet,',
        'der har gennemført historiens største indhentning: På fyrre år er Kina',
        'gået fra et fattigt landbrugsland til verdens næststørste økonomi, og',
        'hundreder af millioner mennesker har forladt fattigdommen.',
        '',
        '## Fra Mao til Deng — vendepunktet i 1978',
        '',
        'Denne stemme begynder ikke med opstigningen, men med prisen før den:',
        '**Kulturrevolutionen** (1966–1976) var en katastrofe — millioner af',
        'døde, ødelagte familier, en økonomi på nulpunktet. Først **Deng',
        'Xiaoping** førte Kina i 1978 ud af den blindgyde. Hans sætning blev',
        'berømt: „Det er lige meget, om katten er sort eller hvid — bare den',
        'fanger mus." Deng åbnede landet: **de særøkonomiske zoner** (Shenzhen',
        'blev fra en fiskerby til en by med 17 millioner indbyggere), bønderne,',
        'der igen måtte arbejde for sig selv, de udenlandske investorer, der var',
        'velkomne. Det, der fulgte, var historiens største økonomiske vækst:',
        'årtier med vækstrater på omkring ti procent, hundreder af millioner',
        'løftet ud af fattigdom.',
        '',
        '## Skyggesiderne — denne stemme nævner dem selv',
        '',
        'Denne stemme skjuler ikke, hvad opstigningen kostede:',
        '**etbarnspolitikken**, der har præget en generation; luftforureningen,',
        'der kvalte byerne; den voksende ulighed mellem kyst og bagland;',
        'gælden; og politikken: **nedkæmpelsen af protesterne på Den Himmelske',
        'Freds Plads i 1989**, undertrykkelsen af uighurerne i Xinjiang, den',
        'manglende pressefrihed, overvågningen. Kina er ikke et demokrati — det',
        'siger denne stemme uden omsvøb. Og den siger også: Mange kinesere',
        'bærer dette kompromis med, fordi de selv har oplevet opstigningen —',
        'forældrene, hvis børn har det bedre; landsbyerne, der fik strøm. Om',
        'dette kompromis holder, er et af de åbne spørgsmål, som dette kapitel',
        'ender med.',
        '',
        '## Storhedens pris — og fremtiden',
        '',
        'Kina står i dag over for det, Japan oplevede tidligere: Befolkningen',
        'ældes — etbarnspolitikken var så succesfuld, at Kina snart har flere',
        'gamle end unge. Den hurtige vækst aftager, ejendomskrisen og gælden',
        'tynger, og verden ser mistroisk på Pekings ambitioner — fra Det',
        'Sydkinesiske Hav til Taiwan. Denne stemme siger, hvad Kina har opnået,',
        'uden at skjule omkostningerne: Kæmpen er vågnet — men at vågne er ikke',
        'det samme som at være ankommet.',
      ].join('\n'),
    },
    {
      id: 'indien-sicht',
      name: 'Indiens syn — verdens største demokrati',
      stimme: 'Hermes',
      text: [
        'Denne stemme fortæller fra Delhi, Mumbai og Bengaluru — fra landet,',
        'der siden 2023 har flere indbyggere end Kina, og som har verdens yngste',
        'store befolkning. Indien er den demokratiske modforestilling til den',
        'kinesiske vej — og denne stemme fortæller, hvad det betyder.',
        '',
        '## Den lange lammelse og vendepunktet i 1991',
        '',
        'Efter uafhængigheden i 1947 valgte Indien under Nehru en socialistisk',
        'vej: planøkonomien, „License Raj" — et system, hvor næsten alt skulle',
        'godkendes, og hvor næsten intet gik hurtigt. I årtier voksede Indien',
        'langsomt — „hindu rate of growth" blev øgenavnet for stilstanden. I',
        '1991 kom vendepunktet: En betalingskrise tvang Indien til at åbne sig,',
        'finansminister Manmohan Singh løsnede lænkerne, og følgen var',
        '**IT-revolutionen**: Bengaluru blev verdens softwarecenter, firmaer som',
        'Infosys og TCS, den indiske diaspora steg i USA til de mest',
        'succesfulde ledere — cheferne for Microsoft, Google og IBM var',
        'pludselig indere. Indien beviste: Demokrati og vækst udelukker ikke',
        'hinanden.',
        '',
        '## Det demografiske udbytte',
        '',
        'Indiens største skat er dets befolkning: Medianalderen ligger på',
        'omkring 28 år — Europa er dobbelt så gammelt, Kina også tydeligt',
        'ældre. Disse unge mennesker er fremtidens arbejdskraft, mens den gamle',
        'verden ældes. Denne stemme siger også, hvad der skulle til for at',
        'indløse udbyttet: skoler til alle, job til millioner, der hvert år',
        'presser sig på arbejdsmarkedet. Uden disse investeringer bliver',
        'udbyttet til en byrde.',
        '',
        '## Skyggesiderne — uden omsvøb',
        '',
        'Denne stemme nævner de egne sår: **uligheden**, der hører til verdens',
        'største; **kastesystemet**, der den dag i dag stiller millioner',
        'ringere; fattigdommen, der trods al vækst forbliver; den mangelfulde',
        'infrastruktur; religionsspændingerne, der igen og igen bryder ud i',
        'vold. Og den siger, hvad demokratiet koster: Det er højlydt, kaotisk og',
        'langsomt — men det er frit, og præcis det adskiller Indien fra Kina. Om',
        'Indien udnytter sin chance, er det spørgsmål, som denne stemme lader',
        'stå åbent — ligesom hele dette kapitel vil ende åbent.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Fire stemmer, et århundrede, en åben fremtid. Denne syntese samler, hvad',
    'Vesten, Japan med de flyvende gæs, Kina og Indien har fortalt — og den',
    'forbliver bevidst **åben**, fordi den historie, som dette sidste kapitel',
    'fortæller, stadig er ved at blive skrevet.',
    '',
    'Den første lektion er forskydningen af vægtene. I 1945 stod Vesten på',
    'højdepunktet af sin magt; Europa lå i ruiner, men verdensordenen var',
    'dets. I dag er Asien verdens mest dynamiske region: Japan viste vejen,',
    'tigerøkonomierne fulgte, Kina indhentede på fyrre år, hvad Vesten havde',
    'bygget i to århundreder, og Indien har verdens yngste befolkning. Den,',
    'der ikke forstår denne forskydning, forstår ikke nutiden.',
    '',
    'Den anden lektion er operatørens tese — fair afbalanceret: Tyskland er',
    'ikke et døende land, og Europa er ikke et gammelt kontinent uden fremtid.',
    'Absolut set hører de fortsat til verdens stærkeste økonomier; relativt',
    'set skrumper deres andel, fordi andre vokser hurtigere. **At indhente er',
    'ikke det samme som at overhale** — og omvendt. Demografien er nøglen:',
    'Europa ældes, Japan ældes, Kina ældes — kun Indien er ungt. Fremtiden',
    'tilhører dem, der kan håndtere deres befolkning.',
    '',
    'Den tredje lektion er ærligheden i balancerne. Hver stemme i dette',
    'kapitel har nævnt sin pris: Vesten sin eksportafhængighed og sin',
    'fremtidsangst, Japan sine tabte årtier, Korea sit diktatur, Kina sit',
    'kompromis med friheden, Indien sin ulighed. Ingen af disse historier er',
    'kun en succes, ingen kun en fiasko — og præcis det gør dem til historie i',
    'denne apps forstand: forståelig, ikke sort-hvid.',
    '',
    'Og det sidste spørgsmål forbliver åbent, fordi det må forblive åbent:',
    'Hvis historie bliver den næste?',
  ].join('\n'),

  urteil: {
    frage: 'Tyskland taber økonomisk relativ vægt, men forbliver absolut en af verdens stærkeste økonomier. Er det en grund til bekymring, en grund til ro — eller begge dele på samme tid, og i så fald, hvori adskiller de to slags bekymring og ro sig?',
    hinweis: 'Der er her intet rigtigt svar. Nogle siger: Relativt tab af betydning er begyndelsen til enden; den, der ikke vokser med verdensøkonomien, falder til sidst også absolut tilbage. Andre siger: At milliarder af mennesker i Asien vokser ud af fattigdom, mens Tyskland forbliver rigt, er ikke et nullsumsspil, men det bedst tænkelige udfald for de fleste mennesker i verden. Prøv i dit svar, om du tænker ud fra Tyskland eller ud fra hele verden — begge synsvinkler fører til forskellige svar, og ingen af dem er forkert.',
  },

  quiz: [
    {
      frage: 'Hvad ændrede valutareformen den 20. juni 1948 konkret i de vestlige besættelseszoner?',
      antworten: [
        'Den indførte euroen som Vesteuropas fælles valuta',
        'Den erstattede den værdiløse rigsmark med D-marken og ophævede samtidig i vid udstrækning prisreguleringen',
        'Den nationaliserede den tyske industri',
      ],
      richtig: 1,
      erklaerung: 'Hver person fik 40 mark i „hovedpenge"; Ludwig Erhard ophævede samtidig en stor del af prisreguleringen. Over natten fyldtes butiksvinduerne — ikke fordi der pludselig var flere varer, men fordi det ikke længere kunne betale sig at hamstre.',
    },
    {
      frage: 'Hvor stor var Marshallplanens andel af den vesttyske økonomiske produktion sammenlignet med dens virkning?',
      antworten: [
        'Målt mod den økonomiske produktion var den forholdsvis lille, men vigtig på det rigtige tidspunkt (råvarer, valuta, tvungent samarbejde)',
        'Den finansierede størstedelen af den vesttyske genopbygning',
        'Den havde ingen betydning for Vesttyskland',
      ],
      richtig: 0,
      erklaerung: 'Af omkring 13 milliarder dollar mellem 1948 og 1952 gik omkring 1,4 milliarder til Vesttyskland — målt mod den økonomiske produktion forholdsvis lidt. Vigtig var den alligevel: som kilde til råvarer og valuta i en mangeltid, og fordi den tvang de europæiske modtagerlande til samarbejde.',
    },
    {
      frage: 'Hvad betyder det, når Tysklands andel af verdensøkonomien siden 1990 falder, mens landets egen økonomiske produktion fortsat vokser?',
      antworten: [
        'Det er umuligt — en faldende andel betyder nødvendigvis, at den egne økonomi skrumper',
        'Begge dele kan gælde samtidig: Når andre økonomier vokser hurtigere, falder ens egen andel rent regnet, også uden egen tilbagegang',
        'Det betyder, at statistikken bliver regnet forkert',
      ],
      richtig: 1,
      erklaerung: 'Det er forskellen på relativt og absolut: Når Kina mellem 1990 og 2024 vokser fra 2 procent til omkring en sjettedel af verdensøkonomien, falder andelen for ethvert langsommere voksende land automatisk — også selv om landets egen økonomi fortsætter med at vokse i samme periode.',
    },
    {
      frage: 'Hvilken økonomi var i 2024 verdens fjerdestørste efter USA, Kina og Tyskland?',
      antworten: [
        'Japan',
        'Frankrig',
        'Indien',
      ],
      richtig: 0,
      erklaerung: 'Japan forblev trods „de tabte årtier" efter 1990 verdens fjerdestørste økonomi. Indien lå i 2024 på femtepladsen, men var den hurtigst voksende af de store økonomier.',
    },
    {
      frage: 'Hvad viser eksemplet med halvlederknapheden i 2021 for de tyske bilfabrikker?',
      antworten: [
        'At Tyskland teknologisk er fuldstændig afhængigt af Kina',
        'At en høj eksportfletning kan betyde styrke og sårbarhed på samme tid',
        'At Tyskland ikke længere har nogen egen bilindustri',
      ],
      richtig: 1,
      erklaerung: 'Da halvledere fra Taiwan i 2021 blev knappe, måtte tyske bilfabrikker på korttidsarbejde — en enkelt manglende komponent fra et enkelt land var nok. Præcis den tætte fletning, der gør Tyskland til en eksportmagt, gør det samtidig sårbart.',
    },
  ],

  karteHinweise: [
    {
      label: '1955–1968 — genopbygning og økonomisk mirakel',
      hinweis:
        'Ti år efter krigen vokser Vesteuropa og Japan hurtigere end nogensinde før: Forbundsrepublikken med omkring 8 procent om året, Japan med omkring 9. Sydkorea, Taiwan og Singapore er på dette tidspunkt fattige lande — Sydkorea kom i 1961 op på omkring 100 dollar per indbygger og lå dermed under Ghana. Verdens største økonomi ligger uden for dette udsnit: USA stod omkring 1960 for omkring 40 procent af verdensøkonomien. Og endnu en gang: Fladen viser land, ikke vægt — vægten står i titlerne.',
    },
    {
      label: '1990 — Japans højdepunkt og de fire tigre',
      hinweis:
        'Japan stod i 1990 for omkring 14 procent af verdensøkonomien — den højeste andel, landet nogensinde har haft. De fire „tigerøkonomier" Sydkorea, Taiwan, Hongkong og Singapore har på én generation halveret afstanden til Europa. Kina er tolv år efter reformernes begyndelse stadig lille: omkring 2 procent af verdensøkonomien. Tyskland er siden den 3. oktober 1990 igen én stat — det er den eneste flade på dette kort, der vokser mellem to faser.',
    },
    {
      label: '2024 — de nye vægtforhold',
      hinweis:
        'Folkerepublikken Kina har siden 2010 været verdens næststørste økonomi, og Indien har siden 2023 været verdens mest folkerige land. Tyskland rykkede i 2023 igen op på tredjepladsen — ikke fordi det var vokset, men fordi yenen var faldet. USA ligger stadig uden for dette udsnit og stadig på førstepladsen med omkring en fjerdedel af verdensøkonomien. Og fladen viser stadig land, ikke vægt: Kinas statsområde er syvogtyve gange så stort som Tysklands, dets økonomiske produktion omkring fire gange.',
    },
  ],
};

module.exports = aufstiegAsiens;
