// Emne: Kina — fra den første kejser til de store dynastier.
//
// Dansk oversættelse af utils/themen/china.js (tysk original).
// Begge stemmer er færdige: den europæiske synsvinkel (Stemme: Opus)
// og den kinesiske synsvinkel (Stemme: Hermes); syntesen nedenfor fører
// dem sammen (se CLAUDE.md, perspektiv-workflow).
//
// Kortet ligger i karten/china.js — det er langt og af en anden art
// (geometri i stedet for fortælling), derfor i en egen fil. Her er kun
// fasehenvisningerne oversat (karteHinweise), ikke selve kortet.
//
// Rene data — ingen UI-imports (arkitekturregel).

const kina = {
  id: 'china',
  titel: 'Kina: Fra den første kejser til de store dynastier',
  epoche: 'Kejsertiden — fra rigssamlingen i 221 f.Kr. til Tang-dynastiets afslutning i 907 e.Kr.',

  aufhaenger: {
    frage: 'Et rige, så stort som Rom — og i århundreder vidste Europa ikke engang rigtigt, at det fandtes. Hvordan skriver man et land sammen, hvor alle skriver forskelligt?',
    text: [
      'Forestil dig, at du skal gøre syv lande til ét. De har ført krig mod',
      'hinanden i to hundrede og halvtreds år. De har forskellige mønter,',
      'forskellige vægte, forskellige love — og de skriver det samme ord med',
      'forskellige tegn. En ordre fra din hovedstad er i den anden ende ikke',
      'bare langsom — den er ulæselig.',
      '',
      'Præcis over for det problem stod i 221 f.Kr. en mand, der kaldte sig',
      'Qin Shi Huangdi: den første ophøjede kejser af Qin. Hans løsning var',
      'lige så enkel som brutal — han gjorde alting ens. Én skrift. Ét mål.',
      'Én vægt. Endda én ensartet sporvidde til vogne, så de passede i de',
      'samme hjulspor.',
      '',
      'Og mens Rom voksede frem i Europa, voksede der i den anden ende af',
      'verden et andet rige frem, der var omtrent lige så stort og havde',
      'omtrent lige så mange mennesker. De to vidste næsten intet om hinanden.',
      'Én eneste tråd forbandt dem: silke.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Den europæiske synsvinkel',
      stimme: 'Opus',
      text: [
        'Sådan fortælles Kinas historie i Europa — eller også fortælles den',
        'bare ikke, for i lang tid vidste Europa forbløffende lidt om den. Det',
        'er i sig selv en del af historien: Denne synsvinkel begynder ikke med',
        'Kina, men med et hul. Behold det gerne i baghovedet, mens du læser.',
        '',
        '## Serica — landet, som stoffet kom fra',
        '',
        'Romerne kendte ikke Kina. De kendte et produkt.',
        '',
        'I Rom var silke det dyreste stof i verden: let som ingenting,',
        'skinnende, køligt mod huden. Nogle vejede det op mod guld. Den lærde',
        'Plinius brokkede sig over, at riget tabte ufattelige summer på det',
        'stads, og senatet skændtes seriøst om, hvorvidt mænd overhovedet',
        'måtte bære silke — den blev anset for alt for blød.',
        '',
        'Hvor stoffet kom fra, vidste ingen rigtigt. Romerne kaldte',
        'menneskene i den anden ende „serere" og landet „Serica" — afledt af',
        'ordet for silke. Plinius berettede i fuldt alvor, at sererne kæmmede',
        'silken af blade. Om silkeorme havde han aldrig hørt. Kineserne',
        'vogtede på denne hemmelighed i over tusind år; på udførsel af orme',
        'eller æg stod der dødsstraf.',
        '',
        'Sådan så Europas billede af Kina længe ud: en vare uden land, et',
        'rygte for enden af en meget lang vej. Og vend nu billedet om. For',
        'dér, hvor vejen begyndte, var der ikke noget rygte, men et rige med',
        'embedsmænd, kanaler, folketællinger og biblioteker.',
        '',
        '## 221 f.Kr.: Én mand gør alting ens',
        '',
        'Før 221 f.Kr. var Kina ikke et land, men en slagmark. Syv store',
        'stater kæmpede om forherredømmet — perioden kaldes den dag i dag de',
        'stridende staters tid. Til sidst sejrede Qin, et hårdt,',
        'velorganiseret rige i vest, og dets konge gjorde sig til noget, der',
        'ikke havde fandtes før: til kejser.',
        '',
        'Hvad der derefter skete, gik hurtigt og dybt:',
        '',
        '- **Én skrift for alle.** Tegnene blev ensrettet. Det var hele',
        '  historiens klogeste træk, og det virker den dag i dag: Mennesker i',
        '  Kina taler meget forskellige sprog, men de skriver de samme tegn. En',
        '  købmand fra Kanton og en embedsmand fra Peking forstår næsten ikke',
        '  hinanden, når de taler — på papir forstår de hinanden med det samme.',
        '- **Ét mål, én vægt, én mønt.** Først dermed blev handel og skatter',
        '  overhovedet til at beregne.',
        '- **Et embedsværk i stedet for adelen.** Riget blev delt i distrikter,',
        '  ledet af embedsmænd, der kunne flyttes rundt, i stedet for arvelige',
        '  fyrster. Den, der intet kan arve, bygger heller ikke sin egen',
        '  magtbase op.',
        '- **En mur mod nord.** Ældre volde blev forbundet til én linje — mod',
        '  steppens rytterfolk.',
        '',
        'Prisen var høj. Hundredtusindvis af tvangsarbejdere døde på mur, veje',
        'og kanaler. Kritiske bøger blev brændt, ubekvemme lærde fjernet. Og',
        'kejseren, der frygtede døden, lod sig bygge et gravmæle, som verden',
        'aldrig havde set: en hær af omkring 8.000 legemsstore lerfigurer, hver',
        'med sit eget ansigt, opstillet i geledder under jorden. Først i 1974',
        'blev den fundet — af bønder, der ville grave en brønd.',
        '',
        'Hans dynasti holdt ikke femten år. Hans rige holdt i to tusind. Navnet',
        'blev i øvrigt også tilbage: „Qin" ligger formentlig i vores ord Kina.',
        '',
        '## Han-dynastiet: da to verdensriger fandtes på samme tid',
        '',
        'Efter Qin fulgte Han-dynastiet — og med det den tid, hvor Kinas',
        'historie og Roms historie næsten rører hinanden. Omkring år 100 e.Kr.',
        'fandtes der på jorden to riger af nogenlunde samme størrelse og',
        'nogenlunde samme befolkningstal: ét omkring Middelhavet og ét ved Den',
        'Gule Flod. Tilsammen herskede de formentlig over halvdelen af alle',
        'mennesker i verden. De kendte ikke hinanden.',
        '',
        'Han-dynastiet holdt sit rige sammen med andre redskaber end Rom. Rom',
        'satsede på legioner, veje og borgerret. Han-dynastiet satsede på et',
        'embedsværk — og endda et, man kunne eksaminere sig ind i. Den, der',
        'beherskede de klassiske tekster, kunne blive embedsmand, også fra små',
        'kår. Fuldstændig slået igennem blev det først århundreder senere, men',
        'tanken var der, længe før Europa fik den: embeder efter prøve i',
        'stedet for efter fødsel.',
        '',
        'Og så er der manden, som silkevejen skylder sin eksistens, uden at',
        'han ville det. I 138 f.Kr. sendte kejser Wu en udsending ved navn',
        '**Zhang Qian** mod vest. Opgaven: finde forbundsfæller mod',
        'xiongnu-folket, rytterfolkene i nord. Zhang Qian blev straks taget til',
        'fange, levede ti år hos xiongnu-folket, giftede sig dér, flygtede',
        'videre mod vest, så lande, som ingen i Kina havde vidst fandtes — og',
        'kom efter tretten år tilbage uden forbund.',
        '',
        'Men med beretninger. Om byer bag ørkenen. Om mennesker, der drak vin.',
        'Om de „himmelske heste" fra Fergana, som var større end alle',
        'kinesiske. Ud af denne fejlslagne mission voksede den handelsvej, som',
        'vi i dag kalder silkevejen — et navn, som i øvrigt først en tysk',
        'geograf fandt på i 1800-tallet.',
        '',
        'Ad denne rute gik mod vest: silke, lak, kanel, ferskner — og på et',
        'tidspunkt papiret, måske den mest skæbnesvangre kinesiske opfindelse',
        'overhovedet. Mod øst kom glas, guld, uld, druer, heste. Og med varerne',
        'rejste idéer: buddhismen kom fra Indien ad disse veje til Kina.',
        'Sygdomme rejste også med; i 100-tallet ramte en stor epidemi begge',
        'ender af ruten, uden at nogen anede hvorfor.',
        '',
        'Ikke et eneste menneske gik hele strækningen. Silken vandrede fra hånd',
        'til hånd, gennem dusinvis af mellemhandlere, et år eller længere. Rom',
        'og Kina sendte udsendinge til hinanden, som enten aldrig nåede frem',
        'eller aldrig vendte tilbage. De to største riger på jorden forblev et',
        'rygte for hinanden.',
        '',
        '## Tang-dynastiet: verdens største by',
        '',
        'Efter Han-dynastiets afslutning faldt Kina fra hinanden i delriger —',
        'og fandt sammen igen. Under Tang-dynastiet (618–907) nåede landet en',
        'blomstring, som man har svært ved at forestille sig.',
        '',
        'Hovedstaden Chang’an var omkring 750 e.Kr. med omkring en million',
        'indbyggere verdens største by — større end alt, hvad Europa havde på',
        'den tid; Rom var for længst skrumpet ind til en lille by. Chang’an var',
        'strengt planlagt: et rektangel, opdelt i 108 ommurede kvarterer, med',
        'en 150 meter bred pragtallé i midten. Om aftenen lukkede trommer',
        'portene, om morgenen åbnede de sig igen.',
        '',
        'Det mest forbløffende er, hvor åben denne by var. På vestmarkedet',
        'handlede sogdere, persere, indere, arabere og tyrkere. Der fandtes',
        'buddhistiske klostre, zoroastriske ildtempler, manikæiske og kristne',
        'menigheder. Persisk musik var mode, polo var overklassens sport, og en',
        'tid bar fornemme kvinder rytterdragt i steppestil. En kejserinde, Wu',
        'Zetian, regerede i eget navn — den eneste kvinde i Kinas historie.',
        '',
        'Men frem for alt: Det var en tid med digtning. Li Bai og Du Fu, Kinas',
        'to berømteste digtere, levede i dette århundrede. Deres digte lærer',
        'kinesiske børn den dag i dag udenad — ligesom Goethe i Tyskland.',
        '',
        'Så kom i 755 e.Kr. general An Lushans oprør, og blomstringen blev til',
        'en katastrofe: Hovedstaden faldt, millioner af mennesker døde eller',
        'mistede deres hjem. Tang-dynastiet regerede endnu i halvandet',
        'århundrede, men den store åbenhed var forbi. I 907 sluttede dynastiet.',
        '',
        '## Hvorfor Europa næsten ikke fortæller det',
        '',
        'Hvis alt det her passer — hvorfor optræder det så sjældent i',
        'europæiske skolebøger?',
        '',
        'En del af svaret er ganske enkelt afstand. Mellem Rom og Chang’an lå',
        '8.000 kilometer, ørkener, højland og et dusin fremmede riger. Man',
        'vidste lidt, fordi man kun kunne vide lidt.',
        '',
        'Den anden del er mere ubehagelig. Europa fortæller gerne',
        'verdenshistorien som en linje, der går fra Grækenland over Rom til',
        'Europa og når sit højdepunkt dér. I den linje er Kina ikke et kapitel,',
        'men højst en fodnote — interessant, eksotisk, men uden for',
        'hovedsporet. Da europæiske rejsende i 1200-tallet endelig kom til',
        'Kina og berettede, hvad de så — byer med millioner af mennesker,',
        'papirpenge, kulopvarmning —, troede man ikke på dem derhjemme. Marco',
        'Polo blev af sine samtidige spottende kaldt „Il Milione",',
        'pralhalsen.',
        '',
        'Og i 1800-tallet kom der endnu noget til: Europa var blevet Kina',
        'militært overlegent og fortalte historien derefter — som om Kina',
        'altid havde været tilbagestående. At papir, bogtryk, kompas og krudt',
        'alle stammer fra Kina og kom vestpå ad silkevejen, passede dårligt ind',
        'i den fortælling.',
        '',
        'Derfor er dette kapitel dobbelt interessant. Det fortæller ikke bare',
        'en historie, men viser også, hvordan en historie opstår: gennem',
        'udvælgelse. Den, der fortæller, bestemmer, hvad der kommer med.',
        '',
        'Og netop her støder denne synsvinkel mod sin grænse. Alt, hvad du',
        'lige har læst, er blikket udefra — blikket hos dem, der sad i den',
        'anden ende af vejen og købte stoffet uden at kende landet. Hvad denne',
        'historie betyder set fra dem, der oplevede den indefra, fortæller en',
        'anden stemme.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Den kinesiske synsvinkel',
      stimme: 'Hermes',
      text: [
        'Denne synsvinkel fortæller indefra — sådan som Kinas historie',
        'fortælles i Kina selv: af mennesker, hvis forfædre boede i Chang’an,',
        'som lærte Li Bais digte i skolen, og for hvem Kina aldrig var det',
        'fjerne land for enden af en vej, men midten. Også det er en',
        'fortælling — med egne begreber, egne spørgsmål og en selvforståelse,',
        'der er sin egen.',
        '',
        '## Midtens rige',
        '',
        '„Zhongguo" — Midtens rige. Sådan kalder Kina sig selv, og navnet er',
        'et program: Verden ordner sig omkring Kina. Ikke fordi Kina påstår at',
        'vide alting, men fordi den egen historie allerede blev fortalt fuldt',
        'ud hundreder af år før den første kontakt med Europa. En civilisation,',
        'der har sin egen kalender, sin egen skrift og sine egne dynastier,',
        'behøver ikke Europa som målestok. Den kinesiske fortælling begynder',
        'ikke med et hul, men med sin egen midte.',
        '',
        'Set herfra virker den europæiske synsvinkel på Kina som et spejl, der',
        'holdes på stor afstand: Det viser et billede — men et lille, uklart',
        'et, og det siger mere om den, der kigger ind i det, end om det, der',
        'betragtes.',
        '',
        '## Himlens søn og mandatet',
        '',
        'I den kinesiske fortælling står kejseren over alt — Himlens søn. Han',
        'hersker ikke af egen ret, men fordi himlen har lånt ham mandatet: Så',
        'længe han regerer godt, så længe markerne er dyrkede, embedsmændene',
        'ærlige og grænserne rolige, bliver herredømmet hos hans dynasti.',
        'Regerer han dårligt, trækker himlen mandatet tilbage — ofte gennem',
        'oprør, som historieskrivningen senere tolker som tegn på, at tiden',
        'var kommet.',
        '',
        'Denne tænkning gør den kinesiske fortælling anderledes end den',
        'europæiske. Europa spørger: „Hvad efterlod Rom?" Kina spørger: „Har',
        'dynastiet opfyldt sit mandat?" Og fordi mandatet vandrer, er',
        'dynastiskiftet ikke et sammenbrud af verden, men verdens orden —',
        'kredsløbet, hvor riget gang på gang samler sig på ny.',
        '',
        '## 221 f.Kr.: Slutningen på kaos',
        '',
        'For den kinesiske fortælling er Qin Shi Huangdi hverken en gåde eller',
        'en modsigelse, men svaret på et åbent sår: 250 år med stridende',
        'stater, hvor staterne rev hinanden i stykker. At en kejser gjorde en',
        'ende på det — med én skrift, ét mål, ét embedsværk — var set fra',
        'denne vinkel genoprettelsen af den orden, som himlen ville.',
        '',
        'Den kinesiske historieskrivning er dog ikke blind for prisen.',
        'Bogbrændingerne og tvangsarbejdet ved muren nævnes den dag i dag — de',
        'lærde i det følgende Han-dynasti tegnede Qin som nådesløs, og den dom',
        'lyder stadig efter. Men de tegner også samlingen: At et land, der var',
        'gået i opløsning i syv stridende dele, blev ét igen — det var set fra',
        'kinesisk side ikke tyranni, men fuldendelse. Og enheden holder den dag',
        'i dag, to tusind år senere. Det er den kinesiske fortællings svar til',
        'alle dem, der kun ser prisen: Se, hvad der er blevet af det.',
        '',
        '## Han-dynastiet: lærde i stedet for generaler',
        '',
        'Han-dynastiet gav riget den regeringsform, som det skulle beholde helt',
        'ind i den sidste kejsertid: lærdomsstaten. Den, der ville være',
        'embedsmand, måtte beherske de klassiske tekster — og kunne lære dem,',
        'uanset baggrund. Prøve i stedet for fødsel. Midtens rige blev ikke',
        'først og fremmest holdt sammen af soldater, men af en forvaltning, der',
        'legitimerede sig gennem uddannelse.',
        '',
        'For den kinesiske fortælling er det et stolthedspunkt, der er ældre',
        'end noget europæisk eksempel: en stat, der uddanner sin ledelse i',
        'stedet for at arve den. At Rom bandt sine borgere gennem rettigheder,',
        'er set fra denne vinkel et andet — ikke det eneste — svar på det',
        'samme spørgsmål: Hvordan holder man et kæmperige sammen?',
        '',
        '## Silkevejen: da verden kom til Chang’an',
        '',
        'Silkevejen er i den kinesiske fortælling ikke en handelsvej, ad',
        'hvilken varer flød mod vest — den er den port, gennem hvilken verden',
        'kom til Kina. Udsendinge og købmænd fra lande, som ingen i Kina havde',
        'hørt om, trådte frem for kejseren og bragte gaver. Set fra kinesisk',
        'side var det ikke handel mellem ligemænd, men verdens tribut til',
        'midten — den orden, som det skulle være. At karavanerne til gengæld',
        'trak tusindvis af kilometer gennem ørkener, bekræftede blot, hvor',
        'begæret det var, som Kina havde at give.',
        '',
        'Zhang Qian, udsendingen, der drog mod vest og kom tilbage efter',
        'tretten år, fortælles også i Kina — som en, der åbnede rigets øjne',
        'for verden. Men vægten ligger anderledes: ikke „vi opdagede vesten",',
        'men „vi lærte den verden at kende, som ville komme til os". Druerne,',
        'hestene, musikken — alt det kom ind, og Kina forblev, hvad det var:',
        'midten.',
        '',
        '## Tang-dynastiet: verdens største by — indefra',
        '',
        'Chang’an under Tang-dynastiet er i den kinesiske fortælling beviset',
        'på, at åbenhed er styrke. I byens 108 kvarterer boede sogdere og',
        'persere, indere og arabere; på vestmarkedet hørte man et dusin sprog.',
        'Set fra kinesisk side var det ingen undtagelse, men den naturlige',
        'orden i et rige, der var sikker på sin midte: Den, der er stærk, kan',
        'være åben.',
        '',
        'Og så er der poesien. Li Bai og Du Fu — deres digte lærer kinesiske',
        'børn den dag i dag udenad, ligesom tyske børn lærer Goethe. At et',
        'århundrede for tusind år siden frembragte den største digtning, det',
        'kinesiske sprog kender, er for den kinesiske fortælling vigtigere end',
        'noget slag. En civilisation kender man ikke på sine grænser, men på',
        'det, den efterlader — og Kina har Li Bai-digtene, konfucianismen,',
        'papiret og skriften.',
        '',
        'Da general An Lushan i 755 gjorde oprør, og Chang’an faldt, var det',
        'også i den kinesiske fortælling en katastrofe — men en velkendt en:',
        'Tang-dynastiets mandat hældede mod sin afslutning. Det var ikke riget,',
        'der sluttede, kun et dynasti. Kredsløbet fortsatte.',
        '',
        '## Hvorfor denne historie lyder anderledes',
        '',
        'To ting gør forskellen til den europæiske synsvinkel ud.',
        '',
        'For det første: Den kinesiske fortælling spørger ikke, hvorfor Europa',
        'vidste så lidt om Kina. Det spørgsmål har den aldrig haft brug for.',
        'For verdens midte var spørgsmålet „Hvorfor kender kanten os ikke?"',
        'meningsløst — historien fortsatte i Chang’an, hvad enten Rom kendte',
        'den eller ej. At Europa længe holdt Kina for et rygte, siger set fra',
        'kinesisk side noget om afstanden — og om perspektivet hos dem, der så',
        'fra kanten ind mod midten.',
        '',
        'For det andet: Også den kinesiske historieskrivning er skrevet af',
        'sejrherrer. Hvert nyt dynasti lod historien om det faldne skrive — og',
        'havde en interesse i at gøre dets mandattab tydeligt. Også i Kina',
        'gælder derfor: Den, der fortæller, vælger ud. Men valget falder',
        'anderledes ud end i Europa, fordi fortællingen tænker i kredsløb i',
        'stedet for i linje. Europa fortæller: Rom faldt, og noget gik til',
        'ende. Kina fortæller: Et dynasti sluttede, og riget samlede sig på ny.',
        '',
        'Det er ingen korrektion af den europæiske synsvinkel. Det er den',
        'anden halvdel af den samme historie — fortalt fra midten i stedet for',
        'fra kanten, indefra i stedet for udefra. Først når begge halvdele',
        'ligger der, kan man se, hvor meget af det, vi kalder „historie",',
        'afhænger af, hvor man står.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Nu ligger to fortællinger om de samme to tusind år side om side — og de',
    'lyder som to forskellige historier. Det er netop pointen.',
    '',
    '**Hvor de mødes:** Begge synsvinkler ser i Qin-samlingen det afgørende',
    'øjeblik — én skrift, ét mål, ét embedsværk. Begge fortæller silkevejen',
    'som den store forbindelse, ad hvilken varer, idéer og buddhismen',
    'vandrede. Og begge kalder Tang-tiden en blomstring, hvor Chang’an var',
    'verdens største by. Når det gælder hvad, ligger fortællingerne tættere',
    'på hinanden, end man skulle tro.',
    '',
    '**Hvor de skilles:** Den europæiske synsvinkel begynder med et hul — „vi',
    'vidste længe intet om Kina" — og spørger, hvorfor det var sådan, og',
    'hvorfor Europa næsten ikke fortæller denne historie. Den kinesiske',
    'synsvinkel begynder med sin egen midte: Kina havde aldrig brug for',
    'blikket udefra, historien fortsatte i Chang’an, hvad enten Rom kendte',
    'den eller ej. Den samme silkevej er for den ene fortælling en handelsvej,',
    'ad hvilken silke flød mod vest; for den anden den port, gennem hvilken',
    'verden kom til midten. Og de samme dynastiskifter er for den ene et tegn',
    'på forfald, for den anden mandatets orden — kredsløbet, hvor riget gang',
    'på gang samler sig på ny.',
    '',
    '**Hvad der følger deraf:** Begge fortællinger er skrevet af mennesker,',
    'der anser deres egen synsvinkel for den naturlige — Europa ser Kina som',
    'en fodnote i udkanten af sin verdenslinje, Kina ser sig selv som midten,',
    'som alting ordner sig omkring. Ordbrugen afslører det: „fjernt rygte" og',
    '„Midtens rige" beskriver den samme afstand — blot fra hver sin ende af',
    'vejen.',
    '',
    '**Din dom begynder her:** Hvis fortælling hjælper dig mest til at',
    'forstå, hvad der skete i disse to tusind år — den udefra eller den',
    'indefra? Og hvad ville der ændre sig i dit billede af Kina, hvis du kun',
    'havde hørt den ene eller kun den anden?',
  ].join('\n'),

  urteil: {
    frage: 'Den første kejser samlede et land, der havde ført krig i 250 år — med én skrift, ét mål, ét embedsværk. Det betalte hundredtusindvis af tvangsarbejdere, brændte bøger og dræbte lærde for. Var denne samling efter din mening prisen værd? Og hvem har egentlig lov til at beslutte sådan noget?',
    hinweis: 'Der er ikke noget rigtigt eller forkert her. Nævn to, tre grunde for din synsvinkel — og overvej, om en bonde ved muren, en embedsmand i hovedstaden og et menneske 2.000 år senere ville give det samme svar.',
  },

  quiz: [
    {
      frage: 'Er det rigtigt, at alle mennesker i Kina taler det samme sprog?',
      antworten: [
        'Ja, siden den første kejser har der kun været ét sprog.',
        'Nej — der tales meget forskellige sprog, men siden den første kejser skrives der med de samme skrifttegn.',
        'Nej, der findes også forskellige skrifter for hver region.',
      ],
      richtig: 1,
      erklaerung: 'Det er selve tricket ved rigssamlingen: Det var skriften, der blev ensrettet — ikke talen. Den, der næsten ikke forstår hinanden mundtligt, forstår hinanden på papir med det samme — derfor holder denne samling den dag i dag.',
    },
    {
      frage: 'Vidste Romerriget, at Kina fandtes?',
      antworten: [
        'Ja, der var jævnlig ambassadørtrafik mellem Rom og Chang’an.',
        'Nej, ingen i Rom havde nogensinde hørt om silke.',
        'Kun nogenlunde — man kendte silken og kaldte det fjerne land „Serica“, men vidste næsten intet om det.',
      ],
      richtig: 2,
      erklaerung: 'Rom kendte produktet, ikke landet. Den lærde Plinius skrev endda, at silken blev kæmmet af blade — om silkeorme havde han aldrig hørt. Omvendt kaldte Kina Rom „Da Qin“ og vidste tilsvarende lidt.',
    },
    {
      frage: 'Hvordan opstod silkevejen?',
      antworten: [
        'En udsending skulle finde forbundsfæller mod xiongnu-folket — det mislykkedes, men han bragte de første beretninger om vesten med hjem.',
        'En kinesisk kejser lod den bygge efter planen som handelsvej.',
        'Romerske købmænd undersøgte vejen fra vest.',
      ],
      richtig: 0,
      erklaerung: 'Zhang Qian drog i 138 f.Kr. af sted med en militær opgave, blev taget til fange og vendte først tilbage efter tretten år — uden forbund, men med viden. Ud af denne fejlslagne mission voksede antikkens vigtigste handelsvej.',
    },
    {
      frage: 'Hvilken by var omkring 750 e.Kr. verdens største?',
      antworten: [
        'Rom',
        'Chang’an, Tang-dynastiets hovedstad, med omkring en million mennesker.',
        'Konstantinopel',
      ],
      richtig: 1,
      erklaerung: 'Chang’an — det nuværende Xi’an — var en planlagt by med 108 ommurede kvarterer, hvor sogdere, persere, indere og arabere drev handel. Rom var på det tidspunkt for længst skrumpet ind til en lille by.',
    },
    {
      frage: 'Er det rigtigt, at papir er en kinesisk opfindelse?',
      antworten: [
        'Nej, papir kom fra Egypten.',
        'Ja — og det vandrede ad silkevejen mod vest sammen med kompas, bogtryk og krudt.',
        'Ja, men det forblev begrænset til Kina helt ind i nyere tid.',
      ],
      richtig: 1,
      erklaerung: 'Papyrus fra Egypten er noget andet end papir. Ægte papir stammer fra Kina og brugte omkring tusind år på at nå Europa. Uden den lange vej ville der ikke findes nogen europæisk bogtrykkerkunst — og uden den næppe den nyere tid, som vi kender den.',
    },
  ],

  // Kortet ligger i karten/china.js — her er kun fasehenvisningerne
  // oversat (phasen → karteHinweise), ikke selve kortet.
  karteHinweise: [
    {
      label: '221 f.Kr.',
      hinweis:
        'Efter 250 års krig mellem de stridende stater er der én sejrherre tilbage: Qin. Den første kejser forener landet mellem Den Gule Flod og Yangtze — og gør straks alting ens: én skrift, ét mål, én sporvidde, én mur mod nord.',
    },
    {
      label: '100 e.Kr.',
      hinweis:
        'Han-dynastiet på sit højdepunkt — omtrent lige så stort og lige så tætbefolket som Romerriget på samme tid. Gennem den smalle Hexi-korridor rækker det helt ud i Tarimbækkenet og holder dermed silkevejen åben.',
    },
    {
      label: '750 e.Kr.',
      hinweis:
        'Tang-dynastiet i fuld flor: Chang’an er med omkring en million indbyggere verdens største by, og silkevejen er mere travl end nogensinde. På hovedstadens gader høres sogdisk, persisk, tyrkisk og sanskrit. Tryk på ruten — den slutter ikke ved billedets kant.',
    },
  ],
};

module.exports = kina;
