// Tema: Trediveårskrigen (1618–1648).
//
// Dansk oversættelse af utils/themen/dreissigjaehriger-krieg.js. Feltnavnene
// følger det tyske skema (aufhaenger, perspektiven, synthese, urteil, quiz) —
// kun teksterne er oversat. Kortet er erstattet af karteHinweise: de tre
// faser (label + hinweis) fra karten/dreissigjaehriger-krieg.js.
//
// Stand: Runde 12. Kapitel tre i nyere tids bue (notizen/kapitel-planung.md).
// Akserne er de samme som i originalen: først stemmen oppefra — dem, der
// besluttede: kejseren, kurfyrsterne, kongerne af Danmark, Sverige og
// Frankrig, feltherrerne. Derefter stemmen nedefra: de berørte, byerne og
// landsbyerne. Ingen side dæmoniseres, ingen bagatelliseres (jf. TONE-REGEL
// i CLAUDE.md). Quizspørgsmålene er vidensspørgsmål — denne app spørger
// ikke om skyld.
//
// Rene data — ingen UI-imports (arkitekturregel).

const trediveaarskrigen = {
  id: 'dreissigjaehriger-krieg',
  titel: 'Trediveårskrigen',
  epoche: '1618–1648',

  aufhaenger: {
    frage: 'Tre mænd flyver ud af et vindue i Prag og overlever — tredive år senere er Midteuropa ødelagt, og der er sluttet en fred, der den dag i dag præger landkortet. Hvordan bliver en strid om kirker til en krig, som til sidst halvdelen af Europa er involveret i?',
    text: [
      'Den 23. maj 1618 kastede bøhmiske adelsmænd to kejserlige statholdere og',
      'deres skriver ud af et vindue på Prags borg. Sytten meter ned. Alle tre',
      'rejste sig igen og løb væk.',
      '',
      'Det lyder næsten som en anekdote — og det er begyndelsen på tredive års',
      'krig. Ikke fordi et vindueskast er så magtfuldt, men fordi alt det, der',
      'havde hobet sig op gennem årtier, lå i det kast: spørgsmålet om, hvem',
      'der i riget bestemmer over troen. Spørgsmålet om, hvor meget magt en',
      'kejser har over fyrster, der selv har valgt ham. Og spørgsmålet om, hvem',
      'der sætter dagsordenen i Europa.',
      '',
      'Det, det blev til, kaldte de involverede selv ikke for „Trediveårskrigen"',
      '— navnet kom senere. De oplevede flere krige efter hinanden: først den',
      'bøhmiske, så den danske, så den svenske, til sidst den fransk-svenske.',
      'Hver eneste begyndte, fordi nogen regnede ud, at det kunne betale sig at',
      'blande sig. Og hver eneste endte, uden at noget var afgjort.',
      '',
      'Dette kapitel fortæller først oppefra: om dem, der besluttede — kejser,',
      'kurfyrster, konger, feltherrer. De har skrevet deres grunde ned, i',
      'breve, traktater og instrukser; man kan se dem regne. Hvad deres',
      'beslutninger anrettede dernede, fortæller den anden stemme.',
    ].join('\n'),
  },

  // „Historie i bevægelse" — kortet kommer efter opmærksomhedsfangeren og før
  // perspektiverne. Her som karteHinweise (de tre faser fra kortfilen).
  karteHinweise: [
    {
      label: '1618',
      hinweis:
        'Riget på krigens tærskel. Den blege linje er rigsgrænsen — og mere kan man ærligt ikke tegne af riget: Det var et kludetæppe, ikke en blok. Inden for denne linje lå over tre hundrede herskaber med egen ret, egen mønt og egen tro. Kun det, der virkelig havde grænser, er farvelagt. Læg mærke til de habsburgske lande: Bøhmen, hvor oprøret begynder i maj 1618, hører dertil — som valgkongerige med garanteret trosfrihed. Fordi alle flader har samme farve, smelter naboer som de Spanske Nederlande og republikken sammen til en blok; kun titlerne siger, hvem der er hvem.',
    },
    {
      label: '1631–1632',
      hinweis:
        'Krigen på sit højdepunkt. I maj 1631 bliver Magdeburg erobret og brænder ned; i september slår Gustav Adolf sammen med Kursachsen ved Breitenfeld den kejserlig-ligistiske hær, og i november 1632 falder han selv ved Lützen. Den store flade i riget er med vilje navngivet, som den er ment: en hærs rækkevidde, ikke et statsområde. Det, der lå inden for, var besat og betalte kontributioner — og kunne i næste felttog være tabt igen. Bøhmen ligger bevidst uden for, selv om saksiske tropper i november 1631 endda stod i Prag: De blev kun en vinter.',
    },
    {
      label: '1648',
      hinweis:
        'Freden i Westfalen, underskrevet den 24. oktober 1648 i Münster og Osnabrück. På kortet ser man tre ting: Sverige sidder nu selv i riget — i Forpommern, i Wismar, i Bremen og Verden. Frankrig har de habsburgske rettigheder i Elsass. Og Republikken Nederlandene og Schweiz er formelt ude af riget. Ikke til at se er det vigtigste: Rigsstænderne fik landshøjhed og ret til at slutte egne forbund — grænserne i riget blev, men den, der herskede derinde, var fra nu af næsten suveræn. Og krigen var ikke slut alle steder: Spanien og Frankrig kæmpede videre til 1659.',
    },
  ],

  perspektiven: [
    {
      id: 'herrscher-sicht',
      name: 'Kejserens, fyrsternes og feltherrernes syn',
      stimme: 'Opus',
      text: [
        'Dette er synet hos dem, der besluttede: kejseren i Wien, de syv',
        'kurfyrster, kongerne af Danmark, Sverige, Frankrig og Spanien,',
        'feltherrerne, der opstillede og solgte hære. Det er fortællingen fra',
        'kabinetterne og feltolejrene — dér, hvor man førte krig som et',
        'regnskab.',
        '',
        'Denne stemme har en fordel og en blind vinkel. Fordelen: Den kan',
        'forklare, hvorfor hvert enkelt skridt så fornuftigt ud fra den',
        'synsvinkel, som den, der tog det, havde — og det er det egentlig',
        'skræmmende ved denne krig. Den blinde vinkel: I det regnskab optræder',
        'de mennesker, der betalte prisen, som poster. Som „kontribution", som',
        '„kvarter", som „hvervning". Ikke som mennesker.',
        '',
        'Begge stemmer i dette kapitel er lige meget værd. At denne her står',
        'først, er ikke en rangorden, men blot den rækkefølge, teksten blev',
        'skrevet i.',
        '',
        '## 1618: Et vindue i Prag',
        '',
        'Bøhmen var et valgkongerige, og dets stænder var overvejende',
        'protestantiske. I 1609 havde kejser Rudolf II. i **Majestætsbrevet**',
        'garanteret dem trosfrihed — ikke af overbevisning, men fordi han havde',
        'brug for deres støtte. Da kirker bagefter blev lukket og revet ned i',
        'to protestantiske byer, så stænderne retten som brudt.',
        '',
        'Den 23. maj 1618 kom de til borgen og kastede de to statholdere ud af',
        'vinduet. Det var ikke et vredesudbrud, men en formel handling med et',
        'forbillede: I Bøhmen havde man gjort det samme i 1419. Budskabet var:',
        'Vi siger kongen op på lydigheden.',
        '',
        'Fra stændernes synsvinkel var det nødværge. Fra Wiens synsvinkel var',
        'det oprør — og ærkehertug **Ferdinand**, der snart skulle blive',
        'kejser, var ikke manden for kompromiser: dybt troende, opdraget af',
        'jesuitter, overbevist om, at en hersker hæfter over for Gud for sine',
        'undersåtters tro. Han havde allerede trængt protestantismen tilbage i',
        'sine egne lande. Det vidste bøhmerne. Netop derfor handlede de.',
        '',
        'De afsatte Ferdinand og valgte en ny konge: **Frederik 5. af Pfalz**,',
        'calvinistisk kurfyrste og svigersøn til den engelske konge. Han sagde',
        'ja — mod rådet fra næsten alle, der kunne regne. Den 8. november 1620',
        'tabte hans hær ved **Det Hvide Bjerg** uden for Prag på godt to timer.',
        'Han flygtede og gik over i historien som „Vinterkongen".',
        '',
        'Det, der fulgte, viser, hvordan sejrherrer tænkte dengang: I 1621 blev',
        '27 ledere henrettet på Den Gamle Bytorv, den protestantiske adel fik',
        'konfiskeret sine ejendomme, og landet blev gjort katolsk. En del af',
        'den inddragne ejendom gjorde en hidtil middelmådig bøhmisk adelsmand',
        'meget rig — han hed Albrecht von Wallenstein.',
        '',
        '## Hvorfor et vindueskast kunne udløse en krig',
        '',
        'For at forstå, hvorfor det ikke var forbi efter to år, må man vide,',
        'hvordan riget var bygget op.',
        '',
        'Det Tysk-Romerske Rige var ikke en stat. Det var et forbund af over',
        'tre hundrede herskaber: kurfyrstendømmer, fyrstendømmer, stifter,',
        'rigsstæder, rigsriddere — hver med egen ret, egen mønt og egne',
        'tropper. I spidsen stod en kejser, der blev valgt, og som hverken fik',
        'penge eller hær uden rigsstændernes samtykke.',
        '',
        'Og oven over det lå siden 1555 **religionsfreden i Augsburg** med sin',
        'berømte formel: **cuius regio, eius religio** — hvis landet, hans',
        'religion. Man læser den oftest som en trosregel. Den var først og',
        'fremmest en magtregel: Den gjorde hver eneste landsfyrste til herre',
        'over kirken i sit land, inklusive dens ejendom. Den, der skifter',
        'trosretning, skifter også indtægterne.',
        '',
        'Freden havde tre konstruktionsfejl, og alle tre eksploderede fra',
        '1618:',
        '',
        '- **Calvinisterne** var ikke nævnt i den — i 1555 fandtes de næsten',
        '  ikke i riget. Tres år senere var Pfalz, Hessen-Kassel og',
        '  Brandenburg reformerte, og freden beskyttede dem ikke.',
        '- **Det gejstlige forbehold** fastslog, at en biskop, der blev',
        '  protestant, måtte afgive sit stift. Det holdt Norden sig ikke til:',
        '  Halberstadt, Magdeburg, Bremen og mange andre stifter var for',
        '  længst i protestantiske hænder.',
        '- Og rigsdomstolene, der skulle have mæglet i sådanne stridssager,',
        '  var selv blokeret af trosretningerne.',
        '',
        'Den, der i dag spørger, om dette var en religionskrig eller en',
        'magtkrig, stiller et spørgsmål, som samtiden ikke ville have forstået.',
        'For dem var begge dele det samme: kirkegods var magt, trosfrihed var',
        'en ret, stænderne havde over for fyrsten, og en alliance sluttede man',
        'med den, der brugte den samme katekismus — indtil det ikke længere',
        'kunne betale sig.',
        '',
        '## 1629: Restitutionsediktet — sejren, der gik for vidt',
        '',
        'Kejseren vandt første halvdel af krigen. Bøhmen var knust, Pfalz',
        'erobret, og i 1623 blev kurværdigheden overført til Bayern — en',
        'uhørt begivenhed, for dermed ændrede kejseren på egen hånd, hvem der',
        'fremover skulle vælge ham. I 1625 greb den danske konge **Christian',
        '4.** ind, samtidig som protestantisk fyrste og som hertug af Holsten',
        'og svenskernes rival om Østersøen; i 1629 måtte han give op i freden',
        'i Lübeck.',
        '',
        'På højdepunktet af sin magt udstedte Ferdinand 2. i marts 1629',
        '**restitutionsediktet**: Alt kirkegods, der siden 1552 var blevet',
        'protestantisk, skulle gives tilbage. To ærkestifter, et dusin',
        'stifter, hundredvis af klostre.',
        '',
        'Juridisk lod det sig begrunde — sådan stod der i freden fra 1555.',
        'Politisk var det krigens største fejl. For det første fratog det de',
        'protestantiske fyrster grundlaget for deres besiddelser. Og for det',
        'andet forskrækkede det også den katolske side: En kejser, der kunne',
        'række så langt, var farlig for enhver fyrste. I sommeren 1630 tvang',
        'kurfyrsterne — de katolske i spidsen — kejseren i Regensburg til at',
        'afskedige sin egen feltherre. De frygtede ham mere end fjenden.',
        '',
        '## Wallenstein: krigens entreprenør',
        '',
        '**Albrecht von Wallenstein** er den skikkelse, man bedst forstår',
        'beslutningstagernes logik på — og dens grænse.',
        '',
        'Han var bøhmisk adelsmand, døbt protestant, blevet katolik, rig',
        'gennem ægteskab og gennem salget af godserne efter 1620. I 1625',
        'tilbød han kejseren noget, ingen andre kunne tilbyde: en hel hær,',
        'opstillet for egen regning. Kejseren havde ingen penge; Wallenstein',
        'havde kredit. Han blev hertug af Friedland, senere også af',
        'Mecklenburg, og førte hære på tidvis over hundrede tusind mand.',
        '',
        'De blev betalt efter et princip, der blev krigens kernesætning:',
        '**Krigen ernærer krigen.** Hæren hentede i landet, hvad krigskassen',
        'ikke kunne give. Byer og landskaber måtte betale **kontributioner**',
        '— faste, formelt udregnede beløb, mod tilsagn om ikke at blive',
        'plyndret. Den, der ikke betalte, fik soldaterne i huset.',
        '',
        'Man må se, hvad der var nyt, og hvad der var gammelt. Gammelt var, at',
        'hære forsørgede sig i landet; det gjorde alle. Nyt var',
        'størrelsesordenen og regnskabets koldblodighed: Wallenstein gjorde',
        'nødløsningen til et system og krigen til en forretning, der bar sig',
        'selv — og netop derfor ikke holdt op igen. En hær, der ernærer sig i',
        'landet, må drage videre, så snart landet er tømt.',
        '',
        'Det er ingen bagtalelse udefra. Det var hensigten, den stod i',
        'traktaterne, og den gjaldt for alle sider — kejserlige, ligistiske,',
        'svenske, franske. Kun på ét punkt fejlede Wallenstein synligt: I 1628',
        'belejrede han **Stralsund** og fik ikke byen, fordi den blev forsynet',
        'over søen. Den, der ikke har Østersøen, vinder ikke i Norden. Den',
        'lære drog en anden to år senere.',
        '',
        'Afskediget i 1630, hentet tilbage i 1632 blev Wallenstein den 25.',
        'februar 1634 i **Eger** slået ihjel af sine egne officerer. Kejseren',
        'havde erklæret ham for afsat og beordret ham pågrebet, død eller',
        'levende; Wallenstein havde på egen hånd forhandlet med fjenden. Om',
        'det var forræderi eller forsøget på at få krigen til at ende,',
        'strides forskningen om den dag i dag. Sikkert er: Manden, der havde',
        'gjort krigen finansierbar, blev ryddet af vejen af det system, han',
        'selv havde bygget.',
        '',
        '## Magdeburg 1631 — hvad det system kostede',
        '',
        'Den 20. maj 1631 faldt **Magdeburg**, belejret siden november af',
        'Pappenheim og siden april af Tilly. Under stormen brød der ild ud; af',
        'omkring 25 000 til 30 000 mennesker døde omkring 20 000. Det var',
        'krigens største enkeltkatastrofe, og byens navn blev til et ord: „at',
        'magdeburgisere".',
        '',
        'Hvem der antændte ilden, er omstridt den dag i dag. Tilly beskyldte',
        'forsvarerne, de protestantiske flyveskrifter de kejserlige tropper;',
        'forskningen holder begge dele for mulige og ingen af dem for bevist.',
        '',
        'Det, der ikke er omstridt, hører hjemme i denne fortælling, fordi det',
        'lægger beslutningstagernes regnskab åbent: Tillys hær havde stået',
        'foran byen i måneder, var ikke blevet betalt og havde fortæret',
        'omegnen. Plyndringen af en erobret by var den lovede løn. Det var',
        'ingen glipp fra enkelte umennesker — det var følgen af en beslutning',
        'om, hvordan man betaler for en krig.',
        '',
        'Det bliver ikke bedre af det. Det bliver bare forklarligt. Og den,',
        'der kan forklare, ser også, hvem der bar ansvaret: ikke lejesoldaten,',
        'der gik i brechen, men dem, der sendte ham derop uden sold.',
        '',
        'Magdeburg blev desuden Europas første store mediekrig. Hundredvis af',
        'flyveskrifter og billeder gik gennem hele kontinentet — og fordi',
        'bogtrykkerkunsten efterhånden var blevet billig, kunne hver side',
        'udbrede sin version. Den, der har denne apps ledetanke i hovedet,',
        'finder her et tidligt eksempel: Samme nat, to fortællinger, begge',
        'trykt, begge med egne interesser.',
        '',
        '## Gustav Adolf 1630–1632',
        '',
        'Den 6. juli 1630 landede **Gustav Adolf**, konge af Sverige, med',
        'omkring 13 000 mand på Usedom. Det blev først muligt gennem',
        'våbenstilstanden i Altmark i 1629, som havde afsluttet hans krig mod',
        'Polen.',
        '',
        'Han kom som protestanternes frelser — og det mente han alvorligt.',
        'Han var en from lutheraner, der bad med sine tropper hver dag, og i',
        'riget så mange i ham „løven fra Midnat", som skulle befri',
        'trosfællerne.',
        '',
        'Han kom samtidig som magtpolitiker, og også det kan man åbent læse',
        'sig til. Sverige ville beherske Østersøen — ingen fjende ved dens',
        'sydkyster, ingen kejserlig flåde, der truede told og handel. Og han',
        'kom med fremmede penge: I traktaten i Bärwalde i 1631 lovede det',
        'katolske Frankrig ham årlige subsidier.',
        '',
        'Militært var han sin tids mest moderne feltherre: mindre, mobile',
        'enheder, salveild i stedet for dybe blokke, lette kanoner, som man',
        'kunne flytte midt i slaget, og dertil en hård disciplin, der',
        'begrænsede plyndringer — så længe solden kom. Den 17. september 1631',
        'slog han sammen med Kursachsen ved **Breitenfeld** nord for Leipzig',
        'Tillys hær, første gang overhovedet. I 1632 drog han til Franken, til',
        'Rhinen og over Lech til Bayern; i maj stod han i München.',
        '',
        'Den 16. november 1632 faldt han ved **Lützen** — i tågen, adskilt fra',
        'sine folk, syvogtredive år gammel. Svenskerne beholdt slagmarken.',
        '',
        'Og så skete der det, som fortællingen om den store feltherre har',
        'allersværest ved at bære: næsten ingenting. Rigskansler Oxenstierna',
        'førte krigen videre, i seksten år. Krigen havde løsrevet sig fra',
        'enkelte mænds vilje.',
        '',
        '## 1635: En kardinal skifter side',
        '',
        'I 1634 led svenskerne et hårdt nederlag ved Nördlingen. I 1635',
        'sluttede kejseren freden i Prag med Kursachsen: Restitutionsediktet',
        'blev reelt opgivet, man aftalte 1627 som skæringsår, og Lausitz gik',
        'til Sachsen. En luthersk kurfyrste kæmpede nu ved den katolske',
        'kejsers side mod de lutherske svenskere. Krigen kunne være endt her.',
        '',
        'Den endte ikke, fordi **kardinal Richelieu** regnede i Paris.',
        'Frankrig var katolsk, dets ledende minister en kirkefyrste — og begge',
        'så den egentlige fare ikke i kætteriet, men i omklamringen fra',
        'Habsburg: Spanien i syd og vest, Østrig i øst. I årevis havde',
        'Frankrig derfor betalt Sverige i stedet for selv at kæmpe. I 1635',
        'erklærede det Spanien krig.',
        '',
        'Den regel, Richelieu handlede efter, har et navn: **statsræson** —',
        'hvad der gavner staten, er tilladt, også mod ens egen trosretning.',
        'Den 19. maj 1643 slog en fransk hær under den enogtyveårige hertug af',
        'Enghien ved **Rocroi** den spanske hær, og de spanske tercios ry for',
        'at være uovervindelige var forbi.',
        '',
        'Senest her kan fortællingen om den rene religionskrig ikke længere',
        'holdes. Men den var heller aldrig helt forkert: For Ferdinand 2. var',
        'hans landes tilbagevenden til den gamle kirke et',
        'samvittighedsspørgsmål, for Gustav Adolf var beskyttelsen af',
        'trosfællerne et ægte motiv, og menneskene i landsbyerne mærkede meget',
        'vel, hvilken præst der stod i kirken, efter at tropperne var draget',
        'igennem. Tro og magt lå ikke ved siden af hinanden, men i hinanden.',
        '',
        '## Hvorfor tredive år?',
        '',
        'Beslutningstagernes ærligste svar på det spørgsmål lyder: fordi',
        'ingen kunne vinde, og ingen ville tabe.',
        '',
        '- **Ingen sejr var afgørende.** Efter hvert vundet slag var fjenden',
        '  slået, men ikke færdig; hære kunne opstilles på ny for penge, og',
        '  penge kom fra det besatte land.',
        '- **Hærene havde egne interesser.** Officerer havde investeret i',
        '  deres regimenter og ville have sold, bytte og erstatning. Fred',
        '  betød arbejdsløshed.',
        '- **Hver side havde minimumskrav**, som den ikke kunne gå under uden',
        '  at tabe ansigt — og forbundsfæller, der havde egne regninger',
        '  udestående.',
        '- **Naboerne tillod det ikke.** Så snart en side blev for stærk,',
        '  trådte nogen ind: Danmark 1625, Sverige 1630, Frankrig 1635. En',
        '  balance gennem indgriben — det samme princip, som Europa bagefter',
        '  lavede politik efter i to hundrede år.',
        '',
        '## 1648: Münster og Osnabrück',
        '',
        'Der blev forhandlet fra 1644, i to byer, fordi trosretningerne ikke',
        'ville sidde ved samme bord: den katolske side med Frankrig i',
        '**Münster**, den protestantiske med Sverige i **Osnabrück**. Omkring',
        '150 gesandtskaber, ikke ét eneste møde med alle involverede, årelang',
        'strid om rangfølger og tiltaleformer. Og imens fortsatte krigen — man',
        'forhandlede for at forbedre sin egen position.',
        '',
        'Den 24. oktober 1648 blev der underskrevet. **Freden i Westfalen**',
        'ordnede det, den ikke kunne afgøre:',
        '',
        '- Religionsfreden i Augsburg blev bekræftet og udvidet til at gælde',
        '  de reformerte. For kirkegodset gjaldt **normalåret** 1624: Det,',
        '  der i det år tilhørte hvem, blev ved med at tilhøre dem — en',
        '  skæringsdataregel i stedet for en dom om, hvem der havde ret.',
        '- Rigsstænderne fik **landshøjhed** og ret til at slutte egne forbund,',
        '  så længe de ikke var rettet mod kejser og rige. Riget blev',
        '  endegyldigt til en sameksistens af næsten suveræne fyrster.',
        '- Sverige fik Forpommern med Rygen, Wismar, Bremen og Verden — og',
        '  dermed sæde og stemme i rigsdagen. Frankrig fik de habsburgske',
        '  rettigheder i Elsass, Brandenburg fik Bagpommern og flere stifter,',
        '  Bayern beholdt kurværdigheden, og Pfalz fik en ny, ottende.',
        '- Republikken Nederlandene og det Schweiziske Edsforbund trådte',
        '  formelt ud af riget.',
        '- En almindelig amnesti genoprettede tilstanden fra 1618 — med én',
        '  undtagelse, som kejseren forbeholdt sig: I sine arvelande forblev',
        '  rekatoliseringen. Bøhmen, hvor det hele var begyndt, fik intet',
        '  tilbage.',
        '',
        'Paven protesterede mod traktaten; den blev sluttet. Mellem Frankrig',
        'og Spanien fortsatte krigen helt til 1659.',
        '',
        'Hvorfor denne fred regnes for det moderne Europas fødselsattest: Den',
        'behandlede alle involverede som ligeværdige traktatparter — store og',
        'små, katolske og protestantiske — og den gjorde religionen til en',
        'sag, man ordner i stedet for at afgøre. Bagefter forhandlede Europa',
        'ikke længere om sandheden, men om grænser, rettigheder og balance.',
        'Det er mindre ophøjet end en sejr, og det er grunden til, at',
        'kongresser siden har været det foretrukne middel.',
        '',
        '## De ubehagelige steder i denne fortælling',
        '',
        'Alt det hidtil sagte er fortalt oppefra, og oppefra ser en krig ud',
        'som en række fornuftige skridt. Fire ting må denne stemme selv sige',
        'højt, for at regnskabet kan stemme.',
        '',
        '**For det første: tallene.** I riget levede der før krigen',
        'skønsmæssigt 16 til 18 millioner mennesker, efter krigen måske 10 til',
        '13 millioner — et tab på omkring en tredjedel. I Mecklenburg,',
        'Pommern, Thüringen og Württemberg døde regionalt op til to',
        'tredjedele; i nordvest, i Hamborg og i alpelandene forblev det',
        'derimod forholdsvis roligt. De fleste døde faldt ikke i slag, men af',
        'sult og sygdomme, der fulgte hærene. **Tallene er omstridte** og',
        'bygger på skattelister og kirkebøger, ikke på tællinger; sikkert er',
        'størrelsesordenen, ikke de enkelte cifre.',
        '',
        '**For det andet: Den, der betalte prisen, havde ikke besluttet den.**',
        'Beslutningstagerne førte i tredive år en krig, hvor de selv sjældent',
        'kom i livsfare — Gustav Adolf er undtagelsen, der springer i øjnene.',
        'De opstillede lejesoldathære, de ikke kunne betale, og sendte dem ind',
        'i landskaber, der måtte dække udgifterne. „Krigen ernærer krigen" er',
        'ingen naturlov. Det var en beslutning, og man kan læse i traktaterne,',
        'hvem der traf den.',
        '',
        '**For det tredje: Trosretningen var ofte påskuddet og sjældent hele',
        'grunden.** En katolsk kardinal betalte lutherske hære. En luthersk',
        'kurfyrste kæmpede for den katolske kejser. Det katolske Bayern',
        'forhandlede i 1647 i al hemmelighed om en egen våbenstilstand. Den,',
        'der ved det, bør heller ikke påstå det modsatte: Troen var ikke kun',
        'en maske. Den var ægte for mange — og netop derfor så anvendelig.',
        '',
        '**For det fjerde: Disse mænd var hverken helgener eller uhyrer.**',
        'Wallenstein var en genial organisator og en skruppelløs',
        'krigsentreprenør. Gustav Adolf var en from mand, en reformator af',
        'krigsvæsenet — og en erobrer, hvis hære levede som alle andres.',
        'Tilly var en disciplineret feltherre og står for Magdeburg. Ferdinand',
        '2. handlede ud fra ægte overbevisning og anrettede dermed frygtelig',
        'skade. Den, der gør dem til helte, forstår ikke krigen; den, der gør',
        'dem til monstre, gør det heller ikke.',
        '',
        '## Og den anden side?',
        '',
        'Denne fortælling har et sted, hvor den tier. Den kan sige, hvor mange',
        'regimenter der stod hvor, hvad en kontribution kostede, og hvilken',
        'artikel i fredstraktaten der bilagde hvilken strid. Den kan ikke',
        'sige, hvordan det var, når det regiment kom til landsbyen.',
        '',
        'Det, der i beslutningstagernes akter hedder „vinterkvarter", hed i en',
        'landsby: fremmede mænd i huset, hele vinteren, med våben, som skulle',
        'have mad og forplejning. Det, der hedder „kontribution", hed: give',
        'sædekornet fra sig, det, der var tiltænkt næste år. Det, der hedder',
        '„hvervning", hed: sønnen tager med, frivilligt eller ej — og hærene',
        'var fulde af mennesker, der selv var blevet plyndret før.',
        '',
        'Disse spørgsmål kan beslutningstagernes syn ikke besvare: Hvordan',
        'overlever man tredive års krig? Hvorfor døde flere mennesker af sult',
        'og sygdomme end i slagene? Hvordan indretter man sig i en verden,',
        'hvor en anden hær to gange om året opkræver skatterne, og præsten',
        'skifter trosretning? Og hvem var lejesoldaterne egentlig, før de blev',
        'lejesoldater?',
        '',
        'De hører til en anden stemme: de berørtes syn, byernes og',
        'landsbyernes. Den er lige så meget værd som denne her — og den har',
        'mere at fortælle, end beslutningstagernes akter aner.',
      ].join('\n'),
    },
    {
      id: 'betroffene-sicht',
      name: 'De berørtes syn',
      stimme: 'Hermes',
      text: [
        'Denne stemme tilhører de mennesker, i hvis landsbyer og byer krigen',
        'fandt sted: bønderne, der måtte give sædekornet fra sig;',
        'håndværkerne, hvis værksted betalte „kontributionen"; præsterne, der',
        'skrev de døde ind i kirkebøgerne; mødrene, hvis sønner tog med, for',
        'ellers var alting tabt.',
        '',
        'Den har andre kilder end den første stemme. Beslutningstagerne',
        'efterlod traktater, felttogsplaner, denkskrifter. De berørte',
        'efterlod dagbøger, regnskabsbøger, kirkebøger, retsakter — og',
        'erindringen, der blev givet videre i familier og landsbyer. Fra',
        'disse kilder taler ikke det, der blev besluttet, men det, der kom',
        'frem.',
        '',
        'Og også denne stemme har en blind vinkel, som den selv må sætte navn',
        'på: Den, der kunne skrive, var ikke den fattigste. De allermest',
        'fattige, som ikke førte bøger, har næsten ingen stemme efterladt.',
        'Det, vi ved om dem, ved vi fra andre — også det hører til denne',
        'fortællings ærlighed.',
        '',
        '## Da krigen kom til landsbyen',
        '',
        'Krigen kom ikke som et slag. Den kom som indkvartering. Det, der i',
        'akterne hed „vinterkvarter", hed i landsbyen: fremmede mænd i huset,',
        'hele vinteren, med våben, som skulle have forplejning — og når maden',
        'slap op, tog de kvæget, og når kvæget var væk, tog de det, der i',
        'huset var noget værd.',
        '',
        'Det, der hed „kontribution", hed i landsbyen: give sædekornet fra',
        'sig. Ikke overskuddet — sædekornet, der var tiltænkt næste år. Og',
        'fordi næsten hver part gjorde sådan, betalte en landsby ofte to gange',
        'om året til to forskellige hære, nogle gange til tre. Der fandtes',
        'landsbyer, der betalte samtidig til kejseren, til svenskerne og til',
        'franskmændene, fordi ingen vidste, hvem der ville have magten næste',
        'måned. Den, der ikke kunne betale, fik udpantning; den, der gjorde',
        'modstand, fik sin landsby brændt.',
        '',
        '„Krigen ernærer krigen" lyder i feltolejrene som et regnskab. I',
        'landsbyen lød den sådan: Om efteråret kom et regiment og tog høsten.',
        'Om vinteren kom det næste og tog kvæget. Om foråret var der intet',
        'tilbage, og alligevel kom der om sommeren igen et regiment.',
        '',
        '## Lejesoldaterne — hvem de virkelig var',
        '',
        'Den første stemme taler om hære, der blev opstillet og solgt. Denne',
        'stemme må sige, hvem der var i dem — for det er en af denne krigs',
        'mest ubehagelige sandheder: Mange soldater havde før været bønder.',
        'Den, der havde mistet alt, havde ingen grund mere til at blive i',
        'landsbyen; den, der tog med, fik i det mindste det, byttet kunne',
        'give. Hærene var fulde af mennesker, der selv var blevet plyndret',
        'før — og som nu stod på den anden side af plyndringen, fordi',
        'overlevelse ikke har en ren side.',
        '',
        'Vi kender én af dem ved navn: **Peter Hagendorf**, en lejesoldat,',
        'der fra 1625 til 1649 — hele krigen igennem — førte dagbog. Han drog',
        'gennem halvdelen af Europa, giftede sig, mistede kone og børn, drog',
        'videre. I hans dagbog står der ved siden af marcherne og plyndringerne',
        'sætninger om hans børn, hans ægteskab, hans tro. Historien kender ham',
        'som „lejesoldat" — han selv så sig som far og ægtemand, der på en',
        'eller anden måde kom igennem. Et menneske, ikke en post.',
        '',
        'Og også det hører hertil, så ubehageligt det end er: Der var',
        'mennesker, der tjente på krigen. Værter, der forplejede hære;',
        'handlende, der leverede til armeer; entreprenører, der skaffede',
        '„leverancer"; og nogle landsbyboere, der sluttede sig til plyndrerne,',
        'når lejligheden var gunstig. Krigen var for de fleste en katastrofe —',
        'men ikke for alle. Den, der fortier det, fortæller en smukkere',
        'historie, end kilderne giver grundlag for.',
        '',
        '## Sult',
        '',
        'De værste år kom midt i krigen: 1634 til 1638. Da sæden år efter år',
        'blev taget eller brændt, var der ikke mere at høste. Folk spiste',
        'græs, rødder, brød af strå og agern. Kirkebøgerne fra disse år er',
        'hele krigens mest rystende kilder: side efter side med',
        'dødsindførsler, ofte med samme dødsårsag — „sult", „dysenteri",',
        '„plettyfus", „død", ganske enkelt.',
        '',
        'Denne stemme må også sige det mørkeste sted højt, der dukker op i',
        'kilderne: Der findes beretninger om kannibalisme fra de værste',
        'sultår. De er sjældne, de er omstridte, og man læser dem ikke gerne.',
        'Men hvis et kapitel om denne krig vil være ærligt, kan det ikke',
        'fortie dem — for de viser, hvad der sker, når hverdagens orden',
        'bryder sammen år efter år.',
        '',
        '## Sygdommene',
        '',
        'De fleste døde i denne krig faldt ikke i slag, men af sygdomme — det',
        'siger også den første stemme. Nedefra ser det sådan ud: Pesten og',
        'dysenterien rejste med hærene. Et regiment slog lejr, og i landsbyen',
        'ved siden af døde folk, før soldaterne overhovedet havde taget noget.',
        'Lægerne var flygtet eller døde; præsterne førte ind, hvad de ikke',
        'kunne helbrede. Hele landsbyer døde inden for få uger — ikke af sår,',
        'men af feber, diaré, udmattelse.',
        '',
        '## Flugt, hjemkomst, tomme landsbyer',
        '',
        'Mange flygtede: til byerne, hvis mure i det mindste beskyttede noget;',
        'til skovene, til bjergene, til slægtninge i roligere egne. Og mange',
        'kom ikke tilbage. Hundredvis af landsbyer forsvandt helt —',
        'forskningen kalder dem „ødegårde". Hvor der før lå marker, voksede',
        'skov; hvor der før boede mennesker, stod ruiner. Den, der vendte',
        'tilbage, fandt ofte intet: intet hus, ingen naboer, ingen kirke.',
        'Kirkebøgerne i nogle sogne brydes af i årtier — som om nogen havde',
        'lukket bogen, og ingen slog den op igen.',
        '',
        'Og så var der troen, der skiftede med herskerne. Godsejeren blev',
        'katolsk, præsten blev afsat, kirken blev genindviet. Den, der ville',
        'blive, gik med; den, der ikke gik med, gik. Set nedefra var skiftet',
        'af trosretning sjældent et samvittighedsspørgsmål og for det meste et',
        'overlevelsesspørgsmål: Man bad dér, hvor man fik lov at leve.',
        '',
        '## Hekseforfølgelsen',
        '',
        'Nu må denne stemme sige det mest ubehagelige sted i sin egen historie',
        'højt: Rædslen kom ikke kun fra hærene. Den kom også fra landsbyerne',
        'selv.',
        '',
        'I krigsårene nåede hekseprocesserne deres højdepunkt — først og',
        'fremmest i 1630\'erne, i netop de regioner, der led værst. Anklaget',
        'blev overvejende kvinder, ofte gamle, ofte enlige. Anmeldt af naboer',
        '„tilstod" de under tortur og blev brændt. Når misvækst og sygdomme',
        'ikke længere havde nogen naturlig forklaring, søgte folk efter',
        'skyldige — og fandt dem i deres egen landsby. Det gør det ikke bedre.',
        'Men det forklarer, hvorfor netop da: Krigen ødelagde ikke kun huse og',
        'høster, den ødelagde også den tillid, der holder en landsby sammen.',
        '',
        '## Hvad denne stemme indrømmer den anden side',
        '',
        'Fairness kræver, at også denne stemme nævner, hvad der ikke er',
        'forkert ved den første.',
        '',
        'Beslutningstagernes syn er ikke forkert — det er bare ufuldstændigt.',
        'Uden deres beslutninger var krigen ikke begyndt, og uden freden i',
        '1648 var den ikke ophørt. Freden var ægte. Da nyheden nåede',
        'landsbyerne, vidste man, at den ville holde — ikke fordi man stolede',
        'på fyrsterne, men fordi ingen længere havde kræfter til at bryde den.',
        'De berørte havde ingen grund til at elske beslutningstagerne. Men de',
        'havde al grund til at tage imod freden.',
        '',
        'Og også beslutningstagerne betalte en pris: Gustav Adolf døde ved',
        'Lützen, Wallenstein blev myrdet, nogle fyrster ruinerede deres lande',
        'og sig selv. Og nogle forsøgte virkelig at holde deres områder uden',
        'for — med penge, med forhandlinger, nogle gange forgæves. Ikke alle i',
        'toppen ønskede krigen. Men dem, der afsluttede den, gjorde det',
        'oppefra — og uden dem ville den ikke have kunnet afsluttes nedefra.',
        '',
        '## Erindringen',
        '',
        'Hvordan har denne krig overlevet i menneskenes hoveder?',
        '',
        'I 1668, tyve år efter freden, udkom en bog: „Den æventyrlige',
        'Simplicissimus" af **Hans Jakob Christoffel von Grimmelshausen**.',
        'Dens forfatter havde selv oplevet krigen som ung soldat. Hans helt',
        'bliver fra bondedreng til lejesoldat, til tigger, til eremit — og til',
        'sidst ved han kun én ting med sikkerhed: at mennesket i krig er i',
        'stand til alt. Det er den store bog om denne krig, og den er skrevet',
        'nedefra.',
        '',
        'Ved siden af står de stille vidner: kirkebøger, landsbykrøniker,',
        'regnskabsbøger — og ordsprogene, der århundreder senere stadig',
        'fortalte, at „svenskerne var kommet". I generationer var krigen et',
        'skrækord, som man formanede børn med og gjorde fremmede mistænksomme',
        'med. Så lang tid tager et sår om at hele.',
        '',
        '## Spørgsmålet til sidst',
        '',
        'Religionskrig eller magtkrig? Den første stemme har vist, hvor svært',
        'spørgsmålet allerede er at besvare oppefra. Nedefra lyder det',
        'ærligste svar: For landsbyen var det begge dele — og ingen af',
        'delene. Det var lige meget, om soldaterne kæmpede for kejseren eller',
        'for kongen af Sverige: De kom, de tog, de gik. Den, der sad i',
        'kælderen, hørte ingen forskel på trosretningerne hos de mænd, der',
        'gennemsøgte huset.',
        '',
        'Men denne stemme kan noget, den første ikke kan: Den kan sige,',
        'hvordan man kender en krig, der virkelig er forbi. Ikke på',
        'traktaten. På den første vinter uden indkvartering. På det første år,',
        'hvor det sædekorn, man selv havde sået, fik lov at spire. Når du',
        'altså svarer på, om denne krig var en religionskrig eller en',
        'magtkrig, så husk: De mennesker, der led under den, blev ikke spurgt,',
        'under hvilket navn den blev ført.',
      ].join('\n'),
    },
  ],

  // Syntese (runde 12, final). Fører de to stemmer sammen — hvor de er
  // enige, hvor de går fra hinanden, og hvorfor det er sådan.
  synthese: [
    'Nu står begge stemmer side om side: kejserens, fyrsternes og',
    'feltherrernes syn og de berørtes syn. Hvad kan man lære af det?',
    '',
    '**Hvor de er enige.** Det er mere, end man skulle vente. Begge stemmer',
    'nævner de samme begivenheder — vindueskastningen i Prag i 1618, Det',
    'Hvide Bjerg, Magdeburg, Breitenfeld, Lützen, freden i Westfalen — og',
    'begge nævner de samme tal: en tredjedel til to tredjedele af',
    'befolkningen i de hårdest ramte landskaber, de fleste døde af sult og',
    'sygdomme, ikke af våben. Begge er også enige i den mest ubehagelige',
    'diagnose: „Krigen ernærer krigen" var ingen naturlov, men et system,',
    'og trosretningen var ofte påskuddet og sjældent hele grunden. Den',
    'første stemme siger det ud fra traktaterne, den anden ud fra',
    'kirkebøgerne — det er den samme udsagn, fra to arkiver.',
    '',
    '**Hvor de går fra hinanden.** Forskellen begynder ved målestokken. Den',
    'første stemme fortæller i felttog og traktatartikler; i dens fortælling',
    'er befolkningen en post — kontribution, kvarter, hvervning. Den anden',
    'stemme fortæller i vintre, høster og dødsindførsler; i dens fortælling',
    'er felttogene de tider, hvor man gemte sædekornet. Begge fortæller den',
    'samme krig — men den ene oppefra, hvor den blev begrundet, den anden',
    'nedefra, hvor den kom frem.',
    '',
    'Den anden forskel er spørgsmålet om afslutningen. For beslutningstagerne',
    'endte krigen med freden i 1648: et forhandlet traktatværk, der ordnede',
    'trosspørgsmålet med en skæringsdato, gav stænderne suverænitet og',
    'grundlagde det moderne statssystem. For de berørte endte den senere og',
    'anderledes: med den første vinter uden indkvartering, det første år,',
    'hvor sædekornet fik lov at spire. Begge afslutninger er sande — men de',
    'falder ikke på samme dag.',
    '',
    'Den tredje forskel angår skyldspørgsmålet — eller rettere: spørgsmålet',
    'om, hvem der overhovedet må stille det. Den første stemme nævner navne,',
    'datoer og beslutninger; den kan sige, hvem der forlængede krigen, og',
    'hvem der afsluttede den. Den anden stemme minder om, at de mennesker,',
    'der betalte prisen, aldrig blev spurgt — hverken om krigens navn eller',
    'om, hvorvidt den faldt i deres smag. Det er ingen modregning, men en',
    'påmindelse om det, der ikke står i nogen traktatakt.',
    '',
    '**Hvad der følger af det.** Den, der læser dette kapitel, holder to',
    'fortællinger i hånden, som ikke behøver at modsige hinanden — de har',
    'blot forskellige synsvinkler på samme ulykke. Syntesen kan ikke lave én',
    'eneste sandhed ud af det, og den vil det heller ikke. Men den kan vise',
    'én ting, som begge stemmer har til fælles: Begge ved, at freden i 1648',
    'var en begyndelse — begyndelsen på et Europa, der ikke længere ville',
    'føre krige som trosspørgsmål. At der alligevel kom krige igen, står på',
    'et andet blad. Præcis dér begynder din vurdering: religionskrig eller',
    'magtkrig — og hvad ville du holde dig til, hvis du havde siddet i en',
    'landsby i 1636?',
  ].join('\n'),

  urteil: {
    frage: 'Var Trediveårskrigen en religionskrig eller en magtkrig — og hvordan ville du kende forskellen? Hvilket svar giver fortællingen oppefra dig, og hvilket spørgsmål står stadig åbent?',
    hinweis: 'Der er her hverken rigtigt eller forkert. Tre anstød: For det første, saml de tilfælde, der ikke passer ind i skemaet — en katolsk kardinal, der betaler lutherske hære; en luthersk kurfyrste, der kæmper for den katolske kejser; et katolsk Bayern, der i hemmelighed forhandler om en særfred. For det andet, prøv modprøven: Ferdinand 2. kunne have afsluttet krigen med et pennestrøg, hvis han havde trukket restitutionsediktet tilbage — hvorfor gjorde han det ikke i årevis? For det tredje, spørg efter målestokken: Freden i Westfalen afgjorde ikke trosspørgsmålet, den ordnede det med en skæringsdato. Er det en fornuftens sejr, en erkendelse af udmattelse — eller begge dele?',
  },

  quiz: [
    {
      frage: 'Hvordan begyndte krigen i 1618?',
      antworten: [
        'Med de svenske troppers indmarch i Pommern.',
        'Med vindueskastningen i Prag: Bøhmiske adelsmænd kastede to kejserlige statholdere og deres skriver ud af et vindue på borgen.',
        'Med kejser Ferdinand 2.s restitutionsedikt.',
      ],
      richtig: 1,
      erklaerung: 'Alle tre overlevede faldet fra omkring sytten meters højde. Bag det lå striden om „Majestætsbrevet" fra 1609, som havde garanteret de bøhmiske stænder trosfrihed. Bøhmen var et valgkongerige: Stænderne afsatte Ferdinand og valgte Frederik 5. af Pfalz. Den 8. november 1620 tabte de ved Det Hvide Bjerg.',
    },
    {
      frage: 'Hvad betød princippet „Krigen ernærer krigen"?',
      antworten: [
        'At soldaterne kun kæmpede om sommeren, når der var nok at høste.',
        'At hærene forsørgede sig i det besatte land — gennem kontributioner, indkvartering og plyndring — fordi fyrsternes krigskasser var tomme.',
        'At hvert slag udløste det næste, indtil en side vandt.',
      ],
      richtig: 1,
      erklaerung: 'Sætningen tilskrives Wallenstein, og den beskriver et system: Kontributioner var formelt udregnede beløb, som byer og landskaber betalte for ikke at blive plyndret. Alle sider arbejdede sådan. En hær, der ernærer sig i landet, må drage videre, så snart landet er tømt — det er en af grundene til, at krigen varede så længe.',
    },
    {
      frage: 'Hvorfor gik det katolske Frankrig i 1635 i krig mod det katolske Habsburg?',
      antworten: [
        'Fordi paven opfordrede til det.',
        'Fordi kongen og kardinal Richelieu i al hemmelighed var konverteret til protestantismen.',
        'Af statsræson: Frankrig så sig omklamret af Spanien og Østrig og ville svække Habsburg — trosretning eller ej.',
      ],
      richtig: 2,
      erklaerung: 'Kardinal Richelieu havde allerede siden traktaten i Bärwalde i 1631 støttet Sverige med penge i stedet for selv at kæmpe. I 1635 erklærede Frankrig Spanien krig; i 1643 sejrede det ved Rocroi. Senest dermed stod det klart, at det i denne krig ikke kun handlede om troen — hvilket ikke betyder, at troen havde været ligegyldig for de involverede.',
    },
    {
      frage: 'Hvad blev aftalt i 1648 i Münster og Osnabrück?',
      antworten: [
        'Riget blev delt i en katolsk og en protestantisk stat.',
        'Religionsfreden blev bekræftet og udvidet til de reformerte, for kirkegodset gjaldt normalåret 1624, og rigsstænderne fik landshøjhed og ret til egne forbund.',
        'Kejseren fik eneafgørelsen over trosretningen i hele riget.',
      ],
      richtig: 1,
      erklaerung: 'Der blev forhandlet i to byer, fordi trosretningerne ikke ville sidde ved samme bord. Sverige fik Forpommern, Wismar, Bremen og Verden, Frankrig de habsburgske rettigheder i Elsass; Nederlandene og Schweiz trådte formelt ud af riget. Freden afgjorde ikke trosspørgsmålet — den ordnede det med en skæringsdato.',
    },
    {
      frage: 'Hvad døde de fleste mennesker af i Trediveårskrigen?',
      antworten: [
        'I de store feltslag som Breitenfeld og Lützen.',
        'Af sult og sygdomme, der fulgte de gennemtogende hære.',
        'Ved belejringen af Magdeburg i 1631.',
      ],
      richtig: 1,
      erklaerung: 'Slagene krævede mange dødsofre, men det store flertal døde af sygdomme som pest og tyfus og af sult, når sædekorn og kvæg var væk. I riget faldt befolkningen fra skønsmæssigt 16 til 18 millioner til 10 til 13 millioner, regionalt med op til to tredjedele — andre steder forblev det næsten roligt. Tallene bygger på skattelister og kirkebøger og er omstridte.',
    },
  ],
};

module.exports = trediveaarskrigen;
