// Tema: Djingis Khan og mongolerne — verdens største landrige.
//
// Dansk oversættelse af utils/themen/dschingis-khan.js. Feltnavnene følger
// det tyske skema (aufhaenger, perspektiven, synthese, urteil, quiz) — kun
// teksterne er oversat. Kortet er erstattet af karteHinweise: de fire faser
// (label + hinweis) fra karten/dschingis-khan.js.
//
// Stand: Runde 5. Kapitlet har to stemmer: den europæiske synsvinkel
// (Stemme: Opus) og den kinesiske synsvinkel på Yuan-tiden (Stemme: Hermes).
// Europa oplevede mongolerne i to år som katastrofe og derefter i hundrede år
// som en åben vej mod øst. Kina oplevede dem i næsten et århundrede som
// herskere i eget land. Det er to meget forskellige erfaringer med de samme
// mennesker.
//
// Rene data — ingen UI-imports (arkitekturregel).

const dschingisKhan = {
  id: 'dschingis-khan',
  titel: 'Djingis Khan og mongolerne — verdens største landrige',
  epoche: 'Fra kurultai i 1206 til Yuan-dynastiets afslutning i 1368',

  aufhaenger: {
    frage: 'Et folk uden byer, uden skrift, uden belejringskunst erobrer på halvtreds år det største sammenhængende landrige, der nogensinde har eksisteret — større end Rom og Kina tilsammen. Hvordan kan det lade sig gøre?',
    text: [
      'Regn efter et øjeblik. Romerriget omfattede på sit højdepunkt omkring',
      'fem millioner kvadratkilometer. Han-riget var nogenlunde lige så stort. Det',
      'mongolske rige nåede op på omkring fireogtyve millioner — en femtedel',
      'af jordens landareal, fra Korea til Polen, fra Sibirien til',
      'Den Persiske Bugt. I begyndelsen stod der måske en million mennesker',
      'på steppen. Rom havde alene i byen Rom flere indbyggere.',
      '',
      'Og disse mennesker havde intet af det, man troede, der skulle til. Ingen',
      'byer, hvor man kunne hente forsyninger. Ingen skrift, hvori man kunne',
      'fastlægge ordrer — den fik de først undervejs, af en',
      'fanget skriver. Ingen erfaring med at bryde mure ned; deres',
      'første belejringer slog fejl på det pinligste.',
      '',
      'Hvad de havde, var heste, buer, en ny lov — og en mand, der voksede op',
      'som søn af en bortført kvinde, hvis far blev forgiftet',
      'og som som dreng blev holdt fanget i et træåg. Han hed',
      'Temüdsjin. Vi kender ham under den titel, som de forsamlede',
      'stammer gav ham i 1206: Djingis Khan.',
      '',
      'I Europa kendte man ham i starten slet ikke. Man kendte kun det, der i 1241',
      'kom fra øst — og anså det for verdens ende.',
    ].join('\n'),
  },

  // „Historie i bevægelse" — kortet kommer efter opmærksomhedsfangeren og før
  // perspektiverne. Her som karteHinweise (de fire faser fra kortfilen).
  karteHinweise: [
    {
      label: '1206',
      hinweis:
        'På kurultai ved Onons udspring udråber de forsamlede stammer Temüdsjin til Djingis Khan. Det, han regerer over, er ikke et rige, men en alliance: måske en million mennesker, flere heste end mennesker, ikke en eneste by. Se godt på denne plet — det næste kort er enogtyve år senere.',
    },
    {
      label: '1227',
      hinweis:
        'I Djingis Khans dødsår strækker riget sig fra Det Kaspiske Hav til Det Gule Hav. Khwarezmid-riget, i 1219 endnu en stormagt med Samarkand og Bukhara, er forsvundet. I Kina slutter fremrykningen ved Den Gule Flod: Syden hører stadig Song til — og vil gøre det i halvtreds år.',
    },
    {
      label: '1259',
      hinweis:
        'Det største omfang: fra Korea til Karpaterne, fra Sibirien til Den Persiske Bugt. Omkring fireogtyve millioner kvadratkilometer, en femtedel af jordens land — aldrig har et rige holdt så meget sammen, og aldrig siden. Fire farvepletter, ét rige: Endnu gælder én storkhan for alle.',
    },
    {
      label: '1294',
      hinweis:
        'Ved Kublai Khans død er riget stadig enormt — men det er ikke længere ét. Fire delriger går hver deres vej, fører hver deres krige, antager hver deres religioner. I Kina regerer Kublai som kejser af et kinesisk dynasti, Yuan, fra Dadu — det nuværende Beijing. Steppen er blevet en provins.',
    },
  ],

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Europæisk synsvinkel',
      stimme: 'Opus',
      text: [
        'Sådan fortælles mongolernes historie i Europa: først som rædsel,',
        'så som forundring, senere som stridsemne. Europa oplevede aldrig dette',
        'rige indefra — det frygtede det i to år og brugte det i hundrede',
        'år. Det præger fortællingen den dag i dag. Læs den derfor',
        'som det, den er: blikket fra den vestlige kant af en verden, hvis midte',
        'lå et andet sted.',
        '',
        '## 1241: Guds vrede står for døren',
        '',
        'Den 9. april 1241 stillede en hær af riddere, minearbejdere',
        'og ordensbrødre sig ved Liegnitz i Schlesien over for en hær, som',
        'ingen vidste præcis, hvor kom fra. Hertug Henrik 2. af Schlesien',
        'førte den an. Slaget varede ikke længe.',
        '',
        'Mongolerne gjorde, hvad de altid gjorde: De simulerede en flugt,',
        'ridderne satte efter, ordenen opløste sig — og så lukkede',
        'fælden sig. Hertug Henrik faldt. Hans hoved blev båret på en lanse',
        'foran murene i Liegnitz. Stedet hedder siden da Wahlstatt,',
        'efter det gamle ord for slagmark.',
        '',
        'To dage senere, flere hundrede kilometer mod syd, skete det samme ved',
        'Mohi i Ungarn med kong Béla 4.s hær. To europæiske hære,',
        'to dage, to nederlag — koordineret over en afstand, som',
        'europæiske budbringere ville have brugt uger på. Præcis det var det',
        'skræmmende: Disse ryttere var ikke vilde, de var organiserede.',
        '',
        'Europa havde ingen forklaring. Hvad det havde, var Bibelen. Man læste',
        'rytterne som folkene Gog og Magog, der ved tidernes ende bryder frem',
        'bag bjergene. Man kaldte dem **tatarer** — og fordi det på',
        'latin næsten lød som *Tartarus*, som underverdenen, var ordet',
        'straks en forklaring med i købet: Disse mennesker kom fra helvede.',
        'Ludvig 9. af Frankrig skal have sagt til sin mor, at enten sendte man',
        'tatarerne tilbage til Tartaros, eller også sendte de alle i',
        'himlen. Krønikeskriveren Matthæus Paris skrev i det fjerne England om',
        'mennesker, der spiser råt kød og drikker blod; han havde aldrig set en',
        'mongol.',
        '',
        'I Nordtyskland udeblev sildehandelen dette år, fordi',
        'fiskerne fra Gotland og Frisland ikke stævnede ud. Frygten nåede',
        'længere end rytterne.',
        '',
        '## Reddet af et dødsfald',
        '',
        'Og så, i foråret 1242, vendte mongolerne om. De stod ved',
        'Donau, de havde lagt Ungarn øde, deres fortrop havde Wien inden for',
        'synsvidde — og de trak sig tilbage, mod øst, uden nød.',
        '',
        'Den forklaring, Europa siden har fortalt sig selv, er et dødsfald: Den',
        '11. december 1241 døde storkhanen Ögedei i Karakorum, søn og',
        'efterfølger af Djingis Khan. Rigerets fyrster, blandt dem Batu,',
        'føreren for vesthæren, måtte tilbage til kurultai — til',
        'forsamlingen, der valgte den nye storkhan. Et dødsfald i',
        'Mongoliet, 6.000 kilometer væk, reddede Mellemeuropa.',
        '',
        'Det er en god historie, og den indeholder formentlig noget sandt. Men',
        'den er også belejlig: Den sparer Europa for spørgsmålet om, hvorvidt',
        'man kunne have forsvaret sig. Historikere nævner i dag flere',
        'grunde — den ungarske vinter 1241/42 var våd, græsgangene gav for',
        'lidt til hundredtusindvis af heste; Ungarns stenslotte var',
        'sejere end Rus træbyer; og felttogets mål var',
        'måske aldrig erobringen af Europa, men sikringen af',
        'vestflanken.',
        '',
        'Læg mærke til dette sted. Her kan du se, mens du kigger på, hvordan',
        'historie skabes: Af „vi ved ikke præcis, hvorfor de drog bort" bliver',
        'der gennem århundrederne „Europa blev reddet". Den, der fortæller,',
        'vælger.',
        '',
        'For en del af Europa passede redningen alligevel ikke. Rus fyrster',
        '— det senere Rusland og Ukraine — blev. Kiev var faldet i 1240;',
        'i omkring 240 år betalte de russiske fyrster tribut til',
        'Den Gyldne Horde og hentede i dens lejr ved Volga',
        'tilladelse til at regere. Den russiske historieskrivning kalder denne',
        'tid for „tataråget". Set fra vest var 1242 en lykkelig',
        'afslutning. Set fra Kiev var det begyndelsen.',
        '',
        '## Pax Mongolica — pludselig er vejen åben',
        '',
        'Så skete det mærkeligste ved hele denne historie: Af',
        'rædslen blev en mulighed.',
        '',
        'For første og eneste gang i historien tilhørte hele',
        'landvejen fra Kina til Europa én eneste orden. Mongolerne',
        'levede af handel — told var deres indtægt, karavaner deres kapital.',
        'Derfor beskyttede de vejene. Landevejsrøveri blev hårdt straffet. På',
        'de store ruter stod der hver 40. kilometer stationer tilhørende',
        '**jam**, postvæsenet: friske heste, logi, proviant. En kurer med',
        'en paiza — en pasplade af træ, sølv eller guld — kunne på',
        'én dag tilbagelægge det, som en karavane brugte en uge på.',
        '',
        'En købmand fra Firenze skrev omkring 1340 i sin håndbog, at vejen',
        'til Kina var „helt sikker, både dag og nat". Det havde ikke været',
        'sandt siden romerne og skulle ikke blive det igen i århundreder.',
        '',
        'Dertil kom en indstilling, som var fremmed for Europa: Mongolerne',
        'spurgte ikke til troen. De ansatte skatteopkrævere, hvad enten de var',
        'muslimer, buddhister, nestorianere eller konfucianere. Præster fra',
        'alle religioner var fritaget for afgifter. I Karakorum lod Möngke Khan',
        'i 1254 kristne, muslimer og buddhister offentligt strides med',
        'hinanden, mens han lyttede — midt i et århundrede, hvor Europa førte',
        'korstog. Tolerancen var også nyttig for ham: Den, der ingen',
        'statsreligion har, behøver ikke håndhæve nogen.',
        '',
        'Så sendte Europa udsendinge. Pave Innocens 4. sendte i 1245',
        'fransiskaneren Johannes af Plano Carpini af sted, en gammel, svær',
        'mand, der i to år red gennem steppen på en hest. Han nåede',
        'faktisk helt til Karakorum, overværede valget af storkhanen Güyük og',
        'bragte et brev tilbage. Paven havde bedt om fred og dåb. Svaret',
        'var kort: Hvis paven ønskede fred, skulle han komme personligt',
        'og underkaste sig. Få år senere rejste Wilhelm af',
        'Rubruk samme vej og skrev den første nøgterne beretning om',
        'mongolerne, som Europa havde — med iagttagelser i stedet for dæmoner.',
        '',
        '## Marco Polo og forundringen, som ingen troede på',
        '',
        'Den berømteste af disse rejsende var ingen munk, men en ung',
        'købmand fra Venedig. **Marco Polo** drog af sted i 1271 med far og',
        'onkel og kom først tilbage i 1295 — fireogtyve år senere. En stor',
        'del af tiden tilbragte han i storkhanen Kublais tjeneste, barnebarnet',
        'af Djingis Khan, som i mellemtiden herskede over hele Kina.',
        '',
        'Det, han fortalte, lød ganske enkelt utroligt for europæiske ører:',
        '',
        '- **Penge af papir.** Khanen lod bark fra morbærtræer presse til blade,',
        '  stemple med sit segl — og alle tog imod det som',
        '  betaling, som var det guld. I Europa var penge noget, man vejede.',
        '- **Sten, der brænder.** Man gravede sorte sten op af jorden og',
        '  varmede husene med dem; de holdt gløden længere end træ. Marco',
        '  Polo havde set kul.',
        '- **Byer uden ende.** Quinsai — det nuværende Hangzhou — skulle have',
        '  tolv tusind broer og flere indbyggere, end Venedig kunne forestille',
        '  sig. Venedig havde dengang måske hundrede tusind.',
        '- **En post, der flyver.** Med jamsystemet tilbagelagde efterretninger',
        '  strækninger, som europæiske budbringere brugte måneder på.',
        '',
        'Man troede ham ikke. Hans bog fik i Italien øgenavnet *Il',
        'Milione* — millionfortælleren, altså pralhalsen. Legenden',
        'vil vide, at venner på dødslejet bad ham om endelig at tilbagekalde,',
        'og at han svarede, at han ikke engang havde fortalt halvdelen.',
        '',
        'Alligevel blev bogen afskrevet og læst, igen og igen. To',
        'århundreder senere ejede en genovesisk søfarer et eksemplar,',
        'fuldskrevet med noter i margenen, og ville nå denne østs rigdom',
        'ved at sejle mod vest. Han hed Christoffer',
        'Columbus. Ad den omvej gjorde det mongolske rige Amerika kendt for',
        'Europa.',
        '',
        'Den åbne vej havde imidlertid en anden side, som ingen',
        'havde bestilt. Midt i 1300-tallet rejste ad de samme ruter',
        'en sygdom mod vest. Den Sorte Død kostede Europa måske',
        'en tredjedel af sine mennesker. Det, der transporterer varer og ideer,',
        'bærer også lopper.',
        '',
        '## Barbaren og banebryderen',
        '',
        'Hvordan mindes Europa så Djingis Khan? Ærligt svar: i to',
        'billeder, som ikke kan fordrage hinanden.',
        '',
        'Det ældste er billedet af **ødelæggeren**. Tallene er forfærdelige,',
        'også selvom de er omstridte: Byer som Nishapur, Merv, Herat og',
        'Bagdad blev plyndret, deres befolkning dræbt eller bortført.',
        'Bagdad var i 1258 det islamiske verdens åndelige centrum — Hülegü, en',
        'sønnesøn af Djingis Khan, gjorde ende på abbasidernes kalifat, og',
        'byens biblioteker gik under. Vandingssystemerne i',
        'Mesopotamien og Persien, bygget over århundreder, kom sig',
        'aldrig helt. Nogle skøn taler om millioner af døde. Den, der siger,',
        'at det „også er en synsvinkel", har misforstået pointen: Ødelæggelse',
        'er ikke et perspektiv.',
        '',
        'Det nyere er billedet af **banebryderen**. Det understreger:',
        'Mongolerne forenede Eurasien for første og eneste gang under én',
        'orden. De beskyttede handelsveje, lod religioner bestå side om side,',
        'samlede håndværkere og lærde i stedet for at dræbe dem og førte',
        'teknikker over kontinenter: bogtryk, papir, kompas, krudt',
        'gik mod vest, persisk astronomi og medicin mod øst. Uden',
        'disse hundrede åbne år — sådan lyder tesen — ville Europa have fået',
        'sin nytid senere eller anderledes.',
        '',
        'Begge billeder er rigtige, og de beskriver de samme mennesker. Det er',
        'bare svært at holde dem i hovedet samtidig. Hvis det gør dig',
        'utilpas, er du det rigtige sted: Præcis her begynder',
        'historie at blive interessant.',
        '',
        'Mongoliet selv ser i øvrigt sagen helt klart. Djingis Khan er',
        'der nationens grundlægger; lufthavnen i Ulaanbaatar bærer hans',
        'navn, hans ansigt er på pengesedlerne. I sovjettiden var',
        'hans navn forbudt, bagefter kom det straks tilbage. Én mand, tre',
        'lande, tre svar.',
        '',
        '## Og den anden side?',
        '',
        'Alt, hvad du lige har læst, er blikket udefra — og',
        'derudover blikket fra meget langt udefra. Europa var for mongolerne',
        'et grænseområde, et felttog på to år, derefter en handelspartner',
        'ved verdens yderste vestende.',
        '',
        'For Kina var det noget helt andet. Der førte mongolerne intet',
        'felttog, der regerede de: Kublai Khan udråbte i 1271 et kinesisk',
        'dynasti, **Yuan**, byggede sig i Dadu — det nuværende Beijing —',
        'en hovedstad og gjorde i 1279 ende på Song-riget. Næsten et',
        'århundrede blev Kina behersket af fremmede, i et land, der',
        'selv forstår sig som verdens midte. Hvordan fortæller man det',
        'indefra? Er Kublai en kinesisk kejser eller en besætter? Og hvad',
        'gør det ved en fortælling, hvor dynastier kommer og går, når',
        'dynastiet denne gang kommer fra steppen?',
        '',
        'Disse spørgsmål kan den europæiske synsvinkel ikke besvare. De',
        'tilhører en anden stemme, som fortæller disse hundrede år indefra.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Kinesisk synsvinkel',
      stimme: 'Hermes',
      text: [
        'Denne synsvinkel fortæller mongolernes historie indefra — fra',
        'Kina, hvor de regerede i næsten et århundrede. For den kinesiske',
        'fortælling er det den sværeste historie overhovedet: Midtens',
        'rige, der for første gang i sin lange historie fuldstændigt blev',
        'behersket af mennesker fra steppen. Hvordan fortæller man det, uden',
        'at knække sit eget selvbillede? Svaret fra den kinesiske',
        'historieskrivning er lige så dristigt, som det er konsekvent.',
        '',
        '## Mandatet kender ingen herkomst',
        '',
        'Nøglen er Himlens mandat — som du allerede kender fra kapitlet om',
        'Kina. Det siger: Himlen giver herredømmet til',
        'hvem den vil, og tager det tilbage, hvis det føres dårligt.',
        'Deraf følger noget, som lyder overraskende for udenforstående:',
        'Himlen spørger ikke til herkomsten. Den har ofte givet mandatet til',
        'bønder og soldater, der grundlagde et rige — hvorfor så ikke',
        'også engang til ryttere fra steppen?',
        '',
        'Den kinesiske fortælling fortolker derfor den mongolske erobring',
        'ikke som et indbrud udefra, men som en dom oppefra:',
        'Song-dynastiet havde forspildt mandatet. Det var svagt, dets',
        'generaler nærede mistillid til hinanden, dets embedsmænd skændtes —',
        'og et rige, der ikke kan forsvare sig, har efter denne logik mistet',
        'retten til at herske. At de nye herrer kom fra steppen, var',
        'ingen modsigelse af verdensordenen. Det var verdensordenen.',
        '',
        '## Kublai blev kineser',
        '',
        'Og så skete der noget, der har præget verdenshistorien:',
        'Kublai Khan indlod sig på Kina. Han gav sit herredømme',
        'dynastinavnet **Yuan** — „oprindelse" — og stillede sig dermed i',
        'rækken af kinesiske dynastier. Han flyttede hovedstaden til',
        'Dadu, det nuværende Beijing, overtog embedsmandsforvaltningen, førte',
        'kalenderen, lod rigshistorien skrive. Fra erobrer blev han',
        'kejser — og Beijing har siden været Kinas hovedstad, den dag i dag.',
        '',
        'Den kinesiske fortælling ser deri beviset på, at Midtens rige var',
        'stærkere end sine erobrere: Mongolerne erobrede Kina,',
        'men Kina formede mongolerne. Den, der regerede i Dadu, regerede',
        'kinesisk — med kinesiske embedsmænd, kinesisk ceremoniel,',
        'kinesisk skrift. Steppefyrsten blev Himlens søn.',
        '',
        '## Hvad Yuan bragte',
        '',
        'Den kinesiske fortælling er ikke blind for, hvad Yuan-tiden',
        'bragte. Det vigtigste: **genforening.** Siden Tangs afslutning',
        'var Kina faldet fra hinanden i delriger — Song i syd, Jin i nord,',
        'dertil tanguter og andre. Næsten tre hundrede års adskillelse, tre',
        'århundreder, hvor Midtens rige var delt. Mongolerne',
        'gjorde det igen til ét Kina. For en civilisation, der definerer sig',
        'ved enheden, er det ikke et lille punkt.',
        '',
        'Dertil kom den åbne verden. Under Yuan var Silkevejen så',
        'sikker som aldrig før — og igen kom verden til Midten: købmænd fra',
        'Persien, handlende fra Venedig, lærde, der var velkomne i Dadu.',
        'Marco Polo, som den europæiske fortælling beretter om, var i den',
        'kinesiske fortælling én af mange fremmede, der tjente ved kejserens',
        'hof — interessant, men intet verdensvidunder. At Vesten',
        'holdt denne besøgende for sensationen, siger set fra kinesisk side',
        'mere om Vesten end om Kina.',
        '',
        '## Prisen',
        '',
        'Ærlig er den kinesiske fortælling også: Mongolerne',
        'regerede ikke som kinesiske kejsere. De delte menneskene i',
        'fire klasser — mongolerne øverst, så fremmede allierede, så',
        'nordkineserne, til sidst sydkineserne, som havde forsvaret sig',
        'længst. Kinesere var i deres egen hovedstad borgere',
        'anden klasse. Skattetrykket var højt, og adskillige embedsmænd i',
        'rigets indre tjente en herre, hvis sprog de ikke',
        'forstod.',
        '',
        'Også det hører med til fortællingen. Yuan-dynastiet regerede med',
        'Himlens mandat — men det regerede fremmed, og det kunne i længden',
        'ikke bæres. Da i 1300-tallet misvækst, oversvømmelser',
        'og oprør rystede riget, tolkede',
        'historieskrivningen det som et tegn: Mandatet forlod Yuan,',
        'ligesom det havde forladt Song. I 1368 trak mongolerne sig tilbage',
        'til steppen, og Ming-dynastiet overtog — igen et',
        'kinesisk dynasti, igen kredsløbet.',
        '',
        '## Og så skrev Ming historien',
        '',
        'Her bliver Yuans historie selv til en lektion om',
        'historie. Yuan-dynastiets officielle krønike blev nemlig',
        'skrevet af Ming-dynastiet — af sejrherrerne, der havde',
        'drevet mongolerne bort. Og Ming gjorde noget forbløffende:',
        'De lod Yuan blive stående i rækken af kinesiske dynastier.',
        'Ikke af gavmildhed. Men fordi deres eget herredømme kun var',
        'legitimt, hvis de fremstod som næste dynasti i mandatets',
        'kredsløb — og kredsløbet krævede, at Yuan',
        'havde hørt med. Optagelsen af fremmedherskerne i',
        'dynastirækken var selv en politisk akt.',
        '',
        'Det er svaret på det spørgsmål, der står i slutningen af den',
        'europæiske fortælling: Er Kublai en kinesisk kejser eller en',
        'besætter? Den kinesiske fortælling siger: Den, der forener riget og',
        'bærer mandatet, er kejser — herkomsten er underordnet. Og',
        'dog strides Kina den dag i dag om, hvordan Yuan skal vurderes.',
        'Nogle fejrer genforeningen og den åbne verden,',
        'andre mindes de fire klasser og fremmedherredømmet.',
        '',
        'At et folk ikke er enigt om, hvordan det skal fortælle sin egen',
        'historie, er ingen svaghed — det er det ærligste,',
        'en civilisation kan sige om sig selv. Også den',
        'kinesiske fortælling er ingen sandhed. Den er en stemme, der',
        'kommer fra midten — og som ved, at sejrherrerne skriver.',
      ].join('\n'),
    },
  ],

  // Syntese (Runde 5, fælles revideret efter at Hermes har suppleret med den
  // kinesiske synsvinkel).
  synthese: [
    'Tre navne for samme folk: „tatarer" — dem, der kommer fra Tartaros, fra',
    'helvede. „Yuan" — et dynastinavn i rækken af',
    'kinesiske dynastier. „Tataråget" — det ord, som den russiske',
    'historieskrivning fandt for 240 års tributtvang. Tre ord,',
    'tre fortællinger, ét rige. Præcis det handler dette kapitel om.',
    '',
    '**Hvor de mødes:** Begge synsvinkler kalder det samme rige',
    'enestående — større end alt tidligere, fra Korea til Polen. Begge',
    'fortæller om Pax Mongolica: sikrede handelsveje, jam-postvæsenet,',
    'religiøs tolerance, den åbne vej mod øst. Og begge gør',
    'tilbagetrækningen i 1242 henholdsvis erobringen i 1279 til vendepunktet',
    'i deres fortælling.',
    '',
    '**Hvor de skilles:** Den europæiske fortælling oplevede',
    'mongolerne i to år som rædsel — „Guds vrede", „reddet af',
    'et dødsfald" — og derefter i hundrede år som en fjern mulighed:',
    'udsendinge, Marco Polo, handel. Mongolerne var for Europa en',
    'begivenhed. Den kinesiske fortælling oplevede dem i næsten et',
    'århundrede som herskere: Kublai blev kejser, Kina blev genforenet,',
    'verden kom til Dadu. Mongolerne var for Kina en epoke. Og den',
    'tredje stemme i udkanten — Rus — kalder samme tid et åg.',
    'Tre erfaringer, tre ord, tre domme over det samme',
    'herredømme.',
    '',
    '**Hvad der følger deraf:** Navnene er fortolkningen. Den, der siger',
    '„tatarer", fortæller om helvede; den, der siger „Yuan", fortæller om',
    'Himlens mandat, som også kan gives til stepperyttere; den, der siger',
    '„tataråget", fortæller om undertrykkelse. Og den kinesiske',
    'fortælling tilføjer den fineste pointe: Selv Yuans officielle',
    'historie blev skrevet af dem, den havde besejret — Ming,',
    'som optog den i dynastirækken, fordi deres egen',
    'legitimitet afhang af det. Sejrherren skriver historien — og',
    'nogle gange skriver han endda historien om den sejrherre, han',
    'besejrede.',
    '',
    '**Din dom begynder her:** Var Djingis Khan en erobrer eller en',
    'vejåbner? Spørgsmålet fører måske på vildspor — han var begge dele,',
    'og svaret afhænger af, hvem du spørger: købmændene,',
    'efterkommerne af de dræbte, Mongoliet, der fejrer ham som grundlægger,',
    'eller Ming-historikerne. Hvilken stemme taler mest',
    'til dig — og hvilken ville du gerne høre mere fra?',
  ].join('\n'),

  urteil: {
    frage: 'Djingis Khan lod byer udslette og skabte samtidig et rum, hvor varer, viden og mennesker sikkert kunne rejse mellem Kina og Europa. Var han en erobrer og ødelægger eller en ordensstifter og vejåbner — og hvem har egentlig ret til at afgøre det: de dræbtes efterkommere, købmændene, der levede af det, eller Mongoliet, der fejrer ham som grundlægger af sit land?',
    hinweis: 'Der er her hverken rigtigt eller forkert. Overvej, om spørgsmålet måske er forkert stillet — må man nødvendigvis vælge mellem de to? Og prøv på dit svar, om du ville anlægge samme målestok over for erobrere, der står dig nærmere: over for Cæsar for eksempel eller Alexander „den Store".',
  },

  quiz: [
    {
      frage: 'Erobrede Djingis Khan Kina?',
      antworten: [
        'Ja, han underkastede hele Kina helt til sydkysten.',
        'Kun nord — tanguternes rige og store dele af Jin-riget. Hele Kina erobrede først hans sønnesøn Kublai i 1279.',
        'Nej, Kina forblev uafhængigt hele mongoltiden.',
      ],
      richtig: 1,
      erklaerung: 'Djingis Khan døde i 1227, midt i felttoget mod tanguterne. Syden — Song-riget — holdt stand i over halvtreds år endnu. Først Kublai Khan gjorde ende på det i 1279 og regerede som kejser af Yuan-dynastiet over hele Kina.',
    },
    {
      frage: 'Erobrede mongolerne Europa?',
      antworten: [
        'Nej, de kom aldrig ud over Wisła.',
        'Ja, hele Europa var mongolsk indtil 1300.',
        'Delvist: I 1241 besejrede de hærene i Polen og Ungarn og trak sig igen i 1242 — men de russiske fyrstendømmer forblev i omkring 240 år under Den Gyldne Horde.',
      ],
      richtig: 2,
      erklaerung: 'For Mellemeuropa var det, der begyndte i 1241, forbi i 1242. Ikke for Rus: Kiev faldt i 1240, og fyrsterne betalte tribut i næsten to et halvt århundrede. Om „Europa blev erobret", afhænger altså af, hvor i Europa du spørger.',
    },
    {
      frage: 'Hvorfor trak mongolerne sig igen ud af Ungarn i 1242?',
      antworten: [
        'Fordi en europæisk hær besejrede dem i et stort slag.',
        'Den kendteste forklaring er storkhanen Ögedeis død i 1241 — fyrsterne måtte tilbage til valget af efterfølgeren. Sikkert ved man det ikke.',
        'Fordi paven betalte dem guld mod at drage bort.',
      ],
      richtig: 1,
      erklaerung: 'Et dødsfald 6.000 kilometer væk — det er den forklaring, Europa har fortalt sig selv i århundreder. I dag nævner man flere grunde: våde græsgange i vinteren 1241/42, seje stenslotte, og måske var erobringen af Europa aldrig målet.',
    },
    {
      frage: 'Hvem var Marco Polo?',
      antworten: [
        'En venetiansk købmand, der var af sted i 24 år, tjente ved Kublai Khans hof — og som hjemme næsten ingen troede på.',
        'En feltherre, der besejrede mongolerne ved Liegnitz.',
        'En udsending fra paven, der skulle døbe mongolerne.',
      ],
      richtig: 0,
      erklaerung: 'Hans bog fik i folkemunde det spottende navn „Il Milione", pralhalsen: papirpenge, brændende sorte sten og byer med millioner af mennesker anså man for opdigtet. To århundreder senere læste Christoffer Columbus denne bog — og ville nå denne øst ved at sejle fra vest.',
    },
    {
      frage: 'Hvad betyder „Pax Mongolica"?',
      antworten: [
        'En fredsaftale mellem paven og storkhanen.',
        'Den tid, hvor hele landvejen mellem Kina og Europa tilhørte ét rige — handelsveje blev beskyttet, religioner tolereret, efterretninger løb gennem et postvæsen med skiftestationer.',
        'Navnet på det mongolske lovværk.',
      ],
      richtig: 1,
      erklaerung: 'Mongolerne levede af told, så de sikrede vejene. En florentinsk købmand skrev omkring 1340, at vejen til Kina var „helt sikker, både dag og nat". Ad de samme åbne veje kom imidlertid også Den Sorte Død til Europa.',
    },
  ],
};

module.exports = dschingisKhan;
