// Emne: Germanerne og folkevandringen.
//
// Dansk oversættelse af utils/themen/germanen.js (tysk original). Begge
// stemmer er med: den romersk-mediterrane synsvinkel (stemme: Opus) og den
// germanske synsvinkel (stemme: Hermes); syntesen nedenfor er færdig og
// fællesrevideret (se CLAUDE.md, perspektiv-workflow).
//
// Ved dette emne tager appens ledetanke en usædvanlig drejning. „Sejren
// skriver historien" — her ikke. Næsten alt, hvad vi tror, vi ved om
// germanerne, står i tekster fra det rige, der gik under: skrevet af
// mennesker, der aldrig var der, på tabernes sprog, om modstandere, der
// selv ikke efterlod sig nogen historiebøger. Og vinderne — kongerne i de
// nye riger — skrev bagefter latin og kaldte sig efter romersk forbillede.
// Den, der vil skifte perspektiv her, må derfor først indrømme, hvor tyndt
// kildematerialet er på den anden side. Præcis det leverer den anden stemme.
//
// Kortet ligger i karten/germanen.js — det viser fem tilstande mellem 100
// og 568 e.Kr. og lader Germanien i første fase bevidst stå tomt som
// ubegrænset flade (begrundelse der i filens hoved). Her er kun
// fasehenvisningerne oversat (karteHinweise), ikke selve kortet.
//
// Rene data — ingen UI-imports (arkitekturregel).

const germanen = {
  id: 'germanen',
  titel: 'Germanerne og folkevandringen',
  epoche: 'Fra Cæsars Rhinen-grænse i 58 f.Kr. til langobarderne i 568 e.Kr.',

  aufhaenger: {
    frage: 'Et verdensrige forsvinder — og ingen, der var der, lægger mærke til det. Hvordan kan det gå til — og ville de angivelige ødelæggere af Rom ikke i virkeligheden selv være romere?',
    text: [
      'I september 476 afsatte en officer ved navn Odoaker i Ravenna den',
      'vestromerske kejser. Kejseren var en dreng, måske seksten,',
      'og han bar det uforholdsmæssigt store navn Romulus Augustulus — „lille',
      'Augustus". Odoaker lod ham ikke dræbe. Han sendte ham med en',
      'årlig pension til et landsted ved Napoli.',
      '',
      'I dag står dette år i enhver skolebog: 476, slutningen på Romerriget.',
      'Dengang skrev næsten ingen om det. Ingen krønike melder om et',
      'tidsalders vendepunkt, ingen tale beklager verdens undergang. Odoaker',
      'udråbte sig ikke til kejser, men sendte herskertegnet til',
      'Konstantinopel og lod sig kalde konge — i kejserens navn, som',
      'fortsatte med at regere der. For samtiden var det en',
      'forvaltningsændring.',
      '',
      'Og det bliver endnu mærkeligere. De mænd, der angiveligt ødelagde',
      'Rom, gjorde bagefter alt for at fremstå romerske. De lod deres',
      'love skrive på latin. De beholdt romerske embedsmænd,',
      'romerske skatter, romerske titler. Teoderik, østgoteren, regerede',
      'Italien og kaldte sig imens kejserens statholder. Den, der vil',
      'ødelægge en ting, genopbygger den ikke bagefter omhyggeligt.',
      '',
      'Altså to spørgsmål. For det første: Hvad skete der egentlig — en undergang',
      'eller en ombygning? For det andet, og det er det ubehageligste: Hvor ved',
      'vi det egentlig fra? For næsten hvert et ord, vi har om germanerne,',
      'stammer fra deres fjender.',
    ].join('\n'),
  },

  // „Historie i bevægelse" — kortet kommer efter opmærksomhedsfangeren og før
  // perspektiverne. Her som karteHinweise (de fem faser fra kortfilen).

  perspektiven: [
    {
      id: 'roemisch',
      name: 'Den romersk-mediterrane synsvinkel',
      stimme: 'Opus',
      text: [
        'Sådan fortælles folkevandringens historie i den tradition,',
        'der stammer fra Middelhavsområdet — fra Romerrigets og dets arvingers',
        'byer, biblioteker og kanslier. Det er fortællingen fra dem, der kunne',
        'skrive — og gjorde det.',
        '',
        'Og her gemmer der sig straks i begyndelsen en mærkelighed. Ellers gælder:',
        'Sejren skriver historien. Her er det omvendt. Om germanerne ved vi',
        'næsten kun, hvad deres fjender skrev om dem —',
        'og de fjender tabte. Germanerne selv efterlod ingen',
        'historiebøger. De havde en skrift, runerne, men den',
        'brugte de til korte indskrifter på våben, sten og smykker,',
        'ikke til krøniker. Den ældste lange tekst på et germansk',
        'sprog er en bibeloversættelse: Den gotiske biskop Wulfila',
        'oversatte i 300-tallet De hellige Skrifter til gotisk og',
        'opfandt selv et alfabet til formålet. Om hans folk får vi næsten',
        'intet at vide deraf — bortset fra en enkelthed, som en senere',
        'forfatter beretter: Bøgerne om kongerne med deres krigshistorier skulle',
        'Wulfila have udeladt, hans folk var krigeriske nok i forvejen.',
        '',
        'Læs altså det følgende som det, det er: indersynet fra et',
        'rige, der aldrig forstod sine naboer og til sidst blev',
        'arvingernes bytte.',
        '',
        '## Hvordan Rom opfandt sine naboer',
        '',
        'I 58 f.Kr. rykkede Cæsar ind i Gallien, og i den beretning,',
        'han skrev om det, trak han en linje: Vest for Rhinen bor',
        'gallierne, øst for den *germanerne*. Det var pænt, klart og',
        'praktisk — og det var en opfindelse. Menneskerne der kaldte sig',
        'ikke sådan. De ville have kaldt sig chattere, cheruskere, markomannere',
        '— eller slet ikke som gruppe. Af en flod på kortet',
        'blev et folk. Rom havde brug for et navn til den anden side, og den,',
        'der trækker en grænse, skaber dermed også det, der ligger på den anden side.',
        '',
        'Hundrede og halvtreds år senere skrev en romersk senator ved navn',
        'Tacitus en slank bog om dette land: **Germanien**, omkring',
        '98 e.Kr. Den er den dag i dag den vigtigste kilde til de tidlige',
        'germanere — og man må tilføje, at Tacitus aldrig var der. Han',
        'samlede, hvad handelsfolk, soldater og ældre bøger kunne give.',
        '',
        'Men først og fremmest skrev han slet ikke rigtigt om Germanien. Han',
        'skrev om Rom. Hans germanere er trofaste, tapre, gæstfrie',
        'og ubestikkelige; de kender ingen luksus, deres ægteskaber er faste, deres',
        'anførere leder ved eksempel. Hver sætning er en bebrejdelse til den',
        'egen hovedstad, hvor Tacitus oplevede bestikkelse, pragt og',
        'angiveri. Det er en gammel tankefigur: den ædle vilde, der holder',
        'spejlet op foran os. Men det er netop et spejl — og man genkender',
        'altid kun sig selv i det.',
        '',
        'Denne bog har en farlig efterhistorie. Den blev længe regnet for',
        'tabt, dukkede i 1400-tallet op igen i et tysk kloster',
        '— og blev fra da af læst, som om den var et forfædrebevis.',
        'Af Tacitus’ „ublandede folk" byggede århundreder',
        'senere nationalister og til sidst nationalsocialisterne sig et',
        'bevis for deres raceteori; Himmler lod i 1943 i Italien lede efter',
        'det ældste håndskrift. En historiker har derfor kaldt Germanien',
        'en af de farligste bøger, der nogensinde er skrevet.',
        'Det bør man vide, før man tager ordet „germanere" i',
        'munden: Det er et romersk samlenavn, og det blev i 1900-tallet',
        'groft misbrugt.',
        '',
        'Det, arkæologien viser, er noget ganske andet end et folk:',
        'landsbyer, gårde, håndværk, forskellige begravelsesskikke,',
        'skiftende forbund. Og grupper, der opstår og forsvinder',
        'igen. Frankerne, alamannerne, sakserne — ingen af disse',
        'grupper havde „altid" været der. De dannede sig undervejs, ofte omkring',
        'en succesrig anfører og en fælles fortælling. Den,',
        'der drog med, hørte til, uanset herkomst. Forskningen kalder det',
        'stammedannelse: Et folk er her snarere noget, der opstår, end noget,',
        'der vandrer.',
        '',
        '## 9 e.Kr.: nederlaget, der skabte en grænse',
        '',
        'Rom havde så sandelig også tænkt sig at tage dette land. Så kom',
        'sommeren år 9. Statholderen Varus drog med tre legioner gennem',
        'ufremkommeligt terræn, ført af en forbundsfælle: Arminius, en',
        'cherusker, der havde stået i romersk tjeneste, var romersk ridder',
        'og kendte den romerske krigsførelse indefra. Han førte Varus i',
        'et baghold. Omkring 15 000 mand mistede livet. Kejser Augustus skal,',
        'som man fortæller, have slået hovedet mod døren: „Varus,',
        'giv mig mine legioner tilbage!"',
        '',
        'Rom slog sig efter dette aldrig igen varigt fast øst for',
        'Rhinen. To bemærkninger dertil, som ofte mangler i den tyske',
        'skoleversion. For det første: Arminius blev et godt årti senere',
        'slået ihjel af medlemmer af sin egen slægt — de frygtede,',
        'at han ville blive konge. Der var intet „Tyskland", der fejrede ham.',
        'For det andet: Præcis denne mand blev i 1800-tallet forvandlet til',
        '„Hermann fra Cheruskerne", med kæmpe mindesmærke og nationalpatos.',
        'Mindesmærket står den dag i dag. Det siger mere om 1800-tallet end',
        'om år 9.',
        '',
        '## Grænsen var en søm, ikke en mur',
        '',
        'Det, der opstod bagefter, er på kortet den mørke linje: Rhinen, Limes,',
        'Donau. Mellem Rhinen og Donau løb den tværs gennem landet — vold,',
        'grav, palisade, vagttårne i synsvidde, over 500 kilometer.',
        '',
        'Man forestiller sig gerne, at det var et bolværk. Det var det ikke;',
        'dertil var det alt for tyndt besat. Det var en kontrolleret tærskel:',
        'Den, der ville igennem, gjorde det ved en overgang, under opsyn og',
        'mod told. Og det var et sted for udveksling. På begge sider blev',
        'der handlet — romersk service, vin og mønter findes langt oppe i',
        'norden, germansk kvæg, rav og hår (til parykker) gik',
        'mod syd. Der blev giftet. Og der blev hvervet.',
        '',
        'Dette sidste punkt er det vigtigste, og det ødelægger hele billedet',
        'af „barbarernes stormløb". Rom havde brug for soldater og hentede dem',
        'på den anden side af grænsen. I 300-tallet var den romerske hær i',
        'store dele en hær af germansk oprindelse — med germanske officerer',
        'og germanske generaler. Manden, der omkring 400 forsvarede Italien mod',
        'goterne, hed Stilicho og var søn af en vandaler. Han',
        'var den mægtigste mand i vestriget, hans datter giftede sig med',
        'kejseren — og i 408 blev han henrettet på foranledning af en hofparti,',
        'fordi man mistroede ham. Kort efter gik titusinder af hans',
        'soldater over til Alarik. Det er en af de bitreste ironier i denne',
        'historie: Rom faldt ikke, fordi der kom for mange germanere, men',
        'blandt andet, fordi det ikke stolede på dem, der for længst var der.',
        '',
        '## 375: Det begynder med en flugt',
        '',
        'Omkring 375 dukkede rytterstyrker op øst for Don, som romerne',
        'kaldte „hunnerne". Hvor de kom fra, er den dag i dag omstridt. For denne',
        'historie er det afgørende, hvad de udløste: Goterne, som',
        'i årtier havde siddet nord for Sortehavet, handlet med riget',
        'og lært af det, kom under pres.',
        '',
        'I 376 stod de i titusindvis på Donaus nordbred og bad om',
        'optagelse. Rom sagde ja — sådanne optagelser var almindelige, riget',
        'havde brug for bønder og rekrutter. Så kom forvaltningens',
        'katastrofe. Forsyningen brød sammen, romerske embedsmænd drev',
        'ågerpriser; en samtidig beretter, at sultende måtte sælge deres børn',
        'i slaveri for at få hundekød. Af',
        'flygtninge blev oprørere.',
        '',
        'Den 9. august 378 stillede kejser Valens dem til kamp ved Adrianopel,',
        'uden at vente på vestens hær. Om aftenen var',
        'østens felthær tilintetgjort og kejseren død; hans lig blev',
        'aldrig fundet. Ammianus Marcellinus, selv officer, kaldte det det',
        'sværeste nederlag siden Cannae — og det lå seks hundrede år',
        'tilbage.',
        '',
        'Læg mærke til begyndelsen af denne kæde, for den modsiger billedet af',
        'plyndringstogtet: Folkevandringen begynder ikke med et angreb på Rom.',
        'Den begynder med mennesker, der flygter fra en anden og beder om',
        'adgang.',
        '',
        '## Stormen: 406 til 476',
        '',
        'Så gik det hurtigt — efter datidens forhold. Nytårsaften 406',
        'gik vandaler, alaner og svebere over Rhinen ved Mainz; en',
        'senere fortælling lader dem gå over isen. De drog gennem',
        'Gallien til Hispanien og i 429 med omkring 80 000 mennesker over',
        'Gibraltarstrædet til Afrika.',
        '',
        'I 410 tog Alarik med vestgoterne Rom og lod byen plyndre i tre dage.',
        'Militært betød det lidt: Rom havde i over hundrede år ikke',
        'længere været hovedstad. Sjæleligt var det uden fortilfælde. I otte',
        'hundrede år havde ingen fjende betrådt denne by. Hieronymus skrev fra',
        'Betlehem, at stemmen var blevet siddende i halsen på ham, mens han dikterede.',
        'Augustin svarede med sin største bog, „Om Gudsstaten": Hvis',
        'det evige rige kan falde, så var det aldrig det evige rige.',
        '',
        'I 439 tog vandalerne Karthago — det hårdeste slag, og det',
        'ikke på grund af byen. Der lå kornet, der ernærede Rom, og',
        'derfra kom skatterne, som hære blev betalt af. Et rige',
        'uden skatter kan ikke købe soldater; et rige uden soldater',
        'taber den næste provins. Fra da af kørte en nedadgående spiral.',
        '',
        'I 451 mødtes næsten hele Europa på en slagmark i Gallien: Den',
        'romerske hær under Aëtius, i forbund med vestgoterne, stillede sig',
        'op mod Attila og hans hunner. Se på, hvem der stod side om side —',
        'romere og gotere, de samme gotere, der i 410 havde plyndret Rom. Så',
        'enkel er opdelingen i „os" og „barbarerne" altså ikke.',
        '',
        'I 455 plyndrede vandalerne Rom en anden gang. I 476 afsatte Odoaker',
        'den sidste kejser. Hvad der kom bagefter, ser du på kortet i',
        'fasen „omkring 500": ikke længere ét rige, men seks kongeriger.',
        '',
        '## Den dag, hvor ingen lagde mærke til noget',
        '',
        'Og nu tilbage til spørgsmålet fra begyndelsen. Hvorfor lagde næsten',
        'ingen mærke til 476?',
        '',
        'Fordi der på nært hold næsten ikke skete noget. Der var stadig en kejser —',
        'i Konstantinopel. Der var stadig romersk ret, romerske skatter,',
        'latinske dokumenter, kirken med sine biskopper, byerne,',
        'sproget. De nye konger regerede med det gamle apparat, fordi det',
        'fungerede, og fordi de ikke havde noget bedre. Teoderik',
        'østgoteren lod romerske senatorer arbejde for sig i Ravenna og',
        'skrev til kejseren, at hans kongerige var en efterligning af',
        'kejserriget. Frankerne lod deres ret skrive på latin.',
        '',
        'Ordet **undergang** stammer fra en meget senere tid. Den',
        'engelske historiker Edward Gibbon kaldte sit seksbindsværk',
        'i 1776 „Romerrigets forfald og undergang" — og billedet af',
        'det store fald er siden ikke forladt nogens sind.',
        '',
        'I dag strides forskningen om det, og striden er ægte: Nogle',
        'taler om *transformation* — antikkens verden var ikke',
        'død, men blevet ombygget, gradvist, af mennesker, der',
        'ville forblive romerske. De andre holder imod, at det er for',
        'venligt: Den, der ser på fundene, finder efter 400 mindre handel,',
        'dårligere håndværk, mindre byer, mindre skrift. I Britannien',
        'forsvandt endda pottemagerhjulet. Det var for meget, mange mennesker',
        'en mærkbar nedtur i levestandarden, ingen overgang.',
        '',
        'Begge har belæg. Måske er det ærligste svar: Det kommer',
        'an på, hvor man står. For en biskop i Ravenna var det et',
        'magtskifte. For en bonde i Britannien var det slutningen',
        'på en verden.',
        '',
        '## Hvad ordet „folkevandring" fortier',
        '',
        'Læg mærke til ordene. På tysk hedder denne tid',
        '**Völkerwanderung** — det lyder som et stort, langsomt tog,',
        'som vogne, kvinder og børn, som et folk på rejse. På',
        'engelsk og fransk hedder samme tid',
        '„barbarernes indfald" — det lyder som overfald. Samme århundrede,',
        'to navne, to domme. Og begge navne blev givet af dem,',
        'der ikke var der.',
        '',
        'Tre ting, som begge ord ikke rummer:',
        '',
        '- **Der var få.** Grupperne talte titusinder, i et',
        '  rige med måske tyve til tredive millioner mennesker. Vandalerne',
        '  bragte i 429 omkring 80 000 mennesker til Afrika — færre,',
        '  end der i dag er plads til i en mellemstor by. Det var ingen flodbølge.',
        '  Det var et lille, bevæbnet mindretal, der rykkede frem i front.',
        '- **Det var ingen faste folk.** Den, der kom til Spanien som „vestgoter",',
        '  kunne være barnebarn af en mand, der hundrede år',
        '  tidligere ville have kaldt sig noget ganske andet. Undervejs sluttede',
        '  slaver, desertører, bønder og hele forbund sig til.',
        '- **Sejrerne ville høre til.** De smadrede ikke riget',
        '  for at sætte noget eget i dets sted. De ville ind.',
        '',
        'Hvad der blev tilbage, ser du den dag i dag. Af provinsernes latin blev',
        'fransk, spansk, portugisisk, italiensk, rumænsk — de',
        'germanske herrer overtog de undertryktes sprog, ikke',
        'omvendt. Kirken overtog forvaltningen, med stifter, der følger de',
        'romerske distrikter. Og ét kongerige på dette kort har præget',
        'Europa som intet andet: frankernes, hvoraf Frankrig',
        'og Karl den Stores rige senere udgik. Kun i Britannien blev',
        'tråden revet over: Der forsvandt latin, byerne forfaldt, og af',
        'anglernes navn blev England.',
        '',
        '## Og den anden side?',
        '',
        'Alt, hvad du lige har læst, er fortalt indefra — ud fra',
        'riget, med dets kilder, dets ord og dets',
        'selvbillede. Selv emnets navn stammer derfra.',
        '',
        'Fra den anden side mangler bøgerne. Men der er grave,',
        'bopladser, redskaber, våben, smykker af stor kunst; der er',
        'sprogene, kongerigernes lovnedtegnelser og fortællinger,',
        'der blev nedskrevet århundreder senere. Deraf kan man sagtens',
        'fortælle noget — bare anderledes og med større forsigtighed.',
        '',
        'Disse spørgsmål kan den romerske synsvinkel ikke besvare: Hvordan ser',
        'denne tid ud, hvis man ikke tager udgangspunkt i et riges ende, men',
        'i begyndelsen af et liv på et nyt sted? Hvad betyder det, når en',
        'gruppe „bosættes på romersk jord" — for dem, der kom,',
        'og for dem, der allerede var der? Og er et samfund uden',
        'skattelister, uden statholdere og uden bymure tilbagestående, eller',
        'er det bare ordnet anderledes?',
        '',
        'De tilhører en anden stemme.',
      ].join('\n'),
    },
    {
      id: 'germanisch',
      name: 'Den germanske synsvinkel',
      stimme: 'Hermes',
      text: [
        'Denne synsvinkel fortæller historien indefra — om de mennesker,',
        'som Rom kaldte „barbarer", og som selv ikke efterlod sig nogen',
        'historiebøger. Derfor må denne stemme ærligt sige, hvor den',
        'kommer fra: fra grave og bopladser, fra smykker og våben, fra',
        'lovnedtegnelser, der blev nedskrevet århundreder senere,',
        'og fra sange, der længe blev givet videre mundtligt, før',
        'nogen nedskrev dem. Det er mindre, end Rom efterlod — men det',
        'rækker til at se, at denne verden indefra så ganske anderledes ud',
        'end udefra.',
        '',
        '## En verden uden krøniker',
        '',
        'Germanerne havde en skrift — runerne —, men de brugte',
        'den ikke til historier, men til korte indskrifter: på',
        'våben, sten, smykker. „Dette spyd er mit" — ikke „Dette',
        'rige har jeg erobret". Deres historier levede i sange og',
        'fortællinger, der gik fra sanger til sanger. Set fra romersk side',
        'var det en mangel: Intet folk uden bøger kan være civiliseret.',
        'Set fra germansk side var det en anden måde at bevare',
        'erindring på: ikke i døde tegn, men i levende stemmer.',
        'Den, der kender sangene, har ikke brug for noget bibliotek.',
        '',
        '## Frihed, som Rom ikke kendte',
        '',
        'Det, Tacitus beskrev udefra, så sådan ud indefra:',
        'Forsamlingen — tinget —, hvor gruppens frie mænd besluttede om krig',
        'og fred, om ret og strid, uden at en',
        'statholder gav ordrer oppefra. Følgeskabet: En anfører',
        'vandt følgesvende ikke gennem embeder, men gennem gavmildhed',
        'og tapperhed — og de fulgte ham, så længe han førte dem.',
        'Troskab var ingen tvang, men en kontrakt, som begge sider',
        'til enhver tid kunne bryde.',
        '',
        'Set fra denne synsvinkel var den romerske orden ikke „højere udviklet",',
        'men bare anderledes: Skattelister, statholdere, bymure —',
        'det var en verden, hvor man adlød, fordi der var forskrifter.',
        'Den germanske verden adlød, fordi man fulgte en mand, man',
        'kendte. Om det var tilbagestående eller bare ordnet anderledes, afgør',
        'den, der ser udefra. Indefra var det frihedens',
        'orden.',
        '',
        '## Hvorfor vi drog af sted',
        '',
        'Den romerske fortælling kalder det, der skete, „folkevandring" —',
        'og mener dermed et stormløb mod riget. Indefra så det anderledes',
        'ud: De færreste drog af sted for at erobre. De flygtede. Fra øst',
        'rullede der noget imod, som der ikke var noget forsvar mod — hunnerne,',
        'ryttere fra steppen, som hele folk flygtede fra i alle retninger.',
        'I 376 stod goterne ved Donaus bred og bad om optagelse. De',
        'ville ikke ødelægge riget. De ville ind.',
        '',
        'Og de, der senere gik over Rhinen, søgte for det meste det samme:',
        'land, tryghed, et sted, hvor man kunne leve. At Rom',
        'så et angreb deri og følte sin egen verden truet, er',
        'forståeligt. Men set fra de vandrendes synsvinkel var det intet felttog,',
        'men fortsættelsen af overlevelsen med andre midler.',
        '',
        '## Hvad vi blev',
        '',
        'Og så skete der noget, som den romerske fortælling kun vanskeligt',
        'kan rumme: Sejrerne ville høre til. De nye konger',
        'kaldte sig romerske embedsmænd, lod deres ret skrive på latin',
        'og deres mønter præge efter romersk forbillede. De',
        'germanske herrer overtog de undertryktes sprog —',
        'deraf blev fransk, spansk, italiensk. Kun hvor Rom ikke',
        'havde været, vandt det eget sprog frem: Af anglerne',
        'blev England.',
        '',
        'Set fra denne synsvinkel er folkevandringen ingen undergang, men',
        'en begyndelse: Begyndelsen på nye kongeriger, nye sprog, et',
        'nyt Europa — bygget af mennesker, som Rom aldrig forstod,',
        'og som til sidst blev dets arvinger, hvad enten de ville eller ej.',
        '',
        '## Hvad denne synsvinkel gør anderledes',
        '',
        'To ting er vigtige, når man hører denne stemme.',
        '',
        'For det første: Den har intet eget navn. „Germanere", „barbarer",',
        '„vandaler" — alle disse navne blev givet udefra, af',
        'skribenter, der ikke spurgte menneskene. Grupperne',
        'kaldte sig chattere, cheruskere, gotere, frankere — eller slet ikke,',
        'fordi de først undervejs dannede sig som folk, omkring en anfører,',
        'et bytte, en fælles historie. At være et folk var',
        'her ingen tilstand, men en begivenhed.',
        '',
        'For det andet: Også denne rekonstruktion er en fortælling. Vi ved',
        'mindre, end vi gerne ville vide, og noget stammer fra senere',
        'kilder, der allerede tænkte romersk. Men retningen af',
        'fortællingen ændrer vurderingen: Hvad der for Rom var en storm, der',
        'afsluttede en verden, var for dem, der drog, begyndelsen på et liv',
        'på et nyt sted. Ingen af de to synsvinkler lyver. De',
        'ser blot fra modsatte ender på den samme vej.',
      ].join('\n'),
    },
  ],

  // Syntese (runde 8, fællesrevideret efter tilføjelsen af den germanske
  // synsvinkel af Hermes).
  synthese: [
    'To synsvinkler på den samme vej — set fra modsatte ender.',
    'Og mærkeligheden på forhånd: Ved dette emne gælder sætningen',
    '„Sejren skriver historien" ikke. Taberne har',
    'skrevet — det rige, der gik under, havde bibliotekerne.',
    'Sejrerne efterlod grave, smykker og sange, men ingen krøniker.',
    'Derfor er her ikke blot fortolkningen omstridt, men allerede',
    'kildesituationen: Vi kender denne tid næsten kun fra én pen.',
    '',
    '**Hvor de mødes:** Begge synsvinkler ser, at de germanske',
    '„sejrere" ville høre til — de overtog latinske titler,',
    'romersk ret, de undertryktes sprog. Begge kalder 476 et',
    'temmelig uspektakulært øjeblik. Og begge ved: De grupper, som Rom',
    'kaldte „germanere", var ingen faste folk, men konstruktioner, der',
    'dannede sig undervejs.',
    '',
    '**Hvor de skilles:** Den romerske fortælling ser i',
    'vandringen et stormløb mod riget — en verdens ende, som den',
    'kalder „barbarernes indfald". Den germanske synsvinkel fortæller om flugt',
    'og søgen: væk fra hunnerne, efter land, efter et sted at leve —',
    '„fortsættelsen af overlevelsen med andre midler". Ordvalget',
    'afslører perspektivet: „Undergang" eller „begyndelse"? „Indtrængere"',
    'eller „mennesker, der ville ind"? „Tilbagestående" eller „ordnet',
    'anderledes"? Selv navnene — germanere, barbarer, vandaler — er',
    'givet udefra; stemmen indefra havde ikke engang et',
    'eget navn.',
    '',
    '**Hvad der følger deraf:** Den, der kun kender den ene fortælling, holder den for',
    'hele historien — netop det gør den farlig. Den romerske',
    'synsvinkel modsiger sig selv flere steder: Den taler om „barbarernes',
    'stormløb" og fortæller samtidig, at den romerske hær i',
    '300-tallet i store dele bestod af germanere. Modsigelser',
    'i en kilde er ingen irritation — de er det sted, hvor man',
    'lærer mest.',
    '',
    '**Din dom begynder her:** Var folkevandringen en undergang',
    'eller en begyndelse? Svaret afhænger af, hvem du spørger: en',
    'biskop i Ravenna, en bonde i Britannien, en goter ved',
    'Donaus bred. Og det afhænger af, hvilket ord du vælger — for',
    'hvert ord er allerede en beslutning.',
  ].join('\n'),

  urteil: {
    frage: 'Var folkevandringen en undergang eller en ombygning? Og hvem bestemmer egentlig, hvilket af de to ord man bruger — dem, der tabte noget ved det, eller dem, der vandt noget?',
    hinweis: 'Der er her intet rigtigt og intet forkert. Tre anstød: For det første, prøv ordene selv — „Völkerwanderung" lyder som et tog med vogne og børn, „barbarernes indfald" som overfald; begge navne blev givet længe efter, og begge indeholder allerede en dom. For det andet kommer det an på, hvor man står: For en biskop i Ravenna var 476 et magtskifte, for en bonde i Britannien slutningen på en verden. For det tredje, tænk på en forandring, du selv har oplevet — flytning, skoleskift, en adskillelse i familien. Ville „undergang" eller „ombygning" have været det rette ord — og ville alle involverede have valgt det samme ord?',
  },

  quiz: [
    {
      frage: 'Hvor ved vi fra, hvad germanerne tænkte, og hvordan de levede?',
      antworten: [
        'Fra deres egne historiebøger, som de skrev med runer.',
        'Næsten kun fra romerske tekster og fra arkæologien — germanerne selv skrev runer til korte indskrifter, men ingen krøniker.',
        'Fra breve, der blev udvekslet mellem de germanske konger.',
      ],
      richtig: 1,
      erklaerung: 'Den vigtigste kilde, Tacitus’ „Germanien", stammer fra en romer, der aldrig var der — og den er i virkeligheden en kritik af Rom. Den ældste lange tekst på et germansk sprog er Wulfilas gotiske bibeloversættelse fra 300-tallet. Hvad vi ellers ved, kommer fra grave, bopladser og fund.',
    },
    {
      frage: 'Fandtes „germanerne" som ét folk?',
      antworten: [
        'Ja, et enhedsfolk med en konge og en fælles hovedstad.',
        'Nej — „germanere" er et romersk samlenavn for meget forskellige grupper; mange af dem (frankere, alamannere, gotere) dannede sig først undervejs.',
        'Ja, men først fra år 9 e.Kr., da Arminius samlede dem.',
      ],
      richtig: 1,
      erklaerung: 'Cæsar trak i 58 f.Kr. en linje ved Rhinen og kaldte alt øst for den „germanere". Menneskerne der ville have kaldt sig cheruskere, chattere eller markomannere. Grupper opstod omkring succesrige anførere, og den, der drog med, hørte til — uanset herkomst.',
    },
    {
      frage: 'Hvad begyndte folkevandringen med?',
      antworten: [
        'Med et planlagt angreb fra germanerne på byen Rom.',
        'Med afsættelsen af den sidste vestromerske kejser i 476.',
        'Med en flugt: Omkring 375 satte hunnerne goterne under pres, og i 376 bad titusinder ved Donau om optagelse i Romerriget.',
      ],
      richtig: 2,
      erklaerung: 'Rom tog dem ind — det var almindeligt, riget havde brug for bønder og soldater. Så svigtede forsyningen, romerske embedsmænd forlangte ågerpriser, og af flygtninge blev oprørere. I 378 faldt en romersk hær ved Adrianopel sammen med kejser Valens.',
    },
    {
      frage: 'Hvor mange mennesker var på vej ved en sådan vandring?',
      antworten: [
        'Millioner — halvdelen af Nordeuropa satte sig i bevægelse.',
        'Titusinder pr. gruppe; vandalerne bragte i 429 omkring 80 000 mennesker til Afrika, til et rige med tyve til tredive millioner indbyggere.',
        'Kun nogle få hundrede krigere, der erobrede riger.',
      ],
      richtig: 1,
      erklaerung: 'Det var ingen flodbølge, men et bevæbnet mindretal, der rykkede frem i front. Netop derfor beholdt de nye konger den romerske forvaltning: Uden den kunne de slet ikke have regeret deres lande.',
    },
    {
      frage: 'Hvad skete der med det latinske sprog, efter at de germanske riger var opstået?',
      antworten: [
        'Det forsvandt overalt, hvor germanske konger herskede.',
        'Det blev og blev til fransk, spansk, portugisisk, italiensk og rumænsk — de nye herrer overtog de undertryktes sprog. Kun i Britannien blev tråden revet over.',
        'Det blev erstattet af gotisk, fordi Wulfila havde oversat Bibelen.',
      ],
      richtig: 1,
      erklaerung: 'Frankerne lod deres ret skrive på latin, Teoderik regerede Italien med romerske embedsmænd. Den, der vil ødelægge en ting, genopbygger den ikke bagefter omhyggeligt — det er et af de stærkeste argumenter mod ordet „undergang". I Britannien var det anderledes: Der forsvandt latin, og af anglernes navn blev England.',
    },
  ],

  karteHinweise: [
    {
      label: 'omkring 100 e.Kr.',
      hinweis:
        'Den mørke linje er grænsen: Rhinen, Limes, Donau. Til venstre ligger et rige med veje, skatter og statholdere. Til højre er kortet tomt — ikke fordi der ikke boede nogen der, men fordi der ikke fandtes et rige med grænser. Rom kaldte landet „Germania magna" og dets beboere „barbarer", uden nogensinde at vide præcis, hvor langt det rakte.',
    },
    {
      label: '375–378',
      hinweis:
        'Fra øst sætter noget sig i bevægelse. Hunnerne løber over goterne ved Sortehavet; titusinder står i 376 ved Donau og beder om optagelse i riget. I 378 falder en romersk hær ved Adrianopel — sammen med kejseren. Grænsen står stadig — men den holder ikke længere, hvad den lover.',
    },
    {
      label: '406–455',
      hinweis:
        'Nytårsaften 406 går vandaler, alaner og svebere over Rhinen; i 410 plyndrer vestgoterne Rom, i 439 tager vandalerne Karthago og dermed kornet, i 455 bliver Rom plyndret en anden gang. Inde i riget ligger nu Attilas rige. Af Vesten er en rest tilbage — Østen står uforandret.',
    },
    {
      label: 'omkring 500',
      hinweis:
        'Fireogtyve år efter afsættelsen af den sidste vestromerske kejser er der i Vesten ikke længere ét rige, men seks. Deres konger regerer med romerske embedsmænd, lader deres lov skrive på latin og kalder sig efter romersk forbillede. Teoderik i Ravenna bærer endda titlen som romersk statholder — og mener den alvorligt.',
    },
    {
      label: '568',
      hinweis:
        'Kejser Justinian har generobret Nordafrika (534) og Italien (554) — og lagt Italien så øde, at det i 568 næsten ikke yder langobarderne modstand. Dermed slutter vandringen. Af rigerne på dette kort bliver det ét, der præger Europa: frankernes. Og ét har stået i næsten tusind år og vil stå i næsten tusind år endnu.',
    },
  ],
};

module.exports = germanen;
