// Oversættelse (dansk) af temaet „Japan — øverdenen mellem afsondring og
// åbning". Kilde: utils/themen/japan.js, kortfaser:
// utils/themen/karten/japan.js.
//
// Struktur: samme skema som de tyske temamoduler (utils/themen/schema.js),
// men uden karte-objektet; kortets faser er oversat i karteHinweise
// (label + hinweis), jf. STAND.md (oversættelsespipeline, da/ i repoet).
//
// Kildefilen rummer den europæiske og den kinesiske synsvinkel (stemmer:
// Opus og Hermes); syntesen nederst er fælles revideret og foreløbig
// (jf. CLAUDE.md, perspektiv-workflow). Gabet mellem de to fortællinger er
// netop temaets pointe: Europa kender Japan siden 1543 — Kina i over to
// tusind år. Den, der holder den europæiske fortælling for Japans historie,
// holder de sidste fem procent for helheden.
//
// Reine data — ingen UI-imports (arkitekturregel).

const japan = {
  id: 'japan',
  titel: 'Japan — øverdenen mellem afsondring og åbning',
  epoche: 'Fra Yamato-perioden omkring 300 e.Kr. til Meiji-restaurationen i 1868',

  aufhaenger: {
    frage: 'Et land lukker sig inde i to hundrede år — og slår en europæisk stormagt fire årtier efter sin åbning. Hvordan kan begge dele være det samme land?',
    text: [
      'Forestil dig, at dit land beslutter: Fra i morgen må ingen komme ind',
      'længere. Og ingen komme ud. Den, der forlader landet og vender tilbage,',
      'bliver henrettet. Skibe må kun bygges så små, at de slet ikke kan klare',
      'det åbne hav. Fremmede skibe bliver sendt væk eller beskudt.',
      '',
      'Det var præcis, hvad Japan gjorde fra 1639. I over to hundrede år. Ét',
      'eneste vindue forblev åbent: en kunstig ø i havnen i Nagasaki, 120 gange',
      '75 meter — mindre end to fodboldbaner. Der måtte omkring tyve hollændere',
      'bo, strengt bevogtet, og én gang om året rejse til Edo for at aflægge',
      'beretning til shogunen.',
      '',
      'To hundrede år senere, i 1853, tvang fire amerikanske krigsskibe åbningen',
      'igennem. Europa og Amerika var enige om, hvad der nu ville komme: endnu',
      'et tilbagestående land, som man kan dele op. Sådan var det gået alle',
      'vegne.',
      '',
      'Det gik anderledes. I 1905 sænkede den japanske flåde i Tsushimastrædet',
      'næsten hele den russiske Østersøflåde. For første gang i århundreder',
      'havde en asiatisk magt besejret en europæisk stormagt i en krig. Mellem',
      'de sorte skibes ankomst og denne dag lå tooghalvtreds år — et',
      'menneskeliv.',
      '',
      'Hvordan kan det lade sig gøre? Og hvorfor er det netop Europa, der undrer sig så meget?',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Europæisk synsvinkel',
      stimme: 'Opus',
      text: [
        'Sådan fortælles Japans historie i Europa: som en række af ankomster.',
        'Først kommer portugiserne, så bliver de fremmede fordrevet, så kommer',
        'amerikanerne, så bliver Japan moderne. Lægger du mærke til noget? I',
        'denne fortælling sker der noget med Japan — det gør intet selv. De',
        'handlede er altid os.',
        '',
        'Det er hverken tilfældigt eller ondskabsfuldt. Det er simpelthen synet',
        'hos en, der kom sent til: Da den første europæer satte foden på',
        'japansk jord, var hovedstaden Kyoto allerede 750 år gammel. Læs derfor',
        'det følgende som det, det er — blikket udefra, og endda fra meget langt',
        'udefra.',
        '',
        '## 1543: En storm, et skib, to geværer',
        '',
        'Et kinesisk handelsskib med portugisiske købmænd om bord bliver drevet',
        'mod den lille ø Tanegashima syd for Kyushu. Sådan begynder kontakten',
        'mellem Europa og Japan: ved en tilfældighed, på grund af dårligt vejr.',
        '',
        'Øens herre købte to arkebuser af de fremmede — forladere, upræcise,',
        'langsomme. Og nu kommer den del, som den europæiske fortælling gerne',
        'springer over: Japan kopierede ikke bare våbnet, det overhalede Europa.',
        'Inden for få årtier fremstillede japanske smede skydevåben i stort tal.',
        'I 1575, i slaget ved Nagashino, affyrede tre tusind skytter bag',
        'palisader i rækker — en taktik, der næsten ikke fandtes i Europa endnu.',
        'Det er meget muligt, at der omkring 1600 fandtes flere skydevåben i',
        'Japan end i noget europæisk land.',
        '',
        'Seks år efter stormen, i 1549, gik jesuitten Frans Xavier i land i',
        'Kagoshima. Missionen var i starten succesfuld: Omkring 1600 fandtes der',
        'måske 300 000 japanske kristne, flere end i mange europæiske',
        'fyrstendømmer. Japanerne kaldte de nyankomne *nanban* — „sydlige',
        'barbarer", fordi deres skibe kom fra syd. Europæerne var på deres side',
        'fascinerede: af renligheden, af høfligheden, af en krigerkaste, der',
        'havde sit eget æresbegreb. Frans Xavier skrev hjem, at dette var det',
        'bedste folk, han nogensinde havde set.',
        '',
        'I 1582 brød fire unge japanske adelsmænd op til Europa. De var af sted',
        'i otte år, blev modtaget i Lissabon, Madrid og Rom, paven hilste dem',
        'personligt, i Venedig blev der holdt fester. Da de kom tilbage i 1590,',
        'var Japan et andet land: Kristendommen var i mellemtiden forbudt.',
        '',
        '## Hvorfor Japan lukkede døren',
        '',
        'Den europæiske fortælling kalder det, der fulgte, for det meste',
        '„kristenforfølgelse" — og får det dermed til at se ud som religiøs',
        'fanatisme. Set fra Japan var det sikkerhedspolitik.',
        '',
        'De japanske magthavere så sig omkring. I 1571 havde spanierne taget',
        'Manila; på Filippinerne var først missionærerne kommet og så',
        'soldaterne. Portugal havde Malakka, Goa, Macau. Et mønster var',
        'genkendeligt. Dertil kom et indenrigspolitisk problem: En kristen',
        'lensherre adlød i sidste ende en pave i Rom — og ikke shogunen i Edo.',
        'For et herredømme, der netop havde forenet et sønderrevet land, var det',
        'uantageligt.',
        '',
        'I 1597 blev 26 kristne korsfæstet i Nagasaki. I 1637 rejste titusinder',
        'af overvejende kristne bønder sig i Shimabara; oprøret blev slået ned,',
        'og hollænderne skød med fra søsiden mod oprørernes fæstning — de ville',
        'vise, hvilken side de stod på. I 1639 blev portugiserne endeligt',
        'udvist. Enhver, der var mistænkt, måtte træde på et Kristusbillede,',
        '*fumi-e*; den, der tøvede, var dømt.',
        '',
        'Hollænderne måtte blive, af én eneste grund: De bragte ingen præster',
        'med. De ville handle, intet andet. Derfor fik de Dejima.',
        '',
        'Og nu det punkt, hvor den europæiske fortælling virkelig bliver skæv.',
        'Ordet **sakoku**, „lukket land", stammer slet ikke fra tiden selv: En',
        'japansk oversætter opfandt det i 1801, da han oversatte bogen af en',
        'tysk læge til japansk. Japan har altså lånt et navn til sin afsondring',
        'fra Europa. Og lukket var landet i øvrigt kun i én retning: Over',
        'Tsushima fortsatte handelen med Korea, over Satsuma den med',
        'Ryukyu-øerne, over Matsumae den med ainuerne i nord, og i Nagasaki lå',
        'foruden de hollandske også kinesiske skibe. Japan havde ikke lukket',
        'verden ude. Det havde lukket Europa ude — bortset fra tyve mænd på en',
        'sandbanke.',
        '',
        '## To hundrede års rygter',
        '',
        'Hvad vidste Europa i denne tid om Japan? Omtrent lige så meget, som',
        'man kan se gennem et nøglehul på 120 gange 75 meter.',
        '',
        'Næsten alt, hvad Europa troede at vide, stammede fra to mænd.',
        'Engelbert Kaempfer, en læge fra Lemgo, boede fra 1690 til 1692 på',
        'Dejima og skrev bagefter en „historie og beskrivelse af Japan"; den',
        'udkom i 1727 og forblev i hundrede år bogen om Japan. Philipp Franz',
        'von Siebold, også læge, kom i 1823 — og blev udvist i 1829, fordi man',
        'fandt japanske landkort hos ham. Kort var en statshemmelighed; Japan',
        'vidste meget præcist, hvad europæerne brugte dem til.',
        '',
        'Ind i dette hul satte Europa sin fantasi. Japan blev „det',
        'hemmelighedsfulde rige", et land af lak, silke og gådefulde skikke. Og',
        'da det så åbnede sig, kom overraskelsen fra en kant, ingen havde',
        "regnet med: fra kunsten. Fra 1860'erne nåede japanske farvetræsnit",
        'Paris — legenden siger, som indpakningspapir til porcelæn. Det, der',
        'derefter skete, kaldes **japonisme**: Monet samlede på træsnit, van',
        'Gogh malede Hiroshige billede for billede efter, Degas overtog de',
        'afskårne billedudsnit, Klimt guldet og fladerne. Europas mest moderne',
        'kunst lærte netop af det land, som Europa anså for tilbagestående.',
        '',
        '## De sorte skibe',
        '',
        'Den 8. juli 1853 sejlede fire krigsskibe fra De Forenede Stater ind i',
        'Tokyobugten, to af dem dampere med sorte skrog og rygende skorstene.',
        'Kommandør Matthew Perry nægtede at fortsætte til Nagasaki, som',
        'forskriften krævede, lod salutskud affyre, overrakte et brev fra sin',
        'præsident og bekendtgjorde, at han året efter ville hente svaret. Han',
        'kom tilbage i 1854 med ni skibe.',
        '',
        'Lad os kalde en spade for en spade: Det var afpresning med kanoner. Og',
        'det, der fulgte, var de såkaldte „ulige traktater" — europæere og',
        'amerikanere var i Japan ikke underlagt japansk ret, og Japan måtte',
        'ikke fastsætte sine egne toldsatser. Det samme havde man påtvunget',
        'Kina efter opiumskrigene. Det var den sædvanlige fremgangsmåde.',
        '',
        'Japan reagerede først, som man forventede: med vrede. Parolen lød',
        '*sonnō jōi* — „ær kejseren, fordriv barbarerne". Unge samuraier fra',
        'fyrstendømmerne Satsuma og Chōshū angreb udlændinge, beskød fremmede',
        'skibe — og blev skudt ned af vestlige flåder. Og så gjorde netop disse',
        'mænd noget bemærkelsesværdigt: De drog den modsatte lære af nederlaget.',
        'Hvis man ikke kan fordrive de fremmede, må man blive det, de er. I 1868',
        'væltede de shogunatet og stillede kejseren i spidsen —',
        'Meiji-restaurationen.',
        '',
        '## På én generation',
        '',
        'Det, der derefter skete, har næsten ingen modstykke i historien.',
        '',
        'I 1871 forlod halvdelen af den japanske regering sit eget land.',
        'Iwakura-missionen rejste i toogtyve måneder gennem De Forenede Stater',
        'og Europa for at se, hvordan fabrikker, parlamenter, skoler, værfter',
        'og hære fungerer. Tilbage kom en indkøbsliste: hæren efter preussisk',
        'forbillede, flåden efter britisk, retsvæsenet efter fransk og tysk,',
        'skolevæsenet efter amerikansk. Japan tog ikke „Vesten" — det tog fra',
        'hvert land det, der fungerede bedst dér.',
        '',
        'I 1872 kørte den første jernbane. I 1889 kom der en forfatning og snart',
        'et parlament. I 1894/95 besejrede Japan Kina, i 1904/05 Rusland — og',
        'den 27. maj 1905 sænkede admiral Tōgō i Tsushimastrædet næsten hele den',
        'russiske Østersøflåde, der havde sejlet halvvejs rundt om jorden.',
        '',
        'Europa var målløst. Aviser skrev om „miraklet". I kolonierne læste man',
        'det anderledes, nemlig som et signal: Den unge Jawaharlal Nehru i',
        'Indien, Sun Yat-sen i Kina, reformatorer i Det Osmanniske Rige — for',
        'dem var 1905 beviset på, at det europæiske herredømme ikke var en',
        'naturlov.',
        '',
        'To ting bør man ikke overse her. For det første: „Mirakel" er et',
        'bekvemt ord. Det lyder som trolddom og sparer spørgsmålet om, hvilke',
        'forudsætninger dette land allerede havde — en af verdens højeste',
        'læsefærdighedsrater, en millionby, en pengeøkonomi, veje, forvaltning,',
        'et håndværk af stor præcision. Japan startede ikke fra nul i 1868. Det',
        'startede fra meget.',
        '',
        'For det andet: Japan overtog fra Vesten ikke kun jernbaner og',
        'forfatninger. Det overtog også ideen om, at en moderne magt må have',
        'kolonier. I 1895 tog det Taiwan, i 1910 annekterede det Korea. Vejen',
        'fortsatte, over Manchuriet og ind i Anden Verdenskrig. Det er den del',
        'af fortællingen, som Europa sjældent fortæller som det, den også er:',
        'en lære, der blev givet videre.',
        '',
        '## Og den anden side?',
        '',
        'Alt, hvad du lige har læst, dækker omkring tre hundrede år — og også',
        'dem kun udefra. Japans historie er mange gange længere, og dens',
        'afgørende nabo var aldrig Europa.',
        '',
        'I over halvandet årtusinde kom næsten alt nyt over havet fra vesten:',
        'vådris, bronze, jern, skrifttegnene, buddhismen, kalenderen,',
        'embedsvæsenet, grundplanen for den første hovedstad Nara — alt sammen',
        'fra Kina, for det meste via Korea. Japan har aldrig bare afskrevet; det',
        'har valgt ud, bygget om, udeladt. Og i 1894 besejrede denne elev sin',
        'lærer.',
        '',
        'Hvordan fortæller man det fra den anden side? Hvad betyder det for et',
        'land, der kalder sig „Riget i Midten", når naboøen, der i århundreder',
        'sendte gesandtskaber, pludselig er stærkere? Og hvordan lyder Japans',
        '„åbning" for et Kina, der på samme tid blev åbnet af de samme',
        'kanonbåde — blot med en helt anden udgang?',
        '',
        'Disse spørgsmål kan den europæiske synsvinkel ikke besvare. De hører',
        'til hos en anden stemme.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Kinesisk synsvinkel',
      stimme: 'Hermes',
      text: [
        'Denne synsvinkel fortæller om Japan tæt på — fra Kina, naboen, der',
        'kendte Japan, længe før Europa vidste, at øerne findes. Den ældste',
        'skriftlige omtale af Japan står i en kinesisk krønike. For Kina har',
        'Japan aldrig været „det hemmelighedsfulde rige", men den fortrolige',
        'nabo på den anden side af havet — eleven, der gik egne veje. Og det',
        'er set fra Kina den egentlige historie.',
        '',
        '## Eleven',
        '',
        'Næsten alt, der engang gjorde Japan til en stat, kom fra Kina:',
        'skrifttegnene, buddhismen, kalenderen, forestillingen om embedsmænd',
        'og forvaltning, endda grundplanen for den første hovedstad Nara, der',
        'blev bygget som et lille Chang’an. I århundreder sendte japanske',
        'herskere gesandtskaber til fastlandet for at lære. Kina så deri den',
        'naturlige orden: Midten gav, kanterne tog — og det japanske hof',
        'betalte sin tribut, som det sømmede sig.',
        '',
        '## Titlen, der var en formærmelse',
        '',
        'Men tidligt viste eleven, at han ikke ville forblive det, han var. Den',
        'japanske hersker kaldte sig *tenno* — „himlens hersker". Set fra Kina',
        'var det en formærmelse: Der kunne kun være ÉN himlens søn, og han sad',
        'i Kina. At naboen gjorde samme krav gældende, var et stille oprør —',
        'det første skridt på en vej, der beskæftiger Kina den dag i dag.',
        '',
        'Og så kom det egentlige brud, som udenforstående næsten ikke kan se:',
        'Japan holdt op med at tage del i kredsløbet. I Kina skiftede',
        'dynastierne, når Himlens mandat var forspildt — det var verdens orden.',
        'I Japan derimod bestod kejserlinjen, århundrede efter århundrede,',
        'mens den virkelige magt vandrede til krigerne, samuraierne, og deres',
        'shoguner. Set fra Kina var det en orden uden mandat: et herredømme,',
        'der aldrig fornyer sig, og en magt, der ikke tilhører den, der udøver',
        'den. Eleven havde overtaget formerne — og erstattet kernen med noget',
        'eget.',
        '',
        '## Frækheden i 1592',
        '',
        'At eleven ville udfordre læreren, viste sig i 1592. Feltherren',
        'Hideyoshi, der netop havde forenet Japan, faldt ind i Korea — i et',
        'land, der hørte til Kina, som en vasal hører til sin herre. Kina',
        'sendte en hær, og efter års krig trak Japan sig tilbage. Set fra Kina',
        'var det en ordenens sejr: Angriberen var blevet slået tilbage, eleven',
        'sat på plads.',
        '',
        'Men den egentlige lære læste Kina først senere. Hideyoshis felttog',
        'viste, at Japan ikke kun kunne lære, men også angribe — og at det ikke',
        'anerkendte den plads, Kina havde reserveret til sig selv.',
        '',
        '## Ydmygelsen i 1894',
        '',
        'Og så kom året 1894. Japan, der netop havde moderniseret sig efter',
        'vestligt forbillede, angreb Kina — og vandt. Eleven besejrede læreren.',
        'For Kina var det mere end et nederlag: Det var sammenbruddet af en',
        'verdensorden. Riget i Midten, der i årtusinder havde været midten,',
        'måtte se til, hvordan øen i kanten ydmygede det.',
        '',
        'På samme tid var Kina og Japan blevet „åbnet" af de samme kanonbåde —',
        'med vidt forskelligt udfald. Japan drog straks læren: Den, der lærer',
        'af Vesten, overlever. Kina tøvede, og tøven kostede. Set fra Kina er',
        'Japans modernisering derfor intet „mirakel" — et ord, Europa bruger,',
        'fordi det ikke kender forhistorien. Det var en beslutning, Japan traf,',
        'og en ydmygelse, Kina led, fordi det ikke traf sin egen.',
        '',
        '## Hvad dette syn gør anderledes',
        '',
        'To ting adskiller den kinesiske fortælling fra den europæiske.',
        '',
        'For det første: Japan var for Kina aldrig en gåde, men en målestok.',
        'Kina målte sig med Japan, længe før Vesten trådte på scenen — først',
        'som elev, så som rival, til sidst som lærestykke. Spørgsmålet „Hvorfor',
        'er Japan stærkere end os?" har ikke sluppet kinesisk politik siden',
        '1894. Europa så Japan gennem et nøglehul; Kina så Japan over',
        'skulderen — og forstod det i sidste ende heller ikke. Nærhed er ingen',
        'garanti for forståelse.',
        '',
        'For det andet: Den kinesiske fortælling er tilbøjelig til at tale',
        'Japans selvstændighed ned. „Alt kom fra Kina" — det er sandt og dog',
        'en forenkling, som naboen med rette ville afvise. Japan har aldrig',
        'afskrevet; det har valgt ud, bygget om, udeladt. Den, der kun',
        'fortæller den ene halvdel, begår samme fejl som den europæiske',
        'fortælling, der begynder i 1543: Han forveksler sit udsnit med hele',
        'historien.',
        '',
        'Det er ingen korrektion af det europæiske syn. Det er nabostemmen,',
        'der kendte eleven, før verden opdagede ham — og som den dag i dag',
        'lever med spørgsmålet, om eleven må overgå læreren uden at forråde',
        'ham.',
      ].join('\n'),
    },
  ],

  synthese: [
    'To naboer fortæller om Japan: Europa, der har kendt det siden 1543 —',
    'og Kina, der har kendt det i over to tusind år. Og begge fortællinger',
    'siger til syvende og sidst mere om fortællerne end om Japan.',
    '',
    '**Hvor de mødes:** Begge synsvinkler fortæller om overtagelsen — Japan',
    'lærte af Kina (skrift, buddhisme, forvaltning) og senere af Vesten',
    '(jernbaner, forfatning, hær). Begge kalder „åbningen" i 1853 for tvungen,',
    'ikke frivillig — Europa taler åbent om kanonbådsafpresning, Kina minder',
    'om, at det på samme tid blev brudt op af de samme magter. Og begge',
    'undrer sig over moderniseringen — blot med forskellige ord.',
    '',
    '**Hvor de skilles:** Den europæiske fortælling begynder ved ankomsterne —',
    '„opdaget", „åbnet", „mirakel". I den sker der noget med Japan; de',
    'handlede er de fremmede. Den kinesiske fortælling begynder ved eleven,',
    'der vælger, bygger om, udelader — og til sidst udfordrer læreren: 1592 i',
    'Korea, 1894 i krigen mod Kina. For Europa var 1905 „miraklet ved',
    'Tsushima". For Kina var 1894 ydmygelsen, der afsluttede en verdensorden.',
    'Ordvalget afslører det: „det hemmelighedsfulde rige" (Europa, der så',
    'gennem et nøglehul) — og „den fortrolige nabo" (Kina, der så over',
    'skulderen og i sidste ende heller ikke forstod ham).',
    '',
    '**Hvad der følger deraf:** Begge fortællinger forveksler deres udsnit',
    'med hele historien. Europa dækker de sidste par procent og lader, som om',
    'det er historien; Kina er tilbøjelig til at tale Japans selvstændighed',
    'ned, fordi „alt kom fra Kina". Japan selv — der hverken ville være en',
    'gåde eller en elev — har i dette kapitel ingen egen stemme. Måske er',
    'netop det den bedste øvelse: En historie, der afslører så meget om',
    'fortællerne, gør synligt, hvor meget al historieskrivning er en',
    'stedbestemmelse.',
    '',
    '**Din dom begynder her:** Hvis fortælling hjælper dig mest til at forstå',
    'Japans vej — den udefra (Europa) eller den fra naboen (Kina)? Og hvilke',
    'spørgsmål ville du selv stille Japan, hvis det fik en egen stemme?',
  ].join('\n'),

  urteil: {
    frage: 'Japan har i over to hundrede år bevidst afsondret sig fra Europa — og blev i 1853 tvunget til at åbne sig med krigsskibe. Var afsondringen en klog beslutning eller en dyr fejltagelse? Og hvem har egentlig ret til at bestemme, om et land holder sine døre åbne: landet selv, eller dem, der vil ind?',
    hinweis: 'Der er her ikke noget rigtigt og forkert. To tanker at dreje videre på: Naboerne, der ikke afsondrede sig — Kina, Indien —, blev i 1800-tallet delt op eller erobret; Japan ikke. Siger det noget om afsondringen? Og: Prøv dit svar en gang til ved at bytte roller. Hvad, hvis et andet land ankrer op for din kyst og kræver handel?',
  },

  quiz: [
    {
      frage: 'Var Japan under afsondringen virkelig afskåret fra hele verden?',
      antworten: [
        'Ja, i over 200 år kom og gik der ingen.',
        'Nej: Handelen med Korea (via Tsushima), med Ryukyu-øerne og med ainuerne i nord fortsatte, og i Nagasaki lå kinesiske skibe ved siden af de hollandske.',
        'Nej, men kun fordi enkelte smuglere brød reglerne.',
      ],
      richtig: 1,
      erklaerung: 'Afsondret var Japan først og fremmest over for Europa — og selv dér forblev Dejima åbent. Mod Asien fandtes der fire regulerede porte. „Lukket land" er derfor et ord, der siger mere om det europæiske blik end om Japan: Den, der ikke måtte ind, anså landet for lukket.',
    },
    {
      frage: 'Hvem var samuraierne?',
      antworten: [
        'En krigerkaste i en herres tjeneste. Fra 1185 lå den faktiske magt hos deres anførere, shogunerne — kejseren forblev et symbol.',
        'Kejserens livgarde, der altid kæmpede direkte for ham.',
        'Vandrende enkeltkæmpere uden herre og uden land.',
      ],
      richtig: 0,
      erklaerung: 'Dobbeltstyret prægede Japan i næsten 700 år: en kejser med værdighed i Kyoto, en shogun med tropper — først i Kamakura, senere i Edo. Herreløse samuraier fandtes også, man kaldte dem ronin, men det var undtagelsen.',
    },
    {
      frage: 'Hvad skete der i 1853 i Tokyobugten?',
      antworten: [
        'En tyfon ødelagde en fremmed flåde, som allerede i 1274 og 1281.',
        'Den sidste shogun trådte frivilligt tilbage.',
        'Fire amerikanske krigsskibe under kommandør Perry tvang Japans åbning igennem — med salutskud og løftet om at vende tilbage året efter med flere skibe.',
      ],
      richtig: 2,
      erklaerung: 'Sådan noget kalder man kanonbådsdiplomati. Perry kom tilbage i 1854 med ni skibe; Japan åbnede to havne. Femten år senere var shogunatet afskaffet — åbningen udefra udløste en omvæltning indefra.',
    },
    {
      frage: 'Hvor gammelt er det japanske kejserhus?',
      antworten: [
        'Det blev nyoprettet i 1868, da shogunatet sluttede.',
        'Det er verdens ældste uafbrudte monarki — de tidligste kejsere er dog sagnomspundne, sikkert belagt bliver linjen først fra omkring det 6. århundrede.',
        'Det opstod først med forfatningen fra 1889.',
      ],
      richtig: 1,
      erklaerung: 'Netop fordi kejseren det meste af tiden ikke havde nogen magt, overlevede han ethvert magtskifte: Den, der regerede, gjorde det i hans navn. I 1868 behøvede man derfor ikke opfinde en ny hersker — man hentede den frem, der havde været der hele tiden.',
    },
    {
      frage: 'Hvordan begyndte kontakten mellem Europa og Japan i 1543?',
      antworten: [
        'Med en handelsaftale mellem Portugal og shogunen.',
        'Med et gesandtskab fra paven.',
        'Med et skib, som en storm drev til Tanegashima — om bord portugisiske købmænd og to skydevåben, som Japan inden for få årtier selv byggede i stort tal.',
      ],
      richtig: 2,
      erklaerung: 'Allerede den første kontakt modbeviser billedet af det forundrede, tilbagestående Japan: I 1575 affyrede tre tusind skytter ved Nagashino i rækker. Omkring 1600 fandtes der formentlig flere skydevåben i Japan end i noget europæisk land.',
    },
  ],

  karteHinweise: [
    {
      label: 'omkring 600',
      hinweis:
        'Yamato-herskerne regerer fra sletten omkring Nara: Honshus syd og midte, Shikoku, Kyushu. Norden tilhører emishi-folket, Ezo i nordøst ligger uden for verden. Alt nyt kommer over havet — skrift, buddhisme, forvaltning, alt sammen fra Kina og via Korea.',
    },
    {
      label: '1274 og 1281',
      hinweis:
        'Kublai Khan, storkhanen fra det foregående kapitel, vil også have Japan. To gange sætter en flåde over fra Korea, i 1281 derudover en anden fra Kina. To gange knuser en tyfon skibene. Japan kalder disse storme „kamikaze" — guddommelig vind — og drager en slutning, der virker helt frem til 1945.',
    },
    {
      label: 'omkring 1700',
      hinweis:
        'Hele Japan under én shogun: Tokugawaerne regerer fra Edo, kejseren forbliver i Kyoto uden magt. Udadtil har landet siden 1639 været lukket — ingen udrejse, ingen fremmede skibe. Kun på øen Dejima ved Nagasaki forbliver et vindue på 120 gange 75 meter åbent.',
    },
    {
      label: '1868',
      hinweis:
        'Femten år efter Perrys ankomst er shogunatet afskaffet, kejseren tilbage i spidsen, hovedstaden hedder nu Tokyo. Fladerne ændrer sig næsten ikke — Ezo bliver indlemmet som Hokkaido —, men landet er et andet: Det bygger jernbaner, fabrikker, en forfatning og en flåde.',
    },
  ],
};

module.exports = japan;
