// Dansk oversættelse: Den nye verdensorden og den kolde krig (1945–1991).
// Tre stemmer: Vestens syn (USA, Storbritannien, Vesteuropa og Forbundsrepublikken,
// stemme: Opus), Østens syn — Sovjetunionen, Warszawapagten, DDR (stemme: Hermes) —
// og tyskernes syn i øst og vest (stemme: Hermes); syntesen fører de tre sammen.
// Kortets faser er oversat i karteHinweise nederst.
// Rene data — ingen UI-imports (arkitekturregel).

module.exports = {
  id: 'kalter-krieg',
  titel: 'Den nye verdensorden og den kolde krig',
  epoche: '1945–1991',

  aufhaenger: {
    frage: 'To lande, der sammen havde besejret Hitler, rettede inden for to år deres våben mod hinanden — og fyrre år senere forsvandt den ene side, uden at der var faldet et eneste skud mellem de to blokke. Hvordan bliver allierede så hurtigt det modsatte, og hvorfor bryder et verdensrige sammen, som ingen har besejret?',
    text: [
      'I april 1945 mødtes amerikanske og sovjetiske soldater ved Elben ved Torgau.',
      'Der findes fotografier af det: unge mænd, der omfavner hinanden, sidder på',
      'kampvogne og griner ind i kameraet. To år senere var der mellem deres lande',
      'opstået en tilstand, som man havde brug for et nyt ord for — den kolde krig.',
      'Kold, fordi de to stormagter aldrig kæmpede direkte mod hinanden. Krig, fordi',
      'de ellers gjorde alt det, der kendetegner krig: opruste, true, spionere,',
      'samle allierede og lade dem kæmpe mod hinanden i fremmede lande.',
      '',
      'Midt igennem løb en linje, og den løb midt gennem Tyskland. 1.393 kilometer',
      'hegn, miner og vagttårne, derudover 155 kilometer mur omkring Vestberlin. En',
      'by, hvor man kunne sidde i en sporvogn og, når man steg ud, stå i et andet',
      'verdenssystem. Ingen andre steder var den kolde krig så bogstaveligt til at se.',
      '',
      'To gange var verden tæt på afgrunden: i oktober 1962, da sovjetiske raketter',
      'blev opdaget på Cuba, og igen og igen i de øjeblikke, hvor en radarskærm viste',
      'noget, der slet ikke var der. På højdepunktet lå der på verdensplan over 60.000',
      'atomsprænghoveder på lager — nok til at ødelægge enhver større by på jorden',
      'flere gange.',
      '',
      'Og så, i 1989, brød den ene side sammen. Ikke gennem et nederlag på slagmarken,',
      'men gennem tomme hylder, en økonomi der ikke længere kunne følge med, en',
      'oliepris der styrtede, en generalsekretær der ville reformere — og gennem',
      'mennesker, der gik på gaden uden våben og ikke gik igen. Den 25. december 1991',
      'ophørte Sovjetunionen med at eksistere.',
      '',
      'Dette kapitel begynder med Vestens syn. Det er én af flere stemmer, ikke den',
      'rigtige — hvem der taler først, afhænger af, hvem der har skrevet denne runde,',
      'og er ikke en rangorden.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'Vestens syn — USA, Storbritannien, Vesteuropa og Forbundsrepublikken',
      stimme: 'Opus',
      text: [
        'Denne stemme fortæller fra Washington, London, Paris og Bonn: fra',
        'regeringskvartererne, hvor beslutningerne blev truffet, men også fra',
        'stuerne, hvor nyhederne kørte, fra Vestberlin, der i fyrre år forstod sig',
        'selv som en ø, og fra skolerne, hvor børn lærte, hvad man skulle gøre i',
        'tilfælde af et angreb.',
        '',
        'Den er ligeværdig med kapitlet øvrige stemmer. At den står først her, er',
        'ikke en rangorden — det skyldes blot, hvem der har overtaget denne runde. Og',
        'den har en opgave, som den stiller sig selv: Den må ikke fortælle',
        'sejrherrernes fortælling, der var så bekvem efter 1989. Vesten førte den',
        'kolde krig med midler, der modsagde dens egne principper, og denne tekst',
        'nævner dem — ikke i en sidebemærkning, men i et selvstændigt afsnit.',
        '',
        '## Fra allierede til modstandere (1945–1947)',
        '',
        'Alliancen mod Hitler var et formålssamfund. Franklin D. Roosevelt, Winston',
        'Churchill og Josef Stalin var forenet af en fælles fjende og ellers af lidt.',
        'På konferencen i Jalta i februar 1945 og i Potsdam i juli og august blev det',
        'fastlagt, hvad der skulle ske med Tyskland: afvæbning, afnazificering, fire',
        'besættelseszoner, krigsskadeserstatninger, Polens forskydning mod vest. Hvad',
        'der ikke blev fastlagt, var det afgørende — hvordan det skulle gå videre,',
        'når den fælles fjende var besejret.',
        '',
        'Fra vestligt synspunkt blev svaret givet i Østeuropa, og det gik hurtigt. I',
        'Polen, Rumænien, Bulgarien og Ungarn opstod der mellem 1945 og 1948',
        'regeringer, som var ved magten efter valg, hvis lovlighed ingen i Vesten',
        'troede på. I februar 1948 overtog kommunistpartiet i Tjekkoslovakiet — det',
        'eneste land i regionen med et fungerende demokrati mellem krigene — den',
        'fulde magt. For mange i Vesten var det øjeblikket, hvor mistillid blev til',
        'vished.',
        '',
        'Og modparten? Dens bevæggrunde hører til her, og denne stemme gengiver dem,',
        'som de var, ikke som karikatur. Sovjetunionen havde mistet omkring 27',
        'millioner mennesker i Anden Verdenskrig — flere end noget andet land. Den',
        'var inden for tredive år blevet overfaldet to gange fra vest, 1914 og 1941,',
        'og anden gang havde angrebet været en udryddelseskrig. Den, der i Moskva',
        'spurgte til sikkerhed, tænkte på et bælte af venligsindede stater mellem sig',
        'og Tyskland. Fra vestligt synspunkt var den deraf afledte frygt for',
        'omringelse overdreven — den forklarede ikke, hvorfor der i Warszawa, Prag og',
        'Budapest måtte indsættes regeringer mod befolkningens vilje. Opfundet var',
        'den dog ikke, og den, der affærdiger den som et rent påskud, forstår ikke',
        'den sovjetiske politik i disse år.',
        '',
        'To tekster gav den vestlige politik sin form. I februar 1946 sendte den',
        'amerikanske diplomat George F. Kennan fra Moskva det „lange telegram":',
        'Sovjetunionen kunne ikke formildes gennem indrømmelser, men godt inddæmmes',
        'gennem tålmodig modstand ved dens grænser. Af tanken blev der et ord —',
        '**containment**, inddæmning — og af ordet retningslinjen for fyrre år. Den',
        '5. marts 1946 sagde Winston Churchill i den amerikanske by Fulton den',
        'sætning, der blev epokens overskrift: Fra Stettin ved Østersøen til Trieste',
        'ved Adriaterhavet havde et **jerntæppe** sænket sig over kontinentet.',
        '',
        'Den 12. marts 1947 proklamerede præsident Harry S. Truman over for',
        'Kongressen, hvad der siden hedder **Truman-doktrinen**: USA ville støtte',
        'frie folk, der gjorde modstand mod væbnede mindretal eller ydre pres. Den',
        'konkrete anledning var Grækenland, hvor en borgerkrig rasede, og Tyrkiet,',
        'som Moskva lagde pres på; Storbritannien kunne ikke længere yde støtten af',
        'egen kraft. Kravet var imidlertid verdensomspændende — og deri lå begge',
        'dele: et opgør med isolationismen fra 1930\'erne, som havde set til, mens',
        'Europa gled mod krig, og begyndelsen på en politik, der til sidst også',
        'skulle støtte diktatorer, så længe de var antikommunistiske.',
        '',
        '## Marshallplanen (1947/48) — hjælp og magtpolitik på samme tid',
        '',
        'Den 5. juni 1947 holdt udenrigsminister George C. Marshall en tale på',
        'Harvard, hvor han tilbød Europa amerikansk økonomisk hjælp. Den blev til',
        'European Recovery Program: omkring 13 milliarder dollar mellem 1948 og',
        '1952 — efter nutidens købekraft langt over hundrede milliarder —, derudover',
        'råstoffer, maskiner, fødevarer og fagkundskab. De europæiske byer lå i',
        'ruiner, vinteren 1946/47 havde været den koldeste i mands minde, i flere',
        'lande sultede mennesker. Marshallplanen gjorde en ende på denne tilstand, og',
        'det er ingen lille sag.',
        '',
        'Den var også magtpolitik, og denne stemme siger det selv i stedet for at',
        'lade sig foreholde det. For det første: Pengene skabte afsætningsmarkeder',
        'for den amerikanske industri, som efter krigen stod som den eneste uskadte,',
        'og bandt Vesteuropa til dollaren. For det andet: Den var knyttet til',
        'betingelser — modtagerne skulle lægge deres økonomiske data frem, planlægge',
        'i fællesskab og åbne handelen. For det tredje, og det er det vigtigste',
        'punkt: Tilbuddet gik udtrykkeligt også til Sovjetunionen og til Polen og',
        'Tjekkoslovakiet. Moskva afslog i juli 1947 i Paris og forbød staterne i sin',
        'interessesfære at tage imod; den tjekkoslovakiske regering, der først ville',
        'sige ja, måtte trække sit tilsagn tilbage. Fra Moskvas synspunkt ville det',
        'at tage imod have betydet at give Washington indsigt i egne regnskaber og',
        'gøre sig økonomisk afhængig — også det er en forståelig tanke, ikke blot',
        'trods.',
        '',
        'Dermed var Europas deling blevet økonomisk. Vesten fik kreditter og et',
        'fælles marked, østen Rådet for gensidig økonomisk bistand (1949) og en',
        'orden, hvor Moskva satte priserne. Denne beslutning fra 1947 forklarer en',
        'stor del af det, der fyrre år senere kunne ses på de tomme hylder.',
        '',
        '## Berlin 1948/49 — luftbroen',
        '',
        'Den 20. juni 1948 indførte vestzonerne D-marken; tre dage senere gjaldt den',
        'også i Berlins vestsektorer. For den vestlige side var det en nødvendighed —',
        'den gamle rigsmark var værdiløs, og sortbørsen regerede. For den sovjetiske',
        'side var det bruddet på den fælles administration af Tyskland, og den',
        'læsning er ikke usandsynlig: En egen valuta er halvvejen til en egen stat.',
        'Den 24. juni 1948 blev alle veje, jernbanelinjer og vandveje til Vestberlin',
        'spærret. To millioner mennesker var afskåret.',
        '',
        'Det, der derefter skete, er den mest indtryksfulde historie, Vesten har at',
        'fortælle fra dette kapitel. De tre luftkorridorer var blevet aftalt',
        'skriftligt i 1945 — vejene var spærret, luftvejen var sikret. I elleve',
        'måneder forsynede omkring 280.000 flyvninger byen med omkring 2,3 millioner',
        'tons kul, mel, medicin og endda enkeltdelene til et kraftværk. På',
        'højdepunktet landede der et fly hvert tredje minut. Lufthavnen Tegel blev',
        'bygget på halvfems dage, overvejende af berlinerkvinder — de såkaldte',
        '„Trümmerfrauen" —, der fjernede murbrokkerne. Omkring firs mennesker',
        'mistede livet ved flystyrt, briter, amerikanere og tyskere.',
        '',
        'Den amerikanske pilot **Gail Halvorsen** begyndte at kaste slik ud over',
        'boligkvartererne med hjemmelavede faldskærme. Af den private idé blev',
        'aktionen „Little Vittles", og af flyene blev **rosinbomberne**. Den 12. maj',
        '1949 ophævede den sovjetiske side blokaden.',
        '',
        'Det, der virkelig skete her, var en omvending: Tre år efter afslutningen på',
        'en krig, som Tyskland havde begyndt, stod berliner børn ved',
        'indflyvningskorridoren og vinkede til de fly, der havde bombet deres by. Af',
        'besættere blev beskyttere. Denne stemme nævner også det ubehagelige derved:',
        'Luftbroen var en humanitær bedrift og en politisk succes på samme tid, og i',
        'Washington og London var begge dele kendt fra begyndelsen. Den, der vinder',
        'en bys hjerter, vinder en position.',
        '',
        'Samme år opstod to tyske stater: Forbundsrepublikken (grundloven af 23. maj',
        '1949) og DDR (7. oktober 1949). Ingen af dem forstod sig selv som endelig.',
        'Bonn blev hovedstad, fordi byen var ubetydelig nok til at virke foreløbig.',
        '',
        '## To blokke: NATO 1949, Warszawapagten 1955',
        '',
        'Den 4. april 1949 underskrev tolv stater i Washington Nordatlantiktraktaten:',
        'USA, Canada, Storbritannien, Frankrig, Italien, Belgien, Nederlandene,',
        'Luxembourg, Norge, Danmark, Island og Portugal. Kernen er artikel 5 — et',
        'angreb på én gælder som et angreb på alle. For første gang i sin historie',
        'indgik USA i fredstid en alliance med europæiske stater.',
        '',
        'Den første generalsekretær, Lord Ismay, siges at have sammenfattet NATOs',
        'formål sådan: at holde amerikanerne inde, russerne ude og tyskerne nede. Om',
        'han nogensinde har sagt sætningen, er uafklaret — men den var i omløb,',
        'fordi den havde en kerne af sandhed, og denne stemme anfører den derfor og',
        'lader den ikke bruge mod sig. Alliancen var også et instrument til at binde',
        'Forbundsrepublikken ind, og Portugal var på dette tidspunkt et diktatur.',
        '',
        'I 1952 tiltrådte Grækenland og Tyrkiet, i 1955 Forbundsrepublikken. Ni dage',
        'efter dens tiltrædelse, den 14. maj 1955, blev **Warszawapagten** grundlagt',
        'i Warszawa — med DDR som medlem. Dermed stod den orden, der holdt indtil',
        '1989. Samme år viste den østrigske statstraktat dog, at det også kunne gå',
        'anderledes: De sovjetiske tropper trak sig ud af Østrig, og landet',
        'erklærede sig for evigt neutralt. Dette eksempel hører med i en fair',
        'fortælling.',
        '',
        'Dertil kom bomben. I 1949 fik Sovjetunionen sit første kernevåben, i 1952',
        'og 1953 fulgte brintbomberne på begge sider, i 1957 sendte Moskva med',
        'Sputnik den første satellit ud i rummet — og beviste dermed, at det rådede',
        'over raketter, der kunne nå ethvert punkt på jorden. Af regnestykket opstod',
        'en logik med en sigende forkortelse: MAD, „mutual assured destruction", den',
        'gensidigt sikrede ødelæggelse. Fred gennem visheden om, at et angreb også',
        'ville ødelægge angriberen. På højdepunktet midt i 1980\'erne lå der på',
        'verdensplan over 60.000 sprænghoveder på lager.',
        '',
        'Tre gange rejste mennesker i østen sig mod deres regeringer, og tre gange',
        'skete der intet fra vestlig side: den 17. juni 1953 i DDR, i oktober og',
        'november 1956 i Ungarn, i august 1968 i Tjekkoslovakiet. Vestlige',
        'radiostationer havde næret håb, som ingen var parat til at indfri.',
        'Regnestykket bagved var hver gang det samme, og det var nøgternt rigtigt:',
        'En indgriben ville have betydet krig mellem atommagter. Men det har en pris,',
        'og denne tekst undviger den ikke: Vesten påberåbte sig friheden og så til,',
        'mens mennesker, der netop havde stolet på den, løb ind i kampvogne.',
        '',
        'Det samme gælder murens opførelse. Mellem 1949 og 1961 havde omkring 2,7',
        'millioner mennesker forladt DDR, de fleste via Berlin. Den 13. august 1961',
        'blev byen delt. Vesten protesterede skarpt og gjorde intet; præsident John',
        'F. Kennedy sagde i kredsen af sine rådgivere i al væsentlighed, at en mur',
        'ikke var nogen smuk løsning, men meget bedre end en krig. Det var',
        'realistisk. Det betød også: Vestberlins frihed var garanteret, menneskene i',
        'østens ikke.',
        '',
        '## De tretten dage — Cuba-krisen 1962',
        '',
        'Den 14. oktober 1962 fotograferede et amerikansk rekognosceringsfly af',
        'typen U-2 affyringsramper til mellemdistanceraketter på Cuba. Derfra ville',
        'Washington og halvdelen af kontinentet have kunnet nås på få minutter.',
        'Præsident Kennedy indkaldte en snæver kreds af rådgivere, **ExComm**, og i',
        'tretten dage kæmpede man dér om en beslutning, som verden intet vidste om.',
        '',
        'De fleste i militæret pressede på for luftangreb og en invasion. Kennedy',
        'besluttede sig den 22. oktober for det mildeste virksomme middel: en',
        'søblokade, der af folkeretlige grunde blev kaldt „karantæne", fordi en',
        'blokade gælder som en krigshandling. Den 24. oktober drejede de sovjetiske',
        'skibe om foran linjen. Lørdag den 27. oktober — i Washington kaldt „Black',
        'Saturday" — blev en U-2 skudt ned over Cuba, og piloten Rudolf Anderson',
        'mistede livet.',
        '',
        'Hvor tæt på det i virkeligheden var, vidste dengang næsten ingen. Samme dag',
        'tvang amerikanske destroyere med øvelsesdybvandsbomber den sovjetiske ubåd',
        '**B-59** op til overfladen. Ubåden havde i dagevis ikke haft radiokontakt,',
        'luften var brugt op, temperaturen over 45 grader — og om bord befandt sig',
        'en torpedo med atomar sprænghovede. Chefen mente, at krigen var brudt ud,',
        'og ville sætte den ind. Til affyringen krævedes samtykke fra tre officerer.',
        'Én nægtede: Vasilij **Arkhipov**. At menneskeheden overlevede denne',
        'weekend, hang på standhaftigheden hos en fireogtrediveårig i et overophedet',
        'stålrør.',
        '',
        'Krisen blev afsluttet gennem en handel, hvis ene halvdel var offentlig, og',
        'hvis anden forblev hemmelig. Offentligt: Sovjetunionen trækker raketterne',
        'tilbage, USA afstår fra en invasion af Cuba. Hemmeligt: De amerikanske',
        '**Jupiter**-raketter i Tyrkiet — og i Italien — trækkes tilbage inden for',
        'få måneder. På grund af hemmeligholdelsen så Nikita Khrusjtjov i årtier ud',
        'som taberen og Kennedy som manden, der havde holdt stand. Denne stemme',
        'nævner det som et ubehageligt punkt i sin egen fortælling: En god del af',
        'den vestlige triumffølelse fra 1962 byggede på, at man fortiede, hvad man',
        'selv havde indrømmet.',
        '',
        'Og modpartens bevæggrunde? Fra Moskvas synspunkt var stationeringen på Cuba',
        'præcis det, amerikanske raketter i Tyrkiet ville have været fra Washingtons',
        'synspunkt, hvis fortegnene havde været omvendt: uudholdeligt tæt på. Den,',
        'der ikke tænker det med, gør krisen til en historie om en galning, der gav',
        'op — og lærer intet af den.',
        '',
        'Lært blev der så sandelig: I 1963 blev den „varme linje" mellem Washington',
        'og Moskva oprettet, samme år blev aftalen om forbud mod atomprøvesprængninger',
        'over jorden indgået, i 1968 ikke-spredningsaftalen.',
        '',
        '## Afspænding: Brandt, østaftalerne, Helsinki 1975',
        '',
        'Fra slutningen af 1960\'erne forsøgte begge sider at gøre tilstanden mere',
        'tålelig. I Forbundsrepublikken bar denne politik et navn: **Willy Brandt**,',
        'forbundskansler fra 1969, og hans rådgiver Egon Bahr, som formularen',
        '„forandring gennem tilnærmelse" (1963) stammer fra. **Østaftalerne** —',
        'Moskva og Warszawa 1970, grundaftalen med DDR 1972 — anerkendte de',
        'eksisterende grænser som ukrænkelige og muliggjorde til gengæld',
        'besøgsrejser, telefonlinjer og handel. Det var stærkt omstridt i',
        'Forbundsrepublikken; modstanderne så deri opgivelsen af genforeningen. Den',
        '7. december 1970 knælede Brandt foran mindesmærket for ofrene for',
        'Warszawaghettoen — en gestus, som der også blev strides om derhjemme.',
        '',
        'Det største skridt var Konferencen om Sikkerhed og Samarbejde i Europa. Den',
        '1. august 1975 underskrev 35 stater i **Helsinki** slutakten fra **KSSE**:',
        'alle NATO-lande, alle Warszawapagt-lande og de neutrale. Sovjetunionen fik,',
        'hvad den i tredive år havde villet — anerkendelsen af grænserne fra 1945.',
        'Vesten fik til gengæld „kurv III": menneskerettigheder, rejsefrihed,',
        'familiesammenføring, fri udveksling af informationer og meninger.',
        '',
        'Mange i Vesten holdt det for en dårlig byttehandel — faste grænser mod bløde',
        'ord. Det blev den mest skæbnesvangre handel i hele den kolde krig. Fordi',
        'slutakten skulle offentliggøres i alle underskriverstater, kunne',
        'borgerrettighedsaktivister fra Moskva til Prag pludselig påberåbe sig et',
        'dokument, som deres egen regering havde underskrevet. I 1976 opstod',
        'Moskva-Helsinki-gruppen, i 1977 Charta 77 i Tjekkoslovakiet, i 1980',
        'fagforeningen Solidarność i Polen. Det, der så ud som en indrømmelse,',
        'virkede som en løftestang — anbragt indefra, af de egne borgere.',
        '',
        'Afspændingen holdt ikke ved. I 1979 besluttede NATO oprustningen med',
        'mellemdistanceraketter (dobbeltbeslutningen), forbundet med tilbuddet om at',
        'forhandle; i december samme år marcherede Sovjetunionen ind i Afghanistan.',
        'Der fulgte de koldeste år siden 1962: Præsident Ronald Reagan talte i 1983',
        'om „ondskabens rige", i november 1983 holdt den sovjetiske ledelse en tid',
        'lang NATO-manøvren „Able Archer" for forberedelsen af et virkeligt angreb.',
        'Og den 26. september 1983 meldte et sovjetisk tidligt varslingssystem',
        'indflyvning af amerikanske raketter. Den vagthavende officer Stanislav',
        'Petrov videremeldte ikke alarmen, fordi tallet forekom ham for lille. Det',
        'var en fejltilmelding. For anden gang hang alt på ét enkelt menneske — og',
        'denne gang var det en fra den anden side.',
        '',
        '## De ubehagelige steder — hvad Vesten selv har ansvaret for',
        '',
        'Dette afsnit står her, fordi det ellers ville overlades til modstemmen.',
        'Vesten førte den kolde krig i frihedens og rettens navn og krænkede',
        'undervejs begge dele flere gange selv.',
        '',
        '**McCarthy-tiden.** Mellem 1947 og 1954 blev titusindvis af mennesker i USA',
        'undersøgt for deres politiske holdning. Komitéen for uamerikansk virksomhed',
        'indkaldte forfattere, instruktører og skuespillere; den, der nægtede at',
        'vidne, kom på sorte lister og fandt ikke længere arbejde — de „Hollywood',
        'Ten" kom i fængsel for det. Senator Joseph McCarthy hævdede fra 1950 at',
        'besidde lister over kommunister i udenrigsministeriet, som han aldrig',
        'forelagde. Mennesker mistede stillinger, venner og helbred på grund af',
        'mistanker, som der ikke var noget forsvar imod. Først i 1954, da McCarthy',
        'gik løs på den amerikanske hær, og høringerne blev transmitteret i',
        'fjernsynet, vendte stemningen. Et land, der gjorde krav på at forsvare',
        'ytringsfriheden mod diktaturet, har i årevis forfulgt meninger.',
        '',
        '**Vietnam.** Det er det eget sår. Af støtten til Frankrig i dets',
        'kolonikrig blev der fra 1964 — efter en hændelse i Tonkin-bugten, hvis',
        'anden, afgørende del efter nutidens forskningsstand ikke fandt sted på den',
        'måde — en egen krig. På højdepunktet stod over 540.000 amerikanske soldater',
        'i landet. Der blev kastet flere bomber end i hele Anden Verdenskrig,',
        'derudover napalm og af løvningsmidlet Agent Orange, hvis følger virker den',
        'dag i dag i fødselskader. Den 16. marts 1968 myrdede amerikanske soldater i',
        'My Lai flere hundrede civile, overvejende kvinder, børn og gamle. Omkring',
        '58.000 amerikanere døde og, alt efter skøn, to til tre millioner',
        'vietnamesere. Krigen blev tabt, og den ødelagde en hel generations tillid',
        'til den egne regering — ikke mindst fordi Pentagon-papirerne i 1971 viste,',
        'hvor længe og hvor bevidst offentligheden var blevet løjet for.',
        '',
        '**Støtten til diktaturer.** Af princippet om at inddæmme kommunismen',
        'overalt fulgte i praksis: Den, der var antikommunist, fik støtte, uanset',
        'hvordan han regerede. I 1953 væltede den amerikanske og den britiske',
        'efterretningstjeneste i **Iran** den folkevalgte regering under Mohammad',
        'Mossadegh, der havde nationaliseret olieindustrien, og støttede shahen — en',
        'forhistorie, uden hvilken den iranske revolution i 1979 ikke er til at',
        'forstå. I 1954 blev en folkevalgt regering i Guatemala væltet. I **Chile**',
        'arbejdede den amerikanske regering efter valget af Salvador Allende i 1970',
        'i årevis med skjulte midler og økonomisk pres på at få ham væltet; om den',
        'selv var involveret i militærkuppet den 11. september 1973, er omstridt,',
        'men rammerne har den været med til at skabe. Hvad der fulgte, var Augusto',
        'Pinochets diktatur med tusindvis af myrdede og forsvundne. I Grækenland',
        'gennemførte oberster i 1967 et kup og regerede i syv år — i en',
        'NATO-medlemsstat. Spanien under Franco og Portugal under Salazar gjaldt som',
        'partnere, Sydafrika med sin raceadskillelse som antikommunistisk allieret.',
        'Og stedfortriderkrigene i Korea, Angola, Nicaragua og Afghanistan kostede',
        'millioner af mennesker livet, som intet havde med striden mellem',
        'Washington og Moskva at gøre.',
        '',
        '**Våbenkapløbet.** Det kostede på begge sider summer, som man næsten ikke',
        'kan forestille sig — alene USA brugte gennem årtierne flere billioner',
        'dollar på sine kernevåben. Den klareste advarsel imod det kom indefra: I',
        'sin afskedstale den 17. januar 1961 talte præsident Dwight D. Eisenhower,',
        'selv general i Anden Verdenskrig, om det „militær-industrielle kompleks",',
        'for hvis uberettigede indflydelse borgerne burde vogte sig. Han vidste,',
        'hvad han talte om.',
        '',
        '## Hvorfor østblokken brød sammen',
        '',
        'Det er kapitlet egentlige spørgsmål, og det har ikke noget simpelt svar.',
        'Fem grunde greb ind i hinanden.',
        '',
        '**For det første: planøkonomi mod markedsøkonomi.** I en planøkonomi',
        'beslutter en myndighed, hvad der produceres i hvilke mængder. Det fungerer',
        'overraskende godt, når et land har brug for få, klart afgrænsede ting —',
        'stål, cement, kampvogne —, og i 1950\'erne voksede den sovjetiske økonomi',
        'hurtigt. Det fungerer dårligt, så snart et samfund bliver mere kompliceret:',
        'Ingen kan for 280 millioner mennesker regne ud, hvor mange sko i hvilken',
        'størrelse der er brug for. Der manglede den tilbagemelding, som prisen',
        'giver i en markedsøkonomi. Resultatet var samtidig tomme hylder og fulde',
        'lagre med usælgelige varer, ventelister på ti år på en bil — og, fordi',
        'virksomhederne blev belønnet for opfyldte planmål og ikke for gode',
        'produkter, ringe grund til at forbedre noget som helst.',
        '',
        '**For det andet: det teknologiske efterslæb.** I 1970\'erne og 1980\'erne',
        'begyndte mikroelektronikken i Vesten. Østen kunne ikke følge med — også',
        'fordi en maskine, som enhver kan kopiere og udbrede med, er et problem i en',
        'stat med censur. Kopimaskiner stod i DDR under lås og slå. Et system, der',
        'er nødt til at kontrollere informationer, kan ikke vinde',
        'informationsteknologien.',
        '',
        '**For det tredje: våbenbyrden.** Sovjetunionen holdt militært trit med USA,',
        'selvom dens økonomi kun var en brøkdel så stor. Skøn går på 15 til 25',
        'procent af den økonomiske ydeevne til militæret, mod omkring 6 procent i',
        'USA. Enhver raket manglede et andet sted. Krigen i Afghanistan fra 1979 kom',
        'til som en permanent belastning og kostede omkring 15.000 sovjetiske',
        'soldater livet.',
        '',
        '**For det fjerde: olieprisfaldet i 1986.** Råolie og naturgas var',
        'Sovjetunionens vigtigste kilde til udenlandsk valuta — dermed blev korn og',
        'vestlig teknologi betalt. I 1985/86 faldt **olieprisen** fra omkring',
        'tredive til under ti dollar pr. tønde. Fra det ene år til det andet',
        'bortfaldt en stor del af de indtægter, som systemet havde stoppet sine',
        'huller med.',
        '',
        '**For det femte: Gorbatjovs reformer.** Mikhail **Gorbatjov**,',
        'generalsekretær fra marts 1985, så situationen klart og ville redde',
        'socialismen, ikke afskaffe den. **Perestrojka** (ombygning) skulle gøre',
        'økonomien mere bevægelig, **glasnost** (åbenhed) bryde forsteningen op',
        'gennem offentlig kritik — reaktorkatastrofen i Tjernobyl i april 1986, der',
        'i dagevis blev hemmeligholdt, gjorde ham fordelene ved åbenhed dramatisk',
        'klart. Begge dele tilsammen havde en sprængkraft, som han ikke havde',
        'tiltænkt dem: De halve økonomiske reformer ødelagde de gamle rutiner uden',
        'at skabe fungerende nye, og ytringsfriheden gjorde en stille utilfredshed',
        'til en offentlig bevægelse. Afgørende var hans opgivelse af',
        'Bresjnev-doktrinen: I 1989 gjorde Moskva klart, at det ikke længere ville',
        'afslutte reformerne i Østeuropa med kampvogne. En sovjetisk talsmand kaldte',
        'det spottende „Sinatra-doktrinen" — alle må gøre det på deres egen måde.',
        'Det var øjeblikket, hvor 1953, 1956 og 1968 ikke længere kunne gentage sig.',
        '',
        'Hvad der udtrykkeligt mangler i denne opremsning, er Vestens',
        'yndlingsforklaring: at Vesten skulle have oprustet østen ihjel.',
        'Våbenpresset var en reel byrde, men de afgørende årsager lå i systemet selv',
        'og i de beslutninger, der blev truffet i Moskva. Vesten har ikke fremkaldt',
        'dette sammenbrud. Det har oplevet det — og var lige så overrasket som alle',
        'andre.',
        '',
        '## 1989 til 1991 — vendepunktet set fra Vesten',
        '',
        'Fra 1985 forhandlede Reagan og Gorbatjov: Geneve 1985, Reykjavik 1986, hvor',
        'man nær var blevet enige om den fuldstændige afskaffelse af alle atomvåben,',
        'og i 1987 INF-aftalen — den første aftale i historien, der ikke begrænsede',
        'en hel våbenkategori, men afskaffede den. I juni 1987 stod Reagan ved',
        'Brandenburger Tor og opfordrede Gorbatjov til at rive denne mur ned.',
        '',
        'Så gik alt meget hurtigt. I Polen blev regeringen og Solidarność i foråret',
        '1989 ved det runde bord enige om delvist frie valg; i juni vandt',
        'oppositionen alle de pladser, den måtte stille op til. Ungarn begyndte i',
        'maj at fjerne sperreanlæggene ved grænsen til Østrig og åbnede den 11.',
        'september grænsen helt. I Leipzig gik der fra september om mandagen flere',
        'og flere mennesker på gaden; den 9. oktober var der omkring 70.000, og der',
        'faldt ikke et skud. Om aftenen den **9. november 1989** åbnede muren sig,',
        'efter at et medlem af DDR-ledelsen havde bekendtgjort en ny rejseregulering',
        'misforståeligt på en pressekonference. I Prag bragte fløjlsrevolutionen',
        'inden for uger et magtskifte uden vold; i Rumænien endte det blodigt, med',
        'henrettelsen af Nicolae Ceaușescu den 25. december 1989.',
        '',
        'I Vesten blev Gorbatjov en respekteret skikkelse — i Tyskland mere end',
        'noget andet sted. Man vidste, hvem man skyldte, at 1989 faldt anderledes ud',
        'end 1953. At han i sit eget land fandt langt mindre tilslutning til det,',
        'hører til den anden halvdel af dette kapitel.',
        '',
        '## To-plus-fire-aftalen, 12. september 1990',
        '',
        'Den tyske enhed var ikke et indre tysk anliggende. Over Tyskland havde fire',
        'magter siden 1945 rettigheder, og uden deres samtykke var en forening',
        'folkeretligt ikke mulig. Derfor forhandlede to tyske stater i 1990 med fire',
        'sejrsmagter — deraf navnet. Den **12. september 1990** underskrev',
        'udenrigsministrene i Moskva „Traktaten om den endelige ordning med hensyn',
        'til Tyskland". Den er hjørnestenen i dette kapitel, og det, der står i den,',
        'er værd at læse nøje:',
        '',
        '- **Artikel 1: grænserne.** Det forenede Tyskland omfatter',
        '  Forbundsrepublikken, DDR og hele Berlin — og intet andet. **Oder-Neisse**-',
        '  grænsen til Polen anerkendes endeligt, alle territoriale krav er',
        '  udelukket. En særskilt tysk-polsk grænsetraktat bekræftede det den 14.',
        '  november 1990.',
        '- **Artikel 2: afkaldet på angrebskrig.** Fra tysk jord vil der kun udgå',
        '  fred; forberedelsen af en angrebskrig er forfatningsstridig og strafbar.',
        '- **Artikel 3: våben og troppestyrke.** Tyskland afstår fra atomare,',
        '  biologiske og kemiske våben og begrænser sine væbnede styrker til 370.000',
        '  soldater.',
        '- **Artikel 4: troppetilbagetrækningen.** De sovjetiske tropper trækker sig',
        '  inden udgangen af 1994 tilbage fra det tidligere DDR\'s område.',
        '- **Artikel 5: det tidligere DDR\'s område.** Der stationeres ingen',
        '  udenlandske tropper og opstilles ingen kernevåben der.',
        '- **Artikel 6: alliancefriheden.** Det forenede Tysklands ret til at tilhøre',
        '  alliancer berøres ikke af denne traktat.',
        '- **Artikel 7: suveræniteten.** Firemagternes rettigheder og ansvar med',
        '  hensyn til Berlin og Tyskland som helhed ophører. Det forenede Tyskland',
        '  får fuld suverænitet over sine indre og ydre anliggender.',
        '',
        'Den 3. oktober 1990 tiltrådte DDR grundlovens gyldighedsområde. 45 år efter',
        'krigens afslutning var Tyskland igen én stat — og for første gang siden',
        '1871 en, hvis grænser ingen af dets naboer anfægtede.',
        '',
        '**Blev aftalen overholdt?** Dette spørgsmål stilles i dag, og det fortjener',
        'et fair svar. Formelt lyder svaret: ja. De sovjetiske tropper trak sig',
        'tilbage inden den 31. august 1994, endda lidt tidligere end aftalt.',
        'Tyskland holdt afkaldet på ABC-våben, bekræftede Oder-Neisse-grænsen og',
        'stationerede ingen udenlandske tropper i øst. Og det forenede Tysklands',
        'NATO-medlemskab var intet traktatbrud: Artikel 6 tillader udtrykkeligt',
        'alliance-tilhørsforhold — det var i 1990 kernen i forhandlingerne, og den',
        'sovjetiske side gav sit samtykke til det.',
        '',
        'Det, der efterfølgende blev omstridt, er noget andet: ikke ordlyden, men',
        '„ånden" i aftalerne fra 1990 — og spørgsmålet om, hvad vestlige politikere',
        'dengang mundtligt har sagt til Gorbatjov om en mulig udvidelse af NATO mod',
        'øst. Denne strid hører til i det næste kapitel, „Rusland og Vesten", og',
        'bliver der behandlet udførligt med begge synsvinkler. Her står kun',
        'befunden: To-plus-fire-aftalen selv forbød ikke NATO-medlemskab, og',
        'østudvidelsen kom senere og var ikke dens genstand.',
        '',
        'Den **25. december 1991** trådte Mikhail Gorbatjov tilbage; om aftenen blev',
        'det røde flag halet ned over Kreml. En dag senere opløste Øverste Sovjet',
        'sig selv. Sovjetunionen var ophørt med at eksistere — uden krig, uden',
        'kapitulation, uden at nogen havde besejret den.',
        '',
        '## „Hvem vandt den kolde krig?"',
        '',
        'Dette spørgsmål blev i 1990 stillet overalt i Vesten, og svaret forekom',
        'selvindlysende: vi. Statskundskabsmanden Francis Fukuyama skrev om',
        '„historiens ende" — det liberale demokrati og markedsøkonomien havde',
        'hævdet sig som den bedste af alle ordener, den store strid var afgjort.',
        '',
        'Denne stemme giver et mere ubehageligt svar på det, og den giver det selv,',
        'før nogen anden kræver det af den.',
        '',
        'For det første: Det var mindre en sejr end et sammenbrud. Sovjetunionen blev',
        'ikke besejret, den gik til grunde på sine egne modsætninger — og på, at',
        'dens sidste leder nægtede at holde den sammen med vold. Den, der gør en',
        'sejr ud af andres fiasko, drager de forkerte lærdomme af det.',
        '',
        'For det andet: Euforien fra 1989 blev ikke overalt i østen oplevet som en',
        'befrielse. For millioner af mennesker betød slutningen også slutningen på',
        'deres virksomhed, deres pension, anerkendelsen af deres erhvervsliv. I',
        'Østtyskland forsvandt inden for få år over to tredjedele af',
        'industriarbejdspladserne; i Rusland faldt den økonomiske ydeevne i',
        '1990\'erne med næsten halvdelen, og mændenes forventede levealder med år.',
        'At mennesker, der havde stået på gaden i 1989, ti år senere var bitre, er',
        'ingen modsigelse — det er to sandheder om samme begivenhed.',
        '',
        'For det tredje: Meget af det, der i dag er selvfølgeligt, skylder denne',
        'afslutning — bevægelsesfriheden i Europa, nedrustningsaftalerne, det',
        'faktum, at der frit vælges i Warszawa og Prag. Også det hører med i samme',
        'balance, uden at det ene ophæver det andet.',
        '',
        '## Og de andre stemmer',
        '',
        'Det, der står her, er en fortælling fra den ene side af linjen. Den kender',
        'luftbroen fra cockpittene, ikke fra kældrene i den sovjetiske kommandantur.',
        'Den kender muren udefra. Den ved ikke, hvordan fyrre år med Warszawapagten',
        'føltes for et land, der var blevet overfaldet i 1941 og så en trussel i',
        'NATO, og den ved ikke, hvordan hverdagen var i en stat, der ikke findes',
        'mere — med børnehaveplads og feriekoloni på den ene side, Stasi og',
        'udrejseansøgning på den anden.',
        '',
        'Derfor står denne perspektiv ikke alene. **Østens syn** — Sovjetunionens,',
        'Warszawapagtens og DDR\'s — supplerer Hermes efter denne runde, og derefter',
        'måske tyskernes syn i øst og vest, for hvem delingen ikke var et kapitel,',
        'men deres liv. Først derefter kan en syntese føre sammen, hvad der her',
        'nødvendigvis forbliver ensidigt. Indtil da gælder, hvad der gælder for hele',
        'dette kapitel: Denne stemme siger ikke „sådan var det". Den siger: Sådan',
        'fortælles det herfra.',
      ].join('\n'),
    },
    {
      id: 'osten-sicht',
      name: 'Østens syn — Sovjetunionen, Warszawapagten, DDR',
      stimme: 'Hermes',
      text: [
        'Denne stemme fortæller fra Moskva, fra Warszawa, fra Østberlin: fra den',
        'verden, der ophørte med at eksistere i 1991. Den er ligeværdig med Vestens',
        'stemme — at den her stod først, var kun rækkefølgen, i hvilken der blev',
        'skrevet.',
        '',
        'Denne stemme begynder ikke i 1945, men med en erindring: Sovjetunionen',
        'havde i denne krig **omkring 27 millioner døde** at sørge over — flere end',
        'noget andet land. Inden for tredive år var dens territorium blevet',
        'overfaldet to gange fra vest, 1914 og 1941. Af denne erfaring taler enhver',
        'østlig beslutning i den kolde krig. Det, Vesten læste som sovjetisk',
        'aggression, var fra Moskvas synspunkt først og fremmest angst: angsten for',
        'en tredje invasion. En bufferzone af venligsindede stater —',
        '„folkedemokratierne" — var for denne stemme ingen erobring, men en',
        'forsikring.',
        '',
        '## Ophygningen i østen',
        '',
        'Også det østlige Tyskland lå i 1945 i ruiner. Og også her blev der bygget',
        'op — blandt andet med krigsskadeserstatninger, som Sovjetunionen',
        'betragtede som sin ret: efter hvad de tyske hære havde forvoldt i',
        'Sovjetunionen. DDR kaldte sin vej **„socialismens opbygning"**: store',
        'virksomheder, jordreform, gratis uddannelse, børnehaver,',
        'masseorganisationerne. Den, der voksede op i denne verden, lærte: Vi',
        'bygger det bedre — et samfund uden arbejdsløshed, uden fattigdom, uden',
        'Vestens klassemodsætninger. At Vesten hævdede det samme, udgjorde',
        'konkurrencen, der førte den kolde krig også i hverdagen.',
        '',
        '## Berlin 1948 og luftbroen — den anden fortælling',
        '',
        'Vesten fortæller blokaden af Berlin som redningen af en omringet by',
        'gennem luftbroen. Denne stemme fortæller den anderledes, og begge',
        'fortællinger kan dokumenteres: Fra østligt synspunkt stod **valutareformen',
        'fra juni 1948** i begyndelsen, hvormed vestmagterne ensidigt afsluttede den',
        'fælles firemagts-administration af Tyskland — et skridt, der skulle',
        'besegle landets deling, allerede før berlinerblokaden begyndte. Blokaden',
        'var fra Moskvas synspunkt svaret på denne solotur: Den, der opsiger den',
        'fælles orden, må regne med følgerne. Vesten vandt denne runde — luftbroen',
        'var en teknisk og menneskelig mesterpræstation. Men at Berlin overlevede,',
        'fordi Vesten forsynede det, bekræftede fra østligt synspunkt blot, hvad',
        'delingen allerede var: en konkurrence, som østen ikke kunne vinde.',
        '',
        '## Muren — den „antifascistiske beskyttelsesmur"',
        '',
        'DDR mistede siden sin grundlæggelse sin befolkning: **indtil 1961 gik',
        'omkring 2,7 millioner mennesker til Vesten** — de fleste unge, mange',
        'uddannede. Læger, ingeniører, lærere forlod landet, der havde uddannet',
        'dem. Fra DDR-ledelsens synspunkt var muren af 13. august 1961 derfor intet',
        'fængsel, men **nødværge**: den „antifascistiske beskyttelsesmur" mod',
        'Vestens hvervning, der med sin velstand blødte østen ud. Denne stemme siger',
        'det ikke som en retfærdiggørelse — muren har revet familier i stykker og',
        'kostet mennesker livet. Men den siger det, fordi muren uden DDR\'s nød ikke',
        'er forklarlig. En stat, der spærrer sine borgere inde, er ingen god stat —',
        'og en stat, der må gøre det, fordi dens borgere går, er en stat i nød.',
        '',
        '## Hverdagen i østen',
        '',
        'Hvad denne stemme holder op imod den vestlige fortælling, er hverdagen:',
        'fuld beskæftigelse, en ret til arbejde, som ingen satte spørgsmålstegn ved,',
        'børnehaver, uddannelse uden skolepenge, billige boliger, et socialt net,',
        'der ikke lod nogen falde. Den, der levede i østen, kendte også',
        'skyggesiderne — **mangeløkonomien** med sine køer, Stasi, rejsefriheden,',
        'som ikke eksisterede, SED, som ikke tillod andre meninger. Denne stemme',
        'bladrer begge sider op, fordi kun sådan bliver det forståeligt, hvorfor',
        'østen holdt så længe: Den bød på tryghed, hvor Vesten bød på frihed. Og det',
        'bliver forståeligt, hvorfor den til sidst alligevel brød sammen:',
        'Menneskerne ville begge dele.',
        '',
        '## De vanskelige år og afspændingen',
        '',
        'Denne stemme fortier ikke, hvad der skete i østen, når ordenen vaklede: den',
        '**17. juni 1953**, da sovjetiske kampvogne slog opstanden i DDR ned;',
        '**Ungarn 1956**; **Prag-foråret 1968**, da Warszawapagtens tropper',
        'afsluttede reformerne i Tjekkoslovakiet — **Bresjnev-doktrinen**, hvorefter',
        'socialismen ikke måtte gå tabt i noget land. For Vesten var det beviser på',
        'systemets karakter. For denne stemme var det forsvaret af den egen lejr —',
        'og den ved, hvor kynisk det lyder i dag.',
        '',
        'Og så kom afspændingen, og den kom også østen til gode: **østaftalerne**',
        'fra begyndelsen af halvfjerdserne, grundaftalen med Forbundsrepublikken, og',
        'i 1975 **KSSE-slutakten fra Helsinki**. Fra østligt synspunkt var Helsinki',
        'den store gevinst: Vesten anerkendte efterkrigsgrænserne — også',
        'Oder-Neisse-grænsen og DDR\'s eksistens. At der i samme slutakt også stod',
        'menneskerettighederne, forekom dengang som en indrømmelse til Vesten. At',
        'netop disse linjer tyve år senere skulle udhule østen indefra, så ingen —',
        'heller ikke denne stemme.',
        '',
        '## Hvad denne stemme ikke kan',
        '',
        'Denne stemme kan ikke forklare, hvorfor DDR-borgerne i 1989 gik i flok,',
        'mens deres regering stadig talte om stabilitet. Den kan ikke forklare,',
        'hvorfor det system, der blev kaldt „reelt eksisterende socialisme", til',
        'sidst havde så lidt opbakning, at en mandagsdemonstration fik det til at',
        'styrte sammen. Det er denne stemmes mest ubehagelige sted: Østen tabte',
        'konkurrencen ikke kun økonomisk, men også i de egne folks tillid. Den',
        'frihed, som Vesten bød på, var intet udstillingsvindue — den var det,',
        'menneskerne virkelig ville.',
      ].join('\n'),
    },
    {
      id: 'deutsche-sicht',
      name: 'Tyskernes syn i øst og vest',
      stimme: 'Hermes',
      text: [
        'Denne stemme taler ikke for en regering, men for de mennesker, for hvem',
        'delingen var hverdag: for familien, der stod ved grænsen om weekenden, for',
        'bedstemoderen i Leipzig og onklen i Hamborg, for børnene, der voksede op i',
        'en delt by. Den er kapitlet tredje stemme, og den er den stille — fordi',
        'den ikke fortæller om verdenspolitik, men om livet deri.',
        '',
        '## To liv i ét land',
        '',
        'Efter 1945 fandtes der ikke „tyskerne" — der fandtes menneskene i vest og',
        'menneskene i øst, og begge fortalte snart egne historier. I vest voksede en',
        'generation op med **Wirtschaftswunder** — det økonomiske mirakel: med',
        'VW-boblen, med ferien i udlandet, med den faste overbevisning, at demokrati',
        'og marked er det rigtige. Delingen var for dem et nyhedsemne — muren var',
        'langt væk, selvom den løb midt gennem Berlin.',
        '',
        'I øst voksede en generation op med opbygningen: med ungdomsvielsen, med',
        'virksomhedsfesten, med stoltheden over den egen virksomhed — og med',
        'hverdagens små kompromiser. Den, der ikke faldt i øjnene, levede bedst;',
        'den, der sagde, hvad han tænkte, fik besvær. Mellem disse to liv lå en',
        'grænse, der for nogle var et ferieemne og for andre en livs-mur.',
        '',
        '## Muren i hverdagen',
        '',
        'Muren var for tyskerne i øst ingen metafor, men en betonvæg i det egne',
        'bybillede: dødsstriben, vagttårnene, ordren om at skyde. Familier blev',
        'revet fra hinanden — **mere end tre millioner besøg om året før 1961,',
        'derefter næsten ingen**. Breve, pakker, telefonopkald under overvågning,',
        'begravelser, som de pårørende fra vest ikke kunne rejse til. Denne stemme',
        'vil ikke udspille den ene side mod den anden: Der var i vest mennesker, der',
        'oplevede delingen som en uret og demonstrerede imod den — og der var i øst',
        'mennesker, der afviste systemet og alligevel blev, fordi de ikke ville',
        'opgive deres land. Men asymmetrien bliver: Kun den ene side havde brug for',
        'en mur.',
        '',
        '## 1989 — folket og muren',
        '',
        'Så kom efteråret 1989. I Leipzig begyndte **mandagsdemonstrationerne** —',
        'først med stearinlys, så med titusinder: „Vi er folket." Parolen var først',
        'et krav til den egne regering, intet råb mod vest. Da grænserne faldt den',
        '**9. november 1989**, stod der mennesker på muren, der aldrig før havde',
        'mødt hinanden — øst og vest, grædende og leende på samme tid. Den, der',
        'oplevede denne nat, fortæller den den dag i dag som et livs lykke.',
        '',
        '## Genforeningen — og dens to sider',
        '',
        'Den **3. oktober 1990** gjorde to tyske stater til én igen. Glæden var',
        'ægte — og den var ikke hele historien. Denne stemme nævner også den anden',
        'side: **Treuhand** solgte eller lukkede de østtyske virksomheder,',
        'millioner mistede deres arbejde, ingeniørers og lærerinders biografier',
        'gjaldt pludselig ikke længere noget. Nogle i øst oplevede genforeningen som',
        'en overtagelse i stedet for en befrielse — og nogle i vest som en',
        'belastning i stedet for en glæde. Af disse to erfaringer voksede',
        '„**muren i hovedet**", der holdt længere end den af beton: fordommene',
        'mellem „Wessis" og „Ossis", som klinger efter den dag i dag.',
        '',
        '## Hvad denne stemme ved',
        '',
        'Denne stemme ved, at historie ikke kun består af traktater og magter, men',
        'af det, mennesker gør med dem. To-plus-fire-aftalen af 12. september 1990',
        'beseglede genforeningen — men selve genforeningen havde menneskene båret ud',
        'på gaden. Ingen regeringschef, ingen hær rev muren ned: Det var menneskene,',
        'der ikke længere lod sig standse. Denne stemme ender med en erindring om',
        'dem, der ikke nåede det — om de **omkring 140 døde ved den indre-tyske',
        'grænse**, hvis historier er den anden side af denne frihed.',
      ].join('\n'),
    },
  ],

  synthese: [
    'Tre stemmer, ét land, én verden. Denne syntese fører sammen, hvad Vesten,',
    'østen og tyskerne i øst og vest har fortalt — og den begynder med',
    '**brudstederne**, hvor de samme begivenheder begyndte ganske forskelligt.',
    '',
    'Ved **begyndelserne**: Den vestlige fortælling begynder med en Sovjetunion,',
    'der indsatte regeringer i Østeuropa — og udleder deraf inddæmningen. Den',
    'østlige fortælling begynder med et land, der havde 27 millioner døde at sørge',
    'over og var blevet overfaldet to gange fra vest — og udleder deraf',
    'sikkerhedszonen. Begge begyndelser kan dokumenteres. Alt efter hvilken man',
    'vælger, er den anden side angriber eller forsvarer. Det er den første',
    'lektion: Historie begynder ikke der, hvor kilderne begynder, men der, hvor',
    'fortællerne sætter begyndelsen.',
    '',
    'Ved **Berlin 1948**: For Vesten er luftbroen redningen af en omringet by. For',
    'østen er valutareformen forud den egentlige brud — skridtet, hvormed',
    'vestmagterne afsluttede den fælles administration. De samme elleve måneder,',
    'to begyndelser, to sandheder. Luftbroen forbliver en mesterpræstation — og',
    'valutareformen forbliver en solotur. Begge dele står.',
    '',
    'Ved **muren**: Vesten ser en regering, der måtte spærre sine borgere inde.',
    'Østen ser en stat i nød, der blødte ud, mens der ved siden af blev bygget et',
    'udstillingsvindue. Og den tredje stemme ser de familier, der blev revet i',
    'stykker. Den, der lader alle tre sætninger stå ved siden af hinanden, har',
    'endnu intet svar — men det rigtige spørgsmål: Hvorfor må en stat spærre sine',
    'borgere inde, for at de bliver?',
    '',
    'Ved **økonomien**: Vesten førte systemernes konkurrence an, som østen tabte.',
    'Planøkonomien sikrede overlevelsen, men ikke velstanden; den lovede lighed og',
    'frembragte mangel. Vestens frihed var intet udstillingsvindue — den var det,',
    'menneskene virkelig ville, og netop det udhulede østen: først indefra,',
    'gennem længslen, så udefra, gennem åbningen.',
    '',
    'Og så **To-plus-fire-aftalen**: Den 12. september 1990 fik det forenede',
    'Tyskland sin fulde suverænitet tilbage; firemagts-rettighederne ophørte.',
    'Aftalen selv tillod udtrykkeligt landet at tilhøre alliancer — spørgsmålet,',
    'om NATOs østudvidelse krænkede aftalens ånd, hører til i det næste kapitel.',
    'Her står befunden: Muren faldt, fordi menneskene ikke længere accepterede den',
    '— ikke fordi en traktat bestemte det.',
    '',
    'Det sidste brudsted er **friheden**. Vesten og østen skændtes i årtier om,',
    'hvilket system der var bedst. Tyskerne i øst og vest har givet svaret — ikke',
    'med våben, men med deres fødder og med stearinlys. Det, der endte i 1991, var',
    'ikke kun en stat, men et løfte, som menneskene ikke længere ville købe. At',
    'minde om det, er dette kapitels opgave — og den lære, der rækker ind i',
    'nutiden.',
  ].join('\n'),

  urteil: {
    frage: 'I fyrre år stod to blokke med titusindvis af atomvåben over for hinanden, uden at der brød en krig ud mellem dem — og begge sider siger den dag i dag, at deres afskrækkelse var grunden. Har freden holdt på trods af disse våben eller på grund af dem, og hvad betyder dit svar for spørgsmålet om, hvordan man skaber sikkerhed i dag?',
    hinweis: 'Der er her ikke noget rigtigt og forkert. To tanker til videre tænkning: Nogle siger, at afskrækkelsen virkede — ingen politiker kunne ønske at vinde en krig, hvor det egne land også ville gå under, og netop det sikrede fyrre års fred mellem stormagterne. Andre siger, at det er et regnestykke, der kun går op, så længe alle involverede er fornuftige, velinformerede og ved deres fulde fem — og at Cuba-krisen, den sovjetiske ubåd B-59 og fejltilmeldingen fra 1983 viser, hvor ofte det netop ikke var tilfældet. Måske hjælper spørgsmålet: Ville du indgå et væddemål, der går godt i 99 procent af tilfældene, hvis den ene resterende procent koster alt?',
  },

  quiz: [
    {
      frage: 'Hvad var Berlin-luftbroen i 1948/49?',
      antworten: [
        'Forsyningen af Vestberlin fra luften, efter at alle land- og vandveje var blevet spærret.',
        'En bro over Spree, der forbandt byens fire sektorer.',
        'Borttransporten af industrianlæg fra Berlin som krigsskadeserstatning.',
      ],
      richtig: 0,
      erklaerung: 'Efter spærringen af adgangsvejene den 24. juni 1948 bragte omkring 280.000 flyvninger i løbet af elleve måneder omkring 2,3 millioner tons varer til byen — på højdepunktet landede der et fly hvert tredje minut. Det var muligt, fordi de tre luftkorridorer var blevet aftalt skriftligt i 1945. Den 12. maj 1949 blev blokaden ophævet.',
    },
    {
      frage: 'Hvornår blev NATO og Warszawapagten grundlagt?',
      antworten: [
        'NATO i 1949, Warszawapagten i 1955 — kort efter at Forbundsrepublikken var trådt ind i NATO.',
        'Begge i samme år 1949, umiddelbart efter grundlæggelsen af de to tyske stater.',
        'Warszawapagten i 1945 i Potsdam, NATO som svar på den i 1961.',
      ],
      richtig: 0,
      erklaerung: 'Nordatlantiktraktaten blev underskrevet af tolv stater den 4. april 1949. Forbundsrepublikken trådte ind den 5. maj 1955 — ni dage senere, den 14. maj 1955, opstod Warszawapagten. Samme år trak de sovjetiske tropper sig ud af Østrig, som siden har været neutralt.',
    },
    {
      frage: 'Hvordan endte Cuba-krisen i oktober 1962?',
      antworten: [
        'Gennem en handel: Sovjetunionen trak raketterne tilbage, USA afstod offentligt fra en invasion af Cuba og trak hemmeligt sine Jupiter-raketter ud af Tyrkiet.',
        'Gennem amerikanske luftangreb, der ødelagde affyringsramperne på Cuba.',
        'Gennem en beslutning i De Forenede Nationer, der erklærede Cuba for en neutral zone.',
      ],
      richtig: 0,
      erklaerung: 'Kennedy besluttede sig mod rådet fra mange i militæret for en søblokade i stedet for et angreb. Tilbagetrækningen af Jupiter-raketterne forblev hemmelig i årtier — derfor så det længe ud, som om kun den ene side havde givet efter. Hvor tæt på det var, viste den sovjetiske ubåd B-59, hvor en officer forhindrede brugen af en atomtorpedo.',
    },
    {
      frage: 'Hvad var det særlige ved KSSE-slutakten fra Helsinki i 1975?',
      antworten: [
        'Underskriverne anerkendte de eksisterende grænser og forpligtede sig samtidig på menneskerettighederne — som borgerrettighedsaktivister i østen senere kunne påberåbe sig.',
        'Den afsluttede Warszawapagten og påbød tilbagetrækning af alle sovjetiske tropper fra Østeuropa.',
        'Den forbød begge sider at besidde atomvåben i Europa.',
      ],
      richtig: 0,
      erklaerung: '35 stater underskrev den 1. august 1975. Fordi slutakten skulle offentliggøres i alle lande, kunne borgerrettighedsgrupper påberåbe sig et dokument, som deres egen regering havde underskrevet: Moskva-Helsinki-gruppen i 1976, Charta 77 et år senere.',
    },
    {
      frage: 'Hvad regulerede To-plus-fire-aftalen af 12. september 1990?',
      antworten: [
        'Den beseglede den tyske enhed folkeretligt: fuld suverænitet, ophør af firemagts-rettighederne, endelig anerkendelse af Oder-Neisse-grænsen, afkald på ABC-våben og tilbagetrækning af de sovjetiske tropper inden udgangen af 1994.',
        'Den delte Tyskland op i fire besættelseszoner og regulerede krigsskadeserstatningerne.',
        'Den forpligtede det forenede Tyskland til neutralitet og forbød det medlemskab af alliancer.',
      ],
      richtig: 0,
      erklaerung: 'Forhandlet har to tyske stater og de fire sejrsmagter — deraf navnet. Artikel 6 fastslår udtrykkeligt, at det forenede Tysklands ret til at tilhøre alliancer forbliver uberørt; artikel 7 afslutter firemagternes rettigheder. Den 3. oktober 1990 var Tyskland igen én stat, den 31. august 1994 forlod de sidste sovjetiske soldater landet.',
    },
  ],

  karteHinweise: [
    {
      label: '1949',
      hinweis: [
        'Fire år efter krigens afslutning står to tyske stater på kortet:',
        'Forbundsrepublikken (grundloven af 23. maj, første forbundsregering i',
        'september) og DDR (7. oktober). Berlin ligger midt i DDR\'s område og er',
        'delt i fire sektorer; blokaden af vestsektorerne sluttede den 12. maj 1949,',
        'elleve måneder efter sin begyndelse. Den 4. april 1949 var NATO blevet',
        'grundlagt — USA, Canada og Island hører med, men ligger uden for dette',
        'udsnit. En Warszawapagt findes endnu ikke, den kommer først i 1955;',
        'staterne øst for linjen står imidlertid allerede under sovjetisk',
        'indflydelse. Grækenland og Tyrkiet er endnu ikke NATO-medlemmer, men',
        'modtager siden 1947 hjælp efter Truman-doktrinen. Østrig er endnu besat af',
        'fire magter. Saarland stod indtil 1957 under fransk administration — på',
        'dette kort er det lagt til Forbundsrepublikken, i 1949 hørte det ikke med.',
      ].join(' '),
    },
    {
      label: '1961/62',
      hinweis: [
        'Nu står to alliancer over for hinanden: NATO, som Forbundsrepublikken',
        'trådte ind i 1955, og Warszawapagten, der opstod som svar derpå samme år —',
        'med DDR som medlem. Grækenland og Tyrkiet er siden 1952 i NATO; i Tyrkiet',
        'står amerikanske Jupiter-raketter, og netop de bliver i oktober 1962 en del',
        'af den hemmelige handel, der afslutter Cuba-krisen. Cuba selv ligger syv',
        'tusinde kilometer vest for dette kort. I Berlin har der siden den 13.',
        'august 1961 været bygget en mur; grænsen tværs gennem Tyskland er 1.393',
        'kilometer lang. Østrig er siden 1955 neutralt, de sovjetiske tropper er',
        'trukket ud — det fandtes altså også. Jugoslavien hører til ingen blok og',
        'grundlægger i 1961 sammen med Indien og Egypten De alliancefrie landes',
        'bevægelse.',
      ].join(' '),
    },
    {
      label: '1989–1991',
      hinweis: [
        'På to år forsvinder fyrre års orden. Den 9. november 1989 åbner muren sig,',
        'den 3. oktober 1990 er de to tyske stater igen én — folkeretligt reguleret',
        'i To-plus-fire-aftalen af 12. september 1990. Den 1. juli 1991 opløser',
        'Warszawapagten sig, den 25. december 1991 træder Mikhail Gorbatjov tilbage,',
        'og Sovjetunionen ophører med at eksistere; Estland, Letland og Litauen er',
        'allerede samme år igen uafhængige. Den mørke linje tværs gennem Europa står',
        'på denne fase stadig, selvom den ikke findes mere — den viser, hvad der er',
        'forsvundet. Hvad der kom efter, er ikke længere en del af dette kapitel: I',
        'Jugoslavien begynder opløsningen i 1991, og spørgsmålet om, hvordan',
        'forholdet mellem Rusland og Vesten udvikler sig, stiller det næste',
        'kapitel.',
      ].join(' '),
    },
  ],
};