// Emne: De tidlige kongeriger — sådan blev erobrere til herskere.
//
// Dansk oversættelse af utils/themen/koenigreiche.js (tysk original).
// Indtil videre indeholder kapitlet KUN krønikeskrivernes og kongehofnenes
// synsvinkel (Stemme: Opus). Synsvinklen fra landsbyerne er tilføjet af
// Hermes; syntesen nedenfor er udtrykkeligt foreløbig og bliver bagefter
// bearbejdet i fællesskab (se CLAUDE.md, perspektiv-workflow).
//
// Kapitlet knytter direkte an til „Germanerne og folkevandringen": Der
// sluttede fortællingen med kongeriger, der beholdt romerske embedsmænd
// og lod deres ret skrive ned på latin. Her bliver spørgsmålet, hvordan
// deraf opstod herredømme — og buen slutter i 800 i Rom.
//
// Kortet ligger i utils/themen/karten/koenigreiche.js — fire tilstande
// mellem 476 og 800; frankernes rige er på det første billede den mindste
// plet og på det sidste den største flade. Her er kun fasehenvisningerne
// oversat (karteHinweise), ikke selve kortet.
//
// Rene data — ingen UI-imports (arkitekturregel).

const koenigreiche = {
  id: 'koenigreiche',
  titel: 'De tidlige kongeriger — sådan blev erobrere til herskere',
  epoche: 'Fra Vestromerrigets undergang i 476 til Karl den Stores kejserkroning i 800',

  aufhaenger: {
    frage: 'De kom som krigere uden kancelli og uden krønike — og tre hundrede år senere lod en af deres efterkommere sig krone til kejser af paven. Hvordan bliver en flok krigere til et kongerige?',
    text: [
      'En hærfører kan befale, så længe han deler bytte ud. Forestil dig,',
      'at du er denne hærfører. Dine mænd følger dig, fordi du gør dem',
      'rige — guld, våben, heste, land. De følger dig personligt, ikke dit',
      'embede. Og nu har du vundet: Landet er dit. Det har byer, du aldrig',
      'har besøgt, veje, du ikke har bygget, og en million mennesker, der',
      'ikke forstår et eneste ord af dit sprog.',
      '',
      'Hvordan regerer du det? Hvordan sørger du for, at dine ordrer også',
      'gælder dér, hvor du ikke er? Hvordan opkræver du skatter, når ingen',
      'længere ved, hvem der skylder hvor meget? Og det sværeste spørgsmål',
      'af alle: Hvordan sikrer du, at din søn må det samme som dig — at',
      'folk adlyder ham, selvom han aldrig har vundet et slag?',
      '',
      'Præcis for denne opgave stod kongerne efter 476. Deres svar er den',
      'grundplan, som Europa i tusind år derefter byggede på: en alliance',
      'med kirken, en dåb på det rette tidspunkt, retten til pergament —',
      'og påstanden om, at Gud selv havde villet det sådan.',
      '',
      'Den 25. december 800 stod en af deres efterkommere i Rom og fik sat',
      'en kejserskrone på hovedet. Krønikeskriverne skrev: Riget er',
      'tilbage. Hvordan det gik til, fortæller dette kapitel — og først og',
      'fremmest, som det blev fortalt af dem, der havde noget at vinde ved',
      'det.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'chronisten',
      name: 'Krønikeskrivernes og kongehofnenes synsvinkel',
      stimme: 'Opus',
      text: [
        'Sådan bliver de tidlige kongerigers historie fortalt dér, hvor',
        'den blev skrevet ned: ved hofferne, i bispesæderne og i klostrene.',
        'Det er de mægtiges fortælling — ikke fordi de andre ikke havde',
        'haft noget at sige, men fordi det kun var disse, der lod skrive.',
        '',
        'Hav fire navne parat, mens du læser, for dem skylder vi næsten',
        'alt: **Gregor af Tours**, biskop, skrev omkring 590 sine „Ti',
        'historiebøger" om frankerne. **Fredegar** hedder en krønike fra',
        'det 7. århundrede, hvis forfatter vi ikke kender. **Beda**, en',
        'munk i Northumbria, fuldførte i 731 den første historie om det',
        'engelske folk. Og **Einhard** skrev omkring 830 Karl den Stores',
        'levned, efter at han i årtier havde levet ved dennes hof.',
        '',
        'Fire kirkemænd. Ingen af dem skrev udelukkende af nysgerrighed:',
        'Enhver skrev for nogen, om nogen og med en hensigt. Det gør ikke',
        'deres bøger værdiløse — det gør dem til kilder, man må læse som',
        'et brev, hvor man kender afsenderen.',
        '',
        '## Kortet efter enden',
        '',
        'Se på kortets første fase, året 476. Her er ikke tomt land og',
        'ingen vildmark, men et ruinlandkort: syv herredømmer, hvor der',
        'lige havde været ét. Vestgoterne holder Sydgallien og Spanien —',
        'det største rige i Vesten. Vandalerne sidder i Nordafrika,',
        'burgunderne ved Rhône, Odoaker i Italien. I Britannien er',
        'angelsaksiske høvdinge begyndt at kalde sig konger. Og frankerne?',
        'En stribe omkring Tournai — den mindste plet på hele billedet.',
        '',
        'Næppe nogen havde i 476 væddet på, at netop denne plet en dag',
        'skulle blive kortets største flade. På det sidste billede, i år',
        '800, er den det.',
        '',
        'Spørgsmålet, som alle disse herrer stod over for, var det samme:',
        'Hvordan holder man det sammen? En hær følger én mand. Et',
        'kongerige skal også fungere, når manden lige er et andet sted —',
        'og når han er død.',
        '',
        '## Hvor de nye herrer fik deres magt fra',
        '',
        'Først af det, de bragte med sig: **følgeskabet**. En høvding',
        'samlede mænd omkring sig, der svor ham troskab; han gav dem våben,',
        'smykker, heste, en plads ved sit bord og en andel af byttet. Det',
        'er ikke et embedsforhold, men et personligt bånd — og et dyrt. En',
        'konge, der ikke længere havde noget at dele ud, var snart ikke',
        'konge mere.',
        '',
        'Præcis her ligger succesens problem. Så længe man erobrer, er der',
        'bytte. Når erobringen er forbi, må kongen hente ud af landet, hvad',
        'han tidligere hentede ud af krigen. Det vil sige: skænke land væk',
        '(og dermed blive fattigere), opkræve afgifter (og til det bruge',
        'folk, der kan regne og skrive) — eller føre krig igen. Næsten alt,',
        'hvad der sker i de næste århundreder, har med den regning at gøre.',
        '',
        'Og så havde disse konger brug for endnu noget, som ikke kan købes',
        'for bytte: en grund til, at netop deres familie må herske. Det',
        'svar, de fandt, har præget Europa — de fik Gud med i båden.',
        '',
        '## Dåben som redskab',
        '',
        'Omkring 496 lod frankernes konge **Klodevig** sig døbe i Reims.',
        'Gregor af Tours fortæller det som et mirakel: Klodevig står i et',
        'slag mod alemannerne, som han er ved at tabe, lover at blive',
        'kristen, hvis han vinder — og vinder. Biskop Remigius skal have',
        'råbt til ham ved dåben: „Bøj din nakke. Tilbed det, du har brændt,',
        'brænd det, du har tilbedt." Selv året er usikkert; det kan også',
        'have været 498 eller 499.',
        '',
        'Det afgørende er ikke, at Klodevig blev kristen, men **hvilken',
        'slags kristen**. Goterne, vandalerne og burgundernes konger var',
        'nemlig for længst kristne — men arianere, tilhængere af en lære,',
        'som den katolske kirke havde fordømt som vranglære. For den',
        'katolske befolkning i Gallien og dens biskopper var disse konger',
        'kættere. Klodevig lod sig døbe katolsk og var dermed den eneste',
        'germanske konge, som den gamle romerske overklasse ubetinget',
        'kunne stille sig bag. Fra en fremmed krigsherre blev han fra den',
        'ene dag til den anden en beskytter af den rettroende.',
        '',
        'Hvor stærkt et redskab det var, ser man deraf, at andre gjorde',
        'det efter. I 589 trådte det tredje koncil i Toledo sammen, og',
        'vestgoternes konge **Rekkared** erklærede der, at han og hans folk',
        'opgav den arianske tro. Derefter regerede konger og biskopper i',
        'Spanien sammen; koncilerne i Toledo var halvt kirkeforsamling,',
        'halvt rigsforsamling. I 597 modtog kongen af Kent, Æthelberht,',
        'den romerske munk Augustin — forsigtigt, under åben himmel, af',
        'frygt for trolddom — og lod sig døbe. Også her forbigår den',
        'fromme fortælling gerne en lille detalje: Æthelberhts hustru',
        'Bertha var en frankisk prinsesse, for længst kristen, og havde',
        'taget sin egen biskop med.',
        '',
        'Sobert betragtet var dåben for disse konger begge dele: et',
        'trosskridt og et magtskridt. Krønikeskriverne fortæller kun om',
        'det første. Man må alligevel godt tænke det andet med.',
        '',
        '## Kirken arver forvaltningen',
        '',
        'Nu kommer dette kapitels vigtigste sætning, og den lyder',
        'uspektakulær: **Kongerne kunne som regel ikke skrive — kirken',
        'kunne.**',
        '',
        'Da Vestromerriget faldt fra hinanden, forsvandt dets forvaltning',
        'ikke bare; den vandrede. Bispesæderne lå i de gamle romerske',
        'byer, kirkedistrikterne fulgte de romerske forvaltningsdistrikter',
        '— vore stifter er for en stor dels vedkommende stadig romersk',
        'landkort. Biskopper kom ofte fra de samme fornemme familier, der',
        'tidligere havde stillet statholdere. De kunne latin, kendte loven,',
        'førte lister, forvaltede korn, dømte i retssager og forhandlede',
        'med belejrere.',
        '',
        'For en konge var en biskop derfor dobbelt værdifuld: som fagmand',
        'og som fortaler hos Gud. For en biskop var en konge dobbelt',
        'værdifuld: som beskyttelse og som pengemand. Begge havde brug for',
        'hinanden, og begge vidste det.',
        '',
        'Man ser resultatet i en tilsyneladende bagatel. Omkring 510 lod',
        'frankerne deres lov skrive ned, **Lex Salica** — deres egen,',
        'gamle lov med bøder for tyveri, manddrab og fornærmelser. Men de',
        'lod den skrive på **latin**, af kirkens skrivere, efter romersk',
        'forbillede. Det samme gjorde vestgoterne, burgunderne og',
        'langobarderne. Den, der vil gøre herredømmet varigt, har brug for',
        'skrift — og skriften lå i klostrene.',
        '',
        'Krønikeskriverne udleder heraf en formel, der skulle holde i seks',
        'hundrede år: Kongen regerer **af Guds nåde**. Ikke fordi han er',
        'den stærkeste kriger. Men fordi Gud har villet det — og den, der',
        'bevidner det, er kirken.',
        '',
        '## Teoderik: en konge, der ville være romer',
        '',
        'Den mand, der gik længst, var **Teoderik den Store**. Han kom til',
        'Ravenna i 493, dræbte Odoaker med egen hånd ved et gæstebud — og',
        'regerede derefter i treogtredive år så romersk, det overhovedet',
        'kunne lade sig gøre. Romerske embedsmænd, romersk ret, et senat,',
        'som han lod fortsætte arbejdet, kornuddeling, cirkuslege,',
        'byggeprogrammer. Han kaldte sig ikke kejser; formelt regerede han',
        'i kejserens navn i Konstantinopel. Hans kirker og hans gravmæle i',
        'Ravenna står den dag i dag; mosaikkerne kan man se.',
        '',
        'I de breve, som hans kansler Cassiodor skrev for ham, står',
        'programmet udtrykkeligt: Goterne sørger for forsvaret, romerne',
        'for civilisationen, og begge har gavn af det. Det var et alvorligt',
        'ment forsøg på at lade to folk leve i ét rige.',
        '',
        'Og det holdt ikke til det sidste. Teoderik var arianer, hans',
        'undersåtter katolske; da forholdet til Konstantinopel blev',
        'dårligere, blev mistilliden til forfølgelse. Ved slutningen af sit',
        'liv lod han den lærde **Boethius** henrette, som i fængslet endnu',
        'skrev „Filosofiens trøst" — en af middelalderens mest læste',
        'bøger. Få årtier senere var østgoternes rige knust, ikke af',
        'barbarer, men af Østromerriget.',
        '',
        '## Skyggesiden står i de samme bøger',
        '',
        'Den, der tror, at krønikeskriverne kun roste deres konger, har',
        'ikke læst dem. Gregor af Tours kalder Klodevig en ny Konstantin,',
        'ført af himmelen — og beretter på de samme sider, hvordan denne',
        'konge lod sine slægtninge rydde af vejen én efter én, én med',
        'øksen, én ved lejede mordere, én ved forræderi. Til sidst,',
        'fortæller Gregor, klagede Klodevig offentligt over, at han nu stod',
        'helt alene som en fremmed og ikke havde flere slægtninge, der',
        'kunne hjælpe ham — og Gregor føjer tørt til, at det sagde han ikke',
        'af sorg, men for at se, om der meldte sig endnu nogen, man kunne',
        'slå ihjel.',
        '',
        'Sådan fortsætter det. Merovingerne delte deres rige efter frankisk',
        'skik mellem alle sønnerne — og disse sønner førte krig mod',
        'hinanden. Dronningerne Brunhilde og Fredegunde bekæmpede hinanden',
        'i årtier; Brunhilde, højt dannet og i årtier indflydelsesrig, blev',
        'i 613 henrettet i en alder af omkring halvfjerds år, ved at man',
        'bandt hende til en hest. Det står ikke i en afsløringsbog; det',
        'står i krønikerne selv.',
        '',
        'Hvorfor skrev de det ned? Fordi de var kirkemænd og så et mønster',
        'i det: Hovmod straffes, Gud dømmer. Deres bøger er lovprisning',
        '**og** advarsel på samme tid. For os har det en praktisk fordel —',
        'en kilde, der også fortæller ubehagelige ting om sin helt, er',
        'mere troværdig end en, der kun stråler.',
        '',
        'Alligevel er rammen deres: Det handler om konger, biskopper, slag',
        'og mirakler. Om høsten rakte, står der i disse bøger kun, når en',
        'hungersnød var så stor, at den nåede hoffet.',
        '',
        '## 751 og 800: Kirken skaber konger',
        '',
        'Hvor langt alliancen mellem trone og alter havde båret, viste sig',
        'i 751. Merovingerne regerede da kun af navn; den virkelige magt',
        'lå hos deres hofmestre, karolingerne. Pipin, den siddende',
        'hofmester, lod paven stille et spørgsmål, der havde noget på sig:',
        'Om det var godt, at den kaldtes konge, som ingen magt havde. Paven',
        'svarede, at det hellere skulle være den, der faktisk udøvede',
        'magten, der kaldtes konge. Derefter blev den sidste merovinger',
        'sendt i kloster, og Pipin blev konge — og, det var det nye,',
        '**salvet**, efter forbillede af Det Gamle Testamentes konger.',
        '',
        'Dermed var det sagt, hvad der havde gjaldt siden Klodevig: Det er',
        'ikke afstamningen alene, der gør kongen, men anerkendelsen — og',
        'den vigtigste anerkendelse uddeler kirken.',
        '',
        'Pipins søn Karl regerede i seksogfyrre år og førte krig næsten',
        'hvert år. Han underlagde sig langobarderne (774), Bayern (788) og',
        'i en trediveårig, meget blodig kamp sakserne, som blev tvunget til',
        'dåb. Hans rige rakte til sidst fra Elben til over Pyrenæerne.',
        '',
        'Den 25. december 800 satte pave Leo 3. i Rom en krone på hans',
        'hoved og lod ham udråbe til kejser. For krønikeskriverne var det',
        'fuldendelsen, buen tilbage over tre hundrede år: **Riget er',
        'tilbage.** Einhard hævder, at hans herre var helt overrasket og',
        'ikke ville være gået ind i kirken, hvis han havde anet det —',
        'hvilket de fleste historikere anser for høflig diplomati. For i',
        'Konstantinopel sad der stadig en kejser, og dér gjaldt begivenheden',
        'som en anmasselse: Man kan ikke krone et andet rige, når det',
        'første stadig står.',
        '',
        'I Aachen lod Karl i mellemtiden gøre noget, der ser mere',
        'uskyldigt ud og har rækket længere end hans felttog. Han hentede',
        'lærde til hoffet, frem for alle angelsakseren Alkuin fra York, og',
        'lod antikke tekster afskrive — med en ny, klart læselig skrift.',
        'Meget af det, vi i dag ejer fra antikken, har kun overlevet, fordi',
        'det blev kopieret i disse årtier. Karl selv, beretter Einhard,',
        'forsøgte endnu som gammel mand at lære at skrive og lagde',
        'skrivetavler under sin hovedpude; rigtig lykkes ville det ikke for',
        'ham.',
        '',
        '## Og den anden side?',
        '',
        'Alt, hvad du lige har læst, kommer fra hofferne — fra dem, der',
        'lod skrive. Det er en historie om konger, biskopper, slag og',
        'kroninger, og den er ærlig inden for sin ramme: Den fortier',
        'hverken mordene eller troens nytte.',
        '',
        'Men i disse kongeriger levede ni ud af ti mennesker på landet. De',
        'dyrkede kornet, som afgifterne kom fra, og stillede mændene, som',
        'hærene blev til af. I krønikerne optræder de næsten kun som tal:',
        'som hungersnød, som pest, som plyndret landsby. Næppe én af dem',
        'har efterladt sig et navn.',
        '',
        'Disse spørgsmål kan hoffernes synsvinkel ikke besvare: Hvad',
        'ændrede sig for en landsby, når herren i det fjerne Toulouse',
        'pludselig hed noget andet? Mærkede man overhovedet skiftet fra',
        'det ene rige til det næste — eller kun på, hvem der hentede',
        'afgifterne? Hvad betyder „kongens dåb" for folk, der stadig gik',
        'til deres gamle kilder og træer? Og hvad har kirken bragt',
        'landsbyerne, ud over afgifter: beskyttelse, forsorg, en domstol,',
        'der også dømte mod mægtige?',
        '',
        'De hører en anden stemme til.',
      ].join('\n'),
    },
    {
      id: 'doerfer',
      name: 'Synsvinklen fra landsbyerne',
      stimme: 'Hermes',
      text: [
        'Denne synsvinkel fortæller kongerigernes historie nedefra — fra',
        'landsbyerne, hvor de fleste mennesker i denne tid levede. Den, der',
        'boede dér, pløjede, såede, høstede og betalte afgifter; han skrev',
        'ikke og lod ikke skrive. Krønikerne nævner disse mennesker kun i',
        'periferien — hvis de overhovedet gør. Derfor må også denne stemme',
        'ærligt sige, hvor den kommer fra: fra bopladsfund og',
        'markstrukturer, fra gravgaver, fra stednavne, fra de steder i',
        'lovene, hvor bønder pludselig optræder. Det er mindre, end',
        'hofferne efterlod — men det rækker til at se, at kongerigerne',
        'nedefra så ganske anderledes ud end oppefra.',
        '',
        '## Kongerigerne, set nedefra',
        '',
        'Hvad ændrede sig for en bonde, når en konge døde, og en anden',
        'kom? Kun lidt — undtagen navnet på den, der hentede afgifterne.',
        'Landsbyen blev, markerne blev, årets gang blev: såning om',
        'foråret, høst om sommeren, slagtning om efteråret. Kongerigerne',
        'skiftede oppe; nede fortsatte arbejdet. Krønikerne fortæller om',
        'erobringer og tronfølger, som om historien var de mægtiges',
        'turnering. For de fleste mennesker var den en række vintre, man',
        'måtte overleve.',
        '',
        '## Det, kongen havde brug for, kom fra vore lader',
        '',
        'Den glitrende verden ved hofferne — følge, fester, krige, gaver —',
        'blev betalt med det, landsbyerne arbejdede frem. Tienden til',
        'kirken, afgifterne til herren, hoveriet på dennes marker:',
        'Kongeriget var en maskine, der levede af høsten. Når',
        'krønikeskriverne skriver om erobrernes „bytte", glemmer de let,',
        'at det egentlige bytte voksede på markerne hvert år — og at det',
        'blev bjærget af mennesker, hvis navne ingen krønikeskriver',
        'nævner.',
        '',
        '## Kongens dåb',
        '',
        'Klodevigs dåb var for hofferne en begivenhed af største',
        'betydning. For en landsby i Gallien næsten ingenting til at',
        'begynde med: Man gik stadig til de kilder og træer, hvor',
        'forfædrene havde lagt deres gaver, fejrede de gamle fester og bad',
        'om beskyttelse for kvæg og høst. Kongens dåb blev først mærkbar i',
        'løbet af generationer — da kirken kom til landsbyen, byggede et',
        'kapel, indsatte en præst, omfortolkede festerne og slog de nye',
        'navne igennem. Hvad der oppefra var en begivenhed, var nedefra en',
        'langsom forandring, der trak ud over årtier. Og flere steder',
        'holdt begge dele længe til side om side: den kristne tro og de',
        'gamle skikke, som kirken forgæves søgte at forbyde.',
        '',
        '## Kirken i landsbyen',
        '',
        'Og hvad bragte kirken landsbyerne? Først afgifterne — tienden,',
        'der fødte hoffet og præsten. Men ikke kun. Klosteret eller',
        'bispkirken var ofte det eneste sted, der købte overskydende høst',
        'op, i nødetider uddelte korn og tog syge ind. Kirkefesterne gav',
        'året dets rytme. Og kirkens domstol var somme tider det eneste',
        'sted, hvor også en mægtig kunne drages til ansvar. Trøst og',
        'kontrol, beskyttelse og afgift lå i samme hånd — kirken var for',
        'landsbyerne begge dele, og de krønikeskrivere, der skrev for den,',
        'fortalte kun den ene side.',
        '',
        '## Hvad denne synsvinkel gør anderledes',
        '',
        'Også denne synsvinkel er en rekonstruktion, og den må indrømme',
        'det: Om de fleste menneskers liv ved vi foruroligende lidt. Men',
        'fortællingens retning ændrer vurderingen. Hvad krønikerne fejrer',
        'som opstigning og fuldendelse — Klodevigs dåb, Karls kroning —',
        'var for størstedelen af menneskeheden arbejde, hoveri og',
        'bekymringen for høsten. De tidlige kongerigers „gyldne tid" var',
        'for ni ud af ti mennesker ingen guldalder, men et hårdt liv, som',
        'man søgte at overleve. De mægtiges historie er ikke flertallets',
        'historie — den er kun den, der blev skrevet ned.',
      ].join('\n'),
    },
  ],

  // Syntese (Runde 9, fælles bearbejdet efter tilføjelsen af synsvinklen
  // fra landsbyerne ved Hermes).
  synthese: [
    'I de foregående kapitler lå perspektiverne side om side på',
    'landkortet — Rom og Kina, Europa og Japan. Her ligger de oven på',
    'hinanden: oppe og nede i samme land, i samme uge, ofte i samme',
    'landsby. Den ene side lod skrive, den anden pløjede. Den, der kun',
    'læser krønikerne, får meget at vide om tyve familier og næsten',
    'intet om ni ud af ti mennesker.',
    '',
    '**Hvor de mødes:** Begge synsvinkler ser den samme maskine:',
    'Kongerigerne blev holdt sammen af følgeskab og kirke.',
    'Krønikeskriverne fortæller det oppefra — dåbene, kroningerne,',
    'alliancerne. Landsbyerne oplevede det nedefra — afgifterne,',
    'hoveriet, tienden, de nye navne. Og begge ved: Kongerne kunne som',
    'regel ikke skrive; kirken kunne. Derfor er kirken i begge',
    'fortællinger den hemmelige hovedperson — dér som tronens støtte,',
    'her som hånden, der greb ind i landsbyen.',
    '',
    '**Hvor de skilles:** Hvad der oppe var en begivenhed, var nede en',
    'forandring over generationer. Klodevigs dåb: for hofferne det',
    'magtskridt, der grundlagde riget; for landsbyerne en fjern proces,',
    'der først blev mærkbar, da kapellet kom. Året 800: for',
    'krønikeskriverne fuldendelsen — rigets genkomst; for bønderne en',
    'vinter som alle andre. Og navnene: I krønikerne står konger,',
    'biskopper, dronninger — ikke en eneste bonde. De mægtiges historie',
    'er ikke flertallets historie; den er kun den, der blev skrevet ned.',
    '',
    '**Hvad der følger heraf:** Den, der kun kender tiden oppefra,',
    'holder krønikerne for hele historien. Hoffernes synsvinkel forråder',
    'sine egne hensigter, når man læser nøje: Den fortæller dåben som et',
    'mirakel og lader ane, hvor nyttig den var; den kalder konger af',
    'Guds nåde og beretter samtidig, hvordan disse konger lod deres',
    'slægtninge slå ihjel. Modsigelser i en kilde er ingen gene — de er',
    'det sted, hvor man lærer mest.',
    '',
    '**Din dom begynder her:** Hvad gør en konge til konge: afstamning,',
    'dåb, magt — eller dem, der anerkender ham? Og hvis der fra en tid',
    'kun er de mægtiges beretninger tilbage: Kan man så overhovedet',
    'vide, hvordan den var — og hvor ville du lede, hvis du alligevel',
    'ville forsøge?',
  ].join('\n'),

  urteil: {
    frage: 'Hvad gør en konge til konge: hans afstamning, hans dåb, hans magt — eller dem, der anerkender ham? Og hvem bestemmer egentlig, hvis historie om et kongerige der bliver fortalt?',
    hinweis: 'Der er ikke noget rigtigt eller forkert her. Tre anstød: For det første stillede Pipin i 751 paven spørgsmålet, om den, der ingen magt har, skal kaldes konge — overvej, hvad det spørgsmål afslører om magt, før du besvarer det. For det andet lod Klodevig sig døbe og blev derved acceptabel for biskopperne og den gamle romerske overklasse; var det tro, beregning — eller kan det slet ikke adskilles? For det tredje: tænk på en gruppe, du kender — klasse, forening, hold. Den, der bestemmer dér, har det som regel ikke alene gennem styrke. Hvad skyldes det ellers?',
  },

  quiz: [
    {
      frage: 'Hvorfor var det så vigtigt, at Klodevig lod sig døbe katolsk?',
      antworten: [
        'Fordi han dermed var den første kristne blandt de germanske konger.',
        'Fordi de andre konger ganske vist var kristne, men arianere — for den katolske befolkning i Gallien og dens biskopper kættere. Klodevig var dermed den eneste konge, som den gamle romerske overklasse kunne stille sig bag.',
        'Fordi paven lovede ham land i Italien til gengæld.',
      ],
      richtig: 1,
      erklaerung: 'Dåben var trosskridt og magtskridt på samme tid. Andre gjorde det efter: I 589 opgav kong Rekkared i Toledo for vestgoternes vedkommende den arianske tro. Gregor af Tours fortæller Klodevigs dåb som et mirakel — selv året er usikkert, 496, 498 eller 499.',
    },
    {
      frage: 'Hvem var Teoderik den Store?',
      antworten: [
        'En romersk kejser, der forsvarede Italien mod goterne.',
        'Den sidste vestromerske kejser, som Odoaker afsatte.',
        'Østgoternes konge, som fra 493 regerede fra Ravenna — med romerske embedsmænd, romersk ret og et senat, som han lod fortsætte arbejdet. Formelt regerede han i kejserens navn i Konstantinopel.',
      ],
      richtig: 2,
      erklaerung: 'Hans kansler Cassiodor formulerede programmet: Goterne forsvarer, romerne forvalter. Forsøget var alvorligt ment — og det holdt ikke til det sidste: Til sidst lod Teoderik den lærde Boethius henrette, som i fængslet endnu skrev „Filosofiens trøst".',
    },
    {
      frage: 'Hvordan fik de nye kongeriger skabt en forvaltning, selvom den romerske var gået i opløsning?',
      antworten: [
        'Gennem kirken: Biskopper kunne latin, ret og regning, kirkedistrikterne fulgte de romerske forvaltningsdistrikter, og i klostrene lå skriften.',
        'De byggede en helt ny forvaltning op af germanske krigere.',
        'De undlod forvaltning og regerede udelukkende gennem hærførelse.',
      ],
      richtig: 0,
      erklaerung: 'Konge og biskop havde brug for hinanden: den ene fagfolk og en fortaler hos Gud, den anden beskyttelse og penge. Det bliver synligt i Lex Salica — frankerne lod deres egen, gamle lov skrive ned, men på latin og af kirkens skrivere.',
    },
    {
      frage: 'Hvad skete der den 25. december 800 i Rom?',
      antworten: [
        'Paven erklærede Vestromerriget for genoprettet og blev selv kejser.',
        'Pave Leo 3. satte frankernes konge Karl en krone på hovedet og lod ham udråbe til kejser — for krønikeskriverne fuldendelsen, for Konstantinopel en anmasselse, fordi der allerede sad en kejser dér.',
        'Karl den Store erobrede Rom og lod sig vælge til kejser af senatet.',
      ],
      richtig: 1,
      erklaerung: 'Einhard hævder, at Karl var overrasket og ellers ikke ville være gået ind i kirken — de fleste historikere anser det for diplomati. Rom var dengang ikke længere en millionby, men et sted med måske 25 000 mennesker mellem ruiner. Titlen vejede alligevel tungere end byen.',
    },
    {
      frage: 'Skrev denne tids konger selv deres historie ned?',
      antworten: [
        'Ja, hvert kongehof førte sin egen dagbog.',
        'Nej — det var biskopper og munke, der skrev: Gregor af Tours om frankerne, Beda om angelsakserne, Einhard om Karl den Store. De fleste konger kunne ikke skrive.',
        'Nej, beretningerne stammer alle fra Konstantinopel.',
      ],
      richtig: 1,
      erklaerung: 'Derfor læser man disse bøger som et brev, hvor man kender afsenderen: Enhver skrev for nogen og med en hensigt. Karl den Store forsøgte ifølge Einhard endnu som gammel mand at lære at skrive og lagde skrivetavler under sin hovedpude — det lykkedes ham ikke rigtigt mere.',
    },
  ],

  karteHinweise: [
    {
      label: '476',
      hinweis:
        'Den sidste vestromerske kejser er afsat, og riget er ikke forsvundet, men delt op. Syv herredømmer, hvor der var ét. Se, hvor lille frankernes rige er her — en stribe omkring Tournai. Og se, hvor stort vestgoternes rige er. I 476 havde ingen væddet på, hvem af de to der til sidst kommer til at præge Europa.',
    },
    {
      label: 'ca. 526',
      hinweis:
        'Et halvt århundrede senere står kongerigerne. Klodevig har slået Syagrius (486), ladet sig døbe (omkring 496) og fortrængt vestgoterne fra Gallien (507) — hans rige rækker nu fra Bretagne til over Rhinen. I Ravenna regerer Teoderik, og han regerer romersk: med romerske embedsmænd, romersk ret og et senat, som han lader fortsætte arbejdet. Grænserne er tegnet glattere, end de var — et kongerige i denne tid var et net af troskabseder, ikke et opmålt statsområde.',
    },
    {
      label: 'ca. 600',
      hinweis:
        'Derimellem ligger et tilbageslag, som kortet ikke kan vise: Kejser Justinian erobrede Nordafrika (534) og Italien (554) tilbage — og hærgede Italien derved så grundigt, at det i 568 næsten ikke ydede langobarderne modstand. Tilbage er et lappetæppe: langobarder i nord og midt, Østromerriget i Ravenna, Rom og syd. I nord er Britannien blevet kristent igen — i 597 landede Augustin i Kent.',
    },
    {
      label: '800',
      hinweis:
        'På juledag 800 sætter pave Leo 3. i Rom en kejserskrone på frankernes konge Karl. Fra den mindste plet i 476 er blevet denne kartes største flade — fra Elben til Ebroen. Men der står også to ting på billedet: Spanien er siden 711 for størstedelens vedkommende islamisk, og i Konstantinopel sidder der stadig en kejser, som intet vil vide af en anden. Fra hans synspunkt er den 25. december 800 ingen festdag, men en anmasselse.',
    },
  ],
};

module.exports = koenigreiche;
