// Emne: Fra middelalderen til nyere tid — Europas fødsel.
//
// Dansk oversættelse af utils/themen/mittelalter.js (tysk original).
// Begge stemmer er færdige: den gamle ordens synsvinkel (Stemme: Opus)
// og byernes og opbruddets stemme (Stemme: Hermes); syntesen nedenfor
// fører dem sammen (se CLAUDE.md, perspektiv-workflow).
//
// Dette er første kapitel i nyere-tids-buen (notizen/kapitel-planung.md):
// broen fra Karl den Store til tærsklen til Trediveårskrigen. Det
// knytter direkte an til „De tidlige kongeriger" — dér sluttede
// fortællingen med kejserkroningen i 800, her begynder den med den.
//
// Kortet ligger i karten/mittelalter.js — fire tilstande mellem 800 og
// 1618, og en pil, der i 1492 løber ud af billedet. Her er kun
// fasehenvisningerne oversat (karteHinweise), ikke selve kortet.
//
// Rene data — ingen UI-imports (arkitekturregel).

const mittelalter = {
  id: 'mittelalter',
  titel: 'Fra middelalderen til nyere tid — Europas fødsel',
  epoche: 'Fra Karl den Stores kejserkroning i 800 til tærsklen til Trediveårskrigen i 1618',

  aufhaenger: {
    frage: 'Otte hundrede år, som man kalder „mørke" — og som universiteterne, byerne, katedralerne og Europas sprog kommer fra. Hvem gav egentlig denne tid dens navn — og hvad havde han ud af det?',
    text: [
      'Forestil dig, at nogen kalder årene, hvor du gik i skole, for „den',
      'mørke tid". Ikke dig. Nogen, der lever længe efter dig, som ikke var',
      'der, og som mener, at først med ham begyndte noget bedre.',
      '',
      'Præcis det skete for middelalderen. Tidens mennesker kaldte sig aldrig',
      'sådan — de ville ikke have forstået ordet. „Middelalder" betyder:',
      'tiden derimellem. Derimellem antikken, som man beundrede, og ens egen',
      'nutid, som man anså for dens genfødsel. Navnet opfandt renæssancens',
      'lærde, mere end tusind år efter dens begyndelse. Det er en vurdering,',
      'der forklæder sig som en tidsangivelse.',
      '',
      'Og hvad ligger der egentlig i disse otte hundrede år? En kejser, der',
      'står barfodet i sneen foran en borg. Hære, der drager mod Jerusalem og',
      'anretter et blodbad der. Et skib, der bringer en pest til Messina, som',
      'hver tredje europæer dør af. De første universiteter. Katedraler, som',
      'tre generationer byggede på. Et værksted i Mainz, hvor en bog',
      'pludselig bliver til tusind. Og en munk, der sender et stridsskrift ud',
      'og dermed splitter kirken.',
      '',
      'Mørk? Lys? Læs først, hvordan verden så ud — nemlig fra synsvinklen',
      'hos dem, der stod øverst i den. Bagefter må du selv dømme.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'alte-ordnung',
      name: 'Den gamle ordens synsvinkel',
      stimme: 'Opus',
      text: [
        'Dette er den gamle ordens fortælling: kejserens og kongernes,',
        'pavernes og biskoppernes, adelens på sine borge og munkenes i deres',
        'klostre. Det er den verden, der anså sig selv for gudgiven — og som',
        'i løbet af disse otte hundrede år oplever, at en anden vokser den',
        'over hovedet.',
        '',
        'Denne stemme har en fordel og en blind plet. Fordelen: Den kender sin',
        'verden indefra og kan forklare, hvorfor den var bygget sådan. Den',
        'blinde plet: Den anser denne byggemåde for tingenes naturlige orden,',
        'fordi den selv sidder øverst i den.',
        '',
        '## En verden af troskabseder',
        '',
        'Karl den Store var blevet kejser i 800. Hans rige faldt fra hinanden',
        'allerede under hans børnebørn — og det, der trådte i stedet, var',
        'ingen stat i nutidens forstand, men et net af personlige løfter.',
        '',
        'Grundforretningen hed **len**. En herre gav en mand land, sammen med',
        'de bønder, der arbejdede på det. Manden blev til gengæld hans vasal:',
        'Han svor troskab, mødte med sine ryttere, når herren drog i krig, og',
        'rådgav ham, når han blev spurgt. Disse vasaller havde igen egne',
        'vasaller, og de igen egne.',
        '',
        'Hvorfor så besværligt? Fordi der ikke var noget andet. Der var ikke',
        'penge i tilstrækkelig mængde, ingen skattelister, ingen embedsmænd,',
        'ingen veje, der hurtigt bar befalinger. En konge kunne ikke betale',
        'nogen, så han betalte med det eneste, han havde: med land. Og fordi',
        'landet så var væk, havde han konstant brug for nyt.',
        '',
        'Den indbyggede fejl viser sig hurtigt. Den, der havde haft et len',
        'længe nok, betragtede det som ejendom og nedarvede det til sin søn.',
        'Dermed blev tjeneren til en konkurrent. Hele de tyske kejseres',
        'historie kan læses som en kamp mod den regning — og de tabte den:',
        'Til sidst stod der ikke noget stærkt kongedømme som i Frankrig eller',
        'England, men et rige af hundredvis af fyrster, der kunne gøre, hvad',
        'de ville. I 1618 vil det hævne sig.',
        '',
        '## Dem, der beder, dem, der kæmper, dem, der arbejder',
        '',
        'Hvordan forklarer man folk, hvorfor verden er sådan? Man erklærer den',
        'for Guds plan. Omkring 1030 samlede en biskop ved navn Adalbero',
        'ordningen i tre ord: Der er dem, der beder, dem, der kæmper, og dem,',
        'der arbejder. Hver stand tjener de andre, ingen kan bestå uden de',
        'andre.',
        '',
        'Det lyder fredeligt og har en hage, som du straks ser: Af de tre',
        'stænder arbejdede én — og den udgjorde over halvfems procent af',
        'menneskene. Inddelingen forklarer ikke blot verden, den',
        'retfærdiggør den også. Den, der står helt nederst, står der ikke på',
        'grund af nogen uretfærdighed, men fordi Gud har indrettet det sådan.',
        'Læg mærke til det: Det er den mest bekvemme tanke, magthaverne',
        'nogensinde har haft.',
        '',
        'Denne ordens hverdag var **godssystemet**. En bonde fik jord,',
        'beskyttelse og en domstol; til gengæld afleverede han en del af',
        'høsten og arbejdede dage om året for herren. Han var som regel ikke',
        'fri — han måtte ikke bare flytte væk eller gifte sig med den, han',
        'ville. Slave var han dog heller ikke: Han havde rettigheder, og han',
        'kunne kræve dem ved domstolene.',
        '',
        'Klostrene hørte til samme orden, og de var mere end bedehus: de',
        'største jordbesiddere, de bedste landmænd, de eneste biblioteker, de',
        'eneste hospitaler, de eneste skoler. Hvis du kunne læse i år 1100,',
        'var du med stor sandsynlighed en gejstlig.',
        '',
        '## To sværd: kejser og pave',
        '',
        'Og nu kommer den strid, der har præget Europa som ingen anden — og',
        'som ingen andre steder i verden fandt sted på samme måde.',
        '',
        'Kirkens lære kendte to sværd, ét åndeligt og ét verdsligt: paven for',
        'sjælene, kejseren for kroppene. Så længe begge ville det samme, gik',
        'det godt. Striden brød ud på det mest nøgterne punkt, man kan tænke',
        'sig — spørgsmålet om, hvem der må indsætte biskopperne. For kejseren',
        'var det ikke et trosspørgsmål, men et eksistensspørgsmål: Biskopper',
        'forvaltede halve lande, stillede tropper og kunne — i modsætning til',
        'grever — ikke nedarve deres embeder. Den, der udnævnte dem,',
        'regerede.',
        '',
        'I januar 1077 stod kejser **Henrik 4.** i tre dage i bodedragt foran',
        'borgen **Canossa**, hvor pave Gregor 7. opholdt sig, og bad om',
        'ophævelse af bandlysningen. Han fik den. „Turen til Canossa" er den',
        'dag i dag et ordsprog for den dybeste ydmygelse.',
        '',
        'Men så enkelt var det ikke. Bandlysningen havde fritaget Henriks',
        'vasaller fra deres troskabsed — derfor var han nødt til at blive den',
        'kvit, og derfor tog han af sted. Knap var han fri, før han samlede en',
        'hær, drog til Italien og indsatte sin egen pave; Gregor døde i',
        'eksil. Ydmygelse og skaktræk på én gang. Først i 1122 blev striden',
        'afsluttet med et kompromis, Konkordatet i Worms.',
        '',
        'Følgen rækker til i dag. I Europa var der fra da af to magter,',
        'hvoraf ingen kunne sluge den anden. Den, der lå i strid med den ene,',
        'kunne vende sig til den anden. Ud af denne vedvarende konflikt er',
        'adskillelsen af åndelig og verdslig magt opstået — ikke af indsigt,',
        'men fordi ingen fik gennemført sin vilje.',
        '',
        '## „Gud vil det" — korstogene',
        '',
        'I 1095 opfordrede pave Urban 2. i Clermont til at hjælpe kristne i',
        'øst og befri Jerusalem. Mængden skal have svaret: „Gud vil det!" Den,',
        'der drog med, fik sine synder tilgivet.',
        '',
        'Fra den gamle ordens synsvinkel var det et mesterstykke: Paven førte',
        'nu det sværd, der egentlig tilhørte kejseren. Og ridderne, som førte',
        'endeløse fejder i deres eget land, havde endelig en fjende, der ikke',
        'var naboen.',
        '',
        'Det, der fulgte, må man lade stå i samme fortælling, som man lader',
        'troen stå i. Allerede på vejen, i Rhinlandet, myrdede korsfarergrupper',
        'jødiske menigheder — Europas første store pogromer. Den 15. juli 1099',
        'erobrede de Jerusalem og anrettede et blodbad blandt muslimer og',
        'jøder, som selv deres egne krønikeskrivere skrev om med rædsel. I',
        '1187 vandt **Saladin** byen tilbage og lod beboerne drage bort mod',
        'løsesum; i Vesten beundrede man ham for det endnu århundreder',
        'senere. I 1204 gik et korstog slet ikke til Det Hellige Land, men',
        'til Konstantinopel: En kristen hær plyndrede en kristen by, fordi',
        'overfarten ellers ikke kunne betales. I 1291 faldt Akko, den sidste',
        'støttebase. Efter knap to hundrede år var alt tabt.',
        '',
        'Tilbage er det, som ingen havde planlagt. Gennem kontakterne kom',
        'varer, regnemetoder, medicinsk viden og antikke tekster til Europa —',
        'meget af det oversat fra arabisk, som til gengæld havde bevaret',
        'grækerne. Og der blev erfaringen tilbage om, at der bag horisonten',
        'lå en verden, der var rigere end ens egen.',
        '',
        '## Da ordenen revnede: pesten',
        '',
        'Omkring 1300 levede der flere mennesker i Europa end nogensinde før.',
        'Så kom katastrofen, og den kom ad handelsruterne: I 1347 brød en',
        'pest ud i Kaffa på Krim, i oktober løb skibene ind i Messina, om',
        'vinteren i Genova og Marseille, sommeren 1348 var den i Paris, om',
        'efteråret i London. På fem år døde omkring **en tredjedel** af',
        'Europas mennesker, i nogle byer halvdelen.',
        '',
        'Ingen kendte årsagen. Man gættede på fordærvet luft, en Guds straf,',
        'en stjernekonstellation — og man ledte efter skyldige. I 1348 og',
        '1349 blev de jødiske menigheder i dusinvis af byer beskyldt for at',
        'have forgiftet brøndene og blev myrdet; i Strasbourg skete det, før',
        'pesten overhovedet var nået dertil.',
        '',
        'For den gamle orden var pesten et jordskælv. Hvor en tredjedel af de',
        'arbejdende mangler, bliver arbejde pludselig værdifuldt: De',
        'overlevende krævede højere løn og færre afgifter, og den, der ikke',
        'fik det, flyttede væk. Herrer og konger forsøgte at lægge loft over',
        'lønningerne ved lov — det hjalp ikke. I England og Frankrig brød',
        'store oprør ud. Fra nu af smuldrer den selvfølge, hvormed alle blev',
        'på deres plads.',
        '',
        'Dertil kom den lange krig: Fra 1337 til 1453 stred England og',
        'Frankrig om den franske krone. I den gik også ridderidealet under —',
        'ved Crécy og Azincourt skød engelske bueskytter det franske rytteri',
        'sammen. Og midt i denne krig førte en bondepige fra Lothringen en',
        'hær: **Jeanne d’Arc**, sytten år gammel. To år senere brændte man',
        'hende som kætter; en senere rettergang frikendte hende, og i dag er',
        'hun en helgen.',
        '',
        '## Tre tal, der ændrer alt',
        '',
        'Ved slutningen af denne tid står tre årstal, som hænger tættere',
        'sammen, end de ser ud til.',
        '',
        '**Omkring 1450, Mainz.** Johannes Gutenberg samler det, der længe',
        'havde eksisteret hver for sig: løse metaltyper, en presse og en',
        'trykfarve, der holder på metal. Før brugte en munk måneder på at',
        'skrive en bog af, nu opstår hundredvis af ens eksemplarer. Halvtreds',
        'år senere findes der millioner af bøger i Europa. For første gang i',
        'historien kan en tanke rejse hurtigere end det menneske, der har',
        'den.',
        '',
        '**1453, Konstantinopel.** Sultan Mehmed 2. tager byen; Det',
        'Østromerske Rige, som i denne apps tidligere kapitler stadig stod',
        'der, når alt i Vesten for længst var forfaldet, er efter næsten',
        'elleve hundrede år forbi. Græske lærde flygter med deres håndskrifter',
        'til Italien og bringer antikken med sig. Og landvejen mod øst ligger',
        'nu i osmanniske hænder — den, der vil have krydderier, må søge en',
        'søvej.',
        '',
        '**1492, Spanien.** På et enkelt år falder Granada, halvøens sidste',
        'islamiske kongerige; jøderne fordrives fra Spanien, mange af dem',
        'familier, der havde levet der i tusind år; og Columbus sejler mod',
        'vest for at nå Indien. De tre begivenheder hører sammen: De samme',
        'herskere, den samme overbevisning om at have retten på sin side.',
        'Hvad rejsen blev til, fortæller det næste kapitel.',
        '',
        '## Hvem opfandt „den mørke middelalder"?',
        '',
        'Omkring samme tid ser italienske lærde tilbage og genopdager antikken',
        '— bøger, byggeformer, billedhuggerkunst. De kalder deres egen tid en',
        'genfødsel, en **renæssance**. Og fordi der jo lå tusind år mellem den',
        'beundrede antik og dem selv, havde de brug for et navn til de år. De',
        'kaldte dem tiden derimellem: **middelalderen**. Digteren Petrarca',
        'talte allerede i det 14. århundrede om, at der efter den var kommet',
        'mørke.',
        '',
        'Hold her et øjeblik. Navnet på denne epoke stammer fra mennesker, der',
        'ikke har oplevet den og havde en interesse i, at deres egen tid',
        'fremstod lys. Det er reklame for egen sag — og den har virket den dag',
        'i dag.',
        '',
        'Hvad navnet fortier: I disse århundreder opstod universiteterne',
        '(Bologna 1088, Paris, Oxford), de gotiske katedraler med deres teknik',
        'og deres lys, brillerne, det mekaniske ur, papiret, trevangsbruget,',
        'halsselet, der gør, at en hest kan trække uden at blive kvalt — og',
        'de sprog, som Europa taler i dag. Befolkningen voksede mellem 1000',
        'og 1300 til omtrent det dobbelte. Det er ikke et samfund i stilstand.',
        '',
        'Og hvad navnet også fortier: Noget af det, man gerne tillægger',
        'middelalderen, hører slet ikke hjemme der. De store hekseforfølgelser',
        'fandt ikke sted i den mørke middelalder, men mellem 1560 og 1630 —',
        'altså i nyere tid, i bogtrykkets, universitets- og videnskabens tid.',
        'Også forestillingen om, at man dengang anså jorden for en flad',
        'skive, er forkert: At den er en kugle, vidste ethvert dannet menneske',
        'siden antikken; det, man skændtes om, var dens størrelse.',
        '',
        'Intet af dette gør tiden lys. Der var sult, pest, ufrihed, kætterbål',
        'og pogromer. Udsagnet er et andet: Den, der afgør en hel epoke med et',
        'enkelt ord, har sparet sig for eftertanken.',
        '',
        '## Splittelsen',
        '',
        'I 1517 vendte munken **Martin Luther** sig i Wittenberg mod',
        'afladshandelen — mod løftet om, at man med penge kunne købe sig fra',
        'straffe i hinsides. For den gamle orden var det først en strid blandt',
        'teologer. Den havde overset, hvad der i mellemtiden havde ændret sig:',
        'Der var bogtrykkerkunsten. Luthers teser var i løbet af få uger i',
        'hele riget, hans stridsskrifter udkom i hundredtusindvis.',
        '',
        'Det, der fulgte, var ikke kun trosstrid. Fyrster, der tog den nye',
        'lære til sig, kunne inddrage kirkegods og blev herrer over deres',
        'egen kirke — tro og regnskab løb side om side. I 1525 rejste bønderne',
        'sig og påberåbte sig Luther; Luther selv opfordrede til at slå dem',
        'ned. Titusinder døde.',
        '',
        'I 1555 endte første runde med Religionsfreden i Augsburg, og den',
        'formel, man enedes om, siger alt om denne orden: **cuius regio, eius religio** — hvis landet, hans religion. Det var ikke den enkelte,',
        'der besluttede, hvilken trosretning han fulgte, men hans landsherre.',
        'Den, der troede anderledes, måtte udvandre. Det var et fremskridt for',
        'tiden, og det viser samtidig, hvordan denne verden tænkte.',
        '',
        'Freden holdt godt tres år. I 1618 blev de kejserlige statholdere i',
        'Prag kastet ud ad vinduet, og den strid, som 1555 havde lagt stille,',
        'brød ud som en krig, der skulle vare tredive år. Dermed slutter',
        'dette kapitel — og det næste begynder.',
        '',
        '## Og den anden side?',
        '',
        'Alt, hvad du lige har læst, er fortalt oppefra: fra pfalzerne,',
        'bispesæderne, klostrene og fra borgene. Det er ordnens verden, som',
        'anså sig selv for gudgiven.',
        '',
        'Men i de samme århundreder voksede der mellem borgene noget andet',
        'frem, som i denne fortælling højst optræder i kanten: **byerne**.',
        'Købmænd, der rejste for egen regning. Håndværkere i lav. Råd, der',
        'regerede sig selv. Sætningen „byluft gør fri" betød bogstaveligt, at',
        'en undsluppen ufri var fri i byen efter år og dag — det er et hul i',
        'standsordenen, og endda midt i den. Dertil universiteterne,',
        'bogtrykkerne, bankiererne, reformatorerne.',
        '',
        'Disse spørgsmål kan den gamle orden ikke besvare: Hvordan ser denne',
        'tid ud, når man ikke betragter den fra tronen, men fra markedet? Hvor',
        'kom pengene fra, som til sidst betalte fyrsternes krige — og hvad',
        'krævede de for det, der havde dem? Hvorfor opstod næsten alle de nye',
        'idéer i byerne? Og var det, som den gamle orden oplevede som forfald,',
        'set nedefra måske et opbrud?',
        '',
        'De tilhører en anden stemme.',
      ].join('\n'),
    },
    {
      id: 'staedte',
      name: 'Byernes og opbruddets stemme',
      stimme: 'Hermes',
      text: [
        'Denne synsvinkel fortæller historien om dem, der hverken stod helt',
        'øverst eller helt nederst: om borgere, købmænd, håndværkere,',
        'studerende, bogtrykkere og reformatorer — menneskene i byerne. De',
        'skrev ingen krøniker om konger, men de førte forretningsbøger,',
        'bygningsregnskaber, lavsordninger og universitetsmatrikler. Og de',
        'efterlod de huse, der stadig står i dag. Fra deres synsvinkel var',
        'det, som den gamle orden oplevede som forfald, et opbrud —',
        'begyndelsen på noget nyt.',
        '',
        '## Byluft gør fri',
        '',
        'Byen var det sted, hvor den gamle orden ikke virkede. Den, der',
        'flyttede til en by, blev fri efter år og dag — „byluft gør fri", hed',
        'det. Her gjaldt ikke fødslen, men kunnen: En håndværker kunne opnå',
        'anseelse gennem sit arbejde, en købmand rigdom gennem sin dygtighed.',
        'Lavene afgjorde, hvem der måtte fremstille hvad — men de afgjorde det',
        'blandt ligemænd, ikke oppefra og ned. Og byen havde egne domstole,',
        'egne mure, egne rettigheder. For en bonde, der var flygtet fra',
        'godssystemet, var byen løftet om et liv, man selv bestemte.',
        '',
        '## De penge, herrerne havde brug for',
        '',
        'Fyrsterne byggede borge, førte krige og holdt hof — og alt sammen',
        'kostede penge, som de ikke havde. Deres land havde de for længst',
        'givet bort i len; det, der var tilbage, var byerne. Købmændene ydede',
        'kreditter, byerne betalte skatter, og til gengæld forhandlede de: om',
        'rettigheder, om told, om selvbestemmelse. Kongen af Frankrig, den',
        'engelske konge, de tyske fyrster — de havde alle brug for pengene fra',
        'byerne, og den, der giver penge, har noget at skulle have sagt.',
        'Hansaens byforbund beherskede handelen på Østersøen og Nordsøen uden',
        'nogensinde at være et kongerige.',
        '',
        '## De nye idéer vokser mellem husene',
        '',
        'Og hvorfor opstod næsten alle de nye idéer i byerne? Fordi det var',
        'der, de mennesker kom sammen, som havde noget at sige hinanden:',
        'lærde, der rejste fra universitet til universitet, købmænd, der',
        'bragte nyheder fra hele verden med sig, håndværkere, der',
        'videreudviklede teknikker. Bologna, Paris, Oxford — de første',
        'universiteter var byinstitutioner, ikke et fyrsteligt privilegium.',
        'Den, der kunne læse og regne, fandt sin plads i byen; på landet var',
        'begge dele nytteløse.',
        '',
        '## Bogtrykket: verden bliver mangfoldiggørbar',
        '',
        'Omkring 1440 udviklede Gutenberg i Mainz trykningen med løse typer.',
        'Det lyder teknisk — det var en revolution. Hidtil havde viden været',
        'det, munke afskrev i klostre; nu kunne en bog pludselig blive til et',
        'helt oplag. Idéerne forlod bibliotekerne og gik ud på gaden. Uden',
        'trykket ville reformationen ikke have været tænkelig: Luthers',
        'skrifter blev trykt i tusindvis af eksemplarer og spredt overalt i',
        'løbet af uger — historiens første massekommunikation. Den gamle',
        'orden, som hvilede på et videnmonopol, mistede kontrollen over det,',
        'folk læste.',
        '',
        '## Reformationen: opbruddet bliver uigenkaldeligt',
        '',
        'Og selve reformationen var også en bybevægelse. Rigsstæderne og',
        'borgerne stod bag reformatorerne — imod afgifterne til Rom, for en',
        'tro, som man selv kunne forstå, på sit eget sprog. Religionsfreden i',
        'Augsburg fra 1555 gav fyrsterne ret til at bestemme trosretningen —',
        'men jorden havde byerne forberedt, de byer, hvor de nye idéer først',
        'slog rod. Det, som den gamle orden bekæmpede som kætteri og forfald,',
        'var nedefra set friheden til selv at tænke.',
        '',
        '## Hvad denne synsvinkel gør anderledes',
        '',
        'Denne synsvinkel er lige så meget en fortælling som hoffernes — men',
        'dens retning er modsat. Hvor den gamle orden så undergangen for en',
        'gudgiven verden, ser den væksten af en ny: friheden, pengene, viden,',
        'pressen. Nyere tid blev ikke skabt af konger — den opstod i byerne,',
        'mellem torvet, lavshuset og bogtrykkerpressen. Og den har den dag i',
        'dag givet det ord gyldighed, som renæssancen fandt for tiden før:',
        '„den mørke middelalder". Fra byernes synsvinkel var denne tid snarere',
        'fødslen af det, vi kalder Europa.',
      ].join('\n'),
    },
  ],

  // Syntese: begge stemmer foreligger og føres her sammen.
  synthese: [
    'Dette kapitel handler om en overgang — og overgange ser modsat ud',
    'oppefra og nedefra. Det, som for den gamle orden fremstod som forfald —',
    'bønder, der flytter væk; byer, der har egne domstole; fyrster, der',
    'siger sig løs fra paven; bøger, som alle kan læse —, var for de andre',
    'netop gevinsten. De samme år, de samme begivenheder, to modsatte ord',
    'for dem.',
    '',
    '**Hvor de mødes:** Begge synsvinkler ser den samme verden: lenenes og',
    'troskabsedens orden, stænderne, kirken som magt. Og begge ser, at',
    'forandringen var uafvendelig — den gamle orden beklager den, byerne',
    'byder den velkommen. Begge ved også: Pengene kom fra byerne, og de nye',
    'idéer voksede mellem husene. Det, der skiller dem, er ikke',
    'iagttagelsen, men fortolkningen.',
    '',
    '**Hvor de skilles:** „Forfald" eller „opbrud" — det er hele forskellen.',
    'Den gamle orden så Guds plan forfalde, byerne så friheden vokse.',
    'Korstogene: et trosoptog eller begyndelsen på handel og udveksling?',
    'Pesten: Guds straf eller det øjeblik, hvor arbejdskraft blev knap og',
    'dyr? Reformationen: kætteri eller retten til selv at tænke? Og det ord,',
    'der sammenfatter det hele — „den mørke middelalder" — er ikke en',
    'iagttagelse, men en vurdering: afsagt af humanister, der ikke havde',
    'oplevet denne tid og havde en interesse i, at deres egen tid fremstod',
    'lys.',
    '',
    '**Hvad der følger deraf:** Den, der giver navnene, har allerede',
    'fortolket — det er denne apps ledende idé, og dette kapitel er dens',
    'smukkeste eksempel: Et helt årtusinde hedder den dag i dag det, som',
    'dets kritikere kaldte det. Den gamle orden forråder sig i sine egne',
    'begrundelser — den erklærer standsordenen for Guds plan, og man ser,',
    'hvem denne plan gavner. Byerne forråder sig i deres fremskridtstro — de',
    'ser i opbruddet kun væksten og lidt af det, der gik tabt. Ingen af de',
    'to synsvinkler lyver; begge er et udvalg.',
    '',
    '**Din vurdering begynder her:** Hvilke ord bruger du selv om hele tider',
    'eller grupper — og hvis vurdering giver du dermed videre? Og: Hvad',
    'ville nogen om fem hundrede år kalde vores nutid — og hvad ville han',
    'hænge det op på?',
  ].join('\n'),
  urteil: {
    frage: 'Var middelalderen virkelig „mørk" — eller er det en fordom, som renæssancen efterlod, og som vi har gentaget i fem hundrede år? Og hvilke billeder af fortidens tider tager vores egen tid for givet, som måske er lige så meget vurderinger?',
    hinweis: 'Der er her intet rigtigt og intet forkert. Tre ting at tænke over: For det første, undersøg, hvem der gav navnet — denne tids mennesker kaldte sig aldrig „middelalderlige"; begrebet stammer fra lærde, der levede tusind år senere og fejrede deres egen tid. For det andet, hold begge dele ved siden af hinanden: universiteter, katedraler, briller og ur på den ene side, pest, ufrihed og pogromer på den anden — og spørg dig selv, om ét enkelt ord overhovedet kan slå til for otte hundrede år. For det tredje, vend det om: Hvad ville nogen om fem hundrede år kalde vores nutid, og hvad ville han hænge det op på?',
  },

  quiz: [
    {
      frage: 'Hvad skete der i 1077 i Canossa?',
      antworten: [
        'Paven underkastede sig kejseren og opgav indsættelsen af biskopper.',
        'Kejser Henrik 4. stod som bodsøger foran borgen, hvor pave Gregor 7. opholdt sig, og opnåede ophævelsen af sin bandlysning.',
        'Kejser og pave indgik den første korstogsaftale.',
      ],
      richtig: 1,
      erklaerung: 'Det handlede om spørgsmålet, hvem der må indsætte biskopperne — for kejseren et magtspørgsmål, for biskopper forvaltede halve lande. Turen til Canossa var ydmygelse og skaktræk på én gang: Henrik var sluppet af med bandlysningen, kom tilbage med en hær og indsatte sin egen pave. Først i 1122 blev striden afsluttet med Konkordatet i Worms.',
    },
    {
      frage: 'Hvad var den Sorte Død?',
      antworten: [
        'En hungersnød, der ramte Europa mellem 1315 og 1317.',
        'Et navn for Hundredårskrigen mellem England og Frankrig.',
        'Pesten fra 1347 til 1353 — den kom ad handelsruterne fra Krim til Europa, og omkring en tredjedel af menneskene døde.',
      ],
      richtig: 2,
      erklaerung: 'Pesten fulgte præcis de veje, ad hvilke der før var kommet peber og silke: Kaffa, Messina, Genova, Marseille, Paris, London. Fordi ingen kendte årsagen, ledte man efter skyldige — i 1348/49 blev de jødiske menigheder i mange byer beskyldt og myrdet. Derefter var arbejdskraft knap og dermed værdifuld: De overlevende krævede højere løn.',
    },
    {
      frage: 'Hvem trykte i Europa først med løse metaltyper?',
      antworten: [
        'Johannes Gutenberg i Mainz, omkring 1450.',
        'Martin Luther i Wittenberg, 1517.',
        'Munkene i klostret Cluny, i det 11. århundrede.',
      ],
      richtig: 0,
      erklaerung: 'Gutenberg kombinerede løse typer, en presse og en holdbar trykfarve. Halvtreds år senere fandtes der millioner af bøger i Europa. Uden dette værksted ville Luthers stridsskrift fra 1517 have fundet få læsere — med det var det i løbet af to uger i hele riget. I Østasien trykte man i øvrigt allerede tidligere.',
    },
    {
      frage: 'Hvad betyder formlen „cuius regio, eius religio" fra 1555?',
      antworten: [
        'Ethvert menneske må selv vælge, hvilken trosretning han følger.',
        'Landsherren bestemmer sit lands trosretning — den, der tror anderledes, må udvandre.',
        'Kejseren bestemmer trosretningen for hele riget.',
      ],
      richtig: 1,
      erklaerung: '„Hvis landet, hans religion." Religionsfreden i Augsburg afsluttede første runde af trosstridene — et fremskridt for tiden, og samtidig viser formlen, hvordan denne orden tænkte: Der blev besluttet oppefra. Freden holdt godt tres år; i 1618 begyndte Trediveårskrigen.',
    },
    {
      frage: 'Hvor kommer udtrykket „den mørke middelalder" fra?',
      antworten: [
        'Fra middelalderens egne mennesker, som oplevede deres tid som mørk.',
        'Fra renæssancens lærde, som beundrede antikken og nedvurderede de tusind år derimellem — begrebet er en vurdering, ikke en tidsangivelse.',
        'Fra det 20. århundredes historikere, som undersøgte pesten.',
      ],
      richtig: 1,
      erklaerung: 'Ingen i middelalderen ville have kaldt sig „middelalderlig" — ordet betyder „tiden derimellem" og stammer fra mennesker, der ville have deres egen nutid til at fremstå lys. To prøver på sagen: De store hekseforfølgelser fandt først sted mellem 1560 og 1630, altså i nyere tid. Og at jorden er en kugle, vidste enhver dannet person i middelalderen.',
    },
  ],

  karteHinweise: [
    {
      label: 'ca. 800',
      hinweis:
        'I begyndelsen står et rige, der omfatter næsten hele Vesten — og som ikke holder hundrede år. Ved siden af ligger de to magter, som Europa slider på i de næste århundreder: kalifatet i syd, der holder hele Middelhavskysten, og Byzans i øst, hvor den kejser sidder, der anser sig selv for den eneste. Den lille strimmel midt i Italien er Kirkestaten — herfra vil paven senere udfordre riget.',
    },
    {
      label: 'ca. 1200',
      hinweis:
        'Karls rige er for længst delt: Af vestdelen bliver Frankrig, af østdelen Det Tysk-Romerske Rige. Det er katedralernes, de første universiteters og stridens mellem kejser og pave tid. Ved Levanten ligger korsfarerstaterne — og det, der er tilbage af dem i 1200, siger mere end nogen fortælling: en kyststrimmel. Jerusalem selv er siden 1187 igen tabt.',
    },
    {
      label: 'ca. 1500',
      hinweis:
        'På to menneskealdre ændrer alt sig: I 1453 tager osmanerne Konstantinopel — Det Østromerske Rige, der havde bestået i over tusind år, er forbi. Omkring 1450 trykker Gutenberg i Mainz med løse typer. I 1492 falder Granada, og samme år sejler Columbus mod vest. Læg mærke til, hvor pilen løber ud af billedet: Præcis der holder Europa op med at anse sig selv for hele verden.',
    },
    {
      label: '1618',
      hinweis:
        'Hundrede år efter Luthers teser er Europa delt — ikke længere i riger, men i trosretninger. Kanten mellem de to flader er denne kartes groveste linje, og den er grov med vilje: I virkeligheden lå begge dele ofte i samme land, undertiden i samme landsby. Bøhmen for eksempel var overvejende protestantisk og ligger her alligevel i den katolske del — og præcis der, i Prag, begynder krigen i 1618.',
    },
  ],
};

module.exports = mittelalter;
