// Emne: Det Romerske Rige — opstigning, orden, undergang.
//
// Dansk oversættelse af utils/themen/roemisches-reich.js (tysk original).
// Begge stemmer er færdige: den europæiske synsvinkel (Stemme: Opus) og
// den kinesiske synsvinkel (Stemme: Hermes); syntesen nedenfor fører dem
// sammen (se CLAUDE.md, perspektiv-workflow).
//
// Kortet ligger i utils/themen/karten/roemisches-reich.js — „Historie i
// bevægelse". Her er kun fasehenvisningerne oversat (karteHinweise),
// ikke selve kortet.
//
// Rene data — ingen UI-imports (arkitekturregel).

const roemischesReich = {
  id: 'roemisches-reich',
  titel: 'Det Romerske Rige',
  epoche: 'Antikken — fra byens grundlæggelse (efter sagnet 753 f.Kr.) til det vestromerske riges fald i 476 e.Kr.',

  aufhaenger: {
    frage: 'Et rige, der spændte over halvdelen af Europa — hvordan holder man sådan noget sammen uden telefon, uden internet, uden biler?',
    text: [
      'Forestil dig, at du skal regere et område, der strækker sig fra Skotland',
      'til Sahara og fra Portugal til Irak. En befaling fra din hovedstad har',
      'brug for flere uger til at nå ud til kanten. Menneskerne der taler',
      'dusinvis af sprog, beder til forskellige guder og har aldrig set nogen',
      'af dine embedsmænd.',
      '',
      'Det er præcis, hvad romerne gjorde — og det fungerede i århundreder.',
      'Hvordan? Og hvorfor holdt det alligevel op med at fungere til sidst?',
      'Det er den egentlig spændende historie. Årstallene er kun pejlemærker,',
      'ikke hovedsagen.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'europaeisch',
      name: 'Europæisk synsvinkel',
      stimme: 'Opus',
      text: [
        'Sådan fortælles Roms historie i Europa — i skolebøger, på museer, i',
        'film. Det er arvingernes fortælling: Europa ser i Rom sin egen',
        'begyndelse. Det farver historien, og det kan du roligt have i',
        'baghovedet, mens du læser.',
        '',
        '## Fra en landsby til et verdensrige',
        '',
        'Rom begynder småt. Et par bakker ved et vadested over Tiberen, bønder,',
        'kvæghandlere, strid med naboerne. Intet tyder på, at der herfra en dag',
        'skal styres et rige.',
        '',
        'Det første vendepunkt: Romerne jager deres konge væk og gør Rom til en',
        'republik — en „offentlig sag" (res publica). I stedet for en enehersker',
        'er der valgte embedsmænd, der kun sidder et år ad gangen, og senatet,',
        'forsamlingen af de indflydelsesrige familier. Romerne er så stolte af',
        'det, at de skriver det på deres felttegn: SPQR — „Senatet og Roms',
        'folk". Den dag i dag står det på romerske kloakdæksler.',
        '',
        'Så vokser Rom. Først over Italien, så videre ud. Den store modstander',
        'er Karthago, handelsmagten i Nordafrika. Gennem tre krige går det frem',
        'og tilbage — Hannibal fører endda krigselefanter over Alperne og',
        'påfører romerne adskillige knusende nederlag. Rom taber slag efter slag',
        'og vinder alligevel krigen, fordi det kan erstatte sine tab og aldrig',
        'giver op. Til sidst er Karthago ødelagt, og Middelhavet er et romersk',
        'indhav. Romerne kalder det kort og godt „mare nostrum" — vort hav.',
        '',
        'Succesen river næsten republikken i stykker. Sejrrige feltherrer som',
        'Cæsar har hære, der er tro mod dem personligt, ikke mod staten. Der',
        'følger borgerkrige. Til sidst står Augustus tilbage — officielt kun',
        '„den første borger", i virkeligheden den første kejser. Republikken',
        'består som kulisse, magten ligger hos en enkelt mand.',
        '',
        '## Hvordan holder man det sammen?',
        '',
        'Her bliver det interessant, for Rom har ikke kun erobret — erobre',
        'kunne mange. Rom kunne beholde. Fire ting var vigtige for det:',
        '',
        '**Vejene.** Omkring 80 000 kilometer befæstede veje gennemkrydser',
        'riget, så lige som de kan komme, over bakker og gennem sumpe. De blev',
        'ikke bygget til handlende, men til hæren: En legion skulle kunne komme',
        'hurtigt hen, hvor som helst. Men hvor soldater kan marchere, kan varer,',
        'breve, idéer og sygdomme også rejse. Vejene bandt riget sammen — og',
        'nogle bruges den dag i dag.',
        '',
        '**Hæren.** Legionerne var ikke en tilfældig hob, men professionelle',
        'soldater med samme udstyr, samme eksercits og samme lejrplan fra',
        'Britannien til Syrien. De kæmpede ikke kun — de byggede: veje, broer,',
        'grænseanlæg, hele byer. Ud af legionernes lejre er Köln, Bonn, Wien og',
        'London vokset frem.',
        '',
        '**Retten.** For den europæiske fortælling er det det vigtigste punkt.',
        'Romerne skrev deres love ned og stillede dem offentligt op, så alle',
        'kunne læse dem. De udviklede regler for kontrakter, ejendom, arv og',
        'skyld, så gennemtænkte, at jurister stadig lærer dem i dag. Noget af',
        'det ligger næsten uændret i den tyske borgerlige lovbog (BGB).',
        '',
        '**Borgerretten.** Måske Roms klogeste træk. Hvem der blev underlagt,',
        'forblev ikke evigt besejret: Man kunne blive romersk borger — som',
        'soldat efter 25 års tjeneste, som by gennem forlening. I 212 e.Kr. fik',
        'næsten alle frie indbyggere i riget borgerret. En nordafrikaner kunne',
        'blive kejser, en spanier ligeså. Riget blev ikke holdt sammen af',
        'herkomst, men af tilhørsforhold.',
        '',
        'Dertil kom noget upåfaldende: fred. I omkring to århundreder var der',
        'stort set roligt i det indre — romerne kaldte det „pax Romana", den',
        'romerske fred. Man kunne rejse fra Trier til Alexandria uden at krydse',
        'en grænse og betale overalt med de samme mønter. Ikke få mennesker i',
        'riget syntes godt om det. Andre så i det først og fremmest stilheden,',
        'der følger efter en erobring.',
        '',
        '## Hvad Rom har forandret',
        '',
        'Taler du dansk, taler du romersk med: vindue, mur, stræde, kælder,',
        'vin, kirke — alt sammen fra latin. Italiensk, spansk, fransk,',
        'portugisisk og rumænsk er opstået direkte af det talte latin. Juli og',
        'august bærer Cæsars og Augustus\' navne. Vores kalender går tilbage til',
        'den romerske. Og kristendommen, der først blev forfulgt i riget, blev',
        'til sidst dets statsreligion — og over de romerske veje og byer den',
        'religion, der kom til at præge Europa.',
        '',
        '## Hvorfor gik det under?',
        '',
        'En enkelt dato nævnes gerne: 476 e.Kr., da den sidste vestromerske',
        'kejser bliver afsat. En dreng ved navn Romulus Augustulus afleverer',
        'sine insignier, og ingen gør meget væsen af det. Ingen samtidig tænkte',
        'den dag: „Nu er antikken slut."',
        '',
        'Selve processen trak ud over århundreder, og forklaringerne modsiger',
        'hinanden den dag i dag:',
        '',
        '- Riget var blevet for stort til at blive regeret fra ét sted — det',
        '  blev delt i en vestlig og en østlig halvdel.',
        '- Kejsere blev udråbt og styrtet af deres egne tropper; i en krisetid i',
        '  det 3. århundrede skiftede magten i gennemsnit næsten hvert år.',
        '- Epidemier og misvækst ramte befolkningen, skattetrykket voksede,',
        '  pengene mistede værdi.',
        '- Fra nord og øst pressede folkeslag over grænserne — somme tider som',
        '  angribere, somme tider som flygtende for hunnerne, somme tider som',
        '  hvervede soldater. Til sidst blev Rom forsvaret af enheder, der selv',
        '  var „barbarer".',
        '',
        'Og så er der spørgsmålet, om „undergang" overhovedet er det rette ord.',
        'Den østlige rigshalvdel med hovedstaden Konstantinopel bestod i næsten',
        'tusind år endnu — dens indbyggere kaldte sig selvfølgelig stadig',
        'romere. Og i vest levede romersk ret, romersk sprog og romersk kirke',
        'bare videre under nye herskere. Måske er Rom ikke så meget faldet som',
        'forvandlet.',
        '',
        '## Hvorfor Europa fortæller denne historie sådan',
        '',
        'Rom har for Europa aldrig kun været fortid, men altid også et krav.',
        'Karl den Store lod sig krone til romersk kejser. Det Tysk-Romerske',
        'Rige bar navnet i titlen i tusind år. Zarerne og kejserne kaldte sig',
        'efter Cæsar. Napoleon lod sig fremstille som romersk feltherre, og hvem',
        'der ser på amerikanske regeringsbygninger, ser romerske søjler.',
        '',
        'Hvem der påberåber sig en forfader, fortæller sjældent dennes historie',
        'nøgternt. Derfor lyder Rom i europæiske bøger ofte som orden, ret og',
        'fremskridt — og sjældnere som det, erobring betyder for de erobrede:',
        'ødelagte byer, tvangsskatter, mennesker i slaveri. Den romerske',
        'historieskriver Tacitus har lagt selve denne sætning i munden på en',
        'britisk anfører: „De laver en ørken og kalder det fred."',
        '',
        'Det er det punkt, hvor en anden synsvinkel kan begynde. For samtidig,',
        'i den anden ende af Silkevejen, fandtes der et rige, der var lige så',
        'stort, og som næsten ingen i Europa taler om.',
      ].join('\n'),
    },
    {
      id: 'chinesisch',
      name: 'Kinesisk synsvinkel',
      stimme: 'Hermes',
      text: [
        'Denne synsvinkel fortæller ikke fra Rom, men fra øst — ud fra den',
        'kinesiske historieskrivning, der har iagttaget Rom på afstand. Også',
        'den er kun én fortælling, men en med andre spørgsmål og andre ord.',
        '',
        '## Da Qin — det fjerne rige i enden af Silkevejen',
        '',
        'Kina vidste om Rom, længe før europæerne vidste om Kina. I de',
        'kejserlige annaler kaldes Det Romerske Rige „Da Qin" — det store Qin.',
        'De kinesiske krønikeskrivere beskrev det som et land i verdens anden',
        'ende, rigt på glas og guld, hvis folk i handel blev anset for ærlige.',
        'I hundreder af år løb Silkevejen: Silke, vævet i Kina, bar romerske',
        'kejsere og senatorer — i Rom var silke så eftertragtet, at nogle vejede',
        'den op mod guld, og senatet endda diskuterede et forbud mod at bære',
        'den.',
        '',
        'Fra kinesisk synsvinkel var Rom altså aldrig verdens midtpunkt, men det',
        'vestlige endepunkt for en handelsvej. Allerede det gør en forskel: Den',
        'europæiske fortælling begynder med Rom og ser udad. Den kinesiske',
        'fortælling kigger på Kina — og Rom fremtræder i den som en fjern,',
        'respekteret handelspartner ved horisonten.',
        '',
        '## To riger, ét mønster',
        '',
        'Samtidig med at Rom steg op, voksede i Silkevejens anden ende',
        'Han-riget frem — omtrent lige så stort, omtrent lige så folkerigt. De',
        'to riger delte næsten verden i to halvdele, og begge kendte de samme',
        'problemer: kæmpe afstande, mange folkeslag, uro ved grænserne.',
        'Han-dynastiet holdt sit rige sammen med embedsmænd, der blev udvalgt',
        'efter eksaminer, med veje og med Silkevejens handelsnet — noget i samme',
        'stil som Rom, bare med andre redskaber.',
        '',
        'Også slutningen ligner hinanden: Han-riget faldt fra hinanden i år 220',
        'e.Kr., få årtier før Rom kom i sin store krise. Fra kinesisk synsvinkel',
        'er det ingen tilfældighed, men et velkendt mønster. Den kinesiske',
        'historieskrivning fortæller herredømme som et kredsløb: Et dynasti',
        'grundlægger et rige, bringer orden og velstand, bliver så svagere —',
        'gennem korruption, borgerkrige, misvækst — og mister til sidst',
        '„Himlens mandat". Så opstår et nyt dynasti ud af kaosset, og kredsløbet',
        'begynder forfra.',
        '',
        '## Himlens mandat',
        '',
        '„Himlens mandat" er nøglen til denne synsvinkel. Det siger: Herredømme',
        'er ikke blot besiddelse, men lånt — og det varer kun, så længe',
        'herskeren regerer godt. Når folket lider, når embeder kan købes, når',
        'bønder ikke længere kan betale deres skatter, så trækker himlen sit',
        'mandat tilbage, hvad man så mærker det eller ej. Sammenbruddet kommer',
        'så ikke pludseligt; det er bare enden på en lang, synlig svaghed.',
        '',
        'Sådan betragtet var Roms undergang ingen tragedie og ingen gåde, men et',
        'velkendt kapitel: Et stort rige, der var blevet for stort og for dyrt,',
        'hvis kejsere bekæmpede hinanden, hvis embeder blev solgt — et rige,',
        'der opfyldte tegnene på tabt mandat. Den kinesiske synsvinkel spørger',
        'ikke så meget „Hvorfor faldt Rom?", men „Hvilke tegn kunne man se',
        'længe i forvejen?" — det samme spørgsmål, som kinesiske',
        'krønikeskrivere også stiller til egne dynastier.',
        '',
        '## Hvad denne synsvinkel gør anderledes',
        '',
        'To forskelle springer i øjnene, når man lægger fortællingerne side om',
        'side.',
        '',
        'For det første: Europa fortæller Roms ende som et stort brud — enden',
        'på en verden. Den kinesiske synsvinkel kender ingen enkelt undergang,',
        'men mønstre: Riger dør, men civilisationer fortsætter. Efter Han-riget',
        'kom De Tre Kongedømmer, så nye dynastier, der påberåbte sig Han-arven.',
        'Rom har fra denne synsvinkel ikke „afsluttet verden", men er ét rige',
        'blandt mange i rigernes kredsløb.',
        '',
        'For det andet: Den kinesiske fortælling undrer sig over, hvor meget',
        'Europa gør Rom til sin egen begyndelse. I Kina gælder den egen historie',
        'som den centrale — Han-riget, Silkevejen, papir og silke. At Europa',
        'søger sine rødder i Rom, mens det samtidige Kina længe næsten ikke',
        'optrådte i europæiske bøger, er fra denne synsvinkel selv en historie',
        'værd: Hvem der fortæller verdenshistorien, vælger — og hvad der',
        'vælges, afhænger af, hvem der fortæller.',
        '',
        'Det er ingen korrektion af den europæiske synsvinkel. Det er en anden',
        'fortælling med egne spørgsmål: Hvad nu, hvis verdenshistorien ikke',
        'begyndte i Rom, men i begge ender af Silkevejen på samme tid?',
      ].join('\n'),
    },
  ],

  synthese: [
    'Nu står to synsvinkler side om side — og man ser straks, hvordan den',
    'samme historie bliver anderledes, alt efter hvor man kigger fra.',
    '',
    '**Hvor de mødes:** Begge fortællinger beskriver Rom som et rige, der',
    'bragte orden og stabilitet over et kæmpe område — den europæiske med',
    'veje, ret og borgerret, den kinesiske med blikket udefra på et rige, der',
    'beherskede sine grænser og sine folk. Begge kender spændingen mellem',
    'centrum og „barbarer" ved randen — germanerne nord for Rom, xiongnuerne',
    'nord for Kina. Og begge fortællinger stammer fra mennesker, der hører til',
    'blandt de beskrevne rigers arvinger eller efterfølgere: sejrherrer og',
    'skrivere.',
    '',
    '**Hvor de går fra hinanden:** Den europæiske synsvinkel gør Rom til sin',
    'egen begyndelse — ret, sprog, kalender og kirke fører tilbage til Rom, og',
    'dets ende fortælles som et stort brud. Den kinesiske synsvinkel kender',
    'Rom som en fjern handelspartner i enden af Silkevejen („Da Qin") og',
    'ordner opstigning og fald ind i et velkendt mønster: Himlens mandat, som',
    'et dynasti får og mister. Hvad der for den ene fortælling er en',
    'enestående undergang, er for den anden et kapitel i et kredsløb, som',
    'Kina selv gennemgik flere gange.',
    '',
    '**Ordvalget afslører synsvinklen:** „Undergang" eller „forvandling"?',
    '„Arv" eller „fjern handelspartner"? „Verdens midtpunkt" eller',
    '„endepunktet for en handelsvej"? De samme begivenheder — andre ord,',
    'anden historie. Præcis her begynder din egen vurdering: Hvilken',
    'fortælling taler mest til dig, hvilke spørgsmål lader den stå åbne — og',
    'hvilket svar ville du give en tredje person, der hverken er hjemme i Rom',
    'eller i Kina?',
  ].join('\n'),

  urteil: {
    frage: 'Rom har bragt veje, ret og fred — og har samtidig ødelagt byer, tvunget skatter igennem og gjort mennesker til slaver. Var Det Romerske Rige efter din mening mere gevinst eller mere tab for de mennesker, der levede i det? Og kommer det an på, hvem man spørger?',
    hinweis: 'Der er her ikke noget rigtigt og forkert. Nævn bare to, tre grunde for din opfattelse — og overvej, om en romersk senator, en slavekvinde og en germansk bonde ville give samme svar.',
  },

  quiz: [
    {
      frage: 'Stemmer det, at Rom altid blev regeret af kejsere?',
      antworten: [
        'Ja, fra grundlæggelsen og helt til enden.',
        'Nej — før var Rom i omkring 500 år en republik med valgte embedsmænd.',
        'Nej — Rom blev altid regeret af præster.',
      ],
      richtig: 1,
      erklaerung: 'Kejsertiden er først den anden halvdel af historien. Før regerede senatet og valgte embedsmænd, der kun sad et år ad gangen — republikken. Augustus blev først i 27 f.Kr. den første kejser.',
    },
    {
      frage: 'Hvad blev de berømte romerske veje bygget til i første række?',
      antworten: [
        'Til handlende, så handelen kunne blomstre.',
        'Til rejsende og ferietrafikken.',
        'Til hæren, så tropper og efterretninger hurtigt kunne nå alle vegne.',
      ],
      richtig: 2,
      erklaerung: 'Først og fremmest var det en militær nødvendighed: Hvem vil holde på et kæmperige, må kunne flytte soldater hurtigt. At handlende, breve og idéer brugte de samme veje, var en meget virkningsfuld sideeffekt.',
    },
    {
      frage: 'Kunne nogen, der ikke var født i Rom, blive romersk borger?',
      antworten: [
        'Ja — borgerretten blev forlenet, fra 212 e.Kr. endda til næsten alle frie indbyggere i riget.',
        'Nej, kun hvem der blev født i byen Rom.',
        'Kun folk fra Italien kunne få den.',
      ],
      richtig: 0,
      erklaerung: 'Det var et af Roms klogeste træk: Besejrede kunne høre til i stedet for evigt at forblive besejrede. Soldater fik borgerretten efter deres tjenestetid, hele byer gennem forlening — og der fandtes kejsere fra Spanien og Nordafrika.',
    },
    {
      frage: 'Stemmer det, at Det Romerske Rige gik under i år 476 e.Kr.?',
      antworten: [
        'Ja, den dag var pludselig alting forbi.',
        'Kun halvt — den sidste vestromerske kejser blev afsat, men den østlige rigshalvdel bestod i næsten 1000 år endnu.',
        'Nej, riget eksisterer den dag i dag.',
      ],
      richtig: 1,
      erklaerung: 'I 476 blev den sidste kejser i vest afsat — ganske udramatisk. I øst regerede Konstantinopel videre indtil 1453, og dets indbyggere kaldte sig selvfølgelig stadig romere. „Undergang" er derfor allerede en fortolkning, ikke en ren kendsgerning.',
    },
    {
      frage: 'Forsvandt latin sammen med Det Romerske Rige?',
      antworten: [
        'Ja, ingen brugte det bagefter.',
        'Nej — af det blev italiensk, spansk, fransk og andre sprog; også i dansk er der mange latinske ord.',
        'Nej, det tales den dag i dag overalt i Europa som dagligsprog.',
      ],
      richtig: 1,
      erklaerung: 'Af det talte latin er de romanske sprog blevet til. Og når du siger „vindue", „mur", „stræde" eller „vin", bruger du latinske ord — de nåede til os gennem romerne og er blevet hængende.',
    },
  ],

  karteHinweise: [
    {
      label: '264 f.Kr.',
      hinweis:
        'Før den første krig mod Karthago: Rom behersker halvøen til Rubicon — ikke en fodbred uden for Italien. Sicilien, Sardinien og Korsika kommer først til med sejren over Karthago (241 og 238 f.Kr.).',
    },
    {
      label: '146 f.Kr.',
      hinweis:
        'Karthago er ødelagt, og det samme er Korinth. Rom holder begge kyster af det vestlige Middelhav, dertil Grækenland og kysterne af Hispanien — af havet bliver „mare nostrum", vort hav.',
    },
    {
      label: '117 e.Kr.',
      hinweis:
        'Den største udstrækning, under kejser Trajan: fra Britannien til Egypten, fra Atlanten til den Persiske Bugt. I nord holder en enkelt linje riget sammen — Rhinen, limes, Donau.',
    },
    {
      label: '476 e.Kr.',
      hinweis:
        'I vest er der kun Italien tilbage af et verdensrige; Britannien, Gallien, Hispanien og Africa er faldet til nye herskere. Øst står derimod stadig — og vil stå i næsten tusind år endnu. „Undergang" er derfor allerede en fortolkning.',
    },
  ],
};

module.exports = roemischesReich;
