// Dansk oversættelse: Rusland og Vesten (1991 til i dag).
//
// Tre stemmer er færdige: Vestens syn (stemme: Opus), Ruslands syn
// (Jelzin-årene, Putin — efter operatørens direktiv „virkelig objektiv",
// stemme: Hermes) og Ukraines syn (stemme: Hermes). Syntesen fører alle tre
// sammen. Kortets faser er oversat i karteHinweise nederst.
//
// Rene data — ingen UI-imports (arkitekturregel).

module.exports = {
  id: 'russland-westen',
  titel: 'Rusland og Vesten',
  epoche: '1991–i dag',

  aufhaenger: {
    frage: 'To sider, der havde vundet sammen i 1945 og i 1990 kaldte hinanden „partnere", står i dag igen over for hinanden — og en sætning fra februar 1990, som ingen fik skrevet ned, føres den dag i dag som bevis. Hvordan bliver et partnerskab i løbet af tredive år igen til en front?',
    text: [
      'Den 21. november 1990 underskrev toogtredive europæiske stater i Paris,',
      'sammen med USA og Canada, et dokument, der erklærede den kolde krig for',
      'afsluttet. „Konfrontationens og Europas delings tidsalder er forbi", står der',
      'i Paris-chartret. Underskrifterne stammer fra Michail Gorbatschow, George',
      'Bush, Helmut Kohl og François Mitterrand. Et år senere fandtes Sovjetunionen',
      'ikke mere.',
      '',
      'Det, der kom bagefter, var først håb. Rusland blev i 1998 optaget i kredsen',
      'af de syv store industrilande, der derefter hed G8. I 1997 underskrev NATO',
      'og Rusland en grundakt, hvor begge sider udtrykkeligt erklærede, at de ikke',
      'længere betragtede hinanden som modstandere. I 2002 satte de sig ved samme',
      'bord i et fælles råd. Russiske og amerikanske soldater øvede sammen.',
      '',
      'Og så var der den anden halvdel af de samme år. Ruslands økonomiske',
      'produktion faldt mellem 1991 og 1998 med omkring fyrre procent — mere end',
      'den amerikanske under verdenskrisen. En hel generations opsparing opløste',
      'sig i inflationen. Den forventede levealder for russiske mænd faldt på fire',
      'år fra 64 til 57 år. I august 1998 var staten insolvent.',
      '',
      'Mellem de to halvdele ligger en sætning. Den 9. februar 1990 sagde den',
      'amerikanske udenrigsminister James Baker i Kreml til Gorbatschow, at NATO',
      'ikke ville udvide sig „en tomme mod øst". Han sagde det i samtalen om den',
      'tyske genforening, der blev aldrig lavet en traktat af det, og om han mente',
      'Polen og de baltiske stater eller kun Østtyskland, er omstridt den dag i',
      'dag. Den ene sætning står den dag i dag i enhver debat om Rusland og Vesten',
      '— hos nogle som bevis på et tillidsbrud, hos andre som dokumentation for,',
      'hvor upålidelig erindringen er.',
      '',
      'Dette kapitel begynder med Vestens syn. Det er én af flere stemmer, ikke den',
      'rigtige — hvilken der taler først, afhænger af, hvem der har skrevet denne',
      'runde, og er ingen rangorden.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'westen-sicht',
      name: 'Vestens syn — USA, NATO og Europa',
      stimme: 'Opus',
      text: [
        'Denne stemme fortæller fra Washington, Bruxelles, Berlin, Warszawa og',
        'Tallinn: fra de hovedstæder, hvor beslutningerne om NATO blev truffet, men',
        'også fra de lande, der i 1999 og 2004 absolut ville ind og havde deres egne',
        'grunde til det.',
        '',
        'Den er ligeværdig med de øvrige stemmer i dette kapitel. At den står først',
        'her, er ingen rangorden — det skyldes blot, hvem der har overtaget denne',
        'runde. Og den har en opgave, der er sværere end i alle kapitler før: Dette',
        'kapitel er ikke afsluttet. Mens disse linjer skrives, føres den krig, som',
        'de handler om. Den, der skriver om en igangværende historie, er selv part',
        '— og den eneste ærlige måde at håndtere det på er at sige det og alligevel',
        'være så præcis, som det er muligt.',
        '',
        '## 1991: håbet — og hvad der bar det',
        '',
        'Vesten forstod Sovjetunionens ophør ikke som en sejr over Rusland — i',
        'hvert fald ikke i de officielle dokumenter. Paris-chartret af 21. november',
        '1990 taler om et fælles Europa, ikke om vindere og tabere. Og det indeholder',
        'en sætning, der kommer igen tre gange i dette kapitel: Enhver stat har ret',
        'til frit at vælge sine alliancer — eller til ikke at tilhøre nogen. Det har',
        'Sovjetunionen været med til at underskrive, og Rusland har bekræftet det',
        'igen i 1999 i Istanbul-chartret.',
        '',
        'Det, der fulgte, var en række invitationer. I 1994 trådte Rusland ind i',
        '„Partnerskab for Fred", det program, hvormed NATO bandt sine tidligere',
        'modstandere til sig. I 1997 underskrev begge sider **NATO-Rusland-grundakten**:',
        'De erklærede heri, at de ikke længere betragtede hinanden som modstandere,',
        'og NATO lovede ikke at opstille atomvåben eller permanent stationerede',
        'store kampformationer i de nye medlemsstater — et tilsagn, som alliancen',
        'holdt indtil 2014. I 1998 blev G7 til **G8**. I 2002 opstod',
        '**NATO-Rusland-rådet**, hvor Rusland ikke sad som gæst, men som',
        'ligeværdigt medlem. I 2012 trådte Rusland ind i Verdenshandelsorganisationen',
        '— med vestlig støtte.',
        '',
        'Efter den 11. september 2001 var Wladimir Putin den første udenlandske',
        'statschef, der ringede til George W. Bush. Rusland åbnede luftrummet for',
        'forsyningerne til Afghanistan og hjalp med at opbygge baser i Centralasien.',
        'Den 25. september 2001 talte Putin tysk foran Forbundsdagen og fik stående',
        'bifald. Den, der i dag fortæller, at Vesten udelukkede Rusland fra starten,',
        'må forklare disse år.',
        '',
        '## 1990\'erne: hvad Vesten så — og hvad det ikke ville se',
        '',
        'Og dog begynder også den første ubehagelige passus i denne fortælling her —',
        'og den er stor. Vesten har ikke kun observeret den russiske omdannelse i',
        '1990\'erne, det har rådgivet om den og været med til at finansiere den.',
        '',
        'Prisfrigivelsen i januar 1992 — „chokterapien" — skulle gå hurtigt, fordi',
        'man frygtede, at en langsom omdannelse politisk ville blive rullet tilbage.',
        'Resultatet blev en inflation på over 2.500 procent i det første år. Den,',
        'der havde sparet op hele livet, var fattig i løbet af måneder.',
        'Masseprivatiseringen via vouchers gav enhver borger et stykke af',
        'statsformuen; de fleste solgte det for nogle få dollars, fordi de havde brug',
        'for penge. I 1995/96 kom proceduren „lån mod aktier": Bankerne lånte staten',
        'penge mod aktieposter i de største råstofselskaber — og da staten ikke',
        'betalte, beholdt de aktierne. Sådan opstod oligarkerne i løbet af få år.',
        'Den 17. august 1998 erklærede Rusland sig statsbankerot.',
        '',
        'Vestlige rådgivere, Den Internationale Valutafond og vestlige regeringer har',
        'anbefalet, støttet og finansieret denne vej. I marts 1996, fire måneder før',
        'præsidentvalget, gav IMF Rusland et lån på 10,2 milliarder dollars; Boris',
        'Jelzin lå i målingerne på få procent — og vandt. Man kan diskutere, om der',
        'var alternativer — eksperterne strides den dag i dag. Men denne stemme kan',
        'ikke lade, som om den russiske elendighed i 1990\'erne var en ren russisk',
        'sag. Det var tiden, hvor millioner af mennesker forbandt ordet „demokrati"',
        'med tomme hylder, udeblivende lønninger og en håndfuld nye milliardærer. Den,',
        'der vil forstå, hvorfor orden i Rusland senere gjaldt mere end frihed,',
        'finder svaret her.',
        '',
        'Dertil kom tonen. „Vi har vundet" var i 1990\'erne en almindelig sætning i',
        'Vesten. Francis Fukuyamas formel om „historiens ende" blev læst, som om man',
        'kun behøvede at vente på, at alle andre blev som os. Denne **triumfalisme**',
        'var ikke den officielle politik, men den var stemningen — og i Moskva',
        'hørte man den præcist. En stormagt, der netop havde mistet halvdelen af sit',
        'statsområde, sin økonomi og sin rolle i verden, blev behandlet som en elev,',
        'der får hjælpeundervisning. Det var en fejl, og den har kostet mere end',
        'mange traktater.',
        '',
        '## Tjetjenien: krigene, som Vesten så bort fra',
        '',
        'I december 1994 marcherede den russiske hær ind i Tjetjenien, der havde',
        'erklæret sig uafhængigt. Groznyj blev skudt i stykker i et vinterfelttog;',
        'overslagene over de civile døde i denne første krig spænder fra 30.000 til',
        'over 50.000. I 1996 endte den med en våbenhvile, der lod spørgsmålet stå',
        'åbent. I 1999 begyndte den anden krig, denne gang under den nye',
        'premierminister Wladimir Putin; De Forenede Nationer kaldte i 2003 Groznyj',
        'for „jordens mest ødelagte by".',
        '',
        'Hvad gjorde Vesten? Det protesterede i erklæringer og fortsatte i øvrigt.',
        'Jelzin forblev den partner, man støttede, fordi man frygtede, hvad der',
        'ville komme efter ham. Og i den anden krig kom et andet motiv til: Efter',
        'den 11. september 2001 rubricerede også Vesten Tjetjenien under',
        '„terrorbekæmpelse". Der var på russisk side faktisk angreb og',
        'gidseltagninger med hundredvis af døde — Moskva 2002, Beslan 2004 —, og der',
        'var på russisk side en fremfærd mod civilbefolkningen, som Den Europæiske',
        'Menneskerettighedsdomstol har fordømt i over to hundrede domme. Begge dele',
        'er sandt. Vesten har sagt det andet i lang tid mere sagte end det første,',
        'og det hører med i denne fortælling.',
        '## Kernen: NATOs udvidelse mod øst',
        '',
        'Her ligger den strid, som dette kapitel i virkeligheden handler om. Den',
        'lader sig dele op i fire spørgsmål, og denne stemme besvarer alle fire —',
        'også dem, den ikke bryder sig om.',
        '',
        '### For det første: Hvad blev sagt i 1990?',
        '',
        'Den 9. februar 1990 sagde den amerikanske udenrigsminister **James Baker**',
        'til Gorbatschow, at hvis et forenet Tyskland forblev i NATO, ville NATO',
        'ikke udvide sit ansvarsområde „en tomme mod øst" — på originalsproget „not',
        'one inch eastward". Samme dag og i ugerne derefter sagde lignende ting:',
        'forbundskansler Helmut Kohl, udenrigsminister Hans-Dietrich Genscher (i sin',
        'tale i Tutzing den 31. januar 1990), den britiske udenrigsminister Douglas',
        'Hurd og NATOs generalsekretær Manfred Wörner. Disse tilsagn er ikke et',
        'rygte: Samtalereferaterne er frigivet og siden 2017 offentligt tilgængelige',
        'i National Security Archive på George Washington University.',
        '',
        '### For det andet: Blev det til en traktat?',
        '',
        'Nej. Der findes intet dokument, hvor NATO forpligter sig til ikke at optage',
        'nye medlemmer. **To-plus-fire-aftalen** af 12. september 1990, der',
        'folkeretligt regulerede den tyske genforening, siger i **artikel 6**',
        'udtrykkeligt det modsatte: „Det forenede Tysklands ret til at tilhøre',
        'alliancer med alle de rettigheder og pligter, der følger heraf, berøres ikke',
        'af denne traktat." Artikel 5 regulerer, hvad der ikke må stationeres på det',
        'tidligere DDR\'s område — ingen atomvåben, ingen udenlandske tropper —, og',
        'denne begrænsning gælder den dag i dag. Om andre lande står der intet i',
        'traktaten, fordi andre lande ikke var dens genstand.',
        '',
        'Også Gorbatschow selv har senere bekræftet det. I 2014 sagde han i et',
        'interview, at emnet „NATO-udvidelse" dengang slet ikke var blevet forhandlet',
        '— det var i de år slet ikke kommet på tale, fordi Warszawapagten stadig',
        'bestod. I samme åndedrag tilføjede han, at **ånden** i datidens tilsagn',
        'senere var blevet krænket. Begge halvdele af denne sætning hører sammen, og',
        'begge sider citerer sædvanligvis kun den ene af dem.',
        '',
        '### For det tredje: Hvorfor kom de nye medlemmer alligevel?',
        '',
        'Fordi de ville det — og de ville det meget. Polen, Tjekkiet og Ungarn',
        'tiltrådte den 12. marts 1999, syv andre stater den 29. marts 2004 —',
        'deriblandt Estland, Letland og Litauen, som var blevet annekteret af',
        'Sovjetunionen i 1940. I hvert af disse lande var det valgte parlamenter og',
        'regeringer, der stillede ansøgningen; i flere var der desuden',
        'folkeafstemninger med klare flertal. Tiltrædelsen var ikke noget, Vesten',
        'bragte til disse lande, men noget, de i årevis havde bedt om — og som fra',
        'starten blev nægtet dem af hensyn til Moskva.',
        '',
        'Set fra vestligt perspektiv følger den afgørende skelnen heraf: En alliance,',
        'man kan tiltræde, er noget andet end en blok, man bliver placeret i. I 1945',
        'spurgte ingen polakkerne. I 1999 tvang ingen dem. Og netop det er den ret,',
        'som Paris-chartret tilkender enhver stat — også den, hvis nabo ikke ser det',
        'gerne.',
        '',
        '### For det fjerde: Hvad gjorde Vesten forkert?',
        '',
        'Tre ting — og de står her, fordi de hører til her.',
        '',
        'For det første **dobbelttydigheden i 1990**. Man har sagt sætninger, der',
        'skulle berolige, uden at få dem på papir — og senere henvist til papiret.',
        'Juridisk er det rent. Politisk er det den slags snilde, der har en pris, og',
        'prisen var tillid.',
        '',
        'For det andet **advarslerne fra egne rækker**, som man overså. George F.',
        'Kennan, inddæmningspolitikkens fader, kaldte i 1997 udvidelsen i New York',
        'Times for „den skæbnesvangreste fejl i amerikansk politik i hele',
        'efterkrigstiden". Den senere CIA-direktør William Burns skrev i 2008 som',
        'ambassadør i Moskva et telegram med titlen „Njet betyder njet": Et',
        'NATO-medlemskab for Ukraine ville være en rød linje for hele den russiske',
        'elite, ikke kun for Putin. Man kan mene, at begge tog fejl. Men man kan',
        'ikke påstå, at ingen har sagt det.',
        '',
        'For det tredje **Bukarest 2008**. På topmødet den 3. april 2008 erklærede',
        'NATO, at Ukraine og Georgien „vil blive medlemmer af NATO" — men besluttede',
        'ingen køreplan dertil, fordi Tyskland og Frankrig var imod. Det var den',
        'dårligste af alle muligheder: en meddelelse, som Moskva læste som en trussel,',
        'uden nogen form for beskyttelse af de to lande, det drejede sig om. Fire',
        'måneder senere førte Rusland krig i Georgien; seks år senere på Krim. Den,',
        'der betragter denne rækkefølge, må tage topmødet i Bukarest alvorligt uden',
        'at gøre det til årsagen — begge dele ville være for letkøbt.',
        '',
        '### Og det russiske syn?',
        '',
        'Den hører til her, også i dette perspektiv, og den lyder omtrent sådan: Man',
        'lovede os noget mundtligt i 1990, henviste os derefter til det med småt og',
        'førte i femogtyve år en militæralliance fra Elben helt op til vores grænse —',
        'mens vi var for svage til at sige nej. Set fra dette syn er ikke den enkelte',
        'tiltrædelse pointen, men mønstret: Hver gang Rusland var svagt, rykkede',
        'linjen tættere på.',
        '',
        'Denne stemme holder det, der står ovenfor, op imod — traktater,',
        'selvbestemmelse, grundakten fra 1997, som NATO holdt sig til i sytten år.',
        'Men den holder det op imod uden at erklære den anden opfattelse for opfundet.',
        'En opfattelse, som på begge sider af Kreml deles af mennesker, der ellers',
        'deler lidt, er ikke et propaganda-fund. Den forklarer blot ikke alting: Den,',
        'der lader grænser ændre sig, fordi han føler sig truet, gør en følelse til',
        'en ret, som ikke er forudset i folkeretten.',
        '',
        'Og for at det ikke misforstås: At gengive fair betyder at gøre forståeligt,',
        'ikke at retfærdiggøre. Det er to forskellige ting, og at holde skellet rent',
        'er dette kapitels egentlige arbejde — på det afgøres det, om man kan forstå',
        'uden at være enig.',
        '',
        '## Rusland under Putin — begge halvdele, med tal',
        '',
        'Den 31. december 1999 overdrog Jelzin forretningerne til Wladimir Putin.',
        'Hvad der så kom, fortælles i Vesten ofte kun halvt. Derfor står begge',
        'halvdele her side om side — ikke for at stille dem op mod hinanden, men',
        'fordi man uden den første ikke forstår den anden.',
        '',
        '### Hvad der blev bedre (2000–2008)',
        '',
        'Økonomien voksede mellem 1999 og 2008 i gennemsnit med omkring syv procent',
        'om året. De disponible realindkomster blev i dette årti omtrent fordoblet,',
        'fattigdomsandelen faldt fra omkring 29 procent (2000) til cirka 13 procent',
        '(2008). Pensioner og lønninger blev igen udbetalt til tiden — hvilket i',
        '1990\'erne langt fra havde været en selvfølge. Staten fungerede igen:',
        'Skatter blev opkrævet (indførelsen af en flad skat på 13 procent i 2001),',
        'udenlandsgælden blev betalt tilbage før tid, centralbanken opbyggede',
        'reserver. Antallet af drab og alkoholdødeligheden faldt markant, og den',
        'forventede levealder steg igen.',
        '',
        'En stor del af det hang på **olieprisen**: En tønde råolie af typen Urals',
        'kostede i 1998 omkring 12 dollars og i sommeren 2008 næsten 140. Uden denne',
        'tilstrømning havde meget ikke været muligt — og det siger også russiske',
        'økonomer. Men det var netop ikke kun olieprisen, og for de mennesker, der',
        'oplevede det, var det meget reelt. Den, der udelukkende beskriver 00\'erne i',
        'Rusland som begyndelsen på et diktatur, beskriver ikke, hvad flertallet',
        'oplevede — og forstår derfor heller ikke den tilslutning, der voksede ud',
        'af det.',
        '',
        '### Hvad der snævrede ind (2000–i dag)',
        '',
        'I samme årti og derefter forsvandt stykke for stykke det, der udgør et',
        'demokrati. Rækken er lang, og den er dokumenteret:',
        '',
        '- **Medierne.** I april 2001 overtog den statsnære Gazprom-koncern den',
        '  sidste store uafhængige tv-station NTW. De seerstærke kanaler er siden da',
        '  under statslig kontrol.',
        '- **Økonomien.** I oktober 2003 blev Michail Chodorkowski, dengang landets',
        '  rigeste mand og politisk aktiv, arresteret; hans oliekoncern Jukos blev',
        '  smadret og gik til en statskoncern.',
        '- **Føderalismen.** I 2004, efter gidseldramaet i Beslan, blev det direkte',
        '  valg af guvernører afskaffet; de blev herefter udpeget fra Moskva.',
        '- **Kritikerne.** Journalisten Anna Politkowskaja, der rapporterede om',
        '  Tjetjenien, blev skudt i Moskva den 7. oktober 2006. Den tidligere',
        '  efterretningsofficer Alexander Litwinenko døde i november 2006 i London af',
        '  forgiftning med polonium-210; en britisk undersøgelse nåede i 2016 frem',
        '  til, at drabet „sandsynligvis" var blevet godkendt på højeste niveau.',
        '  Oppositionspolitikeren Boris Nemzow blev skudt den 27. februar 2015 i',
        '  sigte af Kreml. Alexej Nawalny blev i august 2020 forgiftet med',
        '  nervegiften Nowitschok, behandlet i Berlin, vendte tilbage, blev fængslet',
        '  og døde den 16. februar 2024 i en straffelejr nord for polarcirklen.',
        '- **Retten.** Siden 2012 kan organisationer klassificeres som „udenlandske',
        '  agenter"; reglen er blevet skærpet flere gange og rammer i dag også',
        '  enkeltpersoner. I 2020 blev forfatningen ændret, så Putin kan stille op',
        '  til 2036. Siden marts 2022 straffes det med fængsel at betegne krigen som',
        '  en krig.',
        '',
        'Disse to lister står side om side, og ingen af dem ophæver den anden.',
        'Opsvinget i 00\'erne var ægte. Indsnævringen var det også. Den, der kun',
        'fortæller det ene, fortæller reklame; den, der kun fortæller det andet,',
        'fortæller en karikatur.',
        '## Krigene',
        '',
        '**Georgien, august 2008.** Striden om Sydossetien og Abkhasien var gammel. I',
        'natten til den 8. august 2008 beskød den georgiske hær Tskhinvali, russiske',
        'tropper rykkede ind og stødte langt ud over de omstridte områder frem. Den',
        'undersøgelsesrapport, som EU havde nedsat under Heidi Tagliavini, nåede i',
        '2009 frem til et ubehageligt dobbeltbefund: Det georgiske angreb havde ikke',
        'været folkeretligt forsvarligt — og den russiske reaktion var gået langt ud',
        'over, hvad der stod i rimeligt forhold til, forberedt gennem års',
        'provokationer. Denne stemme gengiver rapporten, som den er, også selv om',
        'dens første halvdel modsiger den vestlige fortælling.',
        '',
        '**Krim og Donbass, 2014.** Efter præsident Janukowytschs fald besatte',
        'soldater uden nationale kendetegn i slutningen af februar 2014 Krim; Putin',
        'bekræftede nogle uger senere, at det var russiske soldater. En',
        'folkeafstemning under besættelse den 16. marts blev ikke internationalt',
        'anerkendt; den 27. marts erklærede FN\'s Generalforsamling anneksionen for',
        'ugyldig med 100 mod 11 stemmer. Om foråret begyndte krigen i Donbass, som',
        'russisk militær var involveret i, også selv om Moskva benægtede det i',
        'årevis. Den 17. juli 2014 blev passagerflyet MH17 med 298 mennesker om bord',
        'skudt ned over Donbass; en nederlandsk domstol dømte i 2022 tre involverede',
        'in absentia. Minsk-aftalerne (september 2014 og februar 2015) frøs krigen',
        'fast uden at afslutte den; ingen af siderne gennemførte dem fuldt ud.',
        '',
        '**Den 24. februar 2022.** Den dag indledte Rusland en storstilet',
        'angrebskrig mod Ukraine — fra øst, fra syd og fra nord over hviderussisk',
        'område mod Kyiv. Det er vigtigt at kalde det præcis det og ikke sige',
        '„konflikt": En konflikt har to sider, der begynder noget; her har én side',
        'overskredet en grænse. Den 2. marts 2022 fordømte FN\'s Generalforsamling',
        'angrebet med 141 mod 5 stemmer og krævede tilbagetrækning. Fremstødet mod',
        'Kyiv mislykkedes og blev afbrudt i begyndelsen af april; i de befriede',
        'byer, blandt dem Butja, fandt efterforskere talrige dræbte civile. Den',
        'Internationale Straffedomstol udstedte i marts 2023 en arrestordre mod',
        'Putin for bortførelsen af ukrainske børn.',
        '',
        'Og den konsekvens, som ingen havde planlagt: **Finland tiltrådte NATO den',
        '4. april 2023, Sverige den 7. marts 2024.** Finland havde siden 1945 holdt',
        'fast i alliancefriheden, Sverige siden 1814. Før februar 2022 var omkring',
        '20 til 25 procent i Finland for en tiltrædelse, få uger efter over 70. NATOs',
        'landegrænse mod Rusland er dermed mere end fordoblet — præcis det, som',
        'krigen ifølge sin egen begrundelse skulle forhindre.',
        '',
        '## Det mest ubehagelige punkt: den egen målestok',
        '',
        'Dette perspektiv påberåber sig en regel — grænser ændrer man ikke med magt.',
        'Så må det sige, hvor det selv har overtrådt den.',
        '',
        '**Kosovo 1999.** NATO bombede Jugoslavien i 78 dage uden mandat fra FN\'s',
        'Sikkerhedsråd. Anledningen — fordrivelsen af den albanske befolkning — var',
        'reel; retsgrundlaget manglede. I 2008 erklærede Kosovo sin uafhængighed,',
        'som Vesten anerkendte, og Rusland ikke. Moskva har siden ført denne sag an',
        'i enhver debat, og henvisningen er ikke grebet ud af luften.',
        '',
        '**Irak 2003.** USA og dets allierede førte krig mod en stat, der ikke havde',
        'angrebet dem, uden FN-mandat og med en begrundelse — masseødelæggelsesvåben',
        '— der viste sig at være forkert. Den, der ikke nævner det, kan ikke tale',
        'troværdigt om folkeret.',
        '',
        '**Libyen 2011.** Sikkerhedsrådet tillod beskyttelsen af civilbefolkningen;',
        'militæraktionen endte med regimets fald. Rusland og Kina, der havde',
        'undladt at stemme, følte sig bedraget — og har siden ikke givet deres',
        'tilsagn i nogen sammenlignelig sag.',
        '',
        '**Og forretningen.** Tyskland fik før 2022 over halvdelen af sin naturgas',
        'fra Rusland og udbyggede med Nord Stream 1 og 2 afhængigheden yderligere —',
        'mod Polens, de baltiske staters og USA\'s udtrykkelige advarsler. „Forandring',
        'gennem handel" hed formlen. Efter 2008 og efter 2014 havde man kunnet',
        'efterprøve den. Man gjorde det ikke, fordi det ville have været dyrt. Da',
        'Putin den 10. februar 2007 holdt en tale på München-sikkerhedskonferencen,',
        'hvor han i klartekst sagde, hvordan han så den vestlige politik, blev det i',
        'Berlin og Paris betragtet som dårligt humør. Det var en meddelelse.',
        '',
        '## Hvad Vesten gør i dag — og hvad det koster',
        '',
        'Siden 2022 har USA, EU og yderligere stater støttet Ukraine med våben,',
        'penge og modtagelse af flygtninge, og de har pålagt Rusland de mest',
        'omfattende sanktioner i efterkrigstiden. NATO-soldater kæmper ikke med;',
        'alliancen har fra starten erklæret, at den ikke gør det, fordi en direkte',
        'krig mellem atommagter ville være noget andet.',
        '',
        'Også her hører modregningen med. Sanktionerne har ikke fået den russiske',
        'økonomi til at kollapse; den har, under omkostninger, omstillet sig. En stor',
        'del af verden — Indien, Kina, Brasilien, Sydafrika og de fleste afrikanske',
        'stater — er ikke med på dem og beskylder Vesten for pludselig at opdage',
        'principper her, som det ikke anvender andre steder. Denne kritik er',
        'ubehagelig, og den er ikke ubegrundet. Og i selve Europa er spørgsmålet',
        'åbent, hvor længe samfund kan bære en støtte, der koster penge og ikke har',
        'nogen synlig afslutning.',
        '',
        '## Hvad dette syn ikke kan se',
        '',
        'Det ser 1990\'erne udefra — som en overgangstid, ikke som sammenbruddet af',
        'ens egen verden. Det ser udvidelsen som summen af frie beslutninger, ikke',
        'som en linje, der rykker tættere på. Det ser den russiske fortælling som en',
        'fortælling og sin egen som en beskrivelse — og netop det er den blinde plet,',
        'som denne app advarer mod i hvert kapitel.',
        '',
        'Derfor står denne stemme ikke alene her. **Ruslands syn** — Jelzin-årene',
        'indefra, stabiliseringen, omringningen, den egen begrundelse for krigene —',
        'skriver Hermes; muligvis kommer en tredje stemme til, Ukraines, som i dette',
        'kapitel hidtil først og fremmest forekommer i stedet for at tale. Først',
        'derefter fører syntesen sammen, hvad der hører sammen.',
      ].join('\n'),
    },
    {
      id: 'russland-sicht',
      name: 'Ruslands syn — 1990\'erne og Putin',
      stimme: 'Hermes',
      text: [
        'Denne stemme fortæller fra Moskva: fra den verden, der den 25. december',
        '1991 brød sammen med Sovjetunionen, og fra det Rusland, der opstod bagefter.',
        'Den er ligeværdig med Vestens stemme — at den stod først her, var kun den',
        'rækkefølge, som der blev skrevet i.',
        '',
        '## 1990\'erne — den store ydmygelse',
        '',
        'Den, der har oplevet 1990\'erne i Rusland, husker dem som en tid med',
        'sammenbrud: Priserne steg uhæmmet, et helt livs opsparing blev værdiløs i',
        'løbet af få måneder, lønninger og pensioner udblev i månedsvis, den',
        'forventede levealder faldt, og staten syntes ikke længere at eksistere.',
        '**Hyperinflationen** i årene 1992 til 1995 åd hele befolkningens opsparing.',
        'Ind i dette tomrum trådte **oligarkerne**: få mænd, der i',
        'privatiseringsbølgen overtog landets største virksomheder for en brøkdel af',
        'deres værdi. „Chokterapien" var en vestlig anbefaling, og denne stemme',
        'siger det uden skadefryd: Vesten mente det godt og havde ingen anelse om,',
        'hvad det anrettede.',
        '',
        'I 1998 brast boblen: **rubelkrisen** — staten kunne ikke længere betale',
        'sine gæld, bankerne brød sammen, og igen mistede millioner deres opsparing.',
        'Og ind i denne tid faldt den første **tjetjenske krig** (1994–1996), en',
        'ydmygende, brutal krig, som Rusland tabte. Den, der oplevede disse år,',
        'oplevede skam. Mens Vesten fejrede 1990\'erne som „frihedens triumf",',
        'oplevede Rusland dem som et nationalt traume — det er **brudpunktet**, hvor',
        'denne stemme begynder.',
        '',
        '## Putin — genoprettelsen af orden',
        '',
        'Wladimir Putin trådte ind i denne verden i 1999/2000 — og operatørens',
        'direktiv for denne stemme lyder: **virkelig objektiv**. Derfor står begge',
        'dele her, uden dæmonisering og uden skønmaleri.',
        '',
        '**Hvad Putin gjorde for Rusland:** Han afsluttede tiden, hvor staten ikke',
        'længere fungerede. Pensionerne blev igen udbetalt og steg, lønningerne kom',
        'til tiden, **økonomien voksede** — mellem 2000 og 2008 med i gennemsnit',
        'omkring syv procent om året, båret af olieprisen, men også af en politik,',
        'der bragte tilliden til den egne valuta og til staten tilbage. Oligarkerne',
        'blev trængt tilbage, „magtens vertikal" genoprettede ordenen, den anden',
        'tjetjenske krig endte med en hård pacificering. For mange russere var Putin',
        'manden, der afsluttede 1990\'ernes ydmygelse — hans tilslutning var i årevis',
        'meget høj, og det var ikke en tvungen tilslutning, men taknemmelighed for',
        'levet stabilitet. Denne præstation er ægte, og denne stemme kalder den ved',
        'navn.',
        '',
        '**Og hvad Putin tog for det:** Medierne blev ensrettet — den uafhængige',
        'kanal NTV blev knust i 2001. Oligarkerne blev ikke kun trængt tilbage, men',
        'også eksproprieret og fængslet, hvis de gjorde modstand (Chodorkowski',
        '2003). Modstandere forsvandt: Alexander Litwinenko døde i 2006 i London af',
        'polonium, Alexej Nawalny blev i 2020 forgiftet med Nowitschok og døde i 2024',
        'i straffelejren. Valgene blev kontrolleret, oppositionen kriminaliseret,',
        'pressefriheden udslukket. Og der var krigene: **Georgien 2008**,',
        '**anneksionen af Krim** i 2014 — som også denne stemme kalder ved navn:',
        'folkeretsstridig — og det **storstilede angreb på Ukraine i 2022**, som',
        'stadig pågår. Denne side af regnskabet er lige så ægte som den første. At',
        'stille begge dele side om side uden at gøre regnskabet op er denne stemmes',
        'arbejde.',
        '',
        '## Omringningen — set fra Moskva',
        '',
        'Denne stemme må også sige, hvad Rusland selv ser som grunden til denne',
        'udvikling: **NATOs udvidelse mod øst**. James Baker havde i 1990 lovet',
        'Gorbatschow, at NATO ikke ville rykke „en tomme mod øst" — om tilsagnet var',
        'menet sådan, og hvor langt det rakte, strides man om den dag i dag. Men det,',
        'der talte fra Moskva, var resultatet: I 1999 tiltrådte Polen, Tjekkiet og',
        'Ungarn, i 2004 de baltiske stater — tidligere sovjetrepublikker. På',
        'topmødet i **Bukarest 2008** hed det, at Georgien og Ukraine ville',
        'tiltræde NATO — uden tidsplan og uden afslag. For Moskva var det en trussel',
        'ved den egen grænse: Den alliance, som man kendte som modstander fra den',
        'kolde krig, kom tættere på. Vesten ser udvidelsen som en succeshistorie om',
        'frie stater; denne stemme ser den som et tillidsbrud. Begge syn står i',
        'dette kapitel side om side — syntesen vil ikke stille dem op mod hinanden.',
        '',
        '## Den mest ubehagelige passus i denne stemme',
        '',
        'Denne stemme må indrømme, hvad den ikke kan forklare: at et folk, der',
        'havde oplevet sovjettidens undertrykkelse, så hurtigt byttede 1990\'ernes',
        'frihed ud med Putins orden. At frygten for kaos var stærkere end',
        'kærligheden til friheden — det er det russiske demokratis tragedie. Og den',
        'må indrømme, at krigen i 2022 har bragt den isolation, som Rusland selv har',
        'valgt: Økonomien faldt, de unge mænd gik eller flygtede, og et land, der',
        'frygtede Vesten, har gjort Vesten til sin fjende. Denne stemme ender ikke',
        'med en retfærdiggørelse, men med det spørgsmål, den stiller sig selv: Hvad',
        'er der blevet af et folk, der to gange i århundredet mistede sin frihed —',
        'og anden gang næsten frivilligt?',
      ].join('\n'),
    },
    {
      id: 'ukraine-sicht',
      name: 'Ukraines syn',
      stimme: 'Hermes',
      text: [
        'Denne stemme er den yngste og den mest sårbare i dette kapitel: Den',
        'fortæller fra et land, der i denne form kun har eksisteret siden 1991 — og',
        'hvis eksistens netop nu trues af en krig, mens disse linjer skrives. Den er',
        'ligeværdig med de to andre stemmer. At den taler sidst, er ingen',
        'rangorden, men forsigtighed: Denne stemme taler om mennesker, der stadig',
        'lever.',
        '',
        '## Det uafhængige Ukraine',
        '',
        'I 1991 blev Ukraine uafhængigt — Europas folkerigeste land efter Rusland,',
        'med en lang egen historie (Kijevrus, kosakkerne, hetmanatet) og et samfund,',
        'der var splittet mellem øst og vest: I øst og syd talte mange russisk, i',
        'vest var den ukrainske identitet stærkere. Den første tid af',
        'uafhængigheden var svær — økonomien brød sammen, korruptionen blomstrede,',
        'politikken svingede mellem Moskva og Bruxelles. Denne stemme fortier ikke',
        'de egne fejl: oligarkerne, de købte valg, de udeblivende reformer. Ukraine',
        'var længe ingen mønsterstat — det gør dens historie menneskelig, ikke',
        'perfekt.',
        '',
        '## To revolutioner',
        '',
        'I 2004 bragte **den Orange Revolution** hundredtusinder på gaden mod et',
        'forfalsket valg — og vandt først. I 2013/14 fulgte **Euromajdan**:',
        'Regeringen havde i sidste øjeblik kasseret en associeringsaftale med EU,',
        'folket gik på gaden, politiet skød, og til sidst flygtede præsidenten. For',
        'denne stemme var Majdan ingen sammensværgelse, men det øjeblik, hvor et',
        'land valgte: til Europa, ikke tilbage til Moskva. Mange mennesker i Ukraine',
        'havde indtil da ingen stærk holdning — Majdan tvang dem til at få en.',
        '',
        '## Anneksionen af Krim og Donbass-krigen',
        '',
        'I februar 2014 besatte soldater uden nationale kendetegn Krim — det var',
        'russiske tropper. Den folkeafstemning, der så „afgjorde" Krim „for Rusland",',
        'fandt sted under besættelse; **anneksionen var folkeretsstridig**, og det',
        'siger denne stemme uden omsvøb. I Donbass begyndte en krig, der varede',
        'indtil 2022: Separatister, støttet af Rusland, mod den ukrainske hær — over',
        '14.000 døde, midt i Europa, i otte år, mens verden så til. Denne stemme',
        'siger også, at den ukrainske regering ikke var uskyldig i østens',
        'fremmedgørelse: Sproget, symbolerne, Kyivs desinteresse i de østlige',
        'regioner var med til at forårsage splittelsen. Men den siger også: Intet af',
        'det forklarer en angrebskrig.',
        '',
        '## Den store krig siden 2022',
        '',
        'Den 24. februar 2022 overfaldt Rusland Ukraine. Planlægningen var lagt an',
        'på en hurtig sejr — hovedstaden skulle falde i løbet af dage. I stedet',
        'gjorde landet modstand: hæren, civilbefolkningen, bønderne, der slæbte',
        'tankene væk med traktorer. Millioner af mennesker flygtede — den største',
        'flugtbølge i Europa siden 1945. I Butja, i Mariupol, i utallige byer fandt',
        'man massegrave. Denne stemme kalder rædslerne ved navn: Det er',
        'krigsforbrydelser, dokumenteret af internationale organisationer. Og den',
        'siger, hvad det betyder at leve i krig: sirenerne, nætterne i kælderen,',
        'mændene ved fronten, børnene, der vokser op i udlandet. Den, der ikke har',
        'oplevet det, skal ikke lade, som om han kan forestille sig det.',
        '',
        '## Hvad denne stemme vil',
        '',
        'Denne stemme vil hverken hævn eller triumf. Den vil, at verden forstår,',
        'hvad der står på spil her: eksistensen af et land, der frit vil vælge,',
        'hvor det hører til — en ret, som Vesten anser for selvfølgelig, og som',
        'Ukraine betaler for med blod. Den ved, at det ukrainske samfund ikke er',
        'perfekt, og at freden, når den kommer, vil kræve kompromiser. Men den ender',
        'med en sætning, som den siger til sig selv igen og igen: Et land, der',
        'forsvarer sin frihed, kan måske tabe — men det har allerede tabt, hvis det',
        'holder op med at prøve.',
      ].join('\n'),
    },
  ],
  synthese: [
    'Tre stemmer, et kontinent, en krig. Denne syntese fører sammen, hvad',
    'Vesten, Rusland og Ukraine har fortalt — og den begynder med de',
    '**brudpunkter**, hvor den samme historie begyndte helt forskelligt.',
    '',
    'Det første **brudpunkt** er året 1991. Vesten fejrede Sovjetunionens',
    'sammenbrud som frihedens triumf — med rette, for det var friheden, der',
    'sejrede. Rusland oplevede de samme år som ydmygelse og kaos:',
    'hyperinflation, oligarker, rubelkrise, de tjetjenske krige. Begge dele er',
    'sandt. Den, der kun fortæller det ene, fortæller en halv historie — og har',
    'måske lagt grunden til den næste konflikt uden at opdage det.',
    '',
    'Det andet **brudpunkt** er NATOs udvidelse mod øst. Vesten så en alliance',
    'af frie stater, der bragte demokrati og sikkerhed til Østeuropa; de nye',
    'medlemmer ønskede tiltrædelsen af fri vilje. Rusland så et tillidsbrud:',
    'tilsagnet fra 1990, der lovede „ikke en tomme mod øst", og en alliance, der',
    'rykkede helt op til den egen grænse. Begge syn er dokumenteret i dette',
    'kapitel — denne syntese **gør ikke regnskabet op** over, hvem der havde mest',
    'ret. Men den siger: En sejrherre, der ydmyger den besejrede, planter den',
    'næste krig. Det er lektionen fra Versailles, og den gælder også for 1991.',
    '',
    'Det tredje **brudpunkt** er den 24. februar 2022. Her ender',
    'perspektivernes symmetri. Den russiske stemme forklarer, hvorfor krigen',
    'kom — omringningen, ydmygelsen, angsten. Men at forklare er ikke at',
    'retfærdiggøre: En angrebskrig forbliver en angrebskrig, anneksionen',
    'forbliver folkeretsstridig, og rædslerne i Butja og Mariupol er',
    'krigsforbrydelser. Det siger også den russiske stemme i dette kapitel.',
    'Ukraine forsvarer sin eksistens — det er ikke et standpunkt, det er et',
    'faktum.',
    '',
    'Det, der bliver tilbage, er spørgsmålet til fremtiden. Vesten forsømte i',
    '1991 at se, hvad der ville blive af Ruslands ydmygelse. Den, der i dag vil',
    'forstå verden, må kende begge sider — Moskvas angst og Kyivs lidelse — og',
    'alligevel klart sige, hvad der ikke kan forhandles: at ingen stat har ret',
    'til at overfalde sin nabo, og at den historie, som sejrherren skriver, ikke',
    'er hele historien. Måske er netop det svaret på dette kapitels',
    'ledespørgsmål: Hvordan allierede fra 1945 blev fjender — og hvad vi kan',
    'gøre for, at det ikke ender sådan igen.',
  ].join('\n'),

  urteil: {
    frage: 'En stat må frit vælge sine alliancer — det står i Paris-chartret, og Rusland har underskrevet det. En nabo kan alligevel føle sig truet af det. Hvordan ville du have løst dette problem, hvis du i 1997 havde siddet med ved bordet — og hvad ville du have været villig til at betale?',
    hinweis: 'Der findes ikke noget rigtigt svar her, og det er ikke ment høfligt, men alvorligt. Nogle siger: Den, der havde nægtet tiltrædelsen, ville have gjort mod Polen og de baltiske stater, hvad man gjorde i 1945 — besluttet hen over hovedet på dem af hensyn til en stormagt. Andre siger: Den, der drev udvidelsen igennem, håndhævede en ret og mistede derved et land, som man ville have haft brug for. Begge sætninger kan belægges, og ingen af dem er hele svaret. Prøv i din begrundelse, hvilken kilde du bruger, og hvem der har skrevet den.',
  },

  quiz: [
    {
      frage: 'Sætningen „ikke en tomme mod øst" fra den amerikanske udenrigsminister James Baker (9. februar 1990) — i hvilken form findes den?',
      antworten: [
        'Som en artikel i en folkeretlig traktat mellem NATO og Sovjetunionen',
        'Som en mundtlig udtalelse i en forhandlingssamtale med Gorbatschow, refereret og i dag frigivet',
        'Som en beslutning i FN\'s Generalforsamling',
      ],
      richtig: 1,
      erklaerung: 'Baker har sagt sætningen, og samtalereferatet har i årevis været offentligt tilgængeligt. En traktat om det findes der ikke — og netop derfor strides man den dag i dag: Den ene side spørger, hvad et ord uden traktat er værd, den anden, hvad en traktat uden ord er værd.',
    },
    {
      frage: 'Hvad siger artikel 6 i To-plus-fire-aftalen af 12. september 1990 om alliancer?',
      antworten: [
        'At det forenede Tyskland ikke må tilhøre nogen alliance',
        'At det forenede Tysklands ret til at tilhøre alliancer ikke berøres af traktaten',
        'At NATO ikke må optage nye medlemmer',
      ],
      richtig: 1,
      erklaerung: 'Artikel 6 lader udtrykkeligt alliancemedlemskabet være uberørt — traktaten forbyder altså hverken Tysklands NATO-medlemskab eller optagelsen af andre stater. Om andre lande står der intet i den, fordi andre lande ikke var dens genstand. Artikel 5 begrænser til gengæld, hvad der må stationeres på det tidligere DDR\'s område.',
    },
    {
      frage: 'Hvilke tre stater var de første til efter den kolde krig at tiltræde NATO den 12. marts 1999?',
      antworten: [
        'Estland, Letland og Litauen',
        'Polen, Tjekkiet og Ungarn',
        'Finland, Sverige og Østrig',
      ],
      richtig: 1,
      erklaerung: 'Polen, Tjekkiet og Ungarn begyndte i 1999. Estland, Letland og Litauen kom til i 2004 sammen med fire andre stater, Finland i 2023 og Sverige i 2024. Østrig er den dag i dag ikke medlem.',
    },
    {
      frage: 'Hvordan udviklede den russiske økonomi sig i de to årtier efter 1991?',
      antworten: [
        'Den voksede uafbrudt fra 1991 til 2008',
        'Den faldt frem til 1998 med omkring 40 procent og voksede derefter frem til 2008 med i gennemsnit omkring syv procent om året',
        'Den forblev nogenlunde uændret gennem begge årtier',
      ],
      richtig: 1,
      erklaerung: 'Først sammenbruddet — med hyperinflation i 1992 og statsbankerotten den 17. august 1998 —, så opsvinget i 00\'erne, båret også af olieprisen: En tønde Urals kostede i 1998 omkring 12 dollars og i 2008 næsten 140. Begge halvdele hører sammen, hvis man vil forstå, hvordan mennesker oplevede disse år.',
    },
    {
      frage: 'Hvad skete der med Finland og Sverige efter det russiske angreb på Ukraine den 24. februar 2022?',
      antworten: [
        'Begge erklærede deres permanente neutralitet',
        'Begge tiltrådte NATO — Finland 2023, Sverige 2024',
        'Begge meldte sig ud af Den Europæiske Union',
      ],
      richtig: 1,
      erklaerung: 'Finland havde siden 1945 holdt fast i alliancefriheden, Sverige siden 1814. I Finland steg tilslutningen til tiltrædelsen i løbet af uger fra omkring en femtedel til over to tredjedele. Dermed er NATOs landegrænse mod Rusland mere end fordoblet.',
    },
  ],

  karteHinweise: [
    {
      label: '1999 — den første udvidelse mod øst',
      hinweis: [
        'Otte år efter Sovjetunionens ophør tiltræder Polen, Tjekkiet og Ungarn',
        'NATO (12. marts 1999). Rusland er skrumpet, men det er ingen modstander:',
        'I 1997 har Moskva og Bruxelles underskrevet NATO-Rusland-grundakten. USA og',
        'Canada, de to største medlemmer, ligger uden for dette udsnit.',
      ].join(' '),
    },
    {
      label: '2014 — Krim og Donbass',
      hinweis: [
        'To yderligere udvidelser ligger imellem: I 2004 kom Estland, Letland,',
        'Litauen, Slovakiet, Slovenien, Rumænien og Bulgarien til, i 2009 Albanien',
        'og Kroatien. Siden 2004 har NATO haft en landegrænse til Rusland. I marts',
        '2014 annekterer Rusland Krim, og om foråret begynder krigen i Donbass.',
      ].join(' '),
    },
    {
      label: '2022–2024 — angrebskrigen og den nordiske udvidelse',
      hinweis: [
        'Den 24. februar 2022 angriber Rusland Ukraine for fuld styrke. Fronten på',
        'dette kort er en tilnærmet status fra 2024, ingen fast tilstand. Og det',
        'viser en konsekvens, som ingen i Moskva havde planlagt: Finland (2023) og',
        'Sverige (2024) opgiver deres årtier lange alliancefrihed og tiltræder NATO.',
      ].join(' '),
    },
  ],
};
