// Tema: Weimarrepublikken og vejen ind i diktaturet (1918–1933) — dansk
// oversættelse af utils/themen/weimar-ns.js (Runde 18, begge stemmer: Opus
// og Hermes).
//
// Struktur og indhold svarer 1:1 til den tyske original: alle perspektiver,
// syntesen, dommen, quizzen og korthinweisene (fra karten/weimar-ns.js).
// Feltnavnene er bibeholdt på tysk (perspektiven, aufhaenger, karteHinweise
// osv.) ligesom i skemaet; kun teksterne er oversat.
//
// Rene data — ingen UI-imports (arkitekturregel).

module.exports = {
  id: 'weimar-ns',
  titel: 'Weimarrepublikken og vejen ind i diktaturet',
  epoche: '1918–1933',

  aufhaenger: {
    frage: 'Det første tyske demokrati var fjorten år gammelt, da det døde — afskaffet ikke af en fremmed hær, men indefra, i vid udstrækning i overensstemmelse med sin egen forfatnings former. Hvordan ødelægger man et demokrati uden at erobre det?',
    text: [
      'I november 1918 gik et kejserrige under, der havde ført og tabt fire års',
      'krig. Det, der kom i stedet for det, var det første demokrati på tysk',
      'grund: almindelig valgret for mænd og kvinder, grundrettigheder, en frit',
      'valgt rigsdag. I årene derefter blev Berlin en af verdens mest',
      'spændende byer, tyske forskere samlede nobelpriser, Bauhaus opfandt de',
      'former, vi bor i den dag i dag, og i biografen kørte „Metropolis".',
      '',
      'Fjorten år senere var der intet tilbage af det. Den 30. januar 1933',
      'udnævnte rigspræsidenten en mand til kansler, hvis parti aldrig havde',
      'vundet et flertal; otte uger senere havde rigsdagen frataget sig selv',
      'magten. Imellem ligger en tabt krig, en inflation, der gjorde',
      'opsparing til papir, seks millioner arbejdsløse — og en kæde af',
      'beslutninger, som mennesker har truffet, ingen naturlove.',
      '',
      'Dette kapitel fortæller derfor ikke historien som skæbne, men som en',
      'følge af skilleveje. Og det fortæller den fra mere end én retning: Den,',
      'der bygger et demokrati, ser noget andet end den, som det ikke har',
      'beskyttet. Kortet viser samtidig noget mærkeligt — mellem 1919 og 1933',
      'ændrer næsten intet sig ved landets grænser. Det, der ændrede sig, stod',
      'ikke på landkortet.',
    ].join('\n'),
  },

  perspektiven: [
    {
      id: 'republik-sicht',
      name: 'Synet hos dem, der byggede og forsvarede republikken',
      stimme: 'Opus',
      text: [
        'Denne stemme fortæller fra republikkens midte: fra rigskancelliets',
        'kontorer, fra nationalforsamlingens mødesale, fra redaktionerne på de',
        'demokratiske aviser, fra fagforeningshusene og fra kontorerne hos de',
        'embedsmænd og dommere, der tjente den nye stat. Det er stemmen fra',
        'socialdemokraterne omkring Friedrich Ebert, forfatningsfædrene og',
        '-mødrene i Weimar, centrum-katolikkerne, de liberale — den „Weimar-',
        'koalition", der byggede dette demokrati og ville forsvare det til det',
        'sidste mod fjender fra højre og venstre.',
        '',
        'Den er ligeværdig med kapitlet anden stemme — synet hos de forfulgte',
        'og retsløse. At den her står først, er ingen rangorden, men blot den',
        'rækkefølge, der blev skrevet i.',
        '',
        'Og den har en fordel og en blind plet, som man bør kende, før man',
        'lytter til den. Fordelen: Den var til stede, da der blev besluttet,',
        'og kan sige, hvad de involverede vidste og frygtede i det øjeblik —',
        'ikke det, vi ved i dag. Den blinde plet: Denne stemme har en',
        'interesse i at få sine egne fejl til at se små ud. Derfor nævner den',
        'dem her udtrykkeligt selv i stedet for at overlade dem til',
        'modstemmen. Den hårdeste sandhed i dette kapitel lyder: Republiken er',
        'ikke kun gået under på sine fjender, men også på sine vogtere.',
        '',
        '## November 1918: en republik ud af et nederlag',
        '',
        'I slutningen af september 1918 meddelte den øverste hærledelse —',
        'general Erich Ludendorff og generalfeltmarskal Paul von Hindenburg —',
        'kejseren, at krigen var tabt militært; man måtte straks bede om en',
        'våbenstilstand. Fire år havde den samme hærledelse reelt regeret',
        'landet og lovet befolkningen sejren. Nu skulle en parlamentarisk',
        'regering føre forhandlingerne. Nogle historikere kalder det',
        '„revolutionen ovenfra": Demokratiet kom til Tyskland i det øjeblik,',
        'hvor der var noget at tabe — og de, der havde ført krigen, trådte til',
        'side.',
        '',
        'Det, der så kom, kom nedefra. Den 29. oktober 1918 nægtede matroserne',
        'på højsøflåden i Wilhelmshaven at adlyde ordren til et sidste,',
        'meningsløst slag. Fra oprøret i Kiel den 3. og 4. november blev der',
        'inden for en uge en revolution: I Hamborg, Bremen, Hannover, München',
        'og til sidst i Berlin overtog arbejder- og soldaterrådene magten —',
        'næsten overalt uden blodsudgydelser. Den 9. november 1918 abdicerede',
        'Wilhelm II., rigskansler Max von Baden overdrog embedet til',
        'socialdemokraten Friedrich Ebert, og Philipp Scheidemann udråbte',
        'republikken fra rigsdagen. To timer senere udråbte Karl Liebknecht',
        'fra byslottet den „frie socialistiske republik". To republikker på én',
        'dag — i det lå allerede den strid, der skulle præge de næste fjorten',
        'år.',
        '',
        'Den 11. november 1918 underskrev en civil delegation under',
        'centrumpolitikeren Matthias Erzberger våbenstilstanden i Compiègne.',
        'De generaler, der havde ført krigen, holdt sig væk fra denne',
        'underskrift. Det var en af de mest skæbnesvangre sporskifter i tysk',
        'historie — men det vidste ingen dengang.',
        '',
        '## Det eget ubekvemme sted: forbundet med den gamle hær',
        '',
        'I natten til den 10. november 1918 telefonerede general Wilhelm',
        'Groener med Friedrich Ebert. Hærledelsen tilbød den nye regering sin',
        'støtte mod et muligt kup efter russisk forbillede; Ebert sagde ja til',
        'at lade officerernes militære kommandobeføjelse forblive urørt.',
        'Denne Ebert-Groener-pagt reddede republikken i de første uger',
        'formentlig fra borgerkrig. Den kom den på lang sigt til at stå dyrt.',
        '',
        'For republikken lod dermed kejserrigets magtapparater i vid',
        'udstrækning forblive urørt: officerskorpset, forvaltningen,',
        'retsvæsenet, universiteterne. Da januaropstanden brød ud i Berlin i',
        'begyndelsen af 1919, lod den socialdemokratiske folkebefuldmægtigede',
        'Gustav Noske frikorpsene sætte ind mod oprørerne — frivillige',
        'forbandt af frontsoldater, hvis officerer foragtede republikken.',
        '„En må blive blodhunden", har Noske sagt; han citerede det senere',
        'selv. Rosa Luxemburg og Karl Liebknecht blev den 15. januar 1919',
        'myrdet af frikorps-officerer, deres mordere slap med latterlige',
        'straffe. I München skød frikorps i maj 1919 over tusind mennesker,',
        'mange af dem uden rettergang.',
        '',
        'Denne stemme kan ikke bortforklare det, og den forsøger det ikke. SPD\'s',
        'ledelse stod over for en ægte beslutning — den frygtede borgerkrig,',
        'sult og et diktatur efter forbillede fra Rusland, og den havde intet',
        'loyalt magtinstrument ud over den gamle hær. Men regnestykket gik',
        'ikke op: De samme frikorps, der i 1919 skulle redde republikken,',
        'marcherede i 1920 under Kapp-kuppet imod den. Og arbejderbevægelsen',
        'var for resten af republikkens levetid splittet — i et',
        'socialdemokrati, der bar staten, og en venstrefløj, der anså den for',
        'forræderi. Dette sår er aldrig helet, og i 1933 var det dødbringende.',
        '',
        '## Weimar 1919: forfatningen',
        '',
        'Den 19. januar 1919 blev nationalforsamlingen valgt — det første valg',
        'i Tyskland, hvor kvinder måtte vælge og vælges. 82 procent af de',
        'stemmeberettigede mødte op; 37 kvinder kom ind i parlamentet.',
        'Weimar-koalitionen af SPD, Centrum og det liberale DDP fik tilsammen',
        'over tre fjerdedele af stemmerne. Der blev mødtes i Weimar, fordi der',
        'blev skudt i Berlin — og fordi navnet på Goethes by skulle give den',
        'nye stat et andet ansigt end kasernernes.',
        '',
        'Det, der blev udfærdiget den 11. august 1919, var for sin tid en',
        'ekstraordinær tekst. „Statsmagten udgår fra folket", hedder det i',
        'artikel 1. Der var grundrettigheder, ligestilling mellem kønnene i',
        'princippet, religionsfrihed, ytringsfrihed, valgret fra 20 år,',
        'virksomhedsråd, ottetimersdagen som mål, socialforsikring. Kvinder',
        'kunne studere og blive dommere. Mens kvinder i Frankrig og Italien i',
        '1919 stadig ikke måtte stemme, stemte millioner i Tyskland.',
        '',
        'Denne stemme nævner selv forfatningens svagheder, fordi den er',
        'medansvarlig for dem:',
        '',
        '- **Artikel 48** gav rigspræsidenten ret til ved „væsentlig',
        '  forstyrrelse af den offentlige sikkerhed og orden" at regere med',
        '  nødforordninger og sætte grundrettigheder ud af kraft. Den var',
        '  tænkt som ildslukker til undtagelsestilfældet. Bygget var den som en',
        '  anden, stille vej til magten — og fra 1930 blev netop denne vej til',
        '  normalen.',
        '- **Den direkte valgte rigspræsident** skulle være en modvægt til',
        '  parlamentet, en „erstatningskejser", som spøgefugle sagde. Han',
        '  udnævnte og afskedigede kansleren og kunne opløse rigsdagen. Den,',
        '  der havde dette embede, besluttede dermed over meget.',
        '- **Den rene forholdstalsvalgret uden spærregrænse** afspejlede enhver',
        '  stemning præcist — og splintrede parlamentet. I de sidste år sad',
        '  over et dusin partier i rigsdagen; en regeringsdannelse blev til en',
        '  regneopgave.',
        '- **Folkeinitiativ og folkeafstemning** var tænkt som deltagelse og',
        '  blev til modstandernes værktøj: I 1929 gjorde initiativet mod',
        '  Young-planen en hidtil ukendt partileder ved navn Adolf Hitler for',
        '  første gang kendt i hele riget, fordi kampagnen kørte gennem',
        '  mediemagnaten Alfred Hugenbergs aviser.',
        '',
        'Ingen af disse svagheder behøvede at føre til katastrofen. Alle',
        'tilsammen gav en forfatning, der ikke bremsede en beslutsom præsident',
        'og et blokeret parlament, men accelererede dem.',
        '',
        '## Versailles og dolkestødslegenden',
        '',
        'Den 28. juni 1919 underskrev den tyske delegation i Versailles',
        'fredstraktaten. Den kostede riget omkring en syvendedel af dets',
        'område og en tiendedel af dets befolkning: Alsace-Lorraine til',
        'Frankrig, Eupen og Malmedy til Belgien, Nordslesvig efter en',
        'folkeafstemning til Danmark, Posen og Vestpreussen til det',
        'nyopståede Polen, en del af Øvreschlesien ligeledes efter',
        'afstemningen i 1921; Danzig blev fristad, Memelområdet blev afskilt,',
        'Saarområdet blev for femten år underlagt Folkeforbundet, alle',
        'kolonier gik tabt. Dertil reparationer, en hær på 100 000 mand, det',
        'besatte og afmilitariserede Rhinland — og artikel 231, der tillagde',
        'Tyskland og dets allierede ansvaret for alle krigsskader.',
        '',
        'Næsten alle tyskere opfattede denne traktat som et diktat, og den',
        'regering, der måtte underskrive den, har selv kaldt den sådan. Det',
        'hører med til denne stemmes ærlighed at stille modregningen ved siden',
        'af: Brest-Litovsk-traktaten, som kejserriget i 1918 pålagde det',
        'besejrede Rusland, var langt hårdere — og i Frankrig, hvis nord lå i',
        'ruiner, fandt mange Versailles for mild. Den, der ved det, forstår',
        'bedre, hvorfor sejrherrerne ikke gav efter, og vil alligevel ikke',
        'finde harmen fra 1919 tåbelig.',
        '',
        'Det, der gjorde størst skade, var ikke traktaten, men en fortælling',
        'om den. Allerede i efteråret 1919 sagde Hindenburg for en',
        'parlamentarisk undersøgelseskommission, at den tyske hær var blevet',
        '„stukket dolken i ryggen bagfra". Dolkestødslegenden hævdede: Ikke',
        'ved fronten var krigen tabt, men i hjemlandet, af socialdemokrater,',
        'jøder og demokrater — „novemberforbryderne". Den var beviseligt',
        'forkert; hærledelsen selv havde i september 1918 indrømmet nederlaget.',
        'Og den var uhyre virkningsfuld, fordi den netop kom fra de to mænd,',
        'som mange tyskere troede på. Den, der troede på denne legende, kunne',
        'kun se republikken som resultatet af et forræderi. Matthias',
        'Erzberger, der havde underskrevet våbenstilstanden, blev myrdet i',
        '1921; udenrigsminister Walther Rathenau, der førte',
        'opfyldelsespolitikken, i 1922. De yderste højrefløj sang spotteviser',
        'dertil.',
        '',
        '## 1923: året, hvor alt skete på samme tid',
        '',
        'Inflationen begyndte ikke i 1923, men i 1914. Kejserriget havde ikke',
        'finansieret krigen gennem skatter, men gennem krigsobligationer — i',
        'forventning om, at de besejrede til sidst ville betale. Krigen gik',
        'tabt, regningen blev tilbage. Da riget kom i restance med',
        'reparationsleverancerne, besatte franske og belgiske tropper den 11.',
        'januar 1923 Ruhr-området. Rigsregeringen udråbte den „passive',
        'modstand" — strejke i hele distriktet — og betalte lønningene for den',
        'med nyprintede penge. Dermed styrtede forringelsen i frit fald. En',
        'dollar kostede i januar 1923 omkring 18 000 mark, i november over',
        'fire billioner.',
        '',
        'Den, der ejede reale værdier, kom igennem. Den, der havde sparet op',
        '— embedsmænd, pensionister, små håndværkere, hele middelstanden —,',
        'mistede på få måneder sikkerheden i et liv. Denne erfaring har',
        'kostet republikken dyrere end enhver reparationsrate: Millioner af',
        'mennesker lærte, at flid og sparsommelighed ikke nyttede noget, og',
        'mange gav ikke krigsfinansieringen fra 1914 ansvaret, men den stat,',
        'der stod der i 1923.',
        '',
        'I august 1923 overtog Gustav Stresemann regeringen. Han gjorde det',
        'mest upopulære, der var muligt: Han brød den passive modstand af,',
        'fordi riget ikke længere kunne betale den. I november kom',
        'rentenmarken, og valutaen stod igen. Samme år måtte republikken',
        'overstå et kommunistisk oprørsforsøg i Hamborg, en rådsregering i',
        'Sachsen og Thüringen og den 8./9. november Adolf Hitlers kupforsøg i',
        'München. Den overstod alle tre. At den overstod dem, bestyrkede',
        'dengang mange i troen på, at det værste var overstået.',
        '',
        '## Retssystemet: blind på det højre øje',
        '',
        'Også dette hører til de steder, som denne stemme selv må nævne,',
        'fordi det vedrører dens egne embedsstuer. Republikkens dommere var de',
        'samme som kejserrigets, udnævnt på livstid og i flertal utilbøjelige',
        'over for den nye orden. Statistikeren Emil Julius Gumbel talte for',
        '1919 til 1922 mere end 300 politiske mord fra højre, som i',
        'gennemsnit blev straffet med få måneders fængsel, og godt to dusin fra',
        'venstre, for hvilke der faldt talrige dødsdomme. Hitler fik i 1924',
        'lov til at bruge sin højforræderiproces som scene og kom efter ni',
        'måneders fæstningsarrest fri.',
        '',
        'Et demokrati, der behandler sine fjender ulige, afvæbner sig selv.',
        'Republikken kunne have ændret det — den kunne have forflyttet',
        'dommere, undersøgt embedsmænd, bygget rigswehrren op på ny. Den',
        'gjorde det ikke, af hensyn til den indre fred og af respekt for',
        'retsvæsenets uafhængighed. Respekten var ærefuld. Prisen var høj.',
        '',
        '## De gyldne år 1924–1929 — og fejltagelsen i dem',
        '',
        'I fem år så det ud, som om republikken havde vundet. Dawes-planen fra',
        '1924 ordnede reparationerne på ny, amerikanske penge strømmede til',
        'Tyskland, produktionen overhalede i 1927 igen førkrigsniveauet.',
        'Gustav Stresemann, efterhånden udenrigsminister, indgik i 1925',
        'Locarno-traktaterne, hvor Tyskland, Frankrig og Belgien anerkendte',
        'deres fælles grænser; i 1926 trådte Tyskland ind i Folkeforbundet,',
        'samme år modtog Stresemann og hans franske kollega Aristide Briand',
        'Nobels fredspris. Köln-zonen i det besatte Rhinland blev i 1926',
        'rømmet, hele Rhinlandet i 1930 — fem år tidligere end fastsat i',
        'traktaten. At forhandle bragte mere end trods; det var lærdommen fra',
        'disse år.',
        '',
        'Og det var år, hvor dette land var mere interessant for verden end',
        'nogensinde før. Bauhaus i Weimar og Dessau, Fritz Langs „Metropolis",',
        'Treøresoperaen, Berliner-kabareten, Thomas Mann og Alfred Döblin,',
        'Albert Einstein, Max Planck, Werner Heisenberg. Kvinder med kort hår,',
        'egen konto og eget erhverv. For første gang valgte tyskerne i 1925 en',
        'rigspræsident direkte — og valgte Paul von Hindenburg, monarkiets',
        'feltmarskal. Også det hører til de gyldne år: Republiken fungerede,',
        'men den var ikke elsket.',
        '',
        'Fejltagelsen i disse år var troen på, at faren var forbi. NSDAP fik',
        'ved rigsdagsvalget i 1928 2,6 procent. Den, der tog partiet alvorligt',
        'dengang, gjaldt som hysterisk. Opsvinget stod på kortfristede',
        'amerikanske kreditter; i oktober 1929 brød New York-børsen sammen, og',
        'samme måned døde Stresemann, 51 år gammel. Republikken mistede sin',
        'dygtigste politiker i det øjeblik, hvor den havde mest brug for ham.',
        '',
        '## Fra 1930: demokratiet tømmes indefra af sine vogtere',
        '',
        'Her ligger det ubekvemmeste sted i hele denne fortælling, og det',
        'tilhører ikke republikkens modstandere, men dens forvaltere.',
        '',
        'I marts 1930 brød den sidste parlamentariske regering i republikken',
        'sammen over et spørgsmål om arbejdsløshedsforsikringen — over et',
        'halvt procentpoint i bidrag. Rigspræsident Hindenburg udnævnte',
        'Heinrich Brüning fra Centrum til kansler, uden at denne havde et',
        'flertal. Da rigsdagen i juli 1930 afviste Brünings sparepakke, satte',
        'han den i kraft ved nødforordning efter artikel 48 — og lod, da',
        'rigsdagen krævede den ophævet, parlamentet opløse. Fra da af blev der',
        'regeret, uden at et flertal samtykkede: I 1930 var der fem',
        'nødforordninger og 94 rigsdagssamlinger, i 1932 var der 66',
        'nødforordninger og 13 samlinger. Parlamentet trådte næsten ikke',
        'længere sammen.',
        '',
        'To ting ved det var skæbnesvangre. For det første selve politikken:',
        'Brüning sparede sig midt ind i verdenskrisen — løn, gager og',
        'understøttelse blev skåret ned ved forordning, mens arbejdsløsheden',
        'steg fra tre millioner (1930) til over seks millioner (begyndelsen af',
        '1932). Han gjorde det af forståelige grunde: Han ville bevise, at',
        'reparationerne ikke kunne betales, og han frygtede efter 1923 ikke',
        'noget så meget som en ny inflation. Resultatet var alligevel, at',
        'millioner af mennesker forbandt demokratiet med nød.',
        '',
        'For det andet formen: Nyvalget i september 1930 gjorde NSDAP med 18,3',
        'procent til det næststærkeste parti. Den rigsdag, som Brüning havde',
        'ladet opløse for at blive friere, var derefter mere uregerlig end',
        'før. Og tilvænningen var der. Den, der har vænnet sig til i tre år,',
        'at love kommer fra rigspræsidentens palæ i stedet for fra',
        'parlamentet, vil i 1933 ikke bemærke noget nyt. Nødforordningerne',
        'blev besluttet for at redde republikken. De lagde instrumenterne',
        'klar, med hvilke den blev afskaffet. Det er ingen bebrejdelse',
        'bagefter — socialdemokrater og liberale sagde det dengang.',
        '',
        '## Undervurderingen: „vi har engageret ham"',
        '',
        'Næsten ingen i den republikanske lejr holdt Hitler for det, han var.',
        'Nogle så en skrigehals fra München, hvis bevægelse ville slides op af',
        'regeringsansvaret. De andre holdt ham for et værktøj, som man kunne',
        'bruge og så lægge til side. Fra Franz von Papen er sætningen',
        'overleveret, at man havde „engageret" Hitler — om to måneder ville',
        'man have presset ham så meget op i en krog, at han peb. Hindenburg',
        'kaldte ham ringeadt den „bøhmiske korporal" og udnævnte ham alligevel.',
        '',
        'Dertil kom uenigheden hos dem, der burde have forsvaret republikken —',
        'det andet store ubekvemme sted for denne stemme. SPD støttede',
        'Brüning for at forhindre værre ting og mistede derved vælgere til',
        'kommunisterne. KPD bekæmpede socialdemokraterne som',
        '„socialfascister" og så i nationalsocialisterne et overgangsfænomen,',
        'hvorefter man selv kom til turen. I Preussen, rigets største land,',
        'havde en stabil republikansk koalition regeret i årevis under',
        'socialdemokraten Otto Braun — indtil Papen den 20. juli 1932 med en',
        'nødforordning afsatte hele den preussiske regering og gjorde sig',
        'selv til rigskommissær. Denne regering havde politiet i det største',
        'tyske land bag sig. Den ydede ingen modstand, men indbragte sagen for',
        'Reichsgericht i Leipzig. Dommen i oktober 1932 faldt halvt ud,',
        'afsættelsen bestod.',
        '',
        'Man kan forstå beslutningen: Borgerkrig mod rigswehrren, med seks',
        'millioner arbejdsløse i ryggen, ville formentlig heller ikke have',
        'reddet republikken. Men den dag gav landets stærkeste republikanske',
        'magtposition efter uden kamp, og alle så det. Seks måneder senere var',
        'Hitler kansler.',
        '',
        '## Hvorfor mennesker valgte republikkens modstandere',
        '',
        'Denne stemme kommer ikke uden om at gengive de andre siders',
        'bevæggrunde fair — ellers forklarer den til sidst intet.',
        '',
        '**Kommunisterne** havde en grund til deres mistillid, som man ikke',
        'kan diskutere væk: I 1919 havde en socialdemokratisk regering ladet',
        'frikorps skyde på arbejdere, og morderne på Rosa Luxemburg var',
        'forblevet ustraffede. Den, der havde oplevet det, troede ikke længere',
        'på et ord fra SPD. At KPD deraf lavede tesen om „socialfascismen" og',
        'søgte hovedfjenden til venstre i stedet for til højre, var en',
        'skæbnesvanger fejl — men den voksede på en reel jord, som',
        'socialdemokratiet selv havde været med til at skabe.',
        '',
        '**De konservative** havde ikke ønsket republikken. For mange af dem',
        'var det parlamentariske demokrati en vestlig import, „utysk", en',
        'tilstand af strid, hvor der skulle være autoritet. De kom fra en',
        'stat, hvor kejseren regerede og embedsmænd tjente, og de frygtede',
        'bolsjevismen som en naturkatastrofe. Deres mål var for det meste',
        'ikke diktaturet hos en Adolf Hitler, men en autoritær orden uden',
        'partier — og netop derfor holdt de ham for brugbar. De tog fejl i et',
        'omfang, for hvilket der findes få sammenligninger.',
        '',
        'Og **NSDAP\'s vælgere**: I 1930 og 1932 stemte millioner af mennesker',
        'på et parti, der aldrig havde gjort en hemmelighed ud af sin foragt',
        'for demokratiet. Mange af dem havde tabt krigen, mistet opsparingen i',
        'inflationen og derefter arbejdet; de oplevede Versailles som en',
        'ydmygelse og republikken som en række af regeringer, der ikke',
        'bedrede deres situation. NSDAP lovede arbejde, orden, stolthed og en',
        'skyldig for alt. Den, der vil forstå, hvorfor det trak, må tage',
        'disse erfaringer alvorligt.',
        '',
        'At tage alvorligt betyder dog ikke at forskønne. Det, dette parti',
        'ville, stod åbent fra begyndelsen: i partiprogrammet fra 1920, der',
        'frakendte jøder statsborgerskabet, i „Mein Kampf", i talerne, i',
        'SA\'s vold på gaderne. Ingen behøvede i 1932 at gætte, hvad der ville',
        'komme, hvis disse folk fik staten. Nød forklarer en valgbeslutning;',
        'den retfærdiggør ikke, hvad der fulgte af den.',
        '',
        '## 1932/33: de sidste måneder',
        '',
        'I foråret 1932 blev Hindenburg genvalgt — med stemmer fra netop',
        'socialdemokraterne, der havde bekæmpet ham i 1925, fordi han nu',
        'gjaldt som det mindre onde mod Hitler. Få uger senere afskedigede han',
        'Brüning og gjorde Franz von Papen til kansler, en mand uden',
        'opbakning i rigsdagen. Papen afsatte den preussiske regering, lod',
        'rigsdagen opløse — og NSDAP blev i juli 1932 med 37,4 procent det',
        'stærkeste parti. Ved det næste valg i november faldt den igen til',
        '33,1 procent; partiet sad i pengeknibe, og nogle i dets ledelse',
        'holdt højdepunktet for overskredet. Et flertal har NSDAP aldrig',
        'opnået ved et frit valg.',
        '',
        'Det, der derefter skete, skete ikke ved valgurnen, men i baglokaler.',
        'General Kurt von Schleicher blev kansler og fejlede inden for otte',
        'uger. Papen, krænket og opsat på at vende tilbage, mødtes den 4.',
        'januar 1933 i huset hos en kölsk bankier med Hitler og aftalte en',
        'regering, hvor Hitler skulle være kansler — flankeret af',
        'konservative ministre, der skulle holde ham i skak. Den 30. januar',
        '1933 udnævnte Hindenburg ham til rigskansler. I dette kabinet sad ud',
        'over Hitler kun to yderligere nationalsocialister. Regnestykket gik',
        'op på fire uger — for den anden side.',
        '',
        'Den 27. februar 1933 brændte rigsdagen. Allerede dagen efter',
        'underskrev Hindenburg „forordningen til beskyttelse af folk og stat",',
        'der satte grundrettighederne i Weimar-forfatningen ud af kraft —',
        'støttet på artikel 48, den samme bestemmelse, som der havde været',
        'regeret med i tre år. Tusindvis af politiske modstandere blev',
        'anholdt. Valget den 5. marts fandt sted under disse betingelser;',
        'NSDAP fik 43,9 procent, et flertal først sammen med sin',
        'koalitionspartner.',
        '',
        'Den 23. marts 1933 stemte rigsdagen i Kroll-operaen om',
        'bemyndigelsesloven, der overførte lovgivningen til regeringen. KPD\'s',
        'medlemmer var anholdt eller på flugt, SA-mænd stod i salen. 94',
        'socialdemokrater stemte imod; deres formand Otto Wels holdt den',
        'sidste frie tale i det tyske parlament: „Frihed og liv kan man tage',
        'fra os, æren ikke." Alle andre partier samtykkede, også Centrum,',
        'der havde været med til at grundlægge republikken. Dermed var det',
        'første tyske demokrati afsluttet — ikke af en fremmed hær, men i',
        'sine egne former.',
        '',
        '## Hvad denne stemme til sidst kan sige — og hvad ikke',
        '',
        'Den kan sige, at denne republik var bedre end sit rygte: Den lavede',
        'af et nederlag en forfatning, overstod inflationen, forligede sig med',
        'sine krigsmodstandere og frembragte på fjorten år en kultur, som',
        'verden den dag i dag lever af. Den kan sige, at dens forsvarere ikke',
        'var kujoner: Generalstrejken mod Kapp-kuppet i 1920 kom fra',
        'fagforeningerne, Reichsbanner mobiliserede hundredtusinder, de 94',
        'nej-stemmer den 23. marts 1933 blev afgivet af mennesker, der vidste,',
        'hvad der ventede dem.',
        '',
        'Og den må sige, hvad den selv fejlede på: på forbundet med de gamle',
        'magter fra 1918, der lod republikkens fjender blive i deres embeder;',
        'på et retsvæsen, den ikke rørte ved; på en splittelse af',
        'arbejderbevægelsen, som den var medskyldig i; på viljen til fra 1930',
        'at regere uden parlament, fordi det var bekvemmere; på vægringen i',
        'juli 1932 at forsvare sin egen magtposition; og på en selvsikkerhed,',
        'der ikke tog en mand alvorligt, som i årevis offentligt havde',
        'annonceret, hvad han ville gøre.',
        '',
        '## Og den anden side?',
        '',
        'Det, denne stemme ikke kan fortælle, er, hvordan det hele føltes',
        'nedefra — for dem, der skulle beskyttes af republikken og ikke blev',
        'det, og for dem, for hvem 1933 ikke var slutningen på en statsform,',
        'men begyndelsen på forfølgelsen. Jødiske tyskere, hvis ligestilling',
        'siden 1919 stod i forfatningsteksten, mens hetzen på gaden var',
        'hverdag. Kommunister, hvis kammerater blev skudt af frikorps i 1919,',
        'og som fra februar 1933 kom først i lejrene. Socialdemokrater og',
        'fagforeningsfolk, hvis huse blev besat i maj 1933. Arbejdsløse, hvis',
        'understøttelse nødforordninger skar ned. Mennesker i kanten, som',
        'intet parti repræsenterede.',
        '',
        'Kapitlet anden stemme — synet hos de forfulgte og retsløse — er',
        'ligeværdig med denne her. Uden den forblev svaret på spørgsmålet i',
        'indledningen en halv. Først begge tilsammen giver billedet: et',
        'demokrati, som dets bygfolk mente oprigtigt, og som dets bygfolk',
        'selv var med til at beskadige — og mennesker, for hvem forskellen',
        'mellem et beskadiget demokrati og intet demokrati afgjorde liv og',
        'død.',
      ].join('\n'),
    },
    {
      id: 'verfolgte-sicht',
      name: 'Synet hos de forfulgte og retsløse',
      stimme: 'Hermes',
      text: [
        'Denne stemme fortæller ikke fra kabinetterne, men nedefra — fra',
        'gaderne, baggårdene, boligerne, partikontorerne, synagogerne og',
        'fagforeningshusene. Det er stemmen hos dem, som diktaturet ramte',
        'først: de jødiske tyskere, hvis ligestilling siden 1919 stod i',
        'forfatningsteksten, mens hetzen på gaden var hverdag; kommunisterne,',
        'hvis kammerater allerede i 1919 var blevet skudt af frikorps, og som',
        'fra februar 1933 kom først i lejrene; socialdemokraterne og',
        'fagforeningsfolkene, hvis huse blev besat i maj 1933; de arbejdsløse,',
        'hvis understøttelse nødforordninger skar ned; menneskene i kanten,',
        'som intet parti repræsenterede.',
        '',
        'Den er ligeværdig med den første stemme — at den her står sidst, er',
        'ingen rangorden, men blot den rækkefølge, der blev skrevet i. Og den',
        'har en fordel og en blind plet. Fordelen: Den kan fortælle, hvordan',
        'demokratiets ende føltes nedefra — ikke som en række beslutninger,',
        'men som en række dage, hvor verden blev snævrere. Den blinde plet:',
        'Denne stemme er tilbøjelig til at hvidvaske sin egen side. Også de',
        'forfulgte var ikke blot ofre uden egen andel — de var uenige, ofte',
        'blinde for faren, og nogle håndterede situationen på en måde, som de',
        'senere selv ikke forstod. Denne stemme nævner det, fordi det er sandt.',
        '',
        '## Hvad republikken først var for dem',
        '',
        'Den, der vil høre denne stemme, må først høre, hvad Weimarrepublikken',
        'var for dem, som den senere ikke beskyttede. For mange var den først',
        'en befrielse: Kvinders valgret fra 1919 gjaldt for alle,',
        'ligestillingen stod i loven, jøder var ligestillede borgere,',
        'fagforeningerne fik for første gang medbestemmelse, ottetimersdagen',
        'var forankret som mål. I de jødiske menigheder i Berlin og Frankfurt',
        'blomstrede et selvbevidst liv; jødiske tyskere var med overalt i',
        'videnskab, medicin, kunst og politik. Mange af dem følte sig i 1919',
        'for første gang virkelig som tyskere — og netop deri lå deres',
        'senere sårbarhed.',
        '',
        'Og denne stemme må nævne, hvad denne republik også var for dem: et',
        'demokrati, der behandlede sine fjender ulige. Et retsvæsen, der var',
        'blindt på det højre øje. Gadevolden i de tidlige år, som staten ofte',
        'først greb ind over for, når det var for sent. Hetzbladene, der år',
        'efter år skrev mod „jøderne", og som ingen forbød, fordi',
        'ytringsfriheden også gjaldt for had. Den, der i 1933 ville sige, at',
        'man ikke havde set det komme, havde ikke set efter.',
        '',
        '## Det eget ubekvemme sted: splittelsen',
        '',
        'Den hårdeste sandhed for denne stemme er den egne afmagt — og den',
        'egne indbyrdes strid. Venstrefløjen stillede i 1933 adskilt op, hvor',
        'den burde have stået sammen. KPD kaldte socialdemokraterne',
        '„socialfascister" og hovedfjenden til højre i stedet for til venstre;',
        'SPD holdt afstand til kommunisterne, hvis ledelse i Moskva kiggede',
        'mod Berlin. Da NSDAP i 1930 blev det næststærkeste parti,',
        'demonstrerede de to arbejderpartier hver for sig — og blev hver for',
        'sig slået. KPD håbede endnu i januar 1933, at Hitler ville slide på',
        '„bourgeoisiet"; SPD håbede på retsstaten, der ville beskytte den.',
        'Begge håb var fejl, og denne stemme nævner dem ved navn: Også de',
        'forfulgte undervurderede faren — ikke fordi de var dumme, men fordi',
        'de vurderede republikken efter sine egne regler og ikke efter',
        'reglerne hos dem, der ville afskaffe den.',
        '',
        'Og den må nævne et andet ubekvemt sted: antisemitismen, der ikke',
        'først begyndte med Hitler og ikke kun sad i SA-kasernerne. Den var',
        'hjemmehørende i embederne, på universiteterne, i foreningerne og i',
        'mange stuer, længe før 1933. Republiken gjorde lidt imod det — men',
        'også de demokratiske partier, også dele af arbejderbevægelsen,',
        'stillede sig sjældent højlydt imod. Da NSDAP i 1932 i mange',
        'middelstandskvarterer blev det stærkeste parti, var det ingen',
        'driftsulykke, men en konstatering.',
        '',
        '## 1933: de første hundrede dage',
        '',
        'Det, der skete efter den 30. januar 1933, skete hurtigt — hurtigere,',
        'end de fleste holdt for muligt. Allerede i natten efter',
        'rigsdagsbranden, den 28. februar 1933, blev tusindvis anholdt; de',
        'fleste af dem var kommunister. I marts 1933 opstod ved Dachau den',
        'første af de store koncentrationslejre, hvor i første omgang frem',
        'for alt politiske modstandere forsvandt — „til forbedring", som',
        'gerningsmændenes sprog lød. Den 1. april 1933 opfordrede SA til',
        'boykot af jødiske forretninger, læger og advokater; SA-poster stod',
        'foran butikkerne, mange kunder blev væk. Den 7. april 1933 blev',
        'jødiske og „politisk upålidelige" embedsmænd fjernet fra tjenesten.',
        'Den 2. maj 1933 blev fagforeningernes huse besat, deres kasser',
        'beslaglagt, deres ledere anholdt. Og den 10. maj 1933 brændte',
        'bøgerne på pladserne i universitetsbyerne — værker af Heinrich Mann,',
        'Erich Kästner, Sigmund Freud, Kurt Tucholsky, af Marx og brødrene',
        'Mann. Den, der så det på en af disse pladser, vidste præcis, hvad',
        'der brændte her: tanker.',
        '',
        'Denne stemme fortæller ikke disse dage som en talrække, men som det,',
        'de var: enkelte dage i enkelte menneskers liv. Dagen, hvor den',
        'jødiske læge fik at vide, at han ikke længere måtte praktisere på',
        'hospitalet. Dagen, hvor fagforeningsmanden fandt sin afdeling',
        'aflåst. Dagen, hvor barnet kom hjem fra skole og spurgte, hvorfor',
        'det ikke længere måtte være med i legen. Dagen, hvor nogen pakkede',
        'kufferten.',
        '',
        '## Emigrationen: at tage af sted eller blive',
        '',
        'Mellem 1933 og 1941 forlod omkring en halv million mennesker Det',
        'Tyske Rige — de fleste af dem jødiske tyskere. Forskere som Albert',
        'Einstein og brødrene Mann tog tidligt af sted; den, der blev, blev',
        'af de forskelligste grunde: af alder, af hensyn til pårørende, af',
        'håbet om, at det ville gå over, af troen på, at man ville „klare',
        'den". Denne stemme fordømmer ikke dem, der blev — den ved, hvor',
        'svært det var at forlade et liv. Men den nævner også illusionen',
        'deri: De fleste, der blev, kunne ikke vide, hvad der ville komme —',
        'og netop det gjorde deres beslutning så menneskelig og så tragisk.',
        'Udlandet tog længe ikke imod alle; mange, der ville af sted, fik',
        'ikke lov. Emigrationen var ingen ordnet eksodus, men en strøm af',
        'enkelte beslutninger under pres.',
        '',
        '## At forblive fair: de andre sider',
        '',
        'Denne stemme må også gengive de andre siders bevæggrunde fair,',
        'ellers forklarer den intet. Republikanerne, der havde bygget',
        'demokratiet, var ingen forrædere — den første stemme har selv nævnt',
        'deres fejl: forbundet med den gamle hær, nødforordningerne,',
        'undervurderingen af Hitler. Også de millioner, der i 1932 ikke',
        'valgte NSDAP, men af fortvivlelse eller ligegyldighed så væk, var',
        'ikke alle onde — mange var trætte, mange var bange, mange tænkte,',
        'det kun ramte andre. Og NSDAP-vælgerne: Den, der vil forstå, hvorfor',
        'mennesker valgte et parti, der åbent talte om udslettelse, må tage',
        'ydmygelsen i Versailles, inflationen og arbejdsløsheden alvorligt —',
        'uden at gøre det til en undskyldning. Gerningsmændene forbliver',
        'ansvarlige, også selv om man forstår deres motiver. Denne stemme',
        'drager netop denne linje: At forklare er ikke at undskylde.',
        '',
        '## Og den anden side?',
        '',
        'Det, denne stemme ikke kan fortælle, er den anden side af samme',
        'kapitel: hvordan republikken føltes ovenfra, hos dem, der byggede og',
        'forsvarede den — forhandlingerne, indrømmelserne, overvejelserne i',
        'kabinetterne, de fortvivlede forsøg på at forhindre det værste. Den',
        'første stemme i dette kapitel fortæller netop det, ærligere end',
        'mange erindringer gør. Først begge stemmer tilsammen giver billedet:',
        'et demokrati, som dets bygfolk mente oprigtigt, og som dets bygfolk',
        'selv var med til at beskadige — og mennesker, for hvem forskellen',
        'mellem et beskadiget demokrati og intet demokrati afgjorde liv og',
        'død.',
        '',
        '## Hvad der bliver',
        '',
        'Det, denne stemme til sidst kan sige, er enkelt: Det var ikke tal,',
        'der begyndte at vige i 1933, men mennesker med navne.',
        'Bogafbrændingen den 10. maj 1933 brændte værker, ikke forfattere —',
        'men forfatterne forlod landet eller forsvandt. Mindet om det første',
        'tyske demokrati tilhører begge stemmer: bygfolkene, der mente det',
        'oprigtigt, og de forfulgte, der betalte først. Og den lærdom fra',
        '1933, som denne stemme kan give med, er en enkel: Et demokrati',
        'måler sig på, hvordan det behandler dem, der står i kanten — for dem',
        'i kanten ser først, når det vælter.',
      ].join('\n'),
    },
  ],
  synthese: [
    'Til dette kapitel hører to stemmer, og begge taler nu. Den første',
    'fortæller Weimarrepublikken fra magtens midte — fra kabinetterne,',
    'nationalforsamlingen, redaktionerne og fagforeningshusene. Den anden',
    'fortæller det samme kapitel nedefra — fra gaderne, baggårdene og',
    'boligerne hos dem, som diktaturet ramte først. Begge er ligeværdige;',
    'hvilken der blev skrevet først, er ingen rangorden.',
    '',
    'Hvor de mødes: De bruger de samme fakta, de samme skilleveje —',
    'november 1918, Weimar 1919, inflationen 1923, nødforordningerne fra',
    '1930, den 20. juli 1932, den 30. januar 1933 —, og begge siger det',
    'samme om dette kapitels afgørende spørgsmål: Republiken blev ikke',
    'erobret, men tømt indefra, og den er også gået under på sine egne',
    'vogtere. Den første stemme nævner disse fejl selv — forbundet med den',
    'gamle hærledelse, frikorpsene, det urørte retsvæsen, at regere uden',
    'parlament, undervurderingen af Hitler, uenigheden hos dem, der ville',
    'forsvare den samme republik. Den anden stemme bekræfter det ud fra sin',
    'erfaring: Den, der nedefra så, hvordan republikken behandlede sine',
    'fjender ulige, vidste tidligere, at den ville vælte.',
    '',
    'Hvor de går fra hinanden, er målestokken. Den, der beslutter, regner i',
    'kabinetter, flertal og frister; den, der er berørt, regner i boliger,',
    'arbejdspladser og liv. For den ene side var republikken en bygning,',
    'som man måtte sikre mod storme; for den anden et tag, der ikke var tæt',
    'på afgørende steder — i 1919 ikke, i 1923 ikke, i 1930 ikke og i 1933',
    'slet ikke mere. Begge regnestykker bruger de samme tal og kommer til',
    'forskellige summer. Og de går også fra hinanden deri, hvad 1933',
    'betydede for dem: For nogle slutningen på en statsform, som de havde',
    'bygget; for andre begyndelsen på en forfølgelse, der begyndte med',
    'navne, ansigter og kufferter.',
    '',
    'Begge stemmer nævner deres egne ubekvemme steder — den første',
    'vogternes fejl, den anden de forfulgtes splittelse og antisemitismen,',
    'der var ældre end NSDAP. Og begge gengiver den anden sides',
    'bevæggrunde fair, uden at bagatellisere: Den første forklarer, hvorfor',
    'mennesker valgte Hitler; den anden forklarer, hvorfor republikanerne',
    'ikke kunne redde, hvad de havde bygget.',
    '',
    'Det, der bliver, er den lærdom, som begge bærer sammen: Et demokrati',
    'måler sig på, hvordan det behandler dem, der står i kanten — og det',
    'dør ikke af et enkelt slag, men af mange små indrømmelser, der hver',
    'for sig virker forståelige. Først begge stemmer tilsammen giver det',
    'hele billede; ingen af dem er „sådan var det".',
  ].join('\n'),

  urteil: {
    frage: 'Weimarrepublikken blev ikke erobret, men tømt indefra — med nødforordninger, som dens egne forsvarere besluttede, og med en udnævnelse, der var forfatningsmæssig. Hvad skulle et demokrati have gjort her, og hvordan kan man overhovedet kende, at et demokrati er i fare?',
    hinweis: 'Der er her ikke noget rigtigt eller forkert. En tanke til eftertanke: Nogle siger, at et demokrati må være kampdygtigt og om nødvendigt bekæmpe sine fjender med deres egne midler — andre anser netop det for det første skridt, med hvilket det afskaffer sig selv. Begge sider påberåber sig 1933. Hvad tænker du?',
  },

  quiz: [
    {
      frage: 'Hvorfor mødtes nationalforsamlingen i 1919 i Weimar og ikke i Berlin?',
      antworten: [
        'Fordi der fandt væbnede kampe sted i Berlin, og medlemmerne ville arbejde uforstyrret.',
        'Fordi Berlin dengang stadig var besat af franske tropper.',
        'Fordi forfatningen foreskrev, at parlamenter skal mødes uden for hovedstaden.',
      ],
      richtig: 0,
      erklaerung: 'I januar 1919 blev der kæmpet i Berlin. Weimar gjaldt som roligt og let at sikre — og navnet på Goethes og Schillers by skulle give den nye stat et andet ansigt end kasernernes.',
    },
    {
      frage: 'Hvad var nyt ved den tyske valgret i 1919?',
      antworten: [
        'For første gang måtte også kvinder vælge og vælges.',
        'For første gang måtte man vælge fra 16 år.',
        'For første gang blev regeringen valgt direkte af folket.',
      ],
      richtig: 0,
      erklaerung: 'Ved valget til nationalforsamlingen den 19. januar 1919 måtte mænd og kvinder fra 20 år vælge. 82 procent af de stemmeberettigede mødte op, 37 kvinder kom ind i parlamentet.',
    },
    {
      frage: 'Hvad regulerede artikel 48 i Weimar-forfatningen?',
      antworten: [
        'Den tillod rigspræsidenten at regere med forordninger i nødssituationer og sætte grundrettigheder ud af kraft.',
        'Den fastlagde, at rigsdagen genvælges hvert fjerde år.',
        'Den forbød partier, der afviste forfatningen.',
      ],
      richtig: 0,
      erklaerung: 'Artikel 48 var tænkt som et nødværktøj. Fra 1930 blev der regeret med den permanent: I 1932 udstedte rigspræsidenten 66 nødforordninger, mens rigsdagen kun trådte sammen 13 gange.',
    },
    {
      frage: 'Hvad bragte pengenes forringelse i 1923 helt ud af kontrol?',
      antworten: [
        'Riget betalte strejken mod Ruhrbesættelsen med nyprintede penge.',
        'De allierede krævede pludselig reparationerne i guld i stedet for i varer.',
        'Et jordskælv ødelagde rigsbanken i Berlin.',
      ],
      richtig: 0,
      erklaerung: 'Forringelsen løb siden krigsfinansieringen i 1914. Da riget i 1923 betalte lønningene for den passive modstand i det besatte Ruhr-område fra seddelpressen, styrtede den i hyperinflation. I november 1923 afsluttede rentenmarken den.',
    },
    {
      frage: 'Hvordan blev Adolf Hitler rigskansler den 30. januar 1933?',
      antworten: [
        'Rigspræsident Hindenburg udnævnte ham efter forhandlinger af konservative politikere.',
        'Hans parti havde vundet det absolutte flertal ved valget i november 1932.',
        'Rigsdagen valgte ham til kansler med to tredjedeles flertal.',
      ],
      richtig: 0,
      erklaerung: 'NSDAP opnåede aldrig et flertal ved et frit valg — i juli 1932 fik den 37,4 procent, i november 33,1. Hitler kom i embedet gennem rigspræsidentens udnævnelse, aftalt af konservative, der troede, de kunne ramme ham ind.',
    },
  ],

  karteHinweise: [
    {
      label: '1919',
      hinweis:
        'Nationalforsamlingen mødes i Weimar, fordi der på gaderne i Berlin kæmpes. Den 28. juni 1919 underskriver den tyske regering Versailles-traktaten, den 11. august udfærdiges forfatningen. Kortet viser de grænser, der fulgte deraf — nogle af dem blev først senere endeligt draget: Nordslesvig efter folkeafstemningen 1920, Øvreschlesien efter afstemningen i 1921 i 1922. Rhinlandet er besat, Saarområdet er underlagt Folkeforbundet, Danzig er fristad, Memelområdet afskilt. Daterede tilstande, uden vurdering — hvad man mener om dem, bestemmer ingen for dig.',
    },
    {
      label: '1924–1929',
      hinweis:
        'De samme grænser, en anden situation. Rentenmarken har afsluttet inflationen, Dawes-planen har ordnet reparationerne på ny, Locarno-traktaten fra 1925 har afspændt forholdet til Frankrig og Belgien; i 1926 bliver Tyskland medlem af Folkeforbundet. På kortet er deraf ét at se: Köln-zonen i nord af Rhinlandet er rømmet i januar 1926, det besatte område er altså blevet mindre. Memelområdet hører siden 1923/24 til Litauen. Berlin, Frankfurt og Dessau bliver i disse år adresser for kunst og videnskab.',
    },
    {
      label: '1933',
      hinweis:
        'Den 30. januar 1933 udnævner rigspræsident Hindenburg Adolf Hitler til rigskansler. Ved statsområdet er intet ændret siden 1919 — det sidste fremmede militær forlod Rhinlandet den 30. juni 1930, fem år tidligere end fastsat i traktaten, og derfor mangler den mørke flade i vest. Det, der har ændret sig, står ikke på landkortet, men i lovtidenderne: Siden 1930 er der regeret med nødforordninger, rigsdagen er blevet opløst tre gange, og i Preussen regerer siden juli 1932 en kommissær indsat af riget.',
    },
  ],
};
